ikfast::IkSolution< T > Class Template Reference
Default implementation of IkSolutionBase.
#include <ikfast.h>
Public Member Functions
IkSolution (const std::vector< IkSingleDOFSolutionBase< T > > &vinfos, const std::vector< int > &vfree)
virtual void GetSolution (T *solution, const T *freevalues) const
gets a concrete solution
virtual void GetSolution (std::vector< T > &solution, const std::vector< T > &freevalues) const
std::vector version of GetSolution
virtual const std::vector< int > & GetFree () const
Gets the indices of the configuration space that have to be preset before a full solution can be returned.
virtual int GetDOF () const
the dof of the solution
virtual void Validate () const
virtual void GetSolutionIndices (std::vector< unsigned int > &v) const
Public Attributes
std::vector< IkSingleDOFSolutionBase< T > > _vbasesol
solution and their offsets if joints are mimiced
std::vector< int > _vfree
Detailed Description
template<typename T>
class ikfast::IkSolution< T >
Default implementation of IkSolutionBase.
Definition at line 169 of file ikfast.h.
Constructor & Destructor Documentation
IkSolution()
template<typename T >
ikfast::IkSolution< T >::IkSolution (const std::vector< IkSingleDOFSolutionBase< T > > & vinfos, const std::vector< int > & vfree) [inline]
Definition at line 172 of file ikfast.h.
  {
    _vbasesol = vinfos;
    _vfree = vfree;
  }
References ikfast::IkSolution< T >::_vbasesol, and ikfast::IkSolution< T >::_vfree.
Member Function Documentation
GetDOF()
template<typename T >
virtual int ikfast::IkSolution< T >::GetDOF () const [inline], [virtual]
the dof of the solution
Implements ikfast::IkSolutionBase< T >.
Definition at line 209 of file ikfast.h.
  {
    return static_cast<int>(_vbasesol.size());
  }
References ikfast::IkSolution< T >::_vbasesol.
Referenced by ikfast::IkSolution< T >::GetSolution().
GetFree()
template<typename T >
virtual const std::vector<int>& ikfast::IkSolution< T >::GetFree () const [inline], [virtual]
Gets the indices of the configuration space that have to be preset before a full solution can be returned.
Returns
vector of indices indicating the free parameters
Implements ikfast::IkSolutionBase< T >.
Definition at line 205 of file ikfast.h.
  {
    return _vfree;
  }
References ikfast::IkSolution< T >::_vfree.
GetSolution() [1/2]
template<typename T >
virtual void ikfast::IkSolution< T >::GetSolution (std::vector< T > & solution, const std::vector< T > & freevalues) const [inline], [virtual]
std::vector version of GetSolution
Reimplemented from ikfast::IkSolutionBase< T >.
Definition at line 199 of file ikfast.h.
  {
    solution.resize(GetDOF());
    GetSolution(&solution.at(0), freevalues.size() > 0 ? &freevalues.at(0) : NULL);
  }
References ikfast::IkSolution< T >::GetDOF(), and ikfast::IkSolution< T >::GetSolution().
GetSolution() [2/2]
template<typename T >
virtual void ikfast::IkSolution< T >::GetSolution (T * solution, const T * freevalues) const [inline], [virtual]
gets a concrete solution
Parameters
 out solution the result
 in freevalues values for the free parameters \se GetFree
Implements ikfast::IkSolutionBase< T >.
Definition at line 178 of file ikfast.h.
  {
    for (std::size_t i = 0; i < _vbasesol.size(); ++i)
    {
      if (_vbasesol[i].freeind < 0)
        solution[i] = _vbasesol[i].foffset;
      else
      {
        solution[i] = freevalues[_vbasesol[i].freeind] * _vbasesol[i].fmul + _vbasesol[i].foffset;
        if (solution[i] > T(3.14159265358979))
        {
          solution[i] -= T(6.28318530717959);
        }
        else if (solution[i] < T(-3.14159265358979))
        {
          solution[i] += T(6.28318530717959);
        }
      }
    }
  }
References ikfast::IkSolution< T >::_vbasesol.
Referenced by ikfast::IkSolution< T >::GetSolution().
GetSolutionIndices()
template<typename T >
virtual void ikfast::IkSolution< T >::GetSolutionIndices (std::vector< unsigned int > & v) const [inline], [virtual]
Definition at line 236 of file ikfast.h.
  {
    v.resize(0);
    v.push_back(0);
    for (int i = (int)_vbasesol.size() - 1; i >= 0; --i)
    {
      if (_vbasesol[i].maxsolutions != (unsigned char)-1 && _vbasesol[i].maxsolutions > 1)
      {
        for (size_t j = 0; j < v.size(); ++j)
        {
          v[j] *= _vbasesol[i].maxsolutions;
        }
        size_t orgsize = v.size();
        if (_vbasesol[i].indices[1] != (unsigned char)-1)
        {
          for (size_t j = 0; j < orgsize; ++j)
          {
            v.push_back(v[j] + _vbasesol[i].indices[1]);
          }
        }
        if (_vbasesol[i].indices[0] != (unsigned char)-1)
        {
          for (size_t j = 0; j < orgsize; ++j)
          {
            v[j] += _vbasesol[i].indices[0];
          }
        }
      }
    }
  }
References ikfast::IkSolution< T >::_vbasesol.
Validate()
template<typename T >
virtual void ikfast::IkSolution< T >::Validate () const [inline], [virtual]
Definition at line 214 of file ikfast.h.
  {
    for (size_t i = 0; i < _vbasesol.size(); ++i)
    {
      if (_vbasesol[i].maxsolutions == (unsigned char)-1)
      {
        throw std::runtime_error("max solutions for joint not initialized");
      }
      if (_vbasesol[i].maxsolutions > 0)
      {
        if (_vbasesol[i].indices[0] >= _vbasesol[i].maxsolutions)
        {
          throw std::runtime_error("index >= max solutions for joint");
        }
        if (_vbasesol[i].indices[1] != (unsigned char)-1 && _vbasesol[i].indices[1] >= _vbasesol[i].maxsolutions)
        {
          throw std::runtime_error("2nd index >= max solutions for joint");
        }
      }
    }
  }
References ikfast::IkSolution< T >::_vbasesol.
Member Data Documentation
_vbasesol
template<typename T >
std::vector<IkSingleDOFSolutionBase<T> > ikfast::IkSolution< T >::_vbasesol
solution and their offsets if joints are mimiced
Definition at line 267 of file ikfast.h.
Referenced by ikfast::IkSolution< T >::GetDOF(), ikfast::IkSolution< T >::GetSolution(), ikfast::IkSolution< T >::GetSolutionIndices(), ikfast::IkSolution< T >::IkSolution(), and ikfast::IkSolution< T >::Validate().
_vfree
template<typename T >
std::vector<int> ikfast::IkSolution< T >::_vfree
Definition at line 268 of file ikfast.h.
Referenced by ikfast::IkSolution< T >::GetFree(), and ikfast::IkSolution< T >::IkSolution().
The documentation for this class was generated from the following file:
submodules/fetch_ros/fetch_ikfast_plugin/include/ikfast.h