fetch_arm::IKFastKinematicsPlugin Class Reference
Public Member Functions
IKFastKinematicsPlugin ()
bool getPositionIK (const geometry_msgs::Pose &ik_pose, const std::vector< double > &ik_seed_state, std::vector< double > &solution, moveit_msgs::MoveItErrorCodes &error_code, const kinematics::KinematicsQueryOptions &options=kinematics::KinematicsQueryOptions()) const override
Given a desired pose of the end-effector, compute the joint angles to reach it.
bool getPositionIK (const std::vector< geometry_msgs::Pose > &ik_poses, const std::vector< double > &ik_seed_state, std::vector< std::vector< double >> &solutions, kinematics::KinematicsResult &result, const kinematics::KinematicsQueryOptions &options) const override
Given a desired pose of the end-effector, compute the set joint angles solutions that are able to reach it.
bool searchPositionIK (const geometry_msgs::Pose &ik_pose, const std::vector< double > &ik_seed_state, double timeout, std::vector< double > &solution, moveit_msgs::MoveItErrorCodes &error_code, const kinematics::KinematicsQueryOptions &options=kinematics::KinematicsQueryOptions()) const override
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
bool searchPositionIK (const geometry_msgs::Pose &ik_pose, const std::vector< double > &ik_seed_state, double timeout, const std::vector< double > &consistency_limits, std::vector< double > &solution, moveit_msgs::MoveItErrorCodes &error_code, const kinematics::KinematicsQueryOptions &options=kinematics::KinematicsQueryOptions()) const override
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
bool searchPositionIK (const geometry_msgs::Pose &ik_pose, const std::vector< double > &ik_seed_state, double timeout, std::vector< double > &solution, const IKCallbackFn &solution_callback, moveit_msgs::MoveItErrorCodes &error_code, const kinematics::KinematicsQueryOptions &options=kinematics::KinematicsQueryOptions()) const override
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
bool searchPositionIK (const geometry_msgs::Pose &ik_pose, const std::vector< double > &ik_seed_state, double timeout, const std::vector< double > &consistency_limits, std::vector< double > &solution, const IKCallbackFn &solution_callback, moveit_msgs::MoveItErrorCodes &error_code, const kinematics::KinematicsQueryOptions &options=kinematics::KinematicsQueryOptions()) const override
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines). The consistency_limit specifies that only certain redundancy positions around those specified in the seed state are admissible and need to be searched.
bool getPositionFK (const std::vector< std::string > &link_names, const std::vector< double > &joint_angles, std::vector< geometry_msgs::Pose > &poses) const override
Given a set of joint angles and a set of links, compute their pose.
void setSearchDiscretization (const std::map< unsigned int, double > &discretization)
Sets the discretization value for the redundant joint.
bool setRedundantJoints (const std::vector< unsigned int > &redundant_joint_indices) override
Overrides the default method to prevent changing the redundant joints.
Private Member Functions
const std::vector< std::string > & getJointNames () const override
const std::vector< std::string > & getLinkNames () const override
bool initialize (const moveit::core::RobotModel &robot_model, const std::string &group_name, const std::string &base_frame, const std::vector< std::string > &tip_frames, double search_discretization) override
size_t solve (KDL::Frame &pose_frame, const std::vector< double > &vfree, IkSolutionList< IkReal > &solutions) const
Calls the IK solver from IKFast.
void getSolution (const IkSolutionList< IkReal > &solutions, int i, std::vector< double > &solution) const
Gets a specific solution from the set.
void getSolution (const IkSolutionList< IkReal > &solutions, const std::vector< double > &ik_seed_state, int i, std::vector< double > &solution) const
Gets a specific solution from the set with joints rotated 360° to be near seed state where possible.
double enforceLimits (double val, double min, double max) const
If the value is outside of min/max then it tries to +/- 2 * pi to put the value into the range.
void fillFreeParams (int count, int *array)
bool getCount (int &count, const int &max_count, const int &min_count) const
bool sampleRedundantJoint (kinematics::DiscretizationMethod method, std::vector< double > &sampled_joint_vals) const
samples the designated redundant joint using the chosen discretization method
bool computeRelativeTransform (const std::string &from, const std::string &to, Eigen::Isometry3d &transform, bool &differs_from_identity)
Validate that we can compute a fixed transform between from and to links.
void transformToChainFrame (const geometry_msgs::Pose &ik_pose, KDL::Frame &ik_pose_chain) const
Transforms the input pose to the correct frame for the solver. This assumes that the group includes the entire solver chain and that any joints outside of the solver chain within the group are are fixed.
Private Attributes
std::vector< std::string > joint_names_
std::vector< double > joint_min_vector_
std::vector< double > joint_max_vector_
std::vector< bool > joint_has_limits_vector_
std::vector< std::string > link_names_
const size_t num_joints_
std::vector< int > free_params_
const std::string IKFAST_TIP_FRAME_ = `wrist_roll_link`
const std::string IKFAST_BASE_FRAME_ = `torso_lift_link`
bool tip_transform_required_
bool base_transform_required_
Eigen::Isometry3d chain_base_to_group_base_
Eigen::Isometry3d group_tip_to_chain_tip_
bool initialized_
const std::string name_ { `ikfast` }
Detailed Description
Definition at line 154 of file fetch_arm_ikfast_moveit_plugin.cpp.
Constructor & Destructor Documentation
IKFastKinematicsPlugin()
fetch_arm::IKFastKinematicsPlugin::IKFastKinematicsPlugin () [inline]
Definition at line 197 of file fetch_arm_ikfast_moveit_plugin.cpp.
                           : num_joints_(GetNumJoints()), initialized_(false)
  {
    srand(time(nullptr));
    supported_methods_.push_back(kinematics::DiscretizationMethods::NO_DISCRETIZATION);
    supported_methods_.push_back(kinematics::DiscretizationMethods::ALL_DISCRETIZED);
    supported_methods_.push_back(kinematics::DiscretizationMethods::ALL_RANDOM_SAMPLED);
  }
Member Function Documentation
computeRelativeTransform()
bool fetch_arm::IKFastKinematicsPlugin::computeRelativeTransform (const std::string & from, const std::string & to, Eigen::Isometry3d & transform, bool & differs_from_identity) [private]
Validate that we can compute a fixed transform between from and to links.
Definition at line 373 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  RobotStatePtr robot_state;
  robot_state.reset(new RobotState(robot_model_));
  auto* from_link = robot_state->getLinkModel(from);
  auto* to_link = robot_state->getLinkModel(to);
  if (!from_link)
    ROS_ERROR_STREAM_NAMED(name_, "Could not find frame " << from);
  if (!to_link)
    ROS_ERROR_STREAM_NAMED(name_, "Could not find frame " << to);
  if (!from_link || !to_link)
    return false;
  if (robot_state->getRobotModel()->getRigidlyConnectedParentLinkModel(from_link) !=
      robot_state->getRobotModel()->getRigidlyConnectedParentLinkModel(to_link))
  {
    ROS_ERROR_STREAM_NAMED(name_, "Link frames " << from << " and " << to << " are not rigidly connected.");
    return false;
  }
  transform = robot_state->getGlobalLinkTransform(from_link).inverse() * robot_state->getGlobalLinkTransform(to_link);
  differs_from_identity = !transform.matrix().isIdentity();
  return true;
}
enforceLimits()
double fetch_arm::IKFastKinematicsPlugin::enforceLimits (double val, double min, double max) const [private]
If the value is outside of min/max then it tries to +/- 2 * pi to put the value into the range.
Definition at line 679 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  // If the joint_value is greater than max subtract 2 * PI until it is less than the max
  while (joint_value > max)
  {
    joint_value -= 2 * M_PI;
  }
  // If the joint_value is less than the min, add 2 * PI until it is more than the min
  while (joint_value < min)
  {
    joint_value += 2 * M_PI;
  }
  return joint_value;
}
fillFreeParams()
void fetch_arm::IKFastKinematicsPlugin::fillFreeParams (int count, int * array) [private]
Definition at line 695 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  free_params_.clear();
  for (int i = 0; i < count; ++i)
    free_params_.push_back(array[i]);
}
References sm_fetch_two_table_whiskey_pour::count.
getCount()
bool fetch_arm::IKFastKinematicsPlugin::getCount (int & count, const int & max_count, const int & min_count) const [private]
Definition at line 702 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  if (count > 0)
  {
    if (-count >= min_count)
    {
      count = -count;
      return true;
    }
    else if (count + 1 <= max_count)
    {
      count = count + 1;
      return true;
    }
    else
    {
      return false;
    }
  }
  else
  {
    if (1 - count <= max_count)
    {
      count = 1 - count;
      return true;
    }
    else if (count - 1 >= min_count)
    {
      count = count - 1;
      return true;
    }
    else
      return false;
  }
}
References sm_fetch_two_table_whiskey_pour::count.
getJointNames()
const std::vector<std::string>& fetch_arm::IKFastKinematicsPlugin::getJointNames () const [inline], [override], [private]
Definition at line 184 of file fetch_arm_ikfast_moveit_plugin.cpp.
  {
    return joint_names_;
  }
getLinkNames()
const std::vector<std::string>& fetch_arm::IKFastKinematicsPlugin::getLinkNames () const [inline], [override], [private]
Definition at line 188 of file fetch_arm_ikfast_moveit_plugin.cpp.
  {
    return link_names_;
  }
getPositionFK()
bool fetch_arm::IKFastKinematicsPlugin::getPositionFK (const std::vector< std::string > & link_names, const std::vector< double > & joint_angles, std::vector< geometry_msgs::Pose > & poses) const [override]
Given a set of joint angles and a set of links, compute their pose.
Parameters
link_names A set of links for which FK needs to be computed
joint_angles The state for which FK is being computed
poses The resultant set of poses (in the frame returned by getBaseFrame())
Returns
True if a valid solution was found, false otherwise
Definition at line 738 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  if (GetIkType() != IKP_Transform6D)
  {
    // ComputeFk() is the inverse function of ComputeIk(), so the format of
    // eerot differs depending on IK type. The Transform6D IK type is the only
    // one for which a 3x3 rotation matrix is returned, which means we can only
    // compute FK for that IK type.
    ROS_ERROR_NAMED(name_, "Can only compute FK for Transform6D IK type!");
    return false;
  }
  KDL::Frame p_out;
  if (link_names.size() == 0)
  {
    ROS_WARN_STREAM_NAMED(name_, "Link names with nothing");
    return false;
  }
  if (link_names.size() != 1 || link_names[0] != getTipFrame())
  {
    ROS_ERROR_NAMED(name_, "Can compute FK for %s only", getTipFrame().c_str());
    return false;
  }
  bool valid = true;
  IkReal eerot[9], eetrans[3];
  if (joint_angles.size() != num_joints_)
  {
    ROS_ERROR_NAMED(name_, "Unexpected number of joint angles");
    return false;
  }
  IkReal angles[num_joints_];
  for (unsigned char i = 0; i < num_joints_; i++)
    angles[i] = joint_angles[i];
  // IKFast56/61
  ComputeFk(angles, eetrans, eerot);
  for (int i = 0; i < 3; ++i)
    p_out.p.data[i] = eetrans[i];
  for (int i = 0; i < 9; ++i)
    p_out.M.data[i] = eerot[i];
  poses.resize(1);
  poses[0] = tf2::toMsg(p_out);
  return valid;
}
References ComputeFk(), GetIkType(), and fetch_arm::IKP_Transform6D.
getPositionIK() [1/2]
bool fetch_arm::IKFastKinematicsPlugin::getPositionIK (const geometry_msgs::Pose & ik_pose, const std::vector< double > & ik_seed_state, std::vector< double > & solution, moveit_msgs::MoveItErrorCodes & error_code, const kinematics::KinematicsQueryOptions & options = kinematics::KinematicsQueryOptions()) const [override]
Given a desired pose of the end-effector, compute the joint angles to reach it.
Parameters
ik_pose the desired pose of the link
ik_seed_state an initial guess solution for the inverse kinematics
solution the solution vector
error_code an error code that encodes the reason for failure or success
Returns
True if a valid solution was found, false otherwise
Definition at line 1056 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  ROS_DEBUG_STREAM_NAMED(name_, "getPositionIK");
  if (!initialized_)
  {
    ROS_ERROR_NAMED(name_, "kinematics not active");
    return false;
  }
  if (ik_seed_state.size() < num_joints_)
  {
    ROS_ERROR_STREAM_NAMED(name_, "ik_seed_state only has " << ik_seed_state.size()
                                                            << " entries, this ikfast solver requires " << num_joints_);
    return false;
  }
  // Check if seed is in bound
  for (std::size_t i = 0; i < ik_seed_state.size(); i++)
  {
    // Add tolerance to limit check
    if (joint_has_limits_vector_[i] && ((ik_seed_state[i] < (joint_min_vector_[i] - LIMIT_TOLERANCE)) ||
                                        (ik_seed_state[i] > (joint_max_vector_[i] + LIMIT_TOLERANCE))))
    {
      ROS_DEBUG_STREAM_NAMED(name_, "IK seed not in limits! " << static_cast<int>(i) << " value " << ik_seed_state[i]
                                                              << " has limit: " << joint_has_limits_vector_[i]
                                                              << " being " << joint_min_vector_[i] << " to "
                                                              << joint_max_vector_[i]);
      return false;
    }
  }
  std::vector<double> vfree(free_params_.size());
  for (std::size_t i = 0; i < free_params_.size(); ++i)
  {
    int p = free_params_[i];
    ROS_ERROR("%u is %f", p, ik_seed_state[p]); // DTC
    vfree[i] = ik_seed_state[p];
  }
  KDL::Frame frame;
  transformToChainFrame(ik_pose, frame);
  IkSolutionList<IkReal> solutions;
  size_t numsol = solve(frame, vfree, solutions);
  ROS_DEBUG_STREAM_NAMED(name_, "Found " << numsol << " solutions from IKFast");
  std::vector<LimitObeyingSol> solutions_obey_limits;
  if (numsol)
  {
    std::vector<double> solution_obey_limits;
    for (std::size_t s = 0; s < numsol; ++s)
    {
      std::vector<double> sol;
      getSolution(solutions, ik_seed_state, s, sol);
      ROS_DEBUG_NAMED(name_, "Sol %d: %e %e %e %e %e %e", static_cast<int>(s), sol[0], sol[1], sol[2], sol[3],
                      sol[4], sol[5]);
      bool obeys_limits = true;
      for (std::size_t i = 0; i < sol.size(); i++)
      {
        // Add tolerance to limit check
        if (joint_has_limits_vector_[i] && ((sol[i] < (joint_min_vector_[i] - LIMIT_TOLERANCE)) ||
                                            (sol[i] > (joint_max_vector_[i] + LIMIT_TOLERANCE))))
        {
          // One element of solution is not within limits
          obeys_limits = false;
          ROS_DEBUG_STREAM_NAMED(name_, "Not in limits! " << static_cast<int>(i) << " value " << sol[i]
                                                          << " has limit: " << joint_has_limits_vector_[i]
                                                          << " being " << joint_min_vector_[i] << " to "
                                                          << joint_max_vector_[i]);
          break;
        }
      }
      if (obeys_limits)
      {
        // All elements of this solution obey limits
        getSolution(solutions, ik_seed_state, s, solution_obey_limits);
        double dist_from_seed = 0.0;
        for (std::size_t i = 0; i < ik_seed_state.size(); ++i)
        {
          dist_from_seed += fabs(ik_seed_state[i] - solution_obey_limits[i]);
        }
        solutions_obey_limits.push_back({ solution_obey_limits, dist_from_seed });
      }
    }
  }
  else
  {
    ROS_DEBUG_STREAM_NAMED(name_, "No IK solution");
  }
  // Sort the solutions under limits and find the one that is closest to ik_seed_state
  if (!solutions_obey_limits.empty())
  {
    std::sort(solutions_obey_limits.begin(), solutions_obey_limits.end());
    solution = solutions_obey_limits[0].value;
    error_code.val = moveit_msgs::MoveItErrorCodes::SUCCESS;
    return true;
  }
  error_code.val = moveit_msgs::MoveItErrorCodes::NO_IK_SOLUTION;
  return false;
}
References LIMIT_TOLERANCE, and service_node_3::s.
getPositionIK() [2/2]
bool fetch_arm::IKFastKinematicsPlugin::getPositionIK (const std::vector< geometry_msgs::Pose > & ik_poses, const std::vector< double > & ik_seed_state, std::vector< std::vector< double >> & solutions, kinematics::KinematicsResult & result, const kinematics::KinematicsQueryOptions & options) const [override]
Given a desired pose of the end-effector, compute the set joint angles solutions that are able to reach it.
This is a default implementation that returns only one solution and so its result is equivalent to calling 'getPositionIK(...)' with a zero initialized seed.
Parameters
ik_poses The desired pose of each tip link
ik_seed_state an initial guess solution for the inverse kinematics
solutions A vector of vectors where each entry is a valid joint solution
result A struct that reports the results of the query
options An option struct which contains the type of redundancy discretization used. This default implementation only supports the KinmaticSearches::NO_DISCRETIZATION method; requesting any other will result in failure.
Returns
True if a valid set of solutions was found, false otherwise.
Definition at line 1165 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  ROS_DEBUG_STREAM_NAMED(name_, "getPositionIK with multiple solutions");
  if (!initialized_)
  {
    ROS_ERROR_NAMED(name_, "kinematics not active");
    result.kinematic_error = kinematics::KinematicErrors::SOLVER_NOT_ACTIVE;
    return false;
  }
  if (ik_poses.empty())
  {
    ROS_ERROR_NAMED(name_, "ik_poses is empty");
    result.kinematic_error = kinematics::KinematicErrors::EMPTY_TIP_POSES;
    return false;
  }
  if (ik_poses.size() > 1)
  {
    ROS_ERROR_NAMED(name_, "ik_poses contains multiple entries, only one is allowed");
    result.kinematic_error = kinematics::KinematicErrors::MULTIPLE_TIPS_NOT_SUPPORTED;
    return false;
  }
  if (ik_seed_state.size() < num_joints_)
  {
    ROS_ERROR_STREAM_NAMED(name_, "ik_seed_state only has " << ik_seed_state.size()
                                                            << " entries, this ikfast solver requires " << num_joints_);
    return false;
  }
  KDL::Frame frame;
  transformToChainFrame(ik_poses[0], frame);
  // solving ik
  std::vector<IkSolutionList<IkReal>> solution_set;
  IkSolutionList<IkReal> ik_solutions;
  std::vector<double> vfree;
  int numsol = 0;
  std::vector<double> sampled_joint_vals;
  if (!redundant_joint_indices_.empty())
  {
    // initializing from seed
    sampled_joint_vals.push_back(ik_seed_state[redundant_joint_indices_[0]]);
    // checking joint limits when using no discretization
    if (options.discretization_method == kinematics::DiscretizationMethods::NO_DISCRETIZATION &&
        joint_has_limits_vector_[redundant_joint_indices_.front()])
    {
      double joint_min = joint_min_vector_[redundant_joint_indices_.front()];
      double joint_max = joint_max_vector_[redundant_joint_indices_.front()];
      double jv = sampled_joint_vals[0];
      if (!((jv > (joint_min - LIMIT_TOLERANCE)) && (jv < (joint_max + LIMIT_TOLERANCE))))
      {
        result.kinematic_error = kinematics::KinematicErrors::IK_SEED_OUTSIDE_LIMITS;
        ROS_ERROR_STREAM_NAMED(name_, "ik seed is out of bounds");
        return false;
      }
    }
    // computing all solutions sets for each sampled value of the redundant joint
    if (!sampleRedundantJoint(options.discretization_method, sampled_joint_vals))
    {
      result.kinematic_error = kinematics::KinematicErrors::UNSUPORTED_DISCRETIZATION_REQUESTED;
      return false;
    }
    for (unsigned int i = 0; i < sampled_joint_vals.size(); i++)
    {
      vfree.clear();
      vfree.push_back(sampled_joint_vals[i]);
      numsol += solve(frame, vfree, ik_solutions);
      solution_set.push_back(ik_solutions);
    }
  }
  else
  {
    // computing for single solution set
    numsol = solve(frame, vfree, ik_solutions);
    solution_set.push_back(ik_solutions);
  }
  ROS_DEBUG_STREAM_NAMED(name_, "Found " << numsol << " solutions from IKFast");
  bool solutions_found = false;
  if (numsol > 0)
  {
    /*
      Iterating through all solution sets and storing those that do not exceed joint limits.
    */
    for (unsigned int r = 0; r < solution_set.size(); r++)
    {
      ik_solutions = solution_set[r];
      numsol = ik_solutions.GetNumSolutions();
      for (int s = 0; s < numsol; ++s)
      {
        std::vector<double> sol;
        getSolution(ik_solutions, ik_seed_state, s, sol);
        bool obeys_limits = true;
        for (unsigned int i = 0; i < sol.size(); i++)
        {
          // Add tolerance to limit check
          if (joint_has_limits_vector_[i] && ((sol[i] < (joint_min_vector_[i] - LIMIT_TOLERANCE)) ||
                                              (sol[i] > (joint_max_vector_[i] + LIMIT_TOLERANCE))))
          {
            // One element of solution is not within limits
            obeys_limits = false;
            ROS_DEBUG_STREAM_NAMED(name_, "Not in limits! " << i << " value " << sol[i] << " has limit: "
                                                            << joint_has_limits_vector_[i] << " being "
                                                            << joint_min_vector_[i] << " to " << joint_max_vector_[i]);
            break;
          }
        }
        if (obeys_limits)
        {
          // All elements of solution obey limits
          solutions_found = true;
          solutions.push_back(sol);
        }
      }
    }
    if (solutions_found)
    {
      result.kinematic_error = kinematics::KinematicErrors::OK;
      return true;
    }
  }
  else
  {
    ROS_DEBUG_STREAM_NAMED(name_, "No IK solution");
  }
  result.kinematic_error = kinematics::KinematicErrors::NO_SOLUTION;
  return false;
}
References ikfast::IkSolutionList< T >::GetNumSolutions(), LIMIT_TOLERANCE, fake_cube_perception_node::r, sick_camera_client::result, and service_node_3::s.
getSolution() [1/2]
void fetch_arm::IKFastKinematicsPlugin::getSolution (const IkSolutionList< IkReal > & solutions, const std::vector< double > & ik_seed_state, int i, std::vector< double > & solution) const [private]
Gets a specific solution from the set with joints rotated 360° to be near seed state where possible.
Definition at line 646 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  solution.clear();
  solution.resize(num_joints_);
  // IKFast56/61
  const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
  std::vector<IkReal> vsolfree(sol.GetFree().size());
  sol.GetSolution(&solution[0], vsolfree.size() > 0 ? &vsolfree[0] : nullptr);
  // rotate joints by +/-360° where it is possible and useful
  for (std::size_t i = 0; i < num_joints_; ++i)
  {
    if (joint_has_limits_vector_[i])
    {
      solution[i] = enforceLimits(solution[i], joint_min_vector_[i], joint_max_vector_[i]);
      double signed_distance = solution[i] - ik_seed_state[i];
      while (signed_distance > M_PI && solution[i] - 2 * M_PI > (joint_min_vector_[i] - LIMIT_TOLERANCE))
      {
        signed_distance -= 2 * M_PI;
        solution[i] -= 2 * M_PI;
      }
      while (signed_distance < -M_PI && solution[i] + 2 * M_PI < (joint_max_vector_[i] + LIMIT_TOLERANCE))
      {
        signed_distance += 2 * M_PI;
        solution[i] += 2 * M_PI;
      }
    }
  }
}
References ikfast::IkSolutionBase< T >::GetFree(), ikfast::IkSolutionBase< T >::GetSolution(), ikfast::IkSolutionList< T >::GetSolution(), and LIMIT_TOLERANCE.
getSolution() [2/2]
void fetch_arm::IKFastKinematicsPlugin::getSolution (const IkSolutionList< IkReal > & solutions, int i, std::vector< double > & solution) const [private]
Gets a specific solution from the set.
Definition at line 626 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  solution.clear();
  solution.resize(num_joints_);
  // IKFast56/61
  const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
  std::vector<IkReal> vsolfree(sol.GetFree().size());
  sol.GetSolution(&solution[0], vsolfree.size() > 0 ? &vsolfree[0] : nullptr);
  for (std::size_t joint_id = 0; joint_id < num_joints_; ++joint_id)
  {
    if (joint_has_limits_vector_[joint_id])
    {
      solution[joint_id] = enforceLimits(solution[joint_id], joint_min_vector_[joint_id], joint_max_vector_[joint_id]);
    }
  }
}
References ikfast::IkSolutionBase< T >::GetFree(), ikfast::IkSolutionBase< T >::GetSolution(), and ikfast::IkSolutionList< T >::GetSolution().
initialize()
bool fetch_arm::IKFastKinematicsPlugin::initialize (const moveit::core::RobotModel & robot_model, const std::string & group_name, const std::string & base_frame, const std::vector< std::string > & tip_frames, double search_discretization) [override], [private]
Definition at line 400 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  if (tip_frames.size() != 1)
  {
    ROS_ERROR_NAMED(name_, "Expecting exactly one tip frame.");
    return false;
  }
  storeValues(robot_model, group_name, base_frame, tip_frames, search_discretization);
  // This IKFast solution was generated with IKFAST_TIP_FRAME_ and IKFAST_BASE_FRAME_.
  // It is often the case that fixed joints are added to these links to model things like
  // a robot mounted on a table or a robot with an end effector attached to the last link.
  // To support these use cases, we store the transform from the IKFAST_BASE_FRAME_ to the
  // base_frame_ and IKFAST_TIP_FRAME_ the tip_frame_ and transform to the input pose accordingly
  if (!computeRelativeTransform(tip_frames_[0], IKFAST_TIP_FRAME_, group_tip_to_chain_tip_, tip_transform_required_) ||
      !computeRelativeTransform(IKFAST_BASE_FRAME_, base_frame_, chain_base_to_group_base_, base_transform_required_))
    return false;
  // IKFast56/61
  fillFreeParams(GetNumFreeParameters(), GetFreeParameters());
  if (free_params_.size() > 1)
  {
    ROS_ERROR_NAMED(name_, "Only one free joint parameter supported!");
    return false;
  }
  else if (free_params_.size() == 1)
  {
    redundant_joint_indices_.clear();
    redundant_joint_indices_.push_back(free_params_[0]);
    KinematicsBase::setSearchDiscretization(search_discretization);
  }
  const moveit::core::JointModelGroup* jmg = robot_model_->getJointModelGroup(group_name);
  if (!jmg)
  {
    ROS_ERROR_STREAM_NAMED(name_, "Unknown planning group: " << group_name);
    return false;
  }
  ROS_DEBUG_STREAM_NAMED(name_, "Registering joints and links");
  const moveit::core::LinkModel* link = robot_model_->getLinkModel(tip_frames_[0]);
  const moveit::core::LinkModel* base_link = robot_model_->getLinkModel(base_frame_);
  while (link && link != base_link)
  {
    ROS_DEBUG_STREAM_NAMED(name_, "Link " << link->getName());
    link_names_.push_back(link->getName());
    const moveit::core::JointModel* joint = link->getParentJointModel();
    if (joint->getType() != joint->UNKNOWN && joint->getType() != joint->FIXED && joint->getVariableCount() == 1)
    {
      ROS_DEBUG_STREAM_NAMED(name_, "Adding joint " << joint->getName());
      joint_names_.push_back(joint->getName());
      const moveit::core::VariableBounds& bounds = joint->getVariableBounds()[0];
      joint_has_limits_vector_.push_back(bounds.position_bounded_);
      joint_min_vector_.push_back(bounds.min_position_);
      joint_max_vector_.push_back(bounds.max_position_);
    }
    link = link->getParentLinkModel();
  }
  if (joint_names_.size() != num_joints_)
  {
    ROS_FATAL_NAMED(name_, "Joint numbers of RobotModel (%zd) and IKFast solver (%zd) do not match",
                    joint_names_.size(), num_joints_);
    return false;
  }
  std::reverse(link_names_.begin(), link_names_.end());
  std::reverse(joint_names_.begin(), joint_names_.end());
  std::reverse(joint_min_vector_.begin(), joint_min_vector_.end());
  std::reverse(joint_max_vector_.begin(), joint_max_vector_.end());
  std::reverse(joint_has_limits_vector_.begin(), joint_has_limits_vector_.end());
  for (size_t joint_id = 0; joint_id < num_joints_; ++joint_id)
    ROS_DEBUG_STREAM_NAMED(name_, joint_names_[joint_id] << " " << joint_min_vector_[joint_id] << " "
                                                         << joint_max_vector_[joint_id] << " "
                                                         << joint_has_limits_vector_[joint_id]);
  initialized_ = true;
  return true;
}
References GetFreeParameters(), and GetNumFreeParameters().
sampleRedundantJoint()
bool fetch_arm::IKFastKinematicsPlugin::sampleRedundantJoint (kinematics::DiscretizationMethod method, std::vector< double > & sampled_joint_vals) const [private]
samples the designated redundant joint using the chosen discretization method
Parameters
method An enumeration flag indicating the discretization method to be used
sampled_joint_vals Sampled joint values for the redundant joint
Returns
True if sampling succeeded.
Definition at line 1308 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  int index = redundant_joint_indices_.front();
  double joint_dscrt = redundant_joint_discretization_.at(index);
  double joint_min = joint_min_vector_[index];
  double joint_max = joint_max_vector_[index];
  switch (method)
  {
    case kinematics::DiscretizationMethods::ALL_DISCRETIZED:
    {
      size_t steps = std::ceil((joint_max - joint_min) / joint_dscrt);
      for (size_t i = 0; i < steps; i++)
      {
        sampled_joint_vals.push_back(joint_min + joint_dscrt * i);
      }
      sampled_joint_vals.push_back(joint_max);
    }
    break;
    case kinematics::DiscretizationMethods::ALL_RANDOM_SAMPLED:
    {
      int steps = std::ceil((joint_max - joint_min) / joint_dscrt);
      steps = steps > 0 ? steps : 1;
      double diff = joint_max - joint_min;
      for (int i = 0; i < steps; i++)
      {
        sampled_joint_vals.push_back(((diff * std::rand()) / (static_cast<double>(RAND_MAX))) + joint_min);
      }
    }
    break;
    case kinematics::DiscretizationMethods::NO_DISCRETIZATION:
      break;
    default:
      ROS_ERROR_STREAM_NAMED(name_, "Discretization method " << method << " is not supported");
      return false;
  }
  return true;
}
searchPositionIK() [1/4]
bool fetch_arm::IKFastKinematicsPlugin::searchPositionIK (const geometry_msgs::Pose & ik_pose, const std::vector< double > & ik_seed_state, double timeout, const std::vector< double > & consistency_limits, std::vector< double > & solution, const IKCallbackFn & solution_callback, moveit_msgs::MoveItErrorCodes & error_code, const kinematics::KinematicsQueryOptions & options = kinematics::KinematicsQueryOptions()) const [override]
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines). The consistency_limit specifies that only certain redundancy positions around those specified in the seed state are admissible and need to be searched.
Parameters
ik_pose the desired pose of the link
ik_seed_state an initial guess solution for the inverse kinematics
consistency_limit the distance that the redundancy can be from the current position
Returns
True if a valid solution was found, false otherwise
Definition at line 825 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  // "SEARCH_MODE" is fixed during code generation
  SEARCH_MODE search_mode = OPTIMIZE_MAX_JOINT;
  // Check if there are no redundant joints
  if (free_params_.size() == 0)
  {
    ROS_DEBUG_STREAM_NAMED(name_, "No need to search since no free params/redundant joints");
    std::vector<geometry_msgs::Pose> ik_poses(1, ik_pose);
    std::vector<std::vector<double>> solutions;
    kinematics::KinematicsResult kinematic_result;
    // Find all IK solutions within joint limits
    if (!getPositionIK(ik_poses, ik_seed_state, solutions, kinematic_result, options))
    {
      ROS_DEBUG_STREAM_NAMED(name_, "No solution whatsoever");
      error_code.val = moveit_msgs::MoveItErrorCodes::NO_IK_SOLUTION;
      return false;
    }
    // sort solutions by their distance to the seed
    std::vector<LimitObeyingSol> solutions_obey_limits;
    for (std::size_t i = 0; i < solutions.size(); ++i)
    {
      double dist_from_seed = 0.0;
      for (std::size_t j = 0; j < ik_seed_state.size(); ++j)
      {
        dist_from_seed += fabs(ik_seed_state[j] - solutions[i][j]);
      }
      solutions_obey_limits.push_back({ solutions[i], dist_from_seed });
    }
    std::sort(solutions_obey_limits.begin(), solutions_obey_limits.end());
    // check for collisions if a callback is provided
    if (!solution_callback.empty())
    {
      for (std::size_t i = 0; i < solutions_obey_limits.size(); ++i)
      {
        solution_callback(ik_pose, solutions_obey_limits[i].value, error_code);
        if (error_code.val == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
          solution = solutions_obey_limits[i].value;
          ROS_DEBUG_STREAM_NAMED(name_, "Solution passes callback");
          return true;
        }
      }
      ROS_DEBUG_STREAM_NAMED(name_, "Solution has error code " << error_code);
      return false;
    }
    else
    {
      solution = solutions_obey_limits[0].value;
      error_code.val = moveit_msgs::MoveItErrorCodes::SUCCESS;
      return true; // no collision check callback provided
    }
  }
  // -------------------------------------------------------------------------------------------------
  // Error Checking
  if (!initialized_)
  {
    ROS_ERROR_STREAM_NAMED(name_, "Kinematics not active");
    error_code.val = error_code.NO_IK_SOLUTION;
    return false;
  }
  if (ik_seed_state.size() != num_joints_)
  {
    ROS_ERROR_STREAM_NAMED(name_, "Seed state must have size " << num_joints_ << " instead of size "
                                                               << ik_seed_state.size());
    error_code.val = error_code.NO_IK_SOLUTION;
    return false;
  }
  if (!consistency_limits.empty() && consistency_limits.size() != num_joints_)
  {
    ROS_ERROR_STREAM_NAMED(name_, "Consistency limits be empty or must have size " << num_joints_ << " instead of size "
                                                                                   << consistency_limits.size());
    error_code.val = error_code.NO_IK_SOLUTION;
    return false;
  }
  // -------------------------------------------------------------------------------------------------
  // Initialize
  KDL::Frame frame;
  transformToChainFrame(ik_pose, frame);
  std::vector<double> vfree(free_params_.size());
  int counter = 0;
  double initial_guess = ik_seed_state[free_params_[0]];
  vfree[0] = initial_guess;
  // -------------------------------------------------------------------------------------------------
  // Handle consitency limits if needed
  int num_positive_increments;
  int num_negative_increments;
  double search_discretization = redundant_joint_discretization_.at(free_params_[0]);
  if (!consistency_limits.empty())
  {
    // MoveIt! replaced consistency_limit (scalar) w/ consistency_limits (vector)
    // Assume [0]th free_params element for now. Probably wrong.
    double max_limit = fmin(joint_max_vector_[free_params_[0]], initial_guess + consistency_limits[free_params_[0]]);
    double min_limit = fmax(joint_min_vector_[free_params_[0]], initial_guess - consistency_limits[free_params_[0]]);
    num_positive_increments = static_cast<int>((max_limit - initial_guess) / search_discretization);
    num_negative_increments = static_cast<int>((initial_guess - min_limit) / search_discretization);
  }
  else // no consistency limits provided
  {
    num_positive_increments = (joint_max_vector_[free_params_[0]] - initial_guess) / search_discretization;
    num_negative_increments = (initial_guess - joint_min_vector_[free_params_[0]]) / search_discretization;
  }
  // -------------------------------------------------------------------------------------------------
  // Begin searching
  ROS_DEBUG_STREAM_NAMED(name_, "Free param is " << free_params_[0] << " initial guess is " << initial_guess
                                                 << ", # positive increments: " << num_positive_increments
                                                 << ", # negative increments: " << num_negative_increments);
  if ((search_mode & OPTIMIZE_MAX_JOINT) && (num_positive_increments + num_negative_increments) > 1000)
    ROS_WARN_STREAM_ONCE_NAMED(name_, "Large search space, consider increasing the search discretization");
  double best_costs = -1.0;
  std::vector<double> best_solution;
  int nattempts = 0, nvalid = 0;
  while (true)
  {
    IkSolutionList<IkReal> solutions;
    size_t numsol = solve(frame, vfree, solutions);
    ROS_DEBUG_STREAM_NAMED(name_, "Found " << numsol << " solutions from IKFast");
    if (numsol > 0)
    {
      for (size_t s = 0; s < numsol; ++s)
      {
        nattempts++;
        std::vector<double> sol;
        getSolution(solutions, ik_seed_state, s, sol);
        bool obeys_limits = true;
        for (size_t i = 0; i < sol.size(); i++)
        {
          if (joint_has_limits_vector_[i] && (sol[i] < joint_min_vector_[i] || sol[i] > joint_max_vector_[i]))
          {
            obeys_limits = false;
            break;
          }
          // ROS_INFO_STREAM_NAMED(name_,"Num " << i << " value " << sol[i] << " has limits " <<
          // joint_has_limits_vector_[i] << " " << joint_min_vector_[i] << " " << joint_max_vector_[i]);
        }
        if (obeys_limits)
        {
          getSolution(solutions, ik_seed_state, s, solution);
          // This solution is within joint limits, now check if in collision (if callback provided)
          if (!solution_callback.empty())
          {
            solution_callback(ik_pose, solution, error_code);
          }
          else
          {
            error_code.val = error_code.SUCCESS;
          }
          if (error_code.val == error_code.SUCCESS)
          {
            nvalid++;
            if (search_mode & OPTIMIZE_MAX_JOINT)
            {
              // Costs for solution: Largest joint motion
              double costs = 0.0;
              for (unsigned int i = 0; i < solution.size(); i++)
              {
                double d = fabs(ik_seed_state[i] - solution[i]);
                if (d > costs)
                  costs = d;
              }
              if (costs < best_costs || best_costs == -1.0)
              {
                best_costs = costs;
                best_solution = solution;
              }
            }
            else
              // Return first feasible solution
              return true;
          }
        }
      }
    }
    if (!getCount(counter, num_positive_increments, -num_negative_increments))
    {
      // Everything searched
      error_code.val = moveit_msgs::MoveItErrorCodes::NO_IK_SOLUTION;
      break;
    }
    vfree[0] = initial_guess + search_discretization * counter;
    // ROS_DEBUG_STREAM_NAMED(name_,"Attempt " << counter << " with 0th free joint having value " << vfree[0]);
  }
  ROS_DEBUG_STREAM_NAMED(name_, "Valid solutions: " << nvalid << "/" << nattempts);
  if ((search_mode & OPTIMIZE_MAX_JOINT) && best_costs != -1.0)
  {
    solution = best_solution;
    error_code.val = error_code.SUCCESS;
    return true;
  }
  // No solution found
  error_code.val = moveit_msgs::MoveItErrorCodes::NO_IK_SOLUTION;
  return false;
}
References setup::d, OPTIMIZE_MAX_JOINT, and service_node_3::s.
searchPositionIK() [2/4]
bool fetch_arm::IKFastKinematicsPlugin::searchPositionIK (const geometry_msgs::Pose & ik_pose, const std::vector< double > & ik_seed_state, double timeout, const std::vector< double > & consistency_limits, std::vector< double > & solution, moveit_msgs::MoveItErrorCodes & error_code, const kinematics::KinematicsQueryOptions & options = kinematics::KinematicsQueryOptions()) const [override]
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
Parameters
ik_pose the desired pose of the link
ik_seed_state an initial guess solution for the inverse kinematics
the distance that the redundancy can be from the current position
Returns
True if a valid solution was found, false otherwise
Definition at line 804 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  return searchPositionIK(ik_pose, ik_seed_state, timeout, consistency_limits, solution, IKCallbackFn(), error_code,
                          options);
}
searchPositionIK() [3/4]
bool fetch_arm::IKFastKinematicsPlugin::searchPositionIK (const geometry_msgs::Pose & ik_pose, const std::vector< double > & ik_seed_state, double timeout, std::vector< double > & solution, const IKCallbackFn & solution_callback, moveit_msgs::MoveItErrorCodes & error_code, const kinematics::KinematicsQueryOptions & options = kinematics::KinematicsQueryOptions()) const [override]
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
Parameters
ik_pose the desired pose of the link
ik_seed_state an initial guess solution for the inverse kinematics
Returns
True if a valid solution was found, false otherwise
Definition at line 814 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  std::vector<double> consistency_limits;
  return searchPositionIK(ik_pose, ik_seed_state, timeout, consistency_limits, solution, solution_callback, error_code,
                          options);
}
searchPositionIK() [4/4]
bool fetch_arm::IKFastKinematicsPlugin::searchPositionIK (const geometry_msgs::Pose & ik_pose, const std::vector< double > & ik_seed_state, double timeout, std::vector< double > & solution, moveit_msgs::MoveItErrorCodes & error_code, const kinematics::KinematicsQueryOptions & options = kinematics::KinematicsQueryOptions()) const [override]
Given a desired pose of the end-effector, search for the joint angles required to reach it. This particular method is intended for `searching` for a solutions by stepping through the redundancy (or other numerical routines).
Parameters
ik_pose the desired pose of the link
ik_seed_state an initial guess solution for the inverse kinematics
Returns
True if a valid solution was found, false otherwise
Definition at line 794 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  std::vector<double> consistency_limits;
  return searchPositionIK(ik_pose, ik_seed_state, timeout, consistency_limits, solution, IKCallbackFn(), error_code,
                          options);
}
setRedundantJoints()
bool fetch_arm::IKFastKinematicsPlugin::setRedundantJoints (const std::vector< unsigned int > & redundant_joint_indices) [override]
Overrides the default method to prevent changing the redundant joints.
Definition at line 519 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  ROS_ERROR_STREAM_NAMED(name_, "Changing the redundant joints isn't permitted by this group's solver ");
  return false;
}
setSearchDiscretization()
void fetch_arm::IKFastKinematicsPlugin::setSearchDiscretization (const std::map< unsigned int, double > & discretization)
Sets the discretization value for the redundant joint.
Since this ikfast implementation allows for one redundant joint then only the first entry will be in the discretization map will be used. Calling this method replaces previous discretization settings.
Parameters
discretization a map of joint indices and discretization value pairs.
Definition at line 486 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  if (discretization.empty())
  {
    ROS_ERROR("The 'discretization' map is empty");
    return;
  }
  if (redundant_joint_indices_.empty())
  {
    ROS_ERROR_STREAM_NAMED(name_, "This group's solver doesn't support redundant joints");
    return;
  }
  if (discretization.begin()->first != redundant_joint_indices_[0])
  {
    std::string redundant_joint = joint_names_[free_params_[0]];
    ROS_ERROR_STREAM_NAMED(name_, "Attempted to discretize a non-redundant joint "
                                      << discretization.begin()->first << ", only joint '" << redundant_joint
                                      << "' with index " << redundant_joint_indices_[0] << " is redundant.");
    return;
  }
  if (discretization.begin()->second <= 0.0)
  {
    ROS_ERROR_STREAM_NAMED(name_, "Discretization can not takes values that are <= 0");
    return;
  }
  redundant_joint_discretization_.clear();
  redundant_joint_discretization_[redundant_joint_indices_[0]] = discretization.begin()->second;
}
solve()
size_t fetch_arm::IKFastKinematicsPlugin::solve (KDL::Frame & pose_frame, const std::vector< double > & vfree, IkSolutionList< IkReal > & solutions) const [private]
Calls the IK solver from IKFast.
Returns
The number of solutions found
Definition at line 525 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  // IKFast56/61
  solutions.Clear();
  double trans[3];
  trans[0] = pose_frame.p[0]; //-.18;
  trans[1] = pose_frame.p[1];
  trans[2] = pose_frame.p[2];
  KDL::Rotation mult;
  KDL::Vector direction;
  switch (GetIkType())
  {
    case IKP_Transform6D:
    case IKP_Translation3D:
      // For **Transform6D**, eerot is 9 values for the 3x3 rotation matrix. For **Translation3D**, these are ignored.
      mult = pose_frame.M;
      double vals[9];
      vals[0] = mult(0, 0);
      vals[1] = mult(0, 1);
      vals[2] = mult(0, 2);
      vals[3] = mult(1, 0);
      vals[4] = mult(1, 1);
      vals[5] = mult(1, 2);
      vals[6] = mult(2, 0);
      vals[7] = mult(2, 1);
      vals[8] = mult(2, 2);
      // IKFast56/61
      ComputeIk(trans, vals, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();
    case IKP_Direction3D:
    case IKP_Ray4D:
    case IKP_TranslationDirection5D:
      // For **Direction3D**, **Ray4D**, and **TranslationDirection5D**, the first 3 values represent the target
      // direction.
      direction = pose_frame.M * KDL::Vector(0, 0, 1);
      ComputeIk(trans, direction.data, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();
    case IKP_TranslationXAxisAngle4D:
    case IKP_TranslationYAxisAngle4D:
    case IKP_TranslationZAxisAngle4D:
      // For *TranslationXAxisAngle4D*, *TranslationYAxisAngle4D*, *TranslationZAxisAngle4D* - end effector origin
      // reaches desired 3D translation, manipulator direction makes a specific angle with x/y/z-axis (defined in the
      // manipulator base link’s coordinate system)
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;
    case IKP_TranslationLocalGlobal6D:
      // For **TranslationLocalGlobal6D**, the diagonal elements ([0],[4],[8]) are the local translation inside the end
      // effector coordinate system.
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;
    case IKP_Rotation3D:
    case IKP_Lookat3D:
    case IKP_TranslationXY2D:
    case IKP_TranslationXYOrientation3D:
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;
    case IKP_TranslationXAxisAngleZNorm4D:
      double roll, pitch, yaw;
      // For **TranslationXAxisAngleZNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to z axis and be rotated at a certain angle starting from the x axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &yaw, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();
    case IKP_TranslationYAxisAngleXNorm4D:
      // For **TranslationYAxisAngleXNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to x axis and be rotated at a certain angle starting from the y axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &roll, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();
    case IKP_TranslationZAxisAngleYNorm4D:
      // For **TranslationZAxisAngleYNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to y axis and be rotated at a certain angle starting from the z axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &pitch, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();
    default:
      ROS_ERROR_NAMED(name_, "Unknown IkParameterizationType! "
                             "Was the solver generated with an incompatible version of Openrave?");
      return 0;
  }
}
References ikfast::IkSolutionList< T >::Clear(), ComputeIk(), GetIkType(), ikfast::IkSolutionList< T >::GetNumSolutions(), fetch_arm::IKP_Direction3D, fetch_arm::IKP_Lookat3D, fetch_arm::IKP_Ray4D, fetch_arm::IKP_Rotation3D, fetch_arm::IKP_Transform6D, fetch_arm::IKP_Translation3D, fetch_arm::IKP_TranslationDirection5D, fetch_arm::IKP_TranslationLocalGlobal6D, fetch_arm::IKP_TranslationXAxisAngle4D, fetch_arm::IKP_TranslationXAxisAngleZNorm4D, fetch_arm::IKP_TranslationXY2D, fetch_arm::IKP_TranslationXYOrientation3D, fetch_arm::IKP_TranslationYAxisAngle4D, fetch_arm::IKP_TranslationYAxisAngleXNorm4D, fetch_arm::IKP_TranslationZAxisAngle4D, and fetch_arm::IKP_TranslationZAxisAngleYNorm4D.
transformToChainFrame()
void fetch_arm::IKFastKinematicsPlugin::transformToChainFrame (const geometry_msgs::Pose & ik_pose, KDL::Frame & ik_pose_chain) const [private]
Transforms the input pose to the correct frame for the solver. This assumes that the group includes the entire solver chain and that any joints outside of the solver chain within the group are are fixed.
Parameters
ik_pose The pose to be transformed which should be in the correct frame for the group.
ik_pose_chain The ik_pose to be populated with the apropriate pose for the solver
Definition at line 1351 of file fetch_arm_ikfast_moveit_plugin.cpp.
{
  if (tip_transform_required_ || base_transform_required_)
  {
    Eigen::Isometry3d ik_eigen_pose;
    tf2::fromMsg(ik_pose, ik_eigen_pose);
    if (tip_transform_required_)
      ik_eigen_pose = ik_eigen_pose * group_tip_to_chain_tip_;
    if (base_transform_required_)
      ik_eigen_pose = chain_base_to_group_base_ * ik_eigen_pose;
    tf::transformEigenToKDL(ik_eigen_pose, ik_pose_chain);
  }
  else
  {
    tf2::fromMsg(ik_pose, ik_pose_chain);
  }
}
Member Data Documentation
base_transform_required_
bool fetch_arm::IKFastKinematicsPlugin::base_transform_required_ [private]
Definition at line 174 of file fetch_arm_ikfast_moveit_plugin.cpp.
chain_base_to_group_base_
Eigen::Isometry3d fetch_arm::IKFastKinematicsPlugin::chain_base_to_group_base_ [private]
Definition at line 178 of file fetch_arm_ikfast_moveit_plugin.cpp.
free_params_
std::vector<int> fetch_arm::IKFastKinematicsPlugin::free_params_ [private]
Definition at line 162 of file fetch_arm_ikfast_moveit_plugin.cpp.
group_tip_to_chain_tip_
Eigen::Isometry3d fetch_arm::IKFastKinematicsPlugin::group_tip_to_chain_tip_ [private]
Definition at line 179 of file fetch_arm_ikfast_moveit_plugin.cpp.
IKFAST_BASE_FRAME_
const std::string fetch_arm::IKFastKinematicsPlugin::IKFAST_BASE_FRAME_ = `torso_lift_link` [private]
Definition at line 167 of file fetch_arm_ikfast_moveit_plugin.cpp.
IKFAST_TIP_FRAME_
const std::string fetch_arm::IKFastKinematicsPlugin::IKFAST_TIP_FRAME_ = `wrist_roll_link` [private]
Definition at line 166 of file fetch_arm_ikfast_moveit_plugin.cpp.
initialized_
bool fetch_arm::IKFastKinematicsPlugin::initialized_ [private]
Definition at line 181 of file fetch_arm_ikfast_moveit_plugin.cpp.
joint_has_limits_vector_
std::vector<bool> fetch_arm::IKFastKinematicsPlugin::joint_has_limits_vector_ [private]
Definition at line 159 of file fetch_arm_ikfast_moveit_plugin.cpp.
joint_max_vector_
std::vector<double> fetch_arm::IKFastKinematicsPlugin::joint_max_vector_ [private]
Definition at line 158 of file fetch_arm_ikfast_moveit_plugin.cpp.
joint_min_vector_
std::vector<double> fetch_arm::IKFastKinematicsPlugin::joint_min_vector_ [private]
Definition at line 157 of file fetch_arm_ikfast_moveit_plugin.cpp.
joint_names_
std::vector<std::string> fetch_arm::IKFastKinematicsPlugin::joint_names_ [private]
Definition at line 156 of file fetch_arm_ikfast_moveit_plugin.cpp.
link_names_
std::vector<std::string> fetch_arm::IKFastKinematicsPlugin::link_names_ [private]
Definition at line 160 of file fetch_arm_ikfast_moveit_plugin.cpp.
name_
const std::string fetch_arm::IKFastKinematicsPlugin::name_ { `ikfast` } [private]
Definition at line 182 of file fetch_arm_ikfast_moveit_plugin.cpp.
num_joints_
const size_t fetch_arm::IKFastKinematicsPlugin::num_joints_ [private]
Definition at line 161 of file fetch_arm_ikfast_moveit_plugin.cpp.
tip_transform_required_
bool fetch_arm::IKFastKinematicsPlugin::tip_transform_required_ [private]
Definition at line 173 of file fetch_arm_ikfast_moveit_plugin.cpp.
The documentation for this class was generated from the following file:
submodules/fetch_ros/fetch_ikfast_plugin/src/fetch_arm_ikfast_moveit_plugin.cpp