smacc::ISmaccUpdatable Class Reference
#include <smacc_updatable.h>
Public Member Functions
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Protected Member Functions
virtual void update ()=0
Private Attributes
boost::optional< ros::Duration > periodDuration_
ros::Time lastUpdate_
Detailed Description
Definition at line 19 of file smacc_updatable.h.
Constructor & Destructor Documentation
ISmaccUpdatable() [1/2]
ISmaccUpdatable::ISmaccUpdatable ()
Definition at line 6 of file smacc_updatable.cpp.
    : lastUpdate_(0)
{
}
ISmaccUpdatable() [2/2]
ISmaccUpdatable::ISmaccUpdatable (ros::Duration duration)
Definition at line 11 of file smacc_updatable.cpp.
    : lastUpdate_(0),
      periodDuration_(duration)
{
}
Member Function Documentation
executeUpdate()
void ISmaccUpdatable::executeUpdate ()
Definition at line 22 of file smacc_updatable.cpp.
{
    bool update = true;
    if (periodDuration_)
    {
        auto now = ros::Time::now();
        auto ellapsed = now - this->lastUpdate_;
        update = ellapsed > *periodDuration_;
        if(update)
        {
            this->lastUpdate_ = now;
        }
    }
    if (update)
    {
        this->update();
    }
}
References lastUpdate_, periodDuration_, and update().
setUpdatePeriod()
void ISmaccUpdatable::setUpdatePeriod (ros::Duration duration)
Definition at line 17 of file smacc_updatable.cpp.
{
    periodDuration_ = duration;
}
References periodDuration_.
Referenced by sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintLateralWorkspace::CpConstraintLateralWorkspace(), sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::CpConstraintLateralWorkspace(), sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintLateralWorkspace::CpConstraintLateralWorkspace(), sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintLateralWorkspace::CpConstraintLateralWorkspace(), sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall(), sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall(), sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall(), sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall(), and sm_fetch_two_table_whiskey_pour::OrArm::onInitialize().
update()
virtual void smacc::ISmaccUpdatable::update () [protected], [pure virtual]
Implemented in sm_fetch_robot_asynchronous_orthogonals::cl_perception_system::ClPerceptionSystem, sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem, sm_fetch_screw_loop_1::cl_perception_system::ClPerceptionSystem, sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem, cl_move_group_interface::CbMoveEndEffectorTrajectory, sm_ferrari::StState2, sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem, smacc::state_reactors::EgRandomGenerator, smacc::event_generators::EgConditionalGenerator, cl_move_base_z::CpTFListener, cl_move_base_z::CbUndoPathBackwards2, cl_move_base_z::Pose, cl_ros_publisher::CbDefaultPublishLoop, sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintVirtualSideWall, and sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall.
Referenced by executeUpdate().
Member Data Documentation
lastUpdate_
ros::Time smacc::ISmaccUpdatable::lastUpdate_ [private]
Definition at line 37 of file smacc_updatable.h.
Referenced by executeUpdate().
periodDuration_
boost::optional<ros::Duration> smacc::ISmaccUpdatable::periodDuration_ [private]
Definition at line 36 of file smacc_updatable.h.
Referenced by executeUpdate(), and setUpdatePeriod().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_updatable.h
smacc/src/smacc/smacc_updatable.cpp