SmaccTestRuntimeNode Class Reference
Public Member Functions
template<typename T >
std::shared_ptr< TestPolicy > tryTestPolicyFactory (std::string matchname, XmlRpc::XmlRpcValue &initXmlRpcValue)
void init ()
void sucess (std::string msg)
void failure (std::string msg)
void update ()
void onRosOutCallback (const rosgraph_msgs::Log &msg)
void onSmaccTransitionCallback (const smacc_msgs::SmaccTransitionLogEntry &msg)
Public Attributes
ros::NodeHandle nh_
ros::Subscriber rosoutSub_
ros::Subscriber smaccTransitionSub_
std::vector< std::shared_ptr< TestPolicy > > testPolicies
boost::signals2::signal< void(const rosgraph_msgs::Log &)> onRosOutMsg
boost::signals2::signal< void(const smacc_msgs::SmaccTransitionLogEntry &)> onSmaccTransition
Detailed Description
Definition at line 28 of file smacc_runtime_test_node.cpp.
Member Function Documentation
failure()
void SmaccTestRuntimeNode::failure (std::string msg) [inline]
Definition at line 105 of file smacc_runtime_test_node.cpp.
  {
    ROS_FATAL_STREAM("SmaccRuntimeTestNode policy thrown failure exit: " << msg);
    exit(-1);
  }
References battery_monitor_node::msg.
Referenced by TimeoutFailureTestPolicy::update().
init()
void SmaccTestRuntimeNode::init () [inline]
Definition at line 61 of file smacc_runtime_test_node.cpp.
  {
    ROS_INFO("[SmaccTestruntimeNode] subscribing rosout");
    ros::NodeHandle private_nh("~");
    std::string stateMachineROSParamWs;
    if (private_nh.getParam("state_machine_rosparam_ws", stateMachineROSParamWs))
    {
      ROS_INFO_STREAM("state machine param ws: " << stateMachineROSParamWs);
    }
    rosoutSub_ = nh_.subscribe("/rosout", 1, &SmaccTestRuntimeNode::onRosOutCallback, this);
    smaccTransitionSub_ = nh_.subscribe(stateMachineROSParamWs + "/smacc/transition_log", 1, &SmaccTestRuntimeNode::onSmaccTransitionCallback, this);
    XmlRpc::XmlRpcValue successSwitchParam;
    private_nh.getParam("success_switch", successSwitchParam);
    ROS_INFO_STREAM("[SmaccTestruntimeNode] success switch" << successSwitchParam);
    ROS_ASSERT(successSwitchParam.getType() == XmlRpc::XmlRpcValue::TypeArray);
    for (int32_t i = 0; i < successSwitchParam.size(); ++i)
    {
      auto initXmlRpcValue = successSwitchParam[i];
      if (tryTestPolicyFactory<ReachedStateSuccessTestPolicy>("state_reached", initXmlRpcValue) != nullptr)
        continue;
    }
    XmlRpc::XmlRpcValue failureSwitchParam;
    private_nh.getParam("failure_switch", failureSwitchParam);
    ROS_INFO_STREAM("[SmaccTestruntimeNode] failure switch" << failureSwitchParam);
    ROS_ASSERT(failureSwitchParam.getType() == XmlRpc::XmlRpcValue::TypeArray);
    for (int32_t i = 0; i < failureSwitchParam.size(); ++i)
    {
      auto initXmlRpcValue = failureSwitchParam[i];
      if (tryTestPolicyFactory<TimeoutFailureTestPolicy>("timeout", initXmlRpcValue) != nullptr)
        continue;
    }
  }
References nh_, onRosOutCallback(), onSmaccTransitionCallback(), rosoutSub_, and smaccTransitionSub_.
Referenced by main().
onRosOutCallback()
void SmaccTestRuntimeNode::onRosOutCallback (const rosgraph_msgs::Log & msg) [inline]
Definition at line 119 of file smacc_runtime_test_node.cpp.
  {
      this->onRosOutMsg(msg);
  }
References onRosOutMsg.
Referenced by init().
onSmaccTransitionCallback()
void SmaccTestRuntimeNode::onSmaccTransitionCallback (const smacc_msgs::SmaccTransitionLogEntry & msg) [inline]
Definition at line 124 of file smacc_runtime_test_node.cpp.
  {
      this->onSmaccTransition(msg);
  }
References onSmaccTransition.
Referenced by init().
sucess()
void SmaccTestRuntimeNode::sucess (std::string msg) [inline]
Definition at line 99 of file smacc_runtime_test_node.cpp.
  {
    ROS_INFO_STREAM("SmaccRuntimeTestNode policy thrown success exit: " << msg);
    exit(-1);
  }
References battery_monitor_node::msg.
Referenced by ReachedStateSuccessTestPolicy::init().
tryTestPolicyFactory()
template<typename T >
std::shared_ptr<TestPolicy> SmaccTestRuntimeNode::tryTestPolicyFactory (std::string matchname, XmlRpc::XmlRpcValue & initXmlRpcValue) [inline]
Definition at line 41 of file smacc_runtime_test_node.cpp.
  {
    std::shared_ptr<TestPolicy> policy = nullptr;
    ROS_INFO_STREAM(initXmlRpcValue);
    auto type = (std::string)initXmlRpcValue["type"];
    if (type == matchname)
    {
      auto specificPolicy = std::make_shared<T>();
      policy = std::dynamic_pointer_cast<TestPolicy>(specificPolicy);
      testPolicies.push_back(policy);
      policy->owner_ = this;
      policy->init(initXmlRpcValue);
    }
    return policy;
  }
References testPolicies, and generate_debs::type.
update()
void SmaccTestRuntimeNode::update () [inline]
Definition at line 111 of file smacc_runtime_test_node.cpp.
  {
    for (auto& policy : testPolicies)
    {
      policy->update();
    }
  }
References testPolicies.
Referenced by main().
Member Data Documentation
nh_
ros::NodeHandle SmaccTestRuntimeNode::nh_
Definition at line 31 of file smacc_runtime_test_node.cpp.
Referenced by init().
onRosOutMsg
boost::signals2::signal<void(const rosgraph_msgs::Log&)> SmaccTestRuntimeNode::onRosOutMsg
Definition at line 37 of file smacc_runtime_test_node.cpp.
Referenced by onRosOutCallback().
onSmaccTransition
boost::signals2::signal<void(const smacc_msgs::SmaccTransitionLogEntry&)> SmaccTestRuntimeNode::onSmaccTransition
Definition at line 38 of file smacc_runtime_test_node.cpp.
Referenced by ReachedStateSuccessTestPolicy::init(), and onSmaccTransitionCallback().
rosoutSub_
ros::Subscriber SmaccTestRuntimeNode::rosoutSub_
Definition at line 32 of file smacc_runtime_test_node.cpp.
Referenced by init().
smaccTransitionSub_
ros::Subscriber SmaccTestRuntimeNode::smaccTransitionSub_
Definition at line 33 of file smacc_runtime_test_node.cpp.
Referenced by init().
testPolicies
std::vector<std::shared_ptr<TestPolicy> > SmaccTestRuntimeNode::testPolicies
Definition at line 36 of file smacc_runtime_test_node.cpp.
Referenced by tryTestPolicyFactory(), and update().
The documentation for this class was generated from the following file:
smacc_diagnostics/smacc_runtime_test/src/smacc_runtime_test_node.cpp