fake_cube_perception_node.FakePerceptionNode Class Reference
Public Member Functions
def __init__ (self)
def update (self)
def simulated_link_state_callback (self, linksmsg)
def propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
def __init__ (self)
def update (self)
def simulated_link_state_callback (self, linksmsg)
def propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
def __init__ (self)
def update (self)
def simulated_link_state_callback (self, linksmsg)
def propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
def __init__ (self)
def update (self)
def simulated_link_state_callback (self, linksmsg)
def propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
def __init__ (self)
def update (self)
def simulated_link_state_callback (self, linksmsg)
def propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Public Attributes
planning_scene
tf_broacaster
tf_listener
pub
update_planning_scene
last_update
update_period
table_collision
cube_collision
Detailed Description
Definition at line 10 of file fake_cube_perception_node.py.
Constructor & Destructor Documentation
__init__() [1/5]
def fake_cube_perception_node.FakePerceptionNode.__init__ (self)
Definition at line 11 of file fake_cube_perception_node.py.
    def __init__(self):
        self.planning_scene = PlanningSceneInterface("map")
        self.tf_broacaster = tf.TransformBroadcaster()
        self.tf_listener = tf.TransformListener()
        self.pub = rospy.Subscriber(
            '/gazebo/link_states', LinkStates, self.simulated_link_state_callback, queue_size=1)
        self.update_planning_scene = True
        self.last_update = rospy.Time.now()
        self.update_period = rospy.Duration(10)
        self.table_collision = True
        self.cube_collision = False
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
__init__() [2/5]
def fake_cube_perception_node.FakePerceptionNode.__init__ (self)
Definition at line 11 of file fake_cube_perception_node.py.
    def __init__(self):
        self.planning_scene = PlanningSceneInterface("map")
        self.tf_broacaster = tf.TransformBroadcaster()
        self.tf_listener = tf.TransformListener()
        self.pub = rospy.Subscriber(
            '/gazebo/link_states', LinkStates, self.simulated_link_state_callback, queue_size=1)
        self.update_planning_scene = True
        self.last_update = rospy.Time.now()
        self.update_period = rospy.Duration(10)
        self.table_collision = True
        self.cube_collision = False
References fake_cube_perception_node.FakePerceptionNode.__init__(), fake_cube_perception_node.FakePerceptionNode.cube_collision, fake_cube_perception_node.FakePerceptionNode.last_update, fake_cube_perception_node.FakePerceptionNode.planning_scene, fake_cube_perception_node.FakePerceptionNode.pub, fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback(), fake_cube_perception_node.FakePerceptionNode.table_collision, fake_cube_perception_node.FakePerceptionNode.tf_broacaster, fake_cube_perception_node.FakePerceptionNode.tf_listener, fake_cube_perception_node.FakePerceptionNode.update_period, and fake_cube_perception_node.FakePerceptionNode.update_planning_scene.
__init__() [3/5]
def fake_cube_perception_node.FakePerceptionNode.__init__ (self)
Definition at line 11 of file fake_cube_perception_node.py.
    def __init__(self):
        self.planning_scene = PlanningSceneInterface("map")
        self.tf_broacaster = tf.TransformBroadcaster()
        self.tf_listener = tf.TransformListener()
        self.pub = rospy.Subscriber(
            '/gazebo/link_states', LinkStates, self.simulated_link_state_callback, queue_size=1)
        self.update_planning_scene = True
        self.last_update = rospy.Time.now()
        self.update_period = rospy.Duration(10)
        self.table_collision = True
        self.cube_collision = False
References fake_cube_perception_node.FakePerceptionNode.__init__(), fake_cube_perception_node.FakePerceptionNode.cube_collision, fake_cube_perception_node.FakePerceptionNode.last_update, fake_cube_perception_node.FakePerceptionNode.planning_scene, fake_cube_perception_node.FakePerceptionNode.pub, fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback(), fake_cube_perception_node.FakePerceptionNode.table_collision, fake_cube_perception_node.FakePerceptionNode.tf_broacaster, fake_cube_perception_node.FakePerceptionNode.tf_listener, fake_cube_perception_node.FakePerceptionNode.update_period, and fake_cube_perception_node.FakePerceptionNode.update_planning_scene.
__init__() [4/5]
def fake_cube_perception_node.FakePerceptionNode.__init__ (self)
Definition at line 11 of file fake_cube_perception_node.py.
    def __init__(self):
        self.planning_scene = PlanningSceneInterface("map")
        self.tf_broacaster = tf.TransformBroadcaster()
        self.tf_listener = tf.TransformListener()
        self.pub = rospy.Subscriber(
            '/gazebo/link_states', LinkStates, self.simulated_link_state_callback, queue_size=1)
        self.update_planning_scene = True
        self.last_update = rospy.Time.now()
        self.update_period = rospy.Duration(10)
        self.table_collision = True
        self.cube_collision = False
References fake_cube_perception_node.FakePerceptionNode.__init__(), fake_cube_perception_node.FakePerceptionNode.cube_collision, fake_cube_perception_node.FakePerceptionNode.last_update, fake_cube_perception_node.FakePerceptionNode.planning_scene, fake_cube_perception_node.FakePerceptionNode.pub, fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback(), fake_cube_perception_node.FakePerceptionNode.table_collision, fake_cube_perception_node.FakePerceptionNode.tf_broacaster, fake_cube_perception_node.FakePerceptionNode.tf_listener, fake_cube_perception_node.FakePerceptionNode.update_period, and fake_cube_perception_node.FakePerceptionNode.update_planning_scene.
__init__() [5/5]
def fake_cube_perception_node.FakePerceptionNode.__init__ (self)
Definition at line 11 of file fake_cube_perception_node.py.
    def __init__(self):
        self.planning_scene = PlanningSceneInterface("map")
        self.tf_broacaster = tf.TransformBroadcaster()
        self.tf_listener = tf.TransformListener()
        self.pub = rospy.Subscriber(
            '/gazebo/link_states', LinkStates, self.simulated_link_state_callback, queue_size=1)
        self.update_planning_scene = True
        self.last_update = rospy.Time.now()
        self.update_period = rospy.Duration(10)
        self.table_collision = True
        self.cube_collision = False
References fake_cube_perception_node.FakePerceptionNode.__init__(), fake_cube_perception_node.FakePerceptionNode.cube_collision, fake_cube_perception_node.FakePerceptionNode.last_update, fake_cube_perception_node.FakePerceptionNode.planning_scene, fake_cube_perception_node.FakePerceptionNode.pub, fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback(), fake_cube_perception_node.FakePerceptionNode.table_collision, fake_cube_perception_node.FakePerceptionNode.tf_broacaster, fake_cube_perception_node.FakePerceptionNode.tf_listener, fake_cube_perception_node.FakePerceptionNode.update_period, and fake_cube_perception_node.FakePerceptionNode.update_planning_scene.
Member Function Documentation
propagate_link_states_to_tf() [1/5]
def fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Definition at line 83 of file fake_cube_perception_node.py.
    def propagate_link_states_to_tf(self, linksmsg, link_name_filter, object_prefix, global_frame):
        filteredLinkPoses = [b for i, b in enumerate(
            linksmsg.pose) if link_name_filter in linksmsg.name[i]]
        transforms = []
        for i, cubepose in enumerate(filteredLinkPoses):
            quat = [cubepose.orientation.x, cubepose.orientation.y,
                    cubepose.orientation.z, cubepose.orientation.w]
            trans = [cubepose.position.x,
                     cubepose.position.y, cubepose.position.z]
            self.tf_broacaster.sendTransform(
                trans, quat, rospy.Time.now(), object_prefix + str(i), global_frame)
            transforms.append([trans, quat])
        return transforms
References fake_cube_perception_node.FakePerceptionNode.tf_broacaster.
Referenced by fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf().
propagate_link_states_to_tf() [2/5]
def fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Definition at line 83 of file fake_cube_perception_node.py.
    def propagate_link_states_to_tf(self, linksmsg, link_name_filter, object_prefix, global_frame):
        filteredLinkPoses = [b for i, b in enumerate(
            linksmsg.pose) if link_name_filter in linksmsg.name[i]]
        transforms = []
        for i, cubepose in enumerate(filteredLinkPoses):
            quat = [cubepose.orientation.x, cubepose.orientation.y,
                    cubepose.orientation.z, cubepose.orientation.w]
            trans = [cubepose.position.x,
                     cubepose.position.y, cubepose.position.z]
            self.tf_broacaster.sendTransform(
                trans, quat, rospy.Time.now(), object_prefix + str(i), global_frame)
            transforms.append([trans, quat])
        return transforms
References fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf(), and fake_cube_perception_node.FakePerceptionNode.tf_broacaster.
propagate_link_states_to_tf() [3/5]
def fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Definition at line 83 of file fake_cube_perception_node.py.
    def propagate_link_states_to_tf(self, linksmsg, link_name_filter, object_prefix, global_frame):
        filteredLinkPoses = [b for i, b in enumerate(
            linksmsg.pose) if link_name_filter in linksmsg.name[i]]
        transforms = []
        for i, cubepose in enumerate(filteredLinkPoses):
            quat = [cubepose.orientation.x, cubepose.orientation.y,
                    cubepose.orientation.z, cubepose.orientation.w]
            trans = [cubepose.position.x,
                     cubepose.position.y, cubepose.position.z]
            self.tf_broacaster.sendTransform(
                trans, quat, rospy.Time.now(), object_prefix + str(i), global_frame)
            transforms.append([trans, quat])
        return transforms
References fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf(), and fake_cube_perception_node.FakePerceptionNode.tf_broacaster.
propagate_link_states_to_tf() [4/5]
def fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Definition at line 83 of file fake_cube_perception_node.py.
    def propagate_link_states_to_tf(self, linksmsg, link_name_filter, object_prefix, global_frame):
        filteredLinkPoses = [b for i, b in enumerate(
            linksmsg.pose) if link_name_filter in linksmsg.name[i]]
        transforms = []
        for i, cubepose in enumerate(filteredLinkPoses):
            quat = [cubepose.orientation.x, cubepose.orientation.y,
                    cubepose.orientation.z, cubepose.orientation.w]
            trans = [cubepose.position.x,
                     cubepose.position.y, cubepose.position.z]
            self.tf_broacaster.sendTransform(
                trans, quat, rospy.Time.now(), object_prefix + str(i), global_frame)
            transforms.append([trans, quat])
        return transforms
References fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf(), and fake_cube_perception_node.FakePerceptionNode.tf_broacaster.
propagate_link_states_to_tf() [5/5]
def fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf (self, linksmsg, link_name_filter, object_prefix, global_frame)
Definition at line 83 of file fake_cube_perception_node.py.
    def propagate_link_states_to_tf(self, linksmsg, link_name_filter, object_prefix, global_frame):
        filteredLinkPoses = [b for i, b in enumerate(
            linksmsg.pose) if link_name_filter in linksmsg.name[i]]
        transforms = []
        for i, cubepose in enumerate(filteredLinkPoses):
            quat = [cubepose.orientation.x, cubepose.orientation.y,
                    cubepose.orientation.z, cubepose.orientation.w]
            trans = [cubepose.position.x,
                     cubepose.position.y, cubepose.position.z]
            self.tf_broacaster.sendTransform(
                trans, quat, rospy.Time.now(), object_prefix + str(i), global_frame)
            transforms.append([trans, quat])
        return transforms
References fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf(), and fake_cube_perception_node.FakePerceptionNode.tf_broacaster.
simulated_link_state_callback() [1/5]
def fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback (self, linksmsg)
string[] name
geometry_msgs/Pose[] pose
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Quaternion orientation
    float64 x
    float64 y
    float64 z
    float64 w
geometry_msgs/Twist[] twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z
Definition at line 29 of file fake_cube_perception_node.py.
    def simulated_link_state_callback(self, linksmsg):
        """
        string[] name
        geometry_msgs/Pose[] pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
        geometry_msgs/Twist[] twist
          geometry_msgs/Vector3 linear
            float64 x
            float64 y
            float64 z
          geometry_msgs/Vector3 angular
            float64 x
            float64 y
            float64 z
        """
        cube_transforms = self.propagate_link_states_to_tf(
            linksmsg, "cube", "cube_", "map")
        table_transforms = self.propagate_link_states_to_tf(
            linksmsg, "table", "table_", "map")
        ellapsed = rospy.Time.now() - self.last_update
        if ellapsed > self.update_period:
            # if self.update_planning_scene:
            rospy.logdebug("updating planning scene")
            attached_objects = self.planning_scene.getKnownAttachedObjects()
            rospy.loginfo(attached_objects)
            #self.update_planning_scene = False
            if self.table_collision and not "cube_0" in attached_objects:
                for i, table_transf in enumerate(table_transforms):
                    #self.planning_scene.removeCollisionObject("table_" + str(i))
                    thickness = 0.12
                    pos = table_transf[0]
                    self.planning_scene.addBox(
                        "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 - thickness*0.5) # 0.68
            if self.cube_collision and not "cube_0" in attached_objects:
                for i, cube_transf in enumerate(cube_transforms):
                    #self.planning_scene.removeCollisionObject("cube_" + str(i))
                    pos = cube_transf[0]
                    self.planning_scene.addCube(
                        "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                    #self.cube_collision = False
simulated_link_state_callback() [2/5]
def fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback (self, linksmsg)
string[] name
geometry_msgs/Pose[] pose
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Quaternion orientation
    float64 x
    float64 y
    float64 z
    float64 w
geometry_msgs/Twist[] twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z
Definition at line 29 of file fake_cube_perception_node.py.
    def simulated_link_state_callback(self, linksmsg):
        """
        string[] name
        geometry_msgs/Pose[] pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
        geometry_msgs/Twist[] twist
          geometry_msgs/Vector3 linear
            float64 x
            float64 y
            float64 z
          geometry_msgs/Vector3 angular
            float64 x
            float64 y
            float64 z
        """
        cube_transforms = self.propagate_link_states_to_tf(
            linksmsg, "cube", "cube_", "map")
        table_transforms = self.propagate_link_states_to_tf(
            linksmsg, "table", "table_", "map")
        ellapsed = rospy.Time.now() - self.last_update
        if ellapsed > self.update_period:
            # if self.update_planning_scene:
            rospy.logdebug("updating planning scene")
            attached_objects = self.planning_scene.getKnownAttachedObjects()
            rospy.loginfo(attached_objects)
            #self.update_planning_scene = False
            if self.table_collision and not "cube_0" in attached_objects:
                for i, table_transf in enumerate(table_transforms):
                    #self.planning_scene.removeCollisionObject("table_" + str(i))
                    thickness = 0.12
                    pos = table_transf[0]
                    self.planning_scene.addBox(
                        "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 - thickness*0.5) # 0.68
            if self.cube_collision and not "cube_0" in attached_objects:
                for i, cube_transf in enumerate(cube_transforms):
                    #self.planning_scene.removeCollisionObject("cube_" + str(i))
                    pos = cube_transf[0]
                    self.planning_scene.addCube(
                        "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                    #self.cube_collision = False
simulated_link_state_callback() [3/5]
def fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback (self, linksmsg)
string[] name
geometry_msgs/Pose[] pose
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Quaternion orientation
    float64 x
    float64 y
    float64 z
    float64 w
geometry_msgs/Twist[] twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z
Definition at line 29 of file fake_cube_perception_node.py.
    def simulated_link_state_callback(self, linksmsg):
        """
        string[] name
        geometry_msgs/Pose[] pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
        geometry_msgs/Twist[] twist
          geometry_msgs/Vector3 linear
            float64 x
            float64 y
            float64 z
          geometry_msgs/Vector3 angular
            float64 x
            float64 y
            float64 z
        """
        cube_transforms = self.propagate_link_states_to_tf(
            linksmsg, "cube", "cube_", "map")
        table_transforms = self.propagate_link_states_to_tf(
            linksmsg, "table", "table_", "map")
        ellapsed = rospy.Time.now() - self.last_update
        if ellapsed > self.update_period:
            # if self.update_planning_scene:
            rospy.logdebug("updating planning scene")
            attached_objects = self.planning_scene.getKnownAttachedObjects()
            rospy.loginfo(attached_objects)
            #self.update_planning_scene = False
            if self.table_collision and not "cube_0" in attached_objects:
                for i, table_transf in enumerate(table_transforms):
                    #self.planning_scene.removeCollisionObject("table_" + str(i))
                    thickness = 0.12
                    pos = table_transf[0]
                    self.planning_scene.addBox(
                        "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 - thickness*0.5) # 0.68
            if self.cube_collision and not "cube_0" in attached_objects:
                for i, cube_transf in enumerate(cube_transforms):
                    #self.planning_scene.removeCollisionObject("cube_" + str(i))
                    pos = cube_transf[0]
                    self.planning_scene.addCube(
                        "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                    #self.cube_collision = False
simulated_link_state_callback() [4/5]
def fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback (self, linksmsg)
string[] name
geometry_msgs/Pose[] pose
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Quaternion orientation
    float64 x
    float64 y
    float64 z
    float64 w
geometry_msgs/Twist[] twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z
Definition at line 29 of file fake_cube_perception_node.py.
    def simulated_link_state_callback(self, linksmsg):
        """
        string[] name
        geometry_msgs/Pose[] pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
        geometry_msgs/Twist[] twist
          geometry_msgs/Vector3 linear
            float64 x
            float64 y
            float64 z
          geometry_msgs/Vector3 angular
            float64 x
            float64 y
            float64 z
        """
        cube_transforms = self.propagate_link_states_to_tf(
            linksmsg, "cube", "cube_", "map")
        table_transforms = self.propagate_link_states_to_tf(
            linksmsg, "table", "table_", "map")
        ellapsed = rospy.Time.now() - self.last_update
        if ellapsed > self.update_period:
            # if self.update_planning_scene:
            rospy.logdebug("updating planning scene")
            attached_objects = self.planning_scene.getKnownAttachedObjects()
            rospy.loginfo(attached_objects)
            #self.update_planning_scene = False
            if self.table_collision and not "cube_0" in attached_objects:
                for i, table_transf in enumerate(table_transforms):
                    #self.planning_scene.removeCollisionObject("table_" + str(i))
                    thickness = 0.12
                    pos = table_transf[0]
                    self.planning_scene.addBox(
                        "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 - thickness*0.5) # 0.68
            if self.cube_collision and not "cube_0" in attached_objects:
                for i, cube_transf in enumerate(cube_transforms):
                    #self.planning_scene.removeCollisionObject("cube_" + str(i))
                    pos = cube_transf[0]
                    self.planning_scene.addCube(
                        "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                    #self.cube_collision = False
simulated_link_state_callback() [5/5]
def fake_cube_perception_node.FakePerceptionNode.simulated_link_state_callback (self, linksmsg)
string[] name
geometry_msgs/Pose[] pose
  geometry_msgs/Point position
    float64 x
    float64 y
    float64 z
  geometry_msgs/Quaternion orientation
    float64 x
    float64 y
    float64 z
    float64 w
geometry_msgs/Twist[] twist
  geometry_msgs/Vector3 linear
    float64 x
    float64 y
    float64 z
  geometry_msgs/Vector3 angular
    float64 x
    float64 y
    float64 z
Definition at line 29 of file fake_cube_perception_node.py.
    def simulated_link_state_callback(self, linksmsg):
        """
        string[] name
        geometry_msgs/Pose[] pose
          geometry_msgs/Point position
            float64 x
            float64 y
            float64 z
          geometry_msgs/Quaternion orientation
            float64 x
            float64 y
            float64 z
            float64 w
        geometry_msgs/Twist[] twist
          geometry_msgs/Vector3 linear
            float64 x
            float64 y
            float64 z
          geometry_msgs/Vector3 angular
            float64 x
            float64 y
            float64 z
        """
        cube_transforms = self.propagate_link_states_to_tf(
            linksmsg, "cube", "cube_", "map")
        table_transforms = self.propagate_link_states_to_tf(
            linksmsg, "table", "table_", "map")
        ellapsed = rospy.Time.now() - self.last_update
        if ellapsed > self.update_period:
            # if self.update_planning_scene:
            rospy.logdebug("updating planning scene")
            attached_objects = self.planning_scene.getKnownAttachedObjects()
            rospy.loginfo(attached_objects)
            #self.update_planning_scene = False
            if self.table_collision and not "cube_0" in attached_objects:
                for i, table_transf in enumerate(table_transforms):
                    #self.planning_scene.removeCollisionObject("table_" + str(i))
                    thickness = 0.12
                    pos = table_transf[0]
                    self.planning_scene.addBox(
                        "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 - thickness*0.5) # 0.68
            if self.cube_collision and not "cube_0" in attached_objects:
                for i, cube_transf in enumerate(cube_transforms):
                    #self.planning_scene.removeCollisionObject("cube_" + str(i))
                    pos = cube_transf[0]
                    self.planning_scene.addCube(
                        "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                    #self.cube_collision = False
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
update() [1/5]
def fake_cube_perception_node.FakePerceptionNode.update (self)
Definition at line 26 of file fake_cube_perception_node.py.
    def update(self):
        pass
References fake_cube_perception_node.FakePerceptionNode.update().
update() [2/5]
def fake_cube_perception_node.FakePerceptionNode.update (self)
Definition at line 26 of file fake_cube_perception_node.py.
    def update(self):
        pass
Referenced by fake_cube_perception_node.FakePerceptionNode.update().
update() [3/5]
def fake_cube_perception_node.FakePerceptionNode.update (self)
Definition at line 26 of file fake_cube_perception_node.py.
    def update(self):
        pass
References fake_cube_perception_node.FakePerceptionNode.update().
update() [4/5]
def fake_cube_perception_node.FakePerceptionNode.update (self)
Definition at line 26 of file fake_cube_perception_node.py.
    def update(self):
        pass
References fake_cube_perception_node.FakePerceptionNode.update().
update() [5/5]
def fake_cube_perception_node.FakePerceptionNode.update (self)
Definition at line 26 of file fake_cube_perception_node.py.
    def update(self):
        pass
References fake_cube_perception_node.FakePerceptionNode.update().
Member Data Documentation
cube_collision
fake_cube_perception_node.FakePerceptionNode.cube_collision
Definition at line 24 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
last_update
fake_cube_perception_node.FakePerceptionNode.last_update
Definition at line 21 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
planning_scene
fake_cube_perception_node.FakePerceptionNode.planning_scene
Definition at line 12 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
pub
fake_cube_perception_node.FakePerceptionNode.pub
Definition at line 17 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
table_collision
fake_cube_perception_node.FakePerceptionNode.table_collision
Definition at line 23 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
tf_broacaster
fake_cube_perception_node.FakePerceptionNode.tf_broacaster
Definition at line 14 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__(), and fake_cube_perception_node.FakePerceptionNode.propagate_link_states_to_tf().
tf_listener
fake_cube_perception_node.FakePerceptionNode.tf_listener
Definition at line 15 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
update_period
fake_cube_perception_node.FakePerceptionNode.update_period
Definition at line 22 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
update_planning_scene
fake_cube_perception_node.FakePerceptionNode.update_planning_scene
Definition at line 20 of file fake_cube_perception_node.py.
Referenced by fake_cube_perception_node.FakePerceptionNode.__init__().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_fetch_robot_asynchronous_orthogonals/servers/fake_cube_perception_node.py