shunk_machine_controlers.ShunkMachineControlersReal Class Reference
Public Member Functions
def __init__ (self)
def setup (self)
def open_chuck (self)
def close_chuck (self)
def start_operation (self)
def end_operation (self)
Detailed Description
Definition at line 6 of file shunk_machine_controlers.py.
Constructor & Destructor Documentation
__init__()
def shunk_machine_controlers.ShunkMachineControlersReal.__init__ (self)
Definition at line 7 of file shunk_machine_controlers.py.
    def __init__(self):
        try:
            import RPi.GPIO as GPIO
        except ImportError:
            print("This script must be run on a Raspberry Pi. (RPi.GPIO import failed)")
            sys.exit(1)
        self.setup()
References shunk_machine_controlers.ShunkMachineControlersReal.setup().
Member Function Documentation
close_chuck()
def shunk_machine_controlers.ShunkMachineControlersReal.close_chuck (self)
Set Pi pins to close chuck.
Definition at line 37 of file shunk_machine_controlers.py.
    def close_chuck(self):
        """Set Pi pins to close chuck."""
        GPIO.output(40, 1)
        GPIO.output(37, 0)
end_operation()
def shunk_machine_controlers.ShunkMachineControlersReal.end_operation (self)
Definition at line 45 of file shunk_machine_controlers.py.
    def end_operation(self):
        pass
open_chuck()
def shunk_machine_controlers.ShunkMachineControlersReal.open_chuck (self)
Set Pi pins to open chuck.
Definition at line 32 of file shunk_machine_controlers.py.
    def open_chuck(self):
        """Set Pi pins to open chuck."""
        GPIO.output(40, 0)
        GPIO.output(37, 1)
Referenced by shunk_machine_controlers_sim.ShunkMachineControlersSim.init_position().
setup()
def shunk_machine_controlers.ShunkMachineControlersReal.setup (self)
Specifies pin numbering schema and sets up GPIO channels
Definition at line 17 of file shunk_machine_controlers.py.
    def setup(self):
        """Specifies pin numbering schema and sets up GPIO channels"""
        # Setup GPIO
        GPIO.setwarnings(False)
        mode = GPIO.getmode()
        if mode is None:
            GPIO.setmode(GPIO.BOARD)
        elif mode == GPIO.BCM:
            GPIO.setup([], GPIO.OUT)
            GPIO.cleanup()
            GPIO.setmode(GPIO.BOARD)
        GPIO.setup(37, GPIO.OUT, initial=1)
        GPIO.setup(40, GPIO.OUT, initial=0)
Referenced by shunk_machine_controlers.ShunkMachineControlersReal.__init__(), and shunk_machine_controlers_sim.ShunkMachineControlersSim.__init__().
start_operation()
def shunk_machine_controlers.ShunkMachineControlersReal.start_operation (self)
Definition at line 42 of file shunk_machine_controlers.py.
    def start_operation(self):
        pass
The documentation for this class was generated from the following file:
submodules/fetch_gazebo/fetchit_challenge/nodes/shunk_machine_controlers.py