robot_controllers::CartesianWrenchController Class Reference
#include <cartesian_wrench.h>
Public Member Functions
CartesianWrenchController ()
virtual ~CartesianWrenchController ()
virtual int init (ros::NodeHandle &nh, ControllerManager *manager)
Initialize the controller and any required data structures.
virtual bool start ()
Attempt to start the controller. This should be called only by the ControllerManager instance.
virtual bool stop (bool force)
Attempt to stop the controller. This should be called only by the ControllerManager instance.
virtual bool reset ()
Cleanly reset the controller to it's initial state. Some controllers may choose to stop themselves. This is mainly used in the case of the the robot exiting some fault condition.
virtual void update (const ros::Time &now, const ros::Duration &dt)
This is the update loop for the controller.
virtual std::string getType ()
Get the type of this controller.
virtual std::vector< std::string > getCommandedNames ()
Get the names of joints/controllers which this controller commands.
virtual std::vector< std::string > getClaimedNames ()
Get the names of joints/controllers which this controller exclusively claims.
void command (const geometry_msgs::Wrench::ConstPtr &goal)
Controller command.
Private Member Functions
void updateJoints ()
Private Attributes
bool initialized_
ControllerManager * manager_
bool enabled_
std::string root_link_
ros::Time last_command_
KDL::Wrench desired_wrench_
KDL::Chain kdl_chain_
boost::shared_ptr< KDL::ChainJntToJacSolver > jac_solver_
KDL::JntArray jnt_pos_
KDL::JntArray jnt_eff_
KDL::Jacobian jacobian_
ros::Publisher feedback_pub_
ros::Subscriber command_sub_
tf::TransformListener tf_
std::vector< JointHandlePtr > joints_
Detailed Description
Definition at line 99 of file cartesian_wrench.h.
Constructor & Destructor Documentation
CartesianWrenchController()
robot_controllers::CartesianWrenchController::CartesianWrenchController ()
Definition at line 87 of file cartesian_wrench.cpp.
  {
 CartesianWrenchController()
virtual robot_controllers::CartesianWrenchController::~CartesianWrenchController () [inline], [virtual]
Definition at line 137 of file cartesian_wrench.h.
Member Function Documentation
command()
void robot_controllers::CartesianWrenchController::command (const geometry_msgs::Wrench::ConstPtr & goal)
Controller command.
Definition at line 220 of file cartesian_wrench.cpp.
{
  return getCommandedNames();
}
} // namespace robot_controllers
References getCommandedNames().
getClaimedNames()
std::vector< std::string > robot_controllers::CartesianWrenchController::getClaimedNames () [virtual]
Get the names of joints/controllers which this controller exclusively claims.
Implements robot_controllers::Controller.
Definition at line 253 of file cartesian_wrench.cpp.
getCommandedNames()
std::vector< std::string > robot_controllers::CartesianWrenchController::getCommandedNames () [virtual]
Get the names of joints/controllers which this controller commands.
Implements robot_controllers::Controller.
Definition at line 241 of file cartesian_wrench.cpp.
Referenced by command().
getType()
virtual std::string robot_controllers::CartesianWrenchController::getType () [inline], [virtual]
Get the type of this controller.
Reimplemented from robot_controllers::Controller.
Definition at line 180 of file cartesian_wrench.h.
init()
int robot_controllers::CartesianWrenchController::init (ros::NodeHandle & nh, ControllerManager * manager) [virtual]
Initialize the controller and any required data structures.
Parameters
nh Node handle for this controller.
manager The controller manager instance, this is needed for the controller to get information about joints, etc.
Returns
0 if succesfully configured, negative values are error codes.
Reimplemented from robot_controllers::Controller.
Definition at line 92 of file cartesian_wrench.cpp.
  {
    ROS_ERROR("Could not construct chain from URDF");
    return -1;
  }
  jac_solver_.reset(new KDL::ChainJntToJacSolver(kdl_chain_));
  jnt_pos_.resize(kdl_chain_.getNrOfJoints());
  jnt_eff_.resize(kdl_chain_.getNrOfJoints());
  jacobian_.resize(kdl_chain_.getNrOfJoints());
  // Init joint handles
  joints_.clear();
  for (size_t i = 0; i < kdl_chain_.getNrOfSegments(); ++i)
    if (kdl_chain_.getSegment(i).getJoint().getType() != KDL::Joint::None)
      joints_.push_back(manager_->getJointHandle(kdl_chain_.getSegment(i).getJoint().getName()));
  // Subscribe to command
  command_sub_ = nh.subscribe<geometry_msgs::Wrench>("command", 1,
                    boost::bind(&CartesianWrenchController::command, this, _1));
  last_command_ = ros::Time(0);
  initialized_ = true;
  return 0;
}
bool CartesianWrenchController::start()
{
  if (!initialized_)
  {
    ROS_ERROR_NAMED("CartesianWrenchController",
                    "Unable to start, not initialized.");
    return false;
  }
  if (ros::Time::now() - last_command_ > ros::Duration(3.0))
  {
    ROS_ERROR_NAMED("CartesianWrenchController",
                    "Unable to start, no goal.");
    return false;
  }
  return true;
}
bool CartesianWrenchController::stop(bool force)
{
  return true;
}
bool CartesianWrenchController::reset()
{
  // Simply stop
  return (manager_->requestStop(getName()) == 0);
}
void CartesianWrenchController::update(const ros::Time& now, const ros::Duration& dt)
{
  // Need to initialize KDL structs
reset()
bool robot_controllers::CartesianWrenchController::reset () [virtual]
Cleanly reset the controller to it's initial state. Some controllers may choose to stop themselves. This is mainly used in the case of the the robot exiting some fault condition.
Returns
True if successfully reset, false otherwise.
Implements robot_controllers::Controller.
Definition at line 176 of file cartesian_wrench.cpp.
{
start()
bool robot_controllers::CartesianWrenchController::start () [virtual]
Attempt to start the controller. This should be called only by the ControllerManager instance.
Returns
True if successfully started, false otherwise.
Implements robot_controllers::Controller.
Definition at line 152 of file cartesian_wrench.cpp.
  {
    // Command has timed out, shutdown
    manager_->requestStop(getName());
    return;
  }
  // This updates jnt_pos_
  updateJoints();
  // Get jacobian
  jac_solver_->JntToJac(jnt_pos_, jacobian_);
  // Convert wrench to joint efforts
  for (size_t i = 0; i < kdl_chain_.getNrOfJoints(); ++i)
  {
References robot_controllers::Controller::getName(), manager_, and robot_controllers::ControllerManager::requestStop().
Referenced by tuck_arm.MoveItThread::__init__().
stop()
bool robot_controllers::CartesianWrenchController::stop (bool force) [virtual]
Attempt to stop the controller. This should be called only by the ControllerManager instance.
Parameters
force Should we force the controller to stop? Some controllers may wish to continue running until they absolutely have to stop.
Returns
True if successfully stopped, false otherwise.
Implements robot_controllers::Controller.
Definition at line 171 of file cartesian_wrench.cpp.
update()
void robot_controllers::CartesianWrenchController::update (const ros::Time & now, const ros::Duration & dt) [virtual]
This is the update loop for the controller.
Parameters
time The system time.
dt The timestep since last call to update.
Implements robot_controllers::Controller.
Definition at line 182 of file cartesian_wrench.cpp.
{
  // Update command
  desired_wrench_.force(0) = goal->force.x;
  desired_wrench_.force(1) = goal->force.y;
  desired_wrench_.force(2) = goal->force.z;
  desired_wrench_.torque(0) = goal->torque.x;
  desired_wrench_.torque(1) = goal->torque.y;
  desired_wrench_.torque(2) = goal->torque.z;
  // Update last command time before trying to start controller
  last_command_ = ros::Time::now();
  // Try to start up
  if (manager_->requestStart(getName()) != 0)
  {
    ROS_ERROR("CartesianWrenchController: Cannot start, blocked by another controller.");
    return;
  }
}
std::vector<std::string> CartesianWrenchController::getCommandedNames()
{
  std::vector<std::string> names;
  if (initialized_)
  {
    for (size_t i = 0; i < kdl_chain_.getNrOfSegments(); ++i)
updateJoints()
void robot_controllers::CartesianWrenchController::updateJoints () [private]
Definition at line 214 of file cartesian_wrench.cpp.
Member Data Documentation
command_sub_
ros::Subscriber robot_controllers::CartesianWrenchController::command_sub_ [private]
Definition at line 213 of file cartesian_wrench.h.
desired_wrench_
KDL::Wrench robot_controllers::CartesianWrenchController::desired_wrench_ [private]
Definition at line 204 of file cartesian_wrench.h.
enabled_
bool robot_controllers::CartesianWrenchController::enabled_ [private]
Definition at line 200 of file cartesian_wrench.h.
feedback_pub_
ros::Publisher robot_controllers::CartesianWrenchController::feedback_pub_ [private]
Definition at line 212 of file cartesian_wrench.h.
initialized_
bool robot_controllers::CartesianWrenchController::initialized_ [private]
Definition at line 197 of file cartesian_wrench.h.
jac_solver_
boost::shared_ptr<KDL::ChainJntToJacSolver> robot_controllers::CartesianWrenchController::jac_solver_ [private]
Definition at line 207 of file cartesian_wrench.h.
jacobian_
KDL::Jacobian robot_controllers::CartesianWrenchController::jacobian_ [private]
Definition at line 210 of file cartesian_wrench.h.
jnt_eff_
KDL::JntArray robot_controllers::CartesianWrenchController::jnt_eff_ [private]
Definition at line 209 of file cartesian_wrench.h.
jnt_pos_
KDL::JntArray robot_controllers::CartesianWrenchController::jnt_pos_ [private]
Definition at line 208 of file cartesian_wrench.h.
joints_
std::vector<JointHandlePtr> robot_controllers::CartesianWrenchController::joints_ [private]
Definition at line 216 of file cartesian_wrench.h.
kdl_chain_
KDL::Chain robot_controllers::CartesianWrenchController::kdl_chain_ [private]
Definition at line 206 of file cartesian_wrench.h.
last_command_
ros::Time robot_controllers::CartesianWrenchController::last_command_ [private]
Definition at line 202 of file cartesian_wrench.h.
manager_
ControllerManager* robot_controllers::CartesianWrenchController::manager_ [private]
Definition at line 198 of file cartesian_wrench.h.
Referenced by start().
root_link_
std::string robot_controllers::CartesianWrenchController::root_link_ [private]
Definition at line 201 of file cartesian_wrench.h.
tf_
tf::TransformListener robot_controllers::CartesianWrenchController::tf_ [private]
Definition at line 215 of file cartesian_wrench.h.
The documentation for this class was generated from the following files:
submodules/robot_controllers/robot_controllers/include/robot_controllers/cartesian_wrench.h
submodules/robot_controllers/robot_controllers/src/cartesian_wrench.cpp