Teleop Class Reference
Public Member Functions
void init (ros::NodeHandle &nh)
void publish (const ros::Duration &dt)
Private Types
typedef boost::shared_ptr< TeleopComponent > TeleopComponentPtr
Private Member Functions
void joyCallback (const sensor_msgs::Joy::ConstPtr &msg)
void stateCallback (const sensor_msgs::JointStateConstPtr &msg)
Private Attributes
std::vector< TeleopComponentPtr > components_
ros::Time last_update_
boost::mutex state_mutex_
sensor_msgs::JointStatePtr state_msg_
ros::Subscriber joy_sub_
ros::Subscriber state_sub_
Detailed Description
Definition at line 715 of file joystick_teleop.cpp.
Member Typedef Documentation
TeleopComponentPtr
typedef boost::shared_ptr<TeleopComponent> Teleop::TeleopComponentPtr [private]
Definition at line 717 of file joystick_teleop.cpp.
Member Function Documentation
init()
void Teleop::init (ros::NodeHandle & nh) [inline]
Definition at line 720 of file joystick_teleop.cpp.
  {
    bool is_fetch;
    bool use_torso;
    bool use_gripper;
    bool use_head;
    bool use_arm;
    bool use_base;
    nh.param("is_fetch", is_fetch, true);
    nh.param("use_torso", use_torso, true);
    nh.param("use_gripper", use_gripper, true);
    nh.param("use_head", use_head, true);
    nh.param("use_arm", use_arm, true);
    nh.param("use_base", use_base, true);
    // TODO: load these from YAML
    TeleopComponentPtr c;
    if (is_fetch)
    {
      if (use_torso)
      {
        // Torso does not override
        c.reset(new FollowTeleop("torso", nh));
        components_.push_back(c);
      }
      if (use_gripper)
      {
        // Gripper does not override
        c.reset(new GripperTeleop("gripper", nh));
        components_.push_back(c);
      }
      if (use_head)
      {
        // Head overrides base
        c.reset(new HeadTeleop("head", nh));
        components_.push_back(c);
      }
      if (use_arm)
      {
        c.reset(new ArmTeleop("arm", nh));
        components_.push_back(c);
      }
    }
    if (use_base)
    {
      // BaseTeleop goes last
      c.reset(new BaseTeleop("base", nh));
      components_.push_back(c);
    }
    state_msg_.reset(new sensor_msgs::JointState());
    joy_sub_ = nh.subscribe("/joy", 1, &Teleop::joyCallback, this);
    state_sub_ = nh.subscribe("/joint_states", 10, &Teleop::stateCallback, this);
  }
References gripper_keyboard::c, components_, joy_sub_, joyCallback(), state_msg_, state_sub_, and stateCallback().
Referenced by main().
joyCallback()
void Teleop::joyCallback (const sensor_msgs::Joy::ConstPtr & msg) [inline], [private]
Definition at line 800 of file joystick_teleop.cpp.
  {
    // Lock mutex on state message
    boost::mutex::scoped_lock lock(state_mutex_);
    bool ok = true;
    for (size_t c = 0; c < components_.size(); c++)
    {
      if (ok)
      {
        ok &= !components_[c]->update(msg, state_msg_);
      }
      else
      {
        // supressed by a higher priority component
        components_[c]->stop();
      }
    }
    last_update_ = ros::Time::now();
  }
References gripper_keyboard::c, components_, last_update_, battery_monitor_node::msg, state_msg_, and state_mutex_.
Referenced by init().
publish()
void Teleop::publish (const ros::Duration & dt) [inline]
Definition at line 780 of file joystick_teleop.cpp.
  {
    if (ros::Time::now() - last_update_ > ros::Duration(0.25))
    {
      // Timed out
      for (size_t c = 0; c < components_.size(); c++)
      {
        components_[c]->stop();
      }
    }
    else
    {
      for (size_t c = 0; c < components_.size(); c++)
      {
        components_[c]->publish(dt);
      }
    }
  }
References gripper_keyboard::c, components_, and last_update_.
Referenced by main().
stateCallback()
void Teleop::stateCallback (const sensor_msgs::JointStateConstPtr & msg) [inline], [private]
Definition at line 821 of file joystick_teleop.cpp.
  {
    // Lock mutex on state message
    boost::mutex::scoped_lock lock(state_mutex_);
    // Update each joint based on message
    for (size_t msg_j = 0; msg_j < msg->name.size(); msg_j++)
    {
      size_t state_j;
      for (state_j = 0; state_j < state_msg_->name.size(); state_j++)
      {
        if (state_msg_->name[state_j] == msg->name[msg_j])
        {
          state_msg_->position[state_j] = msg->position[msg_j];
          state_msg_->velocity[state_j] = msg->velocity[msg_j];
          break;
        }
      }
      if (state_j == state_msg_->name.size())
      {
        // New joint
        state_msg_->name.push_back(msg->name[msg_j]);
        state_msg_->position.push_back(msg->position[msg_j]);
        state_msg_->velocity.push_back(msg->velocity[msg_j]);
      }
    }
  }
References battery_monitor_node::msg, state_msg_, and state_mutex_.
Referenced by init().
Member Data Documentation
components_
std::vector<TeleopComponentPtr> Teleop::components_ [private]
Definition at line 849 of file joystick_teleop.cpp.
Referenced by init(), joyCallback(), and publish().
joy_sub_
ros::Subscriber Teleop::joy_sub_ [private]
Definition at line 853 of file joystick_teleop.cpp.
Referenced by init().
last_update_
ros::Time Teleop::last_update_ [private]
Definition at line 850 of file joystick_teleop.cpp.
Referenced by joyCallback(), and publish().
state_msg_
sensor_msgs::JointStatePtr Teleop::state_msg_ [private]
Definition at line 852 of file joystick_teleop.cpp.
Referenced by init(), joyCallback(), and stateCallback().
state_mutex_
boost::mutex Teleop::state_mutex_ [private]
Definition at line 851 of file joystick_teleop.cpp.
Referenced by joyCallback(), and stateCallback().
state_sub_
ros::Subscriber Teleop::state_sub_ [private]
Definition at line 853 of file joystick_teleop.cpp.
Referenced by init().
The documentation for this class was generated from the following file:
submodules/fetch_ros/fetch_teleop/src/joystick_teleop.cpp