smacc::ISmaccComponent Class Reference
#include <component.h>
Public Member Functions
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Protected Member Functions
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
Protected Attributes
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Friends
class ISmaccOrthogonal
class ISmaccClient
Detailed Description
Definition at line 18 of file component.h.
Constructor & Destructor Documentation
ISmaccComponent()
smacc::ISmaccComponent::ISmaccComponent ()
Definition at line 19 of file smacc_component.cpp.
{
    owner_ = owner;
References onInitialize(), and owner_.
 ISmaccComponent()
smacc::ISmaccComponent::~ISmaccComponent () [virtual]
Definition at line 15 of file smacc_component.cpp.
    : owner_(nullptr)
{
Member Function Documentation
createSiblingComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * smacc::ISmaccComponent::createSiblingComponent (TArgs... targs) [protected]
Definition at line 37 of file smacc_component_impl.h.
    {
References smacc::ISmaccClient::createNamedComponent(), start_controller::name, and owner_.
createSiblingNamedComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * smacc::ISmaccComponent::createSiblingNamedComponent (std::string name, TArgs... targs) [protected]
Definition at line 43 of file smacc_component_impl.h.
getName()
std::string smacc::ISmaccComponent::getName () const [virtual]
Definition at line 40 of file smacc_component.cpp.
initialize()
void smacc::ISmaccComponent::initialize (ISmaccClient * owner) [protected], [virtual]
Definition at line 24 of file smacc_component.cpp.
{
Referenced by sm_viewer_sim::OrNavigation::onInitialize().
onInitialize()
void smacc::ISmaccComponent::onInitialize () [protected], [virtual]
Reimplemented in cl_move_base_z::WaypointNavigator, cl_move_base_z::CostmapSwitch, sm_fetch_robot_asynchronous_orthogonals::cl_perception_system::CpSimulatedGazeboPerception, sm_fetch_screw_loop_1::cl_perception_system::CpSimulatedGazeboPerception, sm_fetch_six_table_pick_n_sort_1::cl_perception_system::CpSimulatedGazeboPerception, sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception, cl_move_base_z::PlannerSwitcher, sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintLateralWorkspace, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintVirtualSideWall, sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall, smacc::components::CpRosControlInterface, and sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData.
Definition at line 30 of file smacc_component.cpp.
{
    stateMachine_ = stateMachine;
References stateMachine_.
Referenced by ISmaccComponent().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject >
void smacc::ISmaccComponent::onOrthogonalAllocation () [inline], [protected]
Definition at line 46 of file component.h.
postEvent() [1/2]
template<typename EventType >
void smacc::ISmaccComponent::postEvent () [protected]
postEvent() [2/2]
template<typename EventType >
void smacc::ISmaccComponent::postEvent (const EventType & ev) [protected]
Definition at line 19 of file smacc_component_impl.h.
    {
References smacc::ISmaccClient::getComponent(), and owner_.
requiresClient()
template<typename TClient >
void smacc::ISmaccComponent::requiresClient (TClient *& requiredClientStorage) [protected]
Definition at line 31 of file smacc_component_impl.h.
    {
References smacc::ISmaccClient::createComponent(), and owner_.
Referenced by sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize(), sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize(), sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize(), sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize(), sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintTableWorkspaces::onInitialize(), sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintTableWorkspaces::onInitialize(), sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::onInitialize(), sm_fetch_screw_loop_1::cl_move_group_interface::CpConstraintLateralWorkspace::onInitialize(), sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintLateralWorkspace::onInitialize(), sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::onInitialize(), and sm_fetch_robot_asynchronous_orthogonals::cl_move_group_interface::CpConstraintLateralWorkspace::onInitialize().
requiresComponent()
template<typename TComponent >
void smacc::ISmaccComponent::requiresComponent (TComponent *& requiredComponentStorage) [protected]
Definition at line 25 of file smacc_component_impl.h.
    {
References owner_, and smacc::ISmaccClient::requiresClient().
setStateMachine()
void smacc::ISmaccComponent::setStateMachine (ISmaccStateMachine * stateMachine) [protected]
Definition at line 35 of file smacc_component.cpp.
{
    std::string keyname = demangleSymbol(typeid(*this).name());
References smacc::introspection::demangleSymbol().
Friends And Related Function Documentation
ISmaccClient
friend class ISmaccClient [friend]
Definition at line 68 of file component.h.
ISmaccOrthogonal
friend class ISmaccOrthogonal [friend]
Definition at line 67 of file component.h.
Member Data Documentation
owner_
ISmaccClient* smacc::ISmaccComponent::owner_ [protected]
Definition at line 65 of file component.h.
Referenced by createSiblingComponent(), ISmaccComponent(), sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::onInitialize(), cl_move_base_z::CostmapSwitch::onInitialize(), cl_move_base_z::WaypointNavigator::onInitialize(), cl_move_base_z::PlannerSwitcher::PlannerSwitcher(), postEvent(), requiresClient(), and requiresComponent().
stateMachine_
ISmaccStateMachine* smacc::ISmaccComponent::stateMachine_ [protected]
Definition at line 63 of file component.h.
Referenced by onInitialize().
The documentation for this class was generated from the following files:
smacc/include/smacc/component.h
smacc/include/smacc/impl/smacc_component_impl.h
smacc/src/smacc/smacc_component.cpp