mecanum_drive_controller::SpeedLimiter Class Reference
#include <speed_limiter.h>
Public Member Functions
SpeedLimiter (bool has_velocity_limits=false, bool has_acceleration_limits=false, double min_velocity=0.0, double max_velocity=0.0, double min_acceleration=0.0, double max_acceleration=0.0)
Constructor.
void limit (double &v, double v0, double dt)
Limit the velocity and acceleration.
void limit_velocity (double &v)
Limit the velocity.
void limit_acceleration (double &v, double v0, double dt)
Limit the acceleration.
Public Attributes
bool has_velocity_limits
bool has_acceleration_limits
double min_velocity
double max_velocity
double min_acceleration
double max_acceleration
Detailed Description
Definition at line 77 of file speed_limiter.h.
Constructor & Destructor Documentation
SpeedLimiter()
mecanum_drive_controller::SpeedLimiter::SpeedLimiter (bool has_velocity_limits = false, bool has_acceleration_limits = false, double min_velocity = 0.0, double max_velocity = 0.0, double min_acceleration = 0.0, double max_acceleration = 0.0)
Constructor.
Parameters
 in has_velocity_limits if true, applies velocity limits
 in has_acceleration_limits if true, applies acceleration limits
 in min_velocity Minimum velocity [m/s], usually <= 0
 in max_velocity Maximum velocity [m/s], usually >= 0
 in min_acceleration Minimum acceleration [m/s^2], usually <= 0
 in max_acceleration Maximum acceleration [m/s^2], usually >= 0
Definition at line 52 of file speed_limiter.cpp.
  : has_velocity_limits(has_velocity_limits),
    has_acceleration_limits(has_acceleration_limits),
    min_velocity(min_velocity),
    max_velocity(max_velocity),
    min_acceleration(min_acceleration),
    max_acceleration(max_acceleration)
  {
  }
Member Function Documentation
limit()
void mecanum_drive_controller::SpeedLimiter::limit (double & v, double v0, double dt)
Limit the velocity and acceleration.
Parameters
 in,out v Velocity [m/s]
 in v0 Previous velocity [m/s]
 in dt Time step [s]
Definition at line 69 of file speed_limiter.cpp.
  {
    limit_velocity(v);
    limit_acceleration(v, v0, dt);
  }
References limit_acceleration(), and limit_velocity().
Referenced by mecanum_drive_controller::MecanumDriveController::update().
limit_acceleration()
void mecanum_drive_controller::SpeedLimiter::limit_acceleration (double & v, double v0, double dt)
Limit the acceleration.
Parameters
 in,out v Velocity [m/s]
 in v0 Previous velocity [m/s]
 in dt Time step [s]
Definition at line 83 of file speed_limiter.cpp.
  {
    if (has_acceleration_limits)
    {
      double dv = v - v0;
      const double dv_min = min_acceleration * dt;
      const double dv_max = max_acceleration * dt;
      dv = clamp(dv, dv_min, dv_max);
      v = v0 + dv;
    }
  }
References clamp(), has_acceleration_limits, max_acceleration, and min_acceleration.
Referenced by limit().
limit_velocity()
void mecanum_drive_controller::SpeedLimiter::limit_velocity (double & v)
Limit the velocity.
Parameters
 in,out v Velocity [m/s]
Definition at line 75 of file speed_limiter.cpp.
  {
    if (has_velocity_limits)
    {
      v = clamp(v, min_velocity, max_velocity);
    }
  }
References clamp(), has_velocity_limits, max_velocity, and min_velocity.
Referenced by limit().
Member Data Documentation
has_acceleration_limits
bool mecanum_drive_controller::SpeedLimiter::has_acceleration_limits
Definition at line 156 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_acceleration().
has_velocity_limits
bool mecanum_drive_controller::SpeedLimiter::has_velocity_limits
Definition at line 155 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_velocity().
max_acceleration
double mecanum_drive_controller::SpeedLimiter::max_acceleration
Definition at line 164 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_acceleration().
max_velocity
double mecanum_drive_controller::SpeedLimiter::max_velocity
Definition at line 160 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_velocity().
min_acceleration
double mecanum_drive_controller::SpeedLimiter::min_acceleration
Definition at line 163 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_acceleration().
min_velocity
double mecanum_drive_controller::SpeedLimiter::min_velocity
Definition at line 159 of file speed_limiter.h.
Referenced by mecanum_drive_controller::MecanumDriveController::init(), and limit_velocity().
The documentation for this class was generated from the following files:
submodules/ridgeback/ridgeback_control/include/mecanum_drive_controller/speed_limiter.h
submodules/ridgeback/ridgeback_control/src/speed_limiter.cpp