robot_controllers::ControllerManager Class Reference
Base class for a controller manager.
#include <controller_manager.h>
Public Member Functions
ControllerManager ()
virtual ~ControllerManager ()
Ensure proper shutdown with virtual destructor.
virtual int init (ros::NodeHandle &nh)
Startup the controller manager, loading default controllers.
virtual int requestStart (const std::string &name)
Start a controller.
virtual int requestStop (const std::string &name)
Stop a controller.
virtual void update (const ros::Time &time, const ros::Duration &dt)
Update active controllers.
virtual void reset ()
Reset all controllers.
bool addJointHandle (JointHandlePtr &j)
Add a joint handle.
HandlePtr getHandle (const std::string &name)
Get the handle associated with a particular joint/controller name.
JointHandlePtr getJointHandle (const std::string &name)
Get the joint handle associated with a particular joint name.
Private Types
typedef actionlib::SimpleActionServer< robot_controllers_msgs::QueryControllerStatesAction > server_t
typedef std::vector< ControllerLoaderPtr > ControllerList
typedef std::vector< JointHandlePtr > JointHandleList
Private Member Functions
void execute (const robot_controllers_msgs::QueryControllerStatesGoalConstPtr &goal)
Action callback.
void getState (robot_controllers_msgs::QueryControllerStatesResult &result)
Fill in the current state of controllers.
bool load (const std::string &name)
Load a controller.
Private Attributes
ControllerList controllers_
JointHandleList joints_
boost::shared_ptr< server_t > server_
Detailed Description
Base class for a controller manager.
Definition at line 48 of file controller_manager.h.
Member Typedef Documentation
ControllerList
typedef std::vector<ControllerLoaderPtr> robot_controllers::ControllerManager::ControllerList [private]
Definition at line 52 of file controller_manager.h.
JointHandleList
typedef std::vector<JointHandlePtr> robot_controllers::ControllerManager::JointHandleList [private]
Definition at line 53 of file controller_manager.h.
server_t
typedef actionlib::SimpleActionServer<robot_controllers_msgs::QueryControllerStatesAction> robot_controllers::ControllerManager::server_t [private]
Definition at line 50 of file controller_manager.h.
Constructor & Destructor Documentation
ControllerManager()
robot_controllers::ControllerManager::ControllerManager ()
Definition at line 37 of file controller_manager.cpp.
{
}
 ControllerManager()
virtual robot_controllers::ControllerManager::~ControllerManager () [inline], [virtual]
Ensure proper shutdown with virtual destructor.
Definition at line 59 of file controller_manager.h.
  {
  }
Member Function Documentation
addJointHandle()
bool robot_controllers::ControllerManager::addJointHandle (JointHandlePtr & j)
Add a joint handle.
Definition at line 206 of file controller_manager.cpp.
{
  // TODO: check for duplicate names?
  joints_.push_back(j);
  return true;
}
References joints_.
execute()
void robot_controllers::ControllerManager::execute (const robot_controllers_msgs::QueryControllerStatesGoalConstPtr & goal) [private]
Action callback.
Definition at line 246 of file controller_manager.cpp.
{
  robot_controllers_msgs::QueryControllerStatesFeedback feedback;
  robot_controllers_msgs::QueryControllerStatesResult result;
  for (size_t i = 0; i < goal->updates.size(); i++)
  {
    // Update this controller
    robot_controllers_msgs::ControllerState state = goal->updates[i];
    // Make sure controller exists
    bool in_controller_list = false;
    for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
    {
      if ((*c)->getController()->getName() == state.name)
      {
        if (state.type != "")
        {
          if (state.type == (*c)->getController()->getType())
          {
            in_controller_list = true;
            break;
          }
          else
          {
            std::stringstream ss;
            ss << "Controller " << state.name << " is of type " << (*c)->getController()->getType() << " not " << state.type;
            getState(result);
            server_->setAborted(result, ss.str());
            return;
          }
        }
        in_controller_list = true;
        break;
      }
    }
    if (!in_controller_list)
    {
      // Check if controller exists on parameter server
      ros::NodeHandle nh;
      if (nh.hasParam(state.name))
      {
        // Create controller (in a loader)
        if (!load(static_cast<std::string>(state.name)))
        {
          std::stringstream ss;
          ss << "Failed to load controller: " << state.name;
          getState(result);
          server_->setAborted(result, ss.str());
          return;
        }
      }
      else
      {
        std::stringstream ss;
        ss << "No such controller to update: " << state.name;
        getState(result);
        server_->setAborted(result, ss.str());
        return;
      }
    }
    // Update state
    if (state.state == state.STOPPED)
    {
      if (requestStop(state.name) != 0)
      {
        std::stringstream ss;
        ss << "Unable to stop " << state.name;
        getState(result);
        server_->setAborted(result, ss.str());
        return;
      }
    }
    else if (state.state == state.RUNNING)
    {
      if (requestStart(state.name) != 0)
      {
        std::stringstream ss;
        ss << "Unable to start " << state.name;
        getState(result);
        server_->setAborted(result, ss.str());
        return;
      }
    }
    else
    {
      std::stringstream ss;
      ss << "Invalid state for controller " << state.name << ": " << static_cast<int>(state.state);
      getState(result);
      server_->setAborted(result, ss.str());
      return;
    }
  }
  // Send result
  getState(result);
  server_->setSucceeded(result);
}
References gripper_keyboard::c, controllers_, getState(), get_controller_state::goal, load(), requestStart(), requestStop(), sick_camera_client::result, server_, and start_controller::state.
Referenced by init().
getHandle()
HandlePtr robot_controllers::ControllerManager::getHandle (const std::string & name)
Get the handle associated with a particular joint/controller name.
Parameters
name The name of the joint/controller.
Definition at line 213 of file controller_manager.cpp.
{
  // Try joints first
  for (JointHandleList::iterator j = joints_.begin(); j != joints_.end(); j++)
  {
    if ((*j)->getName() == name)
      return *j;
  }
  // Then controllers
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    if ((*c)->getController()->getName() == name)
      return (*c)->getController();
  }
  // Not found
  return HandlePtr();
}
References gripper_keyboard::c, controllers_, joints_, and start_controller::name.
getJointHandle()
JointHandlePtr robot_controllers::ControllerManager::getJointHandle (const std::string & name)
Get the joint handle associated with a particular joint name.
Parameters
name The name of the joint.
This is mainly a convienence function.
Definition at line 233 of file controller_manager.cpp.
{
  // Try joints first
  for (JointHandleList::iterator j = joints_.begin(); j != joints_.end(); j++)
  {
    if ((*j)->getName() == name)
      return *j;
  }
  // Not found
  return JointHandlePtr();
}
References joints_, and start_controller::name.
Referenced by robot_controllers::FollowJointTrajectoryController::init().
getState()
void robot_controllers::ControllerManager::getState (robot_controllers_msgs::QueryControllerStatesResult & result) [private]
Fill in the current state of controllers.
Definition at line 346 of file controller_manager.cpp.
{
  result.state.clear();
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    robot_controllers_msgs::ControllerState state;
    state.name = (*c)->getController()->getName();
    state.type = (*c)->getController()->getType();
    if ((*c)->isActive())
    {
      state.state = state.RUNNING;
    }
    else
    {
      state.state = state.STOPPED;
    }
    result.state.push_back(state);
  }
}
References gripper_keyboard::c, controllers_, sick_camera_client::result, and start_controller::state.
Referenced by execute().
init()
int robot_controllers::ControllerManager::init (ros::NodeHandle & nh) [virtual]
Startup the controller manager, loading default controllers.
Parameters
nh The proper node handle for finding parameters.
Returns
0 if success, negative values are error codes.
Note: JointHandles should be added before this is called.
Definition at line 41 of file controller_manager.cpp.
{
  // Find and load default controllers
  XmlRpc::XmlRpcValue controller_params;
  if (nh.getParam("default_controllers", controller_params))
  {
    if (controller_params.getType() != XmlRpc::XmlRpcValue::TypeArray)
    {
      ROS_ERROR_NAMED("ControllerManager", "Parameter 'default_controllers' should be a list.");
      return -1;
    }
    else
    {
      // Load each controller
      for (int c = 0; c < controller_params.size(); c++)
      {
        // Make sure name is valid
        XmlRpc::XmlRpcValue &controller_name = controller_params[c];
        if (controller_name.getType() != XmlRpc::XmlRpcValue::TypeString)
        {
          ROS_WARN_NAMED("ControllerManager", "Controller name is not a string?");
          continue;
        }
        // Create controller (in a loader)
        load(static_cast<std::string>(controller_name));
      }
    }
  }
  else
  {
    ROS_WARN_NAMED("ControllerManager", "No controllers loaded.");
    return -1;
  }
  // Setup actionlib server
  server_.reset(new server_t(nh, "/query_controller_states",
                             boost::bind(&ControllerManager::execute, this, _1),
                             false));
  server_->start();
  return 0;
}
References gripper_keyboard::c, execute(), load(), and server_.
load()
bool robot_controllers::ControllerManager::load (const std::string & name) [private]
Load a controller.
Definition at line 368 of file controller_manager.cpp.
{
  // Create controller (in a loader)
  ControllerLoaderPtr controller(new ControllerLoader());
  // Push back controller (so that autostart will work)
  controllers_.push_back(controller);
  // Now initialize controller
  if (!controller->init(name, this))
  {
    // Remove if init fails
    controllers_.pop_back();
    return false;
  }
  return true;
}
References controllers_, and start_controller::name.
Referenced by execute(), and init().
requestStart()
int robot_controllers::ControllerManager::requestStart (const std::string & name) [virtual]
Start a controller.
Definition at line 85 of file controller_manager.cpp.
{
  // Find requested controller
  ControllerLoaderPtr controller;
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    if ((*c)->getController()->getName() == name)
    {
      controller = *c;
      break;
    }
  }
  // Does controller exist?
  if (!controller)
  {
    ROS_ERROR_STREAM_NAMED("ControllerManager", "Unable to start " << name.c_str() << ": no such controller.");
    return -1;
  }
  // Is controller already running?
  if (controller->isActive())
  {
    ROS_DEBUG_STREAM_NAMED("ControllerManager", "Unable to start " << name.c_str() << ": already running.");
    return 0;
  }
  // Check for conflicts
  std::vector<std::string> names = controller->getController()->getCommandedNames();
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    // Only care about active controllers
    if (!(*c)->isActive())
      continue;
    std::vector<std::string> names2 = (*c)->getController()->getClaimedNames();
    bool conflict = false;
    for (size_t i = 0; i < names.size(); i++)
    {
      for (size_t i2 = 0; i2 < names2.size(); i2++)
      {
        if (names[i] == names2[i2])
        {
          conflict = true;
          break;
        }
      }
      if (conflict) break;
    }
    // Have conflict, try to stop controller (without force)
    if (conflict)
    {
      if ((*c)->stop(false))
      {
        ROS_INFO_STREAM_NAMED("ControllerManager", "Stopped " << (*c)->getController()->getName().c_str());
      }
      else
      {
        // Unable to stop c, cannot start controller
        ROS_ERROR_STREAM_NAMED("ControllerManager", "Unable to stop " <<
                                                    (*c)->getController()->getName().c_str() <<
                                                    " when trying to start " << name.c_str());
        return -1;
      }
    }
  }
  // Start controller
  if (controller->start())
  {
    ROS_INFO_STREAM_NAMED("ControllerManager", "Started " << controller->getController()->getName().c_str());
    return 0;
  }
  return -1; // Unable to start
}
References gripper_keyboard::c, controllers_, and start_controller::name.
Referenced by execute(), and robot_controllers::FollowJointTrajectoryController::executeCb().
requestStop()
int robot_controllers::ControllerManager::requestStop (const std::string & name) [virtual]
Stop a controller.
Definition at line 162 of file controller_manager.cpp.
{
  // Find controller
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    if ((*c)->getController()->getName() == name)
    {
      // Stop controller (with force)
      if ((*c)->stop(true))
      {
        ROS_INFO_STREAM_NAMED("ControllerManager", "Stopped " << (*c)->getController()->getName().c_str());
        return 0;
      }
      else
      {
        return -1; // controller decided not to stop
      }
    }
  }
  return -1; // no such controller
}
References gripper_keyboard::c, controllers_, and start_controller::name.
Referenced by execute(), robot_controllers::FollowJointTrajectoryController::executeCb(), robot_controllers::FollowJointTrajectoryController::reset(), robot_controllers::CartesianWrenchController::start(), robot_controllers::FollowJointTrajectoryController::update(), and robot_controllers::CartesianTwistController::update().
reset()
void robot_controllers::ControllerManager::reset () [virtual]
Reset all controllers.
Definition at line 197 of file controller_manager.cpp.
{
  // Update controllers
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    (*c)->reset();
  }
}
References gripper_keyboard::c, and controllers_.
update()
void robot_controllers::ControllerManager::update (const ros::Time & time, const ros::Duration & dt) [virtual]
Update active controllers.
Definition at line 184 of file controller_manager.cpp.
{
  // Reset handles
  for (JointHandleList::iterator j = joints_.begin(); j != joints_.end(); j++)
    (*j)->reset();
  // Update controllers
  for (ControllerList::iterator c = controllers_.begin(); c != controllers_.end(); c++)
  {
    (*c)->update(time, dt);
  }
}
References gripper_keyboard::c, controllers_, and joints_.
Member Data Documentation
controllers_
ControllerList robot_controllers::ControllerManager::controllers_ [private]
Definition at line 111 of file controller_manager.h.
Referenced by execute(), getHandle(), getState(), load(), requestStart(), requestStop(), reset(), and update().
joints_
JointHandleList robot_controllers::ControllerManager::joints_ [private]
Definition at line 112 of file controller_manager.h.
Referenced by addJointHandle(), getHandle(), getJointHandle(), and update().
server_
boost::shared_ptr<server_t> robot_controllers::ControllerManager::server_ [private]
Definition at line 114 of file controller_manager.h.
Referenced by execute(), and init().
The documentation for this class was generated from the following files:
submodules/robot_controllers/robot_controllers_interface/include/robot_controllers_interface/controller_manager.h
submodules/robot_controllers/robot_controllers_interface/src/controller_manager.cpp