robot_controllers::Controller Class Reference
Base class for a controller. Is derived from a Handle, so that controllers can be passed from ControllerManager::getHandle(), thus allowing controllers to access other controllers (to stack their commands.
#include <controller.h>
Public Member Functions
Controller ()
Default constructor, does almost nothing, all setup is done in init().
virtual ~Controller ()
Ensure proper cleanup with virtual destructor.
virtual int init (ros::NodeHandle &nh, ControllerManager *manager)
Initialize the controller and any required data structures.
virtual bool start ()=0
Attempt to start the controller. This should be called only by the ControllerManager instance.
virtual bool stop (bool force)=0
Attempt to stop the controller. This should be called only by the ControllerManager instance.
virtual bool reset ()=0
Cleanly reset the controller to it's initial state. Some controllers may choose to stop themselves. This is mainly used in the case of the the robot exiting some fault condition.
virtual void update (const ros::Time &time, const ros::Duration &dt)=0
This is the update loop for the controller.
std::string getName ()
Get the name of this controller.
virtual std::string getType ()
Get the type of this controller.
virtual std::vector< std::string > getCommandedNames ()=0
Get the names of joints/controllers which this controller commands.
virtual std::vector< std::string > getClaimedNames ()=0
Get the names of joints/controllers which this controller exclusively claims.
Private Attributes
std::string name_
Detailed Description
Base class for a controller. Is derived from a Handle, so that controllers can be passed from ControllerManager::getHandle(), thus allowing controllers to access other controllers (to stack their commands.
Definition at line 66 of file controller.h.
Constructor & Destructor Documentation
Controller()
robot_controllers::Controller::Controller () [inline]
Default constructor, does almost nothing, all setup is done in init().
Definition at line 72 of file controller.h.
  {
  }
 Controller()
virtual robot_controllers::Controller::~Controller () [inline], [virtual]
Ensure proper cleanup with virtual destructor.
Definition at line 77 of file controller.h.
  {
  }
Member Function Documentation
getClaimedNames()
virtual std::vector<std::string> robot_controllers::Controller::getClaimedNames () [pure virtual]
Get the names of joints/controllers which this controller exclusively claims.
Implemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::GravityCompensation, and robot_controllers::FollowJointTrajectoryController.
getCommandedNames()
virtual std::vector<std::string> robot_controllers::Controller::getCommandedNames () [pure virtual]
Get the names of joints/controllers which this controller commands.
Implemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::GravityCompensation, and robot_controllers::FollowJointTrajectoryController.
getName()
std::string robot_controllers::Controller::getName () [inline], [virtual]
Get the name of this controller.
Implements robot_controllers::Handle.
Definition at line 129 of file controller.h.
  {
    return name_;
  }
References name_.
Referenced by robot_controllers::FollowJointTrajectoryController::executeCb(), robot_controllers::FollowJointTrajectoryController::reset(), robot_controllers::CartesianWrenchController::start(), robot_controllers::FollowJointTrajectoryController::update(), and robot_controllers::CartesianTwistController::update().
getType()
virtual std::string robot_controllers::Controller::getType () [inline], [virtual]
Get the type of this controller.
Reimplemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::GravityCompensation, and robot_controllers::FollowJointTrajectoryController.
Definition at line 135 of file controller.h.
  {
    return "UnknownType";
  }
init()
virtual int robot_controllers::Controller::init (ros::NodeHandle & nh, ControllerManager * manager) [inline], [virtual]
Initialize the controller and any required data structures.
Parameters
nh Node handle for this controller.
manager The controller manager instance, this is needed for the controller to get information about joints, etc.
Returns
0 if succesfully configured, negative values are error codes.
Reimplemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::FollowJointTrajectoryController, and robot_controllers::GravityCompensation.
Definition at line 88 of file controller.h.
  {
    name_ = nh.getNamespace();
    // remove leading slash
    if (name_.at(0) == '/')
      name_.erase(0, 1);
    return 0;
  }
References name_.
Referenced by robot_controllers::FollowJointTrajectoryController::init().
reset()
virtual bool robot_controllers::Controller::reset () [pure virtual]
Cleanly reset the controller to it's initial state. Some controllers may choose to stop themselves. This is mainly used in the case of the the robot exiting some fault condition.
Returns
True if successfully reset, false otherwise.
Implemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::GravityCompensation, and robot_controllers::FollowJointTrajectoryController.
start()
virtual bool robot_controllers::Controller::start () [pure virtual]
Attempt to start the controller. This should be called only by the ControllerManager instance.
Returns
True if successfully started, false otherwise.
Implemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::FollowJointTrajectoryController, and robot_controllers::GravityCompensation.
Referenced by tuck_arm.MoveItThread::__init__().
stop()
virtual bool robot_controllers::Controller::stop (bool force) [pure virtual]
Attempt to stop the controller. This should be called only by the ControllerManager instance.
Parameters
force Should we force the controller to stop? Some controllers may wish to continue running until they absolutely have to stop.
Returns
True if successfully stopped, false otherwise.
Implemented in robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, robot_controllers::FollowJointTrajectoryController, and robot_controllers::GravityCompensation.
update()
virtual void robot_controllers::Controller::update (const ros::Time & time, const ros::Duration & dt) [pure virtual]
This is the update loop for the controller.
Parameters
time The system time.
dt The timestep since last call to update.
Implemented in robot_controllers::GravityCompensation, robot_controllers::CartesianTwistController, robot_controllers::CartesianPoseController, robot_controllers::CartesianWrenchController, robot_controllers::DiffDriveBaseController, robot_controllers::PointHeadController, robot_controllers::ParallelGripperController, robot_controllers::ScaledMimicController, and robot_controllers::FollowJointTrajectoryController.
Member Data Documentation
name_
std::string robot_controllers::Controller::name_ [private]
Definition at line 147 of file controller.h.
Referenced by getName(), and init().
The documentation for this class was generated from the following file:
submodules/robot_controllers/robot_controllers_interface/include/robot_controllers_interface/controller.h