sick_camera_server.PIM60 Class Reference
Public Member Functions
def __init__ (self, ip, port=2116)
def trigger (self)
def send (self, msg)
def recv (self, timeout=0.5)
Public Attributes
buf
sock
Detailed Description
Interface for the PIm60 camera
Definition at line 17 of file sick_camera_server.py.
Constructor & Destructor Documentation
__init__()
def sick_camera_server.PIM60.__init__ (self, ip, port = 2116)
Definition at line 19 of file sick_camera_server.py.
    def __init__(self, ip, port=2116):
        self.buf = ''
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.connect((ip, port))
        self.sock.settimeout(1.0)
Member Function Documentation
recv()
def sick_camera_server.PIM60.recv (self, timeout = 0.5)
Received respose, will strip <STX> and <ETX> from response message 
Definition at line 36 of file sick_camera_server.py.
    def recv(self, timeout = 0.5):
        """ Received respose, will strip <STX> and <ETX> from response message """
        buf = self.buf
        while buf.find(chr(3)) < 0:
            buf += self.sock.recv(1000)
        start_idx = buf.find(chr(2))
        if start_idx < 0:
            print(" Could not find STX in buffer :", self.prettyMsg(buf))
        elif start_idx != 0:
            print(" Garbage data before STX :", self.prettyMsg(buf[:start_idx+1]))
        stop_idx = buf.find(chr(3))
        # Store any following messages in buffer
        self.buf = buf[stop_idx+1:]
        # Make sure remaining message has a STX at begining
        if len(self.buf) and (self.buf[0] != chr(2)):
            print(" Extra garbage after ETX :", self.prettyMsg(buf[stop_idx+1:]))
        if start_idx > stop_idx:
            print(" Found stop before start", start_idx, stop_idx)
        return buf[start_idx+1:stop_idx]
References sick_camera_server.PIM60.buf, and sick_camera_server.PIM60.sock.
Referenced by sick_camera_server.PIM60.trigger().
send()
def sick_camera_server.PIM60.send (self, msg)
Sends messages to device 
Definition at line 31 of file sick_camera_server.py.
    def send(self, msg):
        """ Sends messages to device """
        print('SENT')
        self.sock.sendall(msg)
References sick_camera_server.PIM60.sock.
Referenced by sick_camera_server.PIM60.trigger().
trigger()
def sick_camera_server.PIM60.trigger (self)
Triggers the camera click
Definition at line 25 of file sick_camera_server.py.
    def trigger(self):
        """Triggers the camera click"""
        self.send("TRIG")
        resp = self.recv()
        print(resp)
References sick_camera_server.PIM60.recv(), and sick_camera_server.PIM60.send().
Member Data Documentation
buf
sick_camera_server.PIM60.buf
Definition at line 20 of file sick_camera_server.py.
Referenced by sick_camera_server.PIM60.recv().
sock
sick_camera_server.PIM60.sock
Definition at line 21 of file sick_camera_server.py.
Referenced by sick_camera_server.PIM60.recv(), and sick_camera_server.PIM60.send().
The documentation for this class was generated from the following file:
submodules/fetch_gazebo/fetchit_challenge/nodes/sick_camera_server.py