robot_controllers::SplineTrajectorySampler Class Reference
Sampler that uses splines.
#include <trajectory_spline_sampler.h>
Classes
struct Segment
Public Member Functions
SplineTrajectorySampler (const Trajectory &trajectory)
Construct a trajectory sampler.
virtual TrajectoryPoint sample (double time)
Sample from this trajectory.
virtual double end_time ()
Get the end time of our trajectory.
virtual Trajectory getTrajectory ()
Get the trajectory that we are sampling from.
Private Attributes
std::vector< Segment > segments_
Trajectory trajectory_
TrajectoryPoint result
int seg_
Detailed Description
Sampler that uses splines.
Definition at line 237 of file trajectory_spline_sampler.h.
Constructor & Destructor Documentation
SplineTrajectorySampler()
robot_controllers::SplineTrajectorySampler::SplineTrajectorySampler (const Trajectory & trajectory) [inline]
Construct a trajectory sampler.
Definition at line 249 of file trajectory_spline_sampler.h.
      {
        // This segment is from p to p+1
        segments_[p].start_time = trajectory.points[p].time;
        segments_[p].end_time = trajectory.points[p+1].time;
        // Set up spline
        segments_[p].splines.resize(num_joints);
        if (trajectory.points[p].qdd.size() == trajectory.points[p].q.size())
        {
          result.q.resize(num_joints);
          result.qd.resize(num_joints);
          result.qdd.resize(num_joints);
          // Have accelerations, will use Quintic.
          for (size_t j = 0; j < num_joints; ++j)
          {
            QuinticSpline(trajectory.points[p].q[j],
                          trajectory.points[p].qd[j],
                          trajectory.points[p].qdd[j],
                          trajectory.points[p+1].q[j],
                          trajectory.points[p+1].qd[j],
                          trajectory.points[p+1].qdd[j],
                          segments_[p].end_time - segments_[p].start_time,
                          segments_[p].splines[j]);
          }
          segments_[p].type = QUINTIC;
        }
        else if (trajectory.points[p].qd.size() == trajectory.points[p].q.size())
        {
          result.q.resize(num_joints);
          result.qd.resize(num_joints);
          // Velocities + Positions, do Cubic.
          for (size_t j = 0; j < num_joints; ++j)
          {
            CubicSpline(trajectory.points[p].q[j],
                        trajectory.points[p].qd[j],
                        trajectory.points[p+1].q[j],
                        trajectory.points[p+1].qd[j],
                        segments_[p].end_time - segments_[p].start_time,
                        segments_[p].splines[j]);
          }
          segments_[p].type = CUBIC;
        }
        else
        {
          result.q.resize(num_joints);
 
          // Lame -- only positions do linear
          for (size_t j = 0; j < num_joints; ++j)
          {
            LinearSpline(trajectory.points[p].q[j],
                         trajectory.points[p+1].q[j],
                         segments_[p].end_time - segments_[p].start_time,
                         segments_[p].splines[j]);
          }
          segments_[p].type = LINEAR;
        }
      }
    }
    seg_ = -1;
  }
  virtual TrajectoryPoint sample(double time)
  {
    // Which segment to sample from.
    while ((seg_ + 1 < int(segments_.size())) &&
           (segments_[seg_ + 1].start_time < time))
    {
      ++seg_;
    }
    // Check beginning of trajectory, return empty trajectory point if not started.
    if (seg_ == -1)
      return TrajectoryPoint();
    // Check end of trajectory, restrict time.
    if (time > end_time())
      time = end_time();
    // Sample segment for each joint.
    for (size_t i = 0; i < segments_[seg_].splines.size(); ++i)
    {
      if (segments_[seg_].type == QUINTIC)
      {
        sampleQuinticSpline(segments_[seg_].splines[i], time - segments_[seg_].start_time,
                            result.q[i], result.qd[i], result.qdd[i]);
      }
      else if(segments_[seg_].type == CUBIC)
      {
        sampleCubicSpline(segments_[seg_].splines[i], time - segments_[seg_].start_time,
                          result.q[i], result.qd[i]);
      }
      else
      {
References robot_controllers::CUBIC, robot_controllers::CubicSpline(), robot_controllers::LINEAR, robot_controllers::LinearSpline(), robot_controllers::TrajectoryPoint::q, robot_controllers::TrajectoryPoint::qd, robot_controllers::TrajectoryPoint::qdd, robot_controllers::QUINTIC, robot_controllers::QuinticSpline(), result, segments_, and prepare_simulated_robot::trajectory.
Member Function Documentation
end_time()
virtual double robot_controllers::SplineTrajectorySampler::end_time () [inline], [virtual]
Get the end time of our trajectory.
Implements robot_controllers::TrajectorySampler.
Definition at line 392 of file trajectory_spline_sampler.h.
getTrajectory()
virtual Trajectory robot_controllers::SplineTrajectorySampler::getTrajectory () [inline], [virtual]
Get the trajectory that we are sampling from.
Implements robot_controllers::TrajectorySampler.
Definition at line 398 of file trajectory_spline_sampler.h.
sample()
virtual TrajectoryPoint robot_controllers::SplineTrajectorySampler::sample (double time) [inline], [virtual]
Sample from this trajectory.
Implements robot_controllers::TrajectorySampler.
Definition at line 350 of file trajectory_spline_sampler.h.
  {
    return segments_[segments_.size()-1].end_time;
  }
  virtual Trajectory getTrajectory()
  {
    return trajectory_;
  }
private:
  std::vector<Segment> segments_;
  Trajectory trajectory_;
  TrajectoryPoint result;
  int seg_;
};
} // namespace robot_controllers
#endif // ROBOT_CONTROLLERS_TRAJECTORY_SPLINE_SAMPLER_H_
Member Data Documentation
result
TrajectoryPoint robot_controllers::SplineTrajectorySampler::result [private]
Definition at line 406 of file trajectory_spline_sampler.h.
Referenced by SplineTrajectorySampler().
seg_
int robot_controllers::SplineTrajectorySampler::seg_ [private]
Definition at line 407 of file trajectory_spline_sampler.h.
segments_
std::vector<Segment> robot_controllers::SplineTrajectorySampler::segments_ [private]
Definition at line 404 of file trajectory_spline_sampler.h.
Referenced by robot_controllers::sampleLinearSpline(), and SplineTrajectorySampler().
trajectory_
Trajectory robot_controllers::SplineTrajectorySampler::trajectory_ [private]
Definition at line 405 of file trajectory_spline_sampler.h.
The documentation for this class was generated from the following file:
submodules/robot_controllers/robot_controllers/include/robot_controllers/trajectory_spline_sampler.h