submodules/fetch_ros/fetch_ikfast_plugin/src/fetch_arm_ikfast_solver.cpp File Reference
#include `ikfast.h`
#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>
#include <stdexcept>
#include <sstream>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
Classes
struct CheckValue< T >
class IKSolver
Macros
#define IKFAST_HAS_LIBRARY
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
#define __PRETTY_FUNCTION__ __func__
#define IKFAST_ASSERT(b) { if(!(b)) { std::stringstream ss; ss << `ikfast exception: ` << __FILE__ << `:` << __LINE__ << `: ` <<__PRETTY_FUNCTION__ << `: Assertion '` << #b << `' failed`; throw std::runtime_error(ss.str()); } }
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#define IK2PI ((IkReal)6.28318530717959)
#define IKPI ((IkReal)3.14159265358979)
#define IKPI_2 ((IkReal)1.57079632679490)
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
Functions
IKFAST_COMPILE_ASSERT (IKFAST_VERSION==0x10000049)
void dgetrf_ (const int *m, const int *n, double *a, const int *lda, int *ipiv, int *info)
void zgetrf_ (const int *m, const int *n, std::complex< double > *a, const int *lda, int *ipiv, int *info)
void dgetri_ (const int *n, const double *a, const int *lda, int *ipiv, double *work, const int *lwork, int *info)
void dgesv_ (const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info)
void dgetrs_ (const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info)
void dgeev_ (const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi, double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info)
float IKabs (float f)
double IKabs (double f)
float IKsqr (float f)
double IKsqr (double f)
float IKlog (float f)
double IKlog (double f)
float IKasin (float f)
double IKasin (double f)
float IKfmod (float x, float y)
double IKfmod (double x, double y)
float IKacos (float f)
double IKacos (double f)
float IKsin (float f)
double IKsin (double f)
float IKcos (float f)
double IKcos (double f)
float IKtan (float f)
double IKtan (double f)
float IKsqrt (float f)
double IKsqrt (double f)
float IKatan2Simple (float fy, float fx)
float IKatan2 (float fy, float fx)
double IKatan2Simple (double fy, double fx)
double IKatan2 (double fy, double fx)
template<typename T >
CheckValue< T > IKatan2WithCheck (T fy, T fx, T epsilon)
float IKsign (float f)
double IKsign (double f)
template<typename T >
CheckValue< T > IKPowWithIntegerCheck (T f, int n)
IKFAST_API void ComputeFk (const IkReal *j, IkReal *eetrans, IkReal *eerot)
IKFAST_API int GetNumFreeParameters ()
IKFAST_API int * GetFreeParameters ()
IKFAST_API int GetNumJoints ()
IKFAST_API int GetIkRealSize ()
IKFAST_API int GetIkType ()
IKFAST_API bool ComputeIk (const IkReal *eetrans, const IkReal *eerot, const IkReal *pfree, IkSolutionListBase< IkReal > &solutions)
IKFAST_API bool ComputeIk2 (const IkReal *eetrans, const IkReal *eerot, const IkReal *pfree, IkSolutionListBase< IkReal > &solutions, void *pOpenRAVEManip)
const IKFAST_API char * GetKinematicsHash ()
const IKFAST_API char * GetIkFastVersion ()
int main (int argc, char **argv)
Macro Definition Documentation
__PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
Definition at line 46 of file fetch_arm_ikfast_solver.cpp.
IK2PI
#define IK2PI ((IkReal)6.28318530717959)
Definition at line 59 of file fetch_arm_ikfast_solver.cpp.
IKFAST_ALIGNED16
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
Definition at line 56 of file fetch_arm_ikfast_solver.cpp.
IKFAST_ASSERT
#define IKFAST_ASSERT(b) { if(!(b)) { std::stringstream ss; ss << `ikfast exception: ` << __FILE__ << `:` << __LINE__ << `: ` <<__PRETTY_FUNCTION__ << `: Assertion '` << #b << `' failed`; throw std::runtime_error(ss.str()); } }
Definition at line 49 of file fetch_arm_ikfast_solver.cpp.
IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
Definition at line 107 of file fetch_arm_ikfast_solver.cpp.
IKFAST_COMPILE_ASSERT
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
Definition at line 25 of file fetch_arm_ikfast_solver.cpp.
IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
Definition at line 117 of file fetch_arm_ikfast_solver.cpp.
IKFAST_HAS_LIBRARY
#define IKFAST_HAS_LIBRARY
autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
Author
Rosen Diankov
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
ikfast version 0x10000049 generated on 2016-08-23 13:37:00.154880 To compile with gcc: gcc -lstdc++ ik.cpp To compile without any main function as a shared object (might need -llapack): gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
Definition at line 20 of file fetch_arm_ikfast_solver.cpp.
IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
Definition at line 102 of file fetch_arm_ikfast_solver.cpp.
IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
Definition at line 112 of file fetch_arm_ikfast_solver.cpp.
IKPI
#define IKPI ((IkReal)3.14159265358979)
Definition at line 60 of file fetch_arm_ikfast_solver.cpp.
IKPI_2
#define IKPI_2 ((IkReal)1.57079632679490)
Definition at line 61 of file fetch_arm_ikfast_solver.cpp.
Function Documentation
ComputeFk()
IKFAST_API void ComputeFk (const IkReal * j, IkReal * eetrans, IkReal * eerot)
solves the forward kinematics equations.
Parameters
pfree is an array specifying the free joints of the chain.
Definition at line 299 of file fetch_arm_ikfast_solver.cpp.
                                                                           {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59;
x0=IKsin(j[2]);
x1=IKsin(j[5]);
x2=IKsin(j[4]);
x3=IKcos(j[4]);
x4=IKcos(j[2]);
x5=IKcos(j[3]);
x6=IKsin(j[1]);
x7=IKsin(j[3]);
x8=IKcos(j[5]);
x9=IKcos(j[1]);
x10=IKsin(j[0]);
x11=IKcos(j[0]);
x12=IKcos(j[6]);
x13=IKsin(j[6]);
x14=((1.0)*x1);
x15=((1.0)*x13);
x16=((1.0)*x9);
x17=((1.0)*x12);
x18=((0.1385)*x3);
x19=((1.0)*x6);
x20=((1.0)*x3);
x21=((1.0)*x4);
x22=((1.0)*x8);
x23=(x0*x3);
x24=(x5*x9);
x25=(x0*x7);
x26=(x2*x4);
x27=(x0*x2);
x28=(x5*x6);
x29=(x4*x7);
x30=((0.3215)*x25);
x31=(x19*x7);
x32=((0.1385)*x29);
x33=(x19*x29);
x34=((1.0)*x27*x5);
x35=((0.1385)*x25*x8);
x36=(x16*x27);
x37=(x16*x23);
x38=(((x23*x5))+x26);
x39=((((-1.0)*x34))+((x3*x4)));
x40=((((-1.0)*x31))+((x24*x4)));
x41=(x34+(((-1.0)*x20*x4)));
x42=((((-1.0)*x16*x4*x5))+x31);
x43=(((x16*x7))+((x19*x4*x5)));
x44=((-1.0)*x43);
x45=(((x0*x18*x5))+(((0.1385)*x26)));
x46=((((-1.0)*x19*x5))+(((-1.0)*x16*x29)));
x47=(x30+x35);
x48=(x2*x42);
x49=(x2*x43);
x50=(((x14*x25))+(((-1.0)*x22*x38)));
x51=(((x27*x6))+((x3*x44)));
x52=((1.0)*x50);
x53=(x13*x50);
x54=(((x8*(((((-1.0)*x33))+x24))))+((x1*x51)));
x55=(((x8*(((((-1.0)*x36))+((x3*x40))))))+((x1*x46)));
x56=(((x14*(((((-1.0)*x33))+((x16*x5))))))+(((-1.0)*x22*x51)));
x57=((((0.352)*x9))+(((0.3215)*x24))+(((-0.3215)*x29*x6))+((x1*(((((0.1385)*x27*x6))+((x18*x44))))))+((x8*(((((-1.0)*x32*x6))+(((0.1385)*x24)))))));
x58=(((x13*x56))+((x12*((((x23*x6))+x49)))));
x59=(((x12*x56))+((x13*(((((-1.0)*x49))+(((-1.0)*x19*x23)))))));
eerot[0]=(((x11*x54))+((x10*(((((-1.0)*x14*x38))+(((-1.0)*x22*x25)))))));
eerot[1]=(((x10*(((((-1.0)*x17*x39))+(((-1.0)*x15*x50))))))+((x11*x58)));
eerot[2]=(((x11*x59))+((x10*(((((-1.0)*x15*x41))+(((-1.0)*x17*x50)))))));
eetrans[0]=((0.119525)+((x10*(((((-1.0)*x47))+(((-1.0)*x14*x45))))))+((x11*x57))+(((0.117)*x11)));
eerot[3]=(((x11*((((x1*x38))+((x25*x8))))))+((x10*x54)));
eerot[4]=(((x11*((x53+((x12*x39))))))+((x10*x58)));
eerot[5]=(((x11*((((x12*x50))+((x13*x41))))))+((x10*x59)));
eetrans[1]=(((x10*x57))+((x11*((x47+((x1*x45))))))+(((0.117)*x10)));
eerot[6]=(((x1*(((((-1.0)*x20*x40))+x36))))+((x46*x8)));
eerot[7]=(((x13*x55))+((x12*(((((-1.0)*x48))+x37)))));
eerot[8]=(((x12*x55))+((x13*(((((-1.0)*x37))+x48)))));
eetrans[2]=((0.40858)+(((-0.3215)*x29*x9))+(((-0.3215)*x28))+((x1*(((((0.1385)*x27*x9))+(((-1.0)*x18*x40))))))+(((-0.352)*x6))+((x8*(((((-1.0)*x32*x9))+(((-0.1385)*x28)))))));
}
References IKcos(), and IKsin().
Referenced by fetch_arm::IKFastKinematicsPlugin::getPositionFK().
ComputeIk()
IKFAST_API bool ComputeIk (const IkReal * eetrans, const IkReal * eerot, const IkReal * pfree, IkSolutionListBase< IkReal > & solutions)
solves the inverse kinematics equations.
Parameters
pfree is an array specifying the free joints of the chain.
Definition at line 17437 of file fetch_arm_ikfast_solver.cpp.
                                                                                                                                  {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}
References IKSolver::ComputeIk().
Referenced by main(), and fetch_arm::IKFastKinematicsPlugin::solve().
ComputeIk2()
IKFAST_API bool ComputeIk2 (const IkReal * eetrans, const IkReal * eerot, const IkReal * pfree, IkSolutionListBase< IkReal > & solutions, void * pOpenRAVEManip)
Definition at line 17442 of file fetch_arm_ikfast_solver.cpp.
                                                                                                                                                         {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}
References IKSolver::ComputeIk().
dgeev_()
void dgeev_ (const char * jobvl, const char * jobvr, const int * n, double * a, const int * lda, double * wr, double * wi, double * vl, const int * ldvl, double * vr, const int * ldvr, double * work, const int * lwork, int * info)
dgesv_()
void dgesv_ (const int * n, const int * nrhs, double * a, const int * lda, int * ipiv, double * b, const int * ldb, int * info)
dgetrf_()
void dgetrf_ (const int * m, const int * n, double * a, const int * lda, int * ipiv, int * info)
dgetri_()
void dgetri_ (const int * n, const double * a, const int * lda, int * ipiv, double * work, const int * lwork, int * info)
dgetrs_()
void dgetrs_ (const char * trans, const int * n, const int * nrhs, double * a, const int * lda, int * ipiv, double * b, const int * ldb, int * info)
GetFreeParameters()
IKFAST_API int* GetFreeParameters ()
Definition at line 376 of file fetch_arm_ikfast_solver.cpp.
{ static int freeparams[] = {0}; return freeparams; }
Referenced by fetch_arm::IKFastKinematicsPlugin::initialize().
GetIkFastVersion()
const IKFAST_API char* GetIkFastVersion ()
Definition at line 17449 of file fetch_arm_ikfast_solver.cpp.
{ return "0x10000049"; }
GetIkRealSize()
IKFAST_API int GetIkRealSize ()
Definition at line 379 of file fetch_arm_ikfast_solver.cpp.
{ return sizeof(IkReal); }
GetIkType()
IKFAST_API int GetIkType ()
Definition at line 381 of file fetch_arm_ikfast_solver.cpp.
{ return 0x67000001; }
Referenced by fetch_arm::IKFastKinematicsPlugin::getPositionFK(), and fetch_arm::IKFastKinematicsPlugin::solve().
GetKinematicsHash()
const IKFAST_API char* GetKinematicsHash ()
Definition at line 17447 of file fetch_arm_ikfast_solver.cpp.
{ return "<robot:GenericRobot - fetch (a5ffee371c921db78a56e98f69ac61f1)>"; }
GetNumFreeParameters()
IKFAST_API int GetNumFreeParameters ()
Definition at line 375 of file fetch_arm_ikfast_solver.cpp.
{ return 1; }
Referenced by fetch_arm::IKFastKinematicsPlugin::initialize(), and main().
GetNumJoints()
IKFAST_API int GetNumJoints ()
Definition at line 377 of file fetch_arm_ikfast_solver.cpp.
{ return 7; }
Referenced by main().
IKabs() [1/2]
double IKabs (double f) [inline]
Definition at line 92 of file fetch_arm_ikfast_solver.cpp.
{ return fabs(f); }
IKabs() [2/2]
float IKabs (float f) [inline]
Definition at line 91 of file fetch_arm_ikfast_solver.cpp.
{ return fabsf(f); }
Referenced by IKSolver::ComputeIk(), IKatan2WithCheck(), IKSolver::polyroots4(), IKSolver::polyroots5(), IKSolver::polyroots6(), IKSolver::polyroots7(), IKSolver::polyroots8(), and IKSolver::rotationfunction0().
IKacos() [1/2]
double IKacos (double f) [inline]
Definition at line 161 of file fetch_arm_ikfast_solver.cpp.
{
IKFAST_ASSERT(f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH); // any more error implies something is wrong with the solver
if(f <= -1) return IKPI;
else if(f >= 1) return 0;
return acos(f);
}
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI.
IKacos() [2/2]
float IKacos (float f) [inline]
Definition at line 154 of file fetch_arm_ikfast_solver.cpp.
{
IKFAST_ASSERT(f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH); // any more error implies something is wrong with the solver
if(f <= -1) return float(IKPI);
else if(f >= 1) return float(0);
return acosf(f);
}
References pick_and_place::float, IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKasin() [1/2]
double IKasin (double f) [inline]
Definition at line 128 of file fetch_arm_ikfast_solver.cpp.
{
IKFAST_ASSERT(f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH); // any more error implies something is wrong with the solver
if(f <= -1) return -IKPI_2;
else if(f >= 1) return IKPI_2;
return asin(f);
}
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI_2.
IKasin() [2/2]
float IKasin (float f) [inline]
Definition at line 121 of file fetch_arm_ikfast_solver.cpp.
{
IKFAST_ASSERT(f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH); // any more error implies something is wrong with the solver
if(f <= -1) return float(-IKPI_2);
else if(f >= 1) return float(IKPI_2);
return asinf(f);
}
References pick_and_place::float, IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI_2.
Referenced by IKSolver::ComputeIk().
IKatan2() [1/2]
double IKatan2 (double fy, double fx) [inline]
Definition at line 192 of file fetch_arm_ikfast_solver.cpp.
                                            {
    if(std::isnan(fy)) {
        IKFAST_ASSERT(!std::isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if(std::isnan(fx)) {
        return 0;
    }
    return atan2(fy,fx);
}
References IKFAST_ASSERT, and IKPI_2.
IKatan2() [2/2]
float IKatan2 (float fy, float fx) [inline]
Definition at line 179 of file fetch_arm_ikfast_solver.cpp.
                                         {
    if(std::isnan(fy)) {
        IKFAST_ASSERT(!std::isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if(std::isnan(fx)) {
        return 0;
    }
    return atan2f(fy,fx);
}
References pick_and_place::float, IKFAST_ASSERT, and IKPI_2.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKatan2Simple() [1/2]
double IKatan2Simple (double fy, double fx) [inline]
Definition at line 189 of file fetch_arm_ikfast_solver.cpp.
                                                  {
    return atan2(fy,fx);
}
IKatan2Simple() [2/2]
float IKatan2Simple (float fy, float fx) [inline]
Definition at line 176 of file fetch_arm_ikfast_solver.cpp.
                                               {
    return atan2f(fy,fx);
}
Referenced by IKatan2WithCheck().
IKatan2WithCheck()
template<typename T >
CheckValue<T> IKatan2WithCheck (T fy, T fx, T epsilon) [inline]
Definition at line 211 of file fetch_arm_ikfast_solver.cpp.
{
    CheckValue<T> ret;
    ret.valid = false;
    ret.value = 0;
    if(!std::isnan(fy) && !std::isnan(fx)) {
        if(IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}
References IKabs(), IKatan2Simple(), IKFAST_ATAN2_MAGTHRESH, CheckValue< T >::valid, and CheckValue< T >::value.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKcos() [1/2]
double IKcos (double f) [inline]
Definition at line 171 of file fetch_arm_ikfast_solver.cpp.
{ return cos(f); }
IKcos() [2/2]
float IKcos (float f) [inline]
Definition at line 170 of file fetch_arm_ikfast_solver.cpp.
{ return cosf(f); }
Referenced by ComputeFk(), IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKFAST_COMPILE_ASSERT()
IKFAST_COMPILE_ASSERT (IKFAST_VERSION = =0x10000049)
IKfmod() [1/2]
double IKfmod (double x, double y) [inline]
Definition at line 146 of file fetch_arm_ikfast_solver.cpp.
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}
References pick_and_place::y.
IKfmod() [2/2]
float IKfmod (float x, float y) [inline]
Definition at line 137 of file fetch_arm_ikfast_solver.cpp.
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}
References pick_and_place::y.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKlog() [1/2]
double IKlog (double f) [inline]
Definition at line 98 of file fetch_arm_ikfast_solver.cpp.
{ return log(f); }
IKlog() [2/2]
float IKlog (float f) [inline]
Definition at line 97 of file fetch_arm_ikfast_solver.cpp.
{ return logf(f); }
IKPowWithIntegerCheck()
template<typename T >
CheckValue<T> IKPowWithIntegerCheck (T f, int n) [inline]
Definition at line 246 of file fetch_arm_ikfast_solver.cpp.
{
    CheckValue<T> ret;
    ret.valid = true;
    if(n == 0) {
        ret.value = 1.0;
        return ret;
    }
    else if(n == 1)
    {
        ret.value = f;
        return ret;
    }
    else if(n < 0)
    {
        if(f == 0)
        {
            ret.valid = false;
            ret.value = (T)1.0e30;
            return ret;
        }
        if(n == -1) {
            ret.value = T(1.0)/f;
            return ret;
        }
    }
    int num = n > 0 ? n : -n;
    if(num == 2) {
        ret.value = f*f;
    }
    else if(num == 3) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if(num & 1) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if(n < 0) {
        ret.value = T(1.0)/ret.value;
    }
    return ret;
}
References CheckValue< T >::valid, and CheckValue< T >::value.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKsign() [1/2]
double IKsign (double f) [inline]
Definition at line 235 of file fetch_arm_ikfast_solver.cpp.
                               {
    if(f > 0) {
        return 1.0;
    }
    else if(f < 0) {
        return -1.0;
    }
    return 0;
}
IKsign() [2/2]
float IKsign (float f) [inline]
Definition at line 225 of file fetch_arm_ikfast_solver.cpp.
                             {
    if(f > 0) {
        return float(1);
    }
    else if(f < 0) {
        return float(-1);
    }
    return 0;
}
References pick_and_place::float.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKsin() [1/2]
double IKsin (double f) [inline]
Definition at line 169 of file fetch_arm_ikfast_solver.cpp.
{ return sin(f); }
IKsin() [2/2]
float IKsin (float f) [inline]
Definition at line 168 of file fetch_arm_ikfast_solver.cpp.
{ return sinf(f); }
Referenced by ComputeFk(), IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKsqr() [1/2]
double IKsqr (double f) [inline]
Definition at line 95 of file fetch_arm_ikfast_solver.cpp.
{ return f*f; }
IKsqr() [2/2]
float IKsqr (float f) [inline]
Definition at line 94 of file fetch_arm_ikfast_solver.cpp.
{ return f*f; }
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKsqrt() [1/2]
double IKsqrt (double f) [inline]
Definition at line 175 of file fetch_arm_ikfast_solver.cpp.
{ if(f <= 0.0) return 0.0; return sqrt(f); }
IKsqrt() [2/2]
float IKsqrt (float f) [inline]
Definition at line 174 of file fetch_arm_ikfast_solver.cpp.
{ if(f <= 0.0f) return 0.0f; return sqrtf(f); }
Referenced by IKSolver::ComputeIk(), IKSolver::polyroots2(), and IKSolver::rotationfunction0().
IKtan() [1/2]
double IKtan (double f) [inline]
Definition at line 173 of file fetch_arm_ikfast_solver.cpp.
{ return tan(f); }
IKtan() [2/2]
float IKtan (float f) [inline]
Definition at line 172 of file fetch_arm_ikfast_solver.cpp.
{ return tanf(f); }
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
main()
int main (int argc, char ** argv)
Definition at line 17461 of file fetch_arm_ikfast_solver.cpp.
{
    if(argc != 12+GetNumFreeParameters()+1) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }
    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);
    if(!bSuccess) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }
    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for(std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}
References ComputeIk(), ikfast::IkSolutionBase< T >::GetFree(), GetNumFreeParameters(), GetNumJoints(), ikfast::IkSolutionList< T >::GetNumSolutions(), ikfast::IkSolutionBase< T >::GetSolution(), and ikfast::IkSolutionList< T >::GetSolution().
zgetrf_()
void zgetrf_ (const int * m, const int * n, std::complex< double > * a, const int * lda, int * ipiv, int * info)