submodules/fetch_ros/fetch_teleop/src/joystick_teleop.cpp File Reference
#include <algorithm>
#include <boost/thread/mutex.hpp>
#include <ros/ros.h>
#include <actionlib/client/simple_action_client.h>
#include <control_msgs/FollowJointTrajectoryAction.h>
#include <control_msgs/GripperCommandAction.h>
#include <geometry_msgs/TwistStamped.h>
#include <nav_msgs/Odometry.h>
#include <sensor_msgs/JointState.h>
#include <sensor_msgs/Joy.h>
#include <topic_tools/MuxSelect.h>
Classes
class TeleopComponent
class BaseTeleop
class FollowTeleop
class GripperTeleop
class HeadTeleop
class ArmTeleop
class Teleop
Functions
double integrate (double desired, double present, double max_rate, double dt)
int main (int argc, char **argv)
Function Documentation
integrate()
double integrate (double desired, double present, double max_rate, double dt)
Definition at line 50 of file joystick_teleop.cpp.
{
  if (desired > present)
    return std::min(desired, present + max_rate * dt);
  else
    return std::max(desired, present - max_rate * dt);
}
Referenced by BaseTeleop::publish(), FollowTeleop::publish(), HeadTeleop::publish(), and ArmTeleop::publish().
main()
int main (int argc, char ** argv)
Definition at line 856 of file joystick_teleop.cpp.
{
  ros::init(argc, argv, "teleop");
  ros::NodeHandle n("~");
  Teleop teleop;
  teleop.init(n);
  ros::Rate r(30.0);
  while (ros::ok())
  {
    ros::spinOnce();
    teleop.publish(ros::Duration(1/30.0));
    r.sleep();
  }
  return 0;
}
References Teleop::init(), Teleop::publish(), and fake_cube_perception_node::r.