simple_grasping Namespace Reference
Classes
class BasicGraspingPerception
ROS wrapper for shape grasp planner + object support segmentation.
class ObjectSupportSegmentation
Class that segments a point cloud into objects and supporting surfaces.
class ShapeGraspPlanner
A simple grasp planner that uses the bounding box shape to generate viable grasps.
Functions
void hsv2rgb (const float h, const float s, const float v, float &r, float &g, float &b)
Fill in RGB values from HSV values.
void colorizeCloud (pcl::PointCloud< pcl::PointXYZRGB > &cloud, float hue)
Update rgb component of an XYZRGB cloud to a new HSV color.
template<typename PointT >
double distancePointToPlane (const PointT &point, const pcl::ModelCoefficients::Ptr plane)
Get distance from point to plane.
double distancePointToPlane (const Eigen::Vector4f &point, const pcl::ModelCoefficients::Ptr plane)
Get distance from point to plane.
bool extractShape (const pcl::PointCloud< pcl::PointXYZRGB > &input, pcl::PointCloud< pcl::PointXYZRGB > &output, shape_msgs::SolidPrimitive &shape, geometry_msgs::Pose &pose)
Find the smallest shape primitive we can fit around this object.
bool extractShape (const pcl::PointCloud< pcl::PointXYZRGB > &input, const pcl::ModelCoefficients::Ptr model, pcl::PointCloud< pcl::PointXYZRGB > &output, shape_msgs::SolidPrimitive &shape, geometry_msgs::Pose &pose)
Find the smallest shape primitive we can fit around this object, given the plane parameters.
bool extractUnorientedBoundingBox (const pcl::PointCloud< pcl::PointXYZRGB > &input, shape_msgs::SolidPrimitive &shape, geometry_msgs::Pose &pose)
Find a bounding box around a cloud. This method does not attempt to find best orientation and so the bounding box will be oriented with the frame of the cloud.
moveit_msgs::GripperTranslation makeGripperTranslation (std::string frame, double min, double desired, double x_axis=1.0, double y_axis=0.0, double z_axis=0.0)
Eigen::Quaterniond quaternionFromEuler (float yaw, float pitch, float roll)
Function Documentation
colorizeCloud()
void simple_grasping::colorizeCloud (pcl::PointCloud< pcl::PointXYZRGB > & cloud, float hue)
Update rgb component of an XYZRGB cloud to a new HSV color.
Parameters
cloud The cloud to update.
hue The hue to apply.
Definition at line 67 of file cloud_tools.cpp.
{
  std::vector<pcl::PCLPointField> fields;
  pcl::getFields(cloud, fields);
  size_t rgb_field_index;
  for (rgb_field_index = 0; rgb_field_index < fields.size(); ++rgb_field_index)
  {
    if (fields[rgb_field_index].name == "rgb" ||
        fields[rgb_field_index].name == "rgba")
      break;
  }
  float r, g, b;
  hsv2rgb(hue, 0.8 /*saturation*/, 1.0 /*value*/, r, g, b);
  for (size_t j = 0; j < cloud.points.size(); ++j)
  {
    pcl::PointXYZRGB &p = cloud.points[j];
    unsigned char* pt_rgb = (unsigned char*) &p;
    pt_rgb += fields[rgb_field_index].offset;
    (*pt_rgb) = (unsigned char) (r * 255);
    (*(pt_rgb+1)) = (unsigned char) (g * 255);
    (*(pt_rgb+2)) = (unsigned char) (b * 255);
  }
}
References hsv2rgb(), start_controller::name, and fake_cube_perception_node::r.
Referenced by simple_grasping::ObjectSupportSegmentation::segment().
distancePointToPlane() [1/2]
double simple_grasping::distancePointToPlane (const Eigen::Vector4f & point, const pcl::ModelCoefficients::Ptr plane)
Get distance from point to plane.
Parameters
point The point.
plane Plane coefficients.
Definition at line 93 of file cloud_tools.cpp.
{
  Eigen::Vector4f pp(point);
  pp[3] = 1.0;
  Eigen::Vector4f m(plane->values[0], plane->values[1], plane->values[2], plane->values[3]);
  return pp.dot(m);
}
distancePointToPlane() [2/2]
template<typename PointT >
double simple_grasping::distancePointToPlane (const PointT & point, const pcl::ModelCoefficients::Ptr plane)
Get distance from point to plane.
Parameters
point The point.
plane Plane coefficients.
Definition at line 71 of file cloud_tools.h.
{
  Eigen::Vector4f pp(point.x, point.y, point.z, 1);
  Eigen::Vector4f m(plane->values[0], plane->values[1], plane->values[2], plane->values[3]);
  return pp.dot(m);
}
Referenced by simple_grasping::ObjectSupportSegmentation::segment().
extractShape() [1/2]
bool simple_grasping::extractShape (const pcl::PointCloud< pcl::PointXYZRGB > & input, const pcl::ModelCoefficients::Ptr model, pcl::PointCloud< pcl::PointXYZRGB > & output, shape_msgs::SolidPrimitive & shape, geometry_msgs::Pose & pose)
Find the smallest shape primitive we can fit around this object, given the plane parameters.
Parameters
input Point Cloud of the object.
model Model coefficients for the plane.
output Point Cloud transformed to the pose frame of the shape primitive fit.
shape Returned smallest shape primitive fit.
pose The pose of the shape primitive fit.
Returns
True if a shape was extracted, false if we have a failure.
Definition at line 41 of file shape_extraction.cpp.
{
  // Used to decide between various shapes
  double min_volume = 1000.0; // the minimum volume shape found thus far.
  Eigen::Matrix3f transformation; // the transformation for the best-fit shape
  // Compute z height as maximum distance from planes
  double height = 0.0;
  for (size_t i = 0; i < input.size(); ++i)
  {
    Eigen::Vector4f pp(input[i].x, input[i].y, input[i].z, 1);
    Eigen::Vector4f m(model->values[0], model->values[1], model->values[2], model->values[3]);
    double distance_to_plane = fabs(pp.dot(m));
    if (distance_to_plane > height)
      height = distance_to_plane;
  }
  // Project object into 2d, using plane model coefficients
  pcl::PointCloud<pcl::PointXYZRGB>::Ptr flat(new pcl::PointCloud<pcl::PointXYZRGB>);
  pcl::ProjectInliers<pcl::PointXYZRGB> projection;
  projection.setModelType(pcl::SACMODEL_PLANE);
  projection.setInputCloud(input.makeShared()); // stupid API
  projection.setModelCoefficients(model);
  projection.filter(*flat);
  // Rotate plane so that Z=0
  pcl::PointCloud<pcl::PointXYZRGB>::Ptr flat_projected(new pcl::PointCloud<pcl::PointXYZRGB>);
  Eigen::Vector3f normal(model->values[0], model->values[1], model->values[2]);
  Eigen::Quaternionf qz; qz.setFromTwoVectors(normal, Eigen::Vector3f::UnitZ());
  Eigen::Matrix3f plane_rotation = qz.toRotationMatrix();
  Eigen::Matrix3f inv_plane_rotation = plane_rotation.inverse();
  for (size_t i = 0; i < flat->size(); ++i)
  {
    pcl::PointXYZRGB p;
    p.getVector3fMap() = plane_rotation * (*flat)[i].getVector3fMap();
    flat_projected->push_back(p);
  }
  // Find the convex hull
  pcl::PointCloud<pcl::PointXYZRGB> hull;
  pcl::ConvexHull<pcl::PointXYZRGB> convex_hull;
  convex_hull.setInputCloud(flat_projected);
  convex_hull.setDimension(2);
  convex_hull.reconstruct(hull);
  // Try fitting a rectangle
  shape_msgs::SolidPrimitive rect; // the best-fit rectangle
  rect.type = rect.BOX;
  rect.dimensions.resize(3);
  for (size_t i = 0; i < hull.size() - 1; ++i)
  {
    // For each pair of hull points, determine the angle
    double rise = hull[i+1].y - hull[i].y;
    double run = hull[i+1].x - hull[i].x;
    // and normalize..
    {
      double l = sqrt((rise * rise) + (run * run));
      rise = rise/l;
      run = run/l;
    }
    // Build rotation matrix from change of basis
    Eigen::Matrix3f rotation;
    rotation(0, 0) = run;
    rotation(0, 1) = rise;
    rotation(0, 2) = 0.0;
    rotation(1, 0) = -rise;
    rotation(1, 1) = run;
    rotation(1, 2) = 0.0;
    rotation(2, 0) = 0.0;
    rotation(2, 1) = 0.0;
    rotation(2, 2) = 1.0;
    Eigen::Matrix3f inv_rotation = rotation.inverse();
    // Project hull to new coordinate system
    pcl::PointCloud<pcl::PointXYZRGB> projected_cloud;
    for (size_t j = 0; j < hull.size(); ++j)
    {
      pcl::PointXYZRGB p;
      p.getVector3fMap() = rotation * hull[j].getVector3fMap();
      projected_cloud.push_back(p);
    }
    // Compute min/max
    double x_min = 1000.0;
    double x_max = -1000.0;
    double y_min = 1000.0;
    double y_max = -1000.0;
    for (size_t j = 0; j < projected_cloud.size(); ++j)
    {
      if (projected_cloud[j].x < x_min)
        x_min = projected_cloud[j].x;
      if (projected_cloud[j].x > x_max)
        x_max = projected_cloud[j].x;
      if (projected_cloud[j].y < y_min)
        y_min = projected_cloud[j].y;
      if (projected_cloud[j].y > y_max)
        y_max = projected_cloud[j].y;
    }
    // Is this the best estimate?
    double area = (x_max - x_min) * (y_max - y_min);
    if (area*height < min_volume)
    {
      transformation = inv_plane_rotation * inv_rotation;
      rect.dimensions[0] = (x_max - x_min);
      rect.dimensions[1] = (y_max - y_min);
      rect.dimensions[2] = height;
      Eigen::Vector3f pose3f((x_max + x_min)/2.0, (y_max + y_min)/2.0,
                             projected_cloud[0].z + height/2.0);
      pose3f = transformation * pose3f;
      pose.position.x = pose3f(0);
      pose.position.y = pose3f(1);
      pose.position.z = pose3f(2);
      Eigen::Quaternionf q(transformation);
      pose.orientation.x = q.x();
      pose.orientation.y = q.y();
      pose.orientation.z = q.z();
      pose.orientation.w = q.w();
      min_volume = area * height;
      shape = rect;
    }
  }
  // Try fitting a cylinder
  shape_msgs::SolidPrimitive cylinder; // the best-fit cylinder
  cylinder.type = cylinder.CYLINDER;
  cylinder.dimensions.resize(2);
  for (size_t i = 0; i < hull.size(); ++i)
  {
    for (size_t j = i + 1; j < hull.size(); ++j)
    {
      // For each pair of hull points determine the center point
      // between them as a possible cylinder
      pcl::PointXYZRGB p;
      p.x = (hull[i].x + hull[j].x) / 2.0;
      p.y = (hull[i].y + hull[j].y) / 2.0;
      double radius = 0.0;
      // Find radius from this point
      for (size_t k = 0; k < hull.size(); ++k)
      {
        double dx = hull[k].x - p.x;
        double dy = hull[k].y - p.y;
        double r = sqrt((dx * dx) + (dy * dy));
        if (r > radius)
          radius = r;
      }
      // Is this cylinder the best match?
      double volume = M_PI * radius * radius * height;
      if (volume < min_volume)
      {
        transformation = inv_plane_rotation;
        cylinder.dimensions[0] = height;
        cylinder.dimensions[1] = radius;
        Eigen::Vector3f pose3f(p.x, p.y, hull[0].z + height/2.0);
        pose3f = transformation * pose3f;
        pose.position.x = pose3f(0);
        pose.position.y = pose3f(1);
        pose.position.z = pose3f(2);
        min_volume = volume;
        shape = cylinder;
      }
    }
  }
  // TODO: Try fitting a sphere?
  // Project input to new frame
  Eigen::Vector3f origin(pose.position.x, pose.position.y, pose.position.z);
  for (size_t j = 0; j < input.size(); ++j)
  {
    pcl::PointXYZRGB p;
    p.getVector3fMap() = transformation * (input[j].getVector3fMap() - origin);
    output.push_back(p);
  }
  return true;
}
References pick_and_place::dx, pick_and_place::dy, pick_and_place::height, pick_and_place::l, demo::pose, fake_cube_perception_node::r, smacc::run(), and pick_and_place::y.
extractShape() [2/2]
bool simple_grasping::extractShape (const pcl::PointCloud< pcl::PointXYZRGB > & input, pcl::PointCloud< pcl::PointXYZRGB > & output, shape_msgs::SolidPrimitive & shape, geometry_msgs::Pose & pose)
Find the smallest shape primitive we can fit around this object.
Parameters
input Point Cloud of the object.
output Point Cloud transformed to the pose frame of the shape primitive fit.
shape Returned smallest shape primitive fit.
pose The pose of the shape primitive fit.
Returns
True if a shape was extracted, false if we have a failure.
Definition at line 232 of file shape_extraction.cpp.
{
  // Find lowest point, use as z height
  pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients);
  coefficients->values.resize(4);
  coefficients->values[0] = 0.0;
  coefficients->values[1] = 0.0;
  coefficients->values[2] = 1.0;
  coefficients->values[3] = 1000.0; // z-height
  for (size_t i = 0; i < input.size(); ++i)
  {
    if (input[i].z < coefficients->values[3])
      coefficients->values[3] = input[i].z;
  }
  coefficients->values[3] = -coefficients->values[3];
  return extractShape(input, coefficients, output, shape, pose);
}
References demo::pose.
Referenced by simple_grasping::ObjectSupportSegmentation::segment().
extractUnorientedBoundingBox()
bool simple_grasping::extractUnorientedBoundingBox (const pcl::PointCloud< pcl::PointXYZRGB > & input, shape_msgs::SolidPrimitive & shape, geometry_msgs::Pose & pose)
Find a bounding box around a cloud. This method does not attempt to find best orientation and so the bounding box will be oriented with the frame of the cloud.
Parameters
input Point Cloud of the object.
shape The box fit to this cloud.
pose The pose of the shape primitive extracted.
Definition at line 253 of file shape_extraction.cpp.
{
  double x_min = 1000.0;
  double x_max = -1000.0;
  double y_min = 1000.0;
  double y_max = -1000.0;
  double z_min = 1000.0;
  double z_max = -1000.0;
  for (size_t i = 0; i < input.size(); ++i)
  {
    if (input[i].x < x_min)
      x_min = input[i].x;
    if (input[i].x > x_max)
      x_max = input[i].x;
    if (input[i].y < y_min)
      y_min = input[i].y;
    if (input[i].y > y_max)
      y_max = input[i].y;
    if (input[i].z < z_min)
      z_min = input[i].z;
    if (input[i].z > z_max)
      z_max = input[i].z;
  }
  pose.position.x = (x_min + x_max)/2.0;
  pose.position.y = (y_min + y_max)/2.0;
  pose.position.z = (z_min + z_max)/2.0;
  shape.type = shape.BOX;
  shape.dimensions.push_back(x_max-x_min);
  shape.dimensions.push_back(y_max-y_min);
  shape.dimensions.push_back(z_max-z_min);
  return true;
}
References demo::pose, and pick_and_place::y.
Referenced by simple_grasping::ObjectSupportSegmentation::segment().
hsv2rgb()
void simple_grasping::hsv2rgb (const float h, const float s, const float v, float & r, float & g, float & b)
Fill in RGB values from HSV values.
Parameters
h HSV hue input.
s HSV saturation input.
v HSV value input.
r RGB red output.
g RGB green output.
b RGB blue output.
Definition at line 41 of file cloud_tools.cpp.
{
  float c = v * s;
  float hprime = h/60.0;
  float x = c * (1.0 - fabs(fmodf(hprime, 2.0f) - 1));
  r = g = b = 0;
  if (hprime < 1) {
    r = c; g = x;
  } else if (hprime < 2) {
    r = x; g = c;
  } else if (hprime < 3) {
    g = c; b = x;
  } else if (hprime < 4) {
    g = x; b = c;
  } else if (hprime < 5) {
    r = x; b = c;
  } else if (hprime < 6) {
    r = c; b = x;
  }
  float m = v - c;
  r += m; g+=m; b+=m;
}
References gripper_keyboard::c, tilt_head::h, fake_cube_perception_node::r, and service_node_3::s.
Referenced by colorizeCloud().
makeGripperTranslation()
moveit_msgs::GripperTranslation simple_grasping::makeGripperTranslation (std::string frame, double min, double desired, double x_axis = 1.0, double y_axis = 0.0, double z_axis = 0.0)
Definition at line 42 of file shape_grasp_planner.cpp.
{
  moveit_msgs::GripperTranslation translation;
  translation.direction.vector.x = x_axis;
  translation.direction.vector.y = y_axis;
  translation.direction.vector.z = z_axis;
  translation.direction.header.frame_id = frame;
  translation.min_distance = min;
  translation.desired_distance = desired;
  return translation;
}
Referenced by simple_grasping::ShapeGraspPlanner::createGrasp().
quaternionFromEuler()
Eigen::Quaterniond simple_grasping::quaternionFromEuler (float yaw, float pitch, float roll)
Definition at line 60 of file shape_grasp_planner.cpp.
{
  float sy = sin(yaw*0.5);
  float cy = cos(yaw*0.5);
  float sp = sin(pitch*0.5);
  float cp = cos(pitch*0.5);
  float sr = sin(roll*0.5);
  float cr = cos(roll*0.5);
  float w = cr*cp*cy + sr*sp*sy;
  float x = sr*cp*cy - cr*sp*sy;
  float y = cr*sp*cy + sr*cp*sy;
  float z = cr*cp*sy - sr*sp*cy;
  return Eigen::Quaterniond(w,x,y,z);
}
References pick_and_place::y.
Referenced by simple_grasping::ShapeGraspPlanner::createGrasp(), and simple_grasping::ShapeGraspPlanner::plan().