robot_controllers Namespace Reference
Classes
class CartesianPoseController
class CartesianTwistController
class CartesianWrenchController
class Controller
Base class for a controller. Is derived from a Handle, so that controllers can be passed from ControllerManager::getHandle(), thus allowing controllers to access other controllers (to stack their commands.
class ControllerLoader
Class for loading and managing a single controller.
class ControllerManager
Base class for a controller manager.
class DiffDriveBaseController
ROS-aware controller to manage a differential drive mobile base. This subcribes to cmd_vel topic, publishes odom and tf, and manages the two wheel joints.
class FollowJointTrajectoryController
This ROS interface implements a FollowJointTrajectoryAction interface for controlling (primarily) robot arms.
class GravityCompensation
Controller which uses KDL to compute torque needed for static holding of the chain at the current pose.
class Handle
Base class for a handle.
class JointHandle
Base class for a joint handle. This will be implemented for each type of robot.
class ParallelGripperController
Controller for a parallel jaw gripper, is really only intended for use in simulation.
class PID
class PointHeadController
class ScaledMimicController
Controller for a having one joint be a (scaled) mimic of another. Primary design use case is making a fake bellows joint that moves in relation to a torso lift joint.
struct Spline
Spline.
class SplineTrajectorySampler
Sampler that uses splines.
struct Trajectory
struct TrajectoryPoint
Basis for a Trajectory Point.
class TrajectorySampler
Base class for samplers of trajectories.
Typedefs
typedef boost::shared_ptr< DiffDriveBaseController > DiffDriveBaseControllerPtr
typedef boost::shared_ptr< Controller > ControllerPtr
typedef boost::shared_ptr< ControllerLoader > ControllerLoaderPtr
typedef boost::shared_ptr< Handle > HandlePtr
typedef boost::shared_ptr< JointHandle > JointHandlePtr
Enumerations
enum SplineType { QUINTIC,
CUBIC,
LINEAR
 }
Functions
bool trajectoryFromMsg (const trajectory_msgs::JointTrajectory &message, const std::vector< std::string > joints, Trajectory *trajectory)
Convert message into Trajectory.
bool spliceTrajectories (const Trajectory &t1, const Trajectory &t2, const double time, Trajectory *t)
Splice two trajectories.
void rosPrintTrajectory (Trajectory &t)
Print trajectory to ROS INFO.
bool windupTrajectory (std::vector< bool > continuous, Trajectory &trajectory)
Windup the trajectory so that continuous joints do not wrap.
bool unwindTrajectoryPoint (std::vector< bool > continuous, TrajectoryPoint &p)
static void generatePowers (int n, double x, double *powers)
Helper function for splines.
static void QuinticSpline (double p0, double v0, double a0, double p1, double v1, double a1, double t, Spline &s)
Create a quintic spline with between (p0,v0,a0) and (p1,v1,a1)
static void sampleQuinticSpline (Spline &s, double t, double &position, double &velocity, double &acceleration)
Sample from the spline at time t.
static void CubicSpline (double p0, double v0, double p1, double v1, double t, Spline &s)
Constructor for a cubic spline with between (p0,v0) and (p1,v1)
static void sampleCubicSpline (Spline s, double t, double &position, double &velocity)
Sample from the spline at time t.
static void LinearSpline (double p0, double p1, double t, Spline &s)
static void sampleLinearSpline (Spline &s, double t, double &position)
Typedef Documentation
ControllerLoaderPtr
typedef boost::shared_ptr<ControllerLoader> robot_controllers::ControllerLoaderPtr
Definition at line 79 of file controller_loader.h.
ControllerPtr
typedef boost::shared_ptr<Controller> robot_controllers::ControllerPtr
Definition at line 151 of file controller.h.
DiffDriveBaseControllerPtr
typedef boost::shared_ptr<DiffDriveBaseController> robot_controllers::DiffDriveBaseControllerPtr
Definition at line 220 of file diff_drive_base.h.
HandlePtr
typedef boost::shared_ptr<Handle> robot_controllers::HandlePtr
Definition at line 64 of file handle.h.
JointHandlePtr
typedef boost::shared_ptr<JointHandle> robot_controllers::JointHandlePtr
Definition at line 112 of file joint_handle.h.
Enumeration Type Documentation
SplineType
enum robot_controllers::SplineType
Enumerator
QUINTIC
CUBIC
LINEAR
Definition at line 88 of file trajectory_spline_sampler.h.
  {
Function Documentation
CubicSpline()
static void robot_controllers::CubicSpline (double p0, double v0, double p1, double v1, double t, Spline & s) [static]
Constructor for a cubic spline with between (p0,v0) and (p1,v1)
Parameters
p0 Starting position.
v0 Starting velocity.
p1 Ending position.
v1 Ending velocity.
t Time between start and end.
s Reference to the spline to create.
Definition at line 183 of file trajectory_spline_sampler.h.
{
  s.coef[0] = p0;
  s.coef[1] = p1 - p0;
  s.coef[2] = t;
}
static void sampleLinearSpline(Spline& s, double t, double& position)
{
  position = s.coef[0] + (s.coef[1] * t/s.coef[2]);
}
Referenced by robot_controllers::SplineTrajectorySampler::SplineTrajectorySampler().
generatePowers()
static void robot_controllers::generatePowers (int n, double x, double * powers) [inline], [static]
Helper function for splines.
Definition at line 96 of file trajectory_spline_sampler.h.
  {
    double T[6];
    generatePowers(5, t, T);
    s.coef[0] = p0;
    s.coef[1] = v0;
    s.coef[2] = 0.5*a0;
    s.coef[3] = (-20.0*p0 + 20.0*p1 - 3.0*a0*T[2] + a1*T[2] -
References service_node_3::s, and battery_monitor_node::t.
Referenced by sampleQuinticSpline().
LinearSpline()
static void robot_controllers::LinearSpline (double p0, double p1, double t, Spline & s) [static]
Definition at line 222 of file trajectory_spline_sampler.h.
    {
Referenced by robot_controllers::SplineTrajectorySampler::SplineTrajectorySampler().
QuinticSpline()
static void robot_controllers::QuinticSpline (double p0, double v0, double a0, double p1, double v1, double a1, double t, Spline & s) [static]
Create a quintic spline with between (p0,v0,a0) and (p1,v1,a1)
Parameters
p0 Starting position.
v0 Starting velocity.
a0 Starting acceleration.
p1 Ending position.
v1 Ending velocity.
a1 Ending acceleration.
t Time between start and end.
s The spline
Definition at line 116 of file trajectory_spline_sampler.h.
{
  double T[6];
  generatePowers(5, t, T);
  position = T[0]*s.coef[0] +
             T[1]*s.coef[1] +
             T[2]*s.coef[2] +
             T[3]*s.coef[3] +
             T[4]*s.coef[4] +
             T[5]*s.coef[5];
  velocity = T[0]*s.coef[1] +
         2.0*T[1]*s.coef[2] +
         3.0*T[2]*s.coef[3] +
         4.0*T[3]*s.coef[4] +
         5.0*T[4]*s.coef[5];
  acceleration = 2.0*T[0]*s.coef[2] +
                 6.0*T[1]*s.coef[3] +
                12.0*T[2]*s.coef[4] +
                20.0*T[3]*s.coef[5];
}
Referenced by robot_controllers::SplineTrajectorySampler::SplineTrajectorySampler().
rosPrintTrajectory()
void robot_controllers::rosPrintTrajectory (Trajectory & t) [inline]
Print trajectory to ROS INFO.
Definition at line 254 of file trajectory.h.
{
  for (size_t p = 0; p < trajectory.size(); p++)
  {
    if (continuous.size() != trajectory.points[p].q.size())
    {
      // Size does not match
      return false;
    }
    for (size_t j = 0; j < continuous.size(); j++)
    {
      if (continuous[j])
      {
        if (p > 0)
        {
          // Unwind by taking shortest path from previous point
          double shortest = angles::shortest_angular_distance(trajectory.points[p-1].q[j], trajectory.points[p].q[j]);
          trajectory.points[p].q[j] = trajectory.points[p-1].q[j] + shortest;
        }
        else
        {
          // Start between -PI and PI
          trajectory.points[p].q[j] = angles::normalize_angle(trajectory.points[p].q[j]);
        }
      }
References prepare_simulated_robot::trajectory.
sampleCubicSpline()
static void robot_controllers::sampleCubicSpline (Spline s, double t, double & position, double & velocity) [static]
Sample from the spline at time t.
Definition at line 207 of file trajectory_spline_sampler.h.
      :
  SplineTrajectorySampler(const Trajectory& trajectory) :
    trajectory_(trajectory)
  {
    // Check for invalid trajectory size
    if (trajectory.size() == 0)
    {
sampleLinearSpline()
static void robot_controllers::sampleLinearSpline (Spline & s, double t, double & position) [static]
Definition at line 229 of file trajectory_spline_sampler.h.
    {
      segments_.resize(1);
      segments_[0].start_time = segments_[0].end_time = trajectory.points[0].time;
References robot_controllers::SplineTrajectorySampler::segments_, and prepare_simulated_robot::trajectory.
sampleQuinticSpline()
static void robot_controllers::sampleQuinticSpline (Spline & s, double t, double & position, double & velocity, double & acceleration) [static]
Sample from the spline at time t.
Definition at line 149 of file trajectory_spline_sampler.h.
{
  if (t == 0.0)
  {
    s.coef[0] = p1;
    s.coef[1] = v1;
    s.coef[2] = 0.0;
    s.coef[3] = 0.0;
  }
  else
  {
    double T[4];
    generatePowers(3, t, T);
    s.coef[0] = p0;
    s.coef[1] = v0;
    s.coef[2] = (3.0 * p1 - 3.0 * p0 - 2.0 *v0*T[1] - v1*T[1]) / T[2];
    s.coef[3] = (-2.0 * p1 + 2.0 * p0 + v0*T[1] + v1*T[1]) / T[3];
  }
}
References generatePowers(), service_node_3::s, and battery_monitor_node::t.
spliceTrajectories()
bool robot_controllers::spliceTrajectories (const Trajectory & t1, const Trajectory & t2, const double time, Trajectory * t) [inline]
Splice two trajectories.
Parameters
t1 First trajectory to splice
t2 Second trajectory to splice (will overwrite first)
time The start time for the new trajectory (typically, current system time)
t The new trajectory.
Definition at line 165 of file trajectory.h.
  {
    if (t1.points[p].time >= time && t1.points[p].time < start_t2)
    {
      if (t1.points[p].time > time && t->size() == 0)
      {
        /* This is first point in trajectory, and is after our
           start time, see if we can add one point in front of it */
        if (p > 0)
         t->points.push_back(t1.points[p-1]);
      }
      t->points.push_back(t1.points[p]);
    }
  }
  // Add points from t2
  for (size_t p = 0; p < t2.size(); ++p)
  {
    if (t2.points[p].time >= time)
    {
      if (t2.points[p].time > time && t->size() == 0)
      {
        /* This is first point in trajectory, and is after our
           start time, see if we can add one point in front of it */
        if (p > 0)
         t->points.push_back(t2.points[p-1]);
        else if (t1.size() > 0)
         t->points.push_back(t1.points[t1.size()-1]);
      }
      t->points.push_back(t2.points[p]);
    }
  }
  if (!has_accelerations)
  {
    // Remove any accelerations in output trajectory
    for (size_t i = 0; i < t->points.size(); i++)
    {
      t->points[i].qdd.clear();
    }
  }
  if (!has_velocities)
  {
    // Remove any velocities in output trajectory
    for (size_t i = 0; i < t->points.size(); i++)
    {
      t->points[i].qd.clear();
    }
  }
  return true;
}
inline void rosPrintTrajectory(Trajectory& t)
{
  ROS_INFO_STREAM("Trajectory with " << t.size() << " points:");
  for (size_t p = 0; p < t.size(); ++p)
  {
    ROS_INFO_STREAM(" Point " << p << " at " << std::setprecision (15) << t.points[p].time);
    for (size_t j = 0; j < t.points[p].q.size(); ++j)
    {
      if (t.points[p].qdd.size() == t.points[p].q.size())
      {
        ROS_INFO_STREAM(" " << std::setprecision (5) << t.points[p].q[j] <<
                          ", " << std::setprecision (5) << t.points[p].qd[j] <<
                          ", " << std::setprecision (5) << t.points[p].qdd[j]);
      }
      else if(t.points[p].q.size() == t.points[p].q.size())
      {
        ROS_INFO_STREAM(" " << std::setprecision (5) << t.points[p].q[j] <<
                          ", " << std::setprecision (5) << t.points[p].qd[j]);
      }
      else
      {
        ROS_INFO_STREAM(" " << std::setprecision (5) << t.points[p].q[j]);
      }
    }
  }
}
References battery_monitor_node::t.
Referenced by robot_controllers::FollowJointTrajectoryController::executeCb().
trajectoryFromMsg()
bool robot_controllers::trajectoryFromMsg (const trajectory_msgs::JointTrajectory & message, const std::vector< std::string > joints, Trajectory * trajectory) [inline]
Convert message into Trajectory.
Parameters
message The trajectory message.
joints Vector of joint names, used to order the values within a TrajectoryPoint
trajectory The returned trajectory
Returns
True if trajectory generated, false otherwise.
Definition at line 109 of file trajectory.h.
    {
      point.q.push_back(message.points[p].positions[mapping[j]]);
      if (message.points[p].velocities.size() == message.points[p].positions.size())
        point.qd.push_back(message.points[p].velocities[mapping[j]]);
      if (message.points[p].accelerations.size() == message.points[p].positions.size())
        point.qdd.push_back(message.points[p].accelerations[mapping[j]]);
    }
    point.time = start_time + message.points[p].time_from_start.toSec();
    trajectory->points.push_back(point);
  }
  // Parsed this
  return true;
}
inline bool spliceTrajectories(const Trajectory& t1,
                               const Trajectory& t2,
                               const double time,
                               Trajectory * t)
{
  // Need at least one point in t1 for the following code to work
  if (t1.size() == 0)
  {
    return false;
  }
  // Need at least one point in t2 for the following code to work
  if (t2.size() == 0)
  {
    *t = t1;
    return true;
  }
  // Check sizes
  size_t num_joints = t1.points[0].q.size();
  bool has_velocities = (t1.points[0].qd.size() == num_joints) &&
                        (t2.points[0].qd.size() == num_joints);
  bool has_accelerations = (t1.points[0].qdd.size() == num_joints) &&
                           (t2.points[0].qdd.size() == num_joints);
Referenced by robot_controllers::FollowJointTrajectoryController::executeCb().
unwindTrajectoryPoint()
bool robot_controllers::unwindTrajectoryPoint (std::vector< bool > continuous, TrajectoryPoint & p) [inline]
Definition at line 318 of file trajectory.h.
       :
  // You no copy...
  TrajectorySampler(const TrajectorySampler&);
  TrajectorySampler& operator=(const TrajectorySampler&);
};
} // namespace robot_controllers
#endif // ROBOT_CONTROLLERS_TRAJECTORY_H_
Referenced by robot_controllers::FollowJointTrajectoryController::update().
windupTrajectory()
bool robot_controllers::windupTrajectory (std::vector< bool > continuous, Trajectory & trajectory) [inline]
Windup the trajectory so that continuous joints do not wrap.
Parameters
continuous Which joints in each TrajectoryPoint are continuous.
trajectory The trajectory to unwind.
Definition at line 286 of file trajectory.h.
{
  if (continuous.size() != p.q.size())
  {
    return false;
  }
  for (size_t j = 0; j < continuous.size(); j++)
  {
    if (continuous[j])
    {
      p.q[j] = angles::normalize_angle(p.q[j]);
    }
  }
  return true;
}
class TrajectorySampler
{
public:
  TrajectorySampler() {}
  virtual ~TrajectorySampler() {}
  virtual TrajectoryPoint sample(double time) = 0;
Referenced by robot_controllers::FollowJointTrajectoryController::executeCb().