sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper Struct Reference
#include <st_close_gripper.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClGripper, OrGripper >, StGraspRetreat > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_close_gripper.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClGripper, OrGripper>, StGraspRetreat> > sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::reactions
Definition at line 14 of file st_close_gripper.h.
Member Function Documentation
onEntry()
void sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::onEntry () [inline]
Definition at line 34 of file st_close_gripper.h.
         {
            ros::Duration(1.0).sleep();
         }
onExit()
void sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::onExit () [inline]
Definition at line 39 of file st_close_gripper.h.
         {
            ClMoveGroup *moveGroupClient;
            this->requiresClient(moveGroupClient);
            //auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
            // //std::vector<moveit_msgs::CollisionObject> collisionObjects;
            // moveit_msgs::CollisionObject cubeCollision;
            // auto time = ros::Time::now();
            // createCollisionBox(cubepos.pose.position.x, cubepos.pose.position.y, cubepos.pose.position.z, 0.06, 0.06, 0.06, "collisioncube", "map", cubeCollision, time, moveit_msgs::CollisionObject::ADD);
            // planningSceneInterface.applyCollisionObject(cubeCollision);
            // // collisionObjects.push_back(cubeCollision);
            
            // std::vector<std::string> touch_links{"l_gripper_finger_link", "r_gripper_finger_link"};
            // moveGroupClient->moveGroupClientInterface.attachObject("collisioncube", "gripper_link", touch_links);
            // //moveGroupClient->moveGroupClientInterface.setSupportSurfaceName("table_1");
            
            moveGroupClient->getComponent<CpConstraintTableWorkspaces>()->disableTableCollisionVolume();
            ros::Duration(1.0).sleep();
         }
References smacc::ISmaccState::requiresClient().
runtimeConfigure()
void sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::runtimeConfigure () [inline]
Definition at line 23 of file st_close_gripper.h.
         {
            ClPerceptionSystem *perceptionSystem;
            this->requiresClient(perceptionSystem);
            auto cubeinfo = perceptionSystem->getTargetCurrentCubeInfo();
            auto cbattach = this->getOrthogonal<OrArm>()->getClientBehavior<CbAttachObject>();
            cbattach->targetObjectName_ = cubeinfo->pose_->getFrameId();
         }
References cl_move_base_z::Pose::getFrameId(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::getTargetCurrentCubeInfo(), sm_fetch_two_table_whiskey_pour::cl_perception_system::CubeInfo::pose_, and smacc::ISmaccState::requiresClient().
staticConfigure()
static void sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::staticConfigure () [inline], [static]
Definition at line 17 of file st_close_gripper.h.
         {
            configure_orthogonal<OrGripper, CbCloseGripper>();
            configure_orthogonal<OrArm, CbAttachObject>();
         }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/states/pick_states/st_close_gripper.h