sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose Struct Reference
#include <st_move_preplace_pose.h>
Public Types
typedef mpl::list< Transition< EvMoveGroupMotionExecutionSucceded< ClMoveGroup, OrArm >, StPlaceApproach >, Transition< EvMoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StMovePrePlacePose, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void computeCubeGraspingOrientation (geometry_msgs::PoseStamped &objectPose)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_move_preplace_pose.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvMoveGroupMotionExecutionSucceded<ClMoveGroup, OrArm>, StPlaceApproach>, Transition<EvMoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StMovePrePlacePose, ABORT> > sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose::reactions
Definition at line 16 of file st_move_preplace_pose.h.
Member Function Documentation
computeCubeGraspingOrientation()
void sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose::computeCubeGraspingOrientation (geometry_msgs::PoseStamped & objectPose) [inline]
Definition at line 47 of file st_move_preplace_pose.h.
    {
        // ------ cube grasping orientation -------
        // grasp the object with the gripper using top-to-bottom direction
        auto cubeYawOnTable = tf::getYaw(objectPose.pose.orientation);
        const double degrees90 = M_PI / 2;
        while (cubeYawOnTable > degrees90)
        {
            cubeYawOnTable -= degrees90;
        }
        while (cubeYawOnTable < -degrees90)
        {
            cubeYawOnTable += degrees90;
        }
        ROS_INFO("cube yaw: %lf", cubeYawOnTable);
        auto quat = tf::createQuaternionFromRPY(0, M_PI / 2, cubeYawOnTable);
        tf::quaternionTFToMsg(quat, objectPose.pose.orientation);
    }
Referenced by runtimeConfigure().
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose::runtimeConfigure () [inline]
Definition at line 28 of file st_move_preplace_pose.h.
    {
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        geometry_msgs::PoseStamped placingPose = perceptionSystem->decidePlacePose();
        ROS_INFO_STREAM("[StMovePreplacePose] Decided place pose for cube: " << placingPose);
        placingPose.pose.position.x -= 0;
        placingPose.pose.position.z += 0.3;
        auto moveAbsolute = this->getOrthogonal<OrArm>()
                                ->getClientBehavior<CbMoveEndEffector>();
        computeCubeGraspingOrientation(placingPose);
        moveAbsolute->targetPose = placingPose;
    }
References computeCubeGraspingOrientation(), and smacc::ISmaccState::requiresClient().
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose::staticConfigure () [inline], [static]
Definition at line 19 of file st_move_preplace_pose.h.
    {
        configure_orthogonal<OrArm, CbMoveEndEffector>();
        // configure_orthogonal<OrNavigation, CbNavigateBackwards>(2);
        // configure_orthogonal<OrLED, CbLEDOff>();
        // configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/place_states/st_move_preplace_pose.h