sm_ferrari::inner_states::StiState1 Struct Reference
#include <sti_state_1.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiState1 >, StiState2, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_state_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiState1>, StiState2, CONTINUELOOP> > sm_ferrari::inner_states::StiState1::reactions
Definition at line 16 of file sti_state_1.h.
Member Function Documentation
loopWhileCondition()
bool sm_ferrari::inner_states::StiState1::loopWhileCondition () [inline]
Definition at line 27 of file sti_state_1.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
onEntry()
void sm_ferrari::inner_states::StiState1::onEntry () [inline]
Definition at line 35 of file sti_state_1.h.
References smacc::SmaccState< StiState1, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      StiState1::loopWhileCondition);
  }
onExit()
void sm_ferrari::inner_states::StiState1::onExit () [inline]
Definition at line 41 of file sti_state_1.h.
  {
    ROS_INFO("On Exit!");
  }
runtimeConfigure()
void sm_ferrari::inner_states::StiState1::runtimeConfigure () [inline]
Definition at line 23 of file sti_state_1.h.
  {
  }
staticConfigure()
static void sm_ferrari::inner_states::StiState1::staticConfigure () [inline], [static]
Definition at line 19 of file sti_state_1.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_ferrari/include/sm_ferrari/states/inner_states/sti_state_1.h