sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach Struct Reference
#include <st_place_approach.h>
Public Types
typedef mpl::list< Transition< EvMoveGroupMotionExecutionSucceded< ClMoveGroup, OrArm >, StOpenGripper >, Transition< EvMoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StPlaceApproach, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_place_approach.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvMoveGroupMotionExecutionSucceded<ClMoveGroup, OrArm>, StOpenGripper>, Transition<EvMoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StPlaceApproach, ABORT> > sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::reactions
Definition at line 16 of file st_place_approach.h.
Member Function Documentation
onExit()
void sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::onExit () [inline]
Definition at line 33 of file st_place_approach.h.
    {
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        perceptionSystem->nextCube();
    }
References smacc::ISmaccState::requiresClient().
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::runtimeConfigure () [inline]
Definition at line 26 of file st_place_approach.h.
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&StPlaceApproach::throwSequenceFinishedEvent, this);
    }
References cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StPlaceApproach, SS >::throwSequenceFinishedEvent().
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::staticConfigure () [inline], [static]
Definition at line 19 of file st_place_approach.h.
    {
        geometry_msgs::Vector3 offset;
        offset.z = -0.12;
        configure_orthogonal<OrArm, CbMoveCartesianRelative>(offset);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/place_states/st_place_approach.h