sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose Struct Reference
#include <st_move_pregrasp_pose.h>
Public Types
typedef mpl::list< Transition< EvMoveGroupMotionExecutionSucceded< ClMoveGroup, OrArm >, StGraspApproach, SUCCESS >, Transition< EvMoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StMovePregraspPose, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void computeCubeGraspingOrientation (geometry_msgs::PoseStamped &objectPose)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_move_pregrasp_pose.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvMoveGroupMotionExecutionSucceded<ClMoveGroup, OrArm>, StGraspApproach, SUCCESS>, Transition<EvMoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StMovePregraspPose, ABORT> > sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::reactions
Definition at line 17 of file st_move_pregrasp_pose.h.
Member Function Documentation
computeCubeGraspingOrientation()
void sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::computeCubeGraspingOrientation (geometry_msgs::PoseStamped & objectPose) [inline]
Definition at line 47 of file st_move_pregrasp_pose.h.
    {
        objectPose.pose.position.x -= 0;
        objectPose.pose.position.z += 0.3;
        // ------ cube grasping orientation -------
        // grasp the object with the gripper using top-to-bottom direction
        auto cubeYawOnTable = tf::getYaw(objectPose.pose.orientation);
        const double degrees90 = M_PI / 2;
        while (cubeYawOnTable > degrees90)
        {
            cubeYawOnTable -= degrees90;
        }
        while (cubeYawOnTable < -degrees90)
        {
            cubeYawOnTable += degrees90;
        }
        ROS_INFO("cube yaw: %lf", cubeYawOnTable);
        auto quat = tf::createQuaternionFromRPY(0, M_PI / 2, cubeYawOnTable);
        tf::quaternionTFToMsg(quat, objectPose.pose.orientation);
    }
Referenced by runtimeConfigure().
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::runtimeConfigure () [inline]
Definition at line 29 of file st_move_pregrasp_pose.h.
    {
        ROS_INFO("Pre grasp pose initialization.");
        ros::WallDuration(5).sleep();
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        
        auto pregraspPose = perceptionSystem->decidePickCubePose();
        this->computeCubeGraspingOrientation(pregraspPose);
        auto moveAbsolute = this->getOrthogonal<OrArm>()
                                ->getClientBehavior<CbMoveEndEffector>();
        moveAbsolute->targetPose = pregraspPose;
    }
References computeCubeGraspingOrientation(), smacc::ISmaccState::requiresClient(), and cl_move_group_interface::CbMoveEndEffector::targetPose.
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::staticConfigure () [inline], [static]
Definition at line 20 of file st_move_pregrasp_pose.h.
    {
        configure_orthogonal<OrArm, CbMoveEndEffector>();
        // configure_orthogonal<OrNavigation, CbNavigateBackwards>(2);
        // configure_orthogonal<OrLED, CbLEDOff>();
        // configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/pick_states/st_move_pregrasp_pose.h