sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose Struct Reference
#include <st_move_pregrasp_pose.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbMoveEndEffector, OrArm >, StGraspApproach, SUCCESS >, Transition< EvCbFailure< CbMoveEndEffector, OrArm >, StMovePregraspPose, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Public Attributes
ClMoveGroup * moveGroup_
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_move_pregrasp_pose.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbMoveEndEffector, OrArm>, StGraspApproach, SUCCESS>, Transition<EvCbFailure<CbMoveEndEffector, OrArm>, StMovePregraspPose, ABORT> > sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::reactions
Definition at line 17 of file st_move_pregrasp_pose.h.
Member Function Documentation
runtimeConfigure()
void sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::runtimeConfigure () [inline]
Definition at line 28 of file st_move_pregrasp_pose.h.
            {
                ROS_INFO("Pre grasp pose initialization.");
                ros::WallDuration(1).sleep();
                // --------------------------------------
                this->requiresClient(moveGroup_);
                
                ClPerceptionSystem *perceptionSystem;
                this->requiresClient(perceptionSystem);
                auto cbMoveEndEffector = this->getOrthogonal<OrArm>()->getClientBehavior<CbMoveEndEffector>();
                // --------------------------------------
                moveGroup_->getComponent<CpConstraintTableWorkspaces>()->setBigTableCollisionVolume();
                geometry_msgs::PoseStamped targetCubePose;
                if (perceptionSystem->decidePickCubePose(targetCubePose))
                {
                    geometry_msgs::PoseStamped pregraspPose = targetCubePose;
                    perceptionSystem->computePregraspPoseFromCubePose(pregraspPose);
                    cbMoveEndEffector->targetPose = pregraspPose;
                }
            }
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::computePregraspPoseFromCubePose(), sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePickCubePose(), moveGroup_, and smacc::ISmaccState::requiresClient().
staticConfigure()
static void sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::staticConfigure () [inline], [static]
Definition at line 23 of file st_move_pregrasp_pose.h.
            {
                configure_orthogonal<OrArm, CbMoveEndEffector>();
            }
Member Data Documentation
moveGroup_
ClMoveGroup* sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::moveGroup_
Definition at line 20 of file st_move_pregrasp_pose.h.
Referenced by runtimeConfigure().
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/states/pick_states/st_move_pregrasp_pose.h