sm_respira_1::ac_cycle_inner_states::StiACCycleLoop Struct Reference
#include <sti_ac_cycle_loop.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiACCycleLoop >, StiACCycleInspire, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_ac_cycle_loop.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiACCycleLoop>, StiACCycleInspire, CONTINUELOOP> > sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::reactions
Definition at line 16 of file sti_ac_cycle_loop.h.
Member Function Documentation
loopWhileCondition()
bool sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::loopWhileCondition () [inline]
Definition at line 27 of file sti_ac_cycle_loop.h.
  {
    auto &superstate = this->context<SsACCycle>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count, superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
Referenced by onEntry().
onEntry()
void sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::onEntry () [inline]
Definition at line 35 of file sti_ac_cycle_loop.h.
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&StiACCycleLoop::loopWhileCondition);
  }
References smacc::SmaccState< StiACCycleLoop, SsACCycle >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
runtimeConfigure()
void sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::runtimeConfigure () [inline]
Definition at line 23 of file sti_ac_cycle_loop.h.
  {
  }
staticConfigure()
static void sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::staticConfigure () [inline], [static]
Definition at line 19 of file sti_ac_cycle_loop.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/ac_cycle_inner_states/sti_ac_cycle_loop.h