sm_fetch_two_table_pick_n_place_1::StForwardNextTable Struct Reference
#include <st_forward.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbNavigateGlobalPosition, OrNavigation >, SS2::SsPlaceObject, SUCCESS >, Transition< EvCbFailure< CbNavigateGlobalPosition, OrNavigation >, StUndoIncorrectForward, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void configureGlobalNavigation ()
void configureForwardBehavior ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_forward.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbNavigateGlobalPosition, OrNavigation>, SS2::SsPlaceObject, SUCCESS>, Transition<EvCbFailure<CbNavigateGlobalPosition, OrNavigation>, StUndoIncorrectForward, ABORT> > sm_fetch_two_table_pick_n_place_1::StForwardNextTable::reactions
Definition at line 13 of file st_forward.h.
Member Function Documentation
configureForwardBehavior()
void sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureForwardBehavior () [inline]
Definition at line 59 of file st_forward.h.
    {
      ClMoveBaseZ *moveBaseClient_;
      this->requiresClient(moveBaseClient_);
      auto pose = moveBaseClient_->getComponent<Pose>();
      auto currentPose = pose->toPoseMsg();
      auto offset = 0.15;
      auto forwardDistance = 2.0;
      double dist;
      dist = forwardDistance + offset;
      auto forwardBh = this->getOrthogonal<OrNavigation>()->getClientBehavior<CbNavigateForward>();
      forwardBh->forwardDistance = dist;
    }
References cl_move_base_z::CbNavigateForward::forwardDistance, smacc::ISmaccClient::getComponent(), demo::pose, and smacc::ISmaccState::requiresClient().
configureGlobalNavigation()
void sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureGlobalNavigation () [inline]
Definition at line 28 of file st_forward.h.
    {
      ClMoveBaseZ *moveBaseClient_;
      this->requiresClient(moveBaseClient_);
      auto pose = moveBaseClient_->getComponent<Pose>();
      auto currentPose = pose->toPoseMsg();
      geometry_msgs::Point goalPosition;
      goalPosition.z = 0;
      goalPosition.y = 0;
      double yaw = 0;
      double forwardOffset = 1.2;
      if (currentPose.position.x < -0.2) // robot is at negative x-axis side
      {
        // target is at positive side, at point x=0
        goalPosition.x = forwardOffset;
        yaw = 0;
      }
      else // the robot in at positive x-axis side
      {
        // target is at negative x-axis side at point x = -1
        goalPosition.x = -forwardOffset;
        yaw = -M_PI;
      }
      auto globalNavigationBh = this->getOrthogonal<OrNavigation>()->getClientBehavior<CbNavigateGlobalPosition>();
      globalNavigationBh->goalPosition = goalPosition;
      globalNavigationBh->goalYaw = yaw;
    }
References smacc::ISmaccClient::getComponent(), cl_move_base_z::CbNavigateGlobalPosition::goalPosition, demo::pose, and smacc::ISmaccState::requiresClient().
Referenced by runtimeConfigure().
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::StForwardNextTable::runtimeConfigure () [inline]
Definition at line 22 of file st_forward.h.
    {
      configureGlobalNavigation();
      //configureForwardBehavior();
    }
References configureGlobalNavigation().
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::StForwardNextTable::staticConfigure () [inline], [static]
Definition at line 16 of file st_forward.h.
    {
      configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
      //configure_orthogonal<OrNavigation, CbNavigateForward>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/st_forward.h