sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose Struct Reference
#include <st_move_preplace_pose.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbMoveEndEffector, OrArm >, StPlaceApproach >, Transition< EvCbFailure< CbMoveEndEffector, OrArm >, StMovePrePlacePose, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_move_preplace_pose.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbMoveEndEffector, OrArm>, StPlaceApproach>, Transition<EvCbFailure<CbMoveEndEffector, OrArm>, StMovePrePlacePose, ABORT> > sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::reactions
Definition at line 16 of file st_move_preplace_pose.h.
Member Function Documentation
onExit()
void sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::onExit () [inline]
Definition at line 44 of file st_move_preplace_pose.h.
            {
                ClMoveGroup *moveGroup;
                this->requiresClient(moveGroup);
                moveGroup->getComponent<CpConstraintTableWorkspaces>()->setSmallTableCollisionVolume();
            }
References smacc::ISmaccState::requiresClient().
runtimeConfigure()
void sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::runtimeConfigure () [inline]
Definition at line 24 of file st_move_preplace_pose.h.
            {
                ClPerceptionSystem *perceptionSystem;
                this->requiresClient(perceptionSystem);
                ClMoveGroup *moveGroup;
                this->requiresClient(moveGroup);
                moveGroup->getComponent<CpConstraintTableWorkspaces>()->setBigTableCollisionVolume();
                geometry_msgs::PoseStamped placingPose;
                if (perceptionSystem->decidePrePlacePose(placingPose))
                {
                    auto moveAbsolute = this->getOrthogonal<OrArm>()
                                            ->getClientBehavior<CbMoveEndEffector>();
                    moveAbsolute->targetPose = placingPose;
                }
            }
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePrePlacePose(), and smacc::ISmaccState::requiresClient().
staticConfigure()
static void sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::staticConfigure () [inline], [static]
Definition at line 19 of file st_move_preplace_pose.h.
            {
                configure_orthogonal<OrArm, CbMoveEndEffector>();
            }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/states/place_states/st_move_preplace_pose.h