testing::internal::TuplePrefix< N > Class Template Reference
#include <gmock-matchers.h>
Static Public Member Functions
template<typename MatcherTuple , typename ValueTuple >
static bool Matches (const MatcherTuple &matcher_tuple, const ValueTuple &value_tuple)
template<typename MatcherTuple , typename ValueTuple >
static void ExplainMatchFailuresTo (const MatcherTuple &matchers, const ValueTuple &values, ::std::ostream *os)
Detailed Description
template<size_t N>
class testing::internal::TuplePrefix< N >
Definition at line 726 of file gmock-matchers.h.
Member Function Documentation
ExplainMatchFailuresTo()
template<size_t N>
template<typename MatcherTuple , typename ValueTuple >
static void testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo (const MatcherTuple & matchers, const ValueTuple & values, ::std::ostream * os) [inline], [static]
Definition at line 743 of file gmock-matchers.h.
References interactive_marker::listener, testing::internal::PrintIfNotEmpty(), generate_debs::type, testing::internal::UniversalPrint(), and testing::Value().
                                                     {
    // First, describes failures in the first N - 1 fields.
    TuplePrefix<N - 1>::ExplainMatchFailuresTo(matchers, values,
      os);
    // Then describes the failure (if any) in the (N - 1)-th (0-based)
    // field.
    typename tuple_element<N - 1, MatcherTuple>::type matcher =
        get<N - 1>(matchers);
    typedef typename tuple_element<N - 1, ValueTuple>::type Value;
    Value value = get<N - 1>(values);
    StringMatchResultListener listener;
    if (!matcher.MatchAndExplain(value, &listener)) {
      // TODO(wan): include in the message the name of the parameter
      // as used in MOCK_METHOD*() when possible.
      *os << " Expected arg #" << N - 1 << ": ";
      get<N - 1>(matchers).DescribeTo(os);
      *os << "\n Actual: ";
      // We remove the reference in type Value to prevent the
      // universal printer from printing the address of value, which
      // isn't interesting to the user most of the time. The
      // matcher's MatchAndExplain() method handles the case when
      // the address is interesting.
      internal::UniversalPrint(value, os);
      PrintIfNotEmpty(listener.str(), os);
      *os << "\n";
    }
  }
Matches()
template<size_t N>
template<typename MatcherTuple , typename ValueTuple >
static bool testing::internal::TuplePrefix< N >::Matches (const MatcherTuple & matcher_tuple, const ValueTuple & value_tuple) [inline], [static]
Definition at line 732 of file gmock-matchers.h.
References testing::Matches().
                                                     {
    return TuplePrefix<N - 1>::Matches(matcher_tuple, value_tuple)
        && get<N - 1>(matcher_tuple).Matches(get<N - 1>(value_tuple));
  }
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-matchers.h