franka::Logger Class Reference
#include <logger.h>
Public Member Functions
Logger (size_t log_size)
void log (const RobotState &state, const research_interface::robot::RobotCommand &command)
std::vector< franka::Record > flush ()
Private Attributes
std::vector< RobotState > states_
std::vector< research_interface::robot::RobotCommand > commands_
size_t ring_front_ {0}
size_t ring_size_ {0}
const size_t log_size_
Detailed Description
Definition at line 15 of file logger.h.
Constructor & Destructor Documentation
Logger()
franka::Logger::Logger (size_t log_size) [explicit]
Definition at line 7 of file logger.cpp.
References commands_, and states_.
                              : log_size_(log_size) {
  states_.resize(log_size);
  commands_.resize(log_size);
}
Member Function Documentation
flush()
std::vector< Record > franka::Logger::flush ()
Definition at line 24 of file logger.cpp.
References franka::RobotCommand::cartesian_pose, franka::RobotCommand::cartesian_velocities, franka::Record::command, commands_, franka::RobotCommand::joint_positions, franka::RobotCommand::joint_velocities, log(), franka::CartesianVelocities::O_dP_EE, franka::CartesianPose::O_T_EE, ring_front_, ring_size_, franka::Record::state, states_, franka::Torques::tau_J, and franka::RobotCommand::torques.
Referenced by franka::Robot::Impl::finishMotion(), franka::Robot::Impl::startMotion(), and franka::Robot::Impl::throwOnMotionError().
                                {
  std::vector<Record> log;
  for (size_t i = 0; i < ring_size_; i++) {
    size_t wrapped_index = (ring_front_ + i) % ring_size_;
    RobotCommand command;
    command.joint_positions = commands_[wrapped_index].motion.q_c;
    command.joint_velocities = commands_[wrapped_index].motion.dq_c;
    command.cartesian_pose.O_T_EE = commands_[wrapped_index].motion.O_T_EE_c;
    command.cartesian_velocities.O_dP_EE = commands_[wrapped_index].motion.O_dP_EE_c;
    command.torques.tau_J = commands_[wrapped_index].control.tau_J_d;
    Record record;
    record.state = states_[wrapped_index];
    record.command = command;
    log.push_back(record);
  }
  ring_front_ = 0;
  ring_size_ = 0;
  return log;
}
log()
void franka::Logger::log (const RobotState & state, const research_interface::robot::RobotCommand & command)
Definition at line 12 of file logger.cpp.
References commands_, log_size_, ring_front_, ring_size_, and states_.
Referenced by flush(), and franka::Robot::Impl::update().
                                                                                            {
  if (log_size_ == 0) {
    return;
  }
  commands_[ring_front_] = command;
  states_[ring_front_] = state;
  ring_front_ = (ring_front_ + 1) % log_size_;
  ring_size_ = std::min(log_size_, ring_size_ + 1);
}
Member Data Documentation
commands_
std::vector<research_interface::robot::RobotCommand> franka::Logger::commands_ [private]
Definition at line 25 of file logger.h.
Referenced by flush(), log(), and Logger().
log_size_
const size_t franka::Logger::log_size_ [private]
Definition at line 29 of file logger.h.
Referenced by log().
ring_front_
size_t franka::Logger::ring_front_ {0} [private]
Definition at line 26 of file logger.h.
Referenced by flush(), and log().
ring_size_
size_t franka::Logger::ring_size_ {0} [private]
Definition at line 27 of file logger.h.
Referenced by flush(), and log().
states_
std::vector<RobotState> franka::Logger::states_ [private]
Definition at line 24 of file logger.h.
Referenced by flush(), log(), and Logger().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/logger.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/logger.cpp