franka::Model Class Reference
#include <model.h>
Public Member Functions
Model (franka::Network &network)
Model (Model &&model) noexcept
Model & operator= (Model &&model) noexcept
~Model () noexcept
std::array< double, 16 > pose (Frame frame, const franka::RobotState &robot_state) const
std::array< double, 16 > pose (Frame frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
std::array< double, 42 > bodyJacobian (Frame frame, const franka::RobotState &robot_state) const
std::array< double, 42 > bodyJacobian (Frame frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
std::array< double, 42 > zeroJacobian (Frame frame, const franka::RobotState &robot_state) const
std::array< double, 42 > zeroJacobian (Frame frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
std::array< double, 49 > mass (const franka::RobotState &robot_state) const noexcept
std::array< double, 49 > mass (const std::array< double, 7 > &q, const std::array< double, 9 > &I_total, double m_total, const std::array< double, 3 > &F_x_Ctotal) const noexcept
std::array< double, 7 > coriolis (const franka::RobotState &robot_state) const noexcept
std::array< double, 7 > coriolis (const std::array< double, 7 > &q, const std::array< double, 7 > &dq, const std::array< double, 9 > &I_total, double m_total, const std::array< double, 3 > &F_x_Ctotal) const noexcept
std::array< double, 7 > gravity (const std::array< double, 7 > &q, double m_total, const std::array< double, 3 > &F_x_Ctotal, const std::array< double, 3 > &gravity_earth={{0., 0., -9.81}}) const noexcept
std::array< double, 7 > gravity (const franka::RobotState &robot_state, const std::array< double, 3 > &gravity_earth={ {0., 0., -9.81}}) const noexcept
Private Attributes
std::unique_ptr< ModelLibrary > library_
Detailed Description
Calculates poses of joints and dynamic properties of the robot.
Definition at line 51 of file model.h.
Constructor & Destructor Documentation
Model() [1/2]
franka::Model::Model (franka::Network & network) [explicit]
Creates a new Model instance.
This constructor is for internal use only.
See also
Robot::loadModel
Parameters
in network For internal use.
Exceptions
ModelException if the model library cannot be loaded.
Definition at line 24 of file model.cpp.
References operator=(), and ~Model().
: library_{new ModelLibrary(network)} {}
Model() [2/2]
franka::Model::Model (Model && model) [default], [noexcept]
Move-constructs a new Model instance.
Parameters
in model Other Model instance.
 Model()
franka::Model::~Model () [default], [noexcept]
Unloads the model library.
Referenced by Model().
Member Function Documentation
bodyJacobian() [1/2]
std::array< double, 42 > franka::Model::bodyJacobian (Frame frame, const franka::RobotState & robot_state) const
Gets the 6x7 Jacobian for the given frame, relative to that frame.
The Jacobian is represented as a 6x7 matrix in column-major format.
Parameters
in frame The desired frame.
in robot_state State from which the pose should be calculated.
Returns
Vectorized 6x7 Jacobian, column-major.
Definition at line 83 of file model.cpp.
References franka::RobotState::EE_T_K, franka::RobotState::F_T_EE, and franka::RobotState::q.
Referenced by franka_hw::FrankaModelHandle::getBodyJacobian().
                                                                                      {
  return bodyJacobian(frame, robot_state.q, robot_state.F_T_EE, robot_state.
      EE_T_K);
}
bodyJacobian() [2/2]
std::array< double, 42 > franka::Model::bodyJacobian (Frame frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const
Gets the 6x7 Jacobian for the given frame, relative to that frame.
The Jacobian is represented as a 6x7 matrix in column-major format.
Parameters
in frame The desired frame.
in q Joint position.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 6x7 Jacobian, column-major.
Definition at line 88 of file model.cpp.
References franka::kEndEffector, franka::kFlange, franka::kJoint1, franka::kJoint2, franka::kJoint3, franka::kJoint4, franka::kJoint5, franka::kJoint6, franka::kJoint7, franka::kStiffness, and library_.
          {
  std::array<double, 42> output;
  switch (frame) {
    case Frame::kJoint1:
      library_->body_jacobian_joint1(output.data());
      break;
    case Frame::kJoint2:
      library_->body_jacobian_joint2(q.data(), output.data());
      break;
    case Frame::kJoint3:
      library_->body_jacobian_joint3(q.data(), output.data());
      break;
    case Frame::kJoint4:
      library_->body_jacobian_joint4(q.data(), output.data());
      break;
    case Frame::kJoint5:
      library_->body_jacobian_joint5(q.data(), output.data());
      break;
    case Frame::kJoint6:
      library_->body_jacobian_joint6(q.data(), output.data());
      break;
    case Frame::kJoint7:
      library_->body_jacobian_joint7(q.data(), output.data());
      break;
    case Frame::kFlange:
      library_->body_jacobian_flange(q.data(), output.data());
      break;
    case Frame::kEndEffector:
      library_->body_jacobian_ee(q.data(), F_T_EE.data(), output.data());
      break;
    case Frame::kStiffness:
      library_->body_jacobian_ee(
          q.data(),
          Eigen::Matrix4d(Eigen::Matrix4d(F_T_EE.data()) * Eigen::Matrix4d(EE_T_K.data())).data(),
          output.data());
      break;
    default:
      throw std::invalid_argument("Invalid frame given.");
  }
  return output;
}
coriolis() [1/2]
std::array< double, 7 > franka::Model::coriolis (const franka::RobotState & robot_state) const [noexcept]
Calculates the Coriolis force vector (state-space equation): $ c= C \times dq$, in $[Nm]$.
Parameters
in robot_state State from which the Coriolis force vector should be calculated.
Returns
Coriolis force vector.
Definition at line 205 of file model.cpp.
Referenced by franka_hw::FrankaModelHandle::getCoriolis(), and main().
             {
  return coriolis(robot_state.q, robot_state.dq, robot_state.I_total, robot_state.
      m_total,
                  robot_state.F_x_Ctotal);
}
coriolis() [2/2]
std::array< double, 7 > franka::Model::coriolis (const std::array< double, 7 > & q, const std::array< double, 7 > & dq, const std::array< double, 9 > & I_total, double m_total, const std::array< double, 3 > & F_x_Ctotal) const [noexcept]
Calculates the Coriolis force vector (state-space equation): $ c= C \times dq$, in $[Nm]$.
Parameters
in q Joint position.
in dq Joint velocity.
in I_total Inertia of the attached total load including end effector, relative to center of mass, given as vectorized 3x3 column-major matrix. Unit: $[kg \times m^2]$.
in m_total Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load. Unit: $[m]$.
Returns
Coriolis force vector.
Definition at line 211 of file model.cpp.
References library_.
                   {
  std::array<double, 7> output;
  library_->coriolis(q.data(), dq.data(), I_total.data(), m_total, F_x_Ctotal.data(),
                     output.data());
  return output;
}
gravity() [1/2]
std::array< double, 7 > franka::Model::gravity (const std::array< double, 7 > & q, double m_total, const std::array< double, 3 > & F_x_Ctotal, const std::array< double, 3 > & gravity_earth = {{0., 0., -9.81}}) const [noexcept]
Calculates the gravity vector. Unit: $[Nm]$.
Parameters
in q Joint position.
in m_total Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load. Unit: $[m]$.
in gravity_earth Earth's gravity vector. Unit: $\frac{m}{s^2}$. Default to {0.0, 0.0, -9.81}.
Returns
Gravity vector.
Definition at line 231 of file model.cpp.
References library_.
Referenced by franka_hw::FrankaModelHandle::getGravity(), gravity(), and main().
                                                             {
  std::array<double, 7> output;
  library_->gravity(q.data(), gravity_earth.data(), m_total, F_x_Ctotal.data(), output.data());
  return output;
}
gravity() [2/2]
std::array< double, 7 > franka::Model::gravity (const franka::RobotState & robot_state, const std::array< double, 3 > & gravity_earth = { {0., 0., -9.81}}) const [noexcept]
Calculates the gravity vector. Unit: $[Nm]$.
Parameters
in robot_state State from which the gravity vector should be calculated.
in gravity_earth Earth's gravity vector. Unit: $\frac{m}{s^2}$. Default to {0.0, 0.0, -9.81}.
Returns
Gravity vector.
Definition at line 225 of file model.cpp.
References gravity().
             {
  return gravity(robot_state.q, robot_state.m_total, robot_state.
      F_x_Ctotal, gravity_earth);
};
mass() [1/2]
std::array< double, 49 > franka::Model::mass (const franka::RobotState & robot_state) const [noexcept]
Calculates the 7x7 mass matrix. Unit: $[kg \times m^2]$.
Parameters
in robot_state State from which the pose should be calculated.
Returns
Vectorized 7x7 mass matrix, column-major.
Definition at line 189 of file model.cpp.
Referenced by franka_hw::FrankaModelHandle::getMass().
                                                                                         {
  return mass(robot_state.q, robot_state.I_total, robot_state.
      m_total, robot_state.F_x_Ctotal);
}
mass() [2/2]
std::array< double, 49 > franka::Model::mass (const std::array< double, 7 > & q, const std::array< double, 9 > & I_total, double m_total, const std::array< double, 3 > & F_x_Ctotal) const [noexcept]
Calculates the 7x7 mass matrix. Unit: $[kg \times m^2]$.
Parameters
in q Joint position.
in I_total Inertia of the attached total load including end effector, relative to center of mass, given as vectorized 3x3 column-major matrix. Unit: $[kg \times m^2]$.
in m_total Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load. Unit: $[m]$.
Returns
Vectorized 7x7 mass matrix, column-major.
Definition at line 193 of file model.cpp.
References library_.
                   {
  std::array<double, 49> output;
  library_->mass(q.data(), I_total.data(), m_total, F_x_Ctotal.data(), output.data());
  return output;
}
operator=()
Model & franka::Model::operator= (Model && model) [default], [noexcept]
Move-assigns this Model from another Model instance.
Parameters
in model Other Model instance.
Returns
Model instance.
Referenced by Model().
pose() [1/2]
std::array< double, 16 > franka::Model::pose (Frame frame, const franka::RobotState & robot_state) const
Gets the 4x4 pose matrix for the given frame in base frame.
The pose is represented as a 4x4 matrix in column-major format.
Parameters
in frame The desired frame.
in robot_state State from which the pose should be calculated.
Returns
Vectorized 4x4 pose matrix, column-major.
Definition at line 31 of file model.cpp.
References franka::RobotState::EE_T_K, franka::RobotState::F_T_EE, and franka::RobotState::q.
Referenced by franka_hw::FrankaModelHandle::getPose(), and main().
                                                                                       {
  return pose(frame, robot_state.q, robot_state.F_T_EE, robot_state.
      EE_T_K);
}
pose() [2/2]
std::array< double, 16 > franka::Model::pose (Frame frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const
Gets the 4x4 pose matrix for the given frame in base frame.
The pose is represented as a 4x4 matrix in column-major format.
Parameters
in frame The desired frame.
in q Joint position.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 4x4 pose matrix, column-major.
Definition at line 35 of file model.cpp.
References franka::kEndEffector, franka::kFlange, franka::kJoint1, franka::kJoint2, franka::kJoint3, franka::kJoint4, franka::kJoint5, franka::kJoint6, franka::kJoint7, franka::kStiffness, and library_.
          {
  std::array<double, 16> output;
  switch (frame) {
    case Frame::kJoint1:
      library_->joint1(q.data(), output.data());
      break;
    case Frame::kJoint2:
      library_->joint2(q.data(), output.data());
      break;
    case Frame::kJoint3:
      library_->joint3(q.data(), output.data());
      break;
    case Frame::kJoint4:
      library_->joint4(q.data(), output.data());
      break;
    case Frame::kJoint5:
      library_->joint5(q.data(), output.data());
      break;
    case Frame::kJoint6:
      library_->joint6(q.data(), output.data());
      break;
    case Frame::kJoint7:
      library_->joint7(q.data(), output.data());
      break;
    case Frame::kFlange:
      library_->flange(q.data(), output.data());
      break;
    case Frame::kEndEffector:
      library_->ee(q.data(), F_T_EE.data(), output.data());
      break;
    case Frame::kStiffness:
      library_->ee(
          q.data(),
          Eigen::Matrix4d(Eigen::Matrix4d(F_T_EE.data()) * Eigen::Matrix4d(EE_T_K.data())).data(),
          output.data());
      break;
    default:
      throw std::invalid_argument("Invalid frame given.");
  }
  return output;
}
zeroJacobian() [1/2]
std::array< double, 42 > franka::Model::zeroJacobian (Frame frame, const franka::RobotState & robot_state) const
Gets the 6x7 Jacobian for the given joint relative to the base frame.
The Jacobian is represented as a 6x7 matrix in column-major format.
Parameters
in frame The desired frame.
in robot_state State from which the pose should be calculated.
Returns
Vectorized 6x7 Jacobian, column-major.
Definition at line 136 of file model.cpp.
References franka::RobotState::EE_T_K, franka::RobotState::F_T_EE, and franka::RobotState::q.
Referenced by franka_hw::FrankaModelHandle::getZeroJacobian(), and main().
                                                                                      {
  return zeroJacobian(frame, robot_state.q, robot_state.F_T_EE, robot_state.
      EE_T_K);
};
zeroJacobian() [2/2]
std::array< double, 42 > franka::Model::zeroJacobian (Frame frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const
Gets the 6x7 Jacobian for the given joint relative to the base frame.
The Jacobian is represented as a 6x7 matrix in column-major format.
Parameters
in frame The desired frame.
in q Joint position.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 6x7 Jacobian, column-major.
Definition at line 141 of file model.cpp.
References franka::kEndEffector, franka::kFlange, franka::kJoint1, franka::kJoint2, franka::kJoint3, franka::kJoint4, franka::kJoint5, franka::kJoint6, franka::kJoint7, franka::kStiffness, and library_.
          {
  std::array<double, 42> output;
  switch (frame) {
    case Frame::kJoint1:
      library_->zero_jacobian_joint1(output.data());
      break;
    case Frame::kJoint2:
      library_->zero_jacobian_joint2(q.data(), output.data());
      break;
    case Frame::kJoint3:
      library_->zero_jacobian_joint3(q.data(), output.data());
      break;
    case Frame::kJoint4:
      library_->zero_jacobian_joint4(q.data(), output.data());
      break;
    case Frame::kJoint5:
      library_->zero_jacobian_joint5(q.data(), output.data());
      break;
    case Frame::kJoint6:
      library_->zero_jacobian_joint6(q.data(), output.data());
      break;
    case Frame::kJoint7:
      library_->zero_jacobian_joint7(q.data(), output.data());
      break;
    case Frame::kFlange:
      library_->zero_jacobian_flange(q.data(), output.data());
      break;
    case Frame::kEndEffector:
      library_->zero_jacobian_ee(q.data(), F_T_EE.data(), output.data());
      break;
    case Frame::kStiffness:
      library_->zero_jacobian_ee(
          q.data(),
          Eigen::Matrix4d(Eigen::Matrix4d(F_T_EE.data()) * Eigen::Matrix4d(EE_T_K.data())).data(),
          output.data());
      break;
    default:
      throw std::invalid_argument("Invalid frame given.");
  }
  return output;
}
Member Data Documentation
library_
std::unique_ptr<ModelLibrary> franka::Model::library_ [private]
Definition at line 280 of file model.h.
Referenced by bodyJacobian(), coriolis(), gravity(), mass(), pose(), and zeroJacobian().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/include/franka/model.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/model.cpp