testing::Sequence Class Reference
#include <gmock-spec-builders.h>
Public Member Functions
Sequence ()
void AddExpectation (const Expectation &expectation) const
Private Attributes
internal::linked_ptr< Expectation > last_expectation_
Detailed Description
Definition at line 619 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
Sequence()
testing::Sequence::Sequence () [inline]
Definition at line 622 of file gmock-spec-builders.h.
: last_expectation_(new Expectation) {}
Member Function Documentation
AddExpectation()
void testing::Sequence::AddExpectation (const Expectation & expectation) const
Definition at line 794 of file gmock-spec-builders.cc.
References testing::Expectation::expectation_base().
Referenced by testing::internal::FunctionMockerBase< R(A1, A2)>::AddNewExpectation(), and testing::internal::TypedExpectation< F >::InSequence().
                                                                  {
  if (*last_expectation_ != expectation) {
    if (last_expectation_->expectation_base() != NULL) {
      expectation.expectation_base()->immediate_prerequisites_
          += *last_expectation_;
    }
    *last_expectation_ = expectation;
  }
}
Member Data Documentation
last_expectation_
internal::linked_ptr<Expectation> testing::Sequence::last_expectation_ [private]
Definition at line 633 of file gmock-spec-builders.h.
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-spec-builders.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/src/gmock-spec-builders.cc