testing::CardinalityInterface Class Reference
#include <gmock-cardinalities.h>
Public Member Functions
virtual ~CardinalityInterface ()
virtual int ConservativeLowerBound () const
virtual int ConservativeUpperBound () const
virtual bool IsSatisfiedByCallCount (int call_count) const =0
virtual bool IsSaturatedByCallCount (int call_count) const =0
virtual void DescribeTo (::std::ostream *os) const =0
Detailed Description
Definition at line 59 of file gmock-cardinalities.h.
Constructor & Destructor Documentation
 CardinalityInterface()
virtual testing::CardinalityInterface::~CardinalityInterface () [inline], [virtual]
Definition at line 61 of file gmock-cardinalities.h.
{}
Member Function Documentation
ConservativeLowerBound()
virtual int testing::CardinalityInterface::ConservativeLowerBound () const [inline], [virtual]
Reimplemented in testing::anonymous_namespace{gmock-cardinalities.cc}::BetweenCardinalityImpl.
Definition at line 65 of file gmock-cardinalities.h.
{ return 0; }
ConservativeUpperBound()
virtual int testing::CardinalityInterface::ConservativeUpperBound () const [inline], [virtual]
Reimplemented in testing::anonymous_namespace{gmock-cardinalities.cc}::BetweenCardinalityImpl.
Definition at line 66 of file gmock-cardinalities.h.
References DescribeTo(), IsSatisfiedByCallCount(), and IsSaturatedByCallCount().
{ return INT_MAX; }
DescribeTo()
virtual void testing::CardinalityInterface::DescribeTo (::std::ostream * os) const [pure virtual]
Implemented in testing::anonymous_namespace{gmock-cardinalities.cc}::BetweenCardinalityImpl.
Referenced by ConservativeUpperBound().
IsSatisfiedByCallCount()
virtual bool testing::CardinalityInterface::IsSatisfiedByCallCount (int call_count) const [pure virtual]
Implemented in testing::anonymous_namespace{gmock-cardinalities.cc}::BetweenCardinalityImpl.
Referenced by ConservativeUpperBound().
IsSaturatedByCallCount()
virtual bool testing::CardinalityInterface::IsSaturatedByCallCount (int call_count) const [pure virtual]
Implemented in testing::anonymous_namespace{gmock-cardinalities.cc}::BetweenCardinalityImpl.
Referenced by ConservativeUpperBound().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-cardinalities.h