franka::LibraryDownloader Class Reference
#include <library_downloader.h>
Public Member Functions
LibraryDownloader (Network &network)
~LibraryDownloader ()
const std::string & path () const noexcept
Private Attributes
Poco::File model_library_file_
Detailed Description
Definition at line 13 of file library_downloader.h.
Constructor & Destructor Documentation
LibraryDownloader()
franka::LibraryDownloader::LibraryDownloader (Network & network)
Definition at line 18 of file library_downloader.cpp.
References path().
    : model_library_file_{Poco::TemporaryFile::tempName() + Poco::SharedLibrary::suffix(
      )} {
  using research_interface::robot::LoadModelLibrary;
  LoadModelLibrary::Architecture architecture;
  LoadModelLibrary::System operating_system;
#if defined(LIBFRANKA_X64)
  architecture = LoadModelLibrary::Architecture::kX64;
#elif defined(LIBFRANKA_X86)
  architecture = LoadModelLibrary::Architecture::kX86;
#elif defined(LIBFRANKA_ARM64)
  architecture = LoadModelLibrary::Architecture::kARM64;
#elif defined(LIBFRANKA_ARM)
  architecture = LoadModelLibrary::Architecture::kARM;
#else
  throw ModelException("libfranka: Unsupported architecture!");
#endif
#if defined(LIBFRANKA_WINDOWS)
  operating_system = LoadModelLibrary::System::kWindows;
#elif defined(LIBFRANKA_LINUX)
  operating_system = LoadModelLibrary::System::kLinux;
#else
  throw ModelException("libfranka: Unsupported operating system!");
#endif
  uint32_t command_id = network.tcpSendRequest<LoadModelLibrary>(architecture, operating_system);
  std::vector<uint8_t> buffer;
  LoadModelLibrary::Response response =
      network.tcpBlockingReceiveResponse<LoadModelLibrary>(command_id, &buffer);
  if (response.status != LoadModelLibrary::Status::kSuccess) {
    throw ModelException("libfranka: Server reports error when loading model library.");
  }
  try {
    std::ofstream model_library_stream(path().c_str(), std::ios_base::out | std::ios_base::binary);
    model_library_stream.write(reinterpret_cast<char*>(buffer.data()), buffer.size());
  } catch (const std::exception& ex) {
    throw ModelException("libfranka: Cannot save model library.");
  }
}
 LibraryDownloader()
franka::LibraryDownloader::~LibraryDownloader ()
Definition at line 60 of file library_downloader.cpp.
References model_library_file_, and path().
                                      {
  try {
    if (model_library_file_.exists()) {
      Poco::TemporaryFile::registerForDeletion(path());
      model_library_file_.remove();
    }
  } catch (...) {
  }
}
Member Function Documentation
path()
const std::string & franka::LibraryDownloader::path () const [noexcept]
Definition at line 70 of file library_downloader.cpp.
References model_library_file_.
Referenced by LibraryDownloader(), and ~LibraryDownloader().
                                                        {
  return model_library_file_.path();
}
Member Data Documentation
model_library_file_
Poco::File franka::LibraryDownloader::model_library_file_ [private]
Definition at line 21 of file library_downloader.h.
Referenced by path(), and ~LibraryDownloader().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/library_downloader.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/library_downloader.cpp