testing::ScopedFakeTestPartResultReporter Class Reference
#include <gtest-spi.h>
Public Types
enum InterceptMode { INTERCEPT_ONLY_CURRENT_THREAD,
INTERCEPT_ALL_THREADS
 }
Public Member Functions
ScopedFakeTestPartResultReporter (TestPartResultArray *result)
ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray *result)
virtual ~ScopedFakeTestPartResultReporter ()
virtual void ReportTestPartResult (const TestPartResult &result)
Private Member Functions
void Init ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter)
Private Attributes
const InterceptMode intercept_mode_
TestPartResultReporterInterface * old_reporter_
TestPartResultArray *const result_
Detailed Description
Definition at line 51 of file gtest-spi.h.
Member Enumeration Documentation
InterceptMode
enum testing::ScopedFakeTestPartResultReporter::InterceptMode
Enumerator
INTERCEPT_ONLY_CURRENT_THREAD
INTERCEPT_ALL_THREADS
Definition at line 55 of file gtest-spi.h.
                     {
    INTERCEPT_ONLY_CURRENT_THREAD, // Intercepts only thread local failures.
    INTERCEPT_ALL_THREADS // Intercepts all failures.
  };
Constructor & Destructor Documentation
ScopedFakeTestPartResultReporter() [1/2]
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (TestPartResultArray * result) [explicit]
Definition at line 563 of file gtest.cc.
References Init().
    : intercept_mode_(INTERCEPT_ONLY_CURRENT_THREAD),
      result_(result) {
  Init();
}
ScopedFakeTestPartResultReporter() [2/2]
testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter (InterceptMode intercept_mode, TestPartResultArray * result)
Definition at line 573 of file gtest.cc.
References Init().
    : intercept_mode_(intercept_mode),
      result_(result) {
  Init();
}
 ScopedFakeTestPartResultReporter()
testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () [virtual]
Definition at line 593 of file gtest.cc.
References testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, intercept_mode_, old_reporter_, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
                                                                    {
  internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
  if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
    impl->SetGlobalTestPartResultReporter(old_reporter_);
  } else {
    impl->SetTestPartResultReporterForCurrentThread(old_reporter_);
  }
}
Member Function Documentation
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::ScopedFakeTestPartResultReporter::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ScopedFakeTestPartResultReporter) [private]
Init()
void testing::ScopedFakeTestPartResultReporter::Init () [private]
Definition at line 580 of file gtest.cc.
References testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter(), testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread(), testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, intercept_mode_, old_reporter_, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
Referenced by ScopedFakeTestPartResultReporter().
                                            {
  internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
  if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
    old_reporter_ = impl->GetGlobalTestPartResultReporter();
    impl->SetGlobalTestPartResultReporter(this);
  } else {
    old_reporter_ = impl->GetTestPartResultReporterForCurrentThread();
    impl->SetTestPartResultReporterForCurrentThread(this);
  }
}
ReportTestPartResult()
void testing::ScopedFakeTestPartResultReporter::ReportTestPartResult (const TestPartResult & result) [virtual]
Implements testing::TestPartResultReporterInterface.
Definition at line 604 of file gtest.cc.
References testing::TestPartResultArray::Append(), and result_.
                                  {
  result_->Append(result);
}
Member Data Documentation
intercept_mode_
const InterceptMode testing::ScopedFakeTestPartResultReporter::intercept_mode_ [private]
Definition at line 82 of file gtest-spi.h.
Referenced by Init(), and ~ScopedFakeTestPartResultReporter().
old_reporter_
TestPartResultReporterInterface* testing::ScopedFakeTestPartResultReporter::old_reporter_ [private]
Definition at line 83 of file gtest-spi.h.
Referenced by Init(), and ~ScopedFakeTestPartResultReporter().
result_
TestPartResultArray* const testing::ScopedFakeTestPartResultReporter::result_ [private]
Definition at line 84 of file gtest-spi.h.
Referenced by ReportTestPartResult().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/include/gtest/gtest-spi.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/src/gtest.cc