franka::ModelLibrary Class Reference
#include <model_library.h>
Public Member Functions
ModelLibrary (Network &network)
Public Attributes
const std::function< decltype(Ji_J_J1)> body_jacobian_joint1
const std::function< decltype(Ji_J_J2)> body_jacobian_joint2
const std::function< decltype(Ji_J_J3)> body_jacobian_joint3
const std::function< decltype(Ji_J_J4)> body_jacobian_joint4
const std::function< decltype(Ji_J_J5)> body_jacobian_joint5
const std::function< decltype(Ji_J_J6)> body_jacobian_joint6
const std::function< decltype(Ji_J_J7)> body_jacobian_joint7
const std::function< decltype(Ji_J_J8)> body_jacobian_flange
const std::function< decltype(Ji_J_J9)> body_jacobian_ee
const std::function< decltype(M_NE)> mass
const std::function< decltype(O_J_J1)> zero_jacobian_joint1
const std::function< decltype(O_J_J2)> zero_jacobian_joint2
const std::function< decltype(O_J_J3)> zero_jacobian_joint3
const std::function< decltype(O_J_J4)> zero_jacobian_joint4
const std::function< decltype(O_J_J5)> zero_jacobian_joint5
const std::function< decltype(O_J_J6)> zero_jacobian_joint6
const std::function< decltype(O_J_J7)> zero_jacobian_joint7
const std::function< decltype(O_J_J8)> zero_jacobian_flange
const std::function< decltype(O_J_J9)> zero_jacobian_ee
const std::function< decltype(O_T_J1)> joint1
const std::function< decltype(O_T_J2)> joint2
const std::function< decltype(O_T_J3)> joint3
const std::function< decltype(O_T_J4)> joint4
const std::function< decltype(O_T_J5)> joint5
const std::function< decltype(O_T_J6)> joint6
const std::function< decltype(O_T_J7)> joint7
const std::function< decltype(O_T_J8)> flange
const std::function< decltype(O_T_J9)> ee
const std::function< decltype(c_NE)> coriolis
const std::function< decltype(g_NE)> gravity
Private Attributes
LibraryLoader loader_
Detailed Description
Definition at line 13 of file model_library.h.
Constructor & Destructor Documentation
ModelLibrary()
franka::ModelLibrary::ModelLibrary (franka::Network & network)
Definition at line 9 of file model_library.cpp.
References body_jacobian_ee, body_jacobian_flange, body_jacobian_joint2, body_jacobian_joint3, body_jacobian_joint4, body_jacobian_joint5, body_jacobian_joint6, body_jacobian_joint7, c_NE(), coriolis, ee, flange, g_NE(), franka::LibraryLoader::getSymbol(), gravity, Ji_J_J1(), Ji_J_J2(), Ji_J_J3(), Ji_J_J4(), Ji_J_J5(), Ji_J_J6(), Ji_J_J7(), Ji_J_J8(), Ji_J_J9(), joint1, joint2, joint3, joint4, joint5, joint6, joint7, loader_, M_NE(), mass, O_J_J1(), O_J_J2(), O_J_J3(), O_J_J4(), O_J_J5(), O_J_J6(), O_J_J7(), O_J_J8(), O_J_J9(), O_T_J1(), O_T_J2(), O_T_J3(), O_T_J4(), O_T_J5(), O_T_J6(), O_T_J7(), O_T_J8(), O_T_J9(), zero_jacobian_ee, zero_jacobian_flange, zero_jacobian_joint1, zero_jacobian_joint2, zero_jacobian_joint3, zero_jacobian_joint4, zero_jacobian_joint5, zero_jacobian_joint6, and zero_jacobian_joint7.
    : loader_(LibraryDownloader(network).path()),
      body_jacobian_joint1{reinterpret_cast<decltype(&
      Ji_J_J1)>(loader_.getSymbol("Ji_J_J1"))},
      body_jacobian_joint2{reinterpret_cast<decltype(&
      Ji_J_J2)>(loader_.getSymbol("Ji_J_J2"))},
      body_jacobian_joint3{reinterpret_cast<decltype(&
      Ji_J_J3)>(loader_.getSymbol("Ji_J_J3"))},
      body_jacobian_joint4{reinterpret_cast<decltype(&
      Ji_J_J4)>(loader_.getSymbol("Ji_J_J4"))},
      body_jacobian_joint5{reinterpret_cast<decltype(&
      Ji_J_J5)>(loader_.getSymbol("Ji_J_J5"))},
      body_jacobian_joint6{reinterpret_cast<decltype(&
      Ji_J_J6)>(loader_.getSymbol("Ji_J_J6"))},
      body_jacobian_joint7{reinterpret_cast<decltype(&
      Ji_J_J7)>(loader_.getSymbol("Ji_J_J7"))},
      body_jacobian_flange{reinterpret_cast<decltype(&
      Ji_J_J8)>(loader_.getSymbol("Ji_J_J8"))},
      body_jacobian_ee{reinterpret_cast<decltype(&Ji_J_J9)>(
      loader_.getSymbol("Ji_J_J9"))},
      mass{reinterpret_cast<decltype(&M_NE)>(loader_.getSymbol("M_NE"))},
      zero_jacobian_joint1{reinterpret_cast<decltype(&O_J_J1)>(
      loader_.getSymbol("O_J_J1"))},
      zero_jacobian_joint2{reinterpret_cast<decltype(&O_J_J2)>(
      loader_.getSymbol("O_J_J2"))},
      zero_jacobian_joint3{reinterpret_cast<decltype(&O_J_J3)>(
      loader_.getSymbol("O_J_J3"))},
      zero_jacobian_joint4{reinterpret_cast<decltype(&O_J_J4)>(
      loader_.getSymbol("O_J_J4"))},
      zero_jacobian_joint5{reinterpret_cast<decltype(&O_J_J5)>(
      loader_.getSymbol("O_J_J5"))},
      zero_jacobian_joint6{reinterpret_cast<decltype(&O_J_J6)>(
      loader_.getSymbol("O_J_J6"))},
      zero_jacobian_joint7{reinterpret_cast<decltype(&O_J_J7)>(
      loader_.getSymbol("O_J_J7"))},
      zero_jacobian_flange{reinterpret_cast<decltype(&O_J_J8)>(
      loader_.getSymbol("O_J_J8"))},
      zero_jacobian_ee{reinterpret_cast<decltype(&O_J_J9)>(
      loader_.getSymbol("O_J_J9"))},
      joint1{reinterpret_cast<decltype(&O_T_J1)>(loader_.
      getSymbol("O_T_J1"))},
      joint2{reinterpret_cast<decltype(&O_T_J2)>(loader_.
      getSymbol("O_T_J2"))},
      joint3{reinterpret_cast<decltype(&O_T_J3)>(loader_.
      getSymbol("O_T_J3"))},
      joint4{reinterpret_cast<decltype(&O_T_J4)>(loader_.
      getSymbol("O_T_J4"))},
      joint5{reinterpret_cast<decltype(&O_T_J5)>(loader_.
      getSymbol("O_T_J5"))},
      joint6{reinterpret_cast<decltype(&O_T_J6)>(loader_.
      getSymbol("O_T_J6"))},
      joint7{reinterpret_cast<decltype(&O_T_J7)>(loader_.
      getSymbol("O_T_J7"))},
      flange{reinterpret_cast<decltype(&O_T_J8)>(loader_.
      getSymbol("O_T_J8"))},
      ee{reinterpret_cast<decltype(&O_T_J9)>(loader_.getSymbol("O_T_J9"))},
      coriolis{reinterpret_cast<decltype(&c_NE)>(loader_.
      getSymbol("c_NE"))},
      gravity{reinterpret_cast<decltype(&g_NE)>(loader_.
      getSymbol("g_NE"))} {}
Member Data Documentation
body_jacobian_ee
const std::function<decltype(Ji_J_J9)> franka::ModelLibrary::body_jacobian_ee
Definition at line 29 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_flange
const std::function<decltype(Ji_J_J8)> franka::ModelLibrary::body_jacobian_flange
Definition at line 28 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint1
const std::function<decltype(Ji_J_J1)> franka::ModelLibrary::body_jacobian_joint1
Definition at line 21 of file model_library.h.
body_jacobian_joint2
const std::function<decltype(Ji_J_J2)> franka::ModelLibrary::body_jacobian_joint2
Definition at line 22 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint3
const std::function<decltype(Ji_J_J3)> franka::ModelLibrary::body_jacobian_joint3
Definition at line 23 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint4
const std::function<decltype(Ji_J_J4)> franka::ModelLibrary::body_jacobian_joint4
Definition at line 24 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint5
const std::function<decltype(Ji_J_J5)> franka::ModelLibrary::body_jacobian_joint5
Definition at line 25 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint6
const std::function<decltype(Ji_J_J6)> franka::ModelLibrary::body_jacobian_joint6
Definition at line 26 of file model_library.h.
Referenced by ModelLibrary().
body_jacobian_joint7
const std::function<decltype(Ji_J_J7)> franka::ModelLibrary::body_jacobian_joint7
Definition at line 27 of file model_library.h.
Referenced by ModelLibrary().
coriolis
const std::function<decltype(c_NE)> franka::ModelLibrary::coriolis
Definition at line 53 of file model_library.h.
Referenced by ModelLibrary().
ee
const std::function<decltype(O_T_J9)> franka::ModelLibrary::ee
Definition at line 51 of file model_library.h.
Referenced by ModelLibrary().
flange
const std::function<decltype(O_T_J8)> franka::ModelLibrary::flange
Definition at line 50 of file model_library.h.
Referenced by ModelLibrary().
gravity
const std::function<decltype(g_NE)> franka::ModelLibrary::gravity
Definition at line 54 of file model_library.h.
Referenced by ModelLibrary().
joint1
const std::function<decltype(O_T_J1)> franka::ModelLibrary::joint1
Definition at line 43 of file model_library.h.
Referenced by ModelLibrary().
joint2
const std::function<decltype(O_T_J2)> franka::ModelLibrary::joint2
Definition at line 44 of file model_library.h.
Referenced by ModelLibrary().
joint3
const std::function<decltype(O_T_J3)> franka::ModelLibrary::joint3
Definition at line 45 of file model_library.h.
Referenced by ModelLibrary().
joint4
const std::function<decltype(O_T_J4)> franka::ModelLibrary::joint4
Definition at line 46 of file model_library.h.
Referenced by ModelLibrary().
joint5
const std::function<decltype(O_T_J5)> franka::ModelLibrary::joint5
Definition at line 47 of file model_library.h.
Referenced by ModelLibrary().
joint6
const std::function<decltype(O_T_J6)> franka::ModelLibrary::joint6
Definition at line 48 of file model_library.h.
Referenced by ModelLibrary().
joint7
const std::function<decltype(O_T_J7)> franka::ModelLibrary::joint7
Definition at line 49 of file model_library.h.
Referenced by ModelLibrary().
loader_
LibraryLoader franka::ModelLibrary::loader_ [private]
Definition at line 18 of file model_library.h.
Referenced by ModelLibrary().
mass
const std::function<decltype(M_NE)> franka::ModelLibrary::mass
Definition at line 31 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_ee
const std::function<decltype(O_J_J9)> franka::ModelLibrary::zero_jacobian_ee
Definition at line 41 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_flange
const std::function<decltype(O_J_J8)> franka::ModelLibrary::zero_jacobian_flange
Definition at line 40 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint1
const std::function<decltype(O_J_J1)> franka::ModelLibrary::zero_jacobian_joint1
Definition at line 33 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint2
const std::function<decltype(O_J_J2)> franka::ModelLibrary::zero_jacobian_joint2
Definition at line 34 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint3
const std::function<decltype(O_J_J3)> franka::ModelLibrary::zero_jacobian_joint3
Definition at line 35 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint4
const std::function<decltype(O_J_J4)> franka::ModelLibrary::zero_jacobian_joint4
Definition at line 36 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint5
const std::function<decltype(O_J_J5)> franka::ModelLibrary::zero_jacobian_joint5
Definition at line 37 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint6
const std::function<decltype(O_J_J6)> franka::ModelLibrary::zero_jacobian_joint6
Definition at line 38 of file model_library.h.
Referenced by ModelLibrary().
zero_jacobian_joint7
const std::function<decltype(O_J_J7)> franka::ModelLibrary::zero_jacobian_joint7
Definition at line 39 of file model_library.h.
Referenced by ModelLibrary().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/model_library.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/model_library.cpp