Counter Class Reference
#include <sample4.h>
Public Member Functions
Counter ()
int Increment ()
void Print () const
Private Attributes
int counter_
Detailed Description
Definition at line 38 of file sample4.h.
Constructor & Destructor Documentation
Counter()
Counter::Counter () [inline]
Definition at line 44 of file sample4.h.
References Increment(), and Print().
: counter_(0) {}
Member Function Documentation
Increment()
int Counter::Increment ()
Definition at line 39 of file sample4.cc.
References counter_.
Referenced by Counter(), and TEST().
                       {
  return counter_++;
}
Print()
void Counter::Print () const
Definition at line 44 of file sample4.cc.
References counter_.
Referenced by Counter().
                          {
  printf("%d", counter_);
}
Member Data Documentation
counter_
int Counter::counter_ [private]
Definition at line 40 of file sample4.h.
Referenced by Increment(), and Print().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample4.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample4.cc