franka::Robot Class Reference
#include <robot.h>
Classes
class Impl
Public Types
using ServerVersion = uint16_t
Public Member Functions
Robot (const std::string &franka_address, RealtimeConfig realtime_config=RealtimeConfig::kEnforce, size_t log_size=50)
Robot (Robot &&other) noexcept
Robot & operator= (Robot &&other) noexcept
~Robot () noexcept
void read (std::function< bool(const RobotState &)> read_callback)
RobotState readOnce ()
Model loadModel ()
ServerVersion serverVersion () const noexcept
 Motion generation and joint-level torque commands
The following methods allow to perform motion generation and/or send joint-level torque commands without gravity and friction by providing callback functions.
Only one of these methods can be active at the same time; a franka::ControlException is thrown otherwise.
When a robot state is received, the callback function is used to calculate the response: the desired values for that time step. After sending back the response, the callback function will be called again with the most recently received robot state. Since the robot is controlled with a 1 kHz frequency, the callback functions have to compute their result in a short time frame in order to be accepted. Callback functions take two parameters:
A franka::RobotState showing the current robot state.
A franka::Duration to indicate the time since the last callback invocation. Thus, the duration is zero on the first invocation of the callback function!
The following incomplete example shows the general structure of a callback function:
double time = 0.0;
auto control_callback = [&time](const franka::RobotState& robot_state,
                                franka::Duration time_step) ->
      franka::JointPositions {
  time += time_step.toSec(); // Update time at the beginning of the callback.
  franka::JointPositions output = getJointPositions(time);
  if (time >= max_time) {
    // Return MotionFinished at the end of the trajectory.
    return franka::MotionFinished(output);
  }
  return output;
}
void control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< JointPositions(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< JointVelocities(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< CartesianPose(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< CartesianVelocities(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< JointPositions(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode=ControllerMode::kJointImpedance, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< JointVelocities(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode=ControllerMode::kJointImpedance, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< CartesianPose(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode=ControllerMode::kJointImpedance, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
void control (std::function< CartesianVelocities(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode=ControllerMode::kJointImpedance, bool limit_rate=true, double cutoff_frequency=kDefaultCutoffFrequency)
 Commands
Commands are executed by communicating with the robot over the network. These functions should therefore not be called from within control or motion generator loops.
VirtualWallCuboid getVirtualWall (int32_t id)
void setCollisionBehavior (const std::array< double, 7 > &lower_torque_thresholds_acceleration, const std::array< double, 7 > &upper_torque_thresholds_acceleration, const std::array< double, 7 > &lower_torque_thresholds_nominal, const std::array< double, 7 > &upper_torque_thresholds_nominal, const std::array< double, 6 > &lower_force_thresholds_acceleration, const std::array< double, 6 > &upper_force_thresholds_acceleration, const std::array< double, 6 > &lower_force_thresholds_nominal, const std::array< double, 6 > &upper_force_thresholds_nominal)
void setCollisionBehavior (const std::array< double, 7 > &lower_torque_thresholds, const std::array< double, 7 > &upper_torque_thresholds, const std::array< double, 6 > &lower_force_thresholds, const std::array< double, 6 > &upper_force_thresholds)
void setJointImpedance (const std::array< double, 7 > &K_theta)
void setCartesianImpedance (const std::array< double, 6 > &K_x)
void setGuidingMode (const std::array< bool, 6 > &guiding_mode, bool elbow)
void setK (const std::array< double, 16 > &EE_T_K)
void setEE (const std::array< double, 16 > &F_T_EE)
void setLoad (double load_mass, const std::array< double, 3 > &F_x_Cload, const std::array< double, 9 > &load_inertia)
void setFilters (double joint_position_filter_frequency, double joint_velocity_filter_frequency, double cartesian_position_filter_frequency, double cartesian_velocity_filter_frequency, double controller_filter_frequency)
void automaticErrorRecovery ()
void stop ()
Private Attributes
std::unique_ptr< Impl > impl_
std::mutex control_mutex_
Detailed Description
Maintains a network connection to the robot, provides the current robot state, gives access to the model library and allows to control the robot.
Note
The members of this class are threadsafe.
End effector frame EE
While the end effector parameters are set in a configuration file, it is possible to change the end effector frame with Robot::setEE.
Stiffness frame K
The stiffness frame is used for Cartesian impedance control, and for measuring and applying forces. It can be set with Robot::setK.
Definition at line 42 of file robot.h.
Member Typedef Documentation
ServerVersion
using franka::Robot::ServerVersion = uint16_t
Version of the robot server.
Definition at line 47 of file robot.h.
Constructor & Destructor Documentation
Robot() [1/2]
franka::Robot::Robot (const std::string & franka_address, RealtimeConfig realtime_config = RealtimeConfig::kEnforce, size_t log_size = 50) [explicit]
Establishes a connection with the robot.
Parameters
in franka_address IP/hostname of the robot.
in realtime_config if set to Enforce, an exception will be thrown if realtime priority cannot be set when required. Setting realtime_config to Ignore disables this behavior.
in log_size sets how many last states should be kept for logging purposes. The log is provided when a ControlException is thrown.
Exceptions
NetworkException if the connection is unsuccessful.
IncompatibleVersionException if this version of libfranka is not supported.
Definition at line 13 of file robot.cpp.
References research_interface::robot::kCommandPort, and ~Robot().
    : impl_{new Robot::Impl(
          std::make_unique<Network>(franka_address,
      research_interface::robot::kCommandPort),
          log_size,
          realtime_config)} {}
Robot() [2/2]
franka::Robot::Robot (Robot && other) [noexcept]
Move-constructs a new Robot instance.
Parameters
in other Other Robot instance.
Definition at line 22 of file robot.cpp.
References testing::_, impl_, and franka_gripper::move().
                                   {
  std::lock_guard<std::mutex> _(other.control_mutex_);
  impl_ = std::move(other.impl_);
}
 Robot()
franka::Robot::~Robot () [default], [noexcept]
Closes the connection.
Referenced by Robot().
Member Function Documentation
automaticErrorRecovery()
void franka::Robot::automaticErrorRecovery ()
Runs automatic error recovery on the robot.
Automatic error recovery e.g. resets the robot after a collision occurred.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 298 of file robot.cpp.
References impl_.
Referenced by main().
                                   {
  impl_->executeCommand<research_interface::robot::AutomaticErrorRecovery
      >();
}
control() [1/9]
void franka::Robot::control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for sending joint-level torque commands.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in control_callback Callback function providing joint-level torque commands. See here for more details.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to torque control or motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint-level torque commands are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 41 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
Referenced by main(), and franka_hw::FrankaHW::prepareSwitch().
                                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<JointVelocities> loop(*impl_, std::move(control_callback),
                                    [](const RobotState&, Duration) -> JointVelocities {
                                      return {{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}};
                                    },
                                    limit_rate, cutoff_frequency);
  loop();
}
control() [2/9]
void franka::Robot::control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< JointPositions(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for sending joint-level torque commands and joint positions.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in control_callback Callback function providing joint-level torque commands. See here for more details.
in motion_generator_callback Callback function for motion generation. See here for more details.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to torque control or motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint-level torque or joint position commands are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 59 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<JointPositions> loop(*impl_, std::move(control_callback),
                                   std::move(motion_generator_callback), limit_rate,
                                   cutoff_frequency);
  loop();
}
control() [3/9]
void franka::Robot::control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< JointVelocities(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for sending joint-level torque commands and joint velocities.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in control_callback Callback function providing joint-level torque commands. See here for more details.
in motion_generator_callback Callback function for motion generation. See here for more details.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to torque control or motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint-level torque or joint velocitiy commands are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 77 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<JointVelocities> loop(*impl_, std::move(control_callback),
                                    std::move(motion_generator_callback), limit_rate,
                                    cutoff_frequency);
  loop();
}
control() [4/9]
void franka::Robot::control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< CartesianPose(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for sending joint-level torque commands and Cartesian poses.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in control_callback Callback function providing joint-level torque commands. See here for more details.
in motion_generator_callback Callback function for motion generation. See here for more details.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to torque control or motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint-level torque or Cartesian pose command elements are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 95 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<CartesianPose> loop(*impl_, std::move(control_callback),
                                  std::move(motion_generator_callback), limit_rate,
                                  cutoff_frequency);
  loop();
}
control() [5/9]
void franka::Robot::control (std::function< Torques(const RobotState &, franka::Duration)> control_callback, std::function< CartesianVelocities(const RobotState &, franka::Duration)> motion_generator_callback, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for sending joint-level torque commands and Cartesian velocities.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in control_callback Callback function providing joint-level torque commands. See here for more details.
in motion_generator_callback Callback function for motion generation. See here for more details.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to torque control or motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint-level torque or Cartesian velocity command elements are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 113 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<CartesianVelocities> loop(*impl_, std::move(control_callback),
                                        std::move(motion_generator_callback), limit_rate,
                                        cutoff_frequency);
  loop();
}
control() [6/9]
void franka::Robot::control (std::function< JointPositions(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode = ControllerMode::kJointImpedance, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for a joint position motion generator with a given controller mode.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in motion_generator_callback Callback function for motion generation. See here for more details.
in controller_mode Controller to use to execute the motion.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint position commands are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 131 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<JointPositions> loop(*impl_, controller_mode, std::move(
      motion_generator_callback),
                                   limit_rate, cutoff_frequency);
  loop();
}
control() [7/9]
void franka::Robot::control (std::function< JointVelocities(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode = ControllerMode::kJointImpedance, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for a joint velocity motion generator with a given controller mode.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in motion_generator_callback Callback function for motion generation. See here for more details.
in controller_mode Controller to use to execute the motion.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if joint velocity commands are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 148 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<JointVelocities> loop(*impl_, controller_mode, std::move(
      motion_generator_callback),
                                    limit_rate, cutoff_frequency);
  loop();
}
control() [8/9]
void franka::Robot::control (std::function< CartesianPose(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode = ControllerMode::kJointImpedance, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for a Cartesian pose motion generator with a given controller mode.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in motion_generator_callback Callback function for motion generation. See here for more details.
in controller_mode Controller to use to execute the motion.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if Cartesian pose command elements are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 165 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<CartesianPose> loop(*impl_, controller_mode, std::move(
      motion_generator_callback),
                                  limit_rate, cutoff_frequency);
  loop();
}
control() [9/9]
void franka::Robot::control (std::function< CartesianVelocities(const RobotState &, franka::Duration)> motion_generator_callback, ControllerMode controller_mode = ControllerMode::kJointImpedance, bool limit_rate = true, double cutoff_frequency = kDefaultCutoffFrequency)
Starts a control loop for a Cartesian velocity motion generator with a given controller mode.
Sets realtime priority for the current thread. Cannot be executed while another control or motion generator loop is active.
Parameters
in motion_generator_callback Callback function for motion generation. See here for more details.
in controller_mode Controller to use to execute the motion.
in limit_rate True if rate limiting should be activated. True by default. This could distort your motion!
in cutoff_frequency Cutoff frequency for a first order low-pass filter applied on the user commanded signal. Set to franka::kMaxCutoffFrequency to disable.
Exceptions
ControlException if an error related to motion generation occurred.
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
RealtimeException if realtime priority cannot be set for the current thread.
std::invalid_argument if Cartesian velocity command elements are NaN or infinity.
See also
Robot::Robot to change behavior if realtime priority cannot be set.
Definition at line 182 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                                             {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  ControlLoop<CartesianVelocities> loop(
      *impl_, controller_mode, std::move(motion_generator_callback), limit_rate,
      cutoff_frequency);
  loop();
}
getVirtualWall()
VirtualWallCuboid franka::Robot::getVirtualWall (int32_t id)
Returns the parameters of a virtual wall.
Parameters
in id ID of the virtual wall.
Returns
Parameters of virtual wall.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 227 of file robot.cpp.
References impl_.
                                                  {
  VirtualWallCuboid virtual_wall;
  impl_->executeCommand<research_interface::robot::GetCartesianLimit
      >(id, &virtual_wall);
  return virtual_wall;
}
loadModel()
Model franka::Robot::loadModel ()
Loads the model library from the robot.
Returns
Model instance.
Exceptions
ModelException if the model library cannot be loaded.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 306 of file robot.cpp.
References impl_.
Referenced by main().
                       {
  return impl_->loadModel();
}
operator=()
Robot & franka::Robot::operator= (Robot && other) [noexcept]
Move-assigns this Robot from another Robot instance.
Parameters
in other Other Robot instance.
Returns
Robot instance.
Definition at line 27 of file robot.cpp.
References control_mutex_, impl_, and franka_gripper::move().
                                              {
  if (&other != this) {
    std::unique_lock<std::mutex> this_lock(control_mutex_, std::defer_lock);
    std::unique_lock<std::mutex> other_lock(other.control_mutex_, std::defer_lock);
    std::lock(this_lock, other_lock);
    impl_ = std::move(other.impl_);
  }
  return *this;
}
read()
void franka::Robot::read (std::function< bool(const RobotState &)> read_callback)
Starts a loop for reading the current robot state.
Cannot be executed while a control or motion generator loop is running.
This minimal example will print the robot state 100 times:
franka::Robot robot("robot.franka.de");
size_t count = 0;
robot.read([&count](const franka::RobotState& robot_state) {
  std::cout << robot_state << std::endl;
  return count++ < 100;
});
Parameters
in read_callback Callback function for robot state reading.
Exceptions
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 200 of file robot.cpp.
References control_mutex_, and impl_.
Referenced by main().
                                                                   {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  while (true) {
    RobotState robot_state = impl_->update(nullptr, nullptr);
    if (!read_callback(robot_state)) {
      break;
    }
  }
}
readOnce()
RobotState franka::Robot::readOnce ()
Waits for a robot state update and returns it.
Cannot be executed while a control or motion generator loop is running.
Returns
Current robot state.
Exceptions
InvalidOperationException if a conflicting operation is already running.
NetworkException if the connection is lost, e.g. after a timeout.
See also
Robot::read for a way to repeatedly receive the robot state.
Definition at line 216 of file robot.cpp.
References control_mutex_, and impl_.
Referenced by main().
                           {
  std::unique_lock<std::mutex> l(control_mutex_, std::try_to_lock);
  if (!l.owns_lock()) {
    throw InvalidOperationException(
        "libfranka robot: Cannot perform this operation while another control or read operation "
        "is running.");
  }
  return impl_->readOnce();
}
serverVersion()
Robot::ServerVersion franka::Robot::serverVersion () const [noexcept]
Returns the software version reported by the connected server.
Returns
Software version of the connected server.
Definition at line 37 of file robot.cpp.
References impl_.
                                                       {
  return impl_->serverVersion();
}
setCartesianImpedance()
void franka::Robot::setCartesianImpedance (const std::array< double, 6 > & K_x)
Sets the Cartesian impedance for (x, y, z, roll, pitch, yaw) in the internal controller.
User-provided torques are not affected by this setting.
Parameters
in K_x Cartesian impedance values $K_x=(x, y, z, R, P, Y)$.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 263 of file robot.cpp.
References impl_.
Referenced by franka_control::setCartesianImpedance(), and setDefaultBehavior().
                                    { // NOLINT(readability-identifier-naming)
  impl_->executeCommand<research_interface::robot::SetCartesianImpedance
      >(K_x);
}
setCollisionBehavior() [1/2]
void franka::Robot::setCollisionBehavior (const std::array< double, 7 > & lower_torque_thresholds_acceleration, const std::array< double, 7 > & upper_torque_thresholds_acceleration, const std::array< double, 7 > & lower_torque_thresholds_nominal, const std::array< double, 7 > & upper_torque_thresholds_nominal, const std::array< double, 6 > & lower_force_thresholds_acceleration, const std::array< double, 6 > & upper_force_thresholds_acceleration, const std::array< double, 6 > & lower_force_thresholds_nominal, const std::array< double, 6 > & upper_force_thresholds_nominal)
Changes the collision behavior.
Set separate torque and force boundaries for acceleration/deceleration and constant velocity movement phases.
Forces or torques between lower and upper threshold are shown as contacts in the RobotState. Forces or torques above the upper threshold are registered as collision and cause the robot to stop moving.
Parameters
in lower_torque_thresholds_acceleration Contact torque thresholds during acceleration/deceleration for each joint in $[Nm]$.
in upper_torque_thresholds_acceleration Collision torque thresholds during acceleration/deceleration for each joint in $[Nm]$.
in lower_torque_thresholds_nominal Contact torque thresholds for each joint in $[Nm]$.
in upper_torque_thresholds_nominal Collision torque thresholds for each joint in $[Nm]$.
in lower_force_thresholds_acceleration Contact force thresholds during acceleration/deceleration for $(x,y,z,R,P,Y)$ in $[N]$.
in upper_force_thresholds_acceleration Collision force thresholds during acceleration/deceleration for $(x,y,z,R,P,Y)$ in $[N]$.
in lower_force_thresholds_nominal Contact force thresholds for $(x,y,z,R,P,Y)$ in $[N]$.
in upper_force_thresholds_nominal Collision force thresholds for $(x,y,z,R,P,Y)$ in $[N]$.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
See also
RobotState::cartesian_contact
RobotState::cartesian_collision
RobotState::joint_contact
RobotState::joint_collision
Robot::automaticErrorRecovery for performing a reset after a collision.
Definition at line 233 of file robot.cpp.
References impl_.
Referenced by main(), setDefaultBehavior(), franka_control::setForceTorqueCollisionBehavior(), and franka_control::setFullCollisionBehavior().
                                                                                            {
  impl_->executeCommand<research_interface::robot::SetCollisionBehavior
      >(
      lower_torque_thresholds_acceleration, upper_torque_thresholds_acceleration,
      lower_torque_thresholds_nominal, upper_torque_thresholds_nominal,
      lower_force_thresholds_acceleration, upper_force_thresholds_acceleration,
      lower_force_thresholds_nominal, upper_force_thresholds_nominal);
}
setCollisionBehavior() [2/2]
void franka::Robot::setCollisionBehavior (const std::array< double, 7 > & lower_torque_thresholds, const std::array< double, 7 > & upper_torque_thresholds, const std::array< double, 6 > & lower_force_thresholds, const std::array< double, 6 > & upper_force_thresholds)
Changes the collision behavior.
Set common torque and force boundaries for acceleration/deceleration and constant velocity movement phases.
Forces or torques between lower and upper threshold are shown as contacts in the RobotState. Forces or torques above the upper threshold are registered as collision and cause the robot to stop moving.
Parameters
in lower_torque_thresholds Contact torque thresholds for each joint in $[Nm]$.
in upper_torque_thresholds Collision torque thresholds for each joint in $[Nm]$.
in lower_force_thresholds Contact force thresholds for $(x,y,z,R,P,Y)$ in $[N]$.
in upper_force_thresholds Collision force thresholds for $(x,y,z,R,P,Y)$ in $[N]$.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
See also
RobotState::cartesian_contact
RobotState::cartesian_collision
RobotState::joint_contact
RobotState::joint_collision
Robot::automaticErrorRecovery for performing a reset after a collision.
Definition at line 248 of file robot.cpp.
References impl_.
                                                                                    {
  impl_->executeCommand<research_interface::robot::SetCollisionBehavior
      >(
      lower_torque_thresholds, upper_torque_thresholds, lower_torque_thresholds,
      upper_torque_thresholds, lower_force_thresholds, upper_force_thresholds,
      lower_force_thresholds, upper_force_thresholds);
}
setEE()
void franka::Robot::setEE (const std::array< double, 16 > & F_T_EE)
Sets the transformation $^FT_{EE}$ from flange to end effector frame.
The transformation matrix is represented as a vectorized 4x4 matrix in column-major format.
Parameters
in F_T_EE Vectorized flange-to-EE transformation matrix $^FT_{EE}$, column-major.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
See also
RobotState::O_T_EE for end effector pose in world base frame.
Robot for an explanation of the EE frame.
Definition at line 276 of file robot.cpp.
References impl_.
Referenced by franka_control::setEEFrame().
                                                    { // NOLINT(readability-identifier-naming)
  impl_->executeCommand<research_interface::robot::SetFToEE>(F_T_EE
      );
}
setFilters()
void franka::Robot::setFilters (double joint_position_filter_frequency, double joint_velocity_filter_frequency, double cartesian_position_filter_frequency, double cartesian_velocity_filter_frequency, double controller_filter_frequency)
Sets the cut off frequency for the given motion generator or controller.
Deprecated
Deprecated Use franka::lowpassFilter() instead.
Allowed input range for all the filters is between 1.0 Hz and 1000.0 Hz. If the value is set to maximum (1000Hz) then no filtering is done.
Parameters
in joint_position_filter_frequency Frequency at which the commanded joint position is cut off.
in joint_velocity_filter_frequency Frequency at which the commanded joint velocity is cut off.
in cartesian_position_filter_frequency Frequency at which the commanded Cartesian position is cut off.
in cartesian_velocity_filter_frequency Frequency at which the commanded Cartesian velocity is cut off.
in controller_filter_frequency Frequency at which the commanded torque is cut off.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 287 of file robot.cpp.
References impl_.
                                                           {
  impl_->executeCommand<research_interface::robot::SetFilters>(
      joint_position_filter_frequency, joint_velocity_filter_frequency,
      cartesian_position_filter_frequency, cartesian_velocity_filter_frequency,
      controller_filter_frequency);
}
setGuidingMode()
void franka::Robot::setGuidingMode (const std::array< bool, 6 > & guiding_mode, bool elbow)
Locks or unlocks guiding mode movement in (x, y, z, roll, pitch, yaw).
If a flag is set to true, movement is unlocked.
Note
Guiding mode can be enabled by pressing the two opposing buttons near the robot's flange.
Parameters
in guiding_mode Unlocked movement in (x, y, z, R, P, Y) in guiding mode.
in elbow True if the elbow is free in guiding mode, false otherwise.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 268 of file robot.cpp.
References impl_.
                                                                            {
  impl_->executeCommand<research_interface::robot::SetGuidingMode
      >(guiding_mode, elbow);
}
setJointImpedance()
void franka::Robot::setJointImpedance (const std::array< double, 7 > & K_theta)
Sets the impedance for each joint in the internal controller.
User-provided torques are not affected by this setting.
Parameters
in K_theta Joint impedance values $K_{\theta}$.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 258 of file robot.cpp.
References impl_.
Referenced by main(), setDefaultBehavior(), and franka_control::setJointImpedance().
                                        { // NOLINT(readability-identifier-naming)
  impl_->executeCommand<research_interface::robot::SetJointImpedance
      >(K_theta);
}
setK()
void franka::Robot::setK (const std::array< double, 16 > & EE_T_K)
Sets the transformation $^{EE}T_K$ from end effector frame to stiffness frame.
The transformation matrix is represented as a vectorized 4x4 matrix in column-major format.
Parameters
in EE_T_K Vectorized EE-to-K transformation matrix $^{EE}T_K$, column-major.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
See also
Robot for an explanation of the stiffness frame.
Definition at line 272 of file robot.cpp.
References impl_.
Referenced by franka_control::setKFrame().
                                                   { // NOLINT(readability-identifier-naming)
  impl_->executeCommand<research_interface::robot::SetEEToK>(EE_T_K
      );
}
setLoad()
void franka::Robot::setLoad (double load_mass, const std::array< double, 3 > & F_x_Cload, const std::array< double, 9 > & load_inertia)
Sets dynamic parameters of a payload.
Note
This is not for setting end effector parameters, which have to be set in the administrator's interface.
Parameters
in load_mass Mass of the load in $[kg]$.
in F_x_Cload Translation from flange to center of mass of load $^Fx_{C_\text{load}}$ in $[m]$.
in load_inertia Inertia matrix $I_\text{load}$ in $[kg \times m^2]$, column-major.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 280 of file robot.cpp.
References impl_.
Referenced by franka_control::setLoad().
                                             {
  impl_->executeCommand<research_interface::robot::SetLoad>(
      load_mass, F_x_Cload, load_inertia);
}
stop()
void franka::Robot::stop ()
Stops all currently running motions.
If a control or motion generator loop is running in another thread, it will be preempted with a franka::ControlException.
Exceptions
CommandException if the Control reports an error.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 302 of file robot.cpp.
References impl_.
                 {
  impl_->executeCommand<research_interface::robot::StopMove>();
}
Member Data Documentation
control_mutex_
std::mutex franka::Robot::control_mutex_ [private]
Definition at line 689 of file robot.h.
Referenced by control(), operator=(), read(), and readOnce().
impl_
std::unique_ptr<Impl> franka::Robot::impl_ [private]
Definition at line 685 of file robot.h.
Referenced by automaticErrorRecovery(), control(), getVirtualWall(), loadModel(), operator=(), read(), readOnce(), Robot(), serverVersion(), setCartesianImpedance(), setCollisionBehavior(), setEE(), setFilters(), setGuidingMode(), setJointImpedance(), setK(), setLoad(), and stop().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/include/franka/robot.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/robot.cpp