testing::Message Class Reference
#include <gtest-message.h>
Public Member Functions
Message ()
Message (const Message &msg)
Message (const char *str)
template<typename T >
Message & operator<< (const T &val)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
Message & operator<< (const wchar_t *wide_c_str)
Message & operator<< (wchar_t *wide_c_str)
std::string GetString () const
Private Types
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
Private Member Functions
void operator= (const Message &)
Private Attributes
const internal::scoped_ptr< ::std::stringstream > ss_
Detailed Description
Definition at line 85 of file gtest-message.h.
Member Typedef Documentation
BasicNarrowIoManip
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) [private]
Definition at line 89 of file gtest-message.h.
Constructor & Destructor Documentation
Message() [1/3]
testing::Message::Message ()
Definition at line 946 of file gtest.cc.
                 : ss_(new ::std::stringstream) {
  // By default, we want there to be enough precision when printing
  // a double to a Message.
  *ss_ << std::setprecision(std::numeric_limits<double>::digits10 + 2);
}
Message() [2/3]
testing::Message::Message (const Message & msg) [inline]
Definition at line 96 of file gtest-message.h.
References GetString().
                              : ss_(new ::std::stringstream) { // NOLINT
    *ss_ << msg.GetString();
  }
Message() [3/3]
testing::Message::Message (const char * str) [inline], [explicit]
Definition at line 101 of file gtest-message.h.
References testing::operator<<().
                                    : ss_(new ::std::stringstream) {
    *ss_ << str;
  }
Member Function Documentation
GetString()
std::string testing::Message::GetString () const
Definition at line 981 of file gtest.cc.
References testing::internal::scoped_ptr< T >::get(), ss_, and testing::internal::StringStreamToString().
Referenced by testing::UnitTest::AddTestPartResult(), testing::AssertionResult::AppendMessage(), testing::internal::AppendUserMessage(), testing::internal::XmlUnitTestResultPrinter::EscapeXml(), testing::internal::FlagToEnvVar(), testing::FormatWordList(), testing::internal::GetBoolAssertionFailureMessage(), testing::Test::HasSameFixtureClass(), testing::internal::MakeAndRegisterTestInfo(), Message(), testing::operator<<(), testing::internal::ParseInt32(), testing::Test::RecordProperty(), testing::internal::ShouldShard(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
                                   {
  return internal::StringStreamToString(ss_.get());
}
operator<<() [1/6]
template<typename T >
Message& testing::Message::operator<< (const T & val) [inline]
Definition at line 115 of file gtest-message.h.
Referenced by operator<<().
                                            {
    // Some libraries overload << for STL containers. These
    // overloads are defined in the global namespace instead of ::std.
    //
    // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
    // overloads are visible in either the std namespace or the global
    // namespace, but not other namespaces, including the testing
    // namespace which Google Test's Message class is in.
    //
    // To allow STL containers (and other types that has a << operator
    // defined in the global namespace) to be used in Google Test
    // assertions, testing::Message must access the custom << operator
    // from the global namespace. With this using declaration,
    // overloads of << defined in the global namespace and those
    // visible via Koenig lookup are both exposed in this function.
    using ::operator <<;
    *ss_ << val;
    return *this;
  }
operator<<() [2/6]
template<typename T >
Message& testing::Message::operator<< (T *const & pointer) [inline]
Definition at line 149 of file gtest-message.h.
                                                 { // NOLINT
    if (pointer == NULL) {
      *ss_ << "(null)";
    } else {
      *ss_ << pointer;
    }
    return *this;
  }
operator<<() [3/6]
Message& testing::Message::operator<< (BasicNarrowIoManip val) [inline]
Definition at line 165 of file gtest-message.h.
                                               {
    *ss_ << val;
    return *this;
  }
operator<<() [4/6]
Message& testing::Message::operator<< (bool b) [inline]
Definition at line 171 of file gtest-message.h.
References testing::operator<<().
                               {
    return *this << (b ? "true" : "false");
  }
operator<<() [5/6]
Message & testing::Message::operator<< (const wchar_t * wide_c_str)
Definition at line 954 of file gtest.cc.
References testing::internal::String::ShowWideCString().
                                                       {
  return *this << internal::String::ShowWideCString(wide_c_str);
}
operator<<() [6/6]
Message & testing::Message::operator<< (wchar_t * wide_c_str)
Definition at line 957 of file gtest.cc.
References operator<<(), and testing::internal::String::ShowWideCString().
                                                 {
  return *this << internal::String::ShowWideCString(wide_c_str);
}
operator=()
void testing::Message::operator= (const Message &) [private]
Member Data Documentation
ss_
const internal::scoped_ptr< ::std::stringstream> testing::Message::ss_ [private]
Definition at line 224 of file gtest-message.h.
Referenced by GetString().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/include/gtest/gtest-message.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/src/gtest.cc