testing::internal::BuiltInDefaultValue< T > Class Template Reference
#include <gmock-actions.h>
Static Public Member Functions
static bool Exists ()
static T Get ()
Detailed Description
template<typename T>
class testing::internal::BuiltInDefaultValue< T >
Definition at line 97 of file gmock-actions.h.
Member Function Documentation
Exists()
template<typename T >
static bool testing::internal::BuiltInDefaultValue< T >::Exists () [inline], [static]
Definition at line 112 of file gmock-actions.h.
Referenced by testing::internal::BuiltInDefaultValue< const T >::Exists(), testing::DefaultValue< T >::Exists(), and testing::DefaultValue< T & >::Exists().
                       {
    return false;
  }
Get()
template<typename T >
static T testing::internal::BuiltInDefaultValue< T >::Get () [inline], [static]
Definition at line 116 of file gmock-actions.h.
References testing::internal::BuiltInDefaultValueGetter< T, kDefaultConstructible >::Get().
Referenced by testing::internal::BuiltInDefaultValue< const T >::Get(), testing::DefaultValue< T >::Get(), and testing::DefaultValue< T & >::Get().
                 {
    return BuiltInDefaultValueGetter<T, false>::Get();
  }
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-actions.h