franka_hw::FrankaModelHandle Class Reference
#include <franka_model_interface.h>
Public Member Functions
FrankaModelHandle ()=delete
FrankaModelHandle (const std::string &name, franka::Model &model, franka::RobotState &robot_state)
std::string getName () const noexcept
std::array< double, 49 > getMass () const
std::array< double, 49 > getMass (const std::array< double, 7 > &q, const std::array< double, 9 > &total_inertia, double total_mass, const std::array< double, 3 > &F_x_Ctotal) const
std::array< double, 7 > getCoriolis () const
std::array< double, 7 > getCoriolis (const std::array< double, 7 > &q, const std::array< double, 7 > &dq, const std::array< double, 9 > &total_inertia, double total_mass, const std::array< double, 3 > &F_x_Ctotal) const
std::array< double, 7 > getGravity (const std::array< double, 3 > &gravity_earth={ {0., 0., -9.81}}) const
std::array< double, 7 > getGravity (const std::array< double, 7 > &q, double total_mass, const std::array< double, 3 > &F_x_Ctotal, const std::array< double, 3 > &gravity_earth={{0., 0., -9.81}}) const
std::array< double, 16 > getPose (const franka::Frame &frame) const
std::array< double, 16 > getPose (const franka::Frame &frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
std::array< double, 42 > getBodyJacobian (const franka::Frame &frame) const
std::array< double, 42 > getBodyJacobian (const franka::Frame &frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
std::array< double, 42 > getZeroJacobian (const franka::Frame &frame) const
std::array< double, 42 > getZeroJacobian (const franka::Frame &frame, const std::array< double, 7 > &q, const std::array< double, 16 > &F_T_EE, const std::array< double, 16 > &EE_T_K) const
Private Attributes
std::string name_
const franka::Model * model_
const franka::RobotState * robot_state_
Detailed Description
Handle to perform calculations using the dynamic model of a robot.
Definition at line 17 of file franka_model_interface.h.
Constructor & Destructor Documentation
FrankaModelHandle() [1/2]
franka_hw::FrankaModelHandle::FrankaModelHandle () [delete]
FrankaModelHandle() [2/2]
franka_hw::FrankaModelHandle::FrankaModelHandle (const std::string & name, franka::Model & model, franka::RobotState & robot_state) [inline]
Creates an instance of a FrankaModelHandle.
Parameters
in name The name of the model handle.
in model A reference to the franka::Model instance wrapped by this handle.
in robot_state A reference to the current robot state.
Definition at line 28 of file franka_model_interface.h.
      : name_(name), model_(&model), robot_state_(&robot_state) {}
Member Function Documentation
getBodyJacobian() [1/2]
std::array<double, 42> franka_hw::FrankaModelHandle::getBodyJacobian (const franka::Frame & frame) const [inline]
Gets the 6x7 Jacobian for the given frame, relative to that frame.
The Jacobian is represented as a 6x7 matrix in column-major format and calculated from the current robot state.
Parameters
in frame The desired frame.
Returns
Vectorized 6x7 Jacobian, column-major.
See also
franka::Model::bodyJacobian
Definition at line 199 of file franka_model_interface.h.
References franka::Model::bodyJacobian(), model_, and robot_state_.
                                                                       {
    return model_->bodyJacobian(frame, *robot_state_);
  }
getBodyJacobian() [2/2]
std::array<double, 42> franka_hw::FrankaModelHandle::getBodyJacobian (const franka::Frame & frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const [inline]
Gets the 6x7 Jacobian for the given frame, relative to that frame.
The Jacobian is represented as a 6x7 matrix in column-major format and calculated from the given robot state.
Parameters
in frame The desired frame.
in q Joint position. Unit: $[rad]$.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 6x7 Jacobian, column-major.
See also
franka::Model::bodyJacobian
Definition at line 218 of file franka_model_interface.h.
References franka::Model::bodyJacobian(), model_, and robot_state_.
            {
    return model_->bodyJacobian(frame, *robot_state_);
  }
getCoriolis() [1/2]
std::array<double, 7> franka_hw::FrankaModelHandle::getCoriolis () const [inline]
Calculates the Coriolis force vector (state-space equation) from the current robot state: $ c= C \times dq$, in $[Nm]$.
Returns
Coriolis force vector.
See also
franka::Model::coriolis
Definition at line 79 of file franka_model_interface.h.
References franka::Model::coriolis(), model_, and robot_state_.
{ return model_->coriolis(*robot_state_); }
getCoriolis() [2/2]
std::array<double, 7> franka_hw::FrankaModelHandle::getCoriolis (const std::array< double, 7 > & q, const std::array< double, 7 > & dq, const std::array< double, 9 > & total_inertia, double total_mass, const std::array< double, 3 > & F_x_Ctotal) const [inline]
Calculates the Coriolis force vector (state-space equation) from the given robot state: $ c= C \times dq$, in $[Nm]$.
Parameters
in q Joint position. Unit: $[rad]$.
in dq Joint velocity. Unit: $[\frac{rad}{s}]$.
in total_inertia Inertia of the attached total load including end effector, relative to center of mass, given as vectorized 3x3 column-major matrix. Unit: $[kg \times m^2]$.
in total_mass Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load including end effector. Unit: $[m]$.
Returns
Coriolis force vector.
See also
franka::Model::coriolis
Definition at line 99 of file franka_model_interface.h.
References franka::Model::coriolis(), and model_.
                                                   { // NOLINT (readability-identifier-naming)
    return model_->coriolis(q, dq, total_inertia, total_mass, F_x_Ctotal);
  }
getGravity() [1/2]
std::array<double, 7> franka_hw::FrankaModelHandle::getGravity (const std::array< double, 3 > & gravity_earth = { {0., 0., -9.81}}) const [inline]
Calculates the gravity vector from the current robot state. Unit: $[Nm]$.
Parameters
in gravity_earth Earth's gravity vector. Unit: $\frac{m}{s^2}$. Default to {0.0, 0.0, -9.81}.
Returns
Gravity vector.
See also
franka::Model::gravity
Definition at line 118 of file franka_model_interface.h.
References franka::Model::gravity(), model_, and robot_state_.
                                                                            {
                                       {0., 0., -9.81}}) const {
    return model_->gravity(*robot_state_, gravity_earth);
  }
getGravity() [2/2]
std::array<double, 7> franka_hw::FrankaModelHandle::getGravity (const std::array< double, 7 > & q, double total_mass, const std::array< double, 3 > & F_x_Ctotal, const std::array< double, 3 > & gravity_earth = {{0., 0., -9.81}}) const [inline]
Calculates the gravity vector from the given robot state. Unit: $[Nm]$.
Parameters
in q Joint position. Unit: $[rad]$.
in total_mass Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load including end effector. Unit: $[m]$.
in gravity_earth Earth's gravity vector. Unit: $\frac{m}{s^2}$. Default to {0.0, 0.0, -9.81}.
Returns
Gravity vector.
See also
franka::Model::gravity
Definition at line 139 of file franka_model_interface.h.
References franka::Model::gravity(), and model_.
                                                 {{0., 0., -9.81}}) const {
    return model_->gravity(q, total_mass, F_x_Ctotal, gravity_earth);
  }
getMass() [1/2]
std::array<double, 49> franka_hw::FrankaModelHandle::getMass () const [inline]
Calculates the 7x7 mass matrix from the current robot state. Unit: $[kg \times m^2]$.
Returns
Vectorized 7x7 mass matrix, column-major.
See also
franka::Model::mass
Definition at line 45 of file franka_model_interface.h.
References franka::Model::mass(), model_, and robot_state_.
{ return model_->mass(*robot_state_); }
getMass() [2/2]
std::array<double, 49> franka_hw::FrankaModelHandle::getMass (const std::array< double, 7 > & q, const std::array< double, 9 > & total_inertia, double total_mass, const std::array< double, 3 > & F_x_Ctotal) const [inline]
Calculates the 7x7 mass matrix from a given robot state. Unit: $[kg \times m^2]$.
Parameters
in q Joint position. Unit: $[rad]$.
in total_inertia Inertia of the attached total load including end effector, relative to center of mass, given as vectorized 3x3 column-major matrix. Unit: $[kg \times m^2]$.
in total_mass Weight of the attached total load including end effector. Unit: $[kg]$.
in F_x_Ctotal Translation from flange to center of mass of the attached total load including end effector. Unit: $[m]$.
Returns
Vectorized 7x7 mass matrix, column-major.
See also
franka::Model::mass
Definition at line 63 of file franka_model_interface.h.
References franka::Model::mass(), and model_.
                                                   { // NOLINT (readability-identifier-naming)
    return model_->mass(q, total_inertia, total_mass, F_x_Ctotal);
  }
getName()
std::string franka_hw::FrankaModelHandle::getName () const [inline], [noexcept]
Gets the name of the model handle.
Returns
Name of the model handle.
Definition at line 36 of file franka_model_interface.h.
References name_.
{ return name_; }
getPose() [1/2]
std::array<double, 16> franka_hw::FrankaModelHandle::getPose (const franka::Frame & frame) const [inline]
Gets the 4x4 pose matrix for the given frame in base frame, calculated from the current robot state.
The pose is represented as a 4x4 matrix in column-major format.
Parameters
in frame The desired frame.
Returns
Vectorized 4x4 pose matrix, column-major.
See also
franka::Model::pose
Definition at line 159 of file franka_model_interface.h.
References model_, franka::Model::pose(), and robot_state_.
                                                               {
    return model_->pose(frame, *robot_state_);
  }
getPose() [2/2]
std::array<double, 16> franka_hw::FrankaModelHandle::getPose (const franka::Frame & frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const [inline]
Gets the 4x4 pose matrix for the given frame in base frame, calculated from the given robot state.
The pose is represented as a 4x4 matrix in column-major format.
Parameters
in frame The desired frame.
in q Joint position. Unit: $[rad]$.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 4x4 pose matrix, column-major.
See also
franka::Model::pose
Definition at line 178 of file franka_model_interface.h.
References model_, and franka::Model::pose().
            {
    return model_->pose(frame, q, F_T_EE, EE_T_K);
  }
getZeroJacobian() [1/2]
std::array<double, 42> franka_hw::FrankaModelHandle::getZeroJacobian (const franka::Frame & frame) const [inline]
Gets the 6x7 Jacobian for the given joint relative to the base frame.
The Jacobian is represented as a 6x7 matrix in column-major format and calculated from the current robot state.
Parameters
in frame The desired frame.
Returns
Vectorized 6x7 Jacobian, column-major.
See also
franka::Model::zeroJacobian
Definition at line 239 of file franka_model_interface.h.
References model_, robot_state_, and franka::Model::zeroJacobian().
                                                                       {
    return model_->zeroJacobian(frame, *robot_state_);
  }
getZeroJacobian() [2/2]
std::array<double, 42> franka_hw::FrankaModelHandle::getZeroJacobian (const franka::Frame & frame, const std::array< double, 7 > & q, const std::array< double, 16 > & F_T_EE, const std::array< double, 16 > & EE_T_K) const [inline]
Gets the 6x7 Jacobian for the given joint relative to the base frame.
The Jacobian is represented as a 6x7 matrix in column-major format and calculated from the given robot state.
Parameters
in frame The desired frame.
in q Joint position. Unit: $[rad]$.
in F_T_EE End effector in flange frame.
in EE_T_K Stiffness frame K in the end effector frame.
Returns
Vectorized 6x7 Jacobian, column-major.
See also
franka::Model::zeroJacobian
Definition at line 258 of file franka_model_interface.h.
References model_, robot_state_, and franka::Model::zeroJacobian().
            {
    return model_->zeroJacobian(frame, *robot_state_);
  }
Member Data Documentation
model_
const franka::Model* franka_hw::FrankaModelHandle::model_ [private]
Definition at line 269 of file franka_model_interface.h.
Referenced by getBodyJacobian(), getCoriolis(), getGravity(), getMass(), getPose(), and getZeroJacobian().
name_
std::string franka_hw::FrankaModelHandle::name_ [private]
Definition at line 268 of file franka_model_interface.h.
Referenced by getName().
robot_state_
const franka::RobotState* franka_hw::FrankaModelHandle::robot_state_ [private]
Definition at line 270 of file franka_model_interface.h.
Referenced by getBodyJacobian(), getCoriolis(), getGravity(), getMass(), getPose(), and getZeroJacobian().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/franka_ros/franka_hw/include/franka_hw/franka_model_interface.h