testing::TestPartResult Class Reference
#include <gtest-test-part.h>
Public Types
enum Type { kSuccess,
kNonFatalFailure,
kFatalFailure
 }
Public Member Functions
TestPartResult (Type a_type, const char *a_file_name, int a_line_number, const char *a_message)
Type type () const
const char * file_name () const
int line_number () const
const char * summary () const
const char * message () const
bool passed () const
bool failed () const
bool nonfatally_failed () const
bool fatally_failed () const
Static Private Member Functions
static std::string ExtractSummary (const char *message)
Private Attributes
Type type_
std::string file_name_
int line_number_
std::string summary_
std::string message_
Detailed Description
Definition at line 47 of file gtest-test-part.h.
Member Enumeration Documentation
Type
enum testing::TestPartResult::Type
Enumerator
kSuccess
kNonFatalFailure
kFatalFailure
Definition at line 51 of file gtest-test-part.h.
            {
    kSuccess, // Succeeded.
    kNonFatalFailure, // Failed but the test can continue.
    kFatalFailure // Failed and the test should be terminated.
  };
Constructor & Destructor Documentation
TestPartResult()
testing::TestPartResult::TestPartResult (Type a_type, const char * a_file_name, int a_line_number, const char * a_message) [inline]
Definition at line 60 of file gtest-test-part.h.
      : type_(a_type),
        file_name_(a_file_name == NULL ? "" : a_file_name),
        line_number_(a_line_number),
        summary_(ExtractSummary(a_message)),
        message_(a_message) {
  }
Member Function Documentation
ExtractSummary()
std::string testing::TestPartResult::ExtractSummary (const char * message) [static], [private]
Definition at line 51 of file gtest-test-part.cc.
References testing::internal::kStackTraceMarker, and message().
                                                            {
  const char* const stack_trace = strstr(message,
      internal::kStackTraceMarker);
  return stack_trace == NULL ? message :
      std::string(message, stack_trace);
}
failed()
bool testing::TestPartResult::failed () const [inline]
Definition at line 94 of file gtest-test-part.h.
Referenced by testing::TestResult::Failed(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
{ return type_ != kSuccess; }
fatally_failed()
bool testing::TestPartResult::fatally_failed () const [inline]
Definition at line 100 of file gtest-test-part.h.
Referenced by testing::internal::HasNewFatalFailureHelper::ReportTestPartResult(), and testing::TestPartFatallyFailed().
{ return type_ == kFatalFailure; }
file_name()
const char* testing::TestPartResult::file_name () const [inline]
Definition at line 76 of file gtest-test-part.h.
Referenced by testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PrintTestPartResultToString(), and testing::internal::TestResultAccessor::test_part_results().
                                {
    return file_name_.empty() ? NULL : file_name_.c_str();
  }
line_number()
int testing::TestPartResult::line_number () const [inline]
Definition at line 82 of file gtest-test-part.h.
Referenced by testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PrintTestPartResultToString(), and testing::internal::TestResultAccessor::test_part_results().
{ return line_number_; }
message()
const char* testing::TestPartResult::message () const [inline]
Definition at line 88 of file gtest-test-part.h.
Referenced by ExtractSummary(), testing::internal::HasOneFailure(), testing::operator<<(), testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo(), testing::internal::PrintTestPartResultToString(), and testing::internal::TestResultAccessor::test_part_results().
{ return message_.c_str(); }
nonfatally_failed()
bool testing::TestPartResult::nonfatally_failed () const [inline]
Definition at line 97 of file gtest-test-part.h.
Referenced by testing::TestPartNonfatallyFailed().
{ return type_ == kNonFatalFailure; }
passed()
bool testing::TestPartResult::passed () const [inline]
Definition at line 91 of file gtest-test-part.h.
{ return type_ == kSuccess; }
summary()
const char* testing::TestPartResult::summary () const [inline]
Definition at line 85 of file gtest-test-part.h.
Referenced by testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
{ return summary_.c_str(); }
type()
Type testing::TestPartResult::type () const [inline]
Definition at line 72 of file gtest-test-part.h.
Referenced by testing::internal::HasOneFailure(), testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult(), testing::operator<<(), and testing::internal::PrintTestPartResultToString().
{ return type_; }
Member Data Documentation
file_name_
std::string testing::TestPartResult::file_name_ [private]
Definition at line 111 of file gtest-test-part.h.
line_number_
int testing::TestPartResult::line_number_ [private]
Definition at line 114 of file gtest-test-part.h.
message_
std::string testing::TestPartResult::message_ [private]
Definition at line 116 of file gtest-test-part.h.
summary_
std::string testing::TestPartResult::summary_ [private]
Definition at line 115 of file gtest-test-part.h.
type_
Type testing::TestPartResult::type_ [private]
Definition at line 103 of file gtest-test-part.h.
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/include/gtest/gtest-test-part.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/src/gtest-test-part.cc