Widget Class Reference
#include <widget.h>
Public Member Functions
Widget (int number, const std::string &name)
~Widget ()
float GetFloatValue () const
int GetIntValue () const
std::string GetStringValue () const
void GetCharPtrValue (char *buffer, size_t max_size) const
Private Attributes
float number_
std::string name_
Detailed Description
Definition at line 42 of file widget.h.
Constructor & Destructor Documentation
Widget()
Widget::Widget (int number, const std::string & name)
Definition at line 40 of file widget.cc.
    : number_(number),
      name_(name) {}
 Widget()
Widget::~Widget ()
Definition at line 44 of file widget.cc.
{}
Member Function Documentation
GetCharPtrValue()
void Widget::GetCharPtrValue (char * buffer, size_t max_size) const
Definition at line 58 of file widget.cc.
References name_.
Referenced by TEST().
                                                                {
  // Copy the char* representation of name_ into buffer, up to max_size.
  strncpy(buffer, name_.c_str(), max_size-1);
  buffer[max_size-1] = '\0';
  return;
}
GetFloatValue()
float Widget::GetFloatValue () const
Definition at line 46 of file widget.cc.
References number_.
Referenced by TEST().
                                  {
  return number_;
}
GetIntValue()
int Widget::GetIntValue () const
Definition at line 50 of file widget.cc.
References number_.
Referenced by TEST().
                              {
  return static_cast<int>(number_);
}
GetStringValue()
std::string Widget::GetStringValue () const
Definition at line 54 of file widget.cc.
References name_.
Referenced by TEST().
                                       {
  return name_;
}
Member Data Documentation
name_
std::string Widget::name_ [private]
Definition at line 58 of file widget.h.
Referenced by GetCharPtrValue(), and GetStringValue().
number_
float Widget::number_ [private]
Definition at line 57 of file widget.h.
Referenced by GetFloatValue(), and GetIntValue().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/xcode/Samples/FrameworkSample/widget.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/xcode/Samples/FrameworkSample/widget.cc