franka::Gripper Class Reference
#include <gripper.h>
Public Types
using ServerVersion = uint16_t
Public Member Functions
Gripper (const std::string &franka_address)
Gripper (Gripper &&gripper) noexcept
Gripper & operator= (Gripper &&gripper) noexcept
~Gripper () noexcept
bool homing () const
bool grasp (double width, double speed, double force, double epsilon_inner=0.005, double epsilon_outer=0.005) const
bool move (double width, double speed) const
bool stop () const
GripperState readOnce () const
ServerVersion serverVersion () const noexcept
Private Attributes
std::unique_ptr< Network > network_
uint16_t ri_version_
Detailed Description
Maintains a network connection to the gripper, provides the current gripper state, and allows the execution of commands.
Note
The members of this class are threadsafe.
Definition at line 27 of file gripper.h.
Member Typedef Documentation
ServerVersion
using franka::Gripper::ServerVersion = uint16_t
Version of the gripper server.
Definition at line 32 of file gripper.h.
Constructor & Destructor Documentation
Gripper() [1/2]
franka::Gripper::Gripper (const std::string & franka_address) [explicit]
Establishes a connection with a gripper connected to a robot.
Parameters
in franka_address IP/hostname of the robot the gripper is connected to.
Exceptions
NetworkException if the connection is unsuccessful.
IncompatibleVersionException if this version of libfranka is not supported.
Definition at line 48 of file gripper.cpp.
References research_interface::gripper::kCommandPort, network_, operator=(), ri_version_, and ~Gripper().
    : network_{
          std::make_unique<Network>(franka_address,
      research_interface::gripper::kCommandPort)} {
  connect<research_interface::gripper::Connect, research_interface::gripper::kVersion>(
      *network_, &ri_version_);
}
Gripper() [2/2]
franka::Gripper::Gripper (Gripper && gripper) [default], [noexcept]
Move-constructs a new Gripper instance.
Parameters
in gripper Other Gripper instance.
 Gripper()
franka::Gripper::~Gripper () [default], [noexcept]
Closes the connection.
Referenced by Gripper().
Member Function Documentation
grasp()
bool franka::Gripper::grasp (double width, double speed, double force, double epsilon_inner = 0.005, double epsilon_outer = 0.005) const
Grasps an object.
An object is considered grasped if the distance $d$ between the gripper fingers satisfies $(\text{width} - \text{epsilon_inner}) < d < (\text{width} + \text{epsilon_outer})$.
Parameters
in width Size of the object to grasp. [m]
in speed Closing speed. [m/s]
in force Grasping force. [N]
in epsilon_inner Maximum tolerated deviation when the actual grasped width is smaller than the commanded grasp width.
in epsilon_outer Maximum tolerated deviation when the actual grasped width is larger than the commanded grasp width.
Returns
True if an object has been grasped, false otherwise.
Exceptions
CommandException if an error occurred.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 67 of file gripper.cpp.
References network_, and battery_monitor_node::speed.
Referenced by franka_gripper::grasp(), franka_gripper::gripperCommandExecuteCallback(), and main().
                                                {
  research_interface::gripper::Grasp::GraspEpsilon epsilon(
      epsilon_inner, epsilon_outer);
  return executeCommand<research_interface::gripper::Grasp>(*network_, width, epsilon,
      speed,
                                                            force);
}
homing()
bool franka::Gripper::homing () const
Performs homing of the gripper.
After changing the gripper fingers, a homing needs to be done. This is needed to estimate the maximum grasping width.
Returns
True if command was successful, false otherwise.
Exceptions
CommandException if an error occurred.
NetworkException if the connection is lost, e.g. after a timeout.
See also
GripperState for the maximum grasping width.
Definition at line 63 of file gripper.cpp.
Referenced by franka_gripper::homing(), and main().
                           {
  return executeCommand<research_interface::gripper::Homing>(*network_);
}
move()
bool franka::Gripper::move (double width, double speed) const
Moves the gripper fingers to a specified width.
Parameters
in width Intended opening width. [m]
in speed Closing speed. [m/s]
Returns
True if command was successful, false otherwise.
Exceptions
CommandException if an error occurred.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 77 of file gripper.cpp.
References network_, and battery_monitor_node::speed.
Referenced by franka_gripper::gripperCommandExecuteCallback(), and franka_gripper::move().
                                                   {
  return executeCommand<research_interface::gripper::Move>(*network_, width,
      speed);
}
operator=()
Gripper & franka::Gripper::operator= (Gripper && gripper) [default], [noexcept]
Move-assigns this Gripper from another Gripper instance.
Parameters
in gripper Other Gripper instance.
Returns
Model instance.
Referenced by Gripper().
readOnce()
GripperState franka::Gripper::readOnce () const
Waits for a gripper state update and returns it.
Returns
Current gripper state.
Exceptions
NetworkException if the connection is lost, e.g. after a timeout.
InvalidOperationException if another readOnce is already running.
Definition at line 85 of file gripper.cpp.
References franka::anonymous_namespace{gripper.cpp}::convertGripperState(), and network_.
Referenced by franka_gripper::gripperCommandExecuteCallback(), main(), and franka_gripper::updateGripperState().
                                     {
  research_interface::gripper::GripperState gripper_state;
  // Delete old data from the UDP buffer.
  while (network_->udpReceive<decltype(gripper_state)>(&gripper_state)) {
  }
  gripper_state = network_->udpBlockingReceive<decltype(gripper_state)>();
  return convertGripperState(gripper_state);
}
serverVersion()
Gripper::ServerVersion franka::Gripper::serverVersion () const [noexcept]
Returns the software version reported by the connected server.
Returns
Software version of the connected server.
Definition at line 59 of file gripper.cpp.
References ri_version_.
                                                           {
  return ri_version_;
}
stop()
bool franka::Gripper::stop () const
Stops a currently running gripper move or grasp.
Returns
True if command was successful, false otherwise.
Exceptions
CommandException if an error occurred.
NetworkException if the connection is lost, e.g. after a timeout.
Definition at line 81 of file gripper.cpp.
Referenced by main(), and franka_gripper::stop().
                         {
  return executeCommand<research_interface::gripper::Stop>(*network_);
}
Member Data Documentation
network_
std::unique_ptr<Network> franka::Gripper::network_ [private]
Definition at line 151 of file gripper.h.
Referenced by grasp(), Gripper(), move(), and readOnce().
ri_version_
uint16_t franka::Gripper::ri_version_ [private]
Definition at line 153 of file gripper.h.
Referenced by Gripper(), and serverVersion().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/include/franka/gripper.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/gripper.cpp