testing::internal::MatchMatrix Class Reference
#include <gmock-matchers.h>
Public Member Functions
MatchMatrix (size_t num_elements, size_t num_matchers)
size_t LhsSize () const
size_t RhsSize () const
bool HasEdge (size_t ilhs, size_t irhs) const
void SetEdge (size_t ilhs, size_t irhs, bool b)
bool NextGraph ()
void Randomize ()
string DebugString () const
Private Member Functions
size_t SpaceIndex (size_t ilhs, size_t irhs) const
Private Attributes
size_t num_elements_
size_t num_matchers_
::std::vector< char > matched_
Detailed Description
Definition at line 3257 of file gmock-matchers.h.
Constructor & Destructor Documentation
MatchMatrix()
testing::internal::MatchMatrix::MatchMatrix (size_t num_elements, size_t num_matchers) [inline]
Definition at line 3259 of file gmock-matchers.h.
      : num_elements_(num_elements),
        num_matchers_(num_matchers),
        matched_(num_elements_* num_matchers_, 0) {
  }
Member Function Documentation
DebugString()
string testing::internal::MatchMatrix::DebugString () const
Definition at line 382 of file gmock-matchers.cc.
                                      {
  ::std::stringstream ss;
  const char *sep = "";
  for (size_t i = 0; i < LhsSize(); ++i) {
    ss << sep;
    for (size_t j = 0; j < RhsSize(); ++j) {
      ss << HasEdge(i, j);
    }
    sep = ";";
  }
  return ss.str();
}
HasEdge()
bool testing::internal::MatchMatrix::HasEdge (size_t ilhs, size_t irhs) const [inline]
Definition at line 3267 of file gmock-matchers.h.
Referenced by testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
                                               {
    return matched_[SpaceIndex(ilhs, irhs)] == 1;
  }
LhsSize()
size_t testing::internal::MatchMatrix::LhsSize () const [inline]
Definition at line 3265 of file gmock-matchers.h.
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
{ return num_elements_; }
NextGraph()
bool testing::internal::MatchMatrix::NextGraph ()
Definition at line 359 of file gmock-matchers.cc.
                            {
  for (size_t ilhs = 0; ilhs < LhsSize(); ++ilhs) {
    for (size_t irhs = 0; irhs < RhsSize(); ++irhs) {
      char& b = matched_[SpaceIndex(ilhs, irhs)];
      if (!b) {
        b = 1;
        return true;
      }
      b = 0;
    }
  }
  return false;
}
Randomize()
void testing::internal::MatchMatrix::Randomize ()
Definition at line 373 of file gmock-matchers.cc.
                            {
  for (size_t ilhs = 0; ilhs < LhsSize(); ++ilhs) {
    for (size_t irhs = 0; irhs < RhsSize(); ++irhs) {
      char& b = matched_[SpaceIndex(ilhs, irhs)];
      b = static_cast<char>(rand() & 1); // NOLINT
    }
  }
}
RhsSize()
size_t testing::internal::MatchMatrix::RhsSize () const [inline]
Definition at line 3266 of file gmock-matchers.h.
Referenced by testing::internal::FindPairing(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
{ return num_matchers_; }
SetEdge()
void testing::internal::MatchMatrix::SetEdge (size_t ilhs, size_t irhs, bool b) [inline]
Definition at line 3270 of file gmock-matchers.h.
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::AnalyzeElements().
                                                 {
    matched_[SpaceIndex(ilhs, irhs)] = b ? 1 : 0;
  }
SpaceIndex()
size_t testing::internal::MatchMatrix::SpaceIndex (size_t ilhs, size_t irhs) const [inline], [private]
Definition at line 3284 of file gmock-matchers.h.
                                                    {
    return ilhs * num_matchers_ + irhs;
  }
Member Data Documentation
matched_
::std::vector<char> testing::internal::MatchMatrix::matched_ [private]
Definition at line 3294 of file gmock-matchers.h.
num_elements_
size_t testing::internal::MatchMatrix::num_elements_ [private]
Definition at line 3288 of file gmock-matchers.h.
num_matchers_
size_t testing::internal::MatchMatrix::num_matchers_ [private]
Definition at line 3289 of file gmock-matchers.h.
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-matchers.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/src/gmock-matchers.cc