testing::TestResult Class Reference
#include <gtest.h>
Public Member Functions
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
Private Member Functions
const std::vector< TestPartResult > & test_part_results () const
const std::vector< TestProperty > & test_properties () const
void set_elapsed_time (TimeInMillis elapsed)
void RecordProperty (const std::string &xml_element, const TestProperty &test_property)
void AddTestPartResult (const TestPartResult &test_part_result)
int death_test_count () const
int increment_death_test_count ()
void ClearTestPartResults ()
void Clear ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult)
Static Private Member Functions
static bool ValidateTestProperty (const std::string &xml_element, const TestProperty &test_property)
Private Attributes
internal::Mutex test_properites_mutex_
std::vector< TestPartResult > test_part_results_
std::vector< TestProperty > test_properties_
int death_test_count_
TimeInMillis elapsed_time_
Friends
class TestInfo
class TestCase
class UnitTest
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
Detailed Description
Definition at line 523 of file gtest.h.
Constructor & Destructor Documentation
TestResult()
testing::TestResult::TestResult ()
Definition at line 2017 of file gtest.cc.
    : death_test_count_(0),
      elapsed_time_(0) {
}
 TestResult()
testing::TestResult::~TestResult ()
Definition at line 2023 of file gtest.cc.
                        {
}
Member Function Documentation
AddTestPartResult()
void testing::TestResult::AddTestPartResult (const TestPartResult & test_part_result) [private]
Definition at line 2050 of file gtest.cc.
References test_part_results_.
Referenced by testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult().
                                                                         {
  test_part_results_.push_back(test_part_result);
}
Clear()
void testing::TestResult::Clear () [private]
Definition at line 2162 of file gtest.cc.
References death_test_count_, elapsed_time_, test_part_results_, and test_properties_.
Referenced by testing::TestCase::ClearResult(), and testing::TestInfo::ClearTestResult().
                       {
  test_part_results_.clear();
  test_properties_.clear();
  death_test_count_ = 0;
  elapsed_time_ = 0;
}
ClearTestPartResults()
void testing::TestResult::ClearTestPartResults () [private]
Definition at line 2045 of file gtest.cc.
References test_part_results_.
Referenced by testing::internal::TestResultAccessor::ClearTestPartResults().
                                      {
  test_part_results_.clear();
}
death_test_count()
int testing::TestResult::death_test_count () const [inline], [private]
Definition at line 605 of file gtest.h.
{ return death_test_count_; }
elapsed_time()
TimeInMillis testing::TestResult::elapsed_time () const [inline]
Definition at line 551 of file gtest.h.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
{ return elapsed_time_; }
Failed()
bool testing::TestResult::Failed () const
Definition at line 2170 of file gtest.cc.
References testing::TestPartResult::failed(), GetTestPartResult(), and total_part_count().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::TestCase::TestFailed().
                              {
  for (int i = 0; i < total_part_count(); ++i) {
    if (GetTestPartResult(i).failed())
      return true;
  }
  return false;
}
GetTestPartResult()
const TestPartResult & testing::TestResult::GetTestPartResult (int i) const
Definition at line 2029 of file gtest.cc.
References testing::internal::posix::Abort(), test_part_results_, and total_part_count().
Referenced by Failed(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
                                                               {
  if (i < 0 || i >= total_part_count())
    internal::posix::Abort();
  return test_part_results_.at(i);
}
GetTestProperty()
const TestProperty & testing::TestResult::GetTestProperty (int i) const
Definition at line 2038 of file gtest.cc.
References testing::internal::posix::Abort(), test_properties_, and test_property_count().
Referenced by testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
                                                           {
  if (i < 0 || i >= test_property_count())
    internal::posix::Abort();
  return test_properties_.at(i);
}
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestResult::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestResult) [private]
HasFatalFailure()
bool testing::TestResult::HasFatalFailure () const
Definition at line 2184 of file gtest.cc.
References testing::internal::CountIf(), test_part_results_, and testing::TestPartFatallyFailed().
Referenced by testing::Test::HasFatalFailure().
                                       {
  return CountIf(test_part_results_,
      TestPartFatallyFailed) > 0;
}
HasNonfatalFailure()
bool testing::TestResult::HasNonfatalFailure () const
Definition at line 2194 of file gtest.cc.
References testing::internal::CountIf(), test_part_results_, and testing::TestPartNonfatallyFailed().
                                          {
  return CountIf(test_part_results_,
      TestPartNonfatallyFailed) > 0;
}
increment_death_test_count()
int testing::TestResult::increment_death_test_count () [inline], [private]
Definition at line 608 of file gtest.h.
{ return ++death_test_count_; }
Passed()
bool testing::TestResult::Passed () const [inline]
Definition at line 539 of file gtest.h.
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::PrintFailedTests(), and testing::TestCase::TestPassed().
{ return !Failed(); }
RecordProperty()
void testing::TestResult::RecordProperty (const std::string & xml_element, const TestProperty & test_property) [private]
Definition at line 2057 of file gtest.cc.
References testing::TestProperty::key(), test_properites_mutex_, test_properties_, ValidateTestProperty(), and testing::TestProperty::value().
Referenced by testing::internal::UnitTestImpl::RecordProperty(), and testing::internal::TestResultAccessor::RecordProperty().
                                                                   {
  if (!ValidateTestProperty(xml_element, test_property)) {
    return;
  }
  internal::MutexLock lock(&test_properites_mutex_);
  const std::vector<TestProperty>::iterator property_with_matching_key =
      std::find_if(test_properties_.begin(), test_properties_.end(),
                   internal::TestPropertyKeyIs(test_property.key()));
  if (property_with_matching_key == test_properties_.end()) {
    test_properties_.push_back(test_property);
    return;
  }
  property_with_matching_key->SetValue(test_property.value());
}
set_elapsed_time()
void testing::TestResult::set_elapsed_time (TimeInMillis elapsed) [inline], [private]
Definition at line 584 of file gtest.h.
Referenced by testing::TestInfo::Run().
{ elapsed_time_ = elapsed; }
test_part_results()
const std::vector<TestPartResult>& testing::TestResult::test_part_results () const [inline], [private]
Definition at line 574 of file gtest.h.
Referenced by testing::internal::TestResultAccessor::test_part_results().
                                                             {
    return test_part_results_;
  }
test_properties()
const std::vector<TestProperty>& testing::TestResult::test_properties () const [inline], [private]
Definition at line 579 of file gtest.h.
                                                         {
    return test_properties_;
  }
test_property_count()
int testing::TestResult::test_property_count () const
Definition at line 2205 of file gtest.cc.
References test_properties_.
Referenced by GetTestProperty(), and testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
                                          {
  return static_cast<int>(test_properties_.size());
}
total_part_count()
int testing::TestResult::total_part_count () const
Definition at line 2200 of file gtest.cc.
References test_part_results_.
Referenced by Failed(), GetTestPartResult(), and testing::internal::XmlUnitTestResultPrinter::OutputXmlTestInfo().
                                       {
  return static_cast<int>(test_part_results_.size());
}
ValidateTestProperty()
bool testing::TestResult::ValidateTestProperty (const std::string & xml_element, const TestProperty & test_property) [static], [private]
Definition at line 2155 of file gtest.cc.
References testing::GetReservedAttributesForElement(), testing::TestProperty::key(), and testing::ValidateTestPropertyName().
Referenced by RecordProperty().
                                                                         {
  return ValidateTestPropertyName(test_property.key(),
                                  GetReservedAttributesForElement(
      xml_element));
}
Friends And Related Function Documentation
internal::DefaultGlobalTestPartResultReporter
friend class internal::DefaultGlobalTestPartResultReporter [friend]
Definition at line 567 of file gtest.h.
internal::ExecDeathTest
friend class internal::ExecDeathTest [friend]
Definition at line 568 of file gtest.h.
internal::TestResultAccessor
friend class internal::TestResultAccessor [friend]
Definition at line 569 of file gtest.h.
internal::UnitTestImpl
friend class internal::UnitTestImpl [friend]
Definition at line 570 of file gtest.h.
internal::WindowsDeathTest
friend class internal::WindowsDeathTest [friend]
Definition at line 571 of file gtest.h.
TestCase
friend class TestCase [friend]
Definition at line 565 of file gtest.h.
TestInfo
friend class TestInfo [friend]
Definition at line 564 of file gtest.h.
UnitTest
friend class UnitTest [friend]
Definition at line 566 of file gtest.h.
Member Data Documentation
death_test_count_
int testing::TestResult::death_test_count_ [private]
Definition at line 625 of file gtest.h.
Referenced by Clear().
elapsed_time_
TimeInMillis testing::TestResult::elapsed_time_ [private]
Definition at line 627 of file gtest.h.
Referenced by Clear().
test_part_results_
std::vector<TestPartResult> testing::TestResult::test_part_results_ [private]
Definition at line 621 of file gtest.h.
Referenced by AddTestPartResult(), Clear(), ClearTestPartResults(), GetTestPartResult(), HasFatalFailure(), HasNonfatalFailure(), and total_part_count().
test_properites_mutex_
internal::Mutex testing::TestResult::test_properites_mutex_ [private]
Definition at line 618 of file gtest.h.
Referenced by RecordProperty().
test_properties_
std::vector<TestProperty> testing::TestResult::test_properties_ [private]
Definition at line 623 of file gtest.h.
Referenced by Clear(), GetTestProperty(), RecordProperty(), and test_property_count().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/include/gtest/gtest.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/src/gtest.cc