franka::ControlLoop< T > Class Template Reference
#include <control_loop.h>
Public Types
using ControlCallback = std::function< Torques(const RobotState &, franka::Duration)>
using MotionGeneratorCallback = std::function< T(const RobotState &, franka::Duration)>
Public Member Functions
ControlLoop (RobotControl &robot, ControlCallback control_callback, MotionGeneratorCallback motion_callback, bool limit_rate, double cutoff_frequency)
ControlLoop (RobotControl &robot, ControllerMode controller_mode, MotionGeneratorCallback motion_callback, bool limit_rate, double cutoff_frequency)
void operator() ()
Static Public Attributes
static constexpr research_interface::robot::Move::Deviation kDefaultDeviation
Protected Member Functions
ControlLoop (RobotControl &robot, MotionGeneratorCallback motion_callback, ControlCallback control_callback, bool limit_rate, double cutoff_frequency)
bool spinControl (const RobotState &robot_state, franka::Duration time_step, research_interface::robot::ControllerCommand *command)
bool spinMotion (const RobotState &robot_state, franka::Duration time_step, research_interface::robot::MotionGeneratorCommand *command)
Private Member Functions
void convertMotion (const T &motion, const RobotState &robot_state, research_interface::robot::MotionGeneratorCommand *command)
template<>
void convertMotion (const JointPositions &motion, const RobotState &robot_state, research_interface::robot::MotionGeneratorCommand *command)
template<>
void convertMotion (const JointVelocities &motion, const RobotState &robot_state, research_interface::robot::MotionGeneratorCommand *command)
template<>
void convertMotion (const CartesianPose &motion, const RobotState &robot_state, research_interface::robot::MotionGeneratorCommand *command)
template<>
void convertMotion (const CartesianVelocities &motion, const RobotState &robot_state, research_interface::robot::MotionGeneratorCommand *command)
Private Attributes
RobotControl & robot_
const MotionGeneratorCallback motion_callback_
const ControlCallback control_callback_
const bool limit_rate_
const double cutoff_frequency_
uint32_t motion_id_ = 0
Detailed Description
template<typename T>
class franka::ControlLoop< T >
Definition at line 18 of file control_loop.h.
Member Typedef Documentation
ControlCallback
template<typename T>
using franka::ControlLoop< T >::ControlCallback = std::function<Torques(const RobotState&, franka::Duration)>
Definition at line 23 of file control_loop.h.
MotionGeneratorCallback
template<typename T>
using franka::ControlLoop< T >::MotionGeneratorCallback = std::function<T(const RobotState&, franka::Duration)>
Definition at line 24 of file control_loop.h.
Constructor & Destructor Documentation
ControlLoop() [1/3]
template<typename T >
franka::ControlLoop< T >::ControlLoop (RobotControl & robot, ControlCallback control_callback, MotionGeneratorCallback motion_callback, bool limit_rate, double cutoff_frequency)
Definition at line 80 of file control_loop.cpp.
References franka::ControlLoop< T >::control_callback_, franka::ControlLoop< T >::kDefaultDeviation, research_interface::robot::Move::kExternalController, franka::ControlLoop< T >::motion_callback_, franka::ControlLoop< T >::motion_id_, and franka::RobotControl::startMotion().
    : ControlLoop(robot,
                  std::move(motion_callback),
                  std::move(control_callback),
                  limit_rate,
                  cutoff_frequency) {
  if (!control_callback_) {
    throw std::invalid_argument("libfranka: Invalid control callback given.");
  }
  if (!motion_callback_) {
    throw std::invalid_argument("libfranka: Invalid motion callback given.");
  }
  motion_id_ = robot.startMotion(
      research_interface::robot::Move::ControllerMode::kExternalController
      ,
      MotionGeneratorTraits<T>::kMotionGeneratorMode, kDefaultDeviation,
      kDefaultDeviation);
}
ControlLoop() [2/3]
template<typename T >
franka::ControlLoop< T >::ControlLoop (RobotControl & robot, ControllerMode controller_mode, MotionGeneratorCallback motion_callback, bool limit_rate, double cutoff_frequency)
Definition at line 103 of file control_loop.cpp.
References franka::kCartesianImpedance, franka::ControlLoop< T >::kDefaultDeviation, franka::kJointImpedance, franka::ControlLoop< T >::motion_callback_, and franka::ControlLoop< T >::motion_id_.
    : ControlLoop(robot, std::move(motion_callback), {}, limit_rate, cutoff_frequency)
      {
  if (!motion_callback_) {
    throw std::invalid_argument("libfranka: Invalid motion callback given.");
  }
  research_interface::robot::Move::ControllerMode mode;
  switch (controller_mode) {
    case ControllerMode::kJointImpedance:
      mode = decltype(mode)::kJointImpedance;
      break;
    case ControllerMode::kCartesianImpedance:
      mode = decltype(mode)::kCartesianImpedance;
      break;
    default:
      throw std::invalid_argument("libfranka: Invalid controller mode given.");
  }
  motion_id_ = robot.startMotion(mode, MotionGeneratorTraits<T>::kMotionGeneratorMode,
                                 kDefaultDeviation,
      kDefaultDeviation);
}
ControlLoop() [3/3]
template<typename T >
franka::ControlLoop< T >::ControlLoop (RobotControl & robot, MotionGeneratorCallback motion_callback, ControlCallback control_callback, bool limit_rate, double cutoff_frequency) [protected]
Definition at line 59 of file control_loop.cpp.
References franka::hasRealtimeKernel(), franka::kEnforce, franka::RobotControl::realtimeConfig(), franka::ControlLoop< T >::robot_, and franka::setCurrentThreadToHighestSchedulerPriority().
    : robot_(robot),
      motion_callback_(std::move(motion_callback)),
      control_callback_(std::move(control_callback)),
      limit_rate_(limit_rate),
      cutoff_frequency_(cutoff_frequency) {
  bool throw_on_error = robot_.realtimeConfig() ==
      RealtimeConfig::kEnforce;
  std::string error_message;
  if (!setCurrentThreadToHighestSchedulerPriority(&error_message)
       && throw_on_error) {
    throw RealtimeException(error_message);
  }
  if (throw_on_error && !hasRealtimeKernel()) {
    throw RealtimeException("libfranka: Running kernel does not have realtime capabilities.");
  }
}
Member Function Documentation
convertMotion() [1/5]
template<typename T>
void franka::ControlLoop< T >::convertMotion (const T & motion, const RobotState & robot_state, research_interface::robot::MotionGeneratorCommand * command) [private]
Referenced by franka::ControlLoop< T >::spinMotion().
convertMotion() [2/5]
template<>
void franka::ControlLoop< JointPositions >::convertMotion (const JointPositions & motion, const RobotState & robot_state, research_interface::robot::MotionGeneratorCommand * command) [private]
Definition at line 189 of file control_loop.cpp.
References franka::anonymous_namespace{control_loop.cpp}::checkFinite(), franka::ControlLoop< T >::cutoff_frequency_, franka::RobotState::ddq_d, franka::RobotState::dq_d, franka::kDeltaT, franka::kMaxCutoffFrequency, franka::kMaxJointAcceleration, franka::kMaxJointJerk, franka::kMaxJointVelocity, franka::ControlLoop< T >::limit_rate_, franka::limitRate(), franka::lowpassFilter(), franka::JointPositions::q, research_interface::robot::MotionGeneratorCommand::q_c, and franka::RobotState::q_d.
                                                            {
  command->q_c = motion.q;
  if (cutoff_frequency_ < kMaxCutoffFrequency) {
    for (size_t i = 0; i < 7; i++) {
      command->q_c[i] =
          lowpassFilter(kDeltaT, command->q_c[i], robot_state.q_d[i],
      cutoff_frequency_);
    }
  }
  if (limit_rate_) {
    command->q_c = limitRate(kMaxJointVelocity,
      kMaxJointAcceleration, kMaxJointJerk, command->
      q_c,
                             robot_state.q_d, robot_state.dq_d, robot_state.ddq_d);
  }
  checkFinite(command->q_c);
}
convertMotion() [3/5]
template<>
void franka::ControlLoop< JointVelocities >::convertMotion (const JointVelocities & motion, const RobotState & robot_state, research_interface::robot::MotionGeneratorCommand * command) [private]
Definition at line 208 of file control_loop.cpp.
References franka::anonymous_namespace{control_loop.cpp}::checkFinite(), franka::ControlLoop< T >::cutoff_frequency_, franka::RobotState::ddq_d, franka::JointVelocities::dq, research_interface::robot::MotionGeneratorCommand::dq_c, franka::RobotState::dq_d, franka::kDeltaT, franka::kMaxCutoffFrequency, franka::kMaxJointAcceleration, franka::kMaxJointJerk, franka::kMaxJointVelocity, franka::ControlLoop< T >::limit_rate_, franka::limitRate(), and franka::lowpassFilter().
                                                            {
  command->dq_c = motion.dq;
  if (cutoff_frequency_ < kMaxCutoffFrequency) {
    for (size_t i = 0; i < 7; i++) {
      command->dq_c[i] =
          lowpassFilter(kDeltaT, command->dq_c[i], robot_state.dq_d[i],
      cutoff_frequency_);
    }
  }
  if (limit_rate_) {
    command->dq_c = limitRate(kMaxJointVelocity,
      kMaxJointAcceleration, kMaxJointJerk,
                              command->dq_c, robot_state.dq_d, robot_state.ddq_d);
  }
  checkFinite(command->dq_c);
}
convertMotion() [4/5]
template<>
void franka::ControlLoop< CartesianPose >::convertMotion (const CartesianPose & motion, const RobotState & robot_state, research_interface::robot::MotionGeneratorCommand * command) [private]
Definition at line 227 of file control_loop.cpp.
References franka::cartesianLowpassFilter(), franka::anonymous_namespace{control_loop.cpp}::checkElbow(), franka::anonymous_namespace{control_loop.cpp}::checkMatrix(), franka::ControlLoop< T >::cutoff_frequency_, franka::RobotState::ddelbow_c, franka::RobotState::delbow_c, franka::CartesianPose::elbow, research_interface::robot::MotionGeneratorCommand::elbow_c, franka::RobotState::elbow_c, franka::CartesianPose::hasElbow(), franka::kDeltaT, franka::kMaxCutoffFrequency, franka::kMaxElbowAcceleration, franka::kMaxElbowJerk, franka::kMaxElbowVelocity, franka::kMaxRotationalAcceleration, franka::kMaxRotationalJerk, franka::kMaxRotationalVelocity, franka::kMaxTranslationalAcceleration, franka::kMaxTranslationalJerk, franka::kMaxTranslationalVelocity, franka::ControlLoop< T >::limit_rate_, franka::limitRate(), franka::lowpassFilter(), franka::RobotState::O_ddP_EE_c, franka::RobotState::O_dP_EE_c, franka::CartesianPose::O_T_EE, research_interface::robot::MotionGeneratorCommand::O_T_EE_c, franka::RobotState::O_T_EE_c, and research_interface::robot::MotionGeneratorCommand::valid_elbow.
                                                            {
  command->O_T_EE_c = motion.O_T_EE;
  if (cutoff_frequency_ < kMaxCutoffFrequency) {
    command->O_T_EE_c =
        cartesianLowpassFilter(kDeltaT, command->
      O_T_EE_c, robot_state.O_T_EE_c, cutoff_frequency_);
  }
  if (limit_rate_) {
    command->O_T_EE_c = limitRate(
        kMaxTranslationalVelocity,
      kMaxTranslationalAcceleration,
      kMaxTranslationalJerk,
        kMaxRotationalVelocity, kMaxRotationalAcceleration,
       kMaxRotationalJerk, command->O_T_EE_c,
        robot_state.O_T_EE_c, robot_state.O_dP_EE_c, robot_state.O_ddP_EE_c);
  }
  checkMatrix(command->O_T_EE_c);
  if (motion.hasElbow()) {
    command->valid_elbow = true;
    command->elbow_c = motion.elbow;
    if (cutoff_frequency_ < kMaxCutoffFrequency) {
      command->elbow_c[0] =
          lowpassFilter(kDeltaT, command->elbow_c[0], robot_state.elbow_c[0],
      cutoff_frequency_);
    }
    if (limit_rate_) {
      command->elbow_c[0] =
          limitRate(kMaxElbowVelocity,
      kMaxElbowAcceleration, kMaxElbowJerk, command->
      elbow_c[0],
                    robot_state.elbow_c[0], robot_state.delbow_c[0], robot_state.ddelbow_c[0]);
    }
    checkElbow(command->elbow_c);
  } else {
    command->valid_elbow = false;
    command->elbow_c = {};
  }
}
convertMotion() [5/5]
template<>
void franka::ControlLoop< CartesianVelocities >::convertMotion (const CartesianVelocities & motion, const RobotState & robot_state, research_interface::robot::MotionGeneratorCommand * command) [private]
Definition at line 265 of file control_loop.cpp.
References franka::anonymous_namespace{control_loop.cpp}::checkElbow(), franka::anonymous_namespace{control_loop.cpp}::checkFinite(), franka::ControlLoop< T >::cutoff_frequency_, franka::RobotState::ddelbow_c, franka::RobotState::delbow_c, franka::CartesianVelocities::elbow, research_interface::robot::MotionGeneratorCommand::elbow_c, franka::RobotState::elbow_c, franka::CartesianVelocities::hasElbow(), franka::kDeltaT, franka::kMaxCutoffFrequency, franka::kMaxElbowAcceleration, franka::kMaxElbowJerk, franka::kMaxElbowVelocity, franka::kMaxRotationalAcceleration, franka::kMaxRotationalJerk, franka::kMaxRotationalVelocity, franka::kMaxTranslationalAcceleration, franka::kMaxTranslationalJerk, franka::kMaxTranslationalVelocity, franka::ControlLoop< T >::limit_rate_, franka::limitRate(), franka::lowpassFilter(), franka::RobotState::O_ddP_EE_c, franka::CartesianVelocities::O_dP_EE, research_interface::robot::MotionGeneratorCommand::O_dP_EE_c, franka::RobotState::O_dP_EE_c, and research_interface::robot::MotionGeneratorCommand::valid_elbow.
                                                            {
  command->O_dP_EE_c = motion.O_dP_EE;
  if (cutoff_frequency_ < kMaxCutoffFrequency) {
    for (size_t i = 0; i < 6; i++) {
      command->O_dP_EE_c[i] = lowpassFilter(kDeltaT, command->
      O_dP_EE_c[i],
                                            robot_state.O_dP_EE_c[i],
      cutoff_frequency_);
    }
  }
  if (limit_rate_) {
    command->O_dP_EE_c =
        limitRate(kMaxTranslationalVelocity,
      kMaxTranslationalAcceleration,
      kMaxTranslationalJerk,
                  kMaxRotationalVelocity,
      kMaxRotationalAcceleration, kMaxRotationalJerk,
                  command->O_dP_EE_c, robot_state.O_dP_EE_c, robot_state.O_ddP_EE_c);
  }
  checkFinite(command->O_dP_EE_c);
  if (motion.hasElbow()) {
    command->valid_elbow = true;
    command->elbow_c = motion.elbow;
    if (cutoff_frequency_ < kMaxCutoffFrequency) {
      command->elbow_c[0] =
          lowpassFilter(kDeltaT, command->elbow_c[0], robot_state.elbow_c[0],
      cutoff_frequency_);
    }
    if (limit_rate_) {
      command->elbow_c[0] =
          limitRate(kMaxElbowVelocity,
      kMaxElbowAcceleration, kMaxElbowJerk, command->
      elbow_c[0],
                    robot_state.elbow_c[0], robot_state.delbow_c[0], robot_state.ddelbow_c[0]);
    }
    checkElbow(command->elbow_c);
  } else {
    command->valid_elbow = false;
    command->elbow_c = {};
  }
}
operator()()
template<typename T >
void franka::ControlLoop< T >::operator() ()
Definition at line 128 of file control_loop.cpp.
References franka::RobotControl::cancelMotion(), franka::ControlLoop< T >::control_callback_, franka::RobotControl::finishMotion(), franka::ControlLoop< T >::motion_id_, franka::ControlLoop< T >::robot_, franka::ControlLoop< T >::spinControl(), franka::ControlLoop< T >::spinMotion(), franka::RobotControl::throwOnMotionError(), franka::RobotState::time, and franka::RobotControl::update().
                                    {
  RobotState robot_state = robot_.update(nullptr, nullptr);
  robot_.throwOnMotionError(robot_state, motion_id_);
  Duration previous_time = robot_state.time;
  research_interface::robot::MotionGeneratorCommand
      motion_command{};
  if (control_callback_) {
    research_interface::robot::ControllerCommand
      control_command{};
    while (spinMotion(robot_state, robot_state.time - previous_time, &motion_command) &&
           spinControl(robot_state, robot_state.time - previous_time, &control_command)) {
      previous_time = robot_state.time;
      robot_state = robot_.update(&motion_command, &control_command);
      robot_.throwOnMotionError(robot_state, motion_id_);
    }
    robot_.finishMotion(motion_id_, &motion_command, &control_command);
  } else {
    while (spinMotion(robot_state, robot_state.time - previous_time, &motion_command)) {
      previous_time = robot_state.time;
      robot_state = robot_.update(&motion_command, nullptr);
      robot_.throwOnMotionError(robot_state, motion_id_);
    }
    robot_.finishMotion(motion_id_, &motion_command, nullptr);
  }
} catch (...) {
  try {
    robot_.cancelMotion(motion_id_);
  } catch (...) {
  }
  throw;
}
spinControl()
template<typename T >
bool franka::ControlLoop< T >::spinControl (const RobotState & robot_state, franka::Duration time_step, research_interface::robot::ControllerCommand * command) [protected]
Definition at line 161 of file control_loop.cpp.
References franka::anonymous_namespace{control_loop.cpp}::checkFinite(), franka::ControlLoop< T >::control_callback_, franka::ControlLoop< T >::cutoff_frequency_, franka::kDeltaT, franka::kMaxCutoffFrequency, franka::kMaxTorqueRate, franka::ControlLoop< T >::limit_rate_, franka::limitRate(), franka::lowpassFilter(), franka::Finishable::motion_finished, franka::Torques::tau_J, research_interface::robot::ControllerCommand::tau_J_d, and franka::RobotState::tau_J_d.
Referenced by franka::ControlLoop< T >::operator()().
                                                                                    {
  Torques control_output = control_callback_(robot_state, time_step);
  if (cutoff_frequency_ < kMaxCutoffFrequency) {
    for (size_t i = 0; i < 7; i++) {
      control_output.tau_J[i] = lowpassFilter(kDeltaT, control_output.tau_J[i],
                                              robot_state.tau_J_d[i],
      cutoff_frequency_);
    }
  }
  if (limit_rate_) {
    control_output.tau_J = limitRate(kMaxTorqueRate, control_output.tau_J,
      robot_state.tau_J_d);
  }
  command->tau_J_d = control_output.tau_J;
  checkFinite(command->tau_J_d);
  return !control_output.motion_finished;
}
spinMotion()
template<typename T >
bool franka::ControlLoop< T >::spinMotion (const RobotState & robot_state, franka::Duration time_step, research_interface::robot::MotionGeneratorCommand * command) [protected]
Definition at line 180 of file control_loop.cpp.
References franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::motion_callback_.
Referenced by franka::ControlLoop< T >::operator()().
                                                                                        {
  T motion_output = motion_callback_(robot_state, time_step);
  convertMotion(motion_output, robot_state, command);
  return !motion_output.motion_finished;
}
Member Data Documentation
control_callback_
template<typename T>
const ControlCallback franka::ControlLoop< T >::control_callback_ [private]
Definition at line 56 of file control_loop.h.
Referenced by franka::ControlLoop< T >::ControlLoop(), franka::ControlLoop< T >::operator()(), and franka::ControlLoop< T >::spinControl().
cutoff_frequency_
template<typename T>
const double franka::ControlLoop< T >::cutoff_frequency_ [private]
Definition at line 58 of file control_loop.h.
Referenced by franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::spinControl().
kDefaultDeviation
template<typename T>
constexpr research_interface::robot::Move::Deviation franka::ControlLoop< T >::kDefaultDeviation [static]
Initial value:
{10.0, 3.12,
                                                                                2 * M_PI}
Definition at line 20 of file control_loop.h.
Referenced by franka::ControlLoop< T >::ControlLoop().
limit_rate_
template<typename T>
const bool franka::ControlLoop< T >::limit_rate_ [private]
Definition at line 57 of file control_loop.h.
Referenced by franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::spinControl().
motion_callback_
template<typename T>
const MotionGeneratorCallback franka::ControlLoop< T >::motion_callback_ [private]
Definition at line 55 of file control_loop.h.
Referenced by franka::ControlLoop< T >::ControlLoop(), and franka::ControlLoop< T >::spinMotion().
motion_id_
template<typename T>
uint32_t franka::ControlLoop< T >::motion_id_ = 0 [private]
Definition at line 59 of file control_loop.h.
Referenced by franka::ControlLoop< T >::ControlLoop(), and franka::ControlLoop< T >::operator()().
robot_
template<typename T>
RobotControl& franka::ControlLoop< T >::robot_ [private]
Definition at line 54 of file control_loop.h.
Referenced by franka::ControlLoop< T >::ControlLoop(), and franka::ControlLoop< T >::operator()().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/control_loop.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/control_loop.cpp