testing::internal::MatcherBase< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x, ::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
Protected Member Functions
MatcherBase ()
MatcherBase (const MatcherInterface< T > *impl)
virtual ~MatcherBase ()
Private Attributes
::testing::internal::linked_ptr< const MatcherInterface< T > > impl_
Detailed Description
template<typename T>
class testing::internal::MatcherBase< T >
Definition at line 252 of file gmock-matchers.h.
Constructor & Destructor Documentation
MatcherBase() [1/2]
template<typename T>
testing::internal::MatcherBase< T >::MatcherBase () [inline], [protected]
Definition at line 288 of file gmock-matchers.h.
{}
MatcherBase() [2/2]
template<typename T>
testing::internal::MatcherBase< T >::MatcherBase (const MatcherInterface< T > * impl) [inline], [explicit], [protected]
Definition at line 291 of file gmock-matchers.h.
      : impl_(impl) {}
 MatcherBase()
template<typename T>
virtual testing::internal::MatcherBase< T >::~MatcherBase () [inline], [protected], [virtual]
Definition at line 294 of file gmock-matchers.h.
{}
Member Function Documentation
DescribeNegationTo()
template<typename T>
void testing::internal::MatcherBase< T >::DescribeNegationTo (::std::ostream * os) const [inline]
Definition at line 270 of file gmock-matchers.h.
                                                {
    impl_->DescribeNegationTo(os);
  }
DescribeTo()
template<typename T>
void testing::internal::MatcherBase< T >::DescribeTo (::std::ostream * os) const [inline]
Definition at line 267 of file gmock-matchers.h.
Referenced by testing::internal::PredicateFormatterFromMatcher< M >::operator()().
{ impl_->DescribeTo(os); }
ExplainMatchResultTo()
template<typename T>
void testing::internal::MatcherBase< T >::ExplainMatchResultTo (T x, ::std::ostream * os) const [inline]
Definition at line 275 of file gmock-matchers.h.
                                                       {
    StreamMatchResultListener listener(os);
    MatchAndExplain(x, &listener);
  }
GetDescriber()
template<typename T>
const MatcherDescriberInterface* testing::internal::MatcherBase< T >::GetDescriber () const [inline]
Definition at line 283 of file gmock-matchers.h.
                                                        {
    return impl_.get();
  }
MatchAndExplain()
template<typename T>
bool testing::internal::MatcherBase< T >::MatchAndExplain (T x, MatchResultListener * listener) const [inline]
Definition at line 256 of file gmock-matchers.h.
Referenced by testing::internal::MatchPrintAndExplain().
                                                                 {
    return impl_->MatchAndExplain(x, listener);
  }
Matches()
template<typename T>
bool testing::internal::MatcherBase< T >::Matches (T x) const [inline]
Definition at line 261 of file gmock-matchers.h.
Referenced by testing::internal::MatchPrintAndExplain().
                          {
    DummyMatchResultListener dummy;
    return MatchAndExplain(x, &dummy);
  }
Member Data Documentation
impl_
template<typename T>
::testing::internal::linked_ptr<const MatcherInterface<T> > testing::internal::MatcherBase< T >::impl_ [private]
Definition at line 308 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-matchers.h