sm_panda_moveit::CbPandaOpenGripper Class Reference
#include <cb_panda_open_gripper.h>
Public Member Functions
CbPandaOpenGripper ()
virtual void onEntry () override
virtual void onExit () override
Private Attributes
double previousTolerance
Additional Inherited Members
Detailed Description
Definition at line 5 of file cb_panda_open_gripper.h.
Constructor & Destructor Documentation
CbPandaOpenGripper()
sm_panda_moveit::CbPandaOpenGripper::CbPandaOpenGripper () [inline]
Definition at line 11 of file cb_panda_open_gripper.h.
                         : CbMoveJoints({{"panda_finger_joint1", 0.09999}, {"
      panda_finger_joint2", 0.09999}})
    {
        //setGoalTolerance
    }
Member Function Documentation
onEntry()
virtual void sm_panda_moveit::CbPandaOpenGripper::onEntry () [inline], [override], [virtual]
Reimplemented from moveit_z_client::CbMoveJoints.
Definition at line 16 of file cb_panda_open_gripper.h.
References moveit_z_client::CbMoveJoints::movegroupClient_, moveit_z_client::ClMoveGroup::moveGroupClientInterface, moveit_z_client::CbMoveJoints::onEntry(), and smacc::SmaccClientBehavior::requiresClient().
    {
        this->requiresClient(movegroupClient_);
        auto &moveGroupInterface = movegroupClient_->
      moveGroupClientInterface;
        previousTolerance = moveGroupInterface.getGoalJointTolerance();
        moveGroupInterface.setGoalJointTolerance(0.01);
        moveit_z_client::CbMoveJoints::onEntry();
    }
onExit()
virtual void sm_panda_moveit::CbPandaOpenGripper::onExit () [inline], [override], [virtual]
Reimplemented from moveit_z_client::CbMoveJoints.
Definition at line 27 of file cb_panda_open_gripper.h.
References moveit_z_client::CbMoveJoints::movegroupClient_, moveit_z_client::ClMoveGroup::moveGroupClientInterface, and moveit_z_client::CbMoveJoints::onExit().
    {
        auto &moveGroupInterface = movegroupClient_->
      moveGroupClientInterface;
        moveGroupInterface.setGoalJointTolerance(previousTolerance);
        moveit_z_client::CbMoveJoints::onExit();
    }
Member Data Documentation
previousTolerance
double sm_panda_moveit::CbPandaOpenGripper::previousTolerance [private]
Definition at line 8 of file cb_panda_open_gripper.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/sm_panda_moveit/include/sm_panda_moveit/clients/move_group_client/client_behaviors/cb_panda_open_gripper.h