cpp.ast.TypeConverter Class Reference
Public Member Functions
def __init__ (self, namespace_stack)
def ToType (self, tokens)
def DeclarationToParts (self, parts, needs_name_removed)
def ToParameters (self, tokens)
def CreateReturnType (self, return_type_seq)
def GetTemplateIndices (self, names)
Public Attributes
namespace_stack
Private Member Functions
def _GetTemplateEnd (self, tokens, start)
Detailed Description
Definition at line 458 of file ast.py.
Constructor & Destructor Documentation
__init__()
def cpp.ast.TypeConverter.__init__ (self, namespace_stack)
Definition at line 460 of file ast.py.
    def __init__(self, namespace_stack):
        self.namespace_stack = namespace_stack
Member Function Documentation
_GetTemplateEnd()
def cpp.ast.TypeConverter._GetTemplateEnd (self, tokens, start) [private]
Definition at line 463 of file ast.py.
Referenced by cpp.ast.TypeConverter.DeclarationToParts(), and cpp.ast.TypeConverter.ToType().
    def _GetTemplateEnd(self, tokens, start):
        count = 1
        end = start
        while 1:
            token = tokens[end]
            end += 1
            if token.name == '<':
                count += 1
            elif token.name == '>':
                count -= 1
                if count == 0:
                    break
        return tokens[start:end-1], end
CreateReturnType()
def cpp.ast.TypeConverter.CreateReturnType (self, return_type_seq)
Definition at line 652 of file ast.py.
References cpp.ast.TypeConverter.DeclarationToParts().
    def CreateReturnType(self, return_type_seq):
        if not return_type_seq:
            return None
        start = return_type_seq[0].start
        end = return_type_seq[-1].end
        _, name, templated_types, modifiers, default, other_tokens = \
           self.DeclarationToParts(return_type_seq, False)
        names = [n.name for n in other_tokens]
        reference = '&' in names
        pointer = '*' in names
        array = '[' in names
        return Type(start, end, name, templated_types, modifiers,
                    reference, pointer, array)
DeclarationToParts()
def cpp.ast.TypeConverter.DeclarationToParts (self, parts, needs_name_removed)
Definition at line 536 of file ast.py.
References cpp.ast.TypeConverter._GetTemplateEnd(), and cpp.ast.TypeConverter.ToType().
Referenced by cpp.ast.TypeConverter.CreateReturnType(), and cpp.ast.TypeConverter.ToParameters().
    def DeclarationToParts(self, parts, needs_name_removed):
        name = None
        default = []
        if needs_name_removed:
            # Handle default (initial) values properly.
            for i, t in enumerate(parts):
                if t.name == '=':
                    default = parts[i+1:]
                    name = parts[i-1].name
                    if name == ']' and parts[i-2].name == '[':
                        name = parts[i-3].name
                        i -= 1
                    parts = parts[:i-1]
                    break
            else:
                if parts[-1].token_type == tokenize.NAME:
                    name = parts.pop().name
                else:
                    # TODO(nnorwitz): this is a hack that happens for code like
                    # Register(Foo<T>); where it thinks this is a function call
                    # but it's actually a declaration.
                    name = '???'
        modifiers = []
        type_name = []
        other_tokens = []
        templated_types = []
        i = 0
        end = len(parts)
        while i < end:
            p = parts[i]
            if keywords.IsKeyword(p.name):
                modifiers.append(p.name)
            elif p.name == '<':
                templated_tokens, new_end = self._GetTemplateEnd(parts, i+1)
                templated_types = self.ToType(templated_tokens)
                i = new_end - 1
                # Don't add a spurious :: to data members being initialized.
                next_index = i + 1
                if next_index < end and parts[next_index].name == '::':
                    i += 1
            elif p.name in ('[', ']', '='):
                # These are handled elsewhere.
                other_tokens.append(p)
            elif p.name not in ('*', '&', '>'):
                # Ensure that names have a space between them.
                if (type_name and type_name[-1].token_type == tokenize.NAME and
                    p.token_type == tokenize.NAME):
                    type_name.append(tokenize.Token(tokenize.SYNTAX, ' ', 0, 0))
                type_name.append(p)
            else:
                other_tokens.append(p)
            i += 1
        type_name = ''.join([t.name for t in type_name])
        return name, type_name, templated_types, modifiers, default, other_tokens
GetTemplateIndices()
def cpp.ast.TypeConverter.GetTemplateIndices (self, names)
Definition at line 666 of file ast.py.
    def GetTemplateIndices(self, names):
        # names is a list of strings.
        start = names.index('<')
        end = len(names) - 1
        while end > 0:
            if names[end] == '>':
                break
            end -= 1
        return start, end+1
ToParameters()
def cpp.ast.TypeConverter.ToParameters (self, tokens)
Definition at line 591 of file ast.py.
References cpp.ast.TypeConverter.DeclarationToParts().
    def ToParameters(self, tokens):
        if not tokens:
            return []
        result = []
        name = type_name = ''
        type_modifiers = []
        pointer = reference = array = False
        first_token = None
        default = []
        def AddParameter(end):
            if default:
                del default[0] # Remove flag.
            parts = self.DeclarationToParts(type_modifiers, True)
            (name, type_name, templated_types, modifiers,
             unused_default, unused_other_tokens) = parts
            parameter_type = Type(first_token.start, first_token.end,
                                  type_name, templated_types, modifiers,
                                  reference, pointer, array)
            p = Parameter(first_token.start, end, name,
                          parameter_type, default)
            result.append(p)
        template_count = 0
        for s in tokens:
            if not first_token:
                first_token = s
            if s.name == '<':
                template_count += 1
            elif s.name == '>':
                template_count -= 1
            if template_count > 0:
                type_modifiers.append(s)
                continue
            if s.name == ',':
                AddParameter(s.start)
                name = type_name = ''
                type_modifiers = []
                pointer = reference = array = False
                first_token = None
                default = []
            elif s.name == '*':
                pointer = True
            elif s.name == '&':
                reference = True
            elif s.name == '[':
                array = True
            elif s.name == ']':
                pass # Just don't add to type_modifiers.
            elif s.name == '=':
                # Got a default value. Add any value (None) as a flag.
                default.append(None)
            elif default:
                default.append(s)
            else:
                type_modifiers.append(s)
        AddParameter(tokens[-1].end)
        return result
ToType()
def cpp.ast.TypeConverter.ToType (self, tokens)
Convert [Token,...] to [Class(...), ] useful for base classes.
For example, code like class Foo : public Bar<x, y> { ... };
the "Bar<x, y>" portion gets converted to an AST.

Returns:
  [Class(...), ...]
Definition at line 477 of file ast.py.
References cpp.ast.TypeConverter._GetTemplateEnd(), and cpp.ast.TypeConverter.ToType().
Referenced by cpp.ast.TypeConverter.DeclarationToParts(), and cpp.ast.TypeConverter.ToType().
    def ToType(self, tokens):
        """Convert [Token,...] to [Class(...), ] useful for base classes.
        For example, code like class Foo : public Bar<x, y> { ... };
        the "Bar<x, y>" portion gets converted to an AST.
        Returns:
          [Class(...), ...]
        """
        result = []
        name_tokens = []
        reference = pointer = array = False
        def AddType(templated_types):
            # Partition tokens into name and modifier tokens.
            names = []
            modifiers = []
            for t in name_tokens:
                if keywords.IsKeyword(t.name):
                    modifiers.append(t.name)
                else:
                    names.append(t.name)
            name = ''.join(names)
            if name_tokens:
                result.append(Type(name_tokens[0].start, name_tokens[-1].end,
                                   name, templated_types, modifiers,
                                   reference, pointer, array))
            del name_tokens[:]
        i = 0
        end = len(tokens)
        while i < end:
            token = tokens[i]
            if token.name == '<':
                new_tokens, new_end = self._GetTemplateEnd(tokens, i+1)
                AddType(self.ToType(new_tokens))
                # If there is a comma after the template, we need to consume
                # that here otherwise it becomes part of the name.
                i = new_end
                reference = pointer = array = False
            elif token.name == ',':
                AddType([])
                reference = pointer = array = False
            elif token.name == '*':
                pointer = True
            elif token.name == '&':
                reference = True
            elif token.name == '[':
               pointer = True
            elif token.name == ']':
                pass
            else:
                name_tokens.append(token)
            i += 1
        if name_tokens:
            # No '<' in the tokens, just a simple name and no template.
            AddType([])
        return result
Member Data Documentation
namespace_stack
cpp.ast.TypeConverter.namespace_stack
Definition at line 461 of file ast.py.
Referenced by cpp.ast.AstBuilder._CreateVariable(), cpp.ast.AstBuilder._GetClass(), cpp.ast.AstBuilder._GetMethod(), cpp.ast.AstBuilder.Generate(), cpp.ast.AstBuilder.handle_friend(), cpp.ast.AstBuilder.handle_namespace(), and cpp.ast.AstBuilder.handle_typedef().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/scripts/generator/cpp/ast.py