testing::Matcher< internal::string > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
Matcher ()
Matcher (const MatcherInterface< internal::string > *impl)
Matcher (const internal::string &s)
Matcher (const char *s)
Additional Inherited Members
Detailed Description
template<>
class testing::Matcher< internal::string >
Definition at line 356 of file gmock-matchers.h.
Constructor & Destructor Documentation
Matcher() [1/4]
testing::Matcher< internal::string >::Matcher () [inline]
Definition at line 359 of file gmock-matchers.h.
{}
Matcher() [2/4]
testing::Matcher< internal::string >::Matcher (const MatcherInterface< internal::string > * impl) [inline], [explicit]
Definition at line 361 of file gmock-matchers.h.
References GTEST_API_, and service_node_3::s.
      : internal::MatcherBase<internal::string>(impl) {}
Matcher() [3/4]
testing::Matcher< internal::string >::Matcher (const internal::string & s)
Definition at line 59 of file gmock-matchers.cc.
References testing::Eq().
{ *this = Eq(s); }
Matcher() [4/4]
testing::Matcher< internal::string >::Matcher (const char * s)
Definition at line 62 of file gmock-matchers.cc.
References testing::Eq(), testing::Matcher< T >::Matcher(), and service_node_3::s.
                                              {
  *this = Eq(internal::string(s));
}
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/include/gmock/gmock-matchers.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googlemock/src/gmock-matchers.cc