franka::RobotControl Class Reference
#include <robot_control.h>
Public Member Functions
virtual ~RobotControl ()=default
virtual uint32_t startMotion (research_interface::robot::Move::ControllerMode controller_mode, research_interface::robot::Move::MotionGeneratorMode motion_generator_mode, const research_interface::robot::Move::Deviation &maximum_path_deviation, const research_interface::robot::Move::Deviation &maximum_goal_pose_deviation)=0
virtual void finishMotion (uint32_t motion_id, const research_interface::robot::MotionGeneratorCommand *motion_command, const research_interface::robot::ControllerCommand *control_command)=0
virtual void cancelMotion (uint32_t motion_id)=0
virtual RobotState update (const research_interface::robot::MotionGeneratorCommand *motion_command, const research_interface::robot::ControllerCommand *control_command)=0
virtual void throwOnMotionError (const RobotState &robot_state, uint32_t motion_id)=0
virtual RealtimeConfig realtimeConfig () const noexcept=0
Detailed Description
Definition at line 14 of file robot_control.h.
Constructor & Destructor Documentation
 RobotControl()
virtual franka::RobotControl::~RobotControl () [virtual], [default]
Member Function Documentation
cancelMotion()
virtual void franka::RobotControl::cancelMotion (uint32_t motion_id) [pure virtual]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::operator()().
finishMotion()
virtual void franka::RobotControl::finishMotion (uint32_t motion_id, const research_interface::robot::MotionGeneratorCommand * motion_command, const research_interface::robot::ControllerCommand * control_command) [pure virtual]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::operator()().
realtimeConfig()
virtual RealtimeConfig franka::RobotControl::realtimeConfig () const [pure virtual], [noexcept]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::ControlLoop().
startMotion()
virtual uint32_t franka::RobotControl::startMotion (research_interface::robot::Move::ControllerMode controller_mode, research_interface::robot::Move::MotionGeneratorMode motion_generator_mode, const research_interface::robot::Move::Deviation & maximum_path_deviation, const research_interface::robot::Move::Deviation & maximum_goal_pose_deviation) [pure virtual]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::ControlLoop().
throwOnMotionError()
virtual void franka::RobotControl::throwOnMotionError (const RobotState & robot_state, uint32_t motion_id) [pure virtual]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::operator()().
update()
virtual RobotState franka::RobotControl::update (const research_interface::robot::MotionGeneratorCommand * motion_command, const research_interface::robot::ControllerCommand * control_command) [pure virtual]
Implemented in franka::Robot::Impl.
Referenced by franka::ControlLoop< T >::operator()().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/robot_control.h