sm_panda_moveit::ClPerceptionSystem Class Reference
#include <cl_perception_system.h>
Public Member Functions
ClPerceptionSystem ()
void onLinkStatesCallback (const gazebo_msgs::LinkStates &linksmsg)
geometry_msgs::PoseStamped decidePegPose ()
void propagateLinkStatesToTf (const gazebo_msgs::LinkStates &linksmsg, std::string link_name_filter, std::string object_prefix, std::string global_frame, bool indexpostfix)
virtual void update () override
Public Attributes
cl_move_base_z::Pose * peg0
cl_move_base_z::Pose * horizontalPegPlace0
cl_move_base_z::Pose * horizontalPegPlace1
cl_move_base_z::Pose * horizontalPegPlace2
cl_move_base_z::Pose * wallPegPlace0
cl_move_base_z::Pose * wallPegPlace1
cl_move_base_z::Pose * wallPegPlace2
Private Attributes
ros::Subscriber linkStatesSub_
tf::TransformBroadcaster tfBroadcaster_
Additional Inherited Members
Detailed Description
Definition at line 10 of file cl_perception_system.h.
Constructor & Destructor Documentation
ClPerceptionSystem()
sm_panda_moveit::ClPerceptionSystem::ClPerceptionSystem () [inline]
Definition at line 27 of file cl_perception_system.h.
References onLinkStatesCallback().
    {
        ros::NodeHandle nh;
        linkStatesSub_ = nh.subscribe("/gazebo/link_states", 1, &
      ClPerceptionSystem::onLinkStatesCallback, this);
    }
Member Function Documentation
decidePegPose()
geometry_msgs::PoseStamped sm_panda_moveit::ClPerceptionSystem::decidePegPose () [inline]
Definition at line 43 of file cl_perception_system.h.
References cl_move_base_z::Pose::toPoseStampedMsg(), and cl_move_base_z::Pose::waitTransformUpdate().
Referenced by sm_panda_moveit::pick_states::StMovePregraspPose::runtimeConfigure().
    {
        peg0->waitTransformUpdate();
        return peg0->toPoseStampedMsg();
    }
onLinkStatesCallback()
void sm_panda_moveit::ClPerceptionSystem::onLinkStatesCallback (const gazebo_msgs::LinkStates & linksmsg) [inline]
Definition at line 33 of file cl_perception_system.h.
References propagateLinkStatesToTf().
Referenced by ClPerceptionSystem().
    {
        //std::vector<tf::Transform> pegTransforms;
        this->propagateLinkStatesToTf(linksmsg, "peg", "peg", "world", true);
        this->propagateLinkStatesToTf(linksmsg, "panda::panda_pose", "panda_pose", "
      world", false);
        this->propagateLinkStatesToTf(linksmsg, "horizontal_peg_holder::", "
      horizontal_peg_place_", "world", true);
        this->propagateLinkStatesToTf(linksmsg, "wall_peg_holder::", "
      wall_peg_place_", "world", true);
    }
propagateLinkStatesToTf()
void sm_panda_moveit::ClPerceptionSystem::propagateLinkStatesToTf (const gazebo_msgs::LinkStates & linksmsg, std::string link_name_filter, std::string object_prefix, std::string global_frame, bool indexpostfix) [inline]
Definition at line 49 of file cl_perception_system.h.
References interactive_marker::name, and interactive_marker::pose.
Referenced by onLinkStatesCallback().
    {
        int count = 0;
        for (int i = 0; i < linksmsg.name.size(); i++)
        {
            auto &name = linksmsg.name[i];
            auto &pose = linksmsg.pose[i];
            if (name.find(link_name_filter) == 0)
            {
                tf::Transform transf;
                tf::poseMsgToTF(pose, transf);
                std::string framename = object_prefix;
                if (indexpostfix)
                {
                    framename += std::to_string(count);
                }
                this->tfBroadcaster_.sendTransform(tf::StampedTransform(transf,
      ros::Time::now(), global_frame, framename));
                count++;
            }
        }
    }
update()
virtual void sm_panda_moveit::ClPerceptionSystem::update () [inline], [override], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 74 of file cl_perception_system.h.
    {
    }
Member Data Documentation
horizontalPegPlace0
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::horizontalPegPlace0
Definition at line 19 of file cl_perception_system.h.
horizontalPegPlace1
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::horizontalPegPlace1
Definition at line 20 of file cl_perception_system.h.
horizontalPegPlace2
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::horizontalPegPlace2
Definition at line 21 of file cl_perception_system.h.
linkStatesSub_
ros::Subscriber sm_panda_moveit::ClPerceptionSystem::linkStatesSub_ [private]
Definition at line 13 of file cl_perception_system.h.
peg0
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::peg0
Definition at line 17 of file cl_perception_system.h.
tfBroadcaster_
tf::TransformBroadcaster sm_panda_moveit::ClPerceptionSystem::tfBroadcaster_ [private]
Definition at line 14 of file cl_perception_system.h.
wallPegPlace0
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::wallPegPlace0
Definition at line 23 of file cl_perception_system.h.
wallPegPlace1
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::wallPegPlace1
Definition at line 24 of file cl_perception_system.h.
wallPegPlace2
cl_move_base_z::Pose* sm_panda_moveit::ClPerceptionSystem::wallPegPlace2
Definition at line 25 of file cl_perception_system.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_panda_moveit/sm_panda_moveit/include/sm_panda_moveit/clients/perception_system_client/cl_perception_system.h