franka::Robot::Impl Class Reference
#include <robot_impl.h>
Public Member Functions
Impl (std::unique_ptr< Network > network, size_t log_size, RealtimeConfig realtime_config=RealtimeConfig::kEnforce)
RobotState update (const research_interface::robot::MotionGeneratorCommand *motion_command, const research_interface::robot::ControllerCommand *control_command) override
void throwOnMotionError (const RobotState &robot_state, uint32_t motion_id) override
RobotState readOnce ()
ServerVersion serverVersion () const noexcept
RealtimeConfig realtimeConfig () const noexcept override
uint32_t startMotion (research_interface::robot::Move::ControllerMode controller_mode, research_interface::robot::Move::MotionGeneratorMode motion_generator_mode, const research_interface::robot::Move::Deviation &maximum_path_deviation, const research_interface::robot::Move::Deviation &maximum_goal_pose_deviation) override
void cancelMotion (uint32_t motion_id) override
void finishMotion (uint32_t motion_id, const research_interface::robot::MotionGeneratorCommand *motion_command, const research_interface::robot::ControllerCommand *control_command) override
template<typename T , typename... TArgs>
uint32_t executeCommand (TArgs...)
Model loadModel () const
Protected Member Functions
bool motionGeneratorRunning () const noexcept
bool controllerRunning () const noexcept
Private Types
template<typename T >
using IsBaseOfGetterSetter = std::is_base_of< research_interface::robot::GetterSetterCommandBase< T, T::kCommand >, T >
Private Member Functions
template<typename T >
std::enable_if_t< IsBaseOfGetterSetter< T >::value > handleCommandResponse (const typename T::Response &response) const
template<typename T >
std::enable_if_t<!IsBaseOfGetterSetter< T >::value > handleCommandResponse (const typename T::Response &response) const
research_interface::robot::RobotCommand sendRobotCommand (const research_interface::robot::MotionGeneratorCommand *motion_command, const research_interface::robot::ControllerCommand *control_command) const
research_interface::robot::RobotState receiveRobotState ()
void updateState (const research_interface::robot::RobotState &robot_state)
Private Attributes
std::unique_ptr< Network > network_
Logger logger_
const RealtimeConfig realtime_config_
uint16_t ri_version_
research_interface::robot::MotionGeneratorMode motion_generator_mode_
research_interface::robot::MotionGeneratorMode current_move_motion_generator_mode_
research_interface::robot::ControllerMode controller_mode_
research_interface::robot::ControllerMode current_move_controller_mode_
uint64_t message_id_
Detailed Description
Definition at line 23 of file robot_impl.h.
Member Typedef Documentation
IsBaseOfGetterSetter
template<typename T >
using franka::Robot::Impl::IsBaseOfGetterSetter = std::is_base_of<research_interface::robot::GetterSetterCommandBase<T, T::kCommand>, T> [private]
Definition at line 61 of file robot_impl.h.
Constructor & Destructor Documentation
Impl()
franka::Robot::Impl::Impl (std::unique_ptr< Network > network, size_t log_size, RealtimeConfig realtime_config = RealtimeConfig::kEnforce) [explicit]
Definition at line 43 of file robot_impl.cpp.
References logger_, franka_gripper::move(), network_, realtime_config_, ri_version_, and updateState().
    : network_{std::move(network)}, logger_{log_size},
      realtime_config_{realtime_config} {
  if (!network_) {
    throw std::invalid_argument("libfranka robot: Invalid argument");
  }
  connect<research_interface::robot::Connect, research_interface::robot::kVersion>(*
      network_,
                                                                                   &
      ri_version_);
  updateState(network_->udpBlockingReceive<
      research_interface::robot::RobotState>());
}
Member Function Documentation
cancelMotion()
void franka::Robot::Impl::cancelMotion (uint32_t motion_id) [override], [virtual]
Implements franka::RobotControl.
Definition at line 286 of file robot_impl.cpp.
References controllerRunning(), current_move_controller_mode_, current_move_motion_generator_mode_, research_interface::robot::kIdle, research_interface::robot::kOther, motionGeneratorRunning(), network_, and receiveRobotState().
                                               {
  try {
    executeCommand<research_interface::robot::StopMove>();
  } catch (const CommandException& e) {
    throw ControlException(e.what());
  }
  research_interface::robot::RobotState robot_state;
  do {
    robot_state = receiveRobotState();
  } while (motionGeneratorRunning() || controllerRunning());
  // Ignore Move response.
  // TODO (FWA): It is not guaranteed that the Move response won't come later
  network_->tcpReceiveResponse<research_interface::robot::Move>(
      motion_id, [](auto) {});
  current_move_motion_generator_mode_ =
      research_interface::robot::MotionGeneratorMode::kIdle;
  current_move_controller_mode_ =
      research_interface::robot::ControllerMode::kOther;
}
controllerRunning()
bool franka::Robot::Impl::controllerRunning () const [protected], [noexcept]
Definition at line 170 of file robot_impl.cpp.
References controller_mode_, and research_interface::robot::kExternalController.
Referenced by cancelMotion(), finishMotion(), and startMotion().
                                                 {
  return controller_mode_ ==
      research_interface::robot::ControllerMode::kExternalController
      ;
}
executeCommand()
template<typename T , typename... TArgs>
uint32_t franka::Robot::Impl::executeCommand (TArgs... args)
Definition at line 265 of file robot_impl.h.
References generate_debs::args, and network_.
                                                {
  uint32_t command_id = network_->tcpSendRequest<T>(args...);
  typename T::Response response = network_->tcpBlockingReceiveResponse<T>(command_id);
  handleCommandResponse<T>(response);
  return command_id;
}
finishMotion()
void franka::Robot::Impl::finishMotion (uint32_t motion_id, const research_interface::robot::MotionGeneratorCommand * motion_command, const research_interface::robot::ControllerCommand * control_command) [override], [virtual]
Implements franka::RobotControl.
Definition at line 247 of file robot_impl.cpp.
References controllerRunning(), franka::anonymous_namespace{robot_impl.cpp}::createControlException(), current_move_controller_mode_, current_move_motion_generator_mode_, franka::Logger::flush(), research_interface::robot::kIdle, research_interface::robot::kOther, research_interface::robot::Move::kReflexAborted, logger_, research_interface::robot::MotionGeneratorCommand::motion_generation_finished, motionGeneratorRunning(), network_, and update().
                                                                     {
  if (!motionGeneratorRunning() && !controllerRunning()) {
    current_move_motion_generator_mode_ =
      research_interface::robot::MotionGeneratorMode::kIdle;
    current_move_controller_mode_ =
      research_interface::robot::ControllerMode::kOther;
    return;
  }
  if (motion_command == nullptr) {
    throw ControlException("libfranka robot: No motion generator command given!");
  }
  research_interface::robot::MotionGeneratorCommand
      motion_finished_command = *motion_command;
  motion_finished_command.motion_generation_finished = true;
  // The TCP response for the finished Move might arrive while the robot state still shows that the
  // motion is running, or afterwards. To handle both situations, we do not process TCP packages in
  // this loop and explicitly wait for the Move response over TCP afterwards.
  RobotState robot_state{};
  while (motionGeneratorRunning() || controllerRunning()) {
    robot_state = update(&motion_finished_command, control_command);
  }
  auto response = network_->tcpBlockingReceiveResponse<
      research_interface::robot::Move>(motion_id);
  if (response.status == research_interface::robot::Move::Status::kReflexAborted
      ) {
    throw createControlException("Motion finished commanded, but the robot is still
       moving!",
                                 response.status, robot_state.last_motion_errors,
      logger_.flush());
  }
  try {
    handleCommandResponse<research_interface::robot::Move>(response);
  } catch (const CommandException& e) {
    throw createControlException(e.what(), response.status, robot_state.
      last_motion_errors,
                                 logger_.flush());
  }
  current_move_motion_generator_mode_ =
      research_interface::robot::MotionGeneratorMode::kIdle;
  current_move_controller_mode_ =
      research_interface::robot::ControllerMode::kOther;
}
handleCommandResponse() [1/2]
template<typename T >
std::enable_if_t<IsBaseOfGetterSetter<T>::value> franka::Robot::Impl::handleCommandResponse (const typename T::Response & response) const [inline], [private]
Definition at line 64 of file robot_impl.h.
References service_node_3::s.
                                                {
    using namespace std::string_literals; // NOLINT(google-build-using-namespace)
    switch (response.status) {
      case T::Status::kSuccess:
        break;
      case T::Status::kCommandNotPossibleRejected:
        throw CommandException("libfranka: "s +
      research_interface::robot::CommandTraits<T>::kName +
                               " command rejected: command not possible in the current mode!");
      case T::Status::kInvalidArgumentRejected:
        throw CommandException("libfranka: "s +
      research_interface::robot::CommandTraits<T>::kName +
                               " command rejected: invalid argument!");
      default:
        throw ProtocolException("libfranka: Unexpected response while handling "
      s +
                                
      research_interface::robot::CommandTraits<T>::kName + "
       command!");
    }
  }
handleCommandResponse() [2/2]
template<typename T >
std::enable_if_t<!IsBaseOfGetterSetter<T>::value> franka::Robot::Impl::handleCommandResponse (const typename T::Response & response) const [inline], [private]
Definition at line 84 of file robot_impl.h.
References receiveRobotState(), service_node_3::s, sendRobotCommand(), and updateState().
                                                {
    using namespace std::string_literals; // NOLINT(google-build-using-namespace)
    switch (response.status) {
      case T::Status::kSuccess:
        break;
      case T::Status::kCommandNotPossibleRejected:
        throw CommandException("libfranka: "s +
      research_interface::robot::CommandTraits<T>::kName +
                               " command rejected: command not possible in the current mode!");
      default:
        throw ProtocolException("libfranka: Unexpected response while handling "
      s +
                                
      research_interface::robot::CommandTraits<T>::kName + "
       command!");
    }
  }
loadModel()
Model franka::Robot::Impl::loadModel () const
Definition at line 305 of file robot_impl.cpp.
References network_.
                                 {
  return Model(*network_);
}
motionGeneratorRunning()
bool franka::Robot::Impl::motionGeneratorRunning () const [protected], [noexcept]
Definition at line 166 of file robot_impl.cpp.
References research_interface::robot::kIdle, and motion_generator_mode_.
Referenced by cancelMotion(), finishMotion(), franka::Robot::Impl::handleCommandResponse< research_interface::robot::Move >(), and startMotion().
                                                      {
  return motion_generator_mode_ !=
      research_interface::robot::MotionGeneratorMode::kIdle;
}
readOnce()
RobotState franka::Robot::Impl::readOnce ()
Definition at line 86 of file robot_impl.cpp.
References franka::convertRobotState(), network_, and receiveRobotState().
                               {
  // Delete old data from the UDP buffer.
  research_interface::robot::RobotState robot_state;
  while (network_->udpReceive<decltype(robot_state)>(&robot_state)) {
  }
  return convertRobotState(receiveRobotState());
}
realtimeConfig()
RealtimeConfig franka::Robot::Impl::realtimeConfig () const [override], [virtual], [noexcept]
Implements franka::RobotControl.
Definition at line 174 of file robot_impl.cpp.
References realtime_config_.
                                                        {
  return realtime_config_;
}
receiveRobotState()
research_interface::robot::RobotState franka::Robot::Impl::receiveRobotState () [private]
Definition at line 132 of file robot_impl.cpp.
References research_interface::robot::RobotState::message_id, message_id_, network_, and updateState().
Referenced by cancelMotion(), handleCommandResponse(), readOnce(), and update().
                                                               {
  research_interface::robot::RobotState latest_accepted_state;
  latest_accepted_state.message_id = message_id_;
  // If states are already available on the socket, use the one with the most recent message ID.
  research_interface::robot::RobotState received_state{};
  while (network_->udpReceive(&received_state)) {
    if (received_state.message_id > latest_accepted_state.message_id) {
      latest_accepted_state = received_state;
    }
  }
  // If there was no valid state on the socket, we need to wait.
  while (latest_accepted_state.message_id == message_id_) {
    received_state = network_->udpBlockingReceive<decltype(received_state)>();
    if (received_state.message_id > latest_accepted_state.message_id) {
      latest_accepted_state = received_state;
    }
  }
  updateState(latest_accepted_state);
  return latest_accepted_state;
}
sendRobotCommand()
research_interface::robot::RobotCommand franka::Robot::Impl::sendRobotCommand (const research_interface::robot::MotionGeneratorCommand * motion_command, const research_interface::robot::ControllerCommand * control_command) const [private]
Definition at line 95 of file robot_impl.cpp.
References current_move_controller_mode_, current_move_motion_generator_mode_, research_interface::robot::kExternalController, research_interface::robot::kIdle, research_interface::robot::RobotCommand::message_id, message_id_, and network_.
Referenced by handleCommandResponse(), and update().
                                                                           {
  research_interface::robot::RobotCommand robot_command{};
  if (motion_command != nullptr || control_command != nullptr) {
    robot_command.message_id = message_id_;
    if (motion_command != nullptr) {
      if (current_move_motion_generator_mode_ ==
          research_interface::robot::MotionGeneratorMode::kIdle
      ) {
        throw ControlException(
            "libfranka robot: Trying to send motion command, but no motion generator running!");
      }
      robot_command.motion = *motion_command;
    }
    if (control_command != nullptr) {
      if (current_move_controller_mode_ !=
          research_interface::robot::ControllerMode::kExternalController
      ) {
        throw ControlException(
            "libfranka robot: Trying to send control command, but no controller running!");
      }
      robot_command.control = *control_command;
    }
    if (current_move_motion_generator_mode_ !=
            research_interface::robot::MotionGeneratorMode::kIdle
       &&
        current_move_controller_mode_ ==
            research_interface::robot::ControllerMode::kExternalController
       &&
        (motion_command == nullptr || control_command == nullptr)) {
      throw ControlException("libfranka robot: Trying to send partial robot command!");
    }
    network_->udpSend<research_interface::robot::RobotCommand
      >(robot_command);
  }
  return robot_command;
}
serverVersion()
Robot::ServerVersion franka::Robot::Impl::serverVersion () const [noexcept]
Definition at line 162 of file robot_impl.cpp.
References ri_version_.
                                                           {
  return ri_version_;
}
startMotion()
uint32_t franka::Robot::Impl::startMotion (research_interface::robot::Move::ControllerMode controller_mode, research_interface::robot::Move::MotionGeneratorMode motion_generator_mode, const research_interface::robot::Move::Deviation & maximum_path_deviation, const research_interface::robot::Move::Deviation & maximum_goal_pose_deviation) [override], [virtual]
Implements franka::RobotControl.
Definition at line 178 of file robot_impl.cpp.
References controller_mode_, controllerRunning(), current_move_controller_mode_, current_move_motion_generator_mode_, franka::Logger::flush(), franka::kCartesianImpedance, franka::kJointImpedance, logger_, motion_generator_mode_, motionGeneratorRunning(), network_, and update().
                                                                             {
  if (motionGeneratorRunning() || controllerRunning()) {
    throw ControlException("libfranka robot: Attempted to start multiple motions!");
  }
  switch (motion_generator_mode) {
    case decltype(motion_generator_mode)::kJointPosition:
      current_move_motion_generator_mode_ =
          decltype(current_move_motion_generator_mode_)::
      kJointPosition;
      break;
    case decltype(motion_generator_mode)::kJointVelocity:
      current_move_motion_generator_mode_ =
          decltype(current_move_motion_generator_mode_)::
      kJointVelocity;
      break;
    case decltype(motion_generator_mode)::kCartesianPosition:
      current_move_motion_generator_mode_ =
          decltype(current_move_motion_generator_mode_)::
      kCartesianPosition;
      break;
    case decltype(motion_generator_mode)::kCartesianVelocity:
      current_move_motion_generator_mode_ =
          decltype(current_move_motion_generator_mode_)::
      kCartesianVelocity;
      break;
    default:
      throw std::invalid_argument("libfranka: Invalid motion generator mode given.");
  }
  switch (controller_mode) {
    case decltype(controller_mode)::kJointImpedance:
      current_move_controller_mode_ = decltype(
      current_move_controller_mode_)::kJointImpedance;
      break;
    case decltype(controller_mode)::kCartesianImpedance:
      current_move_controller_mode_ = decltype(
      current_move_controller_mode_)::kCartesianImpedance;
      break;
    case decltype(controller_mode)::kExternalController:
      current_move_controller_mode_ = decltype(
      current_move_controller_mode_)::kExternalController;
      break;
    default:
      throw std::invalid_argument("libfranka robot: Invalid controller mode given.");
  }
  const uint32_t move_command_id = executeCommand<research_interface::robot::Move>(
      controller_mode, motion_generator_mode, maximum_path_deviation, maximum_goal_pose_deviation);
  RobotState robot_state{};
  while (motion_generator_mode_ !=
      current_move_motion_generator_mode_ ||
         controller_mode_ != current_move_controller_mode_) {
    try {
      if (network_->tcpReceiveResponse<research_interface::robot::Move
      >(
              move_command_id,
              std::bind(&Robot::Impl::handleCommandResponse<research_interface::robot::Move>, this,
                        std::placeholders::_1))) {
        break;
      }
    } catch (const CommandException& e) {
      throw ControlException(e.what());
    }
    robot_state = update(nullptr, nullptr);
  }
  logger_.flush();
  return move_command_id;
}
throwOnMotionError()
void franka::Robot::Impl::throwOnMotionError (const RobotState & robot_state, uint32_t motion_id) [override], [virtual]
Implements franka::RobotControl.
Definition at line 68 of file robot_impl.cpp.
References controller_mode_, franka::anonymous_namespace{robot_impl.cpp}::createControlException(), current_move_controller_mode_, current_move_motion_generator_mode_, franka::Logger::flush(), franka::kMove, franka::RobotState::last_motion_errors, logger_, motion_generator_mode_, network_, and franka::RobotState::robot_mode.
                                                                                    {
  if (robot_state.robot_mode != RobotMode::kMove ||
      motion_generator_mode_ !=
      current_move_motion_generator_mode_ ||
      controller_mode_ != current_move_controller_mode_) {
    // We detect a move error by changes in the robot state and we will receive a TCP response to
    // the Move command.
    auto response =
        network_->tcpBlockingReceiveResponse<
      research_interface::robot::Move>(motion_id);
    try {
      handleCommandResponse<research_interface::robot::Move>(response);
    } catch (const CommandException& e) {
      throw createControlException(e.what(), response.status, robot_state.
      last_motion_errors,
                                   logger_.flush());
    }
    throw ProtocolException("Unexpected reply to a Move command");
  }
}
update()
RobotState franka::Robot::Impl::update (const research_interface::robot::MotionGeneratorCommand * motion_command, const research_interface::robot::ControllerCommand * control_command) [override], [virtual]
Implements franka::RobotControl.
Definition at line 54 of file robot_impl.cpp.
References franka::convertRobotState(), franka::Logger::log(), logger_, network_, receiveRobotState(), and sendRobotCommand().
Referenced by finishMotion(), and startMotion().
                                                                     {
  network_->tcpThrowIfConnectionClosed();
  research_interface::robot::RobotCommand robot_command =
      sendRobotCommand(motion_command, control_command);
  RobotState state = convertRobotState(receiveRobotState());
  logger_.log(state, robot_command);
  return state;
}
updateState()
void franka::Robot::Impl::updateState (const research_interface::robot::RobotState & robot_state) [private]
Definition at line 156 of file robot_impl.cpp.
References research_interface::robot::RobotState::controller_mode, controller_mode_, research_interface::robot::RobotState::message_id, message_id_, research_interface::robot::RobotState::motion_generator_mode, and motion_generator_mode_.
Referenced by handleCommandResponse(), Impl(), and receiveRobotState().
                                                                                {
  motion_generator_mode_ = robot_state.
      motion_generator_mode;
  controller_mode_ = robot_state.controller_mode;
  message_id_ = robot_state.message_id;
}
Member Data Documentation
controller_mode_
research_interface::robot::ControllerMode franka::Robot::Impl::controller_mode_ [private]
Initial value:
=
      research_interface::robot::ControllerMode::kOther
Definition at line 116 of file robot_impl.h.
Referenced by controllerRunning(), startMotion(), throwOnMotionError(), and updateState().
current_move_controller_mode_
research_interface::robot::ControllerMode franka::Robot::Impl::current_move_controller_mode_ [private]
Definition at line 118 of file robot_impl.h.
Referenced by cancelMotion(), finishMotion(), sendRobotCommand(), startMotion(), and throwOnMotionError().
current_move_motion_generator_mode_
research_interface::robot::MotionGeneratorMode franka::Robot::Impl::current_move_motion_generator_mode_ [private]
Initial value:
=
      research_interface::robot::MotionGeneratorMode::kIdle
Definition at line 114 of file robot_impl.h.
Referenced by cancelMotion(), finishMotion(), sendRobotCommand(), startMotion(), and throwOnMotionError().
logger_
Logger franka::Robot::Impl::logger_ [private]
Definition at line 108 of file robot_impl.h.
Referenced by finishMotion(), Impl(), startMotion(), throwOnMotionError(), and update().
message_id_
uint64_t franka::Robot::Impl::message_id_ [private]
Definition at line 119 of file robot_impl.h.
Referenced by receiveRobotState(), sendRobotCommand(), and updateState().
motion_generator_mode_
research_interface::robot::MotionGeneratorMode franka::Robot::Impl::motion_generator_mode_ [private]
Definition at line 113 of file robot_impl.h.
Referenced by motionGeneratorRunning(), startMotion(), throwOnMotionError(), and updateState().
network_
std::unique_ptr<Network> franka::Robot::Impl::network_ [private]
Definition at line 106 of file robot_impl.h.
Referenced by cancelMotion(), executeCommand(), finishMotion(), Impl(), loadModel(), readOnce(), receiveRobotState(), franka::Robot::Impl::executeCommand< research_interface::robot::GetCartesianLimit, int32_t, VirtualWallCuboid * >(), sendRobotCommand(), startMotion(), throwOnMotionError(), and update().
realtime_config_
const RealtimeConfig franka::Robot::Impl::realtime_config_ [private]
Definition at line 110 of file robot_impl.h.
Referenced by Impl(), and realtimeConfig().
ri_version_
uint16_t franka::Robot::Impl::ri_version_ [private]
Definition at line 111 of file robot_impl.h.
Referenced by Impl(), and serverVersion().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/robot_impl.h
smacc_sm_reference_library/sm_panda_moveit/libfranka/src/robot_impl.cpp