smacc_sm_reference_library/sm_panda_moveit/libfranka/examples/examples_common.h File Reference
#include <array>
#include <Eigen/Core>
#include <franka/control_types.h>
#include <franka/duration.h>
#include <franka/robot.h>
#include <franka/robot_state.h>
Classes
class MotionGenerator
Functions
void setDefaultBehavior (franka::Robot &robot)
Detailed Description
Contains common types and functions for the examples.
Function Documentation
setDefaultBehavior()
void setDefaultBehavior (franka::Robot & robot)
Sets a default collision behavior, joint impedance, Cartesian impedance, and filter frequency.
Parameters
in robot Robot instance to set behavior on.
Definition at line 12 of file examples_common.cpp.
References franka::Robot::setCartesianImpedance(), franka::Robot::setCollisionBehavior(), and franka::Robot::setJointImpedance().
Referenced by main().
                                            {
  robot.setCollisionBehavior(
      {{20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0}}, {{20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0}},
      {{10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0}}, {{10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0}},
      {{20.0, 20.0, 20.0, 20.0, 20.0, 20.0}}, {{20.0, 20.0, 20.0, 20.0, 20.0, 20.0}},
      {{10.0, 10.0, 10.0, 10.0, 10.0, 10.0}}, {{10.0, 10.0, 10.0, 10.0, 10.0, 10.0}});
  robot.setJointImpedance({{3000, 3000, 3000, 2500, 2500, 2000, 2000}});
  robot.setCartesianImpedance({{3000, 3000, 3000, 300, 300, 300}});
}