smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/include/gtest/gtest_pred_impl.h File Reference
Macros
#define GTEST_ASSERT_(expression, on_failure)
#define GTEST_PRED_FORMAT1_(pred_format, v1, on_failure)
#define GTEST_PRED1_(pred, v1, on_failure)
#define EXPECT_PRED_FORMAT1(pred_format, v1) GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
#define EXPECT_PRED1(pred, v1) GTEST_PRED1_(pred, v1, GTEST_NONFATAL_FAILURE_)
#define ASSERT_PRED_FORMAT1(pred_format, v1) GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_FATAL_FAILURE_)
#define ASSERT_PRED1(pred, v1) GTEST_PRED1_(pred, v1, GTEST_FATAL_FAILURE_)
#define GTEST_PRED_FORMAT2_(pred_format, v1, v2, on_failure)
#define GTEST_PRED2_(pred, v1, v2, on_failure)
#define EXPECT_PRED_FORMAT2(pred_format, v1, v2) GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
#define EXPECT_PRED2(pred, v1, v2) GTEST_PRED2_(pred, v1, v2, GTEST_NONFATAL_FAILURE_)
#define ASSERT_PRED_FORMAT2(pred_format, v1, v2) GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
#define ASSERT_PRED2(pred, v1, v2) GTEST_PRED2_(pred, v1, v2, GTEST_FATAL_FAILURE_)
#define GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, on_failure)
#define GTEST_PRED3_(pred, v1, v2, v3, on_failure)
#define EXPECT_PRED_FORMAT3(pred_format, v1, v2, v3) GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, GTEST_NONFATAL_FAILURE_)
#define EXPECT_PRED3(pred, v1, v2, v3) GTEST_PRED3_(pred, v1, v2, v3, GTEST_NONFATAL_FAILURE_)
#define ASSERT_PRED_FORMAT3(pred_format, v1, v2, v3) GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, GTEST_FATAL_FAILURE_)
#define ASSERT_PRED3(pred, v1, v2, v3) GTEST_PRED3_(pred, v1, v2, v3, GTEST_FATAL_FAILURE_)
#define GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, on_failure)
#define GTEST_PRED4_(pred, v1, v2, v3, v4, on_failure)
#define EXPECT_PRED_FORMAT4(pred_format, v1, v2, v3, v4) GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, GTEST_NONFATAL_FAILURE_)
#define EXPECT_PRED4(pred, v1, v2, v3, v4) GTEST_PRED4_(pred, v1, v2, v3, v4, GTEST_NONFATAL_FAILURE_)
#define ASSERT_PRED_FORMAT4(pred_format, v1, v2, v3, v4) GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, GTEST_FATAL_FAILURE_)
#define ASSERT_PRED4(pred, v1, v2, v3, v4) GTEST_PRED4_(pred, v1, v2, v3, v4, GTEST_FATAL_FAILURE_)
#define GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, on_failure)
#define GTEST_PRED5_(pred, v1, v2, v3, v4, v5, on_failure)
#define EXPECT_PRED_FORMAT5(pred_format, v1, v2, v3, v4, v5) GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, GTEST_NONFATAL_FAILURE_)
#define EXPECT_PRED5(pred, v1, v2, v3, v4, v5) GTEST_PRED5_(pred, v1, v2, v3, v4, v5, GTEST_NONFATAL_FAILURE_)
#define ASSERT_PRED_FORMAT5(pred_format, v1, v2, v3, v4, v5) GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, GTEST_FATAL_FAILURE_)
#define ASSERT_PRED5(pred, v1, v2, v3, v4, v5) GTEST_PRED5_(pred, v1, v2, v3, v4, v5, GTEST_FATAL_FAILURE_)
Functions
template<typename Pred , typename T1 >
AssertionResult AssertPred1Helper (const char *pred_text, const char *e1, Pred pred, const T1 &v1)
template<typename Pred , typename T1 , typename T2 >
AssertionResult AssertPred2Helper (const char *pred_text, const char *e1, const char *e2, Pred pred, const T1 &v1, const T2 &v2)
template<typename Pred , typename T1 , typename T2 , typename T3 >
AssertionResult AssertPred3Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 >
AssertionResult AssertPred4Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
AssertionResult AssertPred5Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, const char *e5, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)
Macro Definition Documentation
ASSERT_PRED1
#define ASSERT_PRED1(pred, v1) GTEST_PRED1_(pred, v1, GTEST_FATAL_FAILURE_)
Definition at line 119 of file gtest_pred_impl.h.
ASSERT_PRED2
#define ASSERT_PRED2(pred, v1, v2) GTEST_PRED2_(pred, v1, v2, GTEST_FATAL_FAILURE_)
Definition at line 167 of file gtest_pred_impl.h.
ASSERT_PRED3
#define ASSERT_PRED3(pred, v1, v2, v3) GTEST_PRED3_(pred, v1, v2, v3, GTEST_FATAL_FAILURE_)
Definition at line 222 of file gtest_pred_impl.h.
ASSERT_PRED4
#define ASSERT_PRED4(pred, v1, v2, v3, v4) GTEST_PRED4_(pred, v1, v2, v3, v4, GTEST_FATAL_FAILURE_)
Definition at line 284 of file gtest_pred_impl.h.
ASSERT_PRED5
#define ASSERT_PRED5(pred, v1, v2, v3, v4, v5) GTEST_PRED5_(pred, v1, v2, v3, v4, v5, GTEST_FATAL_FAILURE_)
Definition at line 353 of file gtest_pred_impl.h.
ASSERT_PRED_FORMAT1
#define ASSERT_PRED_FORMAT1(pred_format, v1) GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_FATAL_FAILURE_)
Definition at line 117 of file gtest_pred_impl.h.
ASSERT_PRED_FORMAT2
#define ASSERT_PRED_FORMAT2(pred_format, v1, v2) GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
Definition at line 165 of file gtest_pred_impl.h.
ASSERT_PRED_FORMAT3
#define ASSERT_PRED_FORMAT3(pred_format, v1, v2, v3) GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, GTEST_FATAL_FAILURE_)
Definition at line 220 of file gtest_pred_impl.h.
ASSERT_PRED_FORMAT4
#define ASSERT_PRED_FORMAT4(pred_format, v1, v2, v3, v4) GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, GTEST_FATAL_FAILURE_)
Definition at line 282 of file gtest_pred_impl.h.
ASSERT_PRED_FORMAT5
#define ASSERT_PRED_FORMAT5(pred_format, v1, v2, v3, v4, v5) GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, GTEST_FATAL_FAILURE_)
Definition at line 351 of file gtest_pred_impl.h.
EXPECT_PRED1
#define EXPECT_PRED1(pred, v1) GTEST_PRED1_(pred, v1, GTEST_NONFATAL_FAILURE_)
Definition at line 115 of file gtest_pred_impl.h.
EXPECT_PRED2
#define EXPECT_PRED2(pred, v1, v2) GTEST_PRED2_(pred, v1, v2, GTEST_NONFATAL_FAILURE_)
Definition at line 163 of file gtest_pred_impl.h.
EXPECT_PRED3
#define EXPECT_PRED3(pred, v1, v2, v3) GTEST_PRED3_(pred, v1, v2, v3, GTEST_NONFATAL_FAILURE_)
Definition at line 218 of file gtest_pred_impl.h.
EXPECT_PRED4
#define EXPECT_PRED4(pred, v1, v2, v3, v4) GTEST_PRED4_(pred, v1, v2, v3, v4, GTEST_NONFATAL_FAILURE_)
Definition at line 280 of file gtest_pred_impl.h.
EXPECT_PRED5
#define EXPECT_PRED5(pred, v1, v2, v3, v4, v5) GTEST_PRED5_(pred, v1, v2, v3, v4, v5, GTEST_NONFATAL_FAILURE_)
Definition at line 349 of file gtest_pred_impl.h.
EXPECT_PRED_FORMAT1
#define EXPECT_PRED_FORMAT1(pred_format, v1) GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_NONFATAL_FAILURE_)
Definition at line 113 of file gtest_pred_impl.h.
EXPECT_PRED_FORMAT2
#define EXPECT_PRED_FORMAT2(pred_format, v1, v2) GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
Definition at line 161 of file gtest_pred_impl.h.
EXPECT_PRED_FORMAT3
#define EXPECT_PRED_FORMAT3(pred_format, v1, v2, v3) GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, GTEST_NONFATAL_FAILURE_)
Definition at line 216 of file gtest_pred_impl.h.
Referenced by testing::internal::SingleFailureChecker::~SingleFailureChecker().
EXPECT_PRED_FORMAT4
#define EXPECT_PRED_FORMAT4(pred_format, v1, v2, v3, v4) GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, GTEST_NONFATAL_FAILURE_)
Definition at line 278 of file gtest_pred_impl.h.
EXPECT_PRED_FORMAT5
#define EXPECT_PRED_FORMAT5(pred_format, v1, v2, v3, v4, v5) GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, GTEST_NONFATAL_FAILURE_)
Definition at line 347 of file gtest_pred_impl.h.
GTEST_ASSERT_
#define GTEST_ASSERT_(expression, on_failure)
Value:
GTEST_AMBIGUOUS_ELSE_BLOCKER_ \
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
    ; \
  else \
    on_failure(gtest_ar.failure_message())
Definition at line 75 of file gtest_pred_impl.h.
GTEST_PRED1_
#define GTEST_PRED1_(pred, v1, on_failure)
Value:
GTEST_ASSERT_(::testing::AssertPred1Helper(#pred, \
                                             #v1, \
                                             pred, \
                                             v1), on_failure)
Definition at line 106 of file gtest_pred_impl.h.
GTEST_PRED2_
#define GTEST_PRED2_(pred, v1, v2, on_failure)
Value:
GTEST_ASSERT_(::testing::AssertPred2Helper(#pred, \
                                             #v1, \
                                             #v2, \
                                             pred, \
                                             v1, \
                                             v2), on_failure)
Definition at line 152 of file gtest_pred_impl.h.
GTEST_PRED3_
#define GTEST_PRED3_(pred, v1, v2, v3, on_failure)
Value:
GTEST_ASSERT_(::testing::AssertPred3Helper(#pred, \
                                             #v1, \
                                             #v2, \
                                             #v3, \
                                             pred, \
                                             v1, \
                                             v2, \
                                             v3), on_failure)
Definition at line 205 of file gtest_pred_impl.h.
GTEST_PRED4_
#define GTEST_PRED4_(pred, v1, v2, v3, v4, on_failure)
Value:
GTEST_ASSERT_(::testing::AssertPred4Helper(#pred, \
                                             #v1, \
                                             #v2, \
                                             #v3, \
                                             #v4, \
                                             pred, \
                                             v1, \
                                             v2, \
                                             v3, \
                                             v4), on_failure)
Definition at line 265 of file gtest_pred_impl.h.
GTEST_PRED5_
#define GTEST_PRED5_(pred, v1, v2, v3, v4, v5, on_failure)
Value:
GTEST_ASSERT_(::testing::AssertPred5Helper(#pred, \
                                             #v1, \
                                             #v2, \
                                             #v3, \
                                             #v4, \
                                             #v5, \
                                             pred, \
                                             v1, \
                                             v2, \
                                             v3, \
                                             v4, \
                                             v5), on_failure)
Definition at line 332 of file gtest_pred_impl.h.
GTEST_PRED_FORMAT1_
#define GTEST_PRED_FORMAT1_(pred_format, v1, on_failure)
Value:
GTEST_ASSERT_(pred_format(#v1, v1), \
                on_failure)
Definition at line 100 of file gtest_pred_impl.h.
GTEST_PRED_FORMAT2_
#define GTEST_PRED_FORMAT2_(pred_format, v1, v2, on_failure)
Value:
GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), \
                on_failure)
Definition at line 146 of file gtest_pred_impl.h.
GTEST_PRED_FORMAT3_
#define GTEST_PRED_FORMAT3_(pred_format, v1, v2, v3, on_failure)
Value:
GTEST_ASSERT_(pred_format(#v1, #v2, #v3, v1, v2, v3), \
                on_failure)
Definition at line 199 of file gtest_pred_impl.h.
GTEST_PRED_FORMAT4_
#define GTEST_PRED_FORMAT4_(pred_format, v1, v2, v3, v4, on_failure)
Value:
GTEST_ASSERT_(pred_format(#v1, #v2, #v3, #v4, v1, v2, v3, v4), \
                on_failure)
Definition at line 259 of file gtest_pred_impl.h.
GTEST_PRED_FORMAT5_
#define GTEST_PRED_FORMAT5_(pred_format, v1, v2, v3, v4, v5, on_failure)
Value:
GTEST_ASSERT_(pred_format(#v1, #v2, #v3, #v4, #v5, v1, v2, v3, v4, v5), \
                on_failure)
Definition at line 326 of file gtest_pred_impl.h.
Function Documentation
AssertPred1Helper()
template<typename Pred , typename T1 >
AssertionResult AssertPred1Helper (const char * pred_text, const char * e1, Pred pred, const T1 & v1)
Definition at line 87 of file gtest_pred_impl.h.
References testing::AssertionFailure(), and testing::AssertionSuccess().
                                                {
  if (pred(v1)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1;
}
AssertPred2Helper()
template<typename Pred , typename T1 , typename T2 >
AssertionResult AssertPred2Helper (const char * pred_text, const char * e1, const char * e2, Pred pred, const T1 & v1, const T2 & v2)
Definition at line 129 of file gtest_pred_impl.h.
References testing::AssertionFailure(), and testing::AssertionSuccess().
                                                {
  if (pred(v1, v2)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2;
}
AssertPred3Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 >
AssertionResult AssertPred3Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 178 of file gtest_pred_impl.h.
References testing::AssertionFailure(), and testing::AssertionSuccess().
                                                {
  if (pred(v1, v2, v3)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3;
}
AssertPred4Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 >
AssertionResult AssertPred4Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)
Definition at line 234 of file gtest_pred_impl.h.
References testing::AssertionFailure(), and testing::AssertionSuccess().
                                                {
  if (pred(v1, v2, v3, v4)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ", "
                            << e4 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3
                            << "\n" << e4 << " evaluates to " << v4;
}
AssertPred5Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
AssertionResult AssertPred5Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, const char * e5, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5)
Definition at line 297 of file gtest_pred_impl.h.
References testing::AssertionFailure(), and testing::AssertionSuccess().
                                                {
  if (pred(v1, v2, v3, v4, v5)) return AssertionSuccess();
  return AssertionFailure() << pred_text << "("
                            << e1 << ", "
                            << e2 << ", "
                            << e3 << ", "
                            << e4 << ", "
                            << e5 << ") evaluates to false, where"
                            << "\n" << e1 << " evaluates to " << v1
                            << "\n" << e2 << " evaluates to " << v2
                            << "\n" << e3 << " evaluates to " << v3
                            << "\n" << e4 << " evaluates to " << v4
                            << "\n" << e5 << " evaluates to " << v5;
}