franka_gripper Namespace Reference
Functions
bool updateGripperState (const franka::Gripper &gripper, franka::GripperState *state)
void gripperCommandExecuteCallback (const franka::Gripper &gripper, const GraspEpsilon &grasp_epsilon, double default_speed, actionlib::SimpleActionServer< control_msgs::GripperCommandAction > *action_server, const control_msgs::GripperCommandGoalConstPtr &goal)
bool move (const franka::Gripper &gripper, const MoveGoalConstPtr &goal)
bool homing (const franka::Gripper &gripper, const HomingGoalConstPtr &)
bool stop (const franka::Gripper &gripper, const StopGoalConstPtr &)
bool grasp (const franka::Gripper &gripper, const GraspGoalConstPtr &goal)
Function Documentation
grasp()
bool franka_gripper::grasp (const franka::Gripper & gripper, const GraspGoalConstPtr & goal)
Calls the libfranka grasp service of the gripper
An object is considered grasped if the distance $d$ between the gripper fingers satisfies $(\text{width} - \text{epsilon_inner}) < d < (\text{width} + \text{epsilon_outer})$.
Parameters
in gripper A gripper instance to execute the command
in goal A grasp goal with target width, epsilon_inner, epsilon_outer, velocity and effort
Returns
True if an object has been grasped, false otherwise.
Definition at line 89 of file franka_gripper.cpp.
References franka::Gripper::grasp().
Referenced by anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), and main().
                                                                        {
  return gripper.grasp(goal->width, goal->speed, goal->force, goal->epsilon.inner,
                       goal->epsilon.outer);
}
gripperCommandExecuteCallback()
void franka_gripper::gripperCommandExecuteCallback (const franka::Gripper & gripper, const GraspEpsilon & grasp_epsilon, double default_speed, actionlib::SimpleActionServer< control_msgs::GripperCommandAction > * action_server, const control_msgs::GripperCommandGoalConstPtr & goal)
Wraps the execution of a gripper command action to catch exceptions and report results
Note
For compatibility with current MoveIt! behavior, the given goal's command position is multiplied by a factor of 2 before being commanded to the gripper!
Parameters
in gripper A pointer to a franka gripper
in default_speed The default speed for a gripper action
in grasp_epsilon The epsilon window of the grasp.
in action_server A pointer to a gripper action server
in goal A gripper action goal
Definition at line 30 of file franka_gripper.cpp.
References franka::Gripper::grasp(), franka::GripperState::max_width, franka::Gripper::move(), franka::Gripper::readOnce(), updateGripperState(), and franka::GripperState::width.
Referenced by anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), and main().
                                                        {
  auto gripper_command_handler = [goal, grasp_epsilon, default_speed, &gripper]() {
    // HACK: As one gripper finger is <mimic>, MoveIt!'s trajectory execution manager
    // only sends us the width of one finger. Multiply by 2 to get the intended width.
    double target_width = 2 * goal->command.position;
    franka::GripperState state = gripper.readOnce();
    if (target_width > state.max_width || target_width < 0.0) {
      ROS_ERROR_STREAM("GripperServer: Commanding out of range width! max_width = "
                       << state.max_width << " command = " << target_width);
      return false;
    }
    constexpr double kSamePositionThreshold = 1e-4;
    if (std::abs(target_width - state.width) < kSamePositionThreshold) {
      return true;
    }
    if (target_width >= state.width) {
      return gripper.move(target_width, default_speed);
    }
    return gripper.grasp(target_width, default_speed, goal->command.max_effort, grasp_epsilon.inner,
                         grasp_epsilon.outer);
  };
  try {
    if (gripper_command_handler()) {
      franka::GripperState state;
      if (updateGripperState(gripper, &state)) {
        control_msgs::GripperCommandResult result;
        result.effort = 0.0;
        result.position = state.width;
        result.reached_goal = static_cast<decltype(result.reached_goal)>(true);
        result.stalled = static_cast<decltype(result.stalled)>(false);
        action_server->setSucceeded(result);
        return;
      }
    }
  } catch (const franka::Exception& ex) {
    ROS_ERROR_STREAM("" << ex.what());
  }
  action_server->setAborted();
}
homing()
bool franka_gripper::homing (const franka::Gripper & gripper, const HomingGoalConstPtr &)
Calls the libfranka homing service of the gripper
Parameters
in gripper A gripper instance to execute the command
Returns
True if command was successful, false otherwise.
Definition at line 81 of file franka_gripper.cpp.
References franka::Gripper::homing().
Referenced by anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), and main().
                                                                       {
  return gripper.homing();
}
move()
bool franka_gripper::move (const franka::Gripper & gripper, const MoveGoalConstPtr & goal)
Calls the libfranka move service of the gripper
Parameters
in gripper A gripper instance to execute the command
in goal A move goal with target width and velocity
Returns
True if command was successful, false otherwise.
Definition at line 77 of file franka_gripper.cpp.
References franka::Gripper::move().
Referenced by testing::ByMove(), testing::internal::edit_distance::CalculateOptimalEdits(), franka::Robot::control(), extractObstacleFromJson(), anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), franka::Robot::Impl::Impl(), main(), franka::Robot::operator=(), testing::Return(), franka::Robot::Robot(), and testing::internal::ReferenceOrValueWrapper< T >::Unwrap().
                                                                      {
  return gripper.move(goal->width, goal->speed);
}
stop()
bool franka_gripper::stop (const franka::Gripper & gripper, const StopGoalConstPtr &)
Calls the libfranka stop service of the gripper to stop applying force
Parameters
in gripper A gripper instance to execute the command
Returns
True if command was successful, false otherwise.
Definition at line 85 of file franka_gripper.cpp.
References franka::Gripper::stop().
Referenced by anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), and main().
                                                                   {
  return gripper.stop();
}
updateGripperState()
bool franka_gripper::updateGripperState (const franka::Gripper & gripper, franka::GripperState * state)
Reads a gripper state if possible
Parameters
in state A gripper state to update
in gripper A pointer to a franka gripper
Returns
True if update was successful, false otherwise.
Definition at line 20 of file franka_gripper.cpp.
References franka::Gripper::readOnce().
Referenced by gripperCommandExecuteCallback(), anonymous_namespace{franka_gripper_node.cpp}::handleErrors(), and main().
                                                                                 {
  try {
    *state = gripper.readOnce();
  } catch (const franka::Exception& ex) {
    ROS_ERROR_STREAM("GripperServer: Exception reading gripper state: " << ex.what());
    return false;
  }
  return true;
}