testing::internal2 Namespace Reference
Classes
class TypeWithoutFormatter
class TypeWithoutFormatter< T, kConvertibleToInteger >
class TypeWithoutFormatter< T, kProtobuf >
Enumerations
enum TypeKind { kProtobuf,
kConvertibleToInteger,
kOtherType
 }
Functions
GTEST_API_ void PrintBytesInObjectTo (const unsigned char *obj_bytes, size_t count, ::std::ostream *os)
template<typename Char , typename CharTraits , typename T >
::std::basic_ostream< Char, CharTraits > & operator<< (::std::basic_ostream< Char, CharTraits > &os, const T &x)
void PrintBytesInObjectTo (const unsigned char *obj_bytes, size_t count, ostream *os)
Variables
const size_t kProtobufOneLinerMaxLength = 50
Enumeration Type Documentation
TypeKind
enum testing::internal2::TypeKind
Enumerator
kProtobuf
kConvertibleToInteger
kOtherType
Definition at line 124 of file gtest-printers.h.
              {
  kProtobuf, // a protobuf type
  kConvertibleToInteger, // a type implicitly convertible to BiggestInt
                          // (e.g. a named or unnamed enum type)
  kOtherType // anything else
};
Function Documentation
operator<<()
template<typename Char , typename CharTraits , typename T >
::std::basic_ostream<Char, CharTraits>& testing::internal2::operator<< (::std::basic_ostream< Char, CharTraits > & os, const T & x)
Definition at line 203 of file gtest-printers.h.
References kConvertibleToInteger, kOtherType, kProtobuf, and testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue().
                                                        {
  TypeWithoutFormatter<T,
      (internal::IsAProtocolMessage<T>::value ? kProtobuf :
       internal::ImplicitlyConvertible<const T&, internal::BiggestInt>::value ?
       kConvertibleToInteger : kOtherType)>::PrintValue(
      x, &os);
  return os;
}
PrintBytesInObjectTo() [1/2]
void testing::internal2::PrintBytesInObjectTo (const unsigned char * obj_bytes, size_t count, ostream * os)
Definition at line 114 of file gtest-printers.cc.
References testing::anonymous_namespace{gtest-printers.cc}::PrintBytesInObjectToImpl().
                                       {
  PrintBytesInObjectToImpl(obj_bytes, count, os);
}
PrintBytesInObjectTo() [2/2]
GTEST_API_ void testing::internal2::PrintBytesInObjectTo (const unsigned char * obj_bytes, size_t count, ::std::ostream * os)
Referenced by testing::internal2::TypeWithoutFormatter< T, kTypeKind >::PrintValue().
Variable Documentation
kProtobufOneLinerMaxLength
const size_t testing::internal2::kProtobufOneLinerMaxLength = 50
Definition at line 148 of file gtest-printers.h.