franka Namespace Reference
Namespaces
 anonymous_namespace{control_loop.cpp}
 anonymous_namespace{gripper.cpp}
 anonymous_namespace{log.cpp}
 anonymous_namespace{rate_limiting.cpp}
 anonymous_namespace{robot_impl.cpp}
 anonymous_namespace{robot_state.cpp}
Classes
class CartesianPose
class CartesianVelocities
struct CommandException
struct ControlException
class ControlLoop
class Duration
struct Errors
struct Exception
struct Finishable
class Gripper
struct GripperState
struct IncompatibleVersionException
struct InvalidOperationException
class JointPositions
class JointVelocities
class LibraryDownloader
class LibraryLoader
class Logger
class Model
struct ModelException
class ModelLibrary
struct MotionGeneratorTraits
struct MotionGeneratorTraits< CartesianPose >
struct MotionGeneratorTraits< CartesianVelocities >
struct MotionGeneratorTraits< JointPositions >
struct MotionGeneratorTraits< JointVelocities >
class Network
struct NetworkException
struct ProtocolException
struct RealtimeException
struct Record
class Robot
struct RobotCommand
class RobotControl
struct RobotState
class Torques
struct VirtualWallCuboid
Enumerations
enum ControllerMode { ControllerMode::kJointImpedance,
ControllerMode::kCartesianImpedance
 }
enum RealtimeConfig { RealtimeConfig::kEnforce,
RealtimeConfig::kIgnore
 }
enum Frame {
Frame::kJoint1,
Frame::kJoint2,
Frame::kJoint3,
Frame::kJoint4,
Frame::kJoint5,
Frame::kJoint6,
Frame::kJoint7,
Frame::kFlange,
Frame::kEndEffector,
Frame::kStiffness
 }
enum RobotMode {
RobotMode::kOther,
RobotMode::kIdle,
RobotMode::kMove,
RobotMode::kGuiding,
RobotMode::kReflex,
RobotMode::kUserStopped,
RobotMode::kAutomaticErrorRecovery
 }
Functions
bool isValidElbow (const std::array< double, 2 > &elbow) noexcept
bool isHomogeneousTransformation (const std::array< double, 16 > &transform) noexcept
bool hasRealtimeKernel ()
bool setCurrentThreadToHighestSchedulerPriority (std::string *error_message)
Torques MotionFinished (Torques command) noexcept
JointPositions MotionFinished (JointPositions command) noexcept
JointVelocities MotionFinished (JointVelocities command) noexcept
CartesianPose MotionFinished (CartesianPose command) noexcept
CartesianVelocities MotionFinished (CartesianVelocities command) noexcept
Duration operator* (uint64_t lhs, const Duration &rhs) noexcept
std::ostream & operator<< (std::ostream &ostream, const Errors &errors)
std::ostream & operator<< (std::ostream &ostream, const franka::GripperState &gripper_state)
std::string logToCSV (const std::vector< Record > &log)
double lowpassFilter (double sample_time, double y, double y_last, double cutoff_frequency)
std::array< double, 16 > cartesianLowpassFilter (double sample_time, std::array< double, 16 > y, std::array< double, 16 > y_last, double cutoff_frequency)
Frame operator++ (Frame &frame, int) noexcept
std::array< double, 7 > limitRate (const std::array< double, 7 > &max_derivatives, const std::array< double, 7 > &commanded_values, const std::array< double, 7 > &last_commanded_values)
double limitRate (double max_velocity, double max_acceleration, double max_jerk, double commanded_velocity, double last_commanded_velocity, double last_commanded_acceleration)
double limitRate (double max_velocity, double max_acceleration, double max_jerk, double commanded_position, double last_commanded_position, double last_commanded_velocity, double last_commanded_acceleration)
std::array< double, 7 > limitRate (const std::array< double, 7 > &max_velocity, const std::array< double, 7 > &max_acceleration, const std::array< double, 7 > &max_jerk, const std::array< double, 7 > &commanded_velocities, const std::array< double, 7 > &last_commanded_velocities, const std::array< double, 7 > &last_commanded_accelerations)
std::array< double, 7 > limitRate (const std::array< double, 7 > &max_velocity, const std::array< double, 7 > &max_acceleration, const std::array< double, 7 > &max_jerk, const std::array< double, 7 > &commanded_positions, const std::array< double, 7 > &last_commanded_positions, const std::array< double, 7 > &last_commanded_velocities, const std::array< double, 7 > &last_commanded_accelerations)
std::array< double, 6 > limitRate (double max_translational_velocity, double max_translational_acceleration, double max_translational_jerk, double max_rotational_velocity, double max_rotational_acceleration, double max_rotational_jerk, const std::array< double, 6 > &O_dP_EE_c, const std::array< double, 6 > &last_O_dP_EE_c, const std::array< double, 6 > &last_O_ddP_EE_c)
std::array< double, 16 > limitRate (double max_translational_velocity, double max_translational_acceleration, double max_translational_jerk, double max_rotational_velocity, double max_rotational_acceleration, double max_rotational_jerk, const std::array< double, 16 > &O_T_EE_c, const std::array< double, 16 > &last_O_T_EE_c, const std::array< double, 6 > &last_O_dP_EE_c, const std::array< double, 6 > &last_O_ddP_EE_c)
std::ostream & operator<< (std::ostream &ostream, const franka::RobotState &robot_state)
Duration::operator std::chrono::duration< uint64_t, std::milli > () const noexcept
std::array< double, 3 > combineCenterOfMass (double m_ee, const std::array< double, 3 > &F_x_Cee, double m_load, const std::array< double, 3 > &F_x_Cload)
Eigen::Matrix3d skewSymmetricMatrixFromVector (const Eigen::Vector3d &input)
std::array< double, 9 > combineInertiaTensor (double m_ee, const std::array< double, 3 > &F_x_Cee, const std::array< double, 9 > &I_ee, double m_load, const std::array< double, 3 > &F_x_Cload, const std::array< double, 9 > &I_load, double m_total, const std::array< double, 3 > &F_x_Ctotal)
template<typename T , uint16_t kLibraryVersion>
void connect (Network &network, uint16_t *ri_version)
RobotState convertRobotState (const research_interface::robot::RobotState &robot_state) noexcept
template<>
void Robot::Impl::handleCommandResponse< research_interface::robot::Move > (const research_interface::robot::Move::Response &response) const
template<>
void Robot::Impl::handleCommandResponse< research_interface::robot::StopMove > (const research_interface::robot::StopMove::Response &response) const
template<>
void Robot::Impl::handleCommandResponse< research_interface::robot::AutomaticErrorRecovery > (const research_interface::robot::AutomaticErrorRecovery::Response &response) const
template<>
uint32_t Robot::Impl::executeCommand< research_interface::robot::GetCartesianLimit, int32_t, VirtualWallCuboid * > (int32_t id, VirtualWallCuboid *virtual_wall_cuboid)
Variables
constexpr double kMaxCutoffFrequency = 1000.0
constexpr double kDefaultCutoffFrequency = 100.0
constexpr double kDeltaT = 1e-3
constexpr double kLimitEps = 1e-3
constexpr double kNormEps = std::numeric_limits<double>::epsilon()
constexpr double kTolNumberPacketsLost = 3.0
constexpr double kFactorCartesianRotationPoseInterface = 0.99
constexpr std::array< double, 7 > kMaxTorqueRate
constexpr std::array< double, 7 > kMaxJointJerk
constexpr std::array< double, 7 > kMaxJointAcceleration
constexpr std::array< double, 7 > kMaxJointVelocity
constexpr double kMaxTranslationalJerk = 6500.0 - kLimitEps
constexpr double kMaxTranslationalAcceleration = 13.0000 - kLimitEps
constexpr double kMaxTranslationalVelocity
constexpr double kMaxRotationalJerk = 12500.0 - kLimitEps
constexpr double kMaxRotationalAcceleration = 25.0000 - kLimitEps
constexpr double kMaxRotationalVelocity
constexpr double kMaxElbowJerk = 5000 - kLimitEps
constexpr double kMaxElbowAcceleration = 10.0000 - kLimitEps
constexpr double kMaxElbowVelocity
Enumeration Type Documentation
ControllerMode
enum franka::ControllerMode [strong]
Available controller modes for a franka::Robot.
Enumerator
kJointImpedance
kCartesianImpedance
Definition at line 19 of file control_types.h.
{ kJointImpedance, kCartesianImpedance };
Frame
enum franka::Frame [strong]
Enumerates the seven joints, the flange, and the end effector of a robot.
Enumerator
kJoint1
kJoint2
kJoint3
kJoint4
kJoint5
kJoint6
kJoint7
kFlange
kEndEffector
kStiffness
Definition at line 21 of file model.h.
                 {
  kJoint1,
  kJoint2,
  kJoint3,
  kJoint4,
  kJoint5,
  kJoint6,
  kJoint7,
  kFlange,
  kEndEffector,
  kStiffness
};
RealtimeConfig
enum franka::RealtimeConfig [strong]
Used to decide whether to enforce realtime mode for a control loop thread.
See also
Robot::Robot
Enumerator
kEnforce
kIgnore
Definition at line 26 of file control_types.h.
{ kEnforce, kIgnore };
RobotMode
enum franka::RobotMode [strong]
Describes the robot's current mode.
Enumerator
kOther
kIdle
kMove
kGuiding
kReflex
kUserStopped
kAutomaticErrorRecovery
Definition at line 22 of file robot_state.h.
                     {
  kOther,
  kIdle,
  kMove,
  kGuiding,
  kReflex,
  kUserStopped,
  kAutomaticErrorRecovery
};
Function Documentation
cartesianLowpassFilter()
std::array< double, 16 > franka::cartesianLowpassFilter (double sample_time, std::array< double, 16 > y, std::array< double, 16 > y_last, double cutoff_frequency)
Applies a first-order low-pass filter to the translation and spherical linear interpolation to the rotation of a transformation matrix which represents a Cartesian Motion.
Parameters
in sample_time Sample time constant
in y Current Cartesian transformation matrix to be filtered
in y_last Cartesian transformation matrix from the previous time step
in cutoff_frequency Cutoff frequency of the low-pass filter
Exceptions
std::invalid_argument if elements of y is infinite or NaN.
std::invalid_argument if elements of y_last is infinite or NaN.
std::invalid_argument if cutoff_frequency is zero, negative, infinite or NaN.
std::invalid_argument if sample_time is negative, infinite or NaN.
Returns
Filtered Cartesian transformation matrix.
Definition at line 28 of file lowpass_filter.cpp.
Referenced by franka::ControlLoop< T >::convertMotion().
                                                                       {
  if (sample_time < 0 || !std::isfinite(sample_time)) {
    throw std::invalid_argument(
        "Cartesian lowpass-filter: sample_time is negative, infinite or NaN.");
  }
  if (cutoff_frequency <= 0 || !std::isfinite(cutoff_frequency)) {
    throw std::invalid_argument(
        "Cartesian lowpass-filter: cutoff_frequency is zero, negative, infinite or NaN.");
  }
  for (size_t i = 0; i < y.size(); i++) {
    if (!std::isfinite(y[i]) || !std::isfinite(y_last[i])) {
      throw std::invalid_argument(
          "Cartesian lowpass-filter: current or past input value of the signal to be filtered is "
          "infinite or NaN.");
    }
  }
  Eigen::Affine3d transform(Eigen::Matrix4d::Map(y.data()));
  Eigen::Affine3d transform_last(Eigen::Matrix4d::Map(y_last.data()));
  Eigen::Quaterniond orientation(transform.linear());
  Eigen::Quaterniond orientation_last(transform_last.linear());
  double gain = sample_time / (sample_time + (1.0 / (2.0 * M_PI * cutoff_frequency)));
  transform.translation() =
      gain * transform.translation() + (1.0 - gain) * transform_last.translation();
  orientation = orientation_last.slerp(gain, orientation);
  transform.linear() << orientation.normalized().toRotationMatrix();
  std::array<double, 16> filtered_values{};
  Eigen::Map<Eigen::Matrix4d>(&filtered_values[0], 4, 4) = transform.matrix();
  return filtered_values;
}
combineCenterOfMass()
std::array< double, 3 > franka::combineCenterOfMass (double m_ee, const std::array< double, 3 > & F_x_Cee, double m_load, const std::array< double, 3 > & F_x_Cload)
Definition at line 7 of file load_calculations.cpp.
Referenced by convertRobotState().
                                          { // NOLINT(readability-identifier-naming)
  std::array<double, 3> F_x_Ctotal{}; // NOLINT(readability-identifier-naming)
  if ((m_ee + m_load) > 0) {
    for (size_t i = 0; i < F_x_Ctotal.size(); i++) {
      F_x_Ctotal[i] = (m_ee * F_x_Cee[i] + m_load * F_x_Cload[i]) / (m_ee + m_load);
    }
  }
  return F_x_Ctotal;
}
combineInertiaTensor()
std::array< double, 9 > franka::combineInertiaTensor (double m_ee, const std::array< double, 3 > & F_x_Cee, const std::array< double, 9 > & I_ee, double m_load, const std::array< double, 3 > & F_x_Cload, const std::array< double, 9 > & I_load, double m_total, const std::array< double, 3 > & F_x_Ctotal)
Definition at line 28 of file load_calculations.cpp.
References skewSymmetricMatrixFromVector().
Referenced by convertRobotState().
                                           { // NOLINT(readability-identifier-naming)
  // If the combined mass equals to zero, the combined inertia is also zero.
  if (m_total == 0) {
    return std::array<double, 9>{};
  }
  Eigen::Vector3d center_of_mass_ee(F_x_Cee.data());
  Eigen::Vector3d center_of_mass_load(F_x_Cload.data());
  Eigen::Vector3d center_of_mass_total(F_x_Ctotal.data());
  Eigen::Matrix3d inertia_ee(I_ee.data());
  Eigen::Matrix3d inertia_ee_flange = Eigen::Matrix3d::Zero();
  Eigen::Matrix3d inertia_load(I_load.data());
  Eigen::Matrix3d inertia_load_flange = Eigen::Matrix3d::Zero();
  Eigen::Matrix3d inertia_total_flange = Eigen::Matrix3d::Zero();
  // Check if the mass equals zero, the inertia should then be zero as well.
  if (m_ee == 0) {
    inertia_ee = Eigen::Matrix3d::Zero();
  }
  if (m_load == 0) {
    inertia_load = Eigen::Matrix3d::Zero();
  }
  // Calculate inertia tensor of EE and load in flange coordinates.
  inertia_ee_flange = inertia_ee - m_ee * (skewSymmetricMatrixFromVector(
      center_of_mass_ee) *
                                           skewSymmetricMatrixFromVector(
      center_of_mass_ee));
  inertia_load_flange =
      inertia_load - m_load * (skewSymmetricMatrixFromVector(
      center_of_mass_load) *
                               skewSymmetricMatrixFromVector(
      center_of_mass_load));
  // Calculate combined inertia tensor in flange coordinate.
  inertia_total_flange = inertia_ee_flange + inertia_load_flange;
  // Calculate combined inertia tensor in combined body center of mass coordinate.
  std::array<double, 9> I_total; // NOLINT(readability-identifier-naming)
  Eigen::Map<Eigen::Matrix3d> inertia_total(I_total.data(), 3, 3);
  inertia_total =
      inertia_total_flange + m_total * (skewSymmetricMatrixFromVector(
      center_of_mass_total) *
                                        skewSymmetricMatrixFromVector(
      center_of_mass_total));
  return I_total;
}
connect()
template<typename T , uint16_t kLibraryVersion>
void franka::connect (Network & network, uint16_t * ri_version)
Definition at line 258 of file network.h.
References franka::Network::tcpBlockingReceiveResponse(), franka::Network::tcpSendRequest(), and franka::Network::udpPort().
Referenced by testing::internal::XmlUnitTestResultPrinter::TestPropertiesAsXmlAttributes().
                                                     {
  uint32_t command_id = network.tcpSendRequest<T>(network.udpPort());
  typename T::Response connect_response = network.tcpBlockingReceiveResponse<T>(command_id);
  switch (connect_response.status) {
    case (T::Status::kIncompatibleLibraryVersion):
      throw IncompatibleVersionException(connect_response.version, kLibraryVersion);
    case (T::Status::kSuccess):
      *ri_version = connect_response.version;
      break;
    default:
      throw ProtocolException("libfranka: Protocol error during connection attempt");
  }
}
convertRobotState()
RobotState franka::convertRobotState (const research_interface::robot::RobotState & robot_state) [noexcept]
Definition at line 309 of file robot_impl.cpp.
References franka::RobotState::cartesian_collision, franka::RobotState::cartesian_contact, combineCenterOfMass(), combineInertiaTensor(), franka::RobotState::control_command_success_rate, franka::RobotState::current_errors, franka::RobotState::ddelbow_c, franka::RobotState::ddq_d, franka::RobotState::delbow_c, franka::RobotState::dq, franka::RobotState::dq_d, franka::RobotState::dtau_J, franka::RobotState::dtheta, franka::RobotState::EE_T_K, franka::RobotState::elbow, franka::RobotState::elbow_c, franka::RobotState::elbow_d, franka::RobotState::F_T_EE, franka::RobotState::F_x_Cee, franka::RobotState::F_x_Cload, franka::RobotState::F_x_Ctotal, franka::RobotState::I_ee, franka::RobotState::I_load, franka::RobotState::I_total, franka::RobotState::joint_collision, franka::RobotState::joint_contact, franka::RobotState::K_F_ext_hat_K, kAutomaticErrorRecovery, research_interface::robot::kAutomaticErrorRecovery, kGuiding, research_interface::robot::kGuiding, research_interface::robot::kIdle, kIdle, kMove, research_interface::robot::kMove, kOther, research_interface::robot::kOther, kReflex, research_interface::robot::kReflex, kUserStopped, research_interface::robot::kUserStopped, franka::RobotState::last_motion_errors, franka::RobotState::m_ee, franka::RobotState::m_load, franka::RobotState::m_total, franka::RobotState::O_ddP_EE_c, franka::RobotState::O_dP_EE_c, franka::RobotState::O_dP_EE_d, franka::RobotState::O_F_ext_hat_K, franka::RobotState::O_T_EE, franka::RobotState::O_T_EE_c, franka::RobotState::O_T_EE_d, franka::RobotState::q, franka::RobotState::q_d, franka::RobotState::robot_mode, franka::RobotState::tau_ext_hat_filtered, franka::RobotState::tau_J, franka::RobotState::tau_J_d, franka::RobotState::theta, and franka::RobotState::time.
Referenced by franka::Robot::Impl::readOnce(), and franka::Robot::Impl::update().
                                                                                            {
  RobotState converted;
  converted.O_T_EE = robot_state.O_T_EE;
  converted.O_T_EE_d = robot_state.O_T_EE_d;
  converted.F_T_EE = robot_state.F_T_EE;
  converted.EE_T_K = robot_state.EE_T_K;
  converted.m_ee = robot_state.m_ee;
  converted.F_x_Cee = robot_state.F_x_Cee;
  converted.I_ee = robot_state.I_ee;
  converted.m_load = robot_state.m_load;
  converted.F_x_Cload = robot_state.F_x_Cload;
  converted.I_load = robot_state.I_load;
  converted.m_total = robot_state.m_ee + robot_state.m_load;
  converted.F_x_Ctotal = combineCenterOfMass(robot_state.m_ee, robot_state.
      F_x_Cee,
                                             robot_state.m_load, robot_state.
      F_x_Cload);
  converted.I_total = combineInertiaTensor(
      robot_state.m_ee, robot_state.F_x_Cee, robot_state.I_ee, robot_state.
      m_load,
      robot_state.F_x_Cload, robot_state.I_load, converted.m_total, converted.F_x_Ctotal);
  converted.elbow = robot_state.elbow;
  converted.elbow_d = robot_state.elbow_d;
  converted.elbow_c = robot_state.elbow_c;
  converted.delbow_c = robot_state.delbow_c;
  converted.ddelbow_c = robot_state.ddelbow_c;
  converted.tau_J = robot_state.tau_J;
  converted.tau_J_d = robot_state.tau_J_d;
  converted.dtau_J = robot_state.dtau_J;
  converted.q = robot_state.q;
  converted.dq = robot_state.dq;
  converted.q_d = robot_state.q_d;
  converted.dq_d = robot_state.dq_d;
  converted.ddq_d = robot_state.ddq_d;
  converted.joint_contact = robot_state.joint_contact;
  converted.cartesian_contact = robot_state.cartesian_contact;
  converted.joint_collision = robot_state.joint_collision;
  converted.cartesian_collision = robot_state.cartesian_collision;
  converted.tau_ext_hat_filtered = robot_state.tau_ext_hat_filtered;
  converted.O_F_ext_hat_K = robot_state.O_F_ext_hat_K;
  converted.K_F_ext_hat_K = robot_state.K_F_ext_hat_K;
  converted.O_dP_EE_d = robot_state.O_dP_EE_d;
  converted.O_T_EE_c = robot_state.O_T_EE_c;
  converted.O_dP_EE_c = robot_state.O_dP_EE_c;
  converted.O_ddP_EE_c = robot_state.O_ddP_EE_c;
  converted.theta = robot_state.theta;
  converted.dtheta = robot_state.dtheta;
  converted.current_errors = robot_state.errors;
  converted.last_motion_errors = robot_state.reflex_reason;
  converted.control_command_success_rate = robot_state.
      control_command_success_rate;
  converted.time = Duration(robot_state.message_id);
  converted.robot_mode = RobotMode::kOther;
  switch (robot_state.robot_mode) {
    case research_interface::robot::RobotMode::kOther:
      converted.robot_mode = RobotMode::kOther;
      break;
    case research_interface::robot::RobotMode::kIdle:
      converted.robot_mode = RobotMode::kIdle;
      break;
    case research_interface::robot::RobotMode::kMove:
      converted.robot_mode = RobotMode::kMove;
      break;
    case research_interface::robot::RobotMode::kGuiding:
      converted.robot_mode = RobotMode::kGuiding;
      break;
    case research_interface::robot::RobotMode::kReflex:
      converted.robot_mode = RobotMode::kReflex;
      break;
    case research_interface::robot::RobotMode::kUserStopped
      :
      converted.robot_mode = RobotMode::kUserStopped;
      break;
    case research_interface::robot::RobotMode::kAutomaticErrorRecovery
      :
      converted.robot_mode = RobotMode::kAutomaticErrorRecovery;
      break;
  }
  return converted;
}
Duration::operator std::chrono::duration< uint64_t, std::milli >()
franka::Duration::operator std::chrono::duration< uint64_t, std::milli > () const [noexcept]
Definition at line 14 of file duration.cpp.
References franka::Duration::duration_.
                                                                        {
  return duration_;
}
hasRealtimeKernel()
bool franka::hasRealtimeKernel ()
Determines whether the current OS kernel is a realtime kernel.
On Linux, this checks for the existence of /sys/kernel/realtime. On Windows, this always returns true.
Returns
True if running a realtime kernel, false otherwise.
Definition at line 18 of file control_tools.cpp.
Referenced by franka::ControlLoop< T >::ControlLoop(), and isHomogeneousTransformation().
                         {
#ifdef LIBFRANKA_WINDOWS
  return true;
#else
  std::ifstream realtime("/sys/kernel/realtime", std::ios_base::in);
  bool is_realtime;
  realtime >> is_realtime;
  return is_realtime;
#endif
}
isHomogeneousTransformation()
bool franka::isHomogeneousTransformation (const std::array< double, 16 > & transform) [inline], [noexcept]
Determines whether the given array represents a valid homogeneous transformation matrix.
Parameters
in transform 4x4 matrix in column-major format.
Returns
True if the array represents a homogeneous transformation matrix, otherwise false.
Definition at line 33 of file control_tools.h.
References hasRealtimeKernel(), and setCurrentThreadToHighestSchedulerPriority().
Referenced by franka::anonymous_namespace{control_loop.cpp}::checkMatrix(), and limitRate().
                                                                                        {
  constexpr double kOrthonormalThreshold = 1e-5;
  if (transform[3] != 0.0 || transform[7] != 0.0 || transform[11] != 0.0 || transform[15] != 1.0) {
    return false;
  }
  for (size_t j = 0; j < 3; ++j) { // i..column
    if (std::abs(std::sqrt(std::pow(transform[j * 4 + 0], 2) + std::pow(transform[j * 4 + 1], 2) +
                           std::pow(transform[j * 4 + 2], 2)) -
                 1.0) > kOrthonormalThreshold) {
      return false;
    }
  }
  for (size_t i = 0; i < 3; ++i) { // j..row
    if (std::abs(std::sqrt(std::pow(transform[0 * 4 + i], 2) + std::pow(transform[1 * 4 + i], 2) +
                           std::pow(transform[2 * 4 + i], 2)) -
                 1.0) > kOrthonormalThreshold) {
      return false;
    }
  }
  return true;
}
isValidElbow()
bool franka::isValidElbow (const std::array< double, 2 > & elbow) [inline], [noexcept]
Determines whether the given elbow configuration is valid or not.
Parameters
in elbow Elbow configuration.
Returns
True if valid, otherwise false.
Definition at line 22 of file control_tools.h.
Referenced by franka::anonymous_namespace{control_loop.cpp}::checkElbow().
                                                                    {
  return elbow[1] == -1.0 || elbow[1] == 1.0;
}
limitRate() [1/7]
std::array< double, 7 > franka::limitRate (const std::array< double, 7 > & max_derivatives, const std::array< double, 7 > & commanded_values, const std::array< double, 7 > & last_commanded_values)
Limits the rate of an input vector of per-joint commands considering the maximum allowed time derivatives.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_derivatives Per-joint maximum allowed time derivative.
in commanded_values Commanded values of the current time step.
in last_commanded_values Commanded values of the previous time step.
Exceptions
std::invalid_argument if commanded_values are infinite or NaN.
Returns
Rate-limited vector of desired values.
Definition at line 59 of file rate_limiting.cpp.
References kDeltaT.
Referenced by franka::ControlLoop< T >::convertMotion(), limitRate(), main(), and franka::ControlLoop< T >::spinControl().
                                                                                  {
  if (!std::all_of(commanded_values.begin(), commanded_values.end(),
                   [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("Commanding value is infinite or NaN.");
  }
  std::array<double, 7> limited_values{};
  for (size_t i = 0; i < 7; i++) {
    double commanded_derivative = (commanded_values[i] - last_commanded_values[i]) /
      kDeltaT;
    limited_values[i] =
        last_commanded_values[i] +
        std::max(std::min(commanded_derivative, max_derivatives[i]), -max_derivatives[i]) *
      kDeltaT;
  }
  return limited_values;
}
limitRate() [2/7]
double franka::limitRate (double max_velocity, double max_acceleration, double max_jerk, double commanded_velocity, double last_commanded_velocity, double last_commanded_acceleration)
Limits the rate of a desired joint velocity considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_velocity Maximum allowed velocity.
in max_acceleration Maximum allowed acceleration.
in max_jerk Maximum allowed jerk.
in commanded_velocity Commanded joint velocity of the current time step.
in last_commanded_velocity Commanded joint velocitiy of the previous time step.
in last_commanded_acceleration Commanded joint acceleration of the previous time step.
Exceptions
std::invalid_argument if commanded_velocity is infinite or NaN.
Returns
Rate-limited desired joint velocity.
Definition at line 76 of file rate_limiting.cpp.
References kDeltaT.
                                                     {
  if (!std::isfinite(commanded_velocity)) {
    throw std::invalid_argument("commanded_velocity is infinite or NaN.");
  }
  // Differentiate to get jerk
  double commanded_jerk =
      (((commanded_velocity - last_commanded_velocity) / kDeltaT) - last_commanded_acceleration) /
      kDeltaT;
  // Limit jerk and integrate to get acceleration
  double commanded_acceleration = last_commanded_acceleration +
                                  std::max(std::min(commanded_jerk, max_jerk), -max_jerk) *
      kDeltaT;
  // Compute acceleration limits
  double safe_max_acceleration = std::min(
      (max_jerk / max_acceleration) * (max_velocity - last_commanded_velocity), max_acceleration);
  double safe_min_acceleration = std::max(
      (max_jerk / max_acceleration) * (-max_velocity - last_commanded_velocity), -max_acceleration);
  // Limit acceleration and integrate to get desired velocities
  return last_commanded_velocity +
         std::max(std::min(commanded_acceleration, safe_max_acceleration), safe_min_acceleration) *
             kDeltaT;
}
limitRate() [3/7]
double franka::limitRate (double max_velocity, double max_acceleration, double max_jerk, double commanded_position, double last_commanded_position, double last_commanded_velocity, double last_commanded_acceleration)
Limits the rate of a desired joint position considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_velocity Maximum allowed velocity.
in max_acceleration Maximum allowed acceleration.
in max_jerk Maximum allowed jerk.
in commanded_position Commanded joint position of the current time step.
in last_commanded_position Commanded joint position of the previous time step.
in last_commanded_velocity Commanded joint velocity of the previous time step.
in last_commanded_acceleration Commanded joint acceleration of the previous time step.
Exceptions
std::invalid_argument if commanded_position is infinite or NaN.
Returns
Rate-limited desired joint position.
Definition at line 106 of file rate_limiting.cpp.
References kDeltaT, and limitRate().
                                                     {
  if (!std::isfinite(commanded_position)) {
    throw std::invalid_argument("commanded_position is infinite or NaN.");
  }
  return last_commanded_position +
         limitRate(max_velocity, max_acceleration, max_jerk,
                   (commanded_position - last_commanded_position) / kDeltaT,
                   last_commanded_velocity, last_commanded_acceleration) *
             kDeltaT;
}
limitRate() [4/7]
std::array< double, 7 > franka::limitRate (const std::array< double, 7 > & max_velocity, const std::array< double, 7 > & max_acceleration, const std::array< double, 7 > & max_jerk, const std::array< double, 7 > & commanded_velocities, const std::array< double, 7 > & last_commanded_velocities, const std::array< double, 7 > & last_commanded_accelerations)
Limits the rate of a desired joint velocity considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_velocity Per-joint maximum allowed velocity.
in max_acceleration Per-joint maximum allowed acceleration.
in max_jerk Per-joint maximum allowed jerk.
in commanded_velocities Commanded joint velocity of the current time step.
in last_commanded_velocities Commanded joint velocities of the previous time step.
in last_commanded_accelerations Commanded joint accelerations of the previous time step.
Exceptions
std::invalid_argument if commanded_velocities are infinite or NaN.
Returns
Rate-limited vector of desired joint velocities.
Definition at line 123 of file rate_limiting.cpp.
References limitRate().
                                                                                         {
  if (!std::all_of(commanded_velocities.begin(), commanded_velocities.end(),
                   [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("commanded_velocities is infinite or NaN.");
  }
  std::array<double, 7> limited_commanded_velocities{};
  for (size_t i = 0; i < 7; i++) {
    limited_commanded_velocities[i] =
        limitRate(max_velocity[i], max_acceleration[i], max_jerk[i], commanded_velocities[i],
                  last_commanded_velocities[i], last_commanded_accelerations[i]);
  }
  return limited_commanded_velocities;
}
limitRate() [5/7]
std::array< double, 7 > franka::limitRate (const std::array< double, 7 > & max_velocity, const std::array< double, 7 > & max_acceleration, const std::array< double, 7 > & max_jerk, const std::array< double, 7 > & commanded_positions, const std::array< double, 7 > & last_commanded_positions, const std::array< double, 7 > & last_commanded_velocities, const std::array< double, 7 > & last_commanded_accelerations)
Limits the rate of a desired joint position considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_velocity Per-joint maximum allowed velocity.
in max_acceleration Per-joint maximum allowed velocity.
in max_jerk Per-joint maximum allowed velocity.
in commanded_positions Per-joint maximum allowed acceleration.
in last_commanded_positions Commanded joint positions of the current time step.
in last_commanded_velocities Commanded joint positions of the previous time step.
in last_commanded_accelerations Commanded joint velocities of the previous time step.
Exceptions
std::invalid_argument if commanded_positions are infinite or NaN.
Returns
Rate-limited vector of desired joint positions.
Definition at line 143 of file rate_limiting.cpp.
References limitRate().
                                                                                         {
  if (!std::all_of(commanded_positions.begin(), commanded_positions.end(),
                   [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("commanded_positions is infinite or NaN.");
  }
  std::array<double, 7> limited_commanded_positions{};
  for (size_t i = 0; i < 7; i++) {
    limited_commanded_positions[i] = limitRate(
        max_velocity[i], max_acceleration[i], max_jerk[i], commanded_positions[i],
        last_commanded_positions[i], last_commanded_velocities[i], last_commanded_accelerations[i]);
  }
  return limited_commanded_positions;
}
limitRate() [6/7]
std::array< double, 6 > franka::limitRate (double max_translational_velocity, double max_translational_acceleration, double max_translational_jerk, double max_rotational_velocity, double max_rotational_acceleration, double max_rotational_jerk, const std::array< double, 6 > & O_dP_EE_c, const std::array< double, 6 > & last_O_dP_EE_c, const std::array< double, 6 > & last_O_ddP_EE_c)
Limits the rate of a desired Cartesian velocity considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_translational_velocity Maximum translational velocity.
in max_translational_acceleration Maximum translational acceleration.
in max_translational_jerk Maximum translational jerk.
in max_rotational_velocity Maximum rotational velocity.
in max_rotational_acceleration Maximum rotational acceleration.
in max_rotational_jerk Maximum rotational jerk.
in O_dP_EE_c Commanded end effector twist of the current time step.
in last_O_dP_EE_c Commanded end effector twist of the previous time step.
in last_O_ddP_EE_c Commanded end effector acceleration of the previous time step.
Exceptions
std::invalid_argument if an element of O_dP_EE_c is infinite or NaN.
Returns
Rate-limited desired end effector twist.
Definition at line 163 of file rate_limiting.cpp.
References limitRate().
                                                { // NOLINT(readability-identifier-naming)
  if (!std::all_of(O_dP_EE_c.begin(), O_dP_EE_c.end(), [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("O_dP_EE_c is infinite or NaN.");
  }
  Eigen::Matrix<double, 6, 1> dx(O_dP_EE_c.data());
  Eigen::Matrix<double, 6, 1> last_dx(last_O_dP_EE_c.data());
  Eigen::Matrix<double, 6, 1> last_ddx(last_O_ddP_EE_c.data());
  dx.head(3) << limitRate(max_translational_velocity, max_translational_acceleration,
                          max_translational_jerk, dx.head(3), last_dx.head(3), last_ddx.head(3));
  dx.tail(3) << limitRate(max_rotational_velocity, max_rotational_acceleration,
      max_rotational_jerk,
                          dx.tail(3), last_dx.tail(3), last_ddx.tail(3));
  std::array<double, 6> limited_values{};
  Eigen::Map<Eigen::Matrix<double, 6, 1>>(&limited_values[0], 6, 1) = dx;
  return limited_values;
}
limitRate() [7/7]
std::array< double, 16 > franka::limitRate (double max_translational_velocity, double max_translational_acceleration, double max_translational_jerk, double max_rotational_velocity, double max_rotational_acceleration, double max_rotational_jerk, const std::array< double, 16 > & O_T_EE_c, const std::array< double, 16 > & last_O_T_EE_c, const std::array< double, 6 > & last_O_dP_EE_c, const std::array< double, 6 > & last_O_ddP_EE_c)
Limits the rate of a desired Cartesian pose considering the limits provided.
Note
FCI filters must be deactivated to work properly.
Parameters
in max_translational_velocity Maximum translational velocity.
in max_translational_acceleration Maximum translational acceleration.
in max_translational_jerk Maximum translational jerk.
in max_rotational_velocity Maximum rotational velocity.
in max_rotational_acceleration Maximum rotational acceleration.
in max_rotational_jerk Maximum rotational jerk.
in O_T_EE_c Commanded pose of the current time step.
in last_O_T_EE_c Commanded pose of the previous time step.
in last_O_dP_EE_c Commanded end effector twist of the previous time step.
in last_O_ddP_EE_c Commanded end effector acceleration of the previous time step.
Exceptions
std::invalid_argument if an element of O_T_EE_c is infinite or NaN.
Returns
Rate-limited desired pose.
Definition at line 190 of file rate_limiting.cpp.
References isHomogeneousTransformation(), kDeltaT, kFactorCartesianRotationPoseInterface, kNormEps, and limitRate().
                                                { // NOLINT(readability-identifier-naming)
  if (!std::all_of(O_T_EE_c.begin(), O_T_EE_c.end(), [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("O_T_EE_c is infinite or NaN.");
  }
  if (!isHomogeneousTransformation(O_T_EE_c)) {
    throw std::invalid_argument(
        "O_T_EE_c is invalid transformation matrix. Has to be column major!");
  }
  Eigen::Matrix<double, 6, 1> dx;
  Eigen::Affine3d commanded_pose(Eigen::Matrix4d::Map(O_T_EE_c.data()));
  Eigen::Affine3d limited_commanded_pose = Eigen::Affine3d::Identity();
  Eigen::Affine3d last_commanded_pose(Eigen::Matrix4d::Map(last_O_T_EE_c.data()));
  // Compute translational velocity
  dx.head(3) << (commanded_pose.translation() - last_commanded_pose.translation()) /
      kDeltaT;
  // Compute rotational velocity
  Eigen::AngleAxisd rot_difference(commanded_pose.linear() *
                                   last_commanded_pose.linear().transpose());
  dx.tail(3) << rot_difference.axis() * rot_difference.angle() / kDeltaT;
  // Limit the rate of the twist
  std::array<double, 6> commanded_O_dP_EE_c{}; // NOLINT(readability-identifier-naming)
  Eigen::Map<Eigen::Matrix<double, 6, 1>>(&commanded_O_dP_EE_c[0], 6, 1) = dx;
  commanded_O_dP_EE_c =
      limitRate(max_translational_velocity, max_translational_acceleration, max_translational_jerk
      ,
                kFactorCartesianRotationPoseInterface *
      max_rotational_velocity,
                kFactorCartesianRotationPoseInterface *
      max_rotational_acceleration,
                kFactorCartesianRotationPoseInterface *
      max_rotational_jerk, commanded_O_dP_EE_c,
                last_O_dP_EE_c, last_O_ddP_EE_c);
  dx = Eigen::Matrix<double, 6, 1>(commanded_O_dP_EE_c.data());
  // Integrate limited twist
  limited_commanded_pose.translation() << last_commanded_pose.translation() + dx.head(3) *
      kDeltaT;
  limited_commanded_pose.linear() << last_commanded_pose.linear();
  if (dx.tail(3).norm() > kNormEps) {
    Eigen::Matrix3d omega_skew;
    Eigen::Vector3d w_norm(dx.tail(3) / dx.tail(3).norm());
    double theta = kDeltaT * dx.tail(3).norm();
    omega_skew << 0, -w_norm(2), w_norm(1), w_norm(2), 0, -w_norm(0), -w_norm(1), w_norm(0), 0;
    // NOLINTNEXTLINE(readability-identifier-naming)
    Eigen::Matrix3d R = Eigen::Matrix3d::Identity() + sin(theta) * omega_skew +
                        (1.0 - cos(theta)) * (omega_skew * omega_skew);
    limited_commanded_pose.linear() << R * last_commanded_pose.linear();
  }
  std::array<double, 16> limited_values{};
  Eigen::Map<Eigen::Matrix4d>(&limited_values[0], 4, 4) = limited_commanded_pose.matrix();
  return limited_values;
}
logToCSV()
std::string franka::logToCSV (const std::vector< Record > & log)
Writes the log to a string in CSV format. If the string is not empty, the first row contains the header with names of columns. The following lines contain rows of values separated by commas.
If the log is empty, the function returns an empty string.
Parameters
in log Log provided by the ControlException.
Returns
a string in CSV format, or empty string.
Definition at line 70 of file log.cpp.
References franka::anonymous_namespace{log.cpp}::csvLine(), franka::anonymous_namespace{log.cpp}::csvRobotCommandHeader(), franka::anonymous_namespace{log.cpp}::csvRobotStateHeader(), and fake_cube_perception_node::r.
Referenced by writeLogToFile().
                                                 {
  if (log.empty()) {
    return "";
  }
  std::ostringstream os;
  os << csvRobotStateHeader() << "," << csvRobotCommandHeader() <<
      std::endl;
  for (const Record& r : log) {
    os << csvLine(r.state) << ",," << csvLine(r.command) << std::endl;
  }
  return os.str();
}
lowpassFilter()
double franka::lowpassFilter (double sample_time, double y, double y_last, double cutoff_frequency)
Applies a first-order low-pass filter
Parameters
in sample_time Sample time constant
in y Current value of the signal to be filtered
in y_last Value of the signal to be filtered in the previous time step
in cutoff_frequency Cutoff frequency of the low-pass filter
Exceptions
std::invalid_argument if y is infinite or NaN.
std::invalid_argument if y_last is infinite or NaN.
std::invalid_argument if cutoff_frequency is zero, negative, infinite or NaN.
std::invalid_argument if sample_time is negative, infinite or NaN.
Returns
Filtered value.
Definition at line 11 of file lowpass_filter.cpp.
Referenced by franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::spinControl().
                                                                                           {
  if (sample_time < 0 || !std::isfinite(sample_time)) {
    throw std::invalid_argument("lowpass-filter: sample_time is negative, infinite or NaN.");
  }
  if (cutoff_frequency <= 0 || !std::isfinite(cutoff_frequency)) {
    throw std::invalid_argument(
        "lowpass-filter: cutoff_frequency is zero, negative, infinite or NaN.");
  }
  if (!std::isfinite(y) || !std::isfinite(y_last)) {
    throw std::invalid_argument(
        "lowpass-filter: current or past input value of the signal to be filtered is infinite or "
        "NaN.");
  }
  double gain = sample_time / (sample_time + (1.0 / (2.0 * M_PI * cutoff_frequency)));
  return gain * y + (1 - gain) * y_last;
}
MotionFinished() [1/5]
Torques franka::MotionFinished (Torques command) [inline], [noexcept]
Helper method to indicate that a motion should stop after processing the given command.
Parameters
in command Last command to be executed before the motion terminates.
Returns
Command with motion_finished set to true.
See also
Documentation on callbacks
Definition at line 275 of file control_types.h.
References franka::Finishable::motion_finished.
Referenced by franka_hw::FrankaHW::controlCallback(), and main().
                                                        { // NOLINT(readability-identifier-naming)
  command.motion_finished = true;
  return command;
}
MotionFinished() [2/5]
JointPositions franka::MotionFinished (JointPositions command) [inline], [noexcept]
Helper method to indicate that a motion should stop after processing the given command.
Parameters
in command Last command to be executed before the motion terminates.
Returns
Command with motion_finished set to true.
See also
Documentation on callbacks
Definition at line 289 of file control_types.h.
References franka::Finishable::motion_finished.
                                     {
  command.motion_finished = true;
  return command;
}
MotionFinished() [3/5]
JointVelocities franka::MotionFinished (JointVelocities command) [inline], [noexcept]
Helper method to indicate that a motion should stop after processing the given command.
Parameters
in command Last command to be executed before the motion terminates.
Returns
Command with motion_finished set to true.
See also
Documentation on callbacks
Definition at line 304 of file control_types.h.
References franka::Finishable::motion_finished.
                                      {
  command.motion_finished = true;
  return command;
}
MotionFinished() [4/5]
CartesianPose franka::MotionFinished (CartesianPose command) [inline], [noexcept]
Helper method to indicate that a motion should stop after processing the given command.
Parameters
in command Last command to be executed before the motion terminates.
Returns
Command with motion_finished set to true.
See also
Documentation on callbacks
Definition at line 319 of file control_types.h.
References franka::Finishable::motion_finished.
                                    {
  command.motion_finished = true;
  return command;
}
MotionFinished() [5/5]
CartesianVelocities franka::MotionFinished (CartesianVelocities command) [inline], [noexcept]
Helper method to indicate that a motion should stop after processing the given command.
Parameters
in command Last command to be executed before the motion terminates.
Returns
Command with motion_finished set to true.
See also
Documentation on callbacks
Definition at line 334 of file control_types.h.
References franka::Finishable::motion_finished.
                                          {
  command.motion_finished = true;
  return command;
}
operator*()
Duration franka::operator* (uint64_t lhs, const Duration & rhs) [noexcept]
Performs multiplication.
Parameters
in lhs Left-hand side of the multiplication.
in rhs Right-hand side of the multiplication.
Returns
Result of the multiplication.
Definition at line 108 of file duration.cpp.
                                                               {
  return rhs * lhs;
}
operator++()
Frame franka::operator++ (Frame & frame, int) [noexcept]
Post-increments the given Frame by one.
For example, Frame::kJoint2++ results in Frame::kJoint3.
Parameters
in frame Frame to increment.
Returns
Original Frame.
Definition at line 18 of file model.cpp.
                                               {
  Frame original = frame;
  frame = static_cast<Frame>(static_cast<std::underlying_type_t<Frame>>(frame) + 1);
  return original;
}
operator<<() [1/3]
std::ostream & franka::operator<< (std::ostream & ostream, const franka::GripperState & gripper_state)
Streams the gripper state as JSON object: {`field_name_1`: value, `field_name_2`: value, ...}
Parameters
in ostream Ostream instance
in gripper_state GripperState struct instance to stream
Returns
Ostream instance
Definition at line 9 of file gripper_state.cpp.
References franka::GripperState::is_grasped, franka::GripperState::max_width, franka::GripperState::temperature, franka::GripperState::time, franka::Duration::toSec(), and franka::GripperState::width.
                                                                                     {
  ostream << "{\"width\": " << gripper_state.width << ", \"max_width\": " << gripper_state.
      max_width
          << ", \"is_grasped\": " << gripper_state.is_grasped
          << ", \"temperature\": " << gripper_state.temperature
          << ", \"time\": " << gripper_state.time.toSec() << "}";
  return ostream;
}
operator<<() [2/3]
std::ostream & franka::operator<< (std::ostream & ostream, const Errors & errors)
Streams the errors as JSON array.
Parameters
in ostream Ostream instance
in errors Errors struct instance to stream
Returns
Ostream instance
Definition at line 119 of file errors.cpp.
                                                                  {
  ostream << static_cast<std::string>(errors);
  return ostream;
}
operator<<() [3/3]
std::ostream & franka::operator<< (std::ostream & ostream, const franka::RobotState & robot_state)
Streams the robot state as JSON object: {`field_name_1`: [0,0,0,0,0,0,0], `field_name_2`: [0,0,0,0,0,0], ...}
Parameters
in ostream Ostream instance
in robot_state RobotState instance to stream
Returns
Ostream instance
Definition at line 53 of file robot_state.cpp.
References franka::RobotState::cartesian_collision, franka::RobotState::cartesian_contact, franka::RobotState::control_command_success_rate, franka::RobotState::current_errors, franka::RobotState::ddelbow_c, franka::RobotState::ddq_d, franka::RobotState::delbow_c, franka::RobotState::dq, franka::RobotState::dq_d, franka::RobotState::dtau_J, franka::RobotState::dtheta, franka::RobotState::EE_T_K, franka::RobotState::elbow, franka::RobotState::elbow_c, franka::RobotState::elbow_d, franka::RobotState::F_T_EE, franka::RobotState::F_x_Cee, franka::RobotState::F_x_Cload, franka::RobotState::F_x_Ctotal, franka::RobotState::I_ee, franka::RobotState::I_load, franka::RobotState::I_total, franka::RobotState::joint_collision, franka::RobotState::joint_contact, franka::RobotState::K_F_ext_hat_K, franka::RobotState::last_motion_errors, franka::RobotState::m_ee, franka::RobotState::m_load, franka::RobotState::m_total, franka::RobotState::O_ddP_EE_c, franka::RobotState::O_dP_EE_c, franka::RobotState::O_dP_EE_d, franka::RobotState::O_F_ext_hat_K, franka::RobotState::O_T_EE, franka::RobotState::O_T_EE_c, franka::RobotState::O_T_EE_d, franka::RobotState::q, franka::RobotState::q_d, franka::RobotState::robot_mode, franka::RobotState::tau_ext_hat_filtered, franka::RobotState::tau_J, franka::RobotState::tau_J_d, franka::RobotState::theta, franka::RobotState::time, and franka::Duration::toMSec().
                                                                                 {
  ostream << "{\"O_T_EE\": " << robot_state.O_T_EE << ", \"O_T_EE_d\": " << robot_state.
      O_T_EE_d
          << ", \"F_T_EE\": " << robot_state.F_T_EE << ", \"EE_T_K\": " << robot_state.
      EE_T_K
          << ", \"m_ee\": " << robot_state.m_ee << ", \"F_x_Cee\": " << robot_state.
      F_x_Cee
          << ", \"I_ee\": " << robot_state.I_ee << ", \"m_load\": " << robot_state.
      m_load
          << ", \"F_x_Cload\": " << robot_state.F_x_Cload << ", \"I_load\": " << robot_state.
      I_load
          << ", \"m_total\": " << robot_state.m_total
          << ", \"F_x_Ctotal\": " << robot_state.F_x_Ctotal
          << ", \"I_total\": " << robot_state.I_total << ", \"elbow\": " << robot_state.
      elbow
          << ", \"elbow_d\": " << robot_state.elbow_d << ", \"elbow_c\": " << robot_state.
      elbow_c
          << ", \"delbow_c\": " << robot_state.delbow_c
          << ", \"ddelbow_c\": " << robot_state.ddelbow_c << ", \"tau_J\": " << robot_state.
      tau_J
          << ", \"tau_J_d\": " << robot_state.tau_J_d << ", \"dtau_J\": " << robot_state.
      dtau_J
          << ", \"q\": " << robot_state.q << ", \"dq\": " << robot_state.dq
          << ", \"q_d\": " << robot_state.q_d << ", \"dq_d\": " << robot_state.
      dq_d
          << ", \"ddq_d\": " << robot_state.ddq_d
          << ", \"joint_contact\": " << robot_state.joint_contact
          << ", \"cartesian_contact\": " << robot_state.cartesian_contact
          << ", \"joint_collision\": " << robot_state.joint_collision
          << ", \"cartesian_collision\": " << robot_state.cartesian_collision
          << ", \"tau_ext_hat_filtered\": " << robot_state.tau_ext_hat_filtered
          << ", \"O_F_ext_hat_K\": " << robot_state.O_F_ext_hat_K
          << ", \"K_F_ext_hat_K\": " << robot_state.K_F_ext_hat_K
          << ", \"O_dP_EE_d\": " << robot_state.O_dP_EE_d
          << ", \"O_T_EE_c\": " << robot_state.O_T_EE_c
          << ", \"O_dP_EE_c\": " << robot_state.O_dP_EE_c
          << ", \"O_ddP_EE_c\": " << robot_state.O_ddP_EE_c << ", \"theta\": " << robot_state.
      theta
          << ", \"dtheta\": " << robot_state.dtheta
          << ", \"current_errors\": " << robot_state.current_errors
          << ", \"last_motion_errors\": " << robot_state.last_motion_errors
          << ", \"control_command_success_rate\": " << robot_state.
      control_command_success_rate
          << ", \"robot_mode\": " << robot_state.robot_mode
          << ", \"time\": " << robot_state.time.toMSec() << "}";
  return ostream;
}
Robot::Impl::executeCommand< research_interface::robot::GetCartesianLimit, int32_t, VirtualWallCuboid * >()
template<>
uint32_t franka::Robot::Impl::executeCommand< research_interface::robot::GetCartesianLimit, int32_t, VirtualWallCuboid *> (int32_t id, VirtualWallCuboid * virtual_wall_cuboid) [inline]
Definition at line 274 of file robot_impl.h.
References franka::Robot::Impl::network_.
                                                {
  using research_interface::robot::GetCartesianLimit;
  uint32_t command_id = network_->tcpSendRequest<GetCartesianLimit>(id);
  GetCartesianLimit::Response response =
      network_->tcpBlockingReceiveResponse<GetCartesianLimit>(command_id);
  virtual_wall_cuboid->p_frame = response.object_frame;
  virtual_wall_cuboid->object_world_size = response.object_world_size;
  virtual_wall_cuboid->active = response.object_activation;
  virtual_wall_cuboid->id = id;
  handleCommandResponse<GetCartesianLimit>(response);
  return command_id;
}
Robot::Impl::handleCommandResponse< research_interface::robot::AutomaticErrorRecovery >()
template<>
void franka::Robot::Impl::handleCommandResponse< research_interface::robot::AutomaticErrorRecovery > (const research_interface::robot::AutomaticErrorRecovery::Response & response) const [inline]
Definition at line 223 of file robot_impl.h.
References research_interface::robot::AutomaticErrorRecovery::kAborted, research_interface::robot::AutomaticErrorRecovery::kCommandNotPossibleRejected, research_interface::robot::AutomaticErrorRecovery::kEmergencyAborted, research_interface::robot::AutomaticErrorRecovery::kManualErrorRecoveryRequiredRejected, research_interface::robot::AutomaticErrorRecovery::kReflexAborted, research_interface::robot::AutomaticErrorRecovery::kSuccess, and service_node_3::s.
                                                                                 {
  using namespace std::string_literals; // NOLINT(google-build-using-namespace)
  switch (response.status) {
    case research_interface::robot::AutomaticErrorRecovery::Status::kSuccess
      :
      break;
    case
      research_interface::robot::AutomaticErrorRecovery::Status::kEmergencyAborted
      :
      throw CommandException("libfranka: "s +
                             research_interface::robot::CommandTraits
      <
                                 
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                             " command aborted: User Stop pressed!");
    case
      research_interface::robot::AutomaticErrorRecovery::Status::kReflexAborted
      :
      throw CommandException("libfranka: "s +
                             research_interface::robot::CommandTraits
      <
                                 
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                             " command aborted: motion aborted by reflex!");
    case
      research_interface::robot::AutomaticErrorRecovery::Status::kCommandNotPossibleRejected
      :
      throw CommandException("libfranka: "s +
                             research_interface::robot::CommandTraits
      <
                                 
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                             " command rejected: command not possible in the current mode!");
    case research_interface::robot::AutomaticErrorRecovery::Status::
        kManualErrorRecoveryRequiredRejected:
      throw CommandException("libfranka: "s +
                             research_interface::robot::CommandTraits
      <
                                 
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                             " command rejected: manual error recovery required!");
    case research_interface::robot::AutomaticErrorRecovery::Status::kAborted
      :
      throw CommandException("libfranka: "s +
                             research_interface::robot::CommandTraits
      <
                                 
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                             " command aborted!");
    default:
      throw ProtocolException("libfranka: Unexpected response while handling "s +
                              research_interface::robot::CommandTraits
      <
                                  
      research_interface::robot::AutomaticErrorRecovery>::kName
      +
                              " command!");
  }
}
Robot::Impl::handleCommandResponse< research_interface::robot::Move >()
template<>
void franka::Robot::Impl::handleCommandResponse< research_interface::robot::Move > (const research_interface::robot::Move::Response & response) const [inline]
Definition at line 123 of file robot_impl.h.
References research_interface::robot::Move::kAborted, research_interface::robot::Move::kCommandNotPossibleRejected, research_interface::robot::Move::kEmergencyAborted, research_interface::robot::Move::kInputErrorAborted, research_interface::robot::Move::kInvalidArgumentRejected, research_interface::robot::Move::kMotionStarted, research_interface::robot::Move::kPreempted, research_interface::robot::Move::kReflexAborted, research_interface::robot::Move::kStartAtSingularPoseRejected, research_interface::robot::Move::kSuccess, franka::Robot::Impl::motionGeneratorRunning(), and service_node_3::s.
                                                               {
  using namespace std::string_literals; // NOLINT(google-build-using-namespace)
  switch (response.status) {
    case research_interface::robot::Move::Status::kSuccess
      :
      break;
    case research_interface::robot::Move::Status::kMotionStarted
      :
      if (motionGeneratorRunning()) {
        throw ProtocolException(
            "libfranka: "s +
            
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
            " received unexpected motion started message.");
      }
      break;
    case research_interface::robot::Move::Status::kEmergencyAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command aborted: User Stop pressed!");
    case research_interface::robot::Move::Status::kReflexAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command aborted: motion aborted by reflex!");
    case research_interface::robot::Move::Status::kInputErrorAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command aborted: invalid input provided!");
    case research_interface::robot::Move::Status::kCommandNotPossibleRejected
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command rejected: command not possible in the current mode!");
    case research_interface::robot::Move::Status::kStartAtSingularPoseRejected
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command rejected: cannot start at singular pose!");
    case research_interface::robot::Move::Status::kInvalidArgumentRejected
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command rejected: maximum path deviation out of range!");
    case research_interface::robot::Move::Status::kPreempted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command preempted!");
    case research_interface::robot::Move::Status::kAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command aborted!");
    default:
      throw ProtocolException(
          "libfranka: Unexpected response while handling "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::Move>::kName
       +
          " command!");
  }
}
Robot::Impl::handleCommandResponse< research_interface::robot::StopMove >()
template<>
void franka::Robot::Impl::handleCommandResponse< research_interface::robot::StopMove > (const research_interface::robot::StopMove::Response & response) const [inline]
Definition at line 187 of file robot_impl.h.
References research_interface::robot::StopMove::kAborted, research_interface::robot::StopMove::kCommandNotPossibleRejected, research_interface::robot::StopMove::kEmergencyAborted, research_interface::robot::StopMove::kReflexAborted, research_interface::robot::StopMove::kSuccess, and service_node_3::s.
                                                                   {
  using namespace std::string_literals; // NOLINT(google-build-using-namespace)
  switch (response.status) {
    case research_interface::robot::StopMove::Status::kSuccess
      :
      break;
    case
      research_interface::robot::StopMove::Status::kCommandNotPossibleRejected
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::StopMove>::kName
       +
          " command rejected: command not possible in the current mode!");
    case research_interface::robot::StopMove::Status::kAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::StopMove>::kName
       +
          " command rejected: command not possible in the current mode!");
    case research_interface::robot::StopMove::Status::kEmergencyAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::StopMove>::kName
       +
          " command aborted: User Stop pressed!");
    case research_interface::robot::StopMove::Status::kReflexAborted
      :
      throw CommandException(
          "libfranka: "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::StopMove>::kName
       +
          " command aborted: motion aborted by reflex!");
    default:
      throw ProtocolException(
          "libfranka: Unexpected response while handling "s +
          
      research_interface::robot::CommandTraits<research_interface::robot::StopMove>::kName
       +
          " command!");
  }
}
setCurrentThreadToHighestSchedulerPriority()
bool franka::setCurrentThreadToHighestSchedulerPriority (std::string * error_message)
Sets the current thread to the highest possible scheduler priority.
Parameters
out error_message Contains an error message if the scheduler priority cannot be set successfully.
Returns
True if successful, false otherwise.
Definition at line 29 of file control_tools.cpp.
References service_node_3::s.
Referenced by franka::ControlLoop< T >::ControlLoop(), and isHomogeneousTransformation().
                                                                          {
#ifdef LIBFRANKA_WINDOWS
  auto get_last_windows_error = []() -> std::string {
    DWORD error_id = GetLastError();
    LPSTR buffer = nullptr;
    size_t size = FormatMessageA(
        FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
        nullptr, error_id, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPSTR)(&buffer), 0, nullptr);
    return std::string(buffer, size);
  };
  if (!SetPriorityClass(GetCurrentProcess(), REALTIME_PRIORITY_CLASS)) {
    if (error_message != nullptr) {
      *error_message =
          "libfranka: unable to set priority for the process: "s + get_last_windows_error();
    }
    return false;
  }
  if (!SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL)) {
    if (error_message != nullptr) {
      *error_message =
          "libfranka: unable to set priority for the thread: "s + get_last_windows_error();
    }
    return false;
  }
  return true;
#else
  const int thread_priority = sched_get_priority_max(SCHED_FIFO);
  if (thread_priority == -1) {
    if (error_message != nullptr) {
      *error_message =
          "libfranka: unable to get maximum possible thread priority: "s + std::strerror(errno);
    }
    return false;
  }
  sched_param thread_param{};
  thread_param.sched_priority = thread_priority;
  if (pthread_setschedparam(pthread_self(), SCHED_FIFO, &thread_param) != 0) {
    if (error_message != nullptr) {
      *error_message = "libfranka: unable to set realtime scheduling: "s + std::strerror(errno);
    }
    return false;
  }
  return true;
#endif
}
skewSymmetricMatrixFromVector()
Eigen::Matrix3d franka::skewSymmetricMatrixFromVector (const Eigen::Vector3d & input)
Definition at line 22 of file load_calculations.cpp.
Referenced by combineInertiaTensor().
                                                                        {
  Eigen::Matrix3d input_hat;
  input_hat << 0, -input(2), input(1), input(2), 0, -input(0), -input(1), input(0), 0;
  return input_hat;
}
Variable Documentation
kDefaultCutoffFrequency
constexpr double franka::kDefaultCutoffFrequency = 100.0
Default cutoff frequency
Definition at line 21 of file lowpass_filter.h.
kDeltaT
constexpr double franka::kDeltaT = 1e-3
Sample time constant
Definition at line 18 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion(), franka::anonymous_namespace{rate_limiting.cpp}::limitRate(), limitRate(), and franka::ControlLoop< T >::spinControl().
kFactorCartesianRotationPoseInterface
constexpr double franka::kFactorCartesianRotationPoseInterface = 0.99
Factor for the definition of rotational limits using the Cartesian Pose interface
Definition at line 35 of file rate_limiting.h.
Referenced by limitRate().
kLimitEps
constexpr double franka::kLimitEps = 1e-3
Epsilon value for checking limits
Definition at line 22 of file rate_limiting.h.
kMaxCutoffFrequency
constexpr double franka::kMaxCutoffFrequency = 1000.0
Maximum cutoff frequency
Definition at line 17 of file lowpass_filter.h.
Referenced by franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::spinControl().
kMaxElbowAcceleration
constexpr double franka::kMaxElbowAcceleration = 10.0000 - kLimitEps
Maximum elbow acceleration
Definition at line 98 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxElbowJerk
constexpr double franka::kMaxElbowJerk = 5000 - kLimitEps
Maximum elbow jerk
Definition at line 94 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxElbowVelocity
constexpr double franka::kMaxElbowVelocity
Initial value:
=
    2.1750 - kLimitEps - kTolNumberPacketsLost *
      kDeltaT * kMaxElbowAcceleration
Maximum elbow velocity
Definition at line 102 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxJointAcceleration
constexpr std::array<double, 7> franka::kMaxJointAcceleration
Initial value:
{
    {15.0000 - kLimitEps, 7.500 - kLimitEps, 10.0000 -
      kLimitEps, 12.5000 - kLimitEps,
     15.0000 - kLimitEps, 20.0000 - kLimitEps, 20.0000 -
      kLimitEps}}
Maximum joint acceleration
Definition at line 51 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxJointJerk
constexpr std::array<double, 7> franka::kMaxJointJerk
Initial value:
{
    {7500.0 - kLimitEps, 3750.0 - kLimitEps, 5000.0 -
      kLimitEps, 6250.0 - kLimitEps,
     7500.0 - kLimitEps, 10000.0 - kLimitEps, 10000.0 -
      kLimitEps}}
Maximum joint jerk
Definition at line 45 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxJointVelocity
constexpr std::array<double, 7> franka::kMaxJointVelocity
Initial value:
{
    {2.1750 - kLimitEps - kTolNumberPacketsLost *
      kDeltaT * kMaxJointAcceleration[0],
     2.1750 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[1],
     2.1750 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[2],
     2.1750 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[3],
     2.6100 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[4],
     2.6100 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[5],
     2.6100 - kLimitEps - kTolNumberPacketsLost*
      kDeltaT* kMaxJointAcceleration[6]}}
Maximum joint velocity
Definition at line 57 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxRotationalAcceleration
constexpr double franka::kMaxRotationalAcceleration = 25.0000 - kLimitEps
Maximum rotational acceleration
Definition at line 85 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxRotationalJerk
constexpr double franka::kMaxRotationalJerk = 12500.0 - kLimitEps
Maximum rotational jerk
Definition at line 81 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxRotationalVelocity
constexpr double franka::kMaxRotationalVelocity
Initial value:
=
    2.5000 - kLimitEps - kTolNumberPacketsLost *
      kDeltaT * kMaxRotationalAcceleration
Maximum rotational velocity
Definition at line 89 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxTorqueRate
constexpr std::array<double, 7> franka::kMaxTorqueRate
Initial value:
{
    {1000 - kLimitEps, 1000 - kLimitEps, 1000 - kLimitEps, 1000 -
      kLimitEps, 1000 - kLimitEps,
     1000 - kLimitEps, 1000 - kLimitEps}}
Maximum torque rate
Definition at line 39 of file rate_limiting.h.
Referenced by main(), and franka::ControlLoop< T >::spinControl().
kMaxTranslationalAcceleration
constexpr double franka::kMaxTranslationalAcceleration = 13.0000 - kLimitEps
Maximum translational acceleration
Definition at line 72 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxTranslationalJerk
constexpr double franka::kMaxTranslationalJerk = 6500.0 - kLimitEps
Maximum translational jerk
Definition at line 68 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kMaxTranslationalVelocity
constexpr double franka::kMaxTranslationalVelocity
Initial value:
=
    1.7000 - kLimitEps - kTolNumberPacketsLost *
      kDeltaT * kMaxTranslationalAcceleration
Maximum translational velocity
Definition at line 76 of file rate_limiting.h.
Referenced by franka::ControlLoop< T >::convertMotion().
kNormEps
constexpr double franka::kNormEps = std::numeric_limits<double>::epsilon()
Epsilon value for limiting Cartesian accelerations/jerks or not
Definition at line 26 of file rate_limiting.h.
Referenced by franka::anonymous_namespace{rate_limiting.cpp}::limitRate(), and limitRate().
kTolNumberPacketsLost
constexpr double franka::kTolNumberPacketsLost = 3.0
Number of packets losts considered for the definition of velocity limits. When a packet is lost, FCI assumes a constant acceleration model
Definition at line 31 of file rate_limiting.h.