std::tr1 Namespace Reference
Namespaces
 gtest_internal
Classes
class tuple
class tuple<>
struct tuple_element
struct tuple_size
struct tuple_size< GTEST_0_TUPLE_(T) >
struct tuple_size< GTEST_10_TUPLE_(T) >
struct tuple_size< GTEST_1_TUPLE_(T) >
struct tuple_size< GTEST_2_TUPLE_(T) >
struct tuple_size< GTEST_3_TUPLE_(T) >
struct tuple_size< GTEST_4_TUPLE_(T) >
struct tuple_size< GTEST_5_TUPLE_(T) >
struct tuple_size< GTEST_6_TUPLE_(T) >
struct tuple_size< GTEST_7_TUPLE_(T) >
struct tuple_size< GTEST_8_TUPLE_(T) >
struct tuple_size< GTEST_9_TUPLE_(T) >
Functions
template<GTEST_1_TYPENAMES_(T) >
class GTEST_1_TUPLE_ (T)
template<GTEST_2_TYPENAMES_(T) >
class GTEST_2_TUPLE_ (T)
template<GTEST_3_TYPENAMES_(T) >
class GTEST_3_TUPLE_ (T)
template<GTEST_4_TYPENAMES_(T) >
class GTEST_4_TUPLE_ (T)
template<GTEST_5_TYPENAMES_(T) >
class GTEST_5_TUPLE_ (T)
template<GTEST_6_TYPENAMES_(T) >
class GTEST_6_TUPLE_ (T)
template<GTEST_7_TYPENAMES_(T) >
class GTEST_7_TUPLE_ (T)
template<GTEST_8_TYPENAMES_(T) >
class GTEST_8_TUPLE_ (T)
template<GTEST_9_TYPENAMES_(T) >
class GTEST_9_TUPLE_ (T)
tuple make_tuple ()
template<GTEST_1_TYPENAMES_(T) >
GTEST_1_TUPLE_ (T) make_tuple(const T0 &f0)
template<GTEST_2_TYPENAMES_(T) >
GTEST_2_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_3_TYPENAMES_(T) >
GTEST_3_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_4_TYPENAMES_(T) >
GTEST_4_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_5_TYPENAMES_(T) >
GTEST_5_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_6_TYPENAMES_(T) >
GTEST_6_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_7_TYPENAMES_(T) >
GTEST_7_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_8_TYPENAMES_(T) >
GTEST_8_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_9_TYPENAMES_(T) >
GTEST_9_TUPLE_ (T) make_tuple(const T0 &f0
template<GTEST_10_TYPENAMES_(T) >
GTEST_10_TUPLE_ (T) make_tuple(const T0 &f0
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(GTEST_10_TUPLE_(T) &t)
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(const GTEST_10_TUPLE_(T) &t)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator== (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator!= (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
Variables
const T1 & f1
const T1 const T2 & f2
const T1 const T2 const T3 & f3
const T1 const T2 const T3 const T4 & f4
const T1 const T2 const T3 const T4 const T5 & f5
const T1 const T2 const T3 const T4 const T5 const T6 & f6
const T1 const T2 const T3 const T4 const T5 const T6 const T7 & f7
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 & f8
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 const T9 & f9
Function Documentation
GTEST_10_TUPLE_()
template<GTEST_10_TYPENAMES_(T) >
std::tr1::GTEST_10_TUPLE_ (T) const & [inline]
GTEST_1_TUPLE_() [1/2]
template<GTEST_1_TYPENAMES_(T) >
class std::tr1::GTEST_1_TUPLE_ (T)
Definition at line 213 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
Referenced by GTEST_1_TUPLE_().
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0) : f0_(f0) {}
  tuple(const tuple& t) : f0_(t.f0_) {}
  template <GTEST_1_TYPENAMES_(U)>
  tuple(const GTEST_1_TUPLE_(U)& t) : f0_(t.f0_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_1_TYPENAMES_(U)>
  tuple& operator=(const GTEST_1_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_1_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_1_TUPLE_(U)& t) {
    f0_ = t.f0_;
    return *this;
  }
  T0 f0_;
};
GTEST_1_TUPLE_() [2/2]
template<GTEST_1_TYPENAMES_(T) >
std::tr1::GTEST_1_TUPLE_ (T) const & [inline]
Definition at line 678 of file gtest-tuple.h.
References GTEST_1_TUPLE_().
                                                  {
  return GTEST_1_TUPLE_(T)(f0);
}
GTEST_2_TUPLE_() [1/2]
template<GTEST_2_TYPENAMES_(T) >
class std::tr1::GTEST_2_TUPLE_ (T)
Definition at line 245 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1) : f0_(f0),
      f1_(f1) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_) {}
  template <GTEST_2_TYPENAMES_(U)>
  tuple(const GTEST_2_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_) {}
  template <typename U0, typename U1>
  tuple(const ::std::pair<U0, U1>& p) : f0_(p.first), f1_(p.second) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_2_TYPENAMES_(U)>
  tuple& operator=(const GTEST_2_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  template <typename U0, typename U1>
  tuple& operator=(const ::std::pair<U0, U1>& p) {
    f0_ = p.first;
    f1_ = p.second;
    return *this;
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_2_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_2_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
};
GTEST_2_TUPLE_() [2/2]
template<GTEST_2_TYPENAMES_(T) >
std::tr1::GTEST_2_TUPLE_ (T) const & [inline]
GTEST_3_TUPLE_() [1/2]
template<GTEST_3_TYPENAMES_(T) >
class std::tr1::GTEST_3_TUPLE_ (T)
Definition at line 288 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2) : f0_(f0), f1_(f1), f2_(f2) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_) {}
  template <GTEST_3_TYPENAMES_(U)>
  tuple(const GTEST_3_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_3_TYPENAMES_(U)>
  tuple& operator=(const GTEST_3_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_3_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_3_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
};
GTEST_3_TUPLE_() [2/2]
template<GTEST_3_TYPENAMES_(T) >
std::tr1::GTEST_3_TUPLE_ (T) const & [inline]
GTEST_4_TUPLE_() [1/2]
template<GTEST_4_TYPENAMES_(T) >
class std::tr1::GTEST_4_TUPLE_ (T)
Definition at line 325 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3) : f0_(f0), f1_(f1), f2_(f2)
      ,
      f3_(f3) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_) {}
  template <GTEST_4_TYPENAMES_(U)>
  tuple(const GTEST_4_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_4_TYPENAMES_(U)>
  tuple& operator=(const GTEST_4_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_4_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_4_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
};
GTEST_4_TUPLE_() [2/2]
template<GTEST_4_TYPENAMES_(T) >
std::tr1::GTEST_4_TUPLE_ (T) const & [inline]
GTEST_5_TUPLE_() [1/2]
template<GTEST_5_TYPENAMES_(T) >
class std::tr1::GTEST_5_TUPLE_ (T)
Definition at line 366 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_(), f4_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3,
      GTEST_BY_REF_(T4) f4) : f0_(f0), f1_(f1), f2_(f2), f3_(f3), f4_(f4) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_),
      f4_(t.f4_) {}
  template <GTEST_5_TYPENAMES_(U)>
  tuple(const GTEST_5_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_), f4_(t.f4_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_5_TYPENAMES_(U)>
  tuple& operator=(const GTEST_5_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_5_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_5_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    f4_ = t.f4_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
  T4 f4_;
};
GTEST_5_TUPLE_() [2/2]
template<GTEST_5_TYPENAMES_(T) >
std::tr1::GTEST_5_TUPLE_ (T) const & [inline]
GTEST_6_TUPLE_() [1/2]
template<GTEST_6_TYPENAMES_(T) >
class std::tr1::GTEST_6_TUPLE_ (T)
Definition at line 410 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_(), f4_(), f5_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3,
      GTEST_BY_REF_(T4) f4,
      GTEST_BY_REF_(T5) f5) : f0_(f0), f1_(f1), f2_(f2), f3_(f3), f4_(f4),
      f5_(f5) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_),
      f4_(t.f4_), f5_(t.f5_) {}
  template <GTEST_6_TYPENAMES_(U)>
  tuple(const GTEST_6_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_), f4_(t.f4_), f5_(t.f5_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_6_TYPENAMES_(U)>
  tuple& operator=(const GTEST_6_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_6_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_6_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    f4_ = t.f4_;
    f5_ = t.f5_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
  T4 f4_;
  T5 f5_;
};
GTEST_6_TUPLE_() [2/2]
template<GTEST_6_TYPENAMES_(T) >
std::tr1::GTEST_6_TUPLE_ (T) const & [inline]
GTEST_7_TUPLE_() [1/2]
template<GTEST_7_TYPENAMES_(T) >
class std::tr1::GTEST_7_TUPLE_ (T)
Definition at line 457 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_(), f4_(), f5_(), f6_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3,
      GTEST_BY_REF_(T4) f4,
      GTEST_BY_REF_(T5) f5, GTEST_BY_REF_(T6) f6) : f0_(f0), f1_(f1), f2_(f2)
      ,
      f3_(f3), f4_(f4), f5_(f5), f6_(f6) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_),
      f4_(t.f4_), f5_(t.f5_), f6_(t.f6_) {}
  template <GTEST_7_TYPENAMES_(U)>
  tuple(const GTEST_7_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_), f4_(t.f4_), f5_(t.f5_), f6_(t.f6_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_7_TYPENAMES_(U)>
  tuple& operator=(const GTEST_7_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_7_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_7_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    f4_ = t.f4_;
    f5_ = t.f5_;
    f6_ = t.f6_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
  T4 f4_;
  T5 f5_;
  T6 f6_;
};
GTEST_7_TUPLE_() [2/2]
template<GTEST_7_TYPENAMES_(T) >
std::tr1::GTEST_7_TUPLE_ (T) const & [inline]
GTEST_8_TUPLE_() [1/2]
template<GTEST_8_TYPENAMES_(T) >
class std::tr1::GTEST_8_TUPLE_ (T)
Definition at line 506 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, f7, std::tr1::tuple<>::f7_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_(), f4_(), f5_(), f6_(), f7_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3,
      GTEST_BY_REF_(T4) f4,
      GTEST_BY_REF_(T5) f5, GTEST_BY_REF_(T6) f6,
      GTEST_BY_REF_(T7) f7) : f0_(f0), f1_(f1), f2_(f2), f3_(f3), f4_(f4),
      f5_(f5), f6_(f6), f7_(f7) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_),
      f4_(t.f4_), f5_(t.f5_), f6_(t.f6_), f7_(t.f7_) {}
  template <GTEST_8_TYPENAMES_(U)>
  tuple(const GTEST_8_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_), f4_(t.f4_), f5_(t.f5_), f6_(t.f6_), f7_(t.f7_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_8_TYPENAMES_(U)>
  tuple& operator=(const GTEST_8_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_8_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_8_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    f4_ = t.f4_;
    f5_ = t.f5_;
    f6_ = t.f6_;
    f7_ = t.f7_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
  T4 f4_;
  T5 f5_;
  T6 f6_;
  T7 f7_;
};
GTEST_8_TUPLE_() [2/2]
template<GTEST_8_TYPENAMES_(T) >
std::tr1::GTEST_8_TUPLE_ (T) const & [inline]
GTEST_9_TUPLE_() [1/2]
template<GTEST_9_TYPENAMES_(T) >
class std::tr1::GTEST_9_TUPLE_ (T)
Definition at line 558 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_, f1, std::tr1::tuple<>::f1_, f2, std::tr1::tuple<>::f2_, f3, std::tr1::tuple<>::f3_, f4, std::tr1::tuple<>::f4_, f5, std::tr1::tuple<>::f5_, f6, std::tr1::tuple<>::f6_, f7, std::tr1::tuple<>::f7_, f8, std::tr1::tuple<>::f8_, GTEST_BY_REF_(), GTEST_DECLARE_TUPLE_AS_FRIEND_, and battery_monitor_node::t.
                        {
 public:
  template <int k> friend class gtest_internal::Get;
  tuple() : f0_(), f1_(), f2_(), f3_(), f4_(), f5_(), f6_(), f7_(), f8_() {}
  explicit tuple(GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1)
      f1,
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3,
      GTEST_BY_REF_(T4) f4,
      GTEST_BY_REF_(T5) f5, GTEST_BY_REF_(T6) f6,
      GTEST_BY_REF_(T7) f7,
      GTEST_BY_REF_(T8) f8) : f0_(f0), f1_(f1), f2_(f2), f3_(f3), f4_(f4),
      f5_(f5), f6_(f6), f7_(f7), f8_(f8) {}
  tuple(const tuple& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_), f3_(t.f3_),
      f4_(t.f4_), f5_(t.f5_), f6_(t.f6_), f7_(t.f7_), f8_(t.f8_) {}
  template <GTEST_9_TYPENAMES_(U)>
  tuple(const GTEST_9_TUPLE_(U)& t) : f0_(t.f0_), f1_(t.f1_), f2_(t.f2_),
      f3_(t.f3_), f4_(t.f4_), f5_(t.f5_), f6_(t.f6_), f7_(t.f7_), f8_(t.f8_) {}
  tuple& operator=(const tuple& t) { return CopyFrom(t); }
  template <GTEST_9_TYPENAMES_(U)>
  tuple& operator=(const GTEST_9_TUPLE_(U)& t) {
    return CopyFrom(t);
  }
  GTEST_DECLARE_TUPLE_AS_FRIEND_
  template <GTEST_9_TYPENAMES_(U)>
  tuple& CopyFrom(const GTEST_9_TUPLE_(U)& t) {
    f0_ = t.f0_;
    f1_ = t.f1_;
    f2_ = t.f2_;
    f3_ = t.f3_;
    f4_ = t.f4_;
    f5_ = t.f5_;
    f6_ = t.f6_;
    f7_ = t.f7_;
    f8_ = t.f8_;
    return *this;
  }
  T0 f0_;
  T1 f1_;
  T2 f2_;
  T3 f3_;
  T4 f4_;
  T5 f5_;
  T6 f6_;
  T7 f7_;
  T8 f8_;
};
GTEST_9_TUPLE_() [2/2]
template<GTEST_9_TYPENAMES_(T) >
std::tr1::GTEST_9_TUPLE_ (T) const & [inline]
GTEST_ADD_REF_()
template<int k, GTEST_10_TYPENAMES_(T) >
std::tr1::GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) &
Definition at line 930 of file gtest-tuple.h.
References testing::Field(), and battery_monitor_node::t.
                           {
  return gtest_internal::Get<k>::Field(t);
}
GTEST_BY_REF_()
template<int k, GTEST_10_TYPENAMES_(T) >
std::tr1::GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) const &
Definition at line 936 of file gtest-tuple.h.
References battery_monitor_node::t.
Referenced by GTEST_1_TUPLE_(), GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
                                 {
  return gtest_internal::Get<k>::ConstField(t);
}
make_tuple()
tuple std::tr1::make_tuple () [inline]
Definition at line 675 of file gtest-tuple.h.
Referenced by testing::internal::FunctionMocker< R(A1)>::With(), testing::internal::FunctionMocker< R(A1, A2)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), and testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With().
{ return tuple<>(); }
operator!=()
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool std::tr1::operator!= (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) [inline]
Definition at line 982 of file gtest-tuple.h.
                                                    { return !(t == u); }
operator==()
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool std::tr1::operator== (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) [inline]
Definition at line 974 of file gtest-tuple.h.
References testing::Eq().
                                                    {
  return gtest_internal::SameSizeTuplePrefixComparator<
      tuple_size<GTEST_10_TUPLE_(T) >::value,
      tuple_size<GTEST_10_TUPLE_(U) >::value>::Eq(t, u);
}
Variable Documentation
f1
const T1 & std::tr1::f1
Initial value:
{
  return GTEST_2_TUPLE_(T)(f0, f1)
Definition at line 683 of file gtest-tuple.h.
Referenced by GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f2
const T1 const T2 & std::tr1::f2
Initial value:
{
  return GTEST_3_TUPLE_(T)(f0, f1, f2)
Definition at line 688 of file gtest-tuple.h.
Referenced by GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f3
const T1 const T2 const T3 & std::tr1::f3
Initial value:
{
  return GTEST_4_TUPLE_(T)(f0, f1, f2, f3)
Definition at line 694 of file gtest-tuple.h.
Referenced by GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f4
const T1 const T2 const T3 const T4 & std::tr1::f4
Initial value:
{
  return GTEST_5_TUPLE_(T)(f0, f1, f2, f3, f4)
Definition at line 700 of file gtest-tuple.h.
Referenced by GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f5
const T1 const T2 const T3 const T4 const T5 & std::tr1::f5
Initial value:
{
  return GTEST_6_TUPLE_(T)(f0, f1, f2, f3, f4, f5)
Definition at line 706 of file gtest-tuple.h.
Referenced by GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f6
const T1 const T2 const T3 const T4 const T5 const T6 & std::tr1::f6
Initial value:
{
  return GTEST_7_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6)
Definition at line 712 of file gtest-tuple.h.
Referenced by GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f7
const T1 const T2 const T3 const T4 const T5 const T6 const T7 & std::tr1::f7
Initial value:
{
  return GTEST_8_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6,
      f7)
Definition at line 718 of file gtest-tuple.h.
Referenced by GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
f8
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 & std::tr1::f8
Initial value:
{
  return GTEST_9_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6,
      f7, f8)
Definition at line 725 of file gtest-tuple.h.
Referenced by GTEST_9_TUPLE_().
f9
const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 const T9& std::tr1::f9
Initial value:
{
  return GTEST_10_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6,
      f7, f8, f9)
Definition at line 732 of file gtest-tuple.h.