franka::anonymous_namespace{log.cpp} Namespace Reference
Functions
template<typename T , size_t N>
std::string csvName (const std::array< T, N > &, const std::string &name)
template<class T , size_t N>
std::ostream & operator<< (std::ostream &ostream, const std::array< T, N > &array)
std::string csvRobotStateHeader ()
std::string csvRobotCommandHeader ()
std::string csvLine (const franka::RobotState &robot_state)
std::string csvLine (const franka::RobotCommand &command)
Function Documentation
csvLine() [1/2]
std::string franka::anonymous_namespace{log.cpp}::csvLine (const franka::RobotState & robot_state)
Definition at line 52 of file log.cpp.
References franka::RobotState::control_command_success_rate, franka::RobotState::dq, franka::RobotState::dq_d, franka::RobotState::q, franka::RobotState::q_d, franka::RobotState::tau_ext_hat_filtered, franka::RobotState::tau_J, franka::RobotState::time, and franka::Duration::toMSec().
                                                       {
  std::ostringstream os;
  os << robot_state.time.toMSec() << "," << robot_state.
      control_command_success_rate << ","
     << robot_state.q << "," << robot_state.q_d << "," << robot_state.dq << "," << robot_state.
      dq_d
     << "," << robot_state.tau_J << "," << robot_state.tau_ext_hat_filtered;
  return os.str();
}
csvLine() [2/2]
std::string franka::anonymous_namespace{log.cpp}::csvLine (const franka::RobotCommand & command)
Definition at line 60 of file log.cpp.
References franka::RobotCommand::cartesian_pose, franka::RobotCommand::cartesian_velocities, franka::JointVelocities::dq, franka::RobotCommand::joint_positions, franka::RobotCommand::joint_velocities, franka::CartesianVelocities::O_dP_EE, franka::CartesianPose::O_T_EE, franka::JointPositions::q, franka::Torques::tau_J, and franka::RobotCommand::torques.
Referenced by franka::logToCSV().
                                                     {
  std::ostringstream os;
  os << command.joint_positions.q << "," << command.
      joint_velocities.dq << ","
     << command.cartesian_pose.O_T_EE << "," << command.
      cartesian_velocities.O_dP_EE << ","
     << command.torques.tau_J;
  return os.str();
}
csvName()
template<typename T , size_t N>
std::string franka::anonymous_namespace{log.cpp}::csvName (const std::array< T, N > & , const std::string & name)
Definition at line 15 of file log.cpp.
Referenced by csvRobotCommandHeader(), and csvRobotStateHeader().
                                                                  {
  std::ostringstream os;
  for (size_t i = 0; i < N - 1; i++) {
    os << name << "[" << i << "], ";
  }
  os << name << "[" << N - 1 << "]";
  return os.str();
}
csvRobotCommandHeader()
std::string franka::anonymous_namespace{log.cpp}::csvRobotCommandHeader ()
Definition at line 41 of file log.cpp.
References franka::RobotCommand::cartesian_pose, franka::RobotCommand::cartesian_velocities, csvName(), franka::JointVelocities::dq, franka::RobotCommand::joint_positions, franka::RobotCommand::joint_velocities, franka::CartesianVelocities::O_dP_EE, franka::CartesianPose::O_T_EE, franka::JointPositions::q, franka::Torques::tau_J, and franka::RobotCommand::torques.
Referenced by franka::logToCSV().
                                  {
  franka::RobotCommand command;
  std::ostringstream os;
  os << "sent commands," << csvName(command.joint_positions.
      q, "q_d") << ","
     << csvName(command.joint_velocities.dq, "dq_d") << ","
     << csvName(command.cartesian_pose.O_T_EE, "O_T_EE_d") << ","
     << csvName(command.cartesian_velocities.O_dP_EE, "O_dP_EE_d") << ","
     << csvName(command.torques.tau_J, "tau_J_d");
  return os.str();
}
csvRobotStateHeader()
std::string franka::anonymous_namespace{log.cpp}::csvRobotStateHeader ()
Definition at line 31 of file log.cpp.
References csvName(), franka::RobotState::dq, franka::RobotState::dq_d, franka::RobotState::q, franka::RobotState::q_d, franka::RobotState::tau_ext_hat_filtered, and franka::RobotState::tau_J.
Referenced by franka::logToCSV().
                                {
  RobotState robot_state;
  std::ostringstream os;
  os << "duration, success rate, " << csvName(robot_state.q, "q") << ","
     << csvName(robot_state.q_d, "q_d") << "," << csvName(robot_state.dq, "dq") << ","
     << csvName(robot_state.dq_d, "dq_d") << "," << csvName(robot_state.tau_J, "tau_J") << ",
      "
     << csvName(robot_state.tau_ext_hat_filtered, "tau_ext_hat_filtered");
  return os.str();
}
operator<<()
template<class T , size_t N>
std::ostream& franka::anonymous_namespace{log.cpp}::operator<< (std::ostream & ostream, const std::array< T, N > & array)
Definition at line 25 of file log.cpp.
                                                                           {
  std::copy(array.cbegin(), array.cend() - 1, std::ostream_iterator<T>(ostream, ","));
  std::copy(array.cend() - 1, array.cend(), std::ostream_iterator<T>(ostream));
  return ostream;
}