franka::anonymous_namespace{gripper.cpp} Namespace Reference
Functions
template<typename T , typename... TArgs>
bool executeCommand (Network &network, TArgs &&... args)
GripperState convertGripperState (const research_interface::gripper::GripperState &gripper_state) noexcept
Function Documentation
convertGripperState()
GripperState franka::anonymous_namespace{gripper.cpp}::convertGripperState (const research_interface::gripper::GripperState & gripper_state) [noexcept]
Definition at line 35 of file gripper.cpp.
References franka::GripperState::is_grasped, franka::GripperState::max_width, franka::GripperState::temperature, franka::GripperState::time, and franka::GripperState::width.
Referenced by franka::Gripper::readOnce().
                                                                         {
  GripperState converted;
  converted.width = gripper_state.width;
  converted.max_width = gripper_state.max_width;
  converted.is_grasped = gripper_state.is_grasped;
  converted.temperature = gripper_state.temperature;
  converted.time = Duration(gripper_state.message_id);
  return converted;
}
executeCommand()
template<typename T , typename... TArgs>
bool franka::anonymous_namespace{gripper.cpp}::executeCommand (Network & network, TArgs &&... args)
Definition at line 17 of file gripper.cpp.
References generate_debs::args, testing::internal::kFail, franka::Network::tcpBlockingReceiveResponse(), and franka::Network::tcpSendRequest().
                                                       {
  uint32_t command_id = network.tcpSendRequest<T>(std::forward<TArgs>(args)...);
  typename T::Response response = network.tcpBlockingReceiveResponse<T>(command_id);
  switch (response.status) {
    case T::Status::kSuccess:
      return true;
    case T::Status::kFail:
      throw CommandException("libfranka gripper: Command failed!");
    case T::Status::kUnsuccessful:
      return false;
    case T::Status::kAborted:
      throw CommandException("libfranka gripper: Command aborted!");
    default:
      throw ProtocolException("libfranka gripper: Unexpected response while handling command!");
  }
}