cpp.ast Namespace Reference
Classes
class _GenericDeclaration
class _NestedType
class _NullDict
class AstBuilder
class Class
class Define
class Delete
class Enum
class Expr
class Friend
class Function
class Goto
class Include
class Method
class Node
class Parameter
class Return
class Struct
class Type
class TypeConverter
class Typedef
class Union
class Using
class VariableDeclaration
Functions
def reversed (seq)
def next (obj)
def BuilderFromSource (source, filename)
def PrintIndentifiers (filename, should_print)
def PrintAllIndentifiers (filenames, should_print)
def main (argv)
Variables
string __author__ = 'nnorwitz@google.com (Neal Norwitz)'
int FUNCTION_NONE = 0x00
int FUNCTION_CONST = 0x01
int FUNCTION_VIRTUAL = 0x02
int FUNCTION_PURE_VIRTUAL = 0x04
int FUNCTION_CTOR = 0x08
int FUNCTION_DTOR = 0x10
int FUNCTION_ATTRIBUTE = 0x20
int FUNCTION_UNKNOWN_ANNOTATION = 0x40
int FUNCTION_THROW = 0x80
int FUNCTION_OVERRIDE = 0x100
string _INTERNAL_TOKEN = 'internal'
string _NAMESPACE_POP = 'ns-pop'
Function Documentation
BuilderFromSource()
def cpp.ast.BuilderFromSource (source, filename)
Utility method that returns an AstBuilder from source code.

Args:
  source: 'C++ source code'
  filename: 'file1'

Returns:
  AstBuilder
Definition at line 1663 of file ast.py.
Referenced by cpp.ast.main(), and cpp.ast.PrintIndentifiers().
def BuilderFromSource(source, filename):
    """Utility method that returns an AstBuilder from source code.
    Args:
      source: 'C++ source code'
      filename: 'file1'
    Returns:
      AstBuilder
    """
    return AstBuilder(tokenize.GetTokens(source), filename)
main()
def cpp.ast.main (argv)
Definition at line 1711 of file ast.py.
References cpp.ast.BuilderFromSource().
def main(argv):
    for filename in argv[1:]:
        source = utils.ReadFile(filename)
        if source is None:
            continue
        print('Processing %s' % filename)
        builder = BuilderFromSource(source, filename)
        try:
            entire_ast = filter(None, builder.Generate())
        except KeyboardInterrupt:
            return
        except:
            # Already printed a warning, print the traceback and continue.
            traceback.print_exc()
        else:
            if utils.DEBUG:
                for ast in entire_ast:
                    print(ast)
next()
def cpp.ast.next (obj)
Definition at line 58 of file ast.py.
Referenced by cpp.ast.AstBuilder._GetNextToken(), cpp.ast.AstBuilder.GetName(), and cl_move_base_z::WaypointNavigator.sendNextGoal().
    def next(obj):
        return obj.next()
VISIBILITY_PUBLIC, VISIBILITY_PROTECTED, VISIBILITY_PRIVATE = range(3)
PrintAllIndentifiers()
def cpp.ast.PrintAllIndentifiers (filenames, should_print)
Prints all identifiers for each C++ source file in filenames.

Args:
  filenames: ['file1', 'file2', ...]
  should_print: predicate with signature: bool Function(token)
Definition at line 1700 of file ast.py.
References cpp.ast.PrintIndentifiers().
def PrintAllIndentifiers(filenames, should_print):
    """Prints all identifiers for each C++ source file in filenames.
    Args:
      filenames: ['file1', 'file2', ...]
      should_print: predicate with signature: bool Function(token)
    """
    for path in filenames:
        PrintIndentifiers(path, should_print)
PrintIndentifiers()
def cpp.ast.PrintIndentifiers (filename, should_print)
Prints all identifiers for a C++ source file.

Args:
  filename: 'file1'
  should_print: predicate with signature: bool Function(token)
Definition at line 1676 of file ast.py.
References cpp.ast.BuilderFromSource().
Referenced by cpp.ast.PrintAllIndentifiers().
def PrintIndentifiers(filename, should_print):
    """Prints all identifiers for a C++ source file.
    Args:
      filename: 'file1'
      should_print: predicate with signature: bool Function(token)
    """
    source = utils.ReadFile(filename, False)
    if source is None:
        sys.stderr.write('Unable to find: %s\n' % filename)
        return
    #print('Processing %s' % actual_filename)
    builder = BuilderFromSource(source, filename)
    try:
        for node in builder.Generate():
            if should_print(node):
                print(node.name)
    except KeyboardInterrupt:
        return
    except:
        pass
reversed()
def cpp.ast.reversed (seq)
Definition at line 52 of file ast.py.
Referenced by cpp.ast.AstBuilder._AddBackTokens(), cl_move_base_z::backward_global_planner::BackwardGlobalPlanner.createDefaultBackwardPath(), and cpp.ast.AstBuilder.HandleError().
    def reversed(seq):
        for i in range(len(seq)-1, -1, -1):
            yield seq[i]
Variable Documentation
__author__
string cpp.ast.__author__ = 'nnorwitz@google.com (Neal Norwitz)' [private]
Definition at line 20 of file ast.py.
_INTERNAL_TOKEN
string cpp.ast._INTERNAL_TOKEN = 'internal' [private]
Definition at line 97 of file ast.py.
_NAMESPACE_POP
string cpp.ast._NAMESPACE_POP = 'ns-pop' [private]
Definition at line 98 of file ast.py.
FUNCTION_ATTRIBUTE
int cpp.ast.FUNCTION_ATTRIBUTE = 0x20
Definition at line 70 of file ast.py.
FUNCTION_CONST
int cpp.ast.FUNCTION_CONST = 0x01
Definition at line 65 of file ast.py.
FUNCTION_CTOR
int cpp.ast.FUNCTION_CTOR = 0x08
Definition at line 68 of file ast.py.
FUNCTION_DTOR
int cpp.ast.FUNCTION_DTOR = 0x10
Definition at line 69 of file ast.py.
FUNCTION_NONE
int cpp.ast.FUNCTION_NONE = 0x00
Definition at line 64 of file ast.py.
FUNCTION_OVERRIDE
int cpp.ast.FUNCTION_OVERRIDE = 0x100
Definition at line 73 of file ast.py.
FUNCTION_PURE_VIRTUAL
int cpp.ast.FUNCTION_PURE_VIRTUAL = 0x04
Definition at line 67 of file ast.py.
FUNCTION_THROW
int cpp.ast.FUNCTION_THROW = 0x80
Definition at line 72 of file ast.py.
FUNCTION_UNKNOWN_ANNOTATION
int cpp.ast.FUNCTION_UNKNOWN_ANNOTATION = 0x40
Definition at line 71 of file ast.py.
FUNCTION_VIRTUAL
int cpp.ast.FUNCTION_VIRTUAL = 0x02
Definition at line 66 of file ast.py.