common Namespace Reference
Functions
def GetCommandOutput (command)
def GetSvnInfo ()
def GetSvnTrunk ()
def IsInGTestSvn ()
def IsInGMockSvn ()
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
_SVN_INFO_URL_RE = re.compile(r'^URL: https://(\w+)\.googlecode\.com/svn(.*)')
Function Documentation
GetCommandOutput()
def common.GetCommandOutput (command)
Runs the shell command and returns its stdout as a list of lines.
Definition at line 46 of file common.py.
Referenced by GetSvnInfo().
def GetCommandOutput(command):
  """Runs the shell command and returns its stdout as a list of lines."""
  f = os.popen(command, 'r')
  lines = [line.strip() for line in f.readlines()]
  f.close()
  return lines
GetSvnInfo()
def common.GetSvnInfo ()
Returns the project name and the current SVN workspace's root path.
Definition at line 55 of file common.py.
References GetCommandOutput().
Referenced by release_docs.WikiBrancher.__init__(), GetSvnTrunk(), IsInGMockSvn(), and IsInGTestSvn().
def GetSvnInfo():
  """Returns the project name and the current SVN workspace's root path."""
  for line in GetCommandOutput('svn info .'):
    m = _SVN_INFO_URL_RE.match(line)
    if m:
      project = m.group(1) # googletest or googlemock
      rel_path = m.group(2)
      root = os.path.realpath(rel_path.count('/') * '../')
      return project, root
  return None, None
GetSvnTrunk()
def common.GetSvnTrunk ()
Returns the current SVN workspace's trunk root path.
Definition at line 69 of file common.py.
References GetSvnInfo().
def GetSvnTrunk():
  """Returns the current SVN workspace's trunk root path."""
  _, root = GetSvnInfo()
  return root + '/trunk' if root else None
IsInGMockSvn()
def common.IsInGMockSvn ()
Definition at line 81 of file common.py.
References GetSvnInfo().
def IsInGMockSvn():
  project, _ = GetSvnInfo()
  return project == 'googlemock'
IsInGTestSvn()
def common.IsInGTestSvn ()
Definition at line 76 of file common.py.
References GetSvnInfo().
def IsInGTestSvn():
  project, _ = GetSvnInfo()
  return project == 'googletest'
Variable Documentation
__author__
string common.__author__ = 'wan@google.com (Zhanyong Wan)' [private]
Definition at line 31 of file common.py.
_SVN_INFO_URL_RE
common._SVN_INFO_URL_RE = re.compile(r'^URL: https://(\w+)\.googlecode\.com/svn(.*)') [private]
Definition at line 43 of file common.py.