franka_control Namespace Reference
Classes
class FrankaStateController
Functions
template<typename T >
ros::ServiceServer advertiseService (ros::NodeHandle &node_handle, const std::string &name, std::function< void(typename T::Request &, typename T::Response &)> handler)
void setCartesianImpedance (franka::Robot &robot, const SetCartesianImpedance::Request &req, SetCartesianImpedance::Response &res)
void setJointImpedance (franka::Robot &robot, const SetJointImpedance::Request &req, SetJointImpedance::Response &res)
void setEEFrame (franka::Robot &robot, const SetEEFrame::Request &req, SetEEFrame::Response &res)
void setKFrame (franka::Robot &robot, const SetKFrame::Request &req, SetKFrame::Response &res)
void setForceTorqueCollisionBehavior (franka::Robot &robot, const SetForceTorqueCollisionBehavior::Request &req, SetForceTorqueCollisionBehavior::Response &res)
void setFullCollisionBehavior (franka::Robot &robot, const SetFullCollisionBehavior::Request &req, SetFullCollisionBehavior::Response &res)
void setLoad (franka::Robot &robot, const SetLoad::Request &req, SetLoad::Response &res)
Function Documentation
advertiseService()
template<typename T >
ros::ServiceServer franka_control::advertiseService (ros::NodeHandle & node_handle, const std::string & name, std::function< void(typename T::Request &, typename T::Response &)> handler)
Definition at line 22 of file services.h.
References interactive_marker::name, setCartesianImpedance(), setEEFrame(), setForceTorqueCollisionBehavior(), setFullCollisionBehavior(), setJointImpedance(), setKFrame(), and setLoad().
                                                                        {
  return node_handle.advertiseService<typename T::Request, typename T::Response>(
      name, [name, handler](typename T::Request& request, typename T::Response& response) {
        try {
          handler(request, response);
          response.success = true;
          ROS_DEBUG_STREAM(name << " succeeded.");
        } catch (const franka::Exception& ex) {
          ROS_ERROR_STREAM(name << " failed: " << ex.what());
          response.success = false;
          response.error = ex.what();
        }
        return true;
      });
}
setCartesianImpedance()
void franka_control::setCartesianImpedance (franka::Robot & robot, const SetCartesianImpedance::Request & req, SetCartesianImpedance::Response & res)
Definition at line 7 of file services.cpp.
References franka::Robot::setCartesianImpedance().
Referenced by advertiseService(), and main().
                                                             {
  std::array<double, 6> cartesian_stiffness;
  std::copy(req.cartesian_stiffness.cbegin(), req.cartesian_stiffness.cend(),
            cartesian_stiffness.begin());
  robot.setCartesianImpedance(cartesian_stiffness);
}
setEEFrame()
void franka_control::setEEFrame (franka::Robot & robot, const SetEEFrame::Request & req, SetEEFrame::Response & res)
Definition at line 24 of file services.cpp.
References franka::Robot::setEE().
Referenced by advertiseService(), and main().
                                       {
  std::array<double, 16> F_T_EE; // NOLINT [readability-identifier-naming]
  std::copy(req.F_T_EE.cbegin(), req.F_T_EE.cend(), F_T_EE.begin());
  robot.setEE(F_T_EE);
}
setForceTorqueCollisionBehavior()
void franka_control::setForceTorqueCollisionBehavior (franka::Robot & robot, const SetForceTorqueCollisionBehavior::Request & req, SetForceTorqueCollisionBehavior::Response & res)
Definition at line 40 of file services.cpp.
References franka::Robot::setCollisionBehavior().
Referenced by advertiseService(), and main().
  {
  std::array<double, 7> lower_torque_thresholds_nominal;
  std::copy(req.lower_torque_thresholds_nominal.cbegin(),
            req.lower_torque_thresholds_nominal.cend(), lower_torque_thresholds_nominal.begin());
  std::array<double, 7> upper_torque_thresholds_nominal;
  std::copy(req.upper_torque_thresholds_nominal.cbegin(),
            req.upper_torque_thresholds_nominal.cend(), upper_torque_thresholds_nominal.begin());
  std::array<double, 6> lower_force_thresholds_nominal;
  std::copy(req.lower_force_thresholds_nominal.cbegin(), req.lower_force_thresholds_nominal.cend(),
            lower_force_thresholds_nominal.begin());
  std::array<double, 6> upper_force_thresholds_nominal;
  std::copy(req.upper_force_thresholds_nominal.cbegin(), req.upper_force_thresholds_nominal.cend(),
            upper_force_thresholds_nominal.begin());
  robot.setCollisionBehavior(lower_torque_thresholds_nominal,
      upper_torque_thresholds_nominal,
                             lower_force_thresholds_nominal, upper_force_thresholds_nominal);
}
setFullCollisionBehavior()
void franka_control::setFullCollisionBehavior (franka::Robot & robot, const SetFullCollisionBehavior::Request & req, SetFullCollisionBehavior::Response & res)
Definition at line 61 of file services.cpp.
References franka::Robot::setCollisionBehavior().
Referenced by advertiseService(), and main().
                                                                   {
  std::array<double, 7> lower_torque_thresholds_acceleration;
  std::copy(req.lower_torque_thresholds_acceleration.cbegin(),
            req.lower_torque_thresholds_acceleration.cend(),
            lower_torque_thresholds_acceleration.begin());
  std::array<double, 7> upper_torque_thresholds_acceleration;
  std::copy(req.upper_torque_thresholds_acceleration.cbegin(),
            req.upper_torque_thresholds_acceleration.cend(),
            upper_torque_thresholds_acceleration.begin());
  std::array<double, 7> lower_torque_thresholds_nominal;
  std::copy(req.lower_torque_thresholds_nominal.cbegin(),
            req.lower_torque_thresholds_nominal.cend(), lower_torque_thresholds_nominal.begin());
  std::array<double, 7> upper_torque_thresholds_nominal;
  std::copy(req.upper_torque_thresholds_nominal.cbegin(),
            req.upper_torque_thresholds_nominal.cend(), upper_torque_thresholds_nominal.begin());
  std::array<double, 6> lower_force_thresholds_acceleration;
  std::copy(req.lower_force_thresholds_acceleration.cbegin(),
            req.lower_force_thresholds_acceleration.cend(),
            lower_force_thresholds_acceleration.begin());
  std::array<double, 6> upper_force_thresholds_acceleration;
  std::copy(req.upper_force_thresholds_acceleration.cbegin(),
            req.upper_force_thresholds_acceleration.cend(),
            upper_force_thresholds_acceleration.begin());
  std::array<double, 6> lower_force_thresholds_nominal;
  std::copy(req.lower_force_thresholds_nominal.cbegin(), req.lower_force_thresholds_nominal.cend(),
            lower_force_thresholds_nominal.begin());
  std::array<double, 6> upper_force_thresholds_nominal;
  std::copy(req.upper_force_thresholds_nominal.cbegin(), req.upper_force_thresholds_nominal.cend(),
            upper_force_thresholds_nominal.begin());
  robot.setCollisionBehavior(lower_torque_thresholds_acceleration,
                             upper_torque_thresholds_acceleration, lower_torque_thresholds_nominal,
                             upper_torque_thresholds_nominal, lower_force_thresholds_acceleration,
                             upper_force_thresholds_acceleration, lower_force_thresholds_nominal,
                             upper_force_thresholds_nominal);
}
setJointImpedance()
void franka_control::setJointImpedance (franka::Robot & robot, const SetJointImpedance::Request & req, SetJointImpedance::Response & res)
Definition at line 16 of file services.cpp.
References franka::Robot::setJointImpedance().
Referenced by advertiseService(), and main().
                                                     {
  std::array<double, 7> joint_stiffness;
  std::copy(req.joint_stiffness.cbegin(), req.joint_stiffness.cend(), joint_stiffness.begin());
  robot.setJointImpedance(joint_stiffness);
}
setKFrame()
void franka_control::setKFrame (franka::Robot & robot, const SetKFrame::Request & req, SetKFrame::Response & res)
Definition at line 32 of file services.cpp.
References franka::Robot::setK().
Referenced by advertiseService(), and main().
                                     {
  std::array<double, 16> EE_T_K; // NOLINT [readability-identifier-naming]
  std::copy(req.EE_T_K.cbegin(), req.EE_T_K.cend(), EE_T_K.begin());
  robot.setK(EE_T_K);
}
setLoad()
void franka_control::setLoad (franka::Robot & robot, const SetLoad::Request & req, SetLoad::Response & res)
Definition at line 99 of file services.cpp.
References franka::Robot::setLoad().
Referenced by advertiseService(), and main().
                                                                                {
  double mass(req.mass);
  std::array<double, 3> F_x_center_load; // NOLINT [readability-identifier-naming]
  std::copy(req.F_x_center_load.cbegin(), req.F_x_center_load.cend(), F_x_center_load.begin());
  std::array<double, 9> load_inertia;
  std::copy(req.load_inertia.cbegin(), req.load_inertia.cend(), load_inertia.begin());
  robot.setLoad(mass, F_x_center_load, load_inertia);
}