anonymous_namespace{franka_gripper_node.cpp} Namespace Reference
Functions
template<typename T_action , typename T_goal , typename T_result >
void handleErrors (actionlib::SimpleActionServer< T_action > *server, std::function< bool(const T_goal &)> handler, const T_goal &goal)
Function Documentation
handleErrors()
template<typename T_action , typename T_goal , typename T_result >
void anonymous_namespace{franka_gripper_node.cpp}::handleErrors (actionlib::SimpleActionServer< T_action > * server, std::function< bool(const T_goal &)> handler, const T_goal & goal)
Definition at line 21 of file franka_gripper_node.cpp.
References franka_gripper::grasp(), franka_gripper::gripperCommandExecuteCallback(), franka_gripper::homing(), franka_gripper::move(), franka_gripper::stop(), and franka_gripper::updateGripperState().
Referenced by main().
                                      {
  T_result result;
  try {
    result.success = handler(goal);
    server->setSucceeded(result);
  } catch (const franka::Exception& ex) {
    ROS_ERROR_STREAM("" << ex.what());
    result.success = false;
    result.error = ex.what();
    server->setAborted(result);
  }
}