testing::anonymous_namespace{gmock-spec-builders.cc} Namespace Reference
Classes
class MockObjectRegistry
struct MockObjectState
Typedefs
typedef std::set< internal::UntypedFunctionMockerBase * > FunctionMockers
Functions
void SetReactionOnUninterestingCalls (const void *mock_obj, internal::CallReaction reaction) GTEST_LOCK_EXCLUDED_(internal
Variables
MockObjectRegistry g_mock_object_registry
std::map< const void *, internal::CallReaction > g_uninteresting_call_reaction
Typedef Documentation
FunctionMockers
typedef std::set<internal::UntypedFunctionMockerBase*> testing::anonymous_namespace{gmock-spec-builders.cc}::FunctionMockers
Definition at line 518 of file gmock-spec-builders.cc.
Function Documentation
SetReactionOnUninterestingCalls()
void testing::anonymous_namespace{gmock-spec-builders.cc}::SetReactionOnUninterestingCalls (const void * mock_obj, internal::CallReaction reaction)
Definition at line 607 of file gmock-spec-builders.cc.
References testing::internal::UntypedFunctionMockerBase::ClearDefaultActionsLocked(), testing::UnitTest::current_test_info(), testing::anonymous_namespace{gmock-spec-builders.cc}::MockObjectState::first_used_file, testing::anonymous_namespace{gmock-spec-builders.cc}::MockObjectState::first_used_line, testing::anonymous_namespace{gmock-spec-builders.cc}::MockObjectState::first_used_test, testing::anonymous_namespace{gmock-spec-builders.cc}::MockObjectState::first_used_test_case, g_mock_object_registry, g_uninteresting_call_reaction, testing::UnitTest::GetInstance(), GTEST_EXCLUSIVE_LOCK_REQUIRED_, GTEST_LOCK_EXCLUDED_, testing::internal::kAllow, testing::internal::kDefault, testing::internal::kFail, testing::internal::kWarn, testing::TestInfo::name(), testing::anonymous_namespace{gmock-spec-builders.cc}::MockObjectRegistry::states(), testing::TestInfo::test_case_name(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
                                                {
  internal::MutexLock l(&internal::g_gmock_mutex);
  g_uninteresting_call_reaction[mock_obj] = reaction;
}
Variable Documentation
g_mock_object_registry
MockObjectRegistry testing::anonymous_namespace{gmock-spec-builders.cc}::g_mock_object_registry
Definition at line 599 of file gmock-spec-builders.cc.
Referenced by SetReactionOnUninterestingCalls().
g_uninteresting_call_reaction
std::map<const void*, internal::CallReaction> testing::anonymous_namespace{gmock-spec-builders.cc}::g_uninteresting_call_reaction
Definition at line 603 of file gmock-spec-builders.cc.
Referenced by SetReactionOnUninterestingCalls().