franka::anonymous_namespace{control_loop.cpp} Namespace Reference
Functions
template<typename T , size_t N>
void checkFinite (const std::array< T, N > &array)
void checkElbow (const std::array< double, 2 > &elbow)
void checkMatrix (const std::array< double, 16 > &transform)
Function Documentation
checkElbow()
void franka::anonymous_namespace{control_loop.cpp}::checkElbow (const std::array< double, 2 > & elbow) [inline]
Definition at line 35 of file control_loop.cpp.
References checkFinite(), and franka::isValidElbow().
Referenced by franka::ControlLoop< T >::convertMotion().
                                                         {
  checkFinite(elbow);
  if (!isValidElbow(elbow)) {
    throw std::invalid_argument(
        "Invalid elbow configuration given! Only +1 or -1 are allowed for the sign of the 4th "
        "joint.");
  }
}
checkFinite()
template<typename T , size_t N>
void franka::anonymous_namespace{control_loop.cpp}::checkFinite (const std::array< T, N > & array) [inline]
Definition at line 29 of file control_loop.cpp.
Referenced by checkElbow(), checkMatrix(), franka::ControlLoop< T >::convertMotion(), and franka::ControlLoop< T >::spinControl().
                                                     {
  if (!std::all_of(array.begin(), array.end(), [](double d) { return std::isfinite(d); })) {
    throw std::invalid_argument("Commanding value is infinite or NaN.");
  }
}
checkMatrix()
void franka::anonymous_namespace{control_loop.cpp}::checkMatrix (const std::array< double, 16 > & transform) [inline]
Definition at line 44 of file control_loop.cpp.
References checkFinite(), and franka::isHomogeneousTransformation().
Referenced by franka::ControlLoop< T >::convertMotion().
                                                               {
  checkFinite(transform);
  if (!isHomogeneousTransformation(transform)) {
    throw std::invalid_argument(
        "libfranka: Attempt to set invalid transformation in motion generator. Has to be column "
        "major!");
  }
}