fuse_gtest_files Namespace Reference
Functions
def VerifyFileExists (directory, relative_path)
def ValidateGTestRootDir (gtest_root)
def VerifyOutputFile (output_dir, relative_path)
def ValidateOutputDir (output_dir)
def FuseGTestH (gtest_root, output_dir)
def FuseGTestAllCcToFile (gtest_root, output_file)
def FuseGTestAllCc (gtest_root, output_dir)
def FuseGTest (gtest_root, output_dir)
def main ()
Variables
string __author__ = 'wan@google.com (Zhanyong Wan)'
DEFAULT_GTEST_ROOT_DIR = os.path.join(os.path.dirname(__file__), '..')
INCLUDE_GTEST_FILE_REGEX = re.compile(r'^\s*#\s*include\s*`(gtest/.+)`')
INCLUDE_SRC_FILE_REGEX = re.compile(r'^\s*#\s*include\s*`(src/.+)`')
string GTEST_H_SEED = 'include/gtest/gtest.h'
string GTEST_SPI_H_SEED = 'include/gtest/gtest-spi.h'
string GTEST_ALL_CC_SEED = 'src/gtest-all.cc'
string GTEST_H_OUTPUT = 'gtest/gtest.h'
string GTEST_ALL_CC_OUTPUT = 'gtest/gtest-all.cc'
Function Documentation
FuseGTest()
def fuse_gtest_files.FuseGTest (gtest_root, output_dir)
Fuses gtest.h and gtest-all.cc.
Definition at line 229 of file fuse_gtest_files.py.
References FuseGTestAllCc(), FuseGTestH(), ValidateGTestRootDir(), and ValidateOutputDir().
Referenced by main().
def FuseGTest(gtest_root, output_dir):
  """Fuses gtest.h and gtest-all.cc."""
  ValidateGTestRootDir(gtest_root)
  ValidateOutputDir(output_dir)
  FuseGTestH(gtest_root, output_dir)
  FuseGTestAllCc(gtest_root, output_dir)
FuseGTestAllCc()
def fuse_gtest_files.FuseGTestAllCc (gtest_root, output_dir)
Scans folder gtest_root to generate gtest/gtest-all.cc in output_dir.
Definition at line 221 of file fuse_gtest_files.py.
References FuseGTestAllCcToFile().
Referenced by FuseGTest().
def FuseGTestAllCc(gtest_root, output_dir):
  """Scans folder gtest_root to generate gtest/gtest-all.cc in output_dir."""
  output_file = open(os.path.join(output_dir, GTEST_ALL_CC_OUTPUT), 'w')
  FuseGTestAllCcToFile(gtest_root, output_file)
  output_file.close()
FuseGTestAllCcToFile()
def fuse_gtest_files.FuseGTestAllCcToFile (gtest_root, output_file)
Scans folder gtest_root to generate gtest/gtest-all.cc in output_file.
Definition at line 178 of file fuse_gtest_files.py.
References cpp.gmock_class.set.
Referenced by FuseGTestAllCc().
def FuseGTestAllCcToFile(gtest_root, output_file):
  """Scans folder gtest_root to generate gtest/gtest-all.cc in output_file."""
  processed_files = set()
  def ProcessFile(gtest_source_file):
    """Processes the given gtest source file."""
    # We don't process the same #included file twice.
    if gtest_source_file in processed_files:
      return
    processed_files.add(gtest_source_file)
    # Reads each line in the given gtest source file.
    for line in open(os.path.join(gtest_root, gtest_source_file), 'r'):
      m = INCLUDE_GTEST_FILE_REGEX.match(line)
      if m:
        if 'include/' + m.group(1) == GTEST_SPI_H_SEED:
          # It's '#include "gtest/gtest-spi.h"'. This file is not
          # #included by "gtest/gtest.h", so we need to process it.
          ProcessFile(GTEST_SPI_H_SEED)
        else:
          # It's '#include "gtest/foo.h"' where foo is not gtest-spi.
          # We treat it as '#include "gtest/gtest.h"', as all other
          # gtest headers are being fused into gtest.h and cannot be
          # #included directly.
          # There is no need to #include "gtest/gtest.h" more than once.
          if not GTEST_H_SEED in processed_files:
            processed_files.add(GTEST_H_SEED)
            output_file.write('#include "%s"\n' % (GTEST_H_OUTPUT,))
      else:
        m = INCLUDE_SRC_FILE_REGEX.match(line)
        if m:
          # It's '#include "src/foo"' - let's process it recursively.
          ProcessFile(m.group(1))
        else:
          output_file.write(line)
  ProcessFile(GTEST_ALL_CC_SEED)
FuseGTestH()
def fuse_gtest_files.FuseGTestH (gtest_root, output_dir)
Scans folder gtest_root to generate gtest/gtest.h in output_dir.
Definition at line 149 of file fuse_gtest_files.py.
References cpp.gmock_class.set.
Referenced by FuseGTest().
def FuseGTestH(gtest_root, output_dir):
  """Scans folder gtest_root to generate gtest/gtest.h in output_dir."""
  output_file = open(os.path.join(output_dir, GTEST_H_OUTPUT), 'w')
  processed_files = set() # Holds all gtest headers we've processed.
  def ProcessFile(gtest_header_path):
    """Processes the given gtest header file."""
    # We don't process the same header twice.
    if gtest_header_path in processed_files:
      return
    processed_files.add(gtest_header_path)
    # Reads each line in the given gtest header.
    for line in open(os.path.join(gtest_root, gtest_header_path), 'r'):
      m = INCLUDE_GTEST_FILE_REGEX.match(line)
      if m:
        # It's '#include "gtest/..."' - let's process it recursively.
        ProcessFile('include/' + m.group(1))
      else:
        # Otherwise we copy the line unchanged to the output file.
        output_file.write(line)
  ProcessFile(GTEST_H_SEED)
  output_file.close()
main()
def fuse_gtest_files.main ()
Definition at line 239 of file fuse_gtest_files.py.
References FuseGTest().
def main():
  argc = len(sys.argv)
  if argc == 2:
    # fuse_gtest_files.py OUTPUT_DIR
    FuseGTest(DEFAULT_GTEST_ROOT_DIR, sys.argv[1])
  elif argc == 3:
    # fuse_gtest_files.py GTEST_ROOT_DIR OUTPUT_DIR
    FuseGTest(sys.argv[1], sys.argv[2])
  else:
    print(__doc__)
    sys.exit(1)
ValidateGTestRootDir()
def fuse_gtest_files.ValidateGTestRootDir (gtest_root)
Makes sure gtest_root points to a valid gtest root directory.

The function aborts the program on failure.
Definition at line 103 of file fuse_gtest_files.py.
References VerifyFileExists().
Referenced by FuseGTest().
def ValidateGTestRootDir(gtest_root):
  """Makes sure gtest_root points to a valid gtest root directory.
  The function aborts the program on failure.
  """
  VerifyFileExists(gtest_root, GTEST_H_SEED)
  VerifyFileExists(gtest_root, GTEST_ALL_CC_SEED)
ValidateOutputDir()
def fuse_gtest_files.ValidateOutputDir (output_dir)
Makes sure output_dir points to a valid output directory.

The function aborts the program on failure.
Definition at line 139 of file fuse_gtest_files.py.
References VerifyOutputFile().
Referenced by FuseGTest().
def ValidateOutputDir(output_dir):
  """Makes sure output_dir points to a valid output directory.
  The function aborts the program on failure.
  """
  VerifyOutputFile(output_dir, GTEST_H_OUTPUT)
  VerifyOutputFile(output_dir, GTEST_ALL_CC_OUTPUT)
VerifyFileExists()
def fuse_gtest_files.VerifyFileExists (directory, relative_path)
Verifies that the given file exists; aborts on failure.

relative_path is the file path relative to the given directory.
Definition at line 89 of file fuse_gtest_files.py.
Referenced by ValidateGTestRootDir().
def VerifyFileExists(directory, relative_path):
  """Verifies that the given file exists; aborts on failure.
  relative_path is the file path relative to the given directory.
  """
  if not os.path.isfile(os.path.join(directory, relative_path)):
    print('ERROR: Cannot find %s in directory %s.' % (relative_path,
                                                      directory))
    print('Please either specify a valid project root directory '
          'or omit it on the command line.')
    sys.exit(1)
VerifyOutputFile()
def fuse_gtest_files.VerifyOutputFile (output_dir, relative_path)
Verifies that the given output file path is valid.

relative_path is relative to the output_dir directory.
Definition at line 113 of file fuse_gtest_files.py.
Referenced by ValidateOutputDir().
def VerifyOutputFile(output_dir, relative_path):
  """Verifies that the given output file path is valid.
  relative_path is relative to the output_dir directory.
  """
  # Makes sure the output file either doesn't exist or can be overwritten.
  output_file = os.path.join(output_dir, relative_path)
  if os.path.exists(output_file):
    # TODO(wan@google.com): The following user-interaction doesn't
    # work with automated processes. We should provide a way for the
    # Makefile to force overwriting the files.
    print('%s already exists in directory %s - overwrite it? (y/N) ' %
          (relative_path, output_dir))
    answer = sys.stdin.readline().strip()
    if answer not in ['y', 'Y']:
      print('ABORTED.')
      sys.exit(1)
  # Makes sure the directory holding the output file exists; creates
  # it and all its ancestors if necessary.
  parent_directory = os.path.dirname(output_file)
  if not os.path.isdir(parent_directory):
    os.makedirs(parent_directory)
Variable Documentation
__author__
string fuse_gtest_files.__author__ = 'wan@google.com (Zhanyong Wan)' [private]
Definition at line 59 of file fuse_gtest_files.py.
DEFAULT_GTEST_ROOT_DIR
fuse_gtest_files.DEFAULT_GTEST_ROOT_DIR = os.path.join(os.path.dirname(__file__), '..')
Definition at line 71 of file fuse_gtest_files.py.
GTEST_ALL_CC_OUTPUT
string fuse_gtest_files.GTEST_ALL_CC_OUTPUT = 'gtest/gtest-all.cc'
Definition at line 86 of file fuse_gtest_files.py.
GTEST_ALL_CC_SEED
string fuse_gtest_files.GTEST_ALL_CC_SEED = 'src/gtest-all.cc'
Definition at line 82 of file fuse_gtest_files.py.
GTEST_H_OUTPUT
string fuse_gtest_files.GTEST_H_OUTPUT = 'gtest/gtest.h'
Definition at line 85 of file fuse_gtest_files.py.
GTEST_H_SEED
string fuse_gtest_files.GTEST_H_SEED = 'include/gtest/gtest.h'
Definition at line 80 of file fuse_gtest_files.py.
GTEST_SPI_H_SEED
string fuse_gtest_files.GTEST_SPI_H_SEED = 'include/gtest/gtest-spi.h'
Definition at line 81 of file fuse_gtest_files.py.
INCLUDE_GTEST_FILE_REGEX
fuse_gtest_files.INCLUDE_GTEST_FILE_REGEX = re.compile(r'^\s*#\s*include\s*`(gtest/.+)`')
Definition at line 74 of file fuse_gtest_files.py.
INCLUDE_SRC_FILE_REGEX
fuse_gtest_files.INCLUDE_SRC_FILE_REGEX = re.compile(r'^\s*#\s*include\s*`(src/.+)`')
Definition at line 77 of file fuse_gtest_files.py.