testing::anonymous_namespace{gtest.cc} Namespace Reference
Classes
class TestNameIs
Functions
bool IsSubstringPred (const char *needle, const char *haystack)
bool IsSubstringPred (const wchar_t *needle, const wchar_t *haystack)
template<typename StringType >
bool IsSubstringPred (const StringType &needle, const StringType &haystack)
template<typename StringType >
AssertionResult IsSubstringImpl (bool expected_to_be_substring, const char *needle_expr, const char *haystack_expr, const StringType &needle, const StringType &haystack)
Function Documentation
IsSubstringImpl()
template<typename StringType >
AssertionResult testing::anonymous_namespace{gtest.cc}::IsSubstringImpl (bool expected_to_be_substring, const char * needle_expr, const char * haystack_expr, const StringType & needle, const StringType & haystack)
Definition at line 1583 of file gtest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and IsSubstringPred().
Referenced by testing::IsNotSubstring(), and testing::IsSubstring().
                                                          {
  if (IsSubstringPred(needle, haystack) == expected_to_be_substring)
    return AssertionSuccess();
  const bool is_wide_string = sizeof(needle[0]) > 1;
  const char* const begin_string_quote = is_wide_string ? "L\"" : "\"";
  return AssertionFailure()
      << "Value of: " << needle_expr << "\n"
      << " Actual: " << begin_string_quote << needle << "\"\n"
      << "Expected: " << (expected_to_be_substring ? "" : "not ")
      << "a substring of " << haystack_expr << "\n"
      << "Which is: " << begin_string_quote << haystack << "\"";
}
IsSubstringPred() [1/3]
bool testing::anonymous_namespace{gtest.cc}::IsSubstringPred (const char * needle, const char * haystack)
Definition at line 1557 of file gtest.cc.
                                                               {
  if (needle == NULL || haystack == NULL)
    return needle == haystack;
  return strstr(haystack, needle) != NULL;
}
IsSubstringPred() [2/3]
bool testing::anonymous_namespace{gtest.cc}::IsSubstringPred (const wchar_t * needle, const wchar_t * haystack)
Definition at line 1564 of file gtest.cc.
                                                                     {
  if (needle == NULL || haystack == NULL)
    return needle == haystack;
  return wcsstr(haystack, needle) != NULL;
}
IsSubstringPred() [3/3]
template<typename StringType >
bool testing::anonymous_namespace{gtest.cc}::IsSubstringPred (const StringType & needle, const StringType & haystack)
Definition at line 1573 of file gtest.cc.
Referenced by IsSubstringImpl().
                                                 {
  return haystack.find(needle) != StringType::npos;
}