franka_hw Namespace Reference
Namespaces
 anonymous_namespace{franka_hw.cpp}
Classes
class FrankaCartesianPoseHandle
class FrankaCartesianVelocityHandle
class FrankaHW
class FrankaModelHandle
class FrankaModelInterface
class FrankaPoseCartesianInterface
class FrankaStateHandle
class FrankaStateInterface
class FrankaVelocityCartesianInterface
struct ResourceClaims
class TriggerRate
Typedefs
using ResourceWithClaimsMap = std::map< std::string, std::vector< std::vector< std::string > >>
using ArmClaimedMap = std::map< std::string, ResourceClaims >
Enumerations
enum ControlMode {
ControlMode::None = 0,
ControlMode::JointTorque = (1 << 0),
ControlMode::JointPosition = (1 << 1),
ControlMode::JointVelocity = (1 << 2),
ControlMode::CartesianVelocity = (1 << 3),
ControlMode::CartesianPose = (1 << 4)
 }
Functions
std::ostream & operator<< (std::ostream &ostream, ControlMode mode)
constexpr ControlMode operator & (ControlMode left, ControlMode right)
constexpr ControlMode operator| (ControlMode left, ControlMode right)
constexpr ControlMode operator^ (ControlMode left, ControlMode right)
constexpr ControlMode operator~ (ControlMode mode)
constexpr ControlMode & operator &= (ControlMode &left, ControlMode right)
constexpr ControlMode & operator|= (ControlMode &left, ControlMode right)
bool findArmIdInResourceId (const std::string &resource_id, std::string *arm_id)
ResourceWithClaimsMap getResourceMap (const std::list< hardware_interface::ControllerInfo > &info)
bool getArmClaimedMap (ResourceWithClaimsMap &resource_map, ArmClaimedMap &arm_claim_map)
ControlMode getControlMode (const std::string &arm_id, ArmClaimedMap &arm_claim_map)
Typedef Documentation
ArmClaimedMap
using franka_hw::ArmClaimedMap = typedef std::map<std::string, ResourceClaims>
Definition at line 26 of file resource_helpers.h.
ResourceWithClaimsMap
using franka_hw::ResourceWithClaimsMap = typedef std::map<std::string, std::vector<std::vector<std::string> >>
Definition at line 16 of file resource_helpers.h.
Enumeration Type Documentation
ControlMode
enum franka_hw::ControlMode [strong]
Enumerator
None
JointTorque
JointPosition
JointVelocity
CartesianVelocity
CartesianPose
Definition at line 10 of file control_mode.h.
                       {
  None = 0,
  JointTorque = (1 << 0),
  JointPosition = (1 << 1),
  JointVelocity = (1 << 2),
  CartesianVelocity = (1 << 3),
  CartesianPose = (1 << 4),
};
Function Documentation
findArmIdInResourceId()
bool franka_hw::findArmIdInResourceId (const std::string & resource_id, std::string * arm_id)
Definition at line 9 of file resource_helpers.cpp.
Referenced by getArmClaimedMap().
                                                                            {
  size_t position = resource_id.rfind("_joint");
  if (position != std::string::npos && position > 0) {
    *arm_id = resource_id.substr(0, position);
    return true;
  }
  position = resource_id.rfind("_robot");
  if (position != std::string::npos && position > 0) {
    *arm_id = resource_id.substr(0, position);
    return true;
  }
  return false;
}
getArmClaimedMap()
bool franka_hw::getArmClaimedMap (ResourceWithClaimsMap & resource_map, ArmClaimedMap & arm_claim_map)
Definition at line 41 of file resource_helpers.cpp.
References franka_hw::ResourceClaims::cartesian_pose_claims, franka_hw::ResourceClaims::cartesian_velocity_claims, findArmIdInResourceId(), franka_hw::ResourceClaims::joint_position_claims, franka_hw::ResourceClaims::joint_torque_claims, and franka_hw::ResourceClaims::joint_velocity_claims.
Referenced by franka_hw::FrankaHW::checkForConflict(), and franka_hw::FrankaHW::prepareSwitch().
                                                                                         {
  std::string current_arm_id;
  // check for conflicts between joint and cartesian level for each arm.
  // Valid claims are torque claims on joint level in combination with either
  // 7 non-torque claims on joint_level or one claim on cartesian level.
  for (auto map_it = resource_map.begin(); map_it != resource_map.end(); map_it++) {
    if (!findArmIdInResourceId(map_it->first, &current_arm_id)) {
      ROS_ERROR_STREAM("Could not find arm_id in resource "
                       << map_it->first
                       << ". Conflict! Name joints as '<robot_arm_id>_joint<jointnumber>'");
      return false;
    }
    ResourceClaims new_claim;
    for (auto claimed_by : map_it->second) {
      if (claimed_by[2] == "hardware_interface::EffortJointInterface") {
        new_claim.joint_torque_claims++;
      } else if (claimed_by[2] == "hardware_interface::PositionJointInterface") {
        new_claim.joint_position_claims++;
      } else if (claimed_by[2] == "hardware_interface::VelocityJointInterface") {
        new_claim.joint_velocity_claims++;
      } else if (claimed_by[2] == "franka_hw::FrankaPoseCartesianInterface") {
        new_claim.cartesian_pose_claims++;
      } else if (claimed_by[2] == "franka_hw::FrankaVelocityCartesianInterface") {
        new_claim.cartesian_velocity_claims++;
      } else {
        return false;
      }
    }
    arm_claim_map[current_arm_id].joint_position_claims += new_claim.joint_position_claims;
    arm_claim_map[current_arm_id].joint_velocity_claims += new_claim.joint_velocity_claims;
    arm_claim_map[current_arm_id].joint_torque_claims += new_claim.joint_torque_claims;
    arm_claim_map[current_arm_id].cartesian_velocity_claims += new_claim.cartesian_velocity_claims;
    arm_claim_map[current_arm_id].cartesian_pose_claims += new_claim.cartesian_pose_claims;
  }
  return true;
}
getControlMode()
ControlMode franka_hw::getControlMode (const std::string & arm_id, ArmClaimedMap & arm_claim_map)
Definition at line 79 of file resource_helpers.cpp.
References CartesianPose, CartesianVelocity, JointPosition, JointTorque, JointVelocity, and None.
Referenced by franka_hw::FrankaHW::prepareSwitch().
                                                                                  {
  ControlMode control_mode = ControlMode::None;
  if (arm_claim_map[arm_id].joint_position_claims > 0 &&
      arm_claim_map[arm_id].joint_velocity_claims == 0 &&
      arm_claim_map[arm_id].joint_torque_claims == 0 &&
      arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
      arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointPosition;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims > 0 &&
             arm_claim_map[arm_id].joint_torque_claims == 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointVelocity;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims > 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointTorque;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims == 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims > 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::CartesianPose;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims == 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims > 0) {
    control_mode = ControlMode::CartesianVelocity;
  } else if (arm_claim_map[arm_id].joint_position_claims > 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims > 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointTorque | ControlMode::JointPosition;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims > 0 &&
             arm_claim_map[arm_id].joint_torque_claims > 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointTorque | ControlMode::JointVelocity;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims > 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims > 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims == 0) {
    control_mode = ControlMode::JointTorque | ControlMode::CartesianPose;
  } else if (arm_claim_map[arm_id].joint_position_claims == 0 &&
             arm_claim_map[arm_id].joint_velocity_claims == 0 &&
             arm_claim_map[arm_id].joint_torque_claims > 0 &&
             arm_claim_map[arm_id].cartesian_pose_claims == 0 &&
             arm_claim_map[arm_id].cartesian_velocity_claims > 0) {
    control_mode = ControlMode::JointTorque | ControlMode::CartesianVelocity;
  }
  return control_mode;
}
getResourceMap()
ResourceWithClaimsMap franka_hw::getResourceMap (const std::list< hardware_interface::ControllerInfo > & info)
Definition at line 23 of file resource_helpers.cpp.
Referenced by franka_hw::FrankaHW::checkForConflict(), and franka_hw::FrankaHW::prepareSwitch().
                                                                                            {
  ResourceWithClaimsMap resource_map;
  for (auto& item : info) {
    const std::vector<hardware_interface::InterfaceResources>& c_res = item.claimed_resources;
    for (auto& resource_set : c_res) {
      const std::set<std::string>& iface_resources = resource_set.resources;
      for (auto& resource : iface_resources) {
        std::vector<std::string> claiming_controller(3);
        claiming_controller[0] = item.name;
        claiming_controller[1] = item.type;
        claiming_controller[2] = resource_set.hardware_interface;
        resource_map[resource].push_back(claiming_controller);
      }
    }
  }
  return resource_map;
}
operator &()
constexpr ControlMode franka_hw::operator& (ControlMode left, ControlMode right)
Definition at line 22 of file control_mode.h.
                                                                     {
  return static_cast<ControlMode>(static_cast<std::underlying_type_t<ControlMode>>(left) &
                                  static_cast<std::underlying_type_t<ControlMode>>(right));
}
operator &=()
constexpr ControlMode& franka_hw::operator&= (ControlMode & left, ControlMode right)
Definition at line 41 of file control_mode.h.
                                                                        {
  return left = left & right;
}
operator<<()
std::ostream & franka_hw::operator<< (std::ostream & ostream, ControlMode mode)
Definition at line 12 of file control_mode.cpp.
References CartesianPose, CartesianVelocity, JointPosition, JointTorque, JointVelocity, and None.
                                                              {
  if (mode == ControlMode::None) {
    ostream << "<none>";
  } else {
    std::vector<std::string> names;
    if ((mode & ControlMode::JointTorque) != ControlMode::None) {
      names.emplace_back("joint_torque");
    }
    if ((mode & ControlMode::JointPosition) != ControlMode::None) {
      names.emplace_back("joint_position");
    }
    if ((mode & ControlMode::JointVelocity) != ControlMode::None) {
      names.emplace_back("joint_velocity");
    }
    if ((mode & ControlMode::CartesianVelocity) != ControlMode::None) {
      names.emplace_back("cartesian_velocity");
    }
    if ((mode & ControlMode::CartesianPose) != ControlMode::None) {
      names.emplace_back("cartesian_pose");
    }
    std::copy(names.cbegin(), names.cend() - 1, std::ostream_iterator<std::string>(ostream, ", "));
    ostream << names.back();
  }
  return ostream;
}
operator^()
constexpr ControlMode franka_hw::operator^ (ControlMode left, ControlMode right)
Definition at line 32 of file control_mode.h.
                                                                     {
  return static_cast<ControlMode>(static_cast<std::underlying_type_t<ControlMode>>(left) ^
                                  static_cast<std::underlying_type_t<ControlMode>>(right));
}
operator|()
constexpr ControlMode franka_hw::operator| (ControlMode left, ControlMode right)
Definition at line 27 of file control_mode.h.
                                                                     {
  return static_cast<ControlMode>(static_cast<std::underlying_type_t<ControlMode>>(left) |
                                  static_cast<std::underlying_type_t<ControlMode>>(right));
}
operator|=()
constexpr ControlMode& franka_hw::operator|= (ControlMode & left, ControlMode right)
Definition at line 45 of file control_mode.h.
                                                                        {
  return left = left | right;
}
operator ()
constexpr ControlMode franka_hw::operator~ (ControlMode mode)
Definition at line 37 of file control_mode.h.
                                                  {
  return static_cast<ControlMode>(~static_cast<std::underlying_type_t<ControlMode>>(mode));
}