smacc_sm_reference_library/sm_panda_moveit/libfranka/examples/print_joint_poses.cpp File Reference
#include <iostream>
#include <iterator>
#include <franka/exception.h>
#include <franka/model.h>
Functions
template<class T , size_t N>
std::ostream & operator<< (std::ostream &ostream, const std::array< T, N > &array)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 24 of file print_joint_poses.cpp.
References franka::kEndEffector, franka::kJoint1, franka::Robot::loadModel(), franka::Model::pose(), and franka::Robot::readOnce().
                                {
  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <robot-hostname>" << std::endl;
    return -1;
  }
  try {
    franka::Robot robot(argv[1]);
    franka::RobotState state = robot.readOnce();
    franka::Model model(robot.loadModel());
    for (franka::Frame frame = franka::Frame::kJoint1; frame <=
      franka::Frame::kEndEffector;
         frame++) {
      std::cout << model.pose(frame, state) << std::endl;
    }
  } catch (franka::Exception const& e) {
    std::cout << e.what() << std::endl;
    return -1;
  }
  return 0;
}
operator<<()
template<class T , size_t N>
std::ostream& operator<< (std::ostream & ostream, const std::array< T, N > & array)
Definition at line 16 of file print_joint_poses.cpp.
                                                                         {
  ostream << "[";
  std::copy(array.cbegin(), array.cend() - 1, std::ostream_iterator<T>(ostream, ","));
  std::copy(array.cend() - 1, array.cend(), std::ostream_iterator<T>(ostream));
  ostream << "]";
  return ostream;
}