smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample3_unittest.cc File Reference
#include `sample3-inl.h`
#include `gtest/gtest.h`
Classes
class QueueTest
Functions
TEST_F (QueueTest, DefaultConstructor)
TEST_F (QueueTest, Dequeue)
TEST_F (QueueTest, Map)
Function Documentation
TEST_F() [1/3]
TEST_F (QueueTest , DefaultConstructor)
Definition at line 123 of file sample3_unittest.cc.
References EXPECT_EQ, QueueTest::q0_, and Queue< E >::Size().
                                      {
  // You can access data in the test fixture here.
  EXPECT_EQ(0u, q0_.Size());
}
TEST_F() [2/3]
TEST_F (QueueTest , Dequeue)
Definition at line 129 of file sample3_unittest.cc.
References ASSERT_TRUE, Queue< E >::Dequeue(), EXPECT_EQ, EXPECT_TRUE, QueueTest::q0_, QueueTest::q1_, QueueTest::q2_, and Queue< E >::Size().
                           {
  int * n = q0_.Dequeue();
  EXPECT_TRUE(n == NULL);
  n = q1_.Dequeue();
  ASSERT_TRUE(n != NULL);
  EXPECT_EQ(1, *n);
  EXPECT_EQ(0u, q1_.Size());
  delete n;
  n = q2_.Dequeue();
  ASSERT_TRUE(n != NULL);
  EXPECT_EQ(2, *n);
  EXPECT_EQ(1u, q2_.Size());
  delete n;
}
TEST_F() [3/3]
TEST_F (QueueTest , Map)
Definition at line 147 of file sample3_unittest.cc.
References QueueTest::MapTester(), QueueTest::q0_, QueueTest::q1_, and QueueTest::q2_.
                       {
  MapTester(&q0_);
  MapTester(&q1_);
  MapTester(&q2_);
}