smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample1.h File Reference
Functions
int Factorial (int n)
bool IsPrime (int n)
Function Documentation
Factorial()
int Factorial (int n)
Definition at line 37 of file sample1.cc.
Referenced by TEST(), and TEST_F().
                     {
  int result = 1;
  for (int i = 1; i <= n; i++) {
    result *= i;
  }
  return result;
}
IsPrime()
bool IsPrime (int n)
Definition at line 47 of file sample1.cc.
Referenced by TEST(), and TEST_F().
                    {
  // Trivial case 1: small numbers
  if (n <= 1) return false;
  // Trivial case 2: even numbers
  if (n % 2 == 0) return n == 2;
  // Now, we have that n is odd and n >= 3.
  // Try to divide n by every odd number i, starting from 3
  for (int i = 3; ; i += 2) {
    // We only have to try i up to the squre root of n
    if (i > n/i) break;
    // Now, we have i <= n/i < n.
    // If n is divisible by i, n is not prime.
    if (n % i == 0) return false;
  }
  // n has no integer factor in the range (1, n), and thus is prime.
  return true;
}