smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample2_unittest.cc File Reference
#include `sample2.h`
#include `gtest/gtest.h`
Functions
TEST (MyString, DefaultConstructor)
TEST (MyString, ConstructorFromCString)
TEST (MyString, CopyConstructor)
TEST (MyString, Set)
Variables
const char kHelloString [] = `Hello, world!`
Function Documentation
TEST() [1/4]
TEST (MyString , DefaultConstructor)
Definition at line 49 of file sample2_unittest.cc.
References MyString::c_string(), EXPECT_EQ, EXPECT_STREQ, MyString::Length(), and service_node_3::s.
                                   {
  const MyString s;
  // Asserts that s.c_string() returns NULL.
  //
  // <TechnicalDetails>
  //
  // If we write NULL instead of
  //
  // static_cast<const char *>(NULL)
  //
  // in this assertion, it will generate a warning on gcc 3.4. The
  // reason is that EXPECT_EQ needs to know the types of its
  // arguments in order to print them when it fails. Since NULL is
  // #defined as 0, the compiler will use the formatter function for
  // int to print it. However, gcc thinks that NULL should be used as
  // a pointer, not an int, and therefore complains.
  //
  // The root of the problem is C++'s lack of distinction between the
  // integer number 0 and the null pointer constant. Unfortunately,
  // we have to live with this fact.
  //
  // </TechnicalDetails>
  EXPECT_STREQ(NULL, s.c_string());
  EXPECT_EQ(0u, s.Length());
}
TEST() [2/4]
TEST (MyString , ConstructorFromCString)
Definition at line 80 of file sample2_unittest.cc.
References MyString::c_string(), EXPECT_EQ, kHelloString, MyString::Length(), and service_node_3::s.
                                       {
  const MyString s(kHelloString);
  EXPECT_EQ(0, strcmp(s.c_string(), kHelloString));
  EXPECT_EQ(sizeof(kHelloString)/sizeof(kHelloString[0]) - 1,
            s.Length());
}
TEST() [3/4]
TEST (MyString , CopyConstructor)
Definition at line 88 of file sample2_unittest.cc.
References MyString::c_string(), EXPECT_EQ, and kHelloString.
                                {
  const MyString s1(kHelloString);
  const MyString s2 = s1;
  EXPECT_EQ(0, strcmp(s2.c_string(), kHelloString));
}
TEST() [4/4]
TEST (MyString , Set)
Definition at line 95 of file sample2_unittest.cc.
References MyString::c_string(), EXPECT_EQ, EXPECT_STREQ, kHelloString, service_node_3::s, and MyString::Set().
                    {
  MyString s;
  s.Set(kHelloString);
  EXPECT_EQ(0, strcmp(s.c_string(), kHelloString));
  // Set should work when the input pointer is the same as the one
  // already in the MyString object.
  s.Set(s.c_string());
  EXPECT_EQ(0, strcmp(s.c_string(), kHelloString));
  // Can we set the MyString to NULL?
  s.Set(NULL);
  EXPECT_STREQ(NULL, s.c_string());
}
Variable Documentation
kHelloString
const char kHelloString[] = `Hello, world!`
Definition at line 77 of file sample2_unittest.cc.
Referenced by TEST().