smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/samples/sample1_unittest.cc File Reference
#include <limits.h>
#include `sample1.h`
#include `gtest/gtest.h`
Functions
TEST (FactorialTest, Negative)
TEST (FactorialTest, Zero)
TEST (FactorialTest, Positive)
TEST (IsPrimeTest, Negative)
TEST (IsPrimeTest, Trivial)
TEST (IsPrimeTest, Positive)
Function Documentation
TEST() [1/6]
TEST (FactorialTest , Negative)
Definition at line 79 of file sample1_unittest.cc.
References EXPECT_EQ, EXPECT_GT, and Factorial().
                              {
  // This test is named "Negative", and belongs to the "FactorialTest"
  // test case.
  EXPECT_EQ(1, Factorial(-5));
  EXPECT_EQ(1, Factorial(-1));
  EXPECT_GT(Factorial(-10), 0);
  // <TechnicalDetails>
  //
  // EXPECT_EQ(expected, actual) is the same as
  //
  // EXPECT_TRUE((expected) == (actual))
  //
  // except that it will print both the expected value and the actual
  // value when the assertion fails. This is very helpful for
  // debugging. Therefore in this case EXPECT_EQ is preferred.
  //
  // On the other hand, EXPECT_TRUE accepts any Boolean expression,
  // and is thus more general.
  //
  // </TechnicalDetails>
}
TEST() [2/6]
TEST (FactorialTest , Zero)
Definition at line 103 of file sample1_unittest.cc.
References EXPECT_EQ, and Factorial().
                          {
  EXPECT_EQ(1, Factorial(0));
}
TEST() [3/6]
TEST (FactorialTest , Positive)
Definition at line 108 of file sample1_unittest.cc.
References EXPECT_EQ, and Factorial().
                              {
  EXPECT_EQ(1, Factorial(1));
  EXPECT_EQ(2, Factorial(2));
  EXPECT_EQ(6, Factorial(3));
  EXPECT_EQ(40320, Factorial(8));
}
TEST() [4/6]
TEST (IsPrimeTest , Negative)
Definition at line 119 of file sample1_unittest.cc.
References EXPECT_FALSE, and IsPrime().
                            {
  // This test belongs to the IsPrimeTest test case.
  EXPECT_FALSE(IsPrime(-1));
  EXPECT_FALSE(IsPrime(-2));
  EXPECT_FALSE(IsPrime(INT_MIN));
}
TEST() [5/6]
TEST (IsPrimeTest , Trivial)
Definition at line 128 of file sample1_unittest.cc.
References EXPECT_FALSE, EXPECT_TRUE, and IsPrime().
                           {
  EXPECT_FALSE(IsPrime(0));
  EXPECT_FALSE(IsPrime(1));
  EXPECT_TRUE(IsPrime(2));
  EXPECT_TRUE(IsPrime(3));
}
TEST() [6/6]
TEST (IsPrimeTest , Positive)
Definition at line 136 of file sample1_unittest.cc.
References EXPECT_FALSE, EXPECT_TRUE, and IsPrime().
                            {
  EXPECT_FALSE(IsPrime(4));
  EXPECT_TRUE(IsPrime(5));
  EXPECT_FALSE(IsPrime(6));
  EXPECT_TRUE(IsPrime(23));
}