smacc_sm_reference_library/sm_panda_moveit/libfranka/3rdparty/googletest/googletest/xcode/Samples/FrameworkSample/widget_test.cc File Reference
#include <string>
#include `gtest/gtest.h`
#include <Widget/widget.h>
Functions
TEST (WidgetInitializerTest, TestConstructor)
TEST (WidgetInitializerTest, TestConversion)
Function Documentation
TEST() [1/2]
TEST (WidgetInitializerTest , TestConstructor)
Definition at line 45 of file widget_test.cc.
References EXPECT_EQ, EXPECT_FLOAT_EQ, Widget::GetFloatValue(), and Widget::GetStringValue().
                                             {
  Widget widget(1.0f, "name");
  EXPECT_FLOAT_EQ(1.0f, widget.GetFloatValue());
  EXPECT_EQ(std::string("name"), widget.GetStringValue());
}
TEST() [2/2]
TEST (WidgetInitializerTest , TestConversion)
Definition at line 53 of file widget_test.cc.
References EXPECT_EQ, EXPECT_STREQ, Widget::GetCharPtrValue(), and Widget::GetIntValue().
                                            {
  Widget widget(1.0f, "name");
  EXPECT_EQ(1, widget.GetIntValue());
  size_t max_size = 128;
  char buffer[max_size];
  widget.GetCharPtrValue(buffer, max_size);
  EXPECT_STREQ("name", buffer);
}