cl_ros_timer::CbTimerCountdownLoop Class Reference
#include <cb_timer_countdown_loop.h>
Public Member Functions
CbTimerCountdownLoop (unsigned long triggerTickCount)
virtual void onEntry () override
virtual void onExit () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
Private Member Functions
void onClientTimerTickCallback ()
Private Attributes
unsigned long tickCounter_
unsigned long tickTriggerCount_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc::SmaccSignal< void()> onTimerTick_
Detailed Description
Definition at line 9 of file cb_timer_countdown_loop.h.
Constructor & Destructor Documentation
CbTimerCountdownLoop()
cl_ros_timer::CbTimerCountdownLoop::CbTimerCountdownLoop (unsigned long triggerTickCount)
Definition at line 6 of file cb_timer_countdown_loop.cpp.
    : tickTriggerCount_(triggerTickCount),
      tickCounter_(0)
{
}
Member Function Documentation
configureEventSourceTypes()
template<typename TObjectTag , typename TDerived >
void cl_ros_timer::CbTimerCountdownLoop::configureEventSourceTypes () [inline]
Definition at line 18 of file cb_timer_countdown_loop.h.
References postCountDownEvent_.
    {
        this->postCountDownEvent_ = [=]() {
            this->template postEvent<EvTimer<TDerived, TObjectTag>>();
        };
    }
onClientTimerTickCallback()
void cl_ros_timer::CbTimerCountdownLoop::onClientTimerTickCallback () [private]
Definition at line 12 of file cb_timer_countdown_loop.cpp.
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
{
    tickCounter_++;
    if (tickCounter_ % tickTriggerCount_ == 0)
    {
        onTimerTick_();
        postCountDownEvent_();
    }
}
onEntry()
void cl_ros_timer::CbTimerCountdownLoop::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_timer_countdown_loop.cpp.
References onClientTimerTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), smacc::SmaccClientBehavior::requiresClient(), and timerClient_.
{
    this->requiresClient(timerClient_);
    timerClient_->onTimerTick(&
      CbTimerCountdownLoop::onClientTimerTickCallback, this);
}
onExit()
void cl_ros_timer::CbTimerCountdownLoop::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 29 of file cb_timer_countdown_loop.cpp.
{
}
onTimerTick()
template<typename T >
boost::signals2::connection cl_ros_timer::CbTimerCountdownLoop::onTimerTick (void(T::*)() callback, T * object) [inline]
Definition at line 26 of file cb_timer_countdown_loop.h.
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::SmaccClientBehavior::getStateMachine(), and onTimerTick_.
    {
        return this->getStateMachine()->createSignalConnection(
      onTimerTick_, callback, object);
    }
Member Data Documentation
onTimerTick_
smacc::SmaccSignal<void()> cl_ros_timer::CbTimerCountdownLoop::onTimerTick_ [private]
Definition at line 37 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback(), and onTimerTick().
postCountDownEvent_
std::function<void()> cl_ros_timer::CbTimerCountdownLoop::postCountDownEvent_ [private]
Definition at line 36 of file cb_timer_countdown_loop.h.
Referenced by configureEventSourceTypes(), and onClientTimerTickCallback().
tickCounter_
unsigned long cl_ros_timer::CbTimerCountdownLoop::tickCounter_ [private]
Definition at line 32 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback().
tickTriggerCount_
unsigned long cl_ros_timer::CbTimerCountdownLoop::tickTriggerCount_ [private]
Definition at line 33 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback().
timerClient_
ClRosTimer* cl_ros_timer::CbTimerCountdownLoop::timerClient_ [private]
Definition at line 35 of file cb_timer_countdown_loop.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_countdown_loop.h
smacc_client_library/ros_timer_client/src/ros_timer_client/cb_timer_countdown_loop.cpp