move_group_interface_client::CbAttachObject Class Reference
#include <cb_attach_object.h>
Public Member Functions
CbAttachObject (std::string targetObjectName)
CbAttachObject ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
std::string targetObjectName_
Additional Inherited Members
Detailed Description
Definition at line 8 of file cb_attach_object.h.
Constructor & Destructor Documentation
CbAttachObject() [1/2]
move_group_interface_client::CbAttachObject::CbAttachObject (std::string targetObjectName)
Definition at line 6 of file cb_attach_object.cpp.
        : targetObjectName_(targetObjectName)
    {
    }
CbAttachObject() [2/2]
move_group_interface_client::CbAttachObject::CbAttachObject ()
Definition at line 11 of file cb_attach_object.cpp.
    {
        
    }
Member Function Documentation
onEntry()
void move_group_interface_client::CbAttachObject::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 16 of file cb_attach_object.cpp.
References move_group_interface_client::GraspingComponent::currentAttachedObjectName, move_group_interface_client::GraspingComponent::fingerTipNames, move_group_interface_client::GraspingComponent::getGraspingObject(), move_group_interface_client::ClMoveGroup::moveGroupClientInterface, move_group_interface_client::ClMoveGroup::planningSceneInterface, smacc::ISmaccClientBehavior::requiresClient(), smacc::ISmaccClientBehavior::requiresComponent(), and targetObjectName_.
    {
        move_group_interface_client::ClMoveGroup *moveGroup;
        this->requiresClient(moveGroup);
        move_group_interface_client::GraspingComponent *
      graspingComponent;
        this->requiresComponent(graspingComponent);
        // auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
        moveit_msgs::CollisionObject targetCollisionObject;
        bool found = graspingComponent->getGraspingObject(
      targetObjectName_, targetCollisionObject);
        if (found)
        {
            targetCollisionObject.operation = moveit_msgs::CollisionObject::ADD;
            targetCollisionObject.header.stamp = ros::Time::now();
            moveGroup->planningSceneInterface.applyCollisionObject(
      targetCollisionObject);
            // collisionObjects.push_back(cubeCollision);
            graspingComponent->currentAttachedObjectName =
      targetObjectName_;
            moveGroup->moveGroupClientInterface.attachObject(
      targetObjectName_, "gripper_link", graspingComponent->
      fingerTipNames);
        }
    }
onExit()
void move_group_interface_client::CbAttachObject::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 43 of file cb_attach_object.cpp.
    {
    }
Member Data Documentation
targetObjectName_
std::string move_group_interface_client::CbAttachObject::targetObjectName_
Definition at line 19 of file cb_attach_object.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_attach_object.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_attach_object.cpp