sm_moveit_3::StForwardNextTable Struct Reference
#include <st_forward.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, SS2::SsPlaceObject, SUCCESS >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StUndoIncorrectForward, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void configureGlobalNavigation ()
void configureForwardBehavior ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_forward.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, SS2::SsPlaceObject, SUCCESS>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StUndoIncorrectForward, ABORT> > sm_moveit_3::StForwardNextTable::reactions
Definition at line 14 of file st_forward.h.
Member Function Documentation
configureForwardBehavior()
void sm_moveit_3::StForwardNextTable::configureForwardBehavior () [inline]
Definition at line 60 of file st_forward.h.
References smacc::ISmaccClient::getComponent(), smacc::ISmaccState::requiresClient(), and cl_move_base_z::Pose::toPoseMsg().
  {
    ClMoveBaseZ *moveBaseClient_;
    this->requiresClient(moveBaseClient_);
    auto pose = moveBaseClient_->getComponent<Pose>();
    auto currentPose = pose->toPoseMsg();
    auto offset = 0.15;
    auto forwardDistance = 2.0;
    double dist;
    
    dist = forwardDistance + offset;
    auto forwardBh = this->getOrthogonal<OrNavigation>()->getClientBehavior<CbNavigateForward>();
    forwardBh->forwardDistance = dist;
  }
configureGlobalNavigation()
void sm_moveit_3::StForwardNextTable::configureGlobalNavigation () [inline]
Definition at line 29 of file st_forward.h.
References smacc::ISmaccClient::getComponent(), smacc::ISmaccState::requiresClient(), and cl_move_base_z::Pose::toPoseMsg().
Referenced by runtimeConfigure().
  {
    ClMoveBaseZ *moveBaseClient_;
    this->requiresClient(moveBaseClient_);
    auto pose = moveBaseClient_->getComponent<Pose>();
    auto currentPose = pose->toPoseMsg();
    geometry_msgs::Point goalPosition;
    goalPosition.z = 0;
    goalPosition.y = 0;
    double yaw = 0;
    double forwardOffset = 1.2;
    if (currentPose.position.x < -0.2) // robot is at negative x-axis side
    {
      // target is at positive side, at point x=0
      goalPosition.x = forwardOffset;
      yaw = 0;
    }
    else // the robot in at positive x-axis side
    {
      // target is at negative x-axis side at point x = -1
      goalPosition.x = -forwardOffset;
      yaw = -M_PI;
    }
    auto globalNavigationBh = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbNavigateGlobalPosition>();
    globalNavigationBh->goalPosition = goalPosition;
    globalNavigationBh->goalYaw = yaw;
  }
runtimeConfigure()
void sm_moveit_3::StForwardNextTable::runtimeConfigure () [inline]
Definition at line 23 of file st_forward.h.
References configureGlobalNavigation().
  {
    configureGlobalNavigation();
    //configureForwardBehavior();
  }
staticConfigure()
static void sm_moveit_3::StForwardNextTable::staticConfigure () [inline], [static]
Definition at line 17 of file st_forward.h.
  {
     configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
    //configure_orthogonal<OrNavigation, CbNavigateForward>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_3/include/sm_moveit_3/states/st_forward.h