sm_moveit_2::place_states::StPlaceApproach Struct Reference
#include <st_place_approach.h>
Public Types
typedef mpl::list< Transition< MoveGroupMotionExecutionSucceded< ClMoveGroup, OrArm >, StOpenGripper >, Transition< MoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StPlaceApproach, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_place_approach.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<MoveGroupMotionExecutionSucceded<ClMoveGroup, OrArm>, StOpenGripper>, Transition<MoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StPlaceApproach, ABORT> > sm_moveit_2::place_states::StPlaceApproach::reactions
Definition at line 16 of file st_place_approach.h.
Member Function Documentation
onExit()
void sm_moveit_2::place_states::StPlaceApproach::onExit () [inline]
Definition at line 33 of file st_place_approach.h.
References smacc::ISmaccState::requiresClient().
    {
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        perceptionSystem->nextCube();
    }
runtimeConfigure()
void sm_moveit_2::place_states::StPlaceApproach::runtimeConfigure () [inline]
Definition at line 26 of file st_place_approach.h.
References move_group_interface_client::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StPlaceApproach, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StPlaceApproach::throwSequenceFinishedEvent, this);
    }
staticConfigure()
static void sm_moveit_2::place_states::StPlaceApproach::staticConfigure () [inline], [static]
Definition at line 19 of file st_place_approach.h.
    {
        geometry_msgs::Vector3 offset;
        offset.z = -0.12;
        configure_orthogonal<OrArm, CbMoveCartesianRelative>(offset);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_2/include/sm_moveit_2/states/place_states/st_place_approach.h