smacc::introspection::StateBehaviorHandler Class Reference
#include <smacc_state_info.h>
Public Member Functions
void configureStateBehavior (std::shared_ptr< smacc::StateBehavior > sb)
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
Public Attributes
std::shared_ptr< smacc::introspection::SmaccStateBehaviorInfo > sbInfo_
Private Attributes
std::vector< CallbackFunctor > callbacks_
Detailed Description
Definition at line 67 of file smacc_state_info.h.
Member Function Documentation
template<typename TEv > void smacc::introspection::StateBehaviorHandler::addInputEvent ()
Definition at line 53 of file smacc_state_behavior_impl.h.
References smacc::introspection::demangleType(), smacc::introspection::CallbackFunctor::fn, and smacc::introspection::TypeInfo::getFromStdTypeInfo().
{
    CallbackFunctor functor;
    functor.fn = [=](std::shared_ptr<smacc::StateBehavior> sb) {
        ROS_INFO("[%s] State Behavior adding input event: %s", demangleType(
      sbInfo_->stateBehaviorType).c_str(), demangledTypeName<TEv>().c_str());
        sb->addInputEvent<TEv>();
    };
    this->callbacks_.push_back(functor);
    auto evtype = TypeInfo::getFromStdTypeInfo(typeid(TEv));
    auto evinfo = std::make_shared<SmaccEventInfo>(evtype);
    EventLabel<TEv>(evinfo->label);
    sbInfo_->sourceEventTypes.push_back(evinfo);
}
void smacc::introspection::StateBehaviorHandler::configureStateBehavior (std::shared_ptr< smacc::StateBehavior > sb)
Definition at line 37 of file state_behavior.cpp.
{
    for (auto callback : this->callbacks_)
    {
        callback.fn(sb);
    }
}
template<typename TEv > void smacc::introspection::StateBehaviorHandler::setOutputEvent ()
Definition at line 71 of file smacc_state_behavior_impl.h.
References smacc::introspection::demangleType(), and smacc::introspection::CallbackFunctor::fn.
{
    CallbackFunctor functor;
    functor.fn = [=](std::shared_ptr<smacc::StateBehavior> sb) {
        ROS_INFO("[%s] State Behavior setting output event: %s", demangleType(
      sbInfo_->stateBehaviorType).c_str(), demangledTypeName<TEv>().c_str());
        sb->setOutputEvent<TEv>();
    };
    this->callbacks_.push_back(functor);
}
Member Data Documentation
std::vector<CallbackFunctor> smacc::introspection::StateBehaviorHandler::callbacks_ [private]
Definition at line 70 of file smacc_state_info.h.
std::shared_ptr<smacc::introspection::SmaccStateBehaviorInfo> smacc::introspection::StateBehaviorHandler::sbInfo_
Definition at line 81 of file smacc_state_info.h.
The documentation for this class was generated from the following files:
smacc/include/smacc/introspection/smacc_state_info.h
smacc/include/smacc/impl/smacc_state_behavior_impl.h
smacc/src/smacc/state_behavior.cpp