moveit_z_client::CbMoveCartesianRelative Class Reference
#include <cb_move_cartesian_relative.h>
Public Member Functions
CbMoveCartesianRelative ()
CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
virtual void onEntry () override
virtual void onExit () override
void moveRelativeCartesian (moveit::planning_interface::MoveGroupInterface *movegroupClient, geometry_msgs::Vector3 &offset)
Public Attributes
geometry_msgs::Vector3 offset_
boost::optional< double > scalingFactor_
boost::optional< std::string > group_
ClMoveGroup * moveGroupSmaccClient_
Detailed Description
Definition at line 14 of file cb_move_cartesian_relative.h.
Constructor & Destructor Documentation
CbMoveCartesianRelative() [1/2]
moveit_z_client::CbMoveCartesianRelative::CbMoveCartesianRelative ()
Definition at line 12 of file cb_move_cartesian_relative.cpp.
{
}
CbMoveCartesianRelative() [2/2]
moveit_z_client::CbMoveCartesianRelative::CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
Definition at line 16 of file cb_move_cartesian_relative.cpp.
                                                                            :
      offset_(offset)
{
}
Member Function Documentation
moveRelativeCartesian()
void moveit_z_client::CbMoveCartesianRelative::moveRelativeCartesian (moveit::planning_interface::MoveGroupInterface * movegroupClient, geometry_msgs::Vector3 & offset)
Definition at line 45 of file cb_move_cartesian_relative.cpp.
References moveGroupSmaccClient_, moveit_z_client::ClMoveGroup::postEventMotionExecutionFailed(), moveit_z_client::ClMoveGroup::postEventMotionExecutionSucceded(), and scalingFactor_.
Referenced by onEntry().
{
  std::vector<geometry_msgs::Pose> waypoints;
  // this one was working fine but the issue is that for relative motions it grows up on ABORT-State-Loop
       pattern
  auto referenceStartPose = movegroupClient->getPoseTarget();
  //auto referenceStartPose = this->moveGroupClientInterface.getCurrentPose();
  ROS_INFO_STREAM("[CbMoveCartesianRelative] RELATIVE MOTION, SOURCE POSE: " << referenceStartPose);
  ROS_INFO_STREAM("[CbMoveCartesianRelative] Offset: " << offset);
  waypoints.push_back(referenceStartPose.pose); // up and out
  auto targetObjectPose = movegroupClient->getPoseTarget();
  auto endPose = referenceStartPose.pose;
  endPose.position.x += offset.x;
  endPose.position.y += offset.y;
  endPose.position.z += offset.z;
  ROS_INFO_STREAM("[CbMoveCartesianRelative] DESTINY POSE: " << endPose);
  // target_pose2.position.x -= 0.15;
  waypoints.push_back(endPose); // left
  movegroupClient->setPoseTarget(endPose);
  float scalinf = 0.5;
  if (scalingFactor_)
    scalinf = *scalingFactor_;
  ROS_INFO_STREAM("[CbMoveCartesianRelative] Using scaling factor: " << scalinf);
  movegroupClient->setMaxVelocityScalingFactor(scalinf);
  moveit_msgs::RobotTrajectory trajectory;
  double fraction = movegroupClient->computeCartesianPath(waypoints,
                                                          0.01, // eef_step
                                                          0.00, // jump_threshold
                                                          trajectory);
  moveit::planning_interface::MoveItErrorCode behaviorResult;
  if (fraction != 1.0 || fraction == -1)
  {
    ROS_WARN_STREAM("[CbMoveCartesianRelative] Cartesian plan joint-continuity percentaje. Execution
       skipped because not 100% of cartesian motion: " << fraction*100<<"%");
    behaviorResult = moveit::planning_interface::MoveItErrorCode::PLANNING_FAILED;
  }
  else
  {
    ROS_INFO_STREAM("[CbMoveCartesianRelative] Cartesian plan joint-continuity percentaje: " << fraction);
    moveit::planning_interface::MoveGroupInterface::Plan grasp_pose_plan;
    // grasp_pose_plan.start_state_ = *(moveGroupInterface.getCurrentState());
    grasp_pose_plan.trajectory_ = trajectory;
    behaviorResult = movegroupClient->execute(grasp_pose_plan);
  }
  if (behaviorResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
  {
    ROS_INFO("[CbMoveCartesianRelative] relative motion execution succedded: fraction %lf.", fraction);
    moveGroupSmaccClient_->postEventMotionExecutionSucceded
      ();
  }
  else
  {
    movegroupClient->setPoseTarget(referenceStartPose); // undo changes since we did not executed the
       motion
    ROS_INFO("[CbMoveCartesianRelative] relative motion execution failed: fraction %lf.", fraction);
    moveGroupSmaccClient_->postEventMotionExecutionFailed
      ();
  }
}
onEntry()
void moveit_z_client::CbMoveCartesianRelative::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 20 of file cb_move_cartesian_relative.cpp.
References group_, moveit_z_client::ClMoveGroup::moveGroupClientInterface, moveGroupSmaccClient_, moveRelativeCartesian(), offset_, and smacc::SmaccClientBehavior::requiresClient().
{
  this->requiresClient(moveGroupSmaccClient_);
  if (this->group_)
  {
    auto res = std::async(std::launch::async, [=] {
      moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
      this->moveRelativeCartesian(&move_group, offset_);
    });
  }
  else
  {
    auto res = std::async(std::launch::async, [=] {
      this->moveRelativeCartesian(&moveGroupSmaccClient_->
      moveGroupClientInterface, offset_);
    });
  }
}
onExit()
void moveit_z_client::CbMoveCartesianRelative::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 39 of file cb_move_cartesian_relative.cpp.
{
    
}
Member Data Documentation
group_
boost::optional<std::string> moveit_z_client::CbMoveCartesianRelative::group_
Definition at line 21 of file cb_move_cartesian_relative.h.
Referenced by onEntry().
moveGroupSmaccClient_
ClMoveGroup* moveit_z_client::CbMoveCartesianRelative::moveGroupSmaccClient_
Definition at line 35 of file cb_move_cartesian_relative.h.
Referenced by moveRelativeCartesian(), and onEntry().
offset_
geometry_msgs::Vector3 moveit_z_client::CbMoveCartesianRelative::offset_
Definition at line 17 of file cb_move_cartesian_relative.h.
Referenced by onEntry().
scalingFactor_
boost::optional<double> moveit_z_client::CbMoveCartesianRelative::scalingFactor_
Definition at line 19 of file cb_move_cartesian_relative.h.
Referenced by moveRelativeCartesian().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_cartesian_relative.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_cartesian_relative.cpp