cl_ros_timer_client::CbTimer Class Reference
#include <cb_ros_timer.h>
Public Member Functions
virtual void onEntry () override
virtual void onExit () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
void onClientTimerTickCallback ()
Private Attributes
ClRosTimer * timerClient_
std::function< void()> postTimerEvent_
boost::signals2::scoped_connection c_
Detailed Description
Definition at line 8 of file cb_ros_timer.h.
Member Function Documentation
template<typename TObjectTag , typename TDerived > void cl_ros_timer_client::CbTimer::configureEventSourceTypes () [inline]
Definition at line 15 of file cb_ros_timer.h.
References onClientTimerTickCallback(), and postTimerEvent_.
  {
    this->postTimerEvent_ = [=]() {
      this->template postEvent<EvTimer<TDerived, TObjectTag>>();
    };
  }
void cl_ros_timer_client::CbTimer::onClientTimerTickCallback ()
Definition at line 12 of file cb_timer.cpp.
References postTimerEvent_.
Referenced by configureEventSourceTypes(), and onEntry().
{
    this->postTimerEvent_();
}
void cl_ros_timer_client::CbTimer::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 5 of file cb_timer.cpp.
References onClientTimerTickCallback(), cl_ros_timer_client::ClRosTimer::onTimerTick(), smacc::SmaccClientBehavior::requiresClient(), and timerClient_.
{
    this->requiresClient(timerClient_);
    timerClient_->onTimerTick(&
      CbTimer::onClientTimerTickCallback, this);
}
void cl_ros_timer_client::CbTimer::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 17 of file cb_timer.cpp.
{
}
Member Data Documentation
boost::signals2::scoped_connection cl_ros_timer_client::CbTimer::c_ [private]
Definition at line 27 of file cb_ros_timer.h.
std::function<void()> cl_ros_timer_client::CbTimer::postTimerEvent_ [private]
Definition at line 26 of file cb_ros_timer.h.
Referenced by configureEventSourceTypes(), and onClientTimerTickCallback().
ClRosTimer* cl_ros_timer_client::CbTimer::timerClient_ [private]
Definition at line 25 of file cb_ros_timer.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_ros_timer.h
smacc_client_library/ros_timer_client/src/ros_timer_client/cb_timer.cpp