move_group_interface_client::CbMoveEndEffector Class Reference
#include <cb_move_end_effector.h>
Public Member Functions
CbMoveEndEffector ()
CbMoveEndEffector (geometry_msgs::PoseStamped target_pose, std::string tip_link=``)
virtual void onEntry () override
virtual void onExit () override
virtual void update () override
std::future< moveit::planning_interface::MoveItErrorCode > planAndExecuteAsync ()
Public Attributes
geometry_msgs::PoseStamped targetPose
std::string tip_link_
boost::optional< std::string > group_
Protected Member Functions
bool moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, geometry_msgs::PoseStamped &targetObjectPose)
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 14 of file cb_move_end_effector.h.
Constructor & Destructor Documentation
CbMoveEndEffector() [1/2]
move_group_interface_client::CbMoveEndEffector::CbMoveEndEffector ()
Definition at line 14 of file cb_move_end_effector.cpp.
{
}
CbMoveEndEffector() [2/2]
move_group_interface_client::CbMoveEndEffector::CbMoveEndEffector (geometry_msgs::PoseStamped target_pose, std::string tip_link = ``)
Definition at line 18 of file cb_move_end_effector.cpp.
References tip_link_.
  : targetPose(target_pose)
{
  tip_link_ = tip_link;
}
Member Function Documentation
moveToAbsolutePose()
bool move_group_interface_client::CbMoveEndEffector::moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, geometry_msgs::PoseStamped & targetObjectPose) [protected]
Definition at line 55 of file cb_move_end_effector.cpp.
References movegroupClient_, move_group_interface_client::ClMoveGroup::planningSceneInterface, move_group_interface_client::ClMoveGroup::postEventMotionExecutionFailed(), move_group_interface_client::ClMoveGroup::postEventMotionExecutionSucceded(), and tip_link_.
Referenced by onEntry().
{
  auto& planningSceneInterface = movegroupClient_->
      planningSceneInterface;
  ROS_DEBUG("[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  ros::WallDuration(1).sleep();
  moveGroupInterface.setPlanningTime(1.0);
  ROS_INFO_STREAM("[CbMoveEndEffector] Target End efector Pose: " << targetObjectPose);
  moveGroupInterface.setPoseTarget(targetObjectPose, tip_link_);
  moveGroupInterface.setPoseReferenceFrame(targetObjectPose.header.frame_id);
  moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
  bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
  ROS_INFO_NAMED("CbMoveEndEffector", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED")
      ;
  if (success)
  {
    auto executionResult = moveGroupInterface.execute(computedMotionPlan);
    if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
    {
      ROS_INFO("[CbMoveEndEffector] motion execution succedded");
      movegroupClient_->postEventMotionExecutionSucceded();
    }
    else
    {
      ROS_INFO("[CbMoveEndEffector] motion execution failed");
      movegroupClient_->postEventMotionExecutionFailed();
    }
  }
  else
  {
    ROS_INFO("[CbMoveEndEffector] motion execution failed");
    movegroupClient_->postEventMotionExecutionFailed();
  }
  ROS_DEBUG("[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  ros::WallDuration(1).sleep();
  return success;
}
onEntry()
void move_group_interface_client::CbMoveEndEffector::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 24 of file cb_move_end_effector.cpp.
References group_, movegroupClient_, move_group_interface_client::ClMoveGroup::moveGroupClientInterface, moveToAbsolutePose(), smacc::SmaccClientBehavior::requiresClient(), and targetPose.
{
  this->requiresClient(movegroupClient_);
  if (this->group_)
  {
    auto res = std::async(std::launch::async, [=] {
      ROS_DEBUG("[CbMoveEndEfector] new thread started to move absolute end effector");
      moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
      this->moveToAbsolutePose(move_group, targetPose);
      ROS_DEBUG("[CbMoveEndEfector] to move absolute end effector thread destroyed");
    });
  }
  else
  {
    auto res = std::async(std::launch::async, [=] {
      ROS_DEBUG("[CbMoveEndEfector] new thread started to move absolute end effector");
      this->moveToAbsolutePose(movegroupClient_->
      moveGroupClientInterface, targetPose);
      ROS_DEBUG("[CbMoveEndEfector] to move absolute end effector thread destroyed");
    });
  }
}
onExit()
void move_group_interface_client::CbMoveEndEffector::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 47 of file cb_move_end_effector.cpp.
{
}
planAndExecuteAsync()
std::future<moveit::planning_interface::MoveItErrorCode> move_group_interface_client::CbMoveEndEffector::planAndExecuteAsync ()
update()
void move_group_interface_client::CbMoveEndEffector::update () [override], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 51 of file cb_move_end_effector.cpp.
{
}
Member Data Documentation
group_
boost::optional<std::string> move_group_interface_client::CbMoveEndEffector::group_
Definition at line 19 of file cb_move_end_effector.h.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* move_group_interface_client::CbMoveEndEffector::movegroupClient_ [protected]
Definition at line 33 of file cb_move_end_effector.h.
Referenced by moveToAbsolutePose(), and onEntry().
targetPose
geometry_msgs::PoseStamped move_group_interface_client::CbMoveEndEffector::targetPose
Definition at line 17 of file cb_move_end_effector.h.
Referenced by onEntry().
tip_link_
std::string move_group_interface_client::CbMoveEndEffector::tip_link_
Definition at line 18 of file cb_move_end_effector.h.
Referenced by CbMoveEndEffector(), and moveToAbsolutePose().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector.cpp