sm_moveit::cl_movegroup::CbMoveJoints Class Reference
#include <cb_move_joints.h>
Public Member Functions
CbMoveJoints ()
CbMoveJoints (const std::map< std::string, double > &jointValueTarget)
virtual void onEntry () override
virtual void onExit () override
Public Attributes
std::map< std::string, double > jointValueTarget_
Private Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 18 of file cb_move_joints.h.
Constructor & Destructor Documentation
sm_moveit::cl_movegroup::CbMoveJoints::CbMoveJoints ()
Definition at line 19 of file cb_move_joints.cpp.
{
}
sm_moveit::cl_movegroup::CbMoveJoints::CbMoveJoints (const std::map< std::string, double > & jointValueTarget)
Definition at line 14 of file cb_move_joints.cpp.
    : jointValueTarget_(jointValueTarget)
{
}
Member Function Documentation
void sm_moveit::cl_movegroup::CbMoveJoints::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_move_joints.cpp.
References jointValueTarget_, movegroupClient_, sm_moveit::cl_movegroup::ClMoveGroup::moveGroupClientInterface, sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionFailed(), sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionSucceded(), and smacc::SmaccClientBehavior::requiresClient().
{
    this->requiresClient(movegroupClient_);
    auto &moveGroupInterface = movegroupClient_->
      moveGroupClientInterface;
    moveGroupInterface.setJointValueTarget(jointValueTarget_);
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
    ROS_INFO_NAMED("CbMoveJoints", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
    if (success)
    {
        auto executionResult = moveGroupInterface.execute(computedMotionPlan);
        if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
            ROS_INFO("[CbMoveJoints] motion execution succedded");
            movegroupClient_->postEventMotionExecutionSucceded
      ();
        }
        else
        {
            ROS_INFO("[CbMoveJoints] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed(
      );
        }
    }
    else
    {
        ROS_INFO("[CbMoveJoints] motion execution failed");
        movegroupClient_->postEventMotionExecutionFailed();
    }
}
void sm_moveit::cl_movegroup::CbMoveJoints::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 57 of file cb_move_joints.cpp.
{
}
Member Data Documentation
std::map<std::string, double> sm_moveit::cl_movegroup::CbMoveJoints::jointValueTarget_
Definition at line 24 of file cb_move_joints.h.
Referenced by onEntry().
ClMoveGroup* sm_moveit::cl_movegroup::CbMoveJoints::movegroupClient_ [private]
Definition at line 21 of file cb_move_joints.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_joints.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_joints.cpp