move_base_z_client::CostmapSwitch Class Reference
#include <cp_costmap_switch.h>
Public Types
enum StandardLayers { StandardLayers::GLOBAL_OBSTACLES_LAYER = 0,
StandardLayers::LOCAL_OBSTACLES_LAYER = 1,
StandardLayers::GLOBAL_INFLATED_LAYER = 2,
StandardLayers::LOCAL_INFLATED_LAYER = 3
 }
Public Member Functions
CostmapSwitch ()
virtual void initialize (smacc::ISmaccClient *owner) override
bool exists (std::string layerName)
void enable (std::string layerName)
void enable (StandardLayers layerType)
void disable (std::string layerName)
void disable (StandardLayers layerType)
void registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName=`enabled`)
Static Public Member Functions
static std::string getStandardCostmapName (StandardLayers layertype)
Static Public Attributes
static std::array< std::string, 4 > layerNames
Private Attributes
std::map< std::string, std::shared_ptr< CostmapProxy > > costmapProxies
move_base_z_client::ClMoveBaseZ * owner_
Additional Inherited Members
Detailed Description
Definition at line 24 of file cp_costmap_switch.h.
Member Enumeration Documentation
enum move_base_z_client::CostmapSwitch::StandardLayers [strong]
Enumerator
GLOBAL_OBSTACLES_LAYER
LOCAL_OBSTACLES_LAYER
GLOBAL_INFLATED_LAYER
LOCAL_INFLATED_LAYER
Definition at line 27 of file cp_costmap_switch.h.
    {
        GLOBAL_OBSTACLES_LAYER = 0,
        LOCAL_OBSTACLES_LAYER = 1,
        GLOBAL_INFLATED_LAYER = 2,
        LOCAL_INFLATED_LAYER = 3
    };
Constructor & Destructor Documentation
move_base_z_client::CostmapSwitch::CostmapSwitch ()
Definition at line 21 of file cp_costmap_switch.cpp.
{
}
Member Function Documentation
void move_base_z_client::CostmapSwitch::disable (std::string layerName)
Definition at line 64 of file cp_costmap_switch.cpp.
References costmapProxies, and exists().
Referenced by disable().
{
    if (!exists(layerName))
        return;
    costmapProxies[layerName]->setCostmapEnabled(false);
}
void move_base_z_client::CostmapSwitch::disable (StandardLayers layerType)
Definition at line 72 of file cp_costmap_switch.cpp.
References disable(), and getStandardCostmapName().
{
    this->disable(getStandardCostmapName(layerType));
}
void move_base_z_client::CostmapSwitch::enable (std::string layerName)
Definition at line 53 of file cp_costmap_switch.cpp.
References exists().
Referenced by enable().
{
    if (!exists(layerName))
        return;
}
void move_base_z_client::CostmapSwitch::enable (StandardLayers layerType)
Definition at line 59 of file cp_costmap_switch.cpp.
References enable(), and getStandardCostmapName().
{
    this->enable(getStandardCostmapName(layerType));
}
bool move_base_z_client::CostmapSwitch::exists (std::string layerName)
Definition at line 45 of file cp_costmap_switch.cpp.
References costmapProxies.
Referenced by disable(), and enable().
{
    if (!exists(layerName))
        return false;
    costmapProxies[layerName]->setCostmapEnabled(true);
}
std::string move_base_z_client::CostmapSwitch::getStandardCostmapName (StandardLayers layertype) [static]
Definition at line 40 of file cp_costmap_switch.cpp.
Referenced by disable(), enable(), and initialize().
{
    return CostmapSwitch::layerNames[(int)layertype];
}
void move_base_z_client::CostmapSwitch::initialize (smacc::ISmaccClient * owner) [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 25 of file cp_costmap_switch.cpp.
References getStandardCostmapName(), GLOBAL_INFLATED_LAYER, GLOBAL_OBSTACLES_LAYER, LOCAL_INFLATED_LAYER, LOCAL_OBSTACLES_LAYER, owner_, and registerProxyFromDynamicReconfigureServer().
{
    this->owner_ = dynamic_cast<move_base_z_client::ClMoveBaseZ *>(
      owner);
    if (this->owner_ == nullptr)
    {
        ROS_ERROR("the owner of the CostmapSwitch must be a ClMoveBaseZ");
    }
    registerProxyFromDynamicReconfigureServer(
      getStandardCostmapName(
      StandardLayers::GLOBAL_OBSTACLES_LAYER));
    registerProxyFromDynamicReconfigureServer(
      getStandardCostmapName(
      StandardLayers::LOCAL_OBSTACLES_LAYER));
    registerProxyFromDynamicReconfigureServer(
      getStandardCostmapName(
      StandardLayers::GLOBAL_INFLATED_LAYER));
    registerProxyFromDynamicReconfigureServer(
      getStandardCostmapName(
      StandardLayers::LOCAL_INFLATED_LAYER));
}
void move_base_z_client::CostmapSwitch::registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName = `enabled`)
Definition at line 14 of file cp_costmap_switch.cpp.
References costmapProxies, smacc::client_bases::SmaccActionClientBase< ActionType >::name_, and owner_.
Referenced by initialize().
{
    auto proxy = std::make_shared<CostmapProxy>(this->owner_->name_ + "/" + costmapName,
      enablePropertyName);
    costmapProxies[costmapName] = proxy;
}
Member Data Documentation
std::map<std::string, std::shared_ptr<CostmapProxy> > move_base_z_client::CostmapSwitch::costmapProxies [private]
Definition at line 56 of file cp_costmap_switch.h.
Referenced by disable(), exists(), and registerProxyFromDynamicReconfigureServer().
std::array< std::string, 4 > move_base_z_client::CostmapSwitch::layerNames [static]
Initial value:
=
        {
            "global_costmap/obstacles_layer",
            "local_costmap/obstacles_layer"
            "global_costmap/inflater_layer",
            "local_costmap/inflater_layer"}
Definition at line 35 of file cp_costmap_switch.h.
move_base_z_client::ClMoveBaseZ* move_base_z_client::CostmapSwitch::owner_ [private]
Definition at line 57 of file cp_costmap_switch.h.
Referenced by initialize(), and registerProxyFromDynamicReconfigureServer().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/costmap_switch/cp_costmap_switch.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/costmap_switch/cp_costmap_switch.cpp