move_base_z_client::PlannerSwitcher Class Reference
#include <planner_switcher.h>
Public Member Functions
PlannerSwitcher ()
void setBackwardPlanner ()
void setForwardPlanner ()
virtual void initialize (smacc::ISmaccClient *owner) override
void setDefaultPlanners ()
Private Member Functions
void updatePlanners (bool subscribecallback=true)
void dynreconfCallback (const dynamic_reconfigure::Config::ConstPtr &configuration_update)
Private Attributes
std::string desired_global_planner_
std::string desired_local_planner_
ros::Subscriber dynrecofSub_
bool set_planners_mode_flag
Additional Inherited Members
Detailed Description
Definition at line 19 of file planner_switcher.h.
Constructor & Destructor Documentation
move_base_z_client::PlannerSwitcher::PlannerSwitcher ()
Definition at line 12 of file planner_switcher.cpp.
{
}
Member Function Documentation
void move_base_z_client::PlannerSwitcher::dynreconfCallback (const dynamic_reconfigure::Config::ConstPtr & configuration_update) [private]
Definition at line 72 of file planner_switcher.cpp.
References desired_global_planner_, desired_local_planner_, set_planners_mode_flag, and updatePlanners().
Referenced by initialize().
{
  auto gp = std::find_if(configuration_update->strs.begin(), configuration_update->strs.begin(),
                         [&](const dynamic_reconfigure::StrParameter &p) {
                           return p.name == "base_global_planner" && p.value ==
      desired_global_planner_;
                         });
  auto lp = std::find_if(configuration_update->strs.begin(), configuration_update->strs.begin(),
                         [&](const dynamic_reconfigure::StrParameter &p) {
                           return p.name == "base_local_planner" && p.value ==
      desired_local_planner_;
                         });
  if (gp == configuration_update->strs.end() || lp == configuration_update->strs.end())
  {
    ROS_INFO("[PlannerSwitcher] After planner update it is noticed an incorrect move_base planner
       configuration. Resending request.");
    set_planners_mode_flag = false;
    updatePlanners(false);
  }
  else
  {
    ROS_INFO("[PlannerSwitcher] Planners correctly configured according to parameter update callback");
    set_planners_mode_flag = true;
  }
}
void move_base_z_client::PlannerSwitcher::initialize (smacc::ISmaccClient * owner) [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 16 of file planner_switcher.cpp.
References dynrecofSub_, and dynreconfCallback().
{
  auto client_ = dynamic_cast<ClMoveBaseZ *>(owner);
  ros::NodeHandle nh(client_->name_);
  dynrecofSub_ = nh.subscribe<dynamic_reconfigure::Config>("/move_base/parameter_updates", 1,
      boost::bind(&PlannerSwitcher::dynreconfCallback, this, _1));
}
void move_base_z_client::PlannerSwitcher::setBackwardPlanner ()
Definition at line 23 of file planner_switcher.cpp.
References desired_global_planner_, desired_local_planner_, and updatePlanners().
Referenced by move_base_z_client::CbUndoPathBackwards::onEntry(), and move_base_z_client::CbNavigateBackwards::onEntry().
{
  ROS_INFO("[PlannerSwitcher] Planner Switcher: Trying to set BackwardPlanner");
  desired_global_planner_ = "backward_global_planner/BackwardGlobalPlanner";
  desired_local_planner_ = "backward_local_planner/BackwardLocalPlanner";
  updatePlanners();
}
void move_base_z_client::PlannerSwitcher::setDefaultPlanners ()
Definition at line 39 of file planner_switcher.cpp.
References desired_global_planner_, desired_local_planner_, and updatePlanners().
Referenced by move_base_z_client::CbNavigateGlobalPosition::onEntry(), move_base_z_client::CbAbsoluteRotate::onEntry(), move_base_z_client::CbRotate::onEntry(), and move_base_z_client::WaypointNavigator::sendNextGoal().
{
  desired_global_planner_ = "navfn/NavfnROS";
  desired_local_planner_ = "base_local_planner/TrajectoryPlannerROS";
  updatePlanners();
}
void move_base_z_client::PlannerSwitcher::setForwardPlanner ()
Definition at line 31 of file planner_switcher.cpp.
References desired_global_planner_, desired_local_planner_, and updatePlanners().
Referenced by move_base_z_client::CbNavigateForward::onEntry().
{
  ROS_INFO("[PlannerSwitcher] Planner Switcher: Trying to set ForwardPlanner");
  desired_global_planner_ = "forward_global_planner/ForwardGlobalPlanner";
  desired_local_planner_ = "forward_local_planner/ForwardLocalPlanner";
  updatePlanners();
}
void move_base_z_client::PlannerSwitcher::updatePlanners (bool subscribecallback = true) [private]
Definition at line 46 of file planner_switcher.cpp.
References desired_global_planner_, and desired_local_planner_.
Referenced by dynreconfCallback(), setBackwardPlanner(), setDefaultPlanners(), and setForwardPlanner().
{
  ROS_INFO_STREAM("[PlannerSwitcher] Setting global planner: " <<
      desired_global_planner_);
  ROS_INFO_STREAM("[PlannerSwitcher] Setting local planner: " <<
      desired_local_planner_);
  dynamic_reconfigure::ReconfigureRequest srv_req;
  dynamic_reconfigure::ReconfigureResponse srv_resp;
  dynamic_reconfigure::StrParameter local_planner, global_planner;
  dynamic_reconfigure::Config conf;
  local_planner.name = "base_local_planner";
  local_planner.value = desired_local_planner_;
  conf.strs.push_back(local_planner);
  global_planner.name = "base_global_planner";
  global_planner.value = desired_global_planner_;
  conf.strs.push_back(global_planner);
  srv_req.config = conf;
  ROS_INFO("seting values of the dynamic reconfigure server");
  ros::service::call("/move_base/set_parameters", srv_req, srv_resp);
  ros::spinOnce();
  ros::Duration(0.5).sleep();
  ROS_INFO_STREAM("[PlannerSwitcher] Response: " << srv_resp);
}
Member Data Documentation
std::string move_base_z_client::PlannerSwitcher::desired_global_planner_ [private]
Definition at line 32 of file planner_switcher.h.
Referenced by dynreconfCallback(), setBackwardPlanner(), setDefaultPlanners(), setForwardPlanner(), and updatePlanners().
std::string move_base_z_client::PlannerSwitcher::desired_local_planner_ [private]
Definition at line 33 of file planner_switcher.h.
Referenced by dynreconfCallback(), setBackwardPlanner(), setDefaultPlanners(), setForwardPlanner(), and updatePlanners().
ros::Subscriber move_base_z_client::PlannerSwitcher::dynrecofSub_ [private]
Definition at line 34 of file planner_switcher.h.
Referenced by initialize().
bool move_base_z_client::PlannerSwitcher::set_planners_mode_flag [private]
Definition at line 35 of file planner_switcher.h.
Referenced by dynreconfCallback().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/planner_switcher/planner_switcher.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/planner_switcher/planner_switcher.cpp