move_base_z_client::WaypointNavigator Class Reference
#include <waypoints_navigator.h>
Public Member Functions
WaypointNavigator ()
virtual void initialize (smacc::ISmaccClient *owner) override
void insertWaypoint (int index, geometry_msgs::Pose &newpose)
void removeWaypoint (int index)
void loadWayPointsFromFile (std::string filepath)
void setWaypoints (const std::vector< geometry_msgs::Pose > &waypoints)
void setWaypoints (const std::vector< Pose2D > &waypoints)
void sendNextGoal ()
const std::vector< geometry_msgs::Pose > & getWaypoints () const
long getCurrentWaypointIndex () const
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
Public Attributes
WaypointEventDispatcher waypointsEventDispatcher
ClMoveBaseZ * client_
Private Member Functions
void onGoalReached (ClMoveBaseZ::ResultConstPtr &res)
Private Attributes
std::vector< geometry_msgs::Pose > waypoints_
boost::signals2::connection succeddedConnection_
int currentWaypoint_
Additional Inherited Members
Detailed Description
Definition at line 27 of file waypoints_navigator.h.
Constructor & Destructor Documentation
move_base_z_client::WaypointNavigator::WaypointNavigator ()
Definition at line 12 of file waypoints_navigator.cpp.
    : currentWaypoint_(0),
      waypoints_(0)
{
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void move_base_z_client::WaypointNavigator::configureEventSourceTypes () [inline]
Definition at line 58 of file waypoints_navigator.h.
References move_base_z_client::WaypointEventDispatcher::initialize().
  {
    waypointsEventDispatcher.initialize<TDerived, TObjectTag>(
      client_);
  }
long move_base_z_client::WaypointNavigator::getCurrentWaypointIndex () const
Definition at line 88 of file waypoints_navigator.cpp.
References currentWaypoint_.
{
  return currentWaypoint_;
}
const std::vector< geometry_msgs::Pose > & move_base_z_client::WaypointNavigator::getWaypoints () const
Definition at line 83 of file waypoints_navigator.cpp.
References waypoints_.
{
  return waypoints_;
}
virtual void move_base_z_client::WaypointNavigator::initialize (smacc::ISmaccClient * owner) [inline], [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 36 of file waypoints_navigator.h.
  {
    client_ = dynamic_cast<ClMoveBaseZ*>(owner);
  }
void move_base_z_client::WaypointNavigator::insertWaypoint (int index, geometry_msgs::Pose & newpose)
Definition at line 47 of file waypoints_navigator.cpp.
References waypoints_.
{
  if (index >= 0 && index <= waypoints_.size())
  {
    waypoints_.insert(waypoints_.begin(), index, newpose);
  }
}
void move_base_z_client::WaypointNavigator::loadWayPointsFromFile (std::string filepath)
Definition at line 94 of file waypoints_navigator.cpp.
References generate_debs::parser, and waypoints_.
Referenced by sm_dance_bot::OrNavigation::loadWaypointsFromYaml(), and sm_dance_bot_2::OrNavigation::loadWaypointsFromYaml().
{
  this->waypoints_.clear();
  std::ifstream ifs(filepath.c_str(), std::ifstream::in);
  if (ifs.good() == false)
  {
    throw std::string("Waypoints file not found");
  }
#ifdef HAVE_NEW_YAMLCPP
  YAML::Node node = YAML::Load(ifs);
#else
  YAML::Parser parser(ifs);
  parser.GetNextDocument(node);
#endif
#ifdef HAVE_NEW_YAMLCPP
  const YAML::Node &wp_node_tmp = node["waypoints"];
  const YAML::Node *wp_node = wp_node_tmp ? &wp_node_tmp : NULL;
#else
  const YAML::Node *wp_node = node.FindValue("waypoints");
#endif
  if (wp_node != NULL)
  {
    for (unsigned int i = 0; i < wp_node->size(); ++i)
    {
      // Parse waypoint entries on YAML
      geometry_msgs::Pose wp;
      try
      {
        // (*wp_node)[i]["name"] >> wp.name;
        // (*wp_node)[i]["frame_id"] >> wp.header.frame_id;
        wp.position.x = (*wp_node)[i]["position"]["x"].as<double>();
        wp.position.y = (*wp_node)[i]["position"]["y"].as<double>();
        wp.position.z = (*wp_node)[i]["position"]["z"].as<double>();
        wp.orientation.x = (*wp_node)[i]["orientation"]["x"].as<double>();
        wp.orientation.y = (*wp_node)[i]["orientation"]["y"].as<double>();
        wp.orientation.z = (*wp_node)[i]["orientation"]["z"].as<double>();
        wp.orientation.w = (*wp_node)[i]["orientation"]["w"].as<double>();
        this->waypoints_.push_back(wp);
      }
      catch (...)
      {
        ROS_ERROR("parsing waypoint file, syntax error in point %d", i);
      }
    }
    ROS_INFO_STREAM("Parsed " << this->waypoints_.size() << " waypoints.");
  }
  else
  {
    ROS_WARN_STREAM("Couldn't find any waypoints in the provided yaml file.");
  }
}
void move_base_z_client::WaypointNavigator::onGoalReached (ClMoveBaseZ::ResultConstPtr & res) [private]
Definition at line 18 of file waypoints_navigator.cpp.
References currentWaypoint_, move_base_z_client::WaypointEventDispatcher::postWaypointEvent(), succeddedConnection_, and waypointsEventDispatcher.
Referenced by sendNextGoal().
{
  waypointsEventDispatcher.postWaypointEvent(
      currentWaypoint_);
  currentWaypoint_++;
  this->succeddedConnection_.disconnect();
}
void move_base_z_client::WaypointNavigator::removeWaypoint (int index)
Definition at line 75 of file waypoints_navigator.cpp.
References waypoints_.
{
  if (index >= 0 && index < waypoints_.size())
  {
    waypoints_.erase(waypoints_.begin() + index);
  }
}
void move_base_z_client::WaypointNavigator::sendNextGoal ()
Definition at line 25 of file waypoints_navigator.cpp.
References client_, currentWaypoint_, smacc::ISmaccClient::getComponent(), onGoalReached(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), move_base_z_client::PlannerSwitcher::setDefaultPlanners(), succeddedConnection_, and waypoints_.
Referenced by sm_dance_bot_2::StNavigateToWaypointsX::onEntry(), and sm_dance_bot::StNavigateToWaypointsX::onInitialize().
{
  if (currentWaypoint_ >= 0 && currentWaypoint_ <
      waypoints_.size())
  {
    auto &next = waypoints_[currentWaypoint_];
    ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    goal.target_pose.pose = next;
    auto plannerSwitcher = client_->getComponent<PlannerSwitcher>();
    plannerSwitcher->setDefaultPlanners();
    ros::spinOnce();
    ros::Duration(5).sleep();
    this->succeddedConnection_ = client_->onSucceeded(&
      WaypointNavigator::onGoalReached, this);
    client_->sendGoal(goal);
  }
}
void move_base_z_client::WaypointNavigator::setWaypoints (const std::vector< geometry_msgs::Pose > & waypoints)
Definition at line 55 of file waypoints_navigator.cpp.
References waypoints_.
{
  this->waypoints_ = waypoints;
}
void move_base_z_client::WaypointNavigator::setWaypoints (const std::vector< Pose2D > & waypoints)
Definition at line 60 of file waypoints_navigator.cpp.
References waypoints_.
{
  this->waypoints_.clear();
  for (auto &p : waypoints)
  {
    geometry_msgs::Pose pose;
    pose.position.x = p.x_;
    pose.position.y = p.y_;
    pose.position.z = 0.0;
    pose.orientation = tf::createQuaternionMsgFromYaw(p.yaw_);
    this->waypoints_.push_back(pose);
  }
}
Member Data Documentation
ClMoveBaseZ* move_base_z_client::WaypointNavigator::client_
Definition at line 32 of file waypoints_navigator.h.
Referenced by sendNextGoal().
int move_base_z_client::WaypointNavigator::currentWaypoint_ [private]
Definition at line 70 of file waypoints_navigator.h.
Referenced by getCurrentWaypointIndex(), onGoalReached(), and sendNextGoal().
boost::signals2::connection move_base_z_client::WaypointNavigator::succeddedConnection_ [private]
Definition at line 68 of file waypoints_navigator.h.
Referenced by onGoalReached(), and sendNextGoal().
std::vector<geometry_msgs::Pose> move_base_z_client::WaypointNavigator::waypoints_ [private]
Definition at line 66 of file waypoints_navigator.h.
Referenced by getWaypoints(), insertWaypoint(), loadWayPointsFromFile(), removeWaypoint(), sendNextGoal(), and setWaypoints().
WaypointEventDispatcher move_base_z_client::WaypointNavigator::waypointsEventDispatcher
Definition at line 30 of file waypoints_navigator.h.
Referenced by onGoalReached().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/waypoints_navigator/waypoints_navigator.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/waypoints_navigator/waypoints_navigator.cpp