moveit_z_client::CbAttachObject Class Reference
#include <cb_attach_object.h>
Public Member Functions
CbAttachObject (std::string targetObjectName)
CbAttachObject ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
std::string targetObjectName_
Detailed Description
Definition at line 8 of file cb_attach_object.h.
Constructor & Destructor Documentation
CbAttachObject() [1/2]
moveit_z_client::CbAttachObject::CbAttachObject (std::string targetObjectName)
Definition at line 6 of file cb_attach_object.cpp.
        : targetObjectName_(targetObjectName)
    {
    }
CbAttachObject() [2/2]
moveit_z_client::CbAttachObject::CbAttachObject ()
Definition at line 11 of file cb_attach_object.cpp.
    {
    }
Member Function Documentation
onEntry()
void moveit_z_client::CbAttachObject::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 15 of file cb_attach_object.cpp.
References moveit_z_client::GraspingComponent::currentAttachedObjectName, moveit_z_client::GraspingComponent::fingerTipNames, moveit_z_client::GraspingComponent::getGraspingObject(), moveit_z_client::ClMoveGroup::moveGroupClientInterface, moveit_z_client::ClMoveGroup::planningSceneInterface, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccClientBehavior::requiresComponent(), and targetObjectName_.
    {
        moveit_z_client::ClMoveGroup *moveGroup;
        this->requiresClient(moveGroup);
        moveit_z_client::GraspingComponent *graspingComponent;
        this->requiresComponent(graspingComponent);
        // auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
        moveit_msgs::CollisionObject targetCollisionObject;
        bool found = graspingComponent->getGraspingObject(
      targetObjectName_, targetCollisionObject);
        if (found)
        {
            targetCollisionObject.operation = moveit_msgs::CollisionObject::ADD;
            targetCollisionObject.header.stamp = ros::Time::now();
            moveGroup->planningSceneInterface.applyCollisionObject(
      targetCollisionObject);
            // collisionObjects.push_back(cubeCollision);
            graspingComponent->currentAttachedObjectName =
      targetObjectName_;
            moveGroup->moveGroupClientInterface.attachObject(
      targetObjectName_, "gripper_link", graspingComponent->
      fingerTipNames);
        }
    }
onExit()
void moveit_z_client::CbAttachObject::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 42 of file cb_attach_object.cpp.
    {
    }
Member Data Documentation
targetObjectName_
std::string moveit_z_client::CbAttachObject::targetObjectName_
Definition at line 19 of file cb_attach_object.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_attach_object.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_attach_object.cpp