move_base_z_client::odom_tracker::OdomTracker Class Reference
This class track the required distance of the cord based on the external localization system.
#include <odom_tracker.h>
Public Member Functions
OdomTracker (std::string nodeName)
virtual void processOdometryMessage (const nav_msgs::Odometry &odom)
odom callback: Updates the path - this must be called periodically for each odometry message.
void setWorkingMode (WorkingMode workingMode)
void setPublishMessages (bool value)
void pushPath ()
void popPath ()
void clearPath ()
void setStartPoint (const geometry_msgs::PoseStamped &pose)
nav_msgs::Path getPath ()
Protected Member Functions
virtual void rtPublishPaths (ros::Time timestamp)
virtual bool updateForward (const nav_msgs::Odometry &odom)
virtual bool updateBackward (const nav_msgs::Odometry &odom)
Protected Attributes
std::shared_ptr< realtime_tools::RealtimePublisher< nav_msgs::Path > > robotBasePathPub_
ros::Subscriber odomSub_
double minPointDistanceForwardThresh_
How much distance there is between two points of the path.
double minPointDistanceBackwardThresh_
Meters.
double minPointAngularDistanceForwardThresh_
rads
double minPointAngularDistanceBackwardThresh_
rads
bool publishMessages
nav_msgs::Path baseTrajectory_
Processed path for the mouth of the reel.
WorkingMode workingMode_
std::vector< nav_msgs::Path > pathStack_
bool subscribeToOdometryTopic_
std::mutex m_mutex_
Detailed Description
This class track the required distance of the cord based on the external localization system.
Definition at line 37 of file odom_tracker.h.
Constructor & Destructor Documentation
move_base_z_client::odom_tracker::OdomTracker::OdomTracker (std::string nodeName)
Definition at line 13 of file odom_tracker.cpp.
References minPointAngularDistanceBackwardThresh_, minPointAngularDistanceForwardThresh_, minPointDistanceBackwardThresh_, minPointDistanceForwardThresh_, odomSub_, processOdometryMessage(), publishMessages, move_base_z_client::odom_tracker::RECORD_PATH_FORWARD, robotBasePathPub_, subscribeToOdometryTopic_, and workingMode_.
{
    workingMode_ = WorkingMode::RECORD_PATH_FORWARD;
    publishMessages = true;
    subscribeToOdometryTopic_ = true;
    ros::NodeHandle nh(nodeName);
    ROS_WARN("Initializing Odometry Tracker");
    if (!nh.getParam("min_point_distance_forward_thresh",
      minPointDistanceForwardThresh_))
    {
        minPointDistanceForwardThresh_ = 0.005; // 1 mm
    }
    if (!nh.getParam("min_point_distance_backward_thresh",
      minPointDistanceBackwardThresh_))
    {
        minPointDistanceBackwardThresh_ = 0.05; // 1 mm
    }
    if (!nh.getParam("min_point_angular_distance_forward_thresh",
      minPointAngularDistanceForwardThresh_))
    {
        minPointAngularDistanceForwardThresh_ = 0.15; // degree
    }
    if (!nh.getParam("min_point_angular_distance_backward_thresh",
      minPointAngularDistanceBackwardThresh_))
    {
        minPointAngularDistanceBackwardThresh_ = 0.15; // degree
    }
    if (this->subscribeToOdometryTopic_)
    {
        odomSub_ = nh.subscribe("odom", 1, &
      OdomTracker::processOdometryMessage, this);
    }
    robotBasePathPub_ = std::make_shared<realtime_tools::RealtimePublisher<nav_msgs::Path>
      >(nh, "odom_tracker_path", 1);
}
Member Function Documentation
void move_base_z_client::odom_tracker::OdomTracker::clearPath ()
Definition at line 101 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and rtPublishPaths().
Referenced by move_base_z_client::CbNavigateBackwards::onEntry(), and move_base_z_client::CbNavigateForward::onEntry().
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    baseTrajectory_.poses.clear();
    rtPublishPaths(ros::Time::now());
}
nav_msgs::Path move_base_z_client::odom_tracker::OdomTracker::getPath ()
Definition at line 122 of file odom_tracker.cpp.
References baseTrajectory_, and m_mutex_.
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    return this->baseTrajectory_;
}
void move_base_z_client::odom_tracker::OdomTracker::popPath ()
Definition at line 87 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and pathStack_.
Referenced by OdomTrackerActionServer::execute().
{
    ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    if (!pathStack_.empty())
    {
        baseTrajectory_.poses = pathStack_.back().poses;
        pathStack_.pop_back();
    }
    ROS_INFO("odom_tracker m_mutex release");
}
void move_base_z_client::odom_tracker::OdomTracker::processOdometryMessage (const nav_msgs::Odometry & odom) [virtual]
odom callback: Updates the path - this must be called periodically for each odometry message.
processOdometryMessage()
Definition at line 246 of file odom_tracker.cpp.
References move_base_z_client::odom_tracker::CLEAR_PATH_BACKWARD, m_mutex_, publishMessages, move_base_z_client::odom_tracker::RECORD_PATH_FORWARD, rtPublishPaths(), updateBackward(), updateForward(), and workingMode_.
Referenced by OdomTracker().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    if (workingMode_ == WorkingMode::RECORD_PATH_FORWARD)
    {
        updateForward(odom);
    }
    else if (workingMode_ == WorkingMode::CLEAR_PATH_BACKWARD)
    {
        updateBackward(odom);
    }
    //ROS_WARN("odomTracker odometry callback");
    if (publishMessages)
    {
        rtPublishPaths(odom.header.stamp);
    }
    //ROS_INFO("odom_tracker m_mutex release");
}
void move_base_z_client::odom_tracker::OdomTracker::pushPath ()
Definition at line 78 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and pathStack_.
Referenced by OdomTrackerActionServer::execute().
{
    ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    pathStack_.push_back(baseTrajectory_);
    baseTrajectory_.poses.clear();
    ROS_INFO("odom_tracker m_mutex release");
}
void move_base_z_client::odom_tracker::OdomTracker::rtPublishPaths (ros::Time timestamp) [protected], [virtual]
rtPublishPaths() Copy trajectory
Definition at line 133 of file odom_tracker.cpp.
References baseTrajectory_, and robotBasePathPub_.
Referenced by clearPath(), and processOdometryMessage().
{
    if (robotBasePathPub_->trylock())
    {
        nav_msgs::Path &msg = robotBasePathPub_->msg_;
        msg = baseTrajectory_;
        msg.header.stamp = timestamp;
        robotBasePathPub_->unlockAndPublish();
    }
}
void move_base_z_client::odom_tracker::OdomTracker::setPublishMessages (bool value)
setPublishMessages()
Definition at line 70 of file odom_tracker.cpp.
References m_mutex_, and publishMessages.
Referenced by OdomTrackerActionServer::execute().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    publishMessages = value;
    //ROS_INFO("odom_tracker m_mutex release");
}
void move_base_z_client::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::PoseStamped & pose)
Definition at line 109 of file odom_tracker.cpp.
References baseTrajectory_, and m_mutex_.
Referenced by move_base_z_client::CbNavigateBackwards::onEntry(), and move_base_z_client::CbNavigateForward::onEntry().
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    if (baseTrajectory_.poses.size() > 0)
    {
        baseTrajectory_.poses[0] = pose;
    }
    else
    {
        baseTrajectory_.poses.push_back(pose);
    }
}
void move_base_z_client::odom_tracker::OdomTracker::setWorkingMode (WorkingMode workingMode)
setWorkingMode()
Definition at line 56 of file odom_tracker.cpp.
References m_mutex_, and workingMode_.
Referenced by OdomTrackerActionServer::execute(), move_base_z_client::CbNavigateBackwards::onEntry(), move_base_z_client::CbNavigateForward::onEntry(), move_base_z_client::CbNavigateBackwards::onExit(), and move_base_z_client::CbNavigateForward::onExit().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    ROS_INFO("[OdomTracker] setting working mode to: %d", (uint8_t)workingMode);
    workingMode_ = workingMode;
    //ROS_INFO("odom_tracker m_mutex release");
}
bool move_base_z_client::odom_tracker::OdomTracker::updateBackward (const nav_msgs::Odometry & odom) [protected], [virtual]
updateBackward() Track robot base pose
Not removing point because it is enough far from the last cord point
Definition at line 151 of file odom_tracker.cpp.
References baseTrajectory_, minPointDistanceBackwardThresh_, and move_base_z_client::odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
{
    // we initially accept any message if the queue is empty
    geometry_msgs::PoseStamped base_pose;
    base_pose.pose = odom.pose.pose;
    base_pose.header = odom.header;
    baseTrajectory_.header = odom.header;
    bool acceptBackward = false;
    bool pullingerror = false;
    if (baseTrajectory_.poses.empty())
    {
        acceptBackward = false;
    }
    else
    {
        const geometry_msgs::Point &prevPoint = baseTrajectory_.poses.back().pose.position;
        const geometry_msgs::Point &currePoint = base_pose.pose.position;
        double lastpointdist = p2pDistance(prevPoint, currePoint);
        acceptBackward = !baseTrajectory_.poses.empty() && lastpointdist <
      minPointDistanceBackwardThresh_;
        pullingerror = lastpointdist > 2 * minPointDistanceBackwardThresh_;
    }
    //ROS_INFO("Backwards, last distance: %lf < %lf accept: %d", dist, minPointDistanceBackwardThresh_,
       acceptBackward);
    if (acceptBackward)
    {
        baseTrajectory_.poses.pop_back();
    }
    else if (pullingerror)
    {
        ROS_INFO_THROTTLE(2, "Incorrect backwards motion.");
    }
    else
    {
    }
    return acceptBackward;
}
bool move_base_z_client::odom_tracker::OdomTracker::updateForward (const nav_msgs::Odometry & odom) [protected], [virtual]
updateForward() Track robot base pose
Definition at line 199 of file odom_tracker.cpp.
References baseTrajectory_, minPointDistanceForwardThresh_, and move_base_z_client::odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
{
    geometry_msgs::PoseStamped base_pose;
    base_pose.pose = odom.pose.pose;
    base_pose.header = odom.header;
    baseTrajectory_.header = odom.header;
    bool enqueueOdomMessage = false;
    double dist = -1;
    if (baseTrajectory_.poses.empty())
    {
        enqueueOdomMessage = true;
    }
    else
    {
        const geometry_msgs::Point &prevPoint = baseTrajectory_.poses.back().pose.position;
        const geometry_msgs::Point &currePoint = base_pose.pose.position;
        dist = p2pDistance(prevPoint, currePoint);
        //ROS_WARN("dist %lf vs min %lf", dist, minPointDistanceForwardThresh_);
        if (dist > minPointDistanceForwardThresh_)
        {
            enqueueOdomMessage = true;
        }
        else
        {
            //ROS_WARN("skip odom, dist: %lf", dist);
            enqueueOdomMessage = false;
        }
    }
    if (enqueueOdomMessage)
    {
        baseTrajectory_.poses.push_back(base_pose);
    }
    return enqueueOdomMessage;
}
Member Data Documentation
nav_msgs::Path move_base_z_client::odom_tracker::OdomTracker::baseTrajectory_ [protected]
Processed path for the mouth of the reel.
Definition at line 106 of file odom_tracker.h.
Referenced by clearPath(), getPath(), popPath(), pushPath(), rtPublishPaths(), setStartPoint(), updateBackward(), and updateForward().
std::mutex move_base_z_client::odom_tracker::OdomTracker::m_mutex_ [protected]
Definition at line 115 of file odom_tracker.h.
Referenced by clearPath(), getPath(), popPath(), processOdometryMessage(), pushPath(), setPublishMessages(), setStartPoint(), and setWorkingMode().
double move_base_z_client::odom_tracker::OdomTracker::minPointAngularDistanceBackwardThresh_ [protected]
rads
Definition at line 99 of file odom_tracker.h.
Referenced by OdomTracker().
double move_base_z_client::odom_tracker::OdomTracker::minPointAngularDistanceForwardThresh_ [protected]
rads
Definition at line 96 of file odom_tracker.h.
Referenced by OdomTracker().
double move_base_z_client::odom_tracker::OdomTracker::minPointDistanceBackwardThresh_ [protected]
Meters.
Definition at line 93 of file odom_tracker.h.
Referenced by OdomTracker(), and updateBackward().
double move_base_z_client::odom_tracker::OdomTracker::minPointDistanceForwardThresh_ [protected]
How much distance there is between two points of the path.
Definition at line 90 of file odom_tracker.h.
Referenced by OdomTracker(), and updateForward().
ros::Subscriber move_base_z_client::odom_tracker::OdomTracker::odomSub_ [protected]
Definition at line 86 of file odom_tracker.h.
Referenced by OdomTracker().
std::vector<nav_msgs::Path> move_base_z_client::odom_tracker::OdomTracker::pathStack_ [protected]
Definition at line 110 of file odom_tracker.h.
Referenced by popPath(), and pushPath().
bool move_base_z_client::odom_tracker::OdomTracker::publishMessages [protected]
Definition at line 103 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setPublishMessages().
std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::Path> > move_base_z_client::odom_tracker::OdomTracker::robotBasePathPub_ [protected]
Definition at line 81 of file odom_tracker.h.
Referenced by OdomTracker(), and rtPublishPaths().
bool move_base_z_client::odom_tracker::OdomTracker::subscribeToOdometryTopic_ [protected]
Definition at line 113 of file odom_tracker.h.
Referenced by OdomTracker().
WorkingMode move_base_z_client::odom_tracker::OdomTracker::workingMode_ [protected]
Definition at line 108 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setWorkingMode().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/odom_tracker/odom_tracker.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/odom_tracker/odom_tracker.cpp