cl_ros_publisher_client::CbDefaultPublishLoop Class Reference
#include <cb_default_publish_loop.h>
Public Member Functions
CbDefaultPublishLoop ()
template<typename TMessage >
CbDefaultPublishLoop (const TMessage &data)
template<typename TMessage >
void setMessage (const TMessage &data)
virtual void onEntry () override
virtual void update ()
virtual void onExit () override
Private Attributes
std::function< void()> deferedPublishFn
ClRosPublisher * client_
Additional Inherited Members
Detailed Description
Definition at line 9 of file cb_default_publish_loop.h.
Constructor & Destructor Documentation
cl_ros_publisher_client::CbDefaultPublishLoop::CbDefaultPublishLoop () [inline]
Definition at line 17 of file cb_default_publish_loop.h.
        : deferedPublishFn(nullptr)
    {
    }
template<typename TMessage > cl_ros_publisher_client::CbDefaultPublishLoop::CbDefaultPublishLoop (const TMessage & data) [inline]
Definition at line 23 of file cb_default_publish_loop.h.
References setMessage().
    {
        this->setMessage(data);
    }
Member Function Documentation
virtual void cl_ros_publisher_client::CbDefaultPublishLoop::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 36 of file cb_default_publish_loop.h.
References smacc::SmaccClientBehavior::requiresClient().
    {
        this->requiresClient(client_);
    }
virtual void cl_ros_publisher_client::CbDefaultPublishLoop::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 47 of file cb_default_publish_loop.h.
    {
    }
template<typename TMessage > void cl_ros_publisher_client::CbDefaultPublishLoop::setMessage (const TMessage & data) [inline]
Definition at line 29 of file cb_default_publish_loop.h.
References cl_ros_publisher_client::ClRosPublisher::publish().
Referenced by CbDefaultPublishLoop().
    {
        deferedPublishFn = [=]() {
            client_->publish(data);
        };
    }
virtual void cl_ros_publisher_client::CbDefaultPublishLoop::update () [inline], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 41 of file cb_default_publish_loop.h.
References deferedPublishFn.
    {
        if (deferedPublishFn != nullptr)
            deferedPublishFn();
    }
Member Data Documentation
ClRosPublisher* cl_ros_publisher_client::CbDefaultPublishLoop::client_ [private]
Definition at line 14 of file cb_default_publish_loop.h.
std::function<void()> cl_ros_publisher_client::CbDefaultPublishLoop::deferedPublishFn [private]
Definition at line 13 of file cb_default_publish_loop.h.
Referenced by update().
The documentation for this class was generated from the following file:
smacc_client_library/ros_publisher_client/include/ros_publisher_client/client_behaviors/cb_default_publish_loop.h