move_base_z_client::CbRotate Class Reference
#include <cb_rotate.h>
Public Member Functions
CbRotate ()
CbRotate (float rotate_degree)
virtual void onEntry () override
Public Attributes
tf::TransformListener listener
ClMoveBaseZ * moveBaseClient_
boost::optional< float > rotateDegree
Detailed Description
Definition at line 18 of file cb_rotate.h.
Constructor & Destructor Documentation
move_base_z_client::CbRotate::CbRotate ()
Definition at line 5 of file cb_rotate.cpp.
{
}
move_base_z_client::CbRotate::CbRotate (float rotate_degree)
Definition at line 9 of file cb_rotate.cpp.
References rotateDegree.
{
    rotateDegree = rotate_degree;
}
Member Function Documentation
void move_base_z_client::CbRotate::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 14 of file cb_rotate.cpp.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccClient::getComponent(), listener, moveBaseClient_, smacc::ISmaccState::param(), smacc::SmaccClientBehavior::requiresClient(), rotateDegree, smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), and move_base_z_client::PlannerSwitcher::setDefaultPlanners().
{
    double angle_increment_degree;
    if (!rotateDegree)
    {
        this->currentState->param("angle_increment_degree", angle_increment_degree, 45.0);
    }
    else
    {
        angle_increment_degree = *rotateDegree;
    }
    this->requiresClient(moveBaseClient_);
    auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
    //this should work better with a coroutine and await
    //this->plannerSwitcher_->setForwardPlanner();
    plannerSwitcher->setDefaultPlanners();
    ros::Rate rate(10.0);
    geometry_msgs::Pose currentPoseMsg;
    while (ros::ok())
    {
        tf::StampedTransform currentPose;
        try
        {
            listener.lookupTransform("/odom", "/base_link",
                                     ros::Time(0), currentPose);
            tf::poseTFToMsg(currentPose, currentPoseMsg);
            break;
        }
        catch (tf::TransformException ex)
        {
            ROS_ERROR("%s", ex.what());
            ros::Duration(1.0).sleep();
        }
    }
    ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    auto currentAngle = tf::getYaw(currentPoseMsg.orientation);
    auto targetAngle = currentAngle + angle_increment_degree * M_PI / 180.0;
    goal.target_pose.pose.position = currentPoseMsg.position;
    goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(targetAngle);
    ROS_INFO_STREAM("current pose: " << currentPoseMsg);
    ROS_INFO_STREAM("goal pose: " << goal.target_pose.pose);
    moveBaseClient_->sendGoal(goal);
}
Member Data Documentation
tf::TransformListener move_base_z_client::CbRotate::listener
Definition at line 21 of file cb_rotate.h.
Referenced by onEntry().
ClMoveBaseZ* move_base_z_client::CbRotate::moveBaseClient_
Definition at line 23 of file cb_rotate.h.
Referenced by onEntry().
boost::optional<float> move_base_z_client::CbRotate::rotateDegree
Definition at line 25 of file cb_rotate.h.
Referenced by CbRotate(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_rotate.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_rotate.cpp