smacc::IOrthogonal Class Reference
#include <smacc_orthogonal.h>
Public Member Functions
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void addClientBehavior (std::shared_ptr< smacc::SmaccClientBehavior > statereactor)
void runtimeConfigure ()
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc::SmaccClientBehavior > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior ()
Protected Member Functions
virtual void onInitialize ()
Protected Attributes
std::vector< std::shared_ptr< smacc::ISmaccClient > > clients_
Private Attributes
ISmaccStateMachine * stateMachine_
std::vector< std::shared_ptr< smacc::SmaccClientBehavior > > clientBehaviors_
Detailed Description
Definition at line 13 of file smacc_orthogonal.h.
Member Function Documentation
void smacc::IOrthogonal::addClientBehavior (std::shared_ptr< smacc::SmaccClientBehavior > statereactor)
Definition at line 13 of file orthogonal.cpp.
References clientBehaviors_, getName(), and getStateMachine().
{
    if (clBehavior != nullptr)
    {
        ROS_INFO("Setting Ortho %s State reactor: %s", this->getName().c_str(), clBehavior->getName(
      ).c_str());
        clBehavior->stateMachine_ = this->getStateMachine();
        clBehavior->currentOrthogonal = this;
        clientBehaviors_.push_back(clBehavior);
    }
    else
    {
        ROS_INFO("Not behavioral State by orthogonal");
    }
}
template<typename TClientBehavior > TClientBehavior * smacc::IOrthogonal::getClientBehavior ()
Definition at line 39 of file smacc_orthogonal_impl.h.
References clientBehaviors_.
{
    for (auto &cb : this->clientBehaviors_)
    {
        auto *ret = dynamic_cast<TClientBehavior *>(cb.get());
        if (ret != nullptr)
        {
            return ret;
        }
    }
    return nullptr;
}
const std::vector< std::shared_ptr< smacc::SmaccClientBehavior > > & smacc::IOrthogonal::getClientBehaviors () const [inline]
Definition at line 58 of file smacc_orthogonal_impl.h.
References clientBehaviors_.
{
    return this->clientBehaviors_;
}
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & smacc::IOrthogonal::getClients () [inline]
Definition at line 53 of file smacc_orthogonal_impl.h.
References clients_.
{
    return clients_;
}
template<typename T > bool smacc::IOrthogonal::getGlobalSMData (std::string name, T & ret)
Definition at line 70 of file smacc_orthogonal_impl.h.
References smacc::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
{
    return this->getStateMachine()->getGlobalSMData(name, ret);
}
std::string smacc::IOrthogonal::getName () const [virtual]
Definition at line 33 of file orthogonal.cpp.
References smacc::introspection::demangleSymbol().
Referenced by addClientBehavior(), onEntry(), onExit(), and runtimeConfigure().
{
    return demangleSymbol(typeid(*this).name());
}
ISmaccStateMachine * smacc::IOrthogonal::getStateMachine () [inline]
Definition at line 76 of file smacc_orthogonal_impl.h.
References stateMachine_.
Referenced by addClientBehavior(), smacc::Orthogonal< OrService3 >::createClient(), smacc::ClientHandler< TOrthogonal, TClient >::createComponent(), getGlobalSMData(), and setGlobalSMData().
{ return this->stateMachine_; }
void smacc::IOrthogonal::onEntry ()
Definition at line 50 of file orthogonal.cpp.
References clientBehaviors_, and getName().
{
    if (clientBehaviors_.size() > 0)
    {
        for (auto &clBehavior : clientBehaviors_)
        {
            ROS_INFO("Orthogonal %s OnEntry, current Behavior: %s",
                     this->getName().c_str(),
                     clBehavior->getName().c_str());
            clBehavior->onEntry();
        }
    }
    else
    {
        ROS_INFO("Orthogonal %s OnEntry", this->getName().c_str());
    }
}
void smacc::IOrthogonal::onExit ()
Definition at line 69 of file orthogonal.cpp.
References clientBehaviors_, and getName().
{
    if (clientBehaviors_.size() > 0)
    {
        for (auto &clBehavior : clientBehaviors_)
        {
            ROS_INFO("Orthogonal %s OnExit, current Behavior: %s", this->getName().c_str(),
      clBehavior->getName().c_str());
            clBehavior->onExit();
        }
        clientBehaviors_.clear();
    }
    else
    {
        ROS_INFO("Orthogonal %s OnExit", this->getName().c_str());
    }
}
void smacc::IOrthogonal::onInitialize () [protected], [virtual]
Reimplemented in sm_dance_bot_2::OrNavigation, sm_dance_bot::OrNavigation, sm_dance_bot_3::OrNavigation, sm_dance_bot_2::OrObstaclePerception, sm_three_some::OrUpdatablePublisher, sm_dance_bot::OrTemperatureSensor, sm_dance_bot_3::OrTemperatureSensor, sm_three_some::OrSubscriber, sm_dance_bot::OrObstaclePerception, sm_dance_bot::OrService3, sm_dance_bot::OrUpdatablePublisher, sm_dance_bot_3::OrObstaclePerception, sm_dance_bot_3::OrService3, sm_dance_bot_3::OrUpdatablePublisher, sm_three_some::OrKeyboard, sm_three_some::OrTimer, sm_viewer_sim::OrNavigation, sm_dance_bot::OrLED, sm_dance_bot::OrStringPublisher, sm_dance_bot::OrTimer, sm_dance_bot_3::OrLED, sm_dance_bot_3::OrStringPublisher, sm_dance_bot_3::OrTimer, and sm_atomic::OrTimer.
Definition at line 29 of file orthogonal.cpp.
Referenced by setStateMachine().
{
}
template<typename SmaccClientType > void smacc::IOrthogonal::requiresClient (SmaccClientType *& storage)
Definition at line 16 of file smacc_orthogonal_impl.h.
References clients_.
Referenced by smacc::SmaccClientBehavior::requiresClient().
{
    for (auto &client : clients_)
    {
        storage = dynamic_cast<SmaccClientType *>(client.get());
        if (storage != nullptr)
            return;
    }
}
template<typename SmaccComponentType > void smacc::IOrthogonal::requiresComponent (SmaccComponentType *& storage)
Definition at line 27 of file smacc_orthogonal_impl.h.
References smacc::ISmaccStateMachine::requiresComponent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("Cannot use the requiresComponent funcionality from an orthogonal before onInitialize");
    }
    else
    {
        stateMachine_->requiresComponent(storage);
    }
}
void smacc::IOrthogonal::runtimeConfigure ()
Definition at line 38 of file orthogonal.cpp.
References clientBehaviors_, and getName().
{
    for (auto &clBehavior : clientBehaviors_)
        {
            ROS_INFO("Orthogonal %s runtimeConfigure, current Behavior: %s",
                     this->getName().c_str(),
                     clBehavior->getName().c_str());
            clBehavior->runtimeConfigure();
        }
}
template<typename T > void smacc::IOrthogonal::setGlobalSMData (std::string name, T value)
Definition at line 64 of file smacc_orthogonal_impl.h.
References getStateMachine(), and smacc::ISmaccStateMachine::setGlobalSMData().
{
    this->getStateMachine()->setGlobalSMData(name, value);
}
void smacc::IOrthogonal::setStateMachine (ISmaccStateMachine * value)
Definition at line 7 of file orthogonal.cpp.
References onInitialize(), and stateMachine_.
Referenced by smacc::ISmaccStateMachine::createOrthogonal().
{
    this->stateMachine_ = value;
    this->onInitialize();
}
Member Data Documentation
std::vector<std::shared_ptr<smacc::SmaccClientBehavior> > smacc::IOrthogonal::clientBehaviors_ [private]
Definition at line 57 of file smacc_orthogonal.h.
Referenced by addClientBehavior(), getClientBehavior(), getClientBehaviors(), onEntry(), onExit(), and runtimeConfigure().
std::vector<std::shared_ptr<smacc::ISmaccClient> > smacc::IOrthogonal::clients_ [protected]
Definition at line 52 of file smacc_orthogonal.h.
Referenced by smacc::Orthogonal< OrService3 >::createClient(), getClients(), and requiresClient().
ISmaccStateMachine* smacc::IOrthogonal::stateMachine_ [private]
Definition at line 55 of file smacc_orthogonal.h.
Referenced by getStateMachine(), requiresComponent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_orthogonal.h
smacc/include/smacc/impl/smacc_orthogonal_impl.h
smacc/src/smacc/orthogonal.cpp