cl_ros_timer_client::CbTimerCountdownOnce Class Reference
#include <cb_timer_countdown_once.h>
Public Member Functions
CbTimerCountdownOnce (unsigned long triggerTickCount)
virtual void onEntry () override
virtual void onExit () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
Private Member Functions
void onClientTimerTickCallback ()
Private Attributes
unsigned long tickCounter_
unsigned long tickTriggerCount_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc::SmaccSignal< void()> onTimerTick_
Detailed Description
Definition at line 8 of file cb_timer_countdown_once.h.
Constructor & Destructor Documentation
cl_ros_timer_client::CbTimerCountdownOnce::CbTimerCountdownOnce (unsigned long triggerTickCount)
Definition at line 6 of file cb_timer_countdown_once.cpp.
    : tickTriggerCount_(triggerTickCount),
      tickCounter_(0)
{
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void cl_ros_timer_client::CbTimerCountdownOnce::configureEventSourceTypes () [inline]
Definition at line 17 of file cb_timer_countdown_once.h.
References postCountDownEvent_.
    {
        this->postCountDownEvent_ = [=]() {
            this->template postEvent<EvTimer<TDerived, TObjectTag>>();
        };
    }
void cl_ros_timer_client::CbTimerCountdownOnce::onClientTimerTickCallback () [private]
Definition at line 12 of file cb_timer_countdown_once.cpp.
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
{
    tickCounter_++;
    if (tickCounter_ % tickTriggerCount_ == 0)
    {
        onTimerTick_();
        postCountDownEvent_();
    }
}
void cl_ros_timer_client::CbTimerCountdownOnce::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_timer_countdown_once.cpp.
References onClientTimerTickCallback(), cl_ros_timer_client::ClRosTimer::onTimerTick(), smacc::SmaccClientBehavior::requiresClient(), and timerClient_.
{
    this->requiresClient(timerClient_);
    timerClient_->onTimerTick(&
      CbTimerCountdownOnce::onClientTimerTickCallback, this);
}
void cl_ros_timer_client::CbTimerCountdownOnce::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 29 of file cb_timer_countdown_once.cpp.
{
}
template<typename T > boost::signals2::connection cl_ros_timer_client::CbTimerCountdownOnce::onTimerTick (void(T::*)() callback, T * object) [inline]
Definition at line 25 of file cb_timer_countdown_once.h.
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::SmaccClientBehavior::getStateMachine(), and onTimerTick_.
    {
        return this->getStateMachine()->createSignalConnection(
      onTimerTick_, callback, object);
    }
Member Data Documentation
smacc::SmaccSignal<void()> cl_ros_timer_client::CbTimerCountdownOnce::onTimerTick_ [private]
Definition at line 36 of file cb_timer_countdown_once.h.
Referenced by onClientTimerTickCallback(), and onTimerTick().
std::function<void()> cl_ros_timer_client::CbTimerCountdownOnce::postCountDownEvent_ [private]
Definition at line 35 of file cb_timer_countdown_once.h.
Referenced by configureEventSourceTypes(), and onClientTimerTickCallback().
unsigned long cl_ros_timer_client::CbTimerCountdownOnce::tickCounter_ [private]
Definition at line 31 of file cb_timer_countdown_once.h.
Referenced by onClientTimerTickCallback().
unsigned long cl_ros_timer_client::CbTimerCountdownOnce::tickTriggerCount_ [private]
Definition at line 32 of file cb_timer_countdown_once.h.
Referenced by onClientTimerTickCallback().
ClRosTimer* cl_ros_timer_client::CbTimerCountdownOnce::timerClient_ [private]
Definition at line 34 of file cb_timer_countdown_once.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_countdown_once.h
smacc_client_library/ros_timer_client/src/ros_timer_client/cb_timer_countdown_once.cpp