move_group_interface_client::CbMoveEndEffectorRelative Class Reference
#include <cb_move_end_effector_relative.h>
Public Member Functions
CbMoveEndEffectorRelative ()
CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
virtual void onEntry () override
virtual void onExit () override
Public Attributes
geometry_msgs::Transform transform_
boost::optional< std::string > group_
Protected Member Functions
void moveRelative (moveit::planning_interface::MoveGroupInterface &moveGroupinterface, geometry_msgs::Transform &transformOffset)
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 14 of file cb_move_end_effector_relative.h.
Constructor & Destructor Documentation
CbMoveEndEffectorRelative() [1/2]
move_group_interface_client::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative ()
Definition at line 14 of file cb_move_end_effector_relative.cpp.
References transform_.
    {
        transform_.rotation.w = 1;
    }
CbMoveEndEffectorRelative() [2/2]
move_group_interface_client::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
Definition at line 19 of file cb_move_end_effector_relative.cpp.
    {
    }
Member Function Documentation
moveRelative()
void move_group_interface_client::CbMoveEndEffectorRelative::moveRelative (moveit::planning_interface::MoveGroupInterface & moveGroupinterface, geometry_msgs::Transform & transformOffset) [protected]
Definition at line 44 of file cb_move_end_effector_relative.cpp.
References movegroupClient_, move_group_interface_client::ClMoveGroup::postEventMotionExecutionFailed(), move_group_interface_client::ClMoveGroup::postEventMotionExecutionSucceded(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), and smacc::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onEntry().
    {
        auto referenceStartPose = moveGroupInterface.getCurrentPose();
        tf::Quaternion currentOrientation;
        tf::quaternionMsgToTF(referenceStartPose.pose.orientation, currentOrientation);
        tf::Quaternion desiredRelativeRotation;
        tf::quaternionMsgToTF(transformOffset.rotation, desiredRelativeRotation);
        auto targetOrientation = desiredRelativeRotation * currentOrientation;
        geometry_msgs::PoseStamped targetObjectPose = referenceStartPose;
        tf::quaternionTFToMsg(targetOrientation, targetObjectPose.pose.orientation);
        targetObjectPose.pose.position.x += transformOffset.translation.x;
        targetObjectPose.pose.position.y += transformOffset.translation.y;
        targetObjectPose.pose.position.z += transformOffset.translation.z;
        moveGroupInterface.setPlanningTime(1.0);
        ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Target End efector Pose: " << targetObjectPose);
        moveGroupInterface.setPoseTarget(targetObjectPose);
        moveGroupInterface.setPoseReferenceFrame("map");
        moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
        bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
        ROS_INFO_NAMED("CbMoveEndEffectorRelative", "Success Visualizing plan 1 (pose goal) %s", success ?
      "" : "FAILED");
        if (success)
        {
            auto executionResult = moveGroupInterface.execute(computedMotionPlan);
            if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
            {
                ROS_INFO("[CbMoveEndEffectorRelative] motion execution succedded");
                movegroupClient_->
      postEventMotionExecutionSucceded();
                this->postSuccessEvent();
            }
            else
            {
                moveGroupInterface.setPoseTarget(referenceStartPose); // undo to avoid abort-repeat state
       issues with this relative motion
                ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
                movegroupClient_->postEventMotionExecutionFailed
      ();
                this->postFailureEvent();
            }
        }
        else
        {
            moveGroupInterface.setPoseTarget(referenceStartPose); //undo since we did not executed the
       motion
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed(
      );
            this->postFailureEvent();
        }
    }
onEntry()
void move_group_interface_client::CbMoveEndEffectorRelative::onEntry () [override], [virtual]
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 23 of file cb_move_end_effector_relative.cpp.
References group_, movegroupClient_, move_group_interface_client::ClMoveGroup::moveGroupClientInterface, moveRelative(), smacc::ISmaccClientBehavior::requiresClient(), and transform_.
    {
        ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Transform end effector pose relative: " <<
      transform_);
        this->requiresClient(movegroupClient_);
        if (this->group_)
        {
            moveit::planning_interface::MoveGroupInterface move_group(*(this->
      group_));
            this->moveRelative(move_group, this->transform_);
        }
        else
        {
            this->moveRelative(movegroupClient_->
      moveGroupClientInterface, this->transform_);
        }
    }
onExit()
void move_group_interface_client::CbMoveEndEffectorRelative::onExit () [override], [virtual]
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 40 of file cb_move_end_effector_relative.cpp.
    {
    }
Member Data Documentation
group_
boost::optional<std::string> move_group_interface_client::CbMoveEndEffectorRelative::group_
Definition at line 19 of file cb_move_end_effector_relative.h.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* move_group_interface_client::CbMoveEndEffectorRelative::movegroupClient_ [protected]
Definition at line 33 of file cb_move_end_effector_relative.h.
Referenced by moveRelative(), and onEntry().
transform_
geometry_msgs::Transform move_group_interface_client::CbMoveEndEffectorRelative::transform_
Definition at line 17 of file cb_move_end_effector_relative.h.
Referenced by CbMoveEndEffectorRelative(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.cpp