sm_moveit::cl_movegroup::ClMoveGroup Class Reference
#include <cl_movegroup.h>
Public Member Functions
ClMoveGroup (std::string groupName)
virtual ~ClMoveGroup ()
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionSuccedded (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionFailed (TCallback callback, T *object)
void moveToAbsolutePose (geometry_msgs::PoseStamped &targetPose)
bool moveEndEfectorToPose (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, moveit::planning_interface::PlanningSceneInterface &planningSceneInterface, geometry_msgs::PoseStamped &targetObjectPose)
void moveRelative (geometry_msgs::Transform &transformOffset)
void moveRelativeCartesian (geometry_msgs::Vector3 &offset)
Public Attributes
moveit::planning_interface::MoveGroupInterface moveGroupClientInterface
moveit::planning_interface::PlanningSceneInterface planningSceneInterface
Private Attributes
std::function< void()> postEventMotionExecutionSucceded
std::function< void()> postEventMotionExecutionFailed
smacc::SmaccSignal< void()> onSucceded_
smacc::SmaccSignal< void()> onFailed_
Additional Inherited Members
Detailed Description
Definition at line 57 of file cl_movegroup.h.
Constructor & Destructor Documentation
sm_moveit::cl_movegroup::ClMoveGroup::ClMoveGroup (std::string groupName)
Definition at line 10 of file cl_movegroup.cpp.
    : moveGroupClientInterface(groupName)
{
    ros::WallDuration(10.0).sleep();
}
sm_moveit::cl_movegroup::ClMoveGroup::~ClMoveGroup () [virtual]
Definition at line 16 of file cl_movegroup.cpp.
{
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void sm_moveit::cl_movegroup::ClMoveGroup::configureEventSourceTypes () [inline]
Definition at line 75 of file cl_movegroup.h.
  {
    postEventMotionExecutionSucceded = [=]() {
      this->onSucceded_();
      this->postEvent<MoveGroupMotionExecutionSucceded<TDerived, TObjectTag>>();
    };
    postEventMotionExecutionFailed = [=]() {
      this->onFailed_();
      this->postEvent<MoveGroupMotionExecutionFailed<TDerived, TObjectTag>>();
    };
  }
bool sm_moveit::cl_movegroup::ClMoveGroup::moveEndEfectorToPose (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, moveit::planning_interface::PlanningSceneInterface & planningSceneInterface, geometry_msgs::PoseStamped & targetObjectPose)
Definition at line 27 of file cl_movegroup.cpp.
References postEventMotionExecutionFailed, and postEventMotionExecutionSucceded.
Referenced by moveRelative(), and moveToAbsolutePose().
{
    moveGroupInterface.setPlanningTime(1.0);
    ROS_INFO_STREAM("Target End efector Pose: " << targetObjectPose);
    moveGroupInterface.setPoseTarget(targetObjectPose);
    moveGroupInterface.setPoseReferenceFrame("/map");
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
    ROS_INFO_NAMED("tutorial", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
    if (success)
    {
        auto executionResult = moveGroupInterface.execute(computedMotionPlan);
        if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
            ROS_INFO("[ClMoveGroup] relative motion execution succedded");
            this->postEventMotionExecutionSucceded();
        }
        else
        {
            ROS_INFO("[ClMoveGroup] motion execution failed");
            this->postEventMotionExecutionFailed();
        }
    }
    else
    {
        ROS_INFO("[ClMoveGroup] motion execution failed");
        this->postEventMotionExecutionFailed();
    }
    return success;
}
void sm_moveit::cl_movegroup::ClMoveGroup::moveRelative (geometry_msgs::Transform & transformOffset)
Definition at line 67 of file cl_movegroup.cpp.
References moveEndEfectorToPose(), moveGroupClientInterface, and planningSceneInterface.
Referenced by sm_moveit::cl_movegroup::CbMoveRelative::onEntry().
{
    auto referenceStartPose = this->moveGroupClientInterface.getCurrentPose();
    tf::Quaternion currentOrientation;
    tf::quaternionMsgToTF(referenceStartPose.pose.orientation, currentOrientation);
    tf::Quaternion desiredRelativeRotation;
    tf::quaternionMsgToTF(transformOffset.rotation, desiredRelativeRotation);
    auto targetOrientation = desiredRelativeRotation * currentOrientation;
    auto targetPose = referenceStartPose;
    tf::quaternionTFToMsg(targetOrientation, targetPose.pose.orientation);
    targetPose.pose.position.x += transformOffset.translation.x;
    targetPose.pose.position.y += transformOffset.translation.y;
    targetPose.pose.position.z += transformOffset.translation.z;
    bool success = moveEndEfectorToPose(
      moveGroupClientInterface,
                                        planningSceneInterface,
                                        targetPose);
}
void sm_moveit::cl_movegroup::ClMoveGroup::moveRelativeCartesian (geometry_msgs::Vector3 & offset)
Definition at line 91 of file cl_movegroup.cpp.
References moveGroupClientInterface, postEventMotionExecutionFailed, and postEventMotionExecutionSucceded.
Referenced by sm_moveit::cl_movegroup::CbMoveCartesianRelative::onEntry().
{
    std::vector<geometry_msgs::Pose> waypoints;
    auto referenceStartPose = this->moveGroupClientInterface.getPoseTarget();
    //auto referenceStartPose = this->moveGroupClientInterface.getCurrentPose();
    ROS_INFO_STREAM("RELATIVE MOTION, SOURCE POSE: " << referenceStartPose);
        ROS_INFO_STREAM("Offset: " << offset);
    waypoints.push_back(referenceStartPose.pose); // up and out
    auto targetObjectPose = this->moveGroupClientInterface.getPoseTarget();
    auto endPose = referenceStartPose.pose;
    endPose.position.x += offset.x;
    endPose.position.y += offset.y;
    endPose.position.z += offset.z;
    ROS_INFO_STREAM("DESTINY POSE: " << endPose);
    //target_pose2.position.x -= 0.15;
    waypoints.push_back(endPose); // left
    this->moveGroupClientInterface.setPoseTarget(endPose);
    this->moveGroupClientInterface.setMaxVelocityScalingFactor(0.1);
    moveit_msgs::RobotTrajectory trajectory;
    double fraction = this->moveGroupClientInterface.computeCartesianPath(waypoints
      ,
                                                                          0.01, // eef_step
                                                                          0.0, // jump_threshold
                                                                          trajectory);
    if (fraction == -1)
    {
        this->postEventMotionExecutionFailed();
        ROS_INFO("[ClMoveGroup] Absolute motion planning failed. Skipping execution.");
        return;
    }
    moveit::planning_interface::MoveGroupInterface::Plan grasp_pose_plan;
    //grasp_pose_plan.start_state_ = *(moveGroupInterface.getCurrentState());
    grasp_pose_plan.trajectory_ = trajectory;
    auto executionResult = this->moveGroupClientInterface.execute(grasp_pose_plan);
    if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
    {
        ROS_INFO("[ClMoveGroup] relative motion execution succedded: fraction %lf", fraction);
        this->postEventMotionExecutionSucceded();
    }
    else
    {
        ROS_INFO("[ClMoveGroup] relative motion execution failed");
        this->postEventMotionExecutionFailed();
    }
    ROS_INFO("Visualizing plan 4 (cartesian path) (%.2f%% acheived)", fraction * 100.0);
}
void sm_moveit::cl_movegroup::ClMoveGroup::moveToAbsolutePose (geometry_msgs::PoseStamped & targetPose)
Definition at line 20 of file cl_movegroup.cpp.
References moveEndEfectorToPose(), moveGroupClientInterface, and planningSceneInterface.
Referenced by sm_moveit::cl_movegroup::CbMoveAbsolute::onEntry().
{
    bool success = moveEndEfectorToPose(
      moveGroupClientInterface,
                                        planningSceneInterface,
                                        targetPose);
}
template<typename TCallback , typename T > boost::signals2::connection sm_moveit::cl_movegroup::ClMoveGroup::onMotionExecutionFailed (TCallback callback, T * object) [inline]
Definition at line 95 of file cl_movegroup.h.
Referenced by sm_moveit::SS1::SsPickObject::runtimeConfigure().
  {
    return this->getStateMachine()->createSignalConnection(
      onFailed_, callback, object);
  }
template<typename TCallback , typename T > boost::signals2::connection sm_moveit::cl_movegroup::ClMoveGroup::onMotionExecutionSuccedded (TCallback callback, T * object) [inline]
Definition at line 89 of file cl_movegroup.h.
Referenced by sm_moveit::pick_states::StNavigationPosture::runtimeConfigure(), sm_moveit::place_states::StPlaceRetreat::runtimeConfigure(), and sm_moveit::place_states::StPlaceApproach::runtimeConfigure().
  {
    return this->getStateMachine()->createSignalConnection(
      onSucceded_, callback, object);
  }
Member Data Documentation
moveit::planning_interface::MoveGroupInterface sm_moveit::cl_movegroup::ClMoveGroup::moveGroupClientInterface
Definition at line 67 of file cl_movegroup.h.
Referenced by moveRelative(), moveRelativeCartesian(), and moveToAbsolutePose().
smacc::SmaccSignal<void()> sm_moveit::cl_movegroup::ClMoveGroup::onFailed_ [private]
Definition at line 64 of file cl_movegroup.h.
smacc::SmaccSignal<void()> sm_moveit::cl_movegroup::ClMoveGroup::onSucceded_ [private]
Definition at line 63 of file cl_movegroup.h.
moveit::planning_interface::PlanningSceneInterface sm_moveit::cl_movegroup::ClMoveGroup::planningSceneInterface
Definition at line 68 of file cl_movegroup.h.
Referenced by moveRelative(), and moveToAbsolutePose().
std::function<void()> sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionFailed [private]
Definition at line 61 of file cl_movegroup.h.
Referenced by moveEndEfectorToPose(), and moveRelativeCartesian().
std::function<void()> sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionSucceded [private]
Definition at line 60 of file cl_movegroup.h.
Referenced by moveEndEfectorToPose(), and moveRelativeCartesian().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/cl_movegroup.h
smacc_client_library/moveit_z_client/src/moveit_z_client/cl_movegroup.cpp