sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem Class Reference
#include <cl_perception_system.h>
Public Member Functions
ClPerceptionSystem ()
virtual ~ClPerceptionSystem ()
void nextCube ()
void retryCubeAfterFail ()
virtual void update () override
RobotProcessStatus getCurrentTable ()
geometry_msgs::PoseStamped decidePickCubePose ()
geometry_msgs::PoseStamped decidePlacePose ()
Public Attributes
cl_move_base_z::Pose * detectedCubePose0
cl_move_base_z::Pose * detectedCubePose1
cl_move_base_z::Pose * detectedCubePose2
boost::optional< geometry_msgs::PoseStamped > originalCube0Pose
boost::optional< geometry_msgs::PoseStamped > originalCube1Pose
boost::optional< geometry_msgs::PoseStamped > originalCube2Pose
boost::optional< geometry_msgs::PoseStamped > cube0DestinationInTable1
boost::optional< geometry_msgs::PoseStamped > cube1DestinationInTable0
boost::optional< geometry_msgs::PoseStamped > cube2DestinationInTable1
ros::Time startTime
ros::Duration readDelay
int decissionsCount
int currentCube = 0
Additional Inherited Members
Detailed Description
Definition at line 19 of file cl_perception_system.h.
Constructor & Destructor Documentation
ClPerceptionSystem()
sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::ClPerceptionSystem () [inline]
Definition at line 40 of file cl_perception_system.h.
    {
        startTime = ros::Time::now();
        readDelay = ros::Duration(5);
        decissionsCount = 0;
    }
 ClPerceptionSystem()
virtual sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::~ClPerceptionSystem () [inline], [virtual]
Definition at line 47 of file cl_perception_system.h.
    {
    }
Member Function Documentation
decidePickCubePose()
geometry_msgs::PoseStamped sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::decidePickCubePose () [inline]
Definition at line 122 of file cl_perception_system.h.
References cl_move_base_z::Pose::toPoseStampedMsg(), and cl_move_base_z::Pose::waitTransformUpdate().
    {
        cl_move_base_z::Pose *targetObjectPose;
        if (currentCube == 0)
        {
            targetObjectPose = detectedCubePose0;
        }
        else if (currentCube == 1)
        {
            targetObjectPose = detectedCubePose1;
        }
        else
        {
            targetObjectPose = detectedCubePose2;
        }
        targetObjectPose->waitTransformUpdate();
        return targetObjectPose->toPoseStampedMsg();
    }
decidePlacePose()
geometry_msgs::PoseStamped sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::decidePlacePose () [inline]
Definition at line 143 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), and cl_move_base_z::Pose::toPoseMsg().
    {
        cl_move_base_z::ClMoveBaseZ *moveBaseclient;
        this->requiresClient(moveBaseclient);
        auto pose = moveBaseclient->getComponent<
      cl_move_base_z::Pose>();
        auto currentPose = pose->toPoseMsg();
        int tableIndex = 0;
        if (currentPose.position.x > -0.2) //negative side
        {
            ROS_INFO("[StOpenGripper] locate cube in table 0");
            tableIndex = 0;
        }
        else
        {
            ROS_INFO("[StOpenGripper] locate cube in table 1");
            tableIndex = 1;
        }
        decissionsCount++;
        if (tableIndex == 0)
        {
            ROS_INFO("[Perception System] deciding cube target in table 0");
            if (currentCube == 0)
            {
                ROS_INFO("[Perception System] deciding cube target 0 in table 0");
                return *originalCube0Pose;
            }
            else if (currentCube == 1)
            {
                ROS_INFO("[Perception System] deciding cube target 1 in table 0");
                return *cube1DestinationInTable0;
            }
            else
            {
                ROS_INFO("[Perception System] deciding cube target 2 in table 0");
                return *originalCube2Pose;
            }
        }
        else
        {
            if (currentCube == 0)
            {
                ROS_INFO("[Perception System] deciding cube target 0 in table 1");
                return *cube0DestinationInTable1;
            }
            else if (currentCube == 1)
            {
                ROS_INFO("[Perception System] deciding cube target 1 in table 1");
                return *originalCube1Pose;
            }
            else
            {
                ROS_INFO("[Perception System] deciding cube target 2 in table 1");
                return *cube2DestinationInTable1;
            }
        }
    }
getCurrentTable()
RobotProcessStatus sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::getCurrentTable () [inline]
Definition at line 106 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), sm_fetch_two_table_pick_n_place_1::cl_perception_system::ONTHEWAY, sm_fetch_two_table_pick_n_place_1::cl_perception_system::TABLE0, sm_fetch_two_table_pick_n_place_1::cl_perception_system::TABLE1, and cl_move_base_z::Pose::toPoseMsg().
    {
        cl_move_base_z::ClMoveBaseZ *moveBaseclient;
        this->requiresClient(moveBaseclient);
        auto pose = moveBaseclient->getComponent<
      cl_move_base_z::Pose>();
        auto currentPose = pose->toPoseMsg();
        int tableIndex = 0;
        if (currentPose.position.x > -0.2)
            return RobotProcessStatus::TABLE0;
        else if (currentPose.position.x < -0.8)
            return RobotProcessStatus::TABLE1;
        else
            return RobotProcessStatus::ONTHEWAY;
    }
nextCube()
void sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::nextCube () [inline]
Definition at line 51 of file cl_perception_system.h.
    {
        currentCube = (currentCube + 1) % 3;
        ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
    }
retryCubeAfterFail()
void sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::retryCubeAfterFail () [inline]
Definition at line 57 of file cl_perception_system.h.
    {
        currentCube = (currentCube - 1) % 3;
        ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
    }
update()
virtual void sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::update () [inline], [override], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 63 of file cl_perception_system.h.
References cl_move_base_z::Pose::isInitialized, and cl_move_base_z::Pose::toPoseStampedMsg().
    {
        auto ellapsed = ros::Time::now() - startTime;
        bool applyUpdate = ellapsed > readDelay;
        if (applyUpdate)
        {
            if (!originalCube0Pose && detectedCubePose0->
      isInitialized)
            {
                originalCube0Pose = detectedCubePose0->
      toPoseStampedMsg();
                cube0DestinationInTable1 =
      originalCube0Pose;
                (*cube0DestinationInTable1).pose.position.x = -
      originalCube0Pose->pose.position.x;
                ROS_INFO_STREAM("[Perception system] Original Cube 0 Pose captured" <<
      originalCube0Pose->pose);
                ROS_INFO_STREAM("[Perception system] Cube 0 Pose table 1 destination" << (*
      cube0DestinationInTable1));
            }
            if (!originalCube1Pose && detectedCubePose1->
      isInitialized)
            {
                originalCube1Pose = detectedCubePose1->
      toPoseStampedMsg();
                cube1DestinationInTable0 =
      originalCube1Pose;
                (*cube1DestinationInTable0).pose.position.x = -
      originalCube1Pose->pose.position.x;
                ROS_INFO_STREAM("[Perception system] Original Cube 1 Pose captured" <<
      originalCube1Pose->pose);
                ROS_INFO_STREAM("[Perception system] Cube 1 Pose table 0 destination" << (*
      cube1DestinationInTable0));
            }
            if (!originalCube2Pose && detectedCubePose2->
      isInitialized)
            {
                originalCube2Pose = detectedCubePose2->
      toPoseStampedMsg();
                cube2DestinationInTable1 =
      originalCube2Pose;
                (*cube2DestinationInTable1).pose.position.x = -originalCube2Pose->pose.
      position.x;
                ROS_INFO_STREAM("[Perception system] Original Cube 2 Pose captured" <<
      originalCube2Pose->pose);
                ROS_INFO_STREAM("[Perception system] Cube 2 Pose table 1 destination" << (*
      cube2DestinationInTable1));
            }
        }
    }
Member Data Documentation
cube0DestinationInTable1
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::cube0DestinationInTable1
Definition at line 30 of file cl_perception_system.h.
cube1DestinationInTable0
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::cube1DestinationInTable0
Definition at line 31 of file cl_perception_system.h.
cube2DestinationInTable1
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::cube2DestinationInTable1
Definition at line 32 of file cl_perception_system.h.
currentCube
int sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::currentCube = 0
Definition at line 38 of file cl_perception_system.h.
decissionsCount
int sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::decissionsCount
Definition at line 37 of file cl_perception_system.h.
detectedCubePose0
cl_move_base_z::Pose* sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::detectedCubePose0
Definition at line 22 of file cl_perception_system.h.
detectedCubePose1
cl_move_base_z::Pose* sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::detectedCubePose1
Definition at line 23 of file cl_perception_system.h.
detectedCubePose2
cl_move_base_z::Pose* sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::detectedCubePose2
Definition at line 24 of file cl_perception_system.h.
originalCube0Pose
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::originalCube0Pose
Definition at line 26 of file cl_perception_system.h.
originalCube1Pose
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::originalCube1Pose
Definition at line 27 of file cl_perception_system.h.
originalCube2Pose
boost::optional<geometry_msgs::PoseStamped> sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::originalCube2Pose
Definition at line 28 of file cl_perception_system.h.
readDelay
ros::Duration sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::readDelay
Definition at line 35 of file cl_perception_system.h.
startTime
ros::Time sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::startTime
Definition at line 34 of file cl_perception_system.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/clients/perception_system_client/cl_perception_system.h