sm_dance_bot_3::cl_lidar::CpLidarSensorData Class Reference
#include <cp_lidar_data.h>
Public Member Functions
virtual void initialize (smacc::ISmaccClient *owner) override
void MessageCallbackStoreDistanceToWall (const sensor_msgs::LaserScan &scanmsg)
Public Attributes
sensor_msgs::LaserScan lastMessage_
float forwardObstacleDistance
const float SECURITY_DISTANCE = 1
Additional Inherited Members
Detailed Description
Definition at line 8 of file cp_lidar_data.h.
Member Function Documentation
virtual void sm_dance_bot_3::cl_lidar::CpLidarSensorData::initialize (smacc::ISmaccClient * owner) [inline], [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 16 of file cp_lidar_data.h.
References MessageCallbackStoreDistanceToWall(), and smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived().
  {
    auto client_ = dynamic_cast<
      multirole_sensor_client::SmaccSubscriberClient<sensor_msgs::LaserScan>
       *>(owner);
    client_->onMessageReceived(&
      CpLidarSensorData::MessageCallbackStoreDistanceToWall,
       this);
  }
void sm_dance_bot_3::cl_lidar::CpLidarSensorData::MessageCallbackStoreDistanceToWall (const sensor_msgs::LaserScan & scanmsg) [inline]
Definition at line 22 of file cp_lidar_data.h.
Referenced by initialize().
  {
    this->lastMessage_ = scanmsg;
    auto fwdist = scanmsg.ranges[scanmsg.ranges.size() / 2] /*meter*/;
    /*if the distance is infinity or nan, use max range distance*/
    if (fwdist == std::numeric_limits<float>::infinity() || fwdist != fwdist)
    {
      this->forwardObstacleDistance = scanmsg.range_max -
      SECURITY_DISTANCE /*meters*/;
      ROS_INFO_THROTTLE(1.0, "[CpLidarSensorData] Distance to forward obstacle is not a number, setting
       default value to: %lf", scanmsg.range_max);
    }
    else
    {
      this->forwardObstacleDistance = std::max(fwdist -
      SECURITY_DISTANCE, 0.0F);
    }
  }
Member Data Documentation
float sm_dance_bot_3::cl_lidar::CpLidarSensorData::forwardObstacleDistance
Definition at line 12 of file cp_lidar_data.h.
sensor_msgs::LaserScan sm_dance_bot_3::cl_lidar::CpLidarSensorData::lastMessage_
Definition at line 11 of file cp_lidar_data.h.
const float sm_dance_bot_3::cl_lidar::CpLidarSensorData::SECURITY_DISTANCE = 1
Definition at line 14 of file cp_lidar_data.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_3/include/sm_dance_bot_3/clients/cl_lidar/components/cp_lidar_data.h