move_base_z_client::CbNavigateBackwards Class Reference
#include <cb_navigate_backward.h>
Public Member Functions
CbNavigateBackwards (float backwardDistance)
CbNavigateBackwards ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< float > backwardDistance
boost::optional< float > backwardSpeed
tf::TransformListener listener
move_base_z_client::ClMoveBaseZ * moveBaseClient_
move_base_z_client::odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 11 of file cb_navigate_backward.h.
Constructor & Destructor Documentation
move_base_z_client::CbNavigateBackwards::CbNavigateBackwards (float backwardDistance)
Definition at line 10 of file cb_navigate_backward.cpp.
References backwardDistance.
{
    if (backwardDistance < 0)
    {
        ROS_ERROR("cb backward: distance must be greater or equal than 0");
        this->backwardDistance = 0;
    }
    this->backwardDistance = backwardDistance;
}
move_base_z_client::CbNavigateBackwards::CbNavigateBackwards ()
Definition at line 20 of file cb_navigate_backward.cpp.
{
}
Member Function Documentation
void move_base_z_client::CbNavigateBackwards::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 24 of file cb_navigate_backward.cpp.
References backwardDistance, move_base_z_client::odom_tracker::OdomTracker::clearPath(), smacc::SmaccClientBehavior::currentState, smacc::ISmaccClient::getComponent(), listener, moveBaseClient_, odomTracker_, smacc::ISmaccState::param(), smacc::SmaccClientBehavior::requiresClient(), smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), move_base_z_client::PlannerSwitcher::setBackwardPlanner(), move_base_z_client::odom_tracker::OdomTracker::setStartPoint(), and move_base_z_client::odom_tracker::OdomTracker::setWorkingMode().
{
    // straight motion distance
    double dist;
    if (!backwardDistance)
    {
        this->currentState->param("straight_motion_distance", dist, 3.5);
    }
    else
    {
        dist = *backwardDistance;
    }
    ROS_INFO_STREAM("Straight motion distance: " << dist);
    this->requiresClient(moveBaseClient_);
    //this should work better with a coroutine and await
    ros::Rate rate(10.0);
    tf::StampedTransform currentPose;
    while (ros::ok())
    {
        try
        {
            listener.lookupTransform("/odom", "/base_link",
                                     ros::Time(0), currentPose);
            break;
        }
        catch (tf::TransformException ex)
        {
            ROS_ERROR("%s", ex.what());
            ros::Duration(1.0).sleep();
        }
    }
    tf::Transform forwardDeltaTransform;
    forwardDeltaTransform.setIdentity();
    forwardDeltaTransform.setOrigin(tf::Vector3(-dist, 0, 0));
    tf::Transform targetPose = currentPose * forwardDeltaTransform;
    ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    tf::poseTFToMsg(targetPose, goal.target_pose.pose);
    ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
    ros::Duration(10).sleep();
    geometry_msgs::PoseStamped currentPoseMsg;
    currentPoseMsg.header.frame_id = "/odom";
    currentPoseMsg.header.stamp = ros::Time::now();
    tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
    odomTracker_ = moveBaseClient_->getComponent<OdomTracker>();
    this->odomTracker_->clearPath();
    this->odomTracker_->setStartPoint(currentPoseMsg);
    this->odomTracker_->setWorkingMode(WorkingMode::RECORD_PATH_FORWARD);
    auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
    plannerSwitcher->setBackwardPlanner();
    moveBaseClient_->sendGoal(goal);
}
void move_base_z_client::CbNavigateBackwards::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 92 of file cb_navigate_backward.cpp.
References odomTracker_, and move_base_z_client::odom_tracker::OdomTracker::setWorkingMode().
{
    this->odomTracker_->setWorkingMode(WorkingMode::IDLE);
}
Member Data Documentation
boost::optional<float> move_base_z_client::CbNavigateBackwards::backwardDistance
Definition at line 14 of file cb_navigate_backward.h.
Referenced by CbNavigateBackwards(), and onEntry().
boost::optional<float> move_base_z_client::CbNavigateBackwards::backwardSpeed
Definition at line 17 of file cb_navigate_backward.h.
tf::TransformListener move_base_z_client::CbNavigateBackwards::listener
Definition at line 19 of file cb_navigate_backward.h.
Referenced by onEntry().
move_base_z_client::ClMoveBaseZ* move_base_z_client::CbNavigateBackwards::moveBaseClient_
Definition at line 21 of file cb_navigate_backward.h.
Referenced by onEntry().
move_base_z_client::odom_tracker::OdomTracker* move_base_z_client::CbNavigateBackwards::odomTracker_
Definition at line 22 of file cb_navigate_backward.h.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_backward.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_navigate_backward.cpp