cl_ros_timer_client::ClRosTimer Class Reference
#include <cl_ros_timer.h>
Public Member Functions
ClRosTimer (ros::Duration duration, bool oneshot=false)
virtual ~ClRosTimer ()
virtual void initialize ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
Protected Member Functions
void timerCallback (const ros::TimerEvent &timedata)
Protected Attributes
ros::NodeHandle nh_
ros::Timer timer
ros::Duration duration
bool oneshot
std::function< void()> postTimerEvent_
smacc::SmaccSignal< void()> onTimerTick_
Detailed Description
Definition at line 24 of file cl_ros_timer.h.
Constructor & Destructor Documentation
cl_ros_timer_client::ClRosTimer::ClRosTimer (ros::Duration duration, bool oneshot = false)
Definition at line 6 of file timer_client.cpp.
References duration, and oneshot.
{
    this->duration = duration;
    this->oneshot = oneshot;
}
cl_ros_timer_client::ClRosTimer::~ClRosTimer () [virtual]
Definition at line 12 of file timer_client.cpp.
References timer.
{
    timer.stop();
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void cl_ros_timer_client::ClRosTimer::configureEventSourceTypes () [inline]
Definition at line 40 of file cl_ros_timer.h.
    {
        this->postTimerEvent_ = [=]() {
            this->postEvent<EvTimer<ClRosTimer, TObjectTag>>();
        };
    }
void cl_ros_timer_client::ClRosTimer::initialize () [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 17 of file timer_client.cpp.
References duration, nh_, oneshot, timer, and timerCallback().
{
    timer = nh_.createTimer(duration, boost::bind(&
      ClRosTimer::timerCallback, this, _1), oneshot);
}
template<typename T > boost::signals2::connection cl_ros_timer_client::ClRosTimer::onTimerTick (void(T::*)() callback, T * object) [inline]
Definition at line 34 of file cl_ros_timer.h.
Referenced by cl_ros_timer_client::CbTimer::onEntry(), cl_ros_timer_client::CbTimerCountdownOnce::onEntry(), cl_ros_timer_client::CbTimerCountdownLoop::onEntry(), sm_atomic::State2::runtimeConfigure(), sm_update::State2::runtimeConfigure(), sm_atomic::State1::runtimeConfigure(), and sm_update::State1::runtimeConfigure().
    {
        return this->getStateMachine()->createSignalConnection(
      onTimerTick_, callback, object);
    }
void cl_ros_timer_client::ClRosTimer::timerCallback (const ros::TimerEvent & timedata) [protected]
Definition at line 22 of file timer_client.cpp.
References onTimerTick_, and postTimerEvent_.
Referenced by initialize().
{
    if (!onTimerTick_.empty())
    {
        this->onTimerTick_();
    }
    postTimerEvent_();
}
Member Data Documentation
ros::Duration cl_ros_timer_client::ClRosTimer::duration [protected]
Definition at line 51 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
ros::NodeHandle cl_ros_timer_client::ClRosTimer::nh_ [protected]
Definition at line 48 of file cl_ros_timer.h.
Referenced by initialize().
bool cl_ros_timer_client::ClRosTimer::oneshot [protected]
Definition at line 52 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
smacc::SmaccSignal<void()> cl_ros_timer_client::ClRosTimer::onTimerTick_ [protected]
Definition at line 56 of file cl_ros_timer.h.
Referenced by timerCallback().
std::function<void()> cl_ros_timer_client::ClRosTimer::postTimerEvent_ [protected]
Definition at line 55 of file cl_ros_timer.h.
Referenced by timerCallback().
ros::Timer cl_ros_timer_client::ClRosTimer::timer [protected]
Definition at line 50 of file cl_ros_timer.h.
Referenced by initialize(), and ~ClRosTimer().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/cl_ros_timer.h
smacc_client_library/ros_timer_client/src/ros_timer_client/timer_client.cpp