cl_move_base_z::odom_tracker::OdomTracker Class Reference
This class track the required distance of the cord based on the external localization system.
#include <odom_tracker.h>
Public Member Functions
OdomTracker (std::string odomtopicName=`/odom`, std::string odomFrame=`odom`)
virtual void processOdometryMessage (const nav_msgs::Odometry &odom)
odom callback: Updates the path - this must be called periodically for each odometry message.
void setWorkingMode (WorkingMode workingMode)
void setPublishMessages (bool value)
void pushPath ()
void popPath (int pathCount=1, bool keepPreviousPath=false)
void clearPath ()
void setStartPoint (const geometry_msgs::PoseStamped &pose)
void setStartPoint (const geometry_msgs::Pose &pose)
nav_msgs::Path getPath ()
void logStateString ()
Protected Member Functions
void reconfigCB (move_base_z_client_plugin::OdomTrackerConfig &config, uint32_t level)
virtual void rtPublishPaths (ros::Time timestamp)
virtual bool updateRecordPath (const nav_msgs::Odometry &odom)
virtual bool updateClearPath (const nav_msgs::Odometry &odom)
void updateAggregatedStackPath ()
Protected Attributes
dynamic_reconfigure::Server< move_base_z_client_plugin::OdomTrackerConfig > paramServer_
dynamic_reconfigure::Server< move_base_z_client_plugin::OdomTrackerConfig >::CallbackType f
std::shared_ptr< realtime_tools::RealtimePublisher< nav_msgs::Path > > robotBasePathPub_
std::shared_ptr< realtime_tools::RealtimePublisher< nav_msgs::Path > > robotBasePathStackedPub_
ros::Subscriber odomSub_
double recordPointDistanceThreshold_
How much distance there is between two points of the path.
double recordAngularDistanceThreshold_
Meters.
double clearPointDistanceThreshold_
rads
double clearAngularDistanceThreshold_
rads
std::string odomFrame_
bool publishMessages
nav_msgs::Path baseTrajectory_
Processed path for the mouth of the reel.
WorkingMode workingMode_
std::vector< nav_msgs::Path > pathStack_
nav_msgs::Path aggregatedStackPathMsg_
bool subscribeToOdometryTopic_
std::mutex m_mutex_
Detailed Description
This class track the required distance of the cord based on the external localization system.
Definition at line 40 of file odom_tracker.h.
Constructor & Destructor Documentation
OdomTracker()
cl_move_base_z::odom_tracker::OdomTracker::OdomTracker (std::string odomtopicName = `/odom`, std::string odomFrame = `odom`)
Definition at line 15 of file odom_tracker.cpp.
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, f, odomFrame_, odomSub_, paramServer_, processOdometryMessage(), publishMessages, reconfigCB(), cl_move_base_z::odom_tracker::RECORD_PATH, recordAngularDistanceThreshold_, recordPointDistanceThreshold_, robotBasePathPub_, robotBasePathStackedPub_, subscribeToOdometryTopic_, and workingMode_.
            : paramServer_(ros::NodeHandle("~/odom_tracker"))
        {
            workingMode_ = WorkingMode::RECORD_PATH;
            publishMessages = true;
            subscribeToOdometryTopic_ = true;
            this->odomFrame_ = odomFrame;
            ros::NodeHandle nh("~/odom_tracker");
            ROS_WARN("Initializing Odometry Tracker");
            if (!nh.getParam("odom_frame", this->odomFrame_))
            {
                ROS_INFO_STREAM("[OdomTracker] odomFrame:" << this->odomFrame_);
            }
            ROS_INFO_STREAM("[OdomTracker] odomFrame overwriten by ros parameter:" << this->
      odomFrame_);
            if (!nh.getParam("record_point_distance_threshold",
      recordPointDistanceThreshold_))
            {
                recordPointDistanceThreshold_ = 0.005; // 5 mm
            }
            ROS_INFO_STREAM("[OdomTracker] record_point_distance_threshold :" <<
      recordPointDistanceThreshold_);
            if (!nh.getParam("record_angular_distance_threshold",
      recordAngularDistanceThreshold_))
            {
                recordAngularDistanceThreshold_ = 0.1; // radians
            }
            ROS_INFO_STREAM("[OdomTracker] record_angular_distance_threshold :" <<
      recordAngularDistanceThreshold_);
            if (!nh.getParam("clear_point_distance_threshold",
      clearPointDistanceThreshold_))
            {
                clearPointDistanceThreshold_ = 0.05; // 5 cm
            }
            ROS_INFO_STREAM("[OdomTracker] clear_point_distance_threshold :" <<
      clearPointDistanceThreshold_);
            if (!nh.getParam("clear_angular_distance_threshold",
      clearAngularDistanceThreshold_))
            {
                clearAngularDistanceThreshold_ = 0.1; // radians
            }
            ROS_INFO_STREAM("[OdomTracker] clear_angular_distance_threshold :" <<
      clearAngularDistanceThreshold_);
            if (this->subscribeToOdometryTopic_)
            {
                odomSub_ = nh.subscribe(odomTopicName, 1, &
      OdomTracker::processOdometryMessage, this);
            }
            robotBasePathPub_ =
      std::make_shared<realtime_tools::RealtimePublisher<nav_msgs::Path>>(nh, "odom_tracker_path", 1);
            robotBasePathStackedPub_ =
      std::make_shared<realtime_tools::RealtimePublisher<nav_msgs::Path>>(nh, "odom_tracker_stacked_path", 1);
            f = boost::bind(&OdomTracker::reconfigCB, this, _1, _2);
            paramServer_.setCallback(f);
        }
Member Function Documentation
clearPath()
void cl_move_base_z::odom_tracker::OdomTracker::clearPath ()
Definition at line 157 of file odom_tracker.cpp.
References baseTrajectory_, logStateString(), m_mutex_, rtPublishPaths(), and updateAggregatedStackPath().
Referenced by cl_move_base_z::CbNavigateBackwards::onEntry(), and sm_dance_bot::radial_motion_states::StiRadialReturn::onExit().
        {
            std::lock_guard<std::mutex> lock(m_mutex_);
            baseTrajectory_.poses.clear();
            rtPublishPaths(ros::Time::now());
            this->logStateString();
            this->updateAggregatedStackPath();
        }
getPath()
nav_msgs::Path cl_move_base_z::odom_tracker::OdomTracker::getPath ()
Definition at line 202 of file odom_tracker.cpp.
References baseTrajectory_, and m_mutex_.
        {
            std::lock_guard<std::mutex> lock(m_mutex_);
            return this->baseTrajectory_;
        }
logStateString()
void cl_move_base_z::odom_tracker::OdomTracker::logStateString ()
Definition at line 143 of file odom_tracker.cpp.
References baseTrajectory_, and pathStack_.
Referenced by clearPath(), popPath(), and pushPath().
        {
            ROS_INFO("--- odom tracker state ---");
            ROS_INFO(" - path stack size: %ld", pathStack_.size());
            ROS_INFO(" - [STACK-HEAD active path size: %ld]", baseTrajectory_.poses.size());
            int i = 0;
            for (auto &p : pathStack_ | boost::adaptors::reversed)
            {
                ROS_INFO_STREAM(" - p " << i << "[" << p.header.stamp << "], size: " << p.poses.size());
                i++;
            }
            ROS_INFO("---");
        }
popPath()
void cl_move_base_z::odom_tracker::OdomTracker::popPath (int pathCount = 1, bool keepPreviousPath = false)
Definition at line 113 of file odom_tracker.cpp.
References baseTrajectory_, logStateString(), m_mutex_, pathStack_, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute().
        {
            ROS_INFO("odom_tracker m_mutex acquire");
            std::lock_guard<std::mutex> lock(m_mutex_);
            ROS_INFO("POP PATH ENTRY");
            this->logStateString();
            if (!keepPreviousPath)
            {
                baseTrajectory_.poses.clear();
            }
            while (popCount > 0 && !pathStack_.empty())
            {
                auto &stacked = pathStack_.back().poses;
                baseTrajectory_.poses.insert(baseTrajectory_.poses.begin(),
      stacked.begin(), stacked.end());
                pathStack_.pop_back();
                popCount--;
                ROS_INFO("POP PATH Iteration ");
                this->logStateString();
            }
            ROS_INFO("POP PATH EXITING");
            this->logStateString();
            ROS_INFO("odom_tracker m_mutex release");
            this->updateAggregatedStackPath();
        }
processOdometryMessage()
void cl_move_base_z::odom_tracker::OdomTracker::processOdometryMessage (const nav_msgs::Odometry & odom) [virtual]
odom callback: Updates the path - this must be called periodically for each odometry message.
processOdometryMessage()
Definition at line 388 of file odom_tracker.cpp.
References cl_move_base_z::odom_tracker::CLEAR_PATH, m_mutex_, publishMessages, cl_move_base_z::odom_tracker::RECORD_PATH, rtPublishPaths(), updateClearPath(), updateRecordPath(), and workingMode_.
Referenced by OdomTracker().
        {
            //ROS_INFO("odom_tracker m_mutex acquire");
            std::lock_guard<std::mutex> lock(m_mutex_);
            if (workingMode_ == WorkingMode::RECORD_PATH)
            {
                updateRecordPath(odom);
            }
            else if (workingMode_ == WorkingMode::CLEAR_PATH)
            {
                updateClearPath(odom);
            }
            //ROS_WARN("odomTracker odometry callback");
            if (publishMessages)
            {
                rtPublishPaths(odom.header.stamp);
            }
            //ROS_INFO("odom_tracker m_mutex release");
        }
pushPath()
void cl_move_base_z::odom_tracker::OdomTracker::pushPath ()
Definition at line 97 of file odom_tracker.cpp.
References baseTrajectory_, logStateString(), m_mutex_, pathStack_, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute(), cl_move_base_z::CbNavigateForward::onEntry(), and cl_move_base_z::CbAbsoluteRotate::onEntry().
        {
            ROS_INFO("odom_tracker m_mutex acquire");
            std::lock_guard<std::mutex> lock(m_mutex_);
            ROS_INFO("PUSH_PATH PATH EXITING");
            this->logStateString();
            pathStack_.push_back(baseTrajectory_);
            baseTrajectory_.poses.clear();
            ROS_INFO("PUSH_PATH PATH EXITING");
            this->logStateString();
            ROS_INFO("odom_tracker m_mutex release");
            this->updateAggregatedStackPath();
        }
reconfigCB()
void cl_move_base_z::odom_tracker::OdomTracker::reconfigCB (move_base_z_client_plugin::OdomTrackerConfig & config, uint32_t level) [protected]
reconfigCB()
Definition at line 372 of file odom_tracker.cpp.
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, odomFrame_, recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by OdomTracker().
        {
            ROS_INFO("[OdomTracker] reconfigure Request");
            this->odomFrame_ = config.odom_frame;
            this->recordPointDistanceThreshold_ = config.
      record_point_distance_threshold;
            this->recordAngularDistanceThreshold_ = config.
      record_angular_distance_threshold;
            this->clearPointDistanceThreshold_ = config.
      clear_point_distance_threshold;
            this->clearAngularDistanceThreshold_ = config.
      clear_angular_distance_threshold;
        }
rtPublishPaths()
void cl_move_base_z::odom_tracker::OdomTracker::rtPublishPaths (ros::Time timestamp) [protected], [virtual]
rtPublishPaths() Copy trajectory
Copy trajectory
Definition at line 213 of file odom_tracker.cpp.
References aggregatedStackPathMsg_, baseTrajectory_, battery_monitor_node::msg, robotBasePathPub_, and robotBasePathStackedPub_.
Referenced by clearPath(), and processOdometryMessage().
        {
            if (robotBasePathPub_->trylock())
            {
                nav_msgs::Path &msg = robotBasePathPub_->msg_;
                msg = baseTrajectory_;
                msg.header.stamp = timestamp;
                robotBasePathPub_->unlockAndPublish();
            }
            if (robotBasePathStackedPub_->trylock())
            {
                nav_msgs::Path &msg = robotBasePathStackedPub_->msg_;
                msg = aggregatedStackPathMsg_;
                msg.header.stamp = timestamp;
                robotBasePathStackedPub_->unlockAndPublish();
            }
        }
setPublishMessages()
void cl_move_base_z::odom_tracker::OdomTracker::setPublishMessages (bool value)
setPublishMessages()
Definition at line 88 of file odom_tracker.cpp.
References m_mutex_, publishMessages, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute().
        {
            //ROS_INFO("odom_tracker m_mutex acquire");
            std::lock_guard<std::mutex> lock(m_mutex_);
            publishMessages = value;
            //ROS_INFO("odom_tracker m_mutex release");
            this->updateAggregatedStackPath();
        }
setStartPoint() [1/2]
void cl_move_base_z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::PoseStamped & pose)
Definition at line 167 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and updateAggregatedStackPath().
Referenced by cl_move_base_z::CbNavigateBackwards::onEntry(), and cl_move_base_z::CbNavigateForward::onEntry().
        {
            std::lock_guard<std::mutex> lock(m_mutex_);
            ROS_INFO_STREAM("[OdomTracker] set current path starting point: " << pose);
            if (baseTrajectory_.poses.size() > 0)
            {
                baseTrajectory_.poses[0] = pose;
            }
            else
            {
                baseTrajectory_.poses.push_back(pose);
            }
            this->updateAggregatedStackPath();
        }
setStartPoint() [2/2]
void cl_move_base_z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::Pose & pose)
Definition at line 182 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, odomFrame_, and updateAggregatedStackPath().
        {
            std::lock_guard<std::mutex> lock(m_mutex_);
            ROS_INFO_STREAM("[OdomTracker] set current path starting point: " << pose);
            geometry_msgs::PoseStamped posestamped;
            posestamped.header.frame_id = this->odomFrame_;
            posestamped.header.stamp = ros::Time::now();
            posestamped.pose = pose;
            if (baseTrajectory_.poses.size() > 0)
            {
                baseTrajectory_.poses[0] = posestamped;
            }
            else
            {
                baseTrajectory_.poses.push_back(posestamped);
            }
            this->updateAggregatedStackPath();
        }
setWorkingMode()
void cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode (WorkingMode workingMode)
setWorkingMode()
Definition at line 74 of file odom_tracker.cpp.
References m_mutex_, and workingMode_.
Referenced by OdomTrackerActionServer::execute(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateBackwards::onExit(), and cl_move_base_z::CbNavigateForward::onExit().
        {
            //ROS_INFO("odom_tracker m_mutex acquire");
            std::lock_guard<std::mutex> lock(m_mutex_);
            ROS_INFO("[OdomTracker] setting working mode to: %d", (uint8_t)workingMode);
            workingMode_ = workingMode;
            //ROS_INFO("odom_tracker m_mutex release");
        }
updateAggregatedStackPath()
void cl_move_base_z::odom_tracker::OdomTracker::updateAggregatedStackPath () [protected]
Definition at line 237 of file odom_tracker.cpp.
References aggregatedStackPathMsg_, odomFrame_, and pathStack_.
Referenced by clearPath(), popPath(), pushPath(), setPublishMessages(), and setStartPoint().
        {
            aggregatedStackPathMsg_.poses.clear();
            for (auto &p : pathStack_)
            {
                aggregatedStackPathMsg_.poses.insert(
      aggregatedStackPathMsg_.poses.end(), p.poses.begin(), p.poses.end());
            }
            aggregatedStackPathMsg_.header.frame_id = this->
      odomFrame_;
        }
updateClearPath()
bool cl_move_base_z::odom_tracker::OdomTracker::updateClearPath (const nav_msgs::Odometry & odom) [protected], [virtual]
updateBackward() Track robot base pose
Not removing point because it is enough far from the last cord point
Definition at line 253 of file odom_tracker.cpp.
References baseTrajectory_, clearAngularDistanceThreshold_, clearPointDistanceThreshold_, and cl_move_base_z::odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
        {
            // we initially accept any message if the queue is empty
            geometry_msgs::PoseStamped base_pose;
            base_pose.pose = odom.pose.pose;
            base_pose.header = odom.header;
            baseTrajectory_.header = odom.header;
            bool acceptBackward = false;
            bool clearingError = false;
            bool finished = false;
            while(!finished)
            {
                if (baseTrajectory_.poses.size() <= 1) // we at least keep always the first
       point of the forward path when clearing (this is important for backwards planner replanning and not losing
       the last goal)
                {
                    acceptBackward = false;
                    finished = true;
                }
                else
                {
                    auto &carrotPose = baseTrajectory_.poses.back().pose;
                    const geometry_msgs::Point &carrotPoint = carrotPose.position;
                    double carrotAngle = tf::getYaw(carrotPose.orientation);
                    auto &currePose = base_pose.pose;
                    const geometry_msgs::Point &currePoint = currePose.position;
                    double currentAngle = tf::getYaw(currePose.orientation);
                    double lastpointdist = p2pDistance(carrotPoint, currePoint);
                    double goalAngleOffset = fabs(angles::shortest_angular_distance(carrotAngle,
      currentAngle));
                    acceptBackward = !baseTrajectory_.poses.empty()
                                        && lastpointdist <
      clearPointDistanceThreshold_ && goalAngleOffset <
      clearAngularDistanceThreshold_;
                    clearingError = lastpointdist > 2 *
      clearPointDistanceThreshold_;
                    ROS_DEBUG_STREAM("[OdomTracker] clearing (accepted: "<< acceptBackward <<") linerr: "<<
       lastpointdist << ", anglerr: " << goalAngleOffset);
                }
                //ROS_INFO("Backwards, last distance: %lf < %lf accept: %d", dist,
       minPointDistanceBackwardThresh_, acceptBackward);
                if (acceptBackward && baseTrajectory_.poses.size() > 1)/*we always leave at
       least one item, specially interesting for the backward local planner reach the backwards goal with
       precission enough*/
                {
                    baseTrajectory_.poses.pop_back();
                }
                else if (clearingError)
                {
                    finished = true;
                    ROS_WARN("[OdomTracker] Incorrect odom clearing motion.");
                }
                else
                {
                    finished = true;
                }
            }
            return acceptBackward;
        }
updateRecordPath()
bool cl_move_base_z::odom_tracker::OdomTracker::updateRecordPath (const nav_msgs::Odometry & odom) [protected], [virtual]
updateRecordPath() Track robot base pose
Definition at line 318 of file odom_tracker.cpp.
References baseTrajectory_, cl_move_base_z::odom_tracker::p2pDistance(), recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by processOdometryMessage().
        {
            geometry_msgs::PoseStamped base_pose;
            base_pose.pose = odom.pose.pose;
            base_pose.header = odom.header;
            baseTrajectory_.header = odom.header;
            bool enqueueOdomMessage = false;
            double dist = -1;
            if (baseTrajectory_.poses.empty())
            {
                enqueueOdomMessage = true;
            }
            else
            {
                const auto &prevPose = baseTrajectory_.poses.back().pose;
                const geometry_msgs::Point &prevPoint = prevPose.position;
                double prevAngle = tf::getYaw(prevPose.orientation);
                const geometry_msgs::Point &currePoint = base_pose.pose.position;
                double currentAngle = tf::getYaw(base_pose.pose.orientation);
                dist = p2pDistance(prevPoint, currePoint);
                double goalAngleOffset = fabs(angles::shortest_angular_distance(prevAngle, currentAngle));
                //ROS_WARN("dist %lf vs min %lf", dist, recordPointDistanceThreshold_);
                if (dist > recordPointDistanceThreshold_ || goalAngleOffset >
      recordAngularDistanceThreshold_)
                {
                    enqueueOdomMessage = true;
                }
                else
                {
                    //ROS_WARN("skip odom, dist: %lf", dist);
                    enqueueOdomMessage = false;
                }
            }
            if (enqueueOdomMessage)
            {
                baseTrajectory_.poses.push_back(base_pose);
            }
            return enqueueOdomMessage;
        }
Member Data Documentation
aggregatedStackPathMsg_
nav_msgs::Path cl_move_base_z::odom_tracker::OdomTracker::aggregatedStackPathMsg_ [protected]
Definition at line 131 of file odom_tracker.h.
Referenced by rtPublishPaths(), and updateAggregatedStackPath().
baseTrajectory_
nav_msgs::Path cl_move_base_z::odom_tracker::OdomTracker::baseTrajectory_ [protected]
Processed path for the mouth of the reel.
Definition at line 125 of file odom_tracker.h.
Referenced by clearPath(), getPath(), logStateString(), popPath(), pushPath(), rtPublishPaths(), setStartPoint(), updateClearPath(), and updateRecordPath().
clearAngularDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::clearAngularDistanceThreshold_ [protected]
rads
Definition at line 116 of file odom_tracker.h.
Referenced by OdomTracker(), reconfigCB(), and updateClearPath().
clearPointDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::clearPointDistanceThreshold_ [protected]
rads
Definition at line 113 of file odom_tracker.h.
Referenced by OdomTracker(), reconfigCB(), and updateClearPath().
f
dynamic_reconfigure::Server<move_base_z_client_plugin::OdomTrackerConfig>::CallbackType cl_move_base_z::odom_tracker::OdomTracker::f [protected]
Definition at line 81 of file odom_tracker.h.
Referenced by OdomTracker().
m_mutex_
std::mutex cl_move_base_z::odom_tracker::OdomTracker::m_mutex_ [protected]
Definition at line 136 of file odom_tracker.h.
Referenced by clearPath(), getPath(), popPath(), processOdometryMessage(), pushPath(), setPublishMessages(), setStartPoint(), and setWorkingMode().
odomFrame_
std::string cl_move_base_z::odom_tracker::OdomTracker::odomFrame_ [protected]
Definition at line 118 of file odom_tracker.h.
Referenced by OdomTracker(), reconfigCB(), setStartPoint(), and updateAggregatedStackPath().
odomSub_
ros::Subscriber cl_move_base_z::odom_tracker::OdomTracker::odomSub_ [protected]
Definition at line 103 of file odom_tracker.h.
Referenced by OdomTracker().
paramServer_
dynamic_reconfigure::Server<move_base_z_client_plugin::OdomTrackerConfig> cl_move_base_z::odom_tracker::OdomTracker::paramServer_ [protected]
Definition at line 80 of file odom_tracker.h.
Referenced by OdomTracker().
pathStack_
std::vector<nav_msgs::Path> cl_move_base_z::odom_tracker::OdomTracker::pathStack_ [protected]
Definition at line 129 of file odom_tracker.h.
Referenced by logStateString(), popPath(), pushPath(), and updateAggregatedStackPath().
publishMessages
bool cl_move_base_z::odom_tracker::OdomTracker::publishMessages [protected]
Definition at line 122 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setPublishMessages().
recordAngularDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::recordAngularDistanceThreshold_ [protected]
Meters.
Definition at line 110 of file odom_tracker.h.
Referenced by OdomTracker(), reconfigCB(), and updateRecordPath().
recordPointDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::recordPointDistanceThreshold_ [protected]
How much distance there is between two points of the path.
Definition at line 107 of file odom_tracker.h.
Referenced by OdomTracker(), reconfigCB(), and updateRecordPath().
robotBasePathPub_
std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::Path> > cl_move_base_z::odom_tracker::OdomTracker::robotBasePathPub_ [protected]
Definition at line 97 of file odom_tracker.h.
Referenced by OdomTracker(), and rtPublishPaths().
robotBasePathStackedPub_
std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::Path> > cl_move_base_z::odom_tracker::OdomTracker::robotBasePathStackedPub_ [protected]
Definition at line 98 of file odom_tracker.h.
Referenced by OdomTracker(), and rtPublishPaths().
subscribeToOdometryTopic_
bool cl_move_base_z::odom_tracker::OdomTracker::subscribeToOdometryTopic_ [protected]
Definition at line 134 of file odom_tracker.h.
Referenced by OdomTracker().
workingMode_
WorkingMode cl_move_base_z::odom_tracker::OdomTracker::workingMode_ [protected]
Definition at line 127 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setWorkingMode().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/odom_tracker/odom_tracker.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/odom_tracker/odom_tracker.cpp