keyboard_client::ClKeyboard Class Reference
#include <cl_keyboard.h>
Public Member Functions
template<typename T >
void OnKeyPress (void(T::*callback)(char keypress), T *object)
ClKeyboard ()
virtual ~ClKeyboard ()
virtual void initialize () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Attributes
smacc::SmaccSignal< void(char keypress)> OnKeyPress_
std::function< void(std_msgs::UInt16)> postEventKeyPress
Private Attributes
bool initialized_
Additional Inherited Members
Detailed Description
Definition at line 148 of file cl_keyboard.h.
Constructor & Destructor Documentation
keyboard_client::ClKeyboard::ClKeyboard ()
Definition at line 4 of file cl_keyboard.cpp.
References initialized_, and smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::topicName.
                       {
  initialized_ = false;
  topicName = "/keyboard_unicode";
}
keyboard_client::ClKeyboard::~ClKeyboard () [virtual]
Definition at line 9 of file cl_keyboard.cpp.
{
  
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void keyboard_client::ClKeyboard::configureEventSourceTypes () [inline]
Definition at line 169 of file cl_keyboard.h.
        {
                // call tothe base configuration to properly handling the message and initial message smacc
       events
                
      smacc::client_bases::SmaccSubscriberClient<std_msgs::UInt16>::configureEventSourceTypes
      <TObjectTag, TDerived>();
                postEventKeyPress = [=](auto unicode_keychar) {
                        char character = (char)unicode_keychar.data;
                        ROS_WARN("detected keyboard: %c", character);
                        if (character == 'a')
                                this->postKeyEvent<EvKeyPressA<ClKeyboard, TObjectTag>>();
                        else if (character == 'b')
                                this->postKeyEvent<EvKeyPressB<ClKeyboard, TObjectTag>>();
                        else if (character == 'c')
                                this->postKeyEvent<EvKeyPressC<ClKeyboard, TObjectTag>>();
                        else if (character == 'd')
                                this->postKeyEvent<EvKeyPressD<ClKeyboard, TObjectTag>>();
                        else if (character == 'e')
                                this->postKeyEvent<EvKeyPressE<ClKeyboard, TObjectTag>>();
                        else if (character == 'f')
                                this->postKeyEvent<EvKeyPressF<ClKeyboard, TObjectTag>>();
                        else if (character == 'g')
                                this->postKeyEvent<EvKeyPressG<ClKeyboard, TObjectTag>>();
                        else if (character == 'h')
                                this->postKeyEvent<EvKeyPressH<ClKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressI<ClKeyboard, TObjectTag>>();
                        else if (character == 'j')
                                this->postKeyEvent<EvKeyPressJ<ClKeyboard, TObjectTag>>();
                        else if (character == 'k')
                                this->postKeyEvent<EvKeyPressK<ClKeyboard, TObjectTag>>();
                        else if (character == 'l')
                                this->postKeyEvent<EvKeyPressL<ClKeyboard, TObjectTag>>();
                        else if (character == 'm')
                                this->postKeyEvent<EvKeyPressM<ClKeyboard, TObjectTag>>();
                        else if (character == 'n')
                                this->postKeyEvent<EvKeyPressN<ClKeyboard, TObjectTag>>();
                        else if (character == 'o')
                                this->postKeyEvent<EvKeyPressO<ClKeyboard, TObjectTag>>();
                        else if (character == 'p')
                                this->postKeyEvent<EvKeyPressP<ClKeyboard, TObjectTag>>();
                        else if (character == 'q')
                                this->postKeyEvent<EvKeyPressQ<ClKeyboard, TObjectTag>>();
                        else if (character == 'r')
                                this->postKeyEvent<EvKeyPressR<ClKeyboard, TObjectTag>>();
                        else if (character == 's')
                                this->postKeyEvent<EvKeyPressS<ClKeyboard, TObjectTag>>();
                        else if (character == 't')
                                this->postKeyEvent<EvKeyPressT<ClKeyboard, TObjectTag>>();
                        else if (character == 'u')
                                this->postKeyEvent<EvKeyPressU<ClKeyboard, TObjectTag>>();
                        else if (character == 'v')
                                this->postKeyEvent<EvKeyPressV<ClKeyboard, TObjectTag>>();
                        else if (character == 'w')
                                this->postKeyEvent<EvKeyPressW<ClKeyboard, TObjectTag>>();
                        else if (character == 'x')
                                this->postKeyEvent<EvKeyPressX<ClKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressY<ClKeyboard, TObjectTag>>();
                        else if (character == 'z')
                                this->postKeyEvent<EvKeyPressZ<ClKeyboard, TObjectTag>>();
                        OnKeyPress_(character); /* */
                };
        }
void keyboard_client::ClKeyboard::initialize () [override], [virtual]
Reimplemented from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >.
Definition at line 14 of file cl_keyboard.cpp.
References smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::initialize(), initialized_, onKeyboardMessage(), and smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::onMessageReceived().
                            {
  SmaccSubscriberClient<std_msgs::UInt16>::initialize();
  if (!this->initialized_) {
    this->onMessageReceived(&ClKeyboard::onKeyboardMessage,
      this);
    this->initialized_ = true;
  }
}
void keyboard_client::ClKeyboard::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar)
Definition at line 24 of file cl_keyboard.cpp.
References postEventKeyPress.
Referenced by initialize().
                                                                        {
  
  postEventKeyPress(unicode_keychar);
}
template<typename T > void keyboard_client::ClKeyboard::OnKeyPress (void(T::*)(char keypress) callback, T * object) [inline]
Definition at line 154 of file cl_keyboard.h.
Referenced by keyboard_client::CbDefaultKeyboardBehavior::onEntry().
        {
                //this->connectSignal(OnKeyPress_, callback, object);
                this->getStateMachine()->createSignalConnection(
      OnKeyPress_, callback, object);
        }
template<typename TEv > void keyboard_client::ClKeyboard::postKeyEvent () [inline]
Definition at line 237 of file cl_keyboard.h.
References smacc::introspection::demangleSymbol().
        {
                ROS_WARN("ClKeyboard ev: %s", smacc::demangleSymbol(typeid(TEv).name()
      ).c_str());
                this->postEvent<TEv>();
        }
Member Data Documentation
bool keyboard_client::ClKeyboard::initialized_ [private]
Definition at line 244 of file cl_keyboard.h.
Referenced by ClKeyboard(), and initialize().
smacc::SmaccSignal<void(char keypress)> keyboard_client::ClKeyboard::OnKeyPress_
Definition at line 151 of file cl_keyboard.h.
std::function<void(std_msgs::UInt16)> keyboard_client::ClKeyboard::postEventKeyPress
Definition at line 166 of file cl_keyboard.h.
Referenced by onKeyboardMessage().
The documentation for this class was generated from the following files:
smacc_client_library/keyboard_client/include/keyboard_client/cl_keyboard.h
smacc_client_library/keyboard_client/src/keyboard_client/cl_keyboard.cpp