smacc::SmaccClientBehavior Class Reference
#include <smacc_client_behavior.h>
Public Member Functions
SmaccClientBehavior ()
virtual ~SmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ISmaccState * getCurrentState ()
Private Member Functions
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
Private Attributes
ISmaccStateMachine * stateMachine_
ISmaccState * currentState
smacc::ISmaccOrthogonal * currentOrthogonal
Friends
class ISmaccState
class ISmaccOrthogonal
Detailed Description
Definition at line 14 of file smacc_client_behavior.h.
Constructor & Destructor Documentation
SmaccClientBehavior()
smacc::SmaccClientBehavior::SmaccClientBehavior ()
Definition at line 5 of file smacc_client_behavior.cpp.
References currentState, and stateMachine_.
    {
        stateMachine_ = nullptr;
        currentState = nullptr;
    }
 SmaccClientBehavior()
smacc::SmaccClientBehavior::~SmaccClientBehavior () [virtual]
Definition at line 11 of file smacc_client_behavior.cpp.
    {
        ROS_WARN("Client behavior deallocated.");
    }
Member Function Documentation
configureEventSourceTypes()
template<typename TObjectTag , typename TDerived >
void smacc::SmaccClientBehavior::configureEventSourceTypes () [private]
Definition at line 72 of file smacc_client_behavior_impl.h.
{}
getCurrentState()
ISmaccState * smacc::SmaccClientBehavior::getCurrentState () [inline]
Definition at line 47 of file smacc_client_behavior_impl.h.
References currentState.
Referenced by cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), and cl_move_base_z::CbNavigateGlobalPosition::readStartPoseFromParameterServer().
{
    return this->currentState;
}
getName()
std::string smacc::SmaccClientBehavior::getName () const
Definition at line 16 of file smacc_client_behavior.cpp.
References smacc::introspection::demangleSymbol().
Referenced by onEntry(), onExit(), and runtimeConfigure().
    {
        return demangleSymbol(typeid(*this).name());
    }
getStateMachine()
ISmaccStateMachine * smacc::SmaccClientBehavior::getStateMachine () [inline]
Definition at line 41 of file smacc_client_behavior_impl.h.
References stateMachine_.
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), cl_ros_timer::CbTimerCountdownOnce::onTimerTick(), and cl_ros_timer::CbTimerCountdownLoop::onTimerTick().
{
    return this->stateMachine_;
}
onEntry()
void smacc::SmaccClientBehavior::onEntry () [virtual]
Reimplemented in cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >, cl_move_base_z::CbNavigateForward, cl_ros_publisher::CbDefaultPublishLoop, cl_move_base_z::CbAbsoluteRotate, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_move_base_z::CbNavigateBackwards, cl_move_base_z::CbRotate, cl_move_base_z::CbNavigateGlobalPosition, moveit_z_client::CbMoveCartesianRelative, moveit_z_client::CbMoveNamedTarget, sm_dance_bot::cl_service3::CbService3, sm_dance_bot_2::cl_service3::CbService3, sm_dance_bot_strikes_back::cl_service3::CbService3, moveit_z_client::CbMoveEndEffectorRelative, moveit_z_client::CbMoveJoints, cl_move_base_z::CbUndoPathBackwards, moveit_z_client::CbMoveEndEffector, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, cl_move_base_z::CbNavigateNextWaypoint, sm_dance_bot::cl_lidar::CbLidarSensor, sm_dance_bot_2::cl_lidar::CbLidarSensor, sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor, cl_keyboard::CbDefaultKeyboardBehavior, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot_2::cl_led::CbLEDOff, sm_dance_bot_2::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, cl_ros_timer::CbTimerCountdownLoop, sm_calendar_week::cl_subscriber::CbDefaultSubscriberBehavior, sm_calendar_week::cl_subscriber::CbWatchdogSubscriberBehavior, sm_moveit::cl_gripper::CbCloseGripper, sm_moveit_2::cl_gripper::CbCloseGripper, sm_moveit_3::cl_gripper::CbCloseGripper, sm_moveit_4::cl_gripper::CbCloseGripper, sm_packml::cl_subscriber::CbDefaultSubscriberBehavior, sm_packml::cl_subscriber::CbWatchdogSubscriberBehavior, sm_respira_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_respira_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_starcraft_ai::cl_subscriber::CbDefaultSubscriberBehavior, sm_starcraft_ai::cl_subscriber::CbWatchdogSubscriberBehavior, sm_three_some::cl_subscriber::CbDefaultSubscriberBehavior, sm_three_some::cl_subscriber::CbWatchdogSubscriberBehavior, cl_ros_timer::CbTimerCountdownOnce, sm_moveit::cl_gripper::CbOpenGripper, sm_moveit_2::cl_gripper::CbOpenGripper, sm_moveit_3::cl_gripper::CbOpenGripper, sm_moveit_4::cl_gripper::CbOpenGripper, sm_pr2_plugs::cl_subscriber::CbDefaultSubscriberBehavior, sm_pr2_plugs::cl_subscriber::CbWatchdogSubscriberBehavior, cl_ros_publisher::CbMutedBehavior< RosMsgType >, and cl_ros_timer::CbTimer.
Definition at line 21 of file smacc_client_behavior.cpp.
References getName().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior onEntry", this->
      getName().c_str());
    }
onExit()
void smacc::SmaccClientBehavior::onExit () [virtual]
Reimplemented in cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >, cl_ros_publisher::CbDefaultPublishLoop, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_move_base_z::CbNavigateGlobalPosition, cl_move_base_z::CbNavigateForward, cl_move_base_z::CbAbsoluteRotate, cl_move_base_z::CbNavigateBackwards, moveit_z_client::CbMoveCartesianRelative, moveit_z_client::CbMoveNamedTarget, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, moveit_z_client::CbMoveEndEffectorRelative, cl_move_base_z::CbUndoPathBackwards, moveit_z_client::CbMoveJoints, sm_moveit::cl_gripper::CbCloseGripper, sm_moveit_2::cl_gripper::CbCloseGripper, sm_moveit_3::cl_gripper::CbCloseGripper, sm_moveit_4::cl_gripper::CbCloseGripper, moveit_z_client::CbMoveEndEffector, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot_2::cl_led::CbLEDOff, sm_dance_bot_2::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_moveit::cl_gripper::CbOpenGripper, sm_moveit_2::cl_gripper::CbOpenGripper, sm_moveit_3::cl_gripper::CbOpenGripper, sm_moveit_4::cl_gripper::CbOpenGripper, cl_move_base_z::CbNavigateNextWaypoint, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, and cl_ros_timer::CbTimer.
Definition at line 31 of file smacc_client_behavior.cpp.
References getName().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior onExit", this->getName().c_str());
    }
postEvent() [1/2]
template<typename EventType >
void smacc::SmaccClientBehavior::postEvent (const EventType & ev)
Definition at line 15 of file smacc_client_behavior_impl.h.
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
        stateMachine_->postEvent(ev);
    }
}
postEvent() [2/2]
template<typename EventType >
void smacc::SmaccClientBehavior::postEvent ()
Definition at line 28 of file smacc_client_behavior_impl.h.
References stateMachine_.
Referenced by cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent().
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
        stateMachine_->template postEvent<EventType>();
    }
}
requiresClient()
template<typename SmaccClientType >
void smacc::SmaccClientBehavior::requiresClient (SmaccClientType *& storage)
Definition at line 53 of file smacc_client_behavior_impl.h.
References currentOrthogonal, and smacc::ISmaccOrthogonal::requiresClient().
Referenced by cl_ros_timer::CbTimer::onEntry(), cl_ros_timer::CbTimerCountdownOnce::onEntry(), sm_moveit::cl_gripper::CbOpenGripper::onEntry(), sm_moveit_2::cl_gripper::CbOpenGripper::onEntry(), sm_moveit_3::cl_gripper::CbOpenGripper::onEntry(), sm_moveit_4::cl_gripper::CbOpenGripper::onEntry(), sm_moveit_3::cl_gripper::CbCloseGripper::onEntry(), sm_moveit_4::cl_gripper::CbCloseGripper::onEntry(), cl_ros_timer::CbTimerCountdownLoop::onEntry(), sm_moveit::cl_gripper::CbCloseGripper::onEntry(), sm_moveit_2::cl_gripper::CbCloseGripper::onEntry(), sm_dance_bot::cl_led::CbLEDOff::onEntry(), sm_dance_bot_2::cl_led::CbLEDOff::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOff::onEntry(), sm_dance_bot_2::cl_led::CbLEDOn::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOn::onEntry(), sm_dance_bot::cl_led::CbLEDOn::onEntry(), cl_keyboard::CbDefaultKeyboardBehavior::onEntry(), cl_move_base_z::CbNavigateNextWaypoint::onEntry(), moveit_z_client::CbMoveEndEffector::onEntry(), sm_dance_bot_2::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), moveit_z_client::CbMoveJoints::onEntry(), moveit_z_client::CbMoveEndEffectorRelative::onEntry(), moveit_z_client::CbMoveNamedTarget::onEntry(), moveit_z_client::CbMoveCartesianRelative::onEntry(), cl_move_base_z::CbNavigateGlobalPosition::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_ros_publisher::CbPublishOnce< RosMsgType >::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_ros_publisher::CbDefaultPublishLoop::onEntry(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >::onEntry(), and cl_move_base_z::CbUndoPathBackwards::onExit().
{
    currentOrthogonal->requiresClient(storage);
}
requiresComponent()
template<typename SmaccComponentType >
void smacc::SmaccClientBehavior::requiresComponent (SmaccComponentType *& storage)
Definition at line 59 of file smacc_client_behavior_impl.h.
References smacc::ISmaccStateMachine::requiresComponent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("Cannot use the requiresComponent funcionality before asigning the client behavior to an
       orthogonal. Try using the OnEntry method to capture required components.");
    }
    else
    {
        stateMachine_->requiresComponent(storage);
    }
}
runtimeConfigure()
void smacc::SmaccClientBehavior::runtimeConfigure () [virtual]
Definition at line 26 of file smacc_client_behavior.cpp.
References getName().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior runtimeConfigure", this->
      getName().c_str());
    }
Friends And Related Function Documentation
ISmaccOrthogonal
friend class ISmaccOrthogonal [friend]
Definition at line 58 of file smacc_client_behavior.h.
ISmaccState
friend class ISmaccState [friend]
Definition at line 57 of file smacc_client_behavior.h.
Member Data Documentation
currentOrthogonal
smacc::ISmaccOrthogonal* smacc::SmaccClientBehavior::currentOrthogonal [private]
Definition at line 55 of file smacc_client_behavior.h.
Referenced by requiresClient().
currentState
ISmaccState* smacc::SmaccClientBehavior::currentState [private]
Definition at line 53 of file smacc_client_behavior.h.
Referenced by getCurrentState(), and SmaccClientBehavior().
stateMachine_
ISmaccStateMachine* smacc::SmaccClientBehavior::stateMachine_ [private]
Definition at line 50 of file smacc_client_behavior.h.
Referenced by getStateMachine(), postEvent(), requiresComponent(), and SmaccClientBehavior().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_client_behavior.h
smacc/include/smacc/impl/smacc_client_behavior_impl.h
smacc/src/smacc/smacc_client_behavior.cpp