move_base_z_client::CbNavigateGlobalPosition Class Reference
#include <cb_navigate_global_position.h>
Public Member Functions
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (ClMoveBaseZ::Goal &goal)
virtual void onExit () override
Public Attributes
boost::optional< geometry_msgs::Point > initialPoint
boost::optional< float > initialYaw
Private Attributes
ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 20 of file cb_navigate_global_position.h.
Constructor & Destructor Documentation
move_base_z_client::CbNavigateGlobalPosition::CbNavigateGlobalPosition ()
Definition at line 8 of file cb_navigate_global_position.cpp.
{
}
move_base_z_client::CbNavigateGlobalPosition::CbNavigateGlobalPosition (float x, float y, float yaw)
Definition at line 12 of file cb_navigate_global_position.cpp.
References initialPoint, and initialYaw.
{
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y = y;
    initialPoint = p;
    initialYaw = yaw;
}
Member Function Documentation
void move_base_z_client::CbNavigateGlobalPosition::goToRadialStart ()
Definition at line 40 of file cb_navigate_global_position.cpp.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccClientBehavior::stateMachine_.
Referenced by onEntry().
{
    ROS_INFO("Sending Goal to MoveBase");
    ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine_->setGlobalSMData("radial_start_pose", goal.target_pose)
      ;
    moveBaseClient_->sendGoal(goal);
}
void move_base_z_client::CbNavigateGlobalPosition::onEntry () [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 21 of file cb_navigate_global_position.cpp.
References smacc::ISmaccClient::getComponent(), goToRadialStart(), moveBaseClient_, smacc::SmaccClientBehavior::requiresClient(), and move_base_z_client::PlannerSwitcher::setDefaultPlanners().
{
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresClient(moveBaseClient_);
    auto *odomTracker = moveBaseClient_->getComponent<OdomTracker>();
    ROS_INFO("Component requirements completed");
    auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
    plannerSwitcher->setDefaultPlanners();
    odomTracker->setWorkingMode(WorkingMode::RECORD_PATH_FORWARD);
    goToRadialStart();
}
void move_base_z_client::CbNavigateGlobalPosition::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 77 of file cb_navigate_global_position.cpp.
{
    ROS_INFO("Exiting move goal Action Client");
}
void move_base_z_client::CbNavigateGlobalPosition::readStartPoseFromParameterServer (ClMoveBaseZ::Goal & goal)
Definition at line 55 of file cb_navigate_global_position.cpp.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccState::getParam(), initialPoint, and initialYaw.
Referenced by goToRadialStart().
{
    if (!initialPoint)
    {
        this->currentState->getParam("start_position_x", goal.target_pose.pose.position
      .x);
        this->currentState->getParam("start_position_y", goal.target_pose.pose.position
      .y);
        double yaw;
        this->currentState->getParam("start_position_yaw", yaw);
        goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(yaw);
    }
    else
    {
        goal.target_pose.pose.position = *initialPoint;
        goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(*
      initialYaw);
    }
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
}
Member Data Documentation
boost::optional<geometry_msgs::Point> move_base_z_client::CbNavigateGlobalPosition::initialPoint
Definition at line 23 of file cb_navigate_global_position.h.
Referenced by CbNavigateGlobalPosition(), and readStartPoseFromParameterServer().
boost::optional<float> move_base_z_client::CbNavigateGlobalPosition::initialYaw
Definition at line 24 of file cb_navigate_global_position.h.
Referenced by CbNavigateGlobalPosition(), and readStartPoseFromParameterServer().
ClMoveBaseZ* move_base_z_client::CbNavigateGlobalPosition::moveBaseClient_ [private]
Definition at line 44 of file cb_navigate_global_position.h.
Referenced by goToRadialStart(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_global_position.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_navigate_global_position.cpp