sm_moveit::cl_movegroup::CbMoveEndEffectorRelative Class Reference
#include <cb_move_end_effector_relative.h>
Public Member Functions
CbMoveEndEffectorRelative ()
CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
virtual void onEntry () override
virtual void onExit () override
void moveRelative (geometry_msgs::Transform &transformOffset)
Public Attributes
geometry_msgs::Transform transform_
Private Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 16 of file cb_move_end_effector_relative.h.
Constructor & Destructor Documentation
sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative ()
Definition at line 15 of file cb_move_end_effector_relative.cpp.
References transform_.
{
    transform_.rotation.w = 1;
}
sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
Definition at line 20 of file cb_move_end_effector_relative.cpp.
{
}
Member Function Documentation
void sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::moveRelative (geometry_msgs::Transform & transformOffset)
Definition at line 35 of file cb_move_end_effector_relative.cpp.
References movegroupClient_, sm_moveit::cl_movegroup::ClMoveGroup::moveGroupClientInterface, sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionFailed(), and sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionSucceded().
Referenced by onEntry().
{
    auto &moveGroupInterface = movegroupClient_->
      moveGroupClientInterface;
    auto referenceStartPose = moveGroupInterface.getCurrentPose();
    tf::Quaternion currentOrientation;
    tf::quaternionMsgToTF(referenceStartPose.pose.orientation, currentOrientation);
    tf::Quaternion desiredRelativeRotation;
    tf::quaternionMsgToTF(transformOffset.rotation, desiredRelativeRotation);
    auto targetOrientation = desiredRelativeRotation * currentOrientation;
    geometry_msgs::PoseStamped targetObjectPose = referenceStartPose;
    tf::quaternionTFToMsg(targetOrientation, targetObjectPose.pose.orientation);
    targetObjectPose.pose.position.x += transformOffset.translation.x;
    targetObjectPose.pose.position.y += transformOffset.translation.y;
    targetObjectPose.pose.position.z += transformOffset.translation.z;
    moveGroupInterface.setPlanningTime(1.0);
    ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Target End efector Pose: " << targetObjectPose);
    moveGroupInterface.setPoseTarget(targetObjectPose);
    moveGroupInterface.setPoseReferenceFrame("/map");
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
    ROS_INFO_NAMED("CbMoveEndEffectorRelative", "Success Visualizing plan 1 (pose goal) %s", success ? "" :
       "FAILED");
    if (success)
    {
        auto executionResult = moveGroupInterface.execute(computedMotionPlan);
        if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution succedded");
            movegroupClient_->postEventMotionExecutionSucceded
      ();
        }
        else
        {
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed(
      );
        }
    }
    else
    {
        ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
        movegroupClient_->postEventMotionExecutionFailed();
    }
}
void sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 24 of file cb_move_end_effector_relative.cpp.
References movegroupClient_, moveRelative(), smacc::SmaccClientBehavior::requiresClient(), and transform_.
{
    ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Transform end effector pose relative: " <<
      transform_);
    this->requiresClient(movegroupClient_);
    moveRelative(transform_);
}
void sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 31 of file cb_move_end_effector_relative.cpp.
{
}
Member Data Documentation
ClMoveGroup* sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::movegroupClient_ [private]
Definition at line 19 of file cb_move_end_effector_relative.h.
Referenced by moveRelative(), and onEntry().
geometry_msgs::Transform sm_moveit::cl_movegroup::CbMoveEndEffectorRelative::transform_
Definition at line 22 of file cb_move_end_effector_relative.h.
Referenced by CbMoveEndEffectorRelative(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_end_effector_relative.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_end_effector_relative.cpp