sm_moveit::cl_movegroup::CbMoveEndEffector Class Reference
#include <cb_move_end_effector.h>
Public Member Functions
CbMoveEndEffector ()
CbMoveEndEffector (geometry_msgs::PoseStamped target_pose)
virtual void onEntry () override
virtual void onExit () override
Public Attributes
geometry_msgs::PoseStamped targetPose
Private Member Functions
bool moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, moveit::planning_interface::PlanningSceneInterface &planningSceneInterface, geometry_msgs::PoseStamped &targetObjectPose)
Private Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 16 of file cb_move_end_effector.h.
Constructor & Destructor Documentation
sm_moveit::cl_movegroup::CbMoveEndEffector::CbMoveEndEffector ()
Definition at line 13 of file cb_move_end_effector.cpp.
{
}
sm_moveit::cl_movegroup::CbMoveEndEffector::CbMoveEndEffector (geometry_msgs::PoseStamped target_pose)
Definition at line 17 of file cb_move_end_effector.cpp.
    : targetPose(target_pose)
{
}
Member Function Documentation
bool sm_moveit::cl_movegroup::CbMoveEndEffector::moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, moveit::planning_interface::PlanningSceneInterface & planningSceneInterface, geometry_msgs::PoseStamped & targetObjectPose) [private]
Definition at line 36 of file cb_move_end_effector.cpp.
References movegroupClient_, sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionFailed(), and sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionSucceded().
Referenced by onEntry().
{
    moveGroupInterface.setPlanningTime(1.0);
    ROS_INFO_STREAM("[CbMoveEndEffector] Target End efector Pose: " << targetObjectPose);
    moveGroupInterface.setPoseTarget(targetObjectPose);
    moveGroupInterface.setPoseReferenceFrame("/map");
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
    ROS_INFO_NAMED("CbMoveEndEffector", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED
      ");
    if (success)
    {
        auto executionResult = moveGroupInterface.execute(computedMotionPlan);
        if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
            ROS_INFO("[CbMoveEndEffector] motion execution succedded");
            movegroupClient_->postEventMotionExecutionSucceded
      ();
        }
        else
        {
            ROS_INFO("[CbMoveEndEffector] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed(
      );
        }
    }
    else
    {
        ROS_INFO("[CbMoveEndEffector] motion execution failed");
        movegroupClient_->postEventMotionExecutionFailed();
    }
    return success;
}
void sm_moveit::cl_movegroup::CbMoveEndEffector::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 22 of file cb_move_end_effector.cpp.
References movegroupClient_, sm_moveit::cl_movegroup::ClMoveGroup::moveGroupClientInterface, moveToAbsolutePose(), sm_moveit::cl_movegroup::ClMoveGroup::planningSceneInterface, smacc::SmaccClientBehavior::requiresClient(), and targetPose.
{
    ros::WallDuration(4).sleep();
    this->requiresClient(movegroupClient_);
    this->moveToAbsolutePose(movegroupClient_->
      moveGroupClientInterface, movegroupClient_->
      planningSceneInterface, targetPose);
    ros::WallDuration(4).sleep();
}
void sm_moveit::cl_movegroup::CbMoveEndEffector::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 32 of file cb_move_end_effector.cpp.
{
}
Member Data Documentation
ClMoveGroup* sm_moveit::cl_movegroup::CbMoveEndEffector::movegroupClient_ [private]
Definition at line 20 of file cb_move_end_effector.h.
Referenced by moveToAbsolutePose(), and onEntry().
geometry_msgs::PoseStamped sm_moveit::cl_movegroup::CbMoveEndEffector::targetPose
Definition at line 23 of file cb_move_end_effector.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_end_effector.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_end_effector.cpp