move_group_interface_client::CbMoveJoints Class Reference
#include <cb_move_joints.h>
Public Member Functions
CbMoveJoints ()
CbMoveJoints (const std::map< std::string, double > &jointValueTarget)
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< double > scalingFactor_
std::map< std::string, double > jointValueTarget_
boost::optional< std::string > group_
Protected Member Functions
void moveJoints (moveit::planning_interface::MoveGroupInterface &moveGroupInterface)
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 16 of file cb_move_joints.h.
Constructor & Destructor Documentation
CbMoveJoints() [1/2]
move_group_interface_client::CbMoveJoints::CbMoveJoints ()
Definition at line 16 of file cb_move_joints.cpp.
  {
  }
CbMoveJoints() [2/2]
move_group_interface_client::CbMoveJoints::CbMoveJoints (const std::map< std::string, double > & jointValueTarget)
Definition at line 12 of file cb_move_joints.cpp.
                                                                              :
      jointValueTarget_(jointValueTarget)
  {
  }
Member Function Documentation
moveJoints()
void move_group_interface_client::CbMoveJoints::moveJoints (moveit::planning_interface::MoveGroupInterface & moveGroupInterface) [protected]
Definition at line 35 of file cb_move_joints.cpp.
References jointValueTarget_, movegroupClient_, move_group_interface_client::ClMoveGroup::postEventMotionExecutionFailed(), move_group_interface_client::ClMoveGroup::postEventMotionExecutionSucceded(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), smacc::SmaccAsyncClientBehavior::postSuccessEvent(), and scalingFactor_.
Referenced by onEntry().
  {
    if (scalingFactor_)
      moveGroupInterface.setMaxVelocityScalingFactor(*scalingFactor_);
    bool success;
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    if (jointValueTarget_.size() == 0)
    {
      ROS_WARN("[CbMoveJoints] No joint was value specified. Skipping planning call.");
      success = false;
    }
    else
    {
      moveGroupInterface.setJointValueTarget(jointValueTarget_);
      success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
      ROS_INFO_NAMED("CbMoveJoints", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
    }
    if (success)
    {
      auto executionResult = moveGroupInterface.execute(computedMotionPlan);
      if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
      {
        ROS_INFO("[CbMoveJoints] motion execution succedded. Throwing success event.");
        movegroupClient_->postEventMotionExecutionSucceded(
      );
        this->postSuccessEvent();
      }
      else
      {
        ROS_WARN("[CbMoveJoints] motion execution failed. Throwing fail event.");
        movegroupClient_->postEventMotionExecutionFailed();
        this->postFailureEvent();
      }
    }
    else
    {
      ROS_WARN("[CbMoveJoints] motion execution failed. Throwing fail event.");
      movegroupClient_->postEventMotionExecutionFailed();
      this->postFailureEvent();
    }
  }
onEntry()
void move_group_interface_client::CbMoveJoints::onEntry () [override], [virtual]
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 20 of file cb_move_joints.cpp.
References group_, movegroupClient_, move_group_interface_client::ClMoveGroup::moveGroupClientInterface, moveJoints(), and smacc::ISmaccClientBehavior::requiresClient().
  {
    this->requiresClient(movegroupClient_);
    if (this->group_)
    {
      moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
      this->moveJoints(move_group);
    }
    else
    {
      this->moveJoints(movegroupClient_->
      moveGroupClientInterface);
    }
  }
onExit()
void move_group_interface_client::CbMoveJoints::onExit () [override], [virtual]
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 80 of file cb_move_joints.cpp.
  {
  }
Member Data Documentation
group_
boost::optional<std::string> move_group_interface_client::CbMoveJoints::group_
Definition at line 21 of file cb_move_joints.h.
Referenced by onEntry().
jointValueTarget_
std::map<std::string, double> move_group_interface_client::CbMoveJoints::jointValueTarget_
Definition at line 20 of file cb_move_joints.h.
Referenced by moveJoints().
movegroupClient_
ClMoveGroup* move_group_interface_client::CbMoveJoints::movegroupClient_ [protected]
Definition at line 30 of file cb_move_joints.h.
Referenced by moveJoints(), and onEntry().
scalingFactor_
boost::optional<double> move_group_interface_client::CbMoveJoints::scalingFactor_
Definition at line 19 of file cb_move_joints.h.
Referenced by moveJoints().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_joints.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_joints.cpp