sm_moveit::cl_movegroup::CbMoveCartesianRelative Class Reference
#include <cb_move_cartesian_relative.h>
Public Member Functions
CbMoveCartesianRelative ()
CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
virtual void onEntry () override
virtual void onExit () override
void moveRelativeCartesian (geometry_msgs::Vector3 &offset)
Public Attributes
geometry_msgs::Vector3 offset_
Detailed Description
Definition at line 16 of file cb_move_cartesian_relative.h.
Constructor & Destructor Documentation
sm_moveit::cl_movegroup::CbMoveCartesianRelative::CbMoveCartesianRelative ()
Definition at line 13 of file cb_move_cartesian_relative.cpp.
{
}
sm_moveit::cl_movegroup::CbMoveCartesianRelative::CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
Definition at line 17 of file cb_move_cartesian_relative.cpp.
                                                                            :
      offset_(offset)
{
}
Member Function Documentation
void sm_moveit::cl_movegroup::CbMoveCartesianRelative::moveRelativeCartesian (geometry_msgs::Vector3 & offset)
Definition at line 31 of file cb_move_cartesian_relative.cpp.
References sm_moveit::cl_movegroup::ClMoveGroup::moveGroupClientInterface, sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionFailed(), sm_moveit::cl_movegroup::ClMoveGroup::postEventMotionExecutionSucceded(), and smacc::SmaccClientBehavior::requiresClient().
Referenced by onEntry().
{
    ClMoveGroup *movegroupClient;
    this->requiresClient(movegroupClient);
    std::vector<geometry_msgs::Pose> waypoints;
    auto referenceStartPose = movegroupClient->moveGroupClientInterface.getPoseTarget();
    //auto referenceStartPose = this->moveGroupClientInterface.getCurrentPose();
    ROS_INFO_STREAM("[CbMoveCartesianRelative] RELATIVE MOTION, SOURCE POSE: " << referenceStartPose);
    ROS_INFO_STREAM("[CbMoveCartesianRelative] Offset: " << offset);
    waypoints.push_back(referenceStartPose.pose); // up and out
    auto targetObjectPose = movegroupClient->moveGroupClientInterface.getPoseTarget();
    auto endPose = referenceStartPose.pose;
    endPose.position.x += offset.x;
    endPose.position.y += offset.y;
    endPose.position.z += offset.z;
    ROS_INFO_STREAM("[CbMoveCartesianRelative] DESTINY POSE: " << endPose);
    //target_pose2.position.x -= 0.15;
    waypoints.push_back(endPose); // left
    movegroupClient->moveGroupClientInterface.setPoseTarget(endPose);
    movegroupClient->moveGroupClientInterface.setMaxVelocityScalingFactor(0.1);
    moveit_msgs::RobotTrajectory trajectory;
    double fraction = movegroupClient->moveGroupClientInterface.computeCartesianPath(waypoints,
                                                                                     0.01, // eef_step
                                                                                     0.0, //
       jump_threshold
                                                                                     trajectory);
    if (fraction == -1)
    {
        movegroupClient->postEventMotionExecutionFailed();
        ROS_INFO("[CbMoveCartesianRelative] Absolute motion planning failed. Skipping execution.");
        return;
    }
    moveit::planning_interface::MoveGroupInterface::Plan grasp_pose_plan;
    //grasp_pose_plan.start_state_ = *(moveGroupInterface.getCurrentState());
    grasp_pose_plan.trajectory_ = trajectory;
    auto executionResult = movegroupClient->moveGroupClientInterface.execute(grasp_pose_plan);
    if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
    {
        ROS_INFO("[CbMoveCartesianRelative] relative motion execution succedded: fraction %lf", fraction);
        movegroupClient->postEventMotionExecutionSucceded();
    }
    else
    {
        ROS_INFO("[CbMoveCartesianRelative] relative motion execution failed");
        movegroupClient->postEventMotionExecutionFailed();
    }
    ROS_INFO("Visualizing plan 4 (cartesian path) (%.2f%% acheived)", fraction * 100.0);
}
void sm_moveit::cl_movegroup::CbMoveCartesianRelative::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 21 of file cb_move_cartesian_relative.cpp.
References moveRelativeCartesian(), and offset_.
{
    this->moveRelativeCartesian(offset_);
}
void sm_moveit::cl_movegroup::CbMoveCartesianRelative::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 26 of file cb_move_cartesian_relative.cpp.
{
}
Member Data Documentation
geometry_msgs::Vector3 sm_moveit::cl_movegroup::CbMoveCartesianRelative::offset_
Definition at line 19 of file cb_move_cartesian_relative.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_cartesian_relative.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_cartesian_relative.cpp