smacc::LogicUnit Class Reference
#include <logic_unit.h>
Classes
struct AddTEventType
Public Member Functions
LogicUnit ()
virtual void onInitialized ()
template<typename TEventList >
void initialize (ISmaccState *ownerState, TEventList *)
virtual void onEventNotified (const std::type_info *eventType)
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void declareInputEvent ()
template<typename TEv >
void declarePostEvent (smacc::introspection::typelist< TEv >)
Public Attributes
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Private Member Functions
template<typename TEvent >
void notifyEvent (TEvent *ev)
Private Attributes
friend ISmaccStateMachine
Detailed Description
Definition at line 23 of file logic_unit.h.
Constructor & Destructor Documentation
smacc::LogicUnit::LogicUnit ()
Definition at line 7 of file logic_unit.cpp.
{
}
Member Function Documentation
template<typename T , typename TClass > void smacc::LogicUnit::createEventCallback (void(TClass::*)(T *) callback, TClass * object)
Definition at line 35 of file smacc_logic_unit_impl.h.
References eventCallbacks_.
{
    const auto *eventtype = &typeid(T);
    this->eventCallbacks_[eventtype] = [=](void *msg) {
        T *evptr = (T *)msg;
        (object->*callback)(evptr);
    };
}
template<typename T > void smacc::LogicUnit::createEventCallback (std::function< void(T *)> callback)
Definition at line 45 of file smacc_logic_unit_impl.h.
References eventCallbacks_.
{
    const auto *eventtype = &typeid(T);
    this->eventCallbacks_[eventtype] = [=](void *msg) {
        T *evptr = (T *)msg;
        callback(evptr);
    };
}
template<typename TEv > void smacc::LogicUnit::declareInputEvent ()
Definition at line 16 of file smacc_logic_unit_impl.h.
References eventTypes.
Referenced by smacc::LogicUnit::AddTEventType< TEventList >::operator()().
{
    this->eventTypes.push_back(&typeid(TEv));
}
template<typename TEv > void smacc::LogicUnit::declarePostEvent (smacc::introspection::typelist< TEv >)
Definition at line 6 of file smacc_logic_unit_impl.h.
References smacc::ISmaccState::getStateMachine(), ownerState, smacc::ISmaccStateMachine::postEvent(), and postEventFn.
{
    this->postEventFn = [this]() {
        ROS_INFO_STREAM("[Logic Unit Base] postingfn posting event: " << demangleSymbol<TEv>());
        auto *ev = new TEv();
        this->ownerState->getStateMachine().postEvent(ev);
    };
}
template<typename TEventList > void smacc::LogicUnit::initialize (ISmaccState * ownerState, TEventList *)
Definition at line 22 of file smacc_logic_unit_impl.h.
References onInitialized(), and ownerState.
{
    this->ownerState = ownerState;
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<TEventList, _1>::type;
    AddTEventType<TEventList> op(this);
    boost::mpl::for_each<wrappedList>(op);
    this->onInitialized();
}
template<typename TEvent > void smacc::LogicUnit::notifyEvent (TEvent * ev) [inline], [private]
Definition at line 78 of file logic_unit.h.
    {
        //the state machine uses this method to notify this logic unit some event happened.
        auto tid = &(typeid(TEvent));
        if (std::find(eventTypes.begin(), eventTypes.end(), tid) !=
      eventTypes.end())
        {
            this->onEventNotified(tid);
            this->update();
            if (eventCallbacks_.count(tid))
            {
                eventCallbacks_[tid]((void *)ev);
            }
        }
    }
void smacc::LogicUnit::onEventNotified (const std::type_info * eventType) [virtual]
Reimplemented in smacc::logic_units::LuEventCountdown, and smacc::logic_units::LuAllEventsGo.
Definition at line 15 of file logic_unit.cpp.
{
}
void smacc::LogicUnit::onInitialized () [virtual]
Reimplemented in smacc::logic_units::LuEventCountdown, and smacc::logic_units::LuAllEventsGo.
Definition at line 11 of file logic_unit.cpp.
Referenced by initialize().
{
}
virtual bool smacc::LogicUnit::triggers () [pure virtual]
Implemented in smacc::logic_units::LuConditional, smacc::logic_units::LuEventCountdown, and smacc::logic_units::LuAllEventsGo.
Referenced by update().
void smacc::LogicUnit::update ()
Definition at line 19 of file logic_unit.cpp.
References postEventFn, and triggers().
{
    if (this->triggers())
    {
        ROS_INFO("Logic unit base REALLY TRIGGERS!!");
        this->postEventFn();
    }
}
Member Data Documentation
std::map<const std::type_info *, std::function<void(void *)> > smacc::LogicUnit::eventCallbacks_
Definition at line 29 of file logic_unit.h.
Referenced by createEventCallback().
std::vector<const std::type_info *> smacc::LogicUnit::eventTypes
Definition at line 28 of file logic_unit.h.
Referenced by declareInputEvent(), and smacc::logic_units::LuEventCountdown::onInitialized().
friend smacc::LogicUnit::ISmaccStateMachine [private]
Definition at line 75 of file logic_unit.h.
ISmaccState* smacc::LogicUnit::ownerState
Definition at line 26 of file logic_unit.h.
Referenced by declarePostEvent(), and initialize().
std::function<void()> smacc::LogicUnit::postEventFn
Definition at line 27 of file logic_unit.h.
Referenced by declarePostEvent(), and update().
The documentation for this class was generated from the following files:
smacc/include/smacc/logic_unit.h
smacc/include/smacc/impl/smacc_logic_unit_impl.h
smacc/src/smacc/logic_unit.cpp