cl_ros_publisher_client::CbPublishOnce< RosMsgType > Class Template Reference
#include <cb_publish_once.h>
Public Member Functions
CbPublishOnce ()
template<typename TMessage >
CbPublishOnce (const TMessage &data)
template<typename TMessage >
void setMessage (const TMessage &data)
virtual void onEntry () override
virtual void onExit () override
Private Attributes
std::function< void()> deferedPublishFn
ClRosPublisher * client_
Detailed Description
template<typename RosMsgType>
*
class cl_ros_publisher_client::CbPublishOnce< RosMsgType >
Definition at line 9 of file cb_publish_once.h.
Constructor & Destructor Documentation
template<typename RosMsgType > cl_ros_publisher_client::CbPublishOnce< RosMsgType >::CbPublishOnce () [inline]
Definition at line 16 of file cb_publish_once.h.
        : deferedPublishFn(nullptr)
    {
    }
template<typename RosMsgType > template<typename TMessage > cl_ros_publisher_client::CbPublishOnce< RosMsgType >::CbPublishOnce (const TMessage & data) [inline]
Definition at line 22 of file cb_publish_once.h.
References cl_ros_publisher_client::CbPublishOnce< RosMsgType >::setMessage().
    {
        this->setMessage(data);
    }
Member Function Documentation
template<typename RosMsgType > virtual void cl_ros_publisher_client::CbPublishOnce< RosMsgType >::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 35 of file cb_publish_once.h.
References cl_ros_publisher_client::CbPublishOnce< RosMsgType >::deferedPublishFn, and smacc::SmaccClientBehavior::requiresClient().
    {
        this->requiresClient(client_);
        if (deferedPublishFn != nullptr)
            deferedPublishFn();
    }
template<typename RosMsgType > virtual void cl_ros_publisher_client::CbPublishOnce< RosMsgType >::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 43 of file cb_publish_once.h.
    {
    }
template<typename RosMsgType > template<typename TMessage > void cl_ros_publisher_client::CbPublishOnce< RosMsgType >::setMessage (const TMessage & data) [inline]
Definition at line 28 of file cb_publish_once.h.
References cl_ros_publisher_client::ClRosPublisher::publish().
Referenced by cl_ros_publisher_client::CbPublishOnce< RosMsgType >::CbPublishOnce().
    {
        deferedPublishFn = [=]() {
            client_->publish(data);
        };
    }
Member Data Documentation
template<typename RosMsgType > ClRosPublisher* cl_ros_publisher_client::CbPublishOnce< RosMsgType >::client_ [private]
Definition at line 13 of file cb_publish_once.h.
template<typename RosMsgType > std::function<void()> cl_ros_publisher_client::CbPublishOnce< RosMsgType >::deferedPublishFn [private]
Definition at line 12 of file cb_publish_once.h.
Referenced by cl_ros_publisher_client::CbPublishOnce< RosMsgType >::onEntry().
The documentation for this class was generated from the following file:
smacc_client_library/ros_publisher_client/include/ros_publisher_client/client_behaviors/cb_publish_once.h