generate_debs Namespace Reference
Functions
def build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
def iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
def get_identified_packages (workspace_folder)
def push_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
def remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
def create_and_push_smacc_debians (osname, osversion, rosversion)
def create_and_push_smacc_viewer_debians (osname, osversion, rosversion)
Variables
string repo_owner = `pibgeus`
rospack = rospkg.RosPack()
packages = rospack.list()
packagesl = list(packages)
parser = argparse.ArgumentParser()
help
default
type
args = parser.parse_args()
string osname = `ubuntu`
osversion = args.ubuntu_version
ros_version = args.ros_version
relative_smacc_folder = args.smacc_src_folder
relative_smacc_viewer_folder = args.smacc_viewer_src_folder
workspace_folder = os.path.abspath(os.path.join(os.getcwd(), `.`))
homefolder = os.getenv(`HOME`)
packagecloud_token_filepath = os.path.join(homefolder, `.packagecloud`)
outfile = open(packagecloud_token_filepath, `w`)
smacc_debians
smacc_viewer_debians
list extra_smacc_viewer = [df for df in smacc_debians if `smacc-msgs` in df]
Function Documentation
def generate_debs.build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
Definition at line 13 of file generate_debs.py.
Referenced by iterate_debian_generation().
def build_deb_package(workspace_source_folder, package_name, packagepath, ubuntu_version,
      ros_distro, already_visited):
    print("-----------------------")
    print("Working folder: " + str(os.getcwd()))
    print("Building debian package: " + str(package_name))
    cmd = "bloom-generate rosdebian --os-name ubuntu --os-version " + \
        str(ubuntu_version) + " --ros-distro " + \
        str(ros_distro) + " " + str(packagepath)
    print(cmd)
    bloomprocess = subprocess.Popen(cmd, shell=True)
    bloomprocess.wait()
    develpackagefolder = None
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        if "package.xml" in files and package_name == root.split("/")[-1]:
            print(root)
            develpackagefolder = root
            break
    localpackagepath = develpackagefolder
    print("current directory:")
    print(os.getcwd())
    print("debian files:")
    print(os.listdir("."))
    # copy the debian folder generated by bloom inside the package
    shutil.move("debian", os.path.join(localpackagepath, "debian"))
    os.chdir(localpackagepath)
    fakerootprocess = subprocess.Popen(
        "fakeroot debian/rules binary", shell=True)
    fakerootprocess.wait()
    os.chdir(localpackagepath)
    shutil.rmtree("debian")
    shutil.rmtree("obj-x86_64-linux-gnu")
    os.chdir(workspace_source_folder)
    # improve this regex
    firstregexstr = '.*ros-' + ros_distro + '-.*\.deb'
    regexstr = '.*ros-' + ros_distro + '-' + \
        package_name.replace("_", "-")+".*\.deb"
    print("Finding deb package: " + str(regexstr))
    thisfolderfiles = []
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        thisfolderfiles = thisfolderfiles + \
            [os.path.join(root, f) for f in files]
    debianfiles = [f for f in thisfolderfiles if re.search(firstregexstr, f)]
    print ("DETECTED DEBIAN FILES:")
    print(debianfiles)
    print ("VISITED DEBIAN FILES:")
    print(already_visited)
    debianfilename = [f for f in debianfiles if re.search(
        regexstr, f) and not f in already_visited][0]
    print("Debian file found: ")
    print(debianfilename)
    installdebiantask = subprocess.Popen(
        "sudo dpkg -i " + debianfilename, shell=True)
    installdebiantask.wait()
    return debianfilename
def generate_debs.create_and_push_smacc_debians (osname, osversion, rosversion)
Definition at line 125 of file generate_debs.py.
References get_identified_packages(), iterate_debian_generation(), push_debian_files(), and remove_debian_files().
def create_and_push_smacc_debians(osname, osversion, rosversion):
    workspace_source_folder = os.path.join(
        workspace_folder, relative_smacc_folder)
    identified_install_packages = get_identified_packages(workspace_folder)
    smacc_manual_order_packages = [ # 'forward_global_planner',
        # 'backward_global_planner',
        # 'backward_local_planner',
        # 'forward_local_planner',
        'smacc_msgs',
        'smacc',
        'all_events_go',
        'conditional',
        'event_countdown',
        'keyboard_client',
        'move_base_z_client_plugin',
        'multirole_sensor_client',
        'ros_publisher_client',
        'ros_timer_client',
        'sm_dance_bot_strikes_back',
        # 'sm_dance_bot_2',
        # 'sm_viewer_sim',
        # 'sm_three_some'
    ]
    smacc_debian_files = iterate_debian_generation(
        workspace_source_folder, smacc_manual_order_packages, identified_install_packages, osversion,
      rosversion)
    create_repo_task = subprocess.Popen(
        "package_cloud repository create smacc", shell=True)
    create_repo_task.wait()
    # ----- PUSHING TO SMACC --------------
    remove_debian_files(repo_owner, "smacc", osname,
                        osversion, smacc_debian_files)
    push_debian_files(repo_owner, "smacc", osname,
                      osversion, smacc_debian_files)
    return smacc_debian_files
def generate_debs.create_and_push_smacc_viewer_debians (osname, osversion, rosversion)
Definition at line 166 of file generate_debs.py.
References get_identified_packages(), iterate_debian_generation(), push_debian_files(), and remove_debian_files().
def create_and_push_smacc_viewer_debians(osname, osversion, rosversion)
      :
    workspace_source_folder = os.path.join(
        workspace_folder, relative_smacc_viewer_folder)
    identified_install_packages = get_identified_packages(workspace_folder)
    smacc_viewer_manual_order_packages = ["smacc_viewer"]
    smacc_viewer_debian_files = iterate_debian_generation(
        workspace_source_folder, smacc_viewer_manual_order_packages, identified_install_packages, osversion
      , rosversion)
    create_repo_task = subprocess.Popen(
        "package_cloud repository create smacc_viewer", shell=True)
    create_repo_task.wait()
    # ----- PUSHING TO SMACC VIEWER--------------
    remove_debian_files(repo_owner, "smacc_viewer", osname,
                        osversion, smacc_viewer_debian_files)
    push_debian_files(repo_owner, "smacc_viewer", osname,
                      osversion, smacc_viewer_debian_files)
    return smacc_viewer_debian_files
def generate_debs.get_identified_packages (workspace_folder)
Definition at line 92 of file generate_debs.py.
Referenced by create_and_push_smacc_debians(), and create_and_push_smacc_viewer_debians().
def get_identified_packages(workspace_folder):
    identified_install_packages = {}
    exclude_with_words = ["ridgeback", "mecanum", "catkin"]
    for pname in packagesl:
        packpath = rospack.get_path(pname)
        print(pname)
        if workspace_folder in packpath:
            if any([True for excludedword in exclude_with_words if excludedword in pname]):
                continue
            identified_install_packages[pname] = packpath
    return identified_install_packages
def generate_debs.iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
Definition at line 83 of file generate_debs.py.
References build_deb_package().
Referenced by create_and_push_smacc_debians(), and create_and_push_smacc_viewer_debians().
def iterate_debian_generation(workspace_source_folder, package_names,
      identified_install_packages, osversion, rosversion):
    os.chdir(workspace_source_folder)
    debianfiles = []
    for pname in package_names:
        debianfiles.append(build_deb_package(workspace_source_folder,
                                             pname, identified_install_packages[pname], osversion,
      rosversion, debianfiles))
    return debianfiles
def generate_debs.push_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 106 of file generate_debs.py.
Referenced by create_and_push_smacc_debians(), and create_and_push_smacc_viewer_debians().
def push_debian_files(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        print("pushing debfile")
        push_debian_task = subprocess.Popen(
            "package_cloud push " + repo_owner+"/"+reponame+"/"+osname+"/" + osversion+" " + debf, shell=
      True)
        push_debian_task.wait()
def generate_debs.remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 114 of file generate_debs.py.
Referenced by create_and_push_smacc_debians(), and create_and_push_smacc_viewer_debians().
def remove_debian_files(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        shortdebfile = debf.split("/")[-1]
        print("yanking debfile")
        push_debian_task = subprocess.Popen(
            "package_cloud yank " + repo_owner+"/"+reponame+"/"+osname+"/" + osversion+" " + shortdebfile,
      shell=True)
        push_debian_task.wait()
# ------------------------ SMACC PACKAGES -----------------------
Variable Documentation
generate_debs.args = parser.parse_args()
Definition at line 222 of file generate_debs.py.
Referenced by smacc::ISmaccState.configure(), smacc::SmaccState< StiSPatternForward3, SS >.configure_orthogonal(), smacc::Orthogonal< OrService3 >.createClient(), smacc::ISmaccState.createStateReactor(), smacc::ISmaccState.getROSNode(), and smacc::SmaccState< StiSPatternForward3, SS >.static_createStateReactor().
generate_debs.default
Definition at line 209 of file generate_debs.py.
list generate_debs.extra_smacc_viewer = [df for df in smacc_debians if `smacc-msgs` in df]
Definition at line 257 of file generate_debs.py.
generate_debs.help
Definition at line 209 of file generate_debs.py.
generate_debs.homefolder = os.getenv(`HOME`)
Definition at line 241 of file generate_debs.py.
string generate_debs.osname = `ubuntu`
Definition at line 226 of file generate_debs.py.
generate_debs.osversion = args.ubuntu_version
Definition at line 227 of file generate_debs.py.
generate_debs.outfile = open(packagecloud_token_filepath, `w`)
Definition at line 244 of file generate_debs.py.
generate_debs.packagecloud_token_filepath = os.path.join(homefolder, `.packagecloud`)
Definition at line 242 of file generate_debs.py.
generate_debs.packages = rospack.list()
Definition at line 204 of file generate_debs.py.
generate_debs.packagesl = list(packages)
Definition at line 205 of file generate_debs.py.
generate_debs.parser = argparse.ArgumentParser()
Definition at line 207 of file generate_debs.py.
Referenced by cl_move_base_z::WaypointNavigator.loadWayPointsFromFile().
generate_debs.relative_smacc_folder = args.smacc_src_folder
Definition at line 234 of file generate_debs.py.
generate_debs.relative_smacc_viewer_folder = args.smacc_viewer_src_folder
Definition at line 235 of file generate_debs.py.
generate_debs.repo_owner = `pibgeus`
Definition at line 199 of file generate_debs.py.
generate_debs.ros_version = args.ros_version
Definition at line 228 of file generate_debs.py.
generate_debs.rospack = rospkg.RosPack()
Definition at line 203 of file generate_debs.py.
generate_debs.smacc_debians
Initial value:
= create_and_push_smacc_debians(
        osname, osversion, ros_version)
Definition at line 248 of file generate_debs.py.
generate_debs.smacc_viewer_debians
Initial value:
= create_and_push_smacc_viewer_debians(
        osname, osversion, ros_version)
Definition at line 250 of file generate_debs.py.
generate_debs.type
Definition at line 215 of file generate_debs.py.
Referenced by smacc::introspection.automaticTransitionTag(), smacc::introspection.automaticTransitionType(), smacc::introspection.CallOnDefinition(), smacc::introspection.EventLabel(), smacc::client_bases::SmaccActionClientBase< sm_dance_bot::LEDControlAction >.getEventLabel(), smacc::introspection.getTransitionType(), smacc::state_reactors::SrAllEventsGo.onInitialized(), smacc::state_reactors::SrEventCountdown.onInitialized(), smacc::introspection::AddSubState.operator()(), smacc::introspection::AddTransition.operator()(), smacc::introspection.processSubState(), smacc::introspection.processTransition(), smacc::introspection.processTransitions(), and smacc::introspection::WalkStatesExecutor< InitialStateType >.walkStates().
generate_debs.workspace_folder = os.path.abspath(os.path.join(os.getcwd(), `.`))
Definition at line 236 of file generate_debs.py.