cl_move_base_z::backward_local_planner Namespace Reference
Classes
class BackwardLocalPlanner
Functions
tf::Stamped< tf::Pose > optionalRobotPose (costmap_2d::Costmap2DROS *costmapRos)
Function Documentation
optionalRobotPose()
tf::Stamped<tf::Pose> cl_move_base_z::backward_local_planner::optionalRobotPose (costmap_2d::Costmap2DROS * costmapRos)
Definition at line 318 of file backward_local_planner.cpp.
Referenced by cl_move_base_z::backward_local_planner::BackwardLocalPlanner::computeVelocityCommands(), cl_move_base_z::backward_local_planner::BackwardLocalPlanner::pureSpinningCmd(), and cl_move_base_z::backward_local_planner::BackwardLocalPlanner::setPlan().
        {
            tf::Stamped<tf::Pose> tfpose;
            costmapRos->getRobotPose(tfpose);
            return tfpose;
        }