sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable Struct Reference
#include <st_bring_bottle_back_navigate_source_table.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, StPlaceBottleBack, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_bring_bottle_back_navigate_source_table.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, StPlaceBottleBack, SUCCESS> > sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable::reactions
Definition at line 16 of file st_bring_bottle_back_navigate_source_table.h.
Member Function Documentation
onExit()
void sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable::onExit () [inline]
Definition at line 37 of file st_bring_bottle_back_navigate_source_table.h.
        {
            ros::Duration(1.0).sleep();
        }
runtimeConfigure()
void sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable::runtimeConfigure () [inline]
Definition at line 24 of file st_bring_bottle_back_navigate_source_table.h.
References sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::getMainTablePose(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::nextObject(), and smacc::ISmaccClient::requiresClient().
        {
            auto *navigateGlobalPosition = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbNavigateGlobalPosition>();
            ClPerceptionSystem *perceptionSystem;
            navigateGlobalPosition->requiresClient(perceptionSystem);
            perceptionSystem->nextObject();
            auto tablePose = perceptionSystem->getMainTablePose().pose;
            tablePose.position.x -= 0.85;
            navigateGlobalPosition->setGoal(tablePose);
        }
staticConfigure()
static void sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable::staticConfigure () [inline], [static]
Definition at line 19 of file st_bring_bottle_back_navigate_source_table.h.
        {
            configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
        }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/states/st_bring_bottle_back_navigate_source_table.h