sm_mtc_picknplace::StMoveToPick Struct Reference
#include <st_move_to_pick.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, MsPickObject, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, MsPickObject, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_move_to_pick.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, MsPickObject, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, MsPickObject, SUCCESS> > sm_mtc_picknplace::StMoveToPick::reactions
Definition at line 15 of file st_move_to_pick.h.
Member Function Documentation
void sm_mtc_picknplace::StMoveToPick::onSingleBehaviorTickCallback () [inline]
Definition at line 46 of file st_move_to_pick.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_picknplace::StMoveToPick::onTimerClientTickCallback () [inline]
Definition at line 41 of file st_move_to_pick.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_picknplace::StMoveToPick::runtimeConfigure () [inline]
Definition at line 24 of file st_move_to_pick.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StMoveToPick::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StMoveToPick::onSingleBehaviorTickCallback
      , this);
    }
static void sm_mtc_picknplace::StMoveToPick::staticConfigure () [inline], [static]
Definition at line 18 of file st_move_to_pick.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_picknplace/include/sm_mtc_picknplace/states/st_move_to_pick.h