sm_moveit::StMovePregraspPose Struct Reference
#include <st_move_pregrasp_pose.h>
Public Types
typedef mpl::list< Transition< MoveitAbsouteMotionFinished< ClMoveGroup, OrArm >, StGraspRetreat > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 13 of file st_move_pregrasp_pose.h.
Member Typedef Documentation
typedef mpl::list< Transition<MoveitAbsouteMotionFinished<ClMoveGroup, OrArm>, StGraspRetreat> > sm_moveit::StMovePregraspPose::reactions
Definition at line 24 of file st_move_pregrasp_pose.h.
Member Function Documentation
void sm_moveit::StMovePregraspPose::runtimeConfigure () [inline]
Definition at line 36 of file st_move_pregrasp_pose.h.
References cl_move_base_z::Pose::get(), cl_move_base_z::Pose::getReferenceFrame(), and cl_move_base_z::Pose::waitTransformUpdate().
    {
        cl_move_base_z::Pose targetObjectPose("/cube_0", "/map");
        targetObjectPose.waitTransformUpdate();
        ROS_INFO("------- TESTING PLAN --------");
        geometry_msgs::PoseStamped pregrasPose;
        pregrasPose.header.frame_id = targetObjectPose.getReferenceFrame();
        pregrasPose.header.stamp = ros::Time::now();
        pregrasPose.pose = targetObjectPose.get();
        pregrasPose.pose.position.x -= 0;
        //pregrasPose.position.y = -pregrasPose.position.y;
        pregrasPose.pose.position.z += 0.3;
        auto cubeYawOnTable = tf::getYaw(pregrasPose.pose.orientation);
        auto degrees90 = M_PI / 2;
        while (cubeYawOnTable > degrees90)
        {
            cubeYawOnTable -= degrees90;
        }
        while (cubeYawOnTable < -degrees90)
        {
            cubeYawOnTable += degrees90;
        }
        ROS_INFO("picking yaw: %lf", cubeYawOnTable);
        auto quat = tf::createQuaternionFromRPY(0, M_PI / 2, cubeYawOnTable);
        tf::quaternionTFToMsg(quat, pregrasPose.pose.orientation);
        auto moveAbsolute = this->getOrthogonal<OrArm>()
                                    ->getClientBehavior<CbGoToCube>();
        moveAbsolute->targetPose = pregrasPose;
        
    }
static void sm_moveit::StMovePregraspPose::staticConfigure () [inline], [static]
Definition at line 27 of file st_move_pregrasp_pose.h.
    {
        configure_orthogonal<OrArm, CbGoToCube>();
        // configure_orthogonal<OrNavigation, CbNavigateBackwards>(2);
        // configure_orthogonal<OrLED, CbLEDOff>();
        // configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit/include/sm_moveit/states/st_move_pregrasp_pose.h