sm_update_loop::State2 Struct Reference
#include <st_state_2.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, State1, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
virtual void update () override
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file st_state_2.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, State1, SUCCESS> > sm_update_loop::State2::reactions
Definition at line 16 of file st_state_2.h.
Member Function Documentation
void sm_update_loop::State2::onSingleBehaviorTickCallback () [inline]
Definition at line 55 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_update_loop::State2::onTimerClientTickCallback () [inline]
Definition at line 50 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_update_loop::State2::runtimeConfigure () [inline]
Definition at line 24 of file st_state_2.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), and smacc::ISmaccState::requiresClient().
    {
        ROS_INFO("Entering State2");
        this->setUpdatePeriod(ros::Duration(1));
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&State2::onTimerClientTickCallback, this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&State2::onSingleBehaviorTickCallback,
      this);
    }
static void sm_update_loop::State2::staticConfigure () [inline], [static]
Definition at line 19 of file st_state_2.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
    }
virtual void sm_update_loop::State2::update () [inline], [override], [virtual]
Definition at line 45 of file st_state_2.h.
    {
        ROS_INFO("STATE 2 UPDATE");
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_update_loop/include/sm_update_loop/states/st_state_2.h