sm_calendar_week::StSaturday Struct Reference
#include <st_saturday.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StSunday, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StSunday, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_saturday.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StSunday, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StSunday, SUCCESS> > sm_calendar_week::StSaturday::reactions
Definition at line 14 of file st_saturday.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_calendar_week::StSaturday::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_saturday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_calendar_week::StSaturday::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_saturday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_calendar_week::StSaturday::runtimeConfigure () [inline]
Definition at line 23 of file st_saturday.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StSaturday::onTimerClientTickCallback,
      this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StSaturday::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_calendar_week::StSaturday::staticConfigure () [inline], [static]
Definition at line 17 of file st_saturday.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_calendar_week/include/sm_calendar_week/states/st_saturday.h