sm_moveit_4::pick_states::StMovePregraspPose Struct Reference
#include <st_move_pregrasp_pose.h>
Public Types
typedef mpl::list< Transition< MoveGroupMotionExecutionSucceded< ClMoveGroup, OrArm >, StGraspApproach, SUCCESS >, Transition< MoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StMovePregraspPose, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Public Attributes
ClMoveGroup * moveGroup_
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_move_pregrasp_pose.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<MoveGroupMotionExecutionSucceded<ClMoveGroup, OrArm>, StGraspApproach, SUCCESS>, Transition<MoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StMovePregraspPose, ABORT> > sm_moveit_4::pick_states::StMovePregraspPose::reactions
Definition at line 17 of file st_move_pregrasp_pose.h.
Member Function Documentation
onExit()
void sm_moveit_4::pick_states::StMovePregraspPose::onExit () [inline]
Definition at line 53 of file st_move_pregrasp_pose.h.
References smacc::ISmaccClient::getComponent().
            {
                moveGroup_->getComponent<CpConstraintTableWorkspaces>()->
      setSmallTableCollisionVolume();
            }
runtimeConfigure()
void sm_moveit_4::pick_states::StMovePregraspPose::runtimeConfigure () [inline]
Definition at line 28 of file st_move_pregrasp_pose.h.
References sm_moveit_4::cl_perception_system::ClPerceptionSystem::computePregraspPoseFromCubePose(), sm_moveit_4::cl_perception_system::ClPerceptionSystem::decidePickCubePose(), smacc::ISmaccClient::getComponent(), and smacc::ISmaccState::requiresClient().
            {
                ROS_INFO("Pre grasp pose initialization.");
                ros::WallDuration(1).sleep();
                // --------------------------------------
                this->requiresClient(moveGroup_);
                
                ClPerceptionSystem *perceptionSystem;
                this->requiresClient(perceptionSystem);
                auto cbMoveEndEffector = this->getOrthogonal<OrArm>()->getClientBehavior<CbMoveEndEffector>
      ();
                // --------------------------------------
                moveGroup_->getComponent<CpConstraintTableWorkspaces>()->
      setBigTableCollisionVolume();
                geometry_msgs::PoseStamped targetCubePose;
                if (perceptionSystem->decidePickCubePose(targetCubePose))
                {
                    geometry_msgs::PoseStamped pregraspPose = targetCubePose;
                    perceptionSystem->computePregraspPoseFromCubePose(pregraspPose);
                    cbMoveEndEffector->targetPose = pregraspPose;
                }
            }
staticConfigure()
static void sm_moveit_4::pick_states::StMovePregraspPose::staticConfigure () [inline], [static]
Definition at line 23 of file st_move_pregrasp_pose.h.
            {
                configure_orthogonal<OrArm, CbMoveEndEffector>();
            }
Member Data Documentation
moveGroup_
ClMoveGroup* sm_moveit_4::pick_states::StMovePregraspPose::moveGroup_
Definition at line 20 of file st_move_pregrasp_pose.h.
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_4/include/sm_moveit_4/states/pick_states/st_move_pregrasp_pose.h