sm_starcraft_ai::StState2 Struct Reference
#include <st_state_2.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StState3, TIMEOUT >, Transition< EvAllGo< SrAllEventsGo >, StState3 >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StState1, PREVIOUS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StState3, NEXT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_state_2.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StState3, TIMEOUT>, Transition<EvAllGo<SrAllEventsGo>, StState3>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StState1, PREVIOUS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StState3, NEXT> > sm_starcraft_ai::StState2::reactions
Definition at line 22 of file st_state_2.h.
Member Function Documentation
void sm_starcraft_ai::StState2::onEntry () [inline]
Definition at line 57 of file st_state_2.h.
    {
        ROS_INFO("On Entry!");
    }
void sm_starcraft_ai::StState2::onExit () [inline]
Definition at line 62 of file st_state_2.h.
    {
        ROS_INFO("On Exit!");
    }
void sm_starcraft_ai::StState2::onSingleBehaviorTickCallback () [inline]
Definition at line 72 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_starcraft_ai::StState2::onTimerClientTickCallback () [inline]
Definition at line 67 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_starcraft_ai::StState2::runtimeConfigure () [inline]
Definition at line 40 of file st_state_2.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StState2::onTimerClientTickCallback, this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StState2::onSingleBehaviorTickCallback
      , this);
    }
static void sm_starcraft_ai::StState2::staticConfigure () [inline], [static]
Definition at line 25 of file st_state_2.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
        // Create State Reactor
        auto sbAll = static_createStateReactor<SrAllEventsGo>();
        sbAll->addInputEvent<EvKeyPressA<CbDefaultKeyboardBehavior, OrKeyboard>>();
        sbAll->addInputEvent<EvKeyPressB<CbDefaultKeyboardBehavior, OrKeyboard>>();
        sbAll->addInputEvent<EvKeyPressC<CbDefaultKeyboardBehavior, OrKeyboard>>();
        sbAll->setOutputEvent<EvAllGo<SrAllEventsGo>>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_starcraft_ai/include/sm_starcraft_ai/states/st_state_2.h