sm_mtc_picknplace::StGeneratePlacePose Struct Reference
#include <st_generate_place_pose.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StPlacePoseIK, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StPlacePoseIK, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_generate_place_pose.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StPlacePoseIK, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StPlacePoseIK, SUCCESS> > sm_mtc_picknplace::StGeneratePlacePose::reactions
Definition at line 14 of file st_generate_place_pose.h.
Member Function Documentation
void sm_mtc_picknplace::StGeneratePlacePose::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_generate_place_pose.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_picknplace::StGeneratePlacePose::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_generate_place_pose.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_picknplace::StGeneratePlacePose::runtimeConfigure () [inline]
Definition at line 23 of file st_generate_place_pose.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StGeneratePlacePose::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StGeneratePlacePose::onSingleBehaviorTickCallback
      , this);
    }
static void sm_mtc_picknplace::StGeneratePlacePose::staticConfigure () [inline], [static]
Definition at line 17 of file st_generate_place_pose.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_picknplace/include/sm_mtc_picknplace/states/ms_place_object_states/st_generate_place_pose.h