sm_atomic_cb::State2 Struct Reference
#include <st_state_2.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, State1, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file st_state_2.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, State1, SUCCESS> > sm_atomic_cb::State2::reactions
Definition at line 15 of file st_state_2.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_atomic_cb::State2::onSingleBehaviorTickCallback () [inline]
Definition at line 48 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_atomic_cb::State2::onTimerClientTickCallback () [inline]
Definition at line 43 of file st_state_2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_atomic_cb::State2::runtimeConfigure () [inline]
Definition at line 24 of file st_state_2.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), and smacc::ISmaccState::requiresClient().
    {
        ROS_INFO("Entering State2");
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&State2::onTimerClientTickCallback, this);
         // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&State2::onSingleBehaviorTickCallback,
      this);
    }
staticConfigure()
static void sm_atomic_cb::State2::staticConfigure () [inline], [static]
Definition at line 19 of file st_state_2.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_atomic_cb/include/sm_atomic_cb/states/st_state_2.h