sm_moveit_4::pick_states::StCloseGripper Struct Reference
#include <st_close_gripper.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClGripper, OrGripper >, StGraspRetreat > > reactions
Public Member Functions
void onEntry ()
void onExit ()
void createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject &collision, const ros::Time &time, int addOrRemove)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_close_gripper.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClGripper, OrGripper>, StGraspRetreat> > sm_moveit_4::pick_states::StCloseGripper::reactions
Definition at line 15 of file st_close_gripper.h.
Member Function Documentation
createCollisionBox()
void sm_moveit_4::pick_states::StCloseGripper::createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject & collision, const ros::Time & time, int addOrRemove) [inline]
Definition at line 58 of file st_close_gripper.h.
Referenced by onExit().
         {
            collision.operation = addOrRemove;
            collision.id = id;
            collision.primitives.resize(1);
            collision.primitives[0].type = collision.primitives[0].BOX;
            collision.primitives[0].dimensions.resize(3);
            collision.primitives[0].dimensions[0] = xl;
            collision.primitives[0].dimensions[1] = yl;
            collision.primitives[0].dimensions[2] = zl;
            collision.primitive_poses.resize(1);
            collision.primitive_poses[0].position.x = x;
            collision.primitive_poses[0].position.y = y;
            collision.primitive_poses[0].position.z = z;
            collision.primitive_poses[0].orientation.w = 1.0;
            collision.header.frame_id = frameid;
            collision.header.stamp = time;
         }
onEntry()
void sm_moveit_4::pick_states::StCloseGripper::onEntry () [inline]
Definition at line 23 of file st_close_gripper.h.
         {
            ros::Duration(1.0).sleep();
         }
onExit()
void sm_moveit_4::pick_states::StCloseGripper::onExit () [inline]
Definition at line 28 of file st_close_gripper.h.
References createCollisionBox(), smacc::ISmaccClient::getComponent(), moveit_z_client::ClMoveGroup::moveGroupClientInterface, moveit_z_client::ClMoveGroup::planningSceneInterface, and smacc::ISmaccState::requiresClient().
         {
            ClMoveGroup *moveGroupClient;
            this->requiresClient(moveGroupClient);
            ClPerceptionSystem *perceptionSystem;
            this->requiresClient(perceptionSystem);
            auto &planningSceneInterface = moveGroupClient->planningSceneInterface;
            auto cubeinfo = perceptionSystem->getTargetCurrentCubeInfo();
            auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
            //std::vector<moveit_msgs::CollisionObject> collisionObjects;
            moveit_msgs::CollisionObject cubeCollision;
            auto time = ros::Time::now();
            createCollisionBox(cubepos.pose.position.x, cubepos.pose.position.y, cubepos.
      pose.position.z, 0.06, 0.06, 0.06, "collisioncube", "map", cubeCollision, time,
      moveit_msgs::CollisionObject::ADD);
            planningSceneInterface.applyCollisionObject(cubeCollision);
            // collisionObjects.push_back(cubeCollision);
            
            std::vector<std::string> touch_links{"l_gripper_finger_link", "r_gripper_finger_link"};
            moveGroupClient->moveGroupClientInterface.attachObject("collisioncube", "gripper_link",
      touch_links);
            //moveGroupClient->moveGroupClientInterface.setSupportSurfaceName("table_1");
            
            moveGroupClient->getComponent<CpConstraintTableWorkspaces>()->disableTableCollisionVolume();
            ros::Duration(1.0).sleep();
         }
staticConfigure()
static void sm_moveit_4::pick_states::StCloseGripper::staticConfigure () [inline], [static]
Definition at line 18 of file st_close_gripper.h.
         {
            configure_orthogonal<OrGripper, CbCloseGripper>();
         }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_4/include/sm_moveit_4/states/pick_states/st_close_gripper.h