sm_moveit::pick_states::StGraspRetreat Struct Reference
#include <st_grasp_retreat.h>
Public Types
typedef mpl::list< > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_grasp_retreat.h.
Member Typedef Documentation
typedef mpl::list< > sm_moveit::pick_states::StGraspRetreat::reactions
Definition at line 16 of file st_grasp_retreat.h.
Member Function Documentation
void sm_moveit::pick_states::StGraspRetreat::runtimeConfigure () [inline]
Definition at line 26 of file st_grasp_retreat.h.
References sm_moveit::cl_movegroup::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StGraspRetreat, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup* moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StGraspRetreat::throwSequenceFinishedEvent, this);
    }
static void sm_moveit::pick_states::StGraspRetreat::staticConfigure () [inline], [static]
Definition at line 19 of file st_grasp_retreat.h.
    {
        geometry_msgs::Vector3 offset;
        offset.z = 0.12;
        configure_orthogonal<OrArm, CbMoveCartesianRelative>(offset);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit/include/sm_moveit/states/pick_states/st_grasp_retreat.h