sm_mtc_pour::StAllowGripperObjectCollision2 Struct Reference
#include <st_allow_gripper_object_collision2.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StDetachObject, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StDetachObject, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_allow_gripper_object_collision2.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StDetachObject, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StDetachObject, SUCCESS> > sm_mtc_pour::StAllowGripperObjectCollision2::reactions
Definition at line 14 of file st_allow_gripper_object_collision2.h.
Member Function Documentation
void sm_mtc_pour::StAllowGripperObjectCollision2::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_allow_gripper_object_collision2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_pour::StAllowGripperObjectCollision2::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_allow_gripper_object_collision2.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_pour::StAllowGripperObjectCollision2::runtimeConfigure () [inline]
Definition at line 23 of file st_allow_gripper_object_collision2.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&
      StAllowGripperObjectCollision2::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StAllowGripperObjectCollision2::onSingleBehaviorTickCallback
      , this);
    }
static void sm_mtc_pour::StAllowGripperObjectCollision2::staticConfigure () [inline], [static]
Definition at line 17 of file st_allow_gripper_object_collision2.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_pour/include/sm_mtc_pour/states/ms_place_bottle_states/st_allow_gripper_object_collision2.h