sm_pr2_plugs::StGetOutletLocations Struct Reference
#include <st_get_outlet_locations.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, MsWeekend, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, MsWeekend, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file st_get_outlet_locations.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, MsWeekend, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, MsWeekend, SUCCESS> > sm_pr2_plugs::StGetOutletLocations::reactions
Definition at line 13 of file st_get_outlet_locations.h.
Member Function Documentation
void sm_pr2_plugs::StGetOutletLocations::onSingleBehaviorTickCallback () [inline]
Definition at line 44 of file st_get_outlet_locations.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_pr2_plugs::StGetOutletLocations::onTimerClientTickCallback () [inline]
Definition at line 39 of file st_get_outlet_locations.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_pr2_plugs::StGetOutletLocations::runtimeConfigure () [inline]
Definition at line 22 of file st_get_outlet_locations.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StGetOutletLocations::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StGetOutletLocations::onSingleBehaviorTickCallback, this)
      ;
    }
static void sm_pr2_plugs::StGetOutletLocations::staticConfigure () [inline], [static]
Definition at line 16 of file st_get_outlet_locations.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_get_outlet_locations.h