sm_three_some::ss1_states::Ssr1 Struct Reference
#include <ssr_1.h>
Public Types
typedef smacc::Transition< EvLoopContinue< Ssr1 >, Ssr2, CONTINUELOOP > reactions
Public Member Functions
void onInitialize ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file ssr_1.h.
Member Typedef Documentation
typedef smacc::Transition<EvLoopContinue<Ssr1>, Ssr2, CONTINUELOOP> sm_three_some::ss1_states::Ssr1::reactions
Definition at line 10 of file ssr_1.h.
Member Function Documentation
bool sm_three_some::ss1_states::Ssr1::loopWhileCondition () [inline]
Definition at line 22 of file ssr_1.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void sm_three_some::ss1_states::Ssr1::onDefinition () [inline], [static]
Definition at line 13 of file ssr_1.h.
  {
  }
void sm_three_some::ss1_states::Ssr1::onEntry () [inline]
Definition at line 30 of file ssr_1.h.
References smacc::SmaccState< Ssr1, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      Ssr1::loopWhileCondition);
  }
void sm_three_some::ss1_states::Ssr1::onInitialize () [inline]
Definition at line 18 of file ssr_1.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/states/ss_superstate_1/ssr_1.h