sm_mtc_pour::StMoveToPreGraspPose Struct Reference
#include <st_move_to_pre_grasp_pose.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StApproachObject, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StApproachObject, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_move_to_pre_grasp_pose.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StApproachObject, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StApproachObject, SUCCESS> > sm_mtc_pour::StMoveToPreGraspPose::reactions
Definition at line 15 of file st_move_to_pre_grasp_pose.h.
Member Function Documentation
void sm_mtc_pour::StMoveToPreGraspPose::onSingleBehaviorTickCallback () [inline]
Definition at line 46 of file st_move_to_pre_grasp_pose.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_pour::StMoveToPreGraspPose::onTimerClientTickCallback () [inline]
Definition at line 41 of file st_move_to_pre_grasp_pose.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_pour::StMoveToPreGraspPose::runtimeConfigure () [inline]
Definition at line 24 of file st_move_to_pre_grasp_pose.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StMoveToPreGraspPose::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StMoveToPreGraspPose::onSingleBehaviorTickCallback, this)
      ;
    }
static void sm_mtc_pour::StMoveToPreGraspPose::staticConfigure () [inline], [static]
Definition at line 18 of file st_move_to_pre_grasp_pose.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_pour/include/sm_mtc_pour/states/st_move_to_pre_grasp_pose.h