sm_calendar_week::StWednesday Struct Reference
#include <st_wednesday.h>
Classes
struct RESET
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StThursday, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StThursday, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_wednesday.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StThursday, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StThursday, SUCCESS> > sm_calendar_week::StWednesday::reactions
Definition at line 17 of file st_wednesday.h.
Member Function Documentation
void sm_calendar_week::StWednesday::onSingleBehaviorTickCallback () [inline]
Definition at line 48 of file st_wednesday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_calendar_week::StWednesday::onTimerClientTickCallback () [inline]
Definition at line 43 of file st_wednesday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_calendar_week::StWednesday::runtimeConfigure () [inline]
Definition at line 26 of file st_wednesday.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StWednesday::onTimerClientTickCallback,
      this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StWednesday::onSingleBehaviorTickCallback
      , this);
    }
static void sm_calendar_week::StWednesday::staticConfigure () [inline], [static]
Definition at line 20 of file st_wednesday.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_calendar_week/include/sm_calendar_week/states/st_wednesday.h