sm_update_loop::State1 Struct Reference
#include <st_state_1.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, State2, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
virtual void update () override
void onTimerClientTickCallback ()
void onRepeatBehaviorTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 9 of file st_state_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, State2, SUCCESS> > sm_update_loop::State1::reactions
Definition at line 18 of file st_state_1.h.
Member Function Documentation
onRepeatBehaviorTickCallback()
void sm_update_loop::State1::onRepeatBehaviorTickCallback () [inline]
Definition at line 61 of file st_state_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("repeat behavior tick!");
    }
onSingleBehaviorTickCallback()
void sm_update_loop::State1::onSingleBehaviorTickCallback () [inline]
Definition at line 66 of file st_state_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_update_loop::State1::onTimerClientTickCallback () [inline]
Definition at line 56 of file st_state_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_update_loop::State1::runtimeConfigure () [inline]
Definition at line 27 of file st_state_1.h.
References onRepeatBehaviorTickCallback(), onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and cl_ros_timer::ClRosTimer::onTimerTick().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&State1::onTimerClientTickCallback,
       this);
        // getting reference to the repeat countdown behavior
        auto *cbrepeat = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownLoop>();
        // subscribe to the repeat countdown behavior callback
        cbrepeat->onTimerTick(&State1::onRepeatBehaviorTickCallback,
      this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&State1::onSingleBehaviorTickCallback,
      this);
    }
staticConfigure()
static void sm_update_loop::State1::staticConfigure () [inline], [static]
Definition at line 21 of file st_state_1.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownLoop>(3); // EvTimer triggers each 3 client ticks
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
    }
update()
virtual void sm_update_loop::State1::update () [inline], [override], [virtual]
Definition at line 51 of file st_state_1.h.
    {
        ROS_INFO("STATE 1 UPDATE!");
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_update_loop/include/sm_update_loop/states/st_state_1.h