sm_dance_bot::s_pattern_states::SsrSPatternLoopStart Struct Reference
#include <ssr_spattern_loop_start.h>
Public Types
typedef mpl::list< smacc::Transition< EvLoopContinue< SsrSPatternLoopStart >, SsrSPatternRotate1, CONTINUELOOP > > reactions
Public Member Functions
void onInitialize ()
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file ssr_spattern_loop_start.h.
Member Typedef Documentation
typedef mpl::list<smacc::Transition<EvLoopContinue<SsrSPatternLoopStart>, SsrSPatternRotate1, CONTINUELOOP> > sm_dance_bot::s_pattern_states::SsrSPatternLoopStart::reactions
Definition at line 8 of file ssr_spattern_loop_start.h.
Member Function Documentation
bool sm_dance_bot::s_pattern_states::SsrSPatternLoopStart::loopCondition () [inline]
Definition at line 18 of file ssr_spattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void sm_dance_bot::s_pattern_states::SsrSPatternLoopStart::onDefinition () [inline], [static]
Definition at line 10 of file ssr_spattern_loop_start.h.
  {
  }
void sm_dance_bot::s_pattern_states::SsrSPatternLoopStart::onEntry () [inline]
Definition at line 24 of file ssr_spattern_loop_start.h.
References smacc::SmaccState< SsrSPatternLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopCondition().
  {
    checkWhileLoopConditionAndThrowEvent(&
      SsrSPatternLoopStart::loopCondition);
  }
void sm_dance_bot::s_pattern_states::SsrSPatternLoopStart::onInitialize () [inline]
Definition at line 14 of file ssr_spattern_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/states/s_pattern_states/ssr_spattern_loop_start.h