sm_mtc_picknplace::StRetreatAfterPlace Struct Reference
#include <st_retreat_after_place.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StMoveToHome, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StMoveToHome, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_retreat_after_place.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StMoveToHome, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StMoveToHome, SUCCESS> > sm_mtc_picknplace::StRetreatAfterPlace::reactions
Definition at line 14 of file st_retreat_after_place.h.
Member Function Documentation
void sm_mtc_picknplace::StRetreatAfterPlace::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_retreat_after_place.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_picknplace::StRetreatAfterPlace::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_retreat_after_place.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_picknplace::StRetreatAfterPlace::runtimeConfigure () [inline]
Definition at line 23 of file st_retreat_after_place.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StRetreatAfterPlace::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StRetreatAfterPlace::onSingleBehaviorTickCallback
      , this);
    }
static void sm_mtc_picknplace::StRetreatAfterPlace::staticConfigure () [inline], [static]
Definition at line 17 of file st_retreat_after_place.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_picknplace/include/sm_mtc_picknplace/states/ms_place_object_states/st_retreat_after_place.h