sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject Struct Reference
#include <ss_pick_object.h>
Public Types
typedef mpl::list< Transition< EvSequenceFinished< SS1::StNavigationPosture >, StRotate180, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onMoveitError ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 24 of file ss_pick_object.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvSequenceFinished<SS1::StNavigationPosture>, StRotate180, SUCCESS> > sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::reactions
Definition at line 33 of file ss_pick_object.h.
Member Function Documentation
onMoveitError()
void sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::onMoveitError () [inline]
Definition at line 50 of file ss_pick_object.h.
Referenced by runtimeConfigure().
    {
        ROS_ERROR("Moveit motion failed, retrying");
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        perceptionSystem->retryCubeAfterFail();
    }
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::runtimeConfigure () [inline]
Definition at line 41 of file ss_pick_object.h.
References move_group_interface_client::ClMoveGroup::onMotionExecutionFailed(), and onMoveitError().
    {
        ROS_INFO("picking object superstate");
        ClMoveGroup *movegroupClient;
        this->requiresClient(movegroupClient);
        movegroupClient->onMotionExecutionFailed(&SsPickObject::onMoveitError,
      this);
    }
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::staticConfigure () [inline], [static]
Definition at line 36 of file ss_pick_object.h.
    {
        //configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/superstates/ss_pick_object.h