sm_packML::ss2_states::StiState4 Struct Reference
#include <sti_state_4.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiState4 >, StiState5, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_state_4.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvLoopContinue<StiState4>, StiState5, CONTINUELOOP> > sm_packML::ss2_states::StiState4::reactions
Definition at line 16 of file sti_state_4.h.
Member Function Documentation
bool sm_packML::ss2_states::StiState4::loopWhileCondition () [inline]
Definition at line 27 of file sti_state_4.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
void sm_packML::ss2_states::StiState4::onEntry () [inline]
Definition at line 35 of file sti_state_4.h.
References smacc::SmaccState< StiState4, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      StiState4::loopWhileCondition);
  }
void sm_packML::ss2_states::StiState4::runtimeConfigure () [inline]
Definition at line 23 of file sti_state_4.h.
  {
  }
static void sm_packML::ss2_states::StiState4::staticConfigure () [inline], [static]
Definition at line 19 of file sti_state_4.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_packML/include/sm_packML/states/ss_superstate_2/sti_state_4.h