sm_respira_1::StCalibrationStep1 Struct Reference
#include <st_calibration_step_1.h>
Public Types
typedef mpl::list< Transition< EvKeyPressL< CbDefaultKeyboardBehavior, OrKeyboard >, StObserve, PREEMPT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_calibration_step_1.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressL<CbDefaultKeyboardBehavior, OrKeyboard>, StObserve, PREEMPT> > sm_respira_1::StCalibrationStep1::reactions
Definition at line 16 of file st_calibration_step_1.h.
Member Function Documentation
void sm_respira_1::StCalibrationStep1::onEntry () [inline]
Definition at line 44 of file st_calibration_step_1.h.
    {
        ROS_INFO("On Entry!");
    }
void sm_respira_1::StCalibrationStep1::onExit () [inline]
Definition at line 49 of file st_calibration_step_1.h.
    {
        ROS_INFO("On Exit!");
    }
void sm_respira_1::StCalibrationStep1::onSingleBehaviorTickCallback () [inline]
Definition at line 59 of file st_calibration_step_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_respira_1::StCalibrationStep1::onTimerClientTickCallback () [inline]
Definition at line 54 of file st_calibration_step_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_respira_1::StCalibrationStep1::runtimeConfigure () [inline]
Definition at line 27 of file st_calibration_step_1.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StCalibrationStep1::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StCalibrationStep1::onSingleBehaviorTickCallback
      , this);
    }
static void sm_respira_1::StCalibrationStep1::staticConfigure () [inline], [static]
Definition at line 19 of file st_calibration_step_1.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/st_calibration_step_1.h