sm_three_some::ss1_states::StiState1 Struct Reference
#include <sti_state_1.h>
Public Types
typedef Transition< EvLoopContinue< StiState1 >, StiState2, CONTINUELOOP > reactions
Public Member Functions
void onInitialize ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file sti_state_1.h.
Member Typedef Documentation
typedef Transition<EvLoopContinue<StiState1>, StiState2, CONTINUELOOP> sm_three_some::ss1_states::StiState1::reactions
Definition at line 10 of file sti_state_1.h.
Member Function Documentation
bool sm_three_some::ss1_states::StiState1::loopWhileCondition () [inline]
Definition at line 22 of file sti_state_1.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void sm_three_some::ss1_states::StiState1::onDefinition () [inline], [static]
Definition at line 13 of file sti_state_1.h.
  {
  }
void sm_three_some::ss1_states::StiState1::onEntry () [inline]
Definition at line 30 of file sti_state_1.h.
References smacc::SmaccState< StiState1, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      StiState1::loopWhileCondition);
  }
void sm_three_some::ss1_states::StiState1::onInitialize () [inline]
Definition at line 18 of file sti_state_1.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/states/ss_superstate_1/sti_state_1.h