sm_ridgeback_floor_coverage_static_1::StNavigateForward1 Struct Reference
#include <st_navigate_forward_1.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbNavigateForward, OrNavigation >, StRotateDegrees2 >, Transition< EvCbFailure< CbNavigateForward, OrNavigation >, StNavigateToWaypointsX, ABORT >, Transition< EvActionPreempted< CbNavigateForward, OrNavigation >, StNavigateToWaypointsX, PREEMPT > > reactions
Public Member Functions
void runtimeConfigure ()
void onActionClientSucceeded (ClMoveBaseZ::ResultConstPtr &msg)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_navigate_forward_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbNavigateForward, OrNavigation>, StRotateDegrees2>, Transition<EvCbFailure<CbNavigateForward, OrNavigation>, StNavigateToWaypointsX, ABORT>, Transition<EvActionPreempted<CbNavigateForward, OrNavigation>, StNavigateToWaypointsX, PREEMPT> > sm_ridgeback_floor_coverage_static_1::StNavigateForward1::reactions
Definition at line 17 of file st_navigate_forward_1.h.
Member Function Documentation
onActionClientSucceeded()
void sm_ridgeback_floor_coverage_static_1::StNavigateForward1::onActionClientSucceeded (ClMoveBaseZ::ResultConstPtr & msg) [inline]
Definition at line 36 of file st_navigate_forward_1.h.
Referenced by runtimeConfigure().
    {
      ROS_INFO_STREAM(" [Callback SmaccSignal] Success Detected from StAquireSensors (connected to client
       signal), result data: " << *msg);
    }
runtimeConfigure()
void sm_ridgeback_floor_coverage_static_1::StNavigateForward1::runtimeConfigure () [inline]
Definition at line 27 of file st_navigate_forward_1.h.
References onActionClientSucceeded(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and smacc::ISmaccState::requiresClient().
    {
      ClMoveBaseZ *move_base_action_client;
      this->requiresClient(move_base_action_client);
      // we careful with the lifetime of the callbac, us a scoped connection if is not forever
      move_base_action_client->onSucceeded(&
      StNavigateForward1::onActionClientSucceeded, this);
    }
staticConfigure()
static void sm_ridgeback_floor_coverage_static_1::StNavigateForward1::staticConfigure () [inline], [static]
Definition at line 20 of file st_navigate_forward_1.h.
    {
      configure_orthogonal<OrNavigation, CbNavigateForward>(1);
      configure_orthogonal<OrLED, CbLEDOff>();
      configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_ridgeback_floor_coverage_static_1/include/sm_ridgeback_floor_coverage_static_1/states/ms_dance_bot_run_mode/st_navigate_forward_1.h