sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart Struct Reference
#include <sti_spattern_loop_start.h>
Public Types
typedef mpl::list< smacc::Transition< EvLoopContinue< StiSPatternLoopStart >, StiSPatternRotate1, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file sti_spattern_loop_start.h.
Member Typedef Documentation
typedef mpl::list<smacc::Transition<EvLoopContinue<StiSPatternLoopStart>, StiSPatternRotate1, CONTINUELOOP> > sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart::reactions
Definition at line 8 of file sti_spattern_loop_start.h.
Member Function Documentation
bool sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart::loopCondition () [inline]
Definition at line 18 of file sti_spattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    return superstate.iteration_count++ < superstate.total_iterations();
  }
void sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart::onEntry () [inline]
Definition at line 24 of file sti_spattern_loop_start.h.
References smacc::SmaccState< StiSPatternLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopCondition().
  {
    checkWhileLoopConditionAndThrowEvent(&
      StiSPatternLoopStart::loopCondition);
  }
void sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart::runtimeConfigure () [inline]
Definition at line 14 of file sti_spattern_loop_start.h.
  {
  }
static void sm_dance_bot_3::s_pattern_states::StiSPatternLoopStart::staticConfigure () [inline], [static]
Definition at line 10 of file sti_spattern_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_3/include/sm_dance_bot_3/states/s_pattern_states/sti_spattern_loop_start.h