sm_fetch_two_table_whiskey_pour::StNavigateToDestinyTable Struct Reference
#include <st_navigate_to_destiny_table.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, StDecideDestinyTableAction, SUCCESS >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StNavigateToDestinyTable, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_navigate_to_destiny_table.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, StDecideDestinyTableAction , SUCCESS>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StNavigateToDestinyTable, ABORT> > sm_fetch_two_table_whiskey_pour::StNavigateToDestinyTable::reactions
Definition at line 18 of file st_navigate_to_destiny_table.h.
Member Function Documentation
runtimeConfigure()
void sm_fetch_two_table_whiskey_pour::StNavigateToDestinyTable::runtimeConfigure () [inline]
Definition at line 26 of file st_navigate_to_destiny_table.h.
References sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::decidePickCubePose(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::getTargetTablePose(), and smacc::ISmaccClient::requiresClient().
        {
            auto navigateGlobalPosition = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbNavigateGlobalPosition>();
            ClPerceptionSystem *perceptionSystem;
            navigateGlobalPosition->requiresClient(perceptionSystem);
            geometry_msgs::PoseStamped nextCubePose;
            perceptionSystem->decidePickCubePose(nextCubePose);
            auto targetTablePose = perceptionSystem->getTargetTablePose().pose;
            if (targetTablePose.position.x > 0)
            {
                targetTablePose.position.x -= 0.85;
            }
            else
            {
                targetTablePose.position.x += 0.85;
                auto quat = tf::createQuaternionFromYaw(M_PI);
                tf::quaternionTFToMsg(quat, targetTablePose.orientation);
            }
            navigateGlobalPosition->setGoal(targetTablePose);
        }
staticConfigure()
static void sm_fetch_two_table_whiskey_pour::StNavigateToDestinyTable::staticConfigure () [inline], [static]
Definition at line 21 of file st_navigate_to_destiny_table.h.
        {
            configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
        }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/states/st_navigate_to_destiny_table.h