sm_pr2_plugs::StNavigateToOutlet Struct Reference
#include <st_navigate_to_outlet.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StUnplug, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StUnplug, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_navigate_to_outlet.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StUnplug, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StUnplug, SUCCESS> > sm_pr2_plugs::StNavigateToOutlet::reactions
Definition at line 14 of file st_navigate_to_outlet.h.
Member Function Documentation
void sm_pr2_plugs::StNavigateToOutlet::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_navigate_to_outlet.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_pr2_plugs::StNavigateToOutlet::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_navigate_to_outlet.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_pr2_plugs::StNavigateToOutlet::runtimeConfigure () [inline]
Definition at line 23 of file st_navigate_to_outlet.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StNavigateToOutlet::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StNavigateToOutlet::onSingleBehaviorTickCallback
      , this);
    }
static void sm_pr2_plugs::StNavigateToOutlet::staticConfigure () [inline], [static]
Definition at line 17 of file st_navigate_to_outlet.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_navigate_to_outlet.h