sm_pr2_plugs::StClearLeftArm Struct Reference
#include <st_clear_left_arm.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StWiggleOut, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file st_clear_left_arm.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StWiggleOut, SUCCESS> > sm_pr2_plugs::StClearLeftArm::reactions
Definition at line 13 of file st_clear_left_arm.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_pr2_plugs::StClearLeftArm::onSingleBehaviorTickCallback () [inline]
Definition at line 44 of file st_clear_left_arm.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_pr2_plugs::StClearLeftArm::onTimerClientTickCallback () [inline]
Definition at line 39 of file st_clear_left_arm.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_pr2_plugs::StClearLeftArm::runtimeConfigure () [inline]
Definition at line 22 of file st_clear_left_arm.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StClearLeftArm::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StClearLeftArm::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_pr2_plugs::StClearLeftArm::staticConfigure () [inline], [static]
Definition at line 16 of file st_clear_left_arm.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_clear_left_arm.h