sm_mtc_picknplace::StEntryState Struct Reference
#include <st_entry_state.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StOpenHand, SUCCESS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StOpenHand, PREEMPT > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_entry_state.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StOpenHand, SUCCESS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StOpenHand, PREEMPT> > sm_mtc_picknplace::StEntryState::reactions
Definition at line 15 of file st_entry_state.h.
Member Function Documentation
void sm_mtc_picknplace::StEntryState::onSingleBehaviorTickCallback () [inline]
Definition at line 46 of file st_entry_state.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_picknplace::StEntryState::onTimerClientTickCallback () [inline]
Definition at line 41 of file st_entry_state.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_picknplace::StEntryState::runtimeConfigure () [inline]
Definition at line 24 of file st_entry_state.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StEntryState::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StEntryState::onSingleBehaviorTickCallback
      , this);
    }
static void sm_mtc_picknplace::StEntryState::staticConfigure () [inline], [static]
Definition at line 18 of file st_entry_state.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_picknplace/include/sm_mtc_picknplace/states/st_entry_state.h