sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart Struct Reference
#include <sti_spattern_loop_start.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiSPatternLoopStart >, StiSPatternRotate1, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_spattern_loop_start.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiSPatternLoopStart>, StiSPatternRotate1, CONTINUELOOP> > sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart::reactions
Definition at line 15 of file sti_spattern_loop_start.h.
Member Function Documentation
loopCondition()
bool sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart::loopCondition () [inline]
Definition at line 26 of file sti_spattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    if(superstate.iteration_count++ < superstate.total_iterations())
    {
      ROS_INFO("Spattern iteration finished, going to next iteration (%d)", superstate.iteration_count);
      return true;
    }
    else
    {
      ROS_INFO("Spattern iteration finished, All iterations finished (%d)", superstate.iteration_count - 1)
      ;
      return false;
    }
    
  }
onEntry()
void sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart::onEntry () [inline]
Definition at line 42 of file sti_spattern_loop_start.h.
References smacc::SmaccState< StiSPatternLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopCondition().
  {
    checkWhileLoopConditionAndThrowEvent(&
      StiSPatternLoopStart::loopCondition);
  }
runtimeConfigure()
void sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart::runtimeConfigure () [inline]
Definition at line 22 of file sti_spattern_loop_start.h.
  {
  }
staticConfigure()
static void sm_ridgeback_floor_coverage_dynamic_1::s_pattern_states::StiSPatternLoopStart::staticConfigure () [inline], [static]
Definition at line 18 of file sti_spattern_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_ridgeback_floor_coverage_dynamic_1/include/sm_ridgeback_floor_coverage_dynamic_1/states/s_pattern_states/sti_spattern_loop_start.h