sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird Struct Reference
#include <st_recovery_screw_third.h>
Public Types
typedef mpl::list< Transition< EvCbFailure< CbExecuteLastTrajectory, OrArm >, StRecoveryScrewThird, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onSuccess ()
void onExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file st_recovery_screw_third.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbFailure<CbExecuteLastTrajectory, OrArm>, StRecoveryScrewThird, ABORT> > sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird::reactions
Definition at line 13 of file st_recovery_screw_third.h.
Member Function Documentation
onExit()
void sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird::onExit () [inline]
Definition at line 35 of file st_recovery_screw_third.h.
            {
            }
onSuccess()
void sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird::onSuccess () [inline]
Definition at line 29 of file st_recovery_screw_third.h.
References smacc::SmaccState< StRecoveryScrewThird, SS >::throwSequenceFinishedEvent().
Referenced by runtimeConfigure().
            {
                this->throwSequenceFinishedEvent();
            }
runtimeConfigure()
void sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird::runtimeConfigure () [inline]
Definition at line 22 of file st_recovery_screw_third.h.
References onSuccess().
            {
                CbExecuteLastTrajectory *cb = this->getOrthogonal<OrArm>()->
      getClientBehavior<CbExecuteLastTrajectory>();
                //cb->onSuccess(&StRecoveryScrewInitial::throwSequenceFinishedEvent, this);
                cb->onSuccess(&StRecoveryScrewThird::onSuccess, this);
            }
staticConfigure()
static void sm_fetch_two_table_whiskey_pour::recovery_screw::StRecoveryScrewThird::staticConfigure () [inline], [static]
Definition at line 16 of file st_recovery_screw_third.h.
            {
                configure_orthogonal<OrArm, CbExecuteLastTrajectory>();
                configure_orthogonal<OrGripper, CbCloseGripper>();
            }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/states/recovery_screw_states/st_recovery_screw_third.h