sm_respira_1::StObserve Struct Reference
#include <st_observe.h>
Classes
struct AC_CYCLE
struct CALIBRATION
struct CMV_CYCLE
struct PC_CYCLE
struct PS_CYCLE
struct SHUTDOWN
Public Types
typedef mpl::list< Transition< EvKeyPressA< CbDefaultKeyboardBehavior, OrKeyboard >, SS1::SsACCycle, AC_CYCLE >, Transition< EvKeyPressB< CbDefaultKeyboardBehavior, OrKeyboard >, SS2::SsCMVCycle, CMV_CYCLE >, Transition< EvKeyPressC< CbDefaultKeyboardBehavior, OrKeyboard >, SS3::SsPCCycle, PC_CYCLE >, Transition< EvKeyPressD< CbDefaultKeyboardBehavior, OrKeyboard >, SS4::SsPSCycle, PS_CYCLE >, Transition< EvKeyPressL< CbDefaultKeyboardBehavior, OrKeyboard >, MsCalibration, CALIBRATION >, Transition< EvKeyPressS< CbDefaultKeyboardBehavior, OrKeyboard >, MsShutdown, SHUTDOWN > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_observe.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressA<CbDefaultKeyboardBehavior, OrKeyboard>, SS1::SsACCycle, AC_CYCLE>, Transition<EvKeyPressB<CbDefaultKeyboardBehavior, OrKeyboard>, SS2::SsCMVCycle, CMV_CYCLE>, Transition<EvKeyPressC<CbDefaultKeyboardBehavior, OrKeyboard>, SS3::SsPCCycle, PC_CYCLE>, Transition<EvKeyPressD<CbDefaultKeyboardBehavior, OrKeyboard>, SS4::SsPSCycle, PS_CYCLE>, Transition<EvKeyPressL<CbDefaultKeyboardBehavior, OrKeyboard>, MsCalibration, CALIBRATION>, Transition<EvKeyPressS<CbDefaultKeyboardBehavior, OrKeyboard>, MsShutdown, SHUTDOWN> > sm_respira_1::StObserve::reactions
Definition at line 30 of file st_observe.h.
Member Function Documentation
onEntry()
void sm_respira_1::StObserve::onEntry () [inline]
Definition at line 58 of file st_observe.h.
    {
        ROS_INFO("On Entry!");
    }
onExit()
void sm_respira_1::StObserve::onExit () [inline]
Definition at line 63 of file st_observe.h.
    {
        ROS_INFO("On Exit!");
    }
onSingleBehaviorTickCallback()
void sm_respira_1::StObserve::onSingleBehaviorTickCallback () [inline]
Definition at line 73 of file st_observe.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_respira_1::StObserve::onTimerClientTickCallback () [inline]
Definition at line 68 of file st_observe.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_respira_1::StObserve::runtimeConfigure () [inline]
Definition at line 41 of file st_observe.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StObserve::onTimerClientTickCallback, this
      );
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StObserve::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_respira_1::StObserve::staticConfigure () [inline], [static]
Definition at line 33 of file st_observe.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/st_observe.h