sm_mtc_picknplace::StForbidCollisionObject Struct Reference
#include <st_forbid_collision_object.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, MsPlaceObject, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, MsPlaceObject, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_forbid_collision_object.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, MsPlaceObject, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, MsPlaceObject, SUCCESS> > sm_mtc_picknplace::StForbidCollisionObject::reactions
Definition at line 14 of file st_forbid_collision_object.h.
Member Function Documentation
void sm_mtc_picknplace::StForbidCollisionObject::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_forbid_collision_object.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_picknplace::StForbidCollisionObject::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_forbid_collision_object.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_picknplace::StForbidCollisionObject::runtimeConfigure () [inline]
Definition at line 23 of file st_forbid_collision_object.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StForbidCollisionObject::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StForbidCollisionObject::onSingleBehaviorTickCallback,
       this);
    }
static void sm_mtc_picknplace::StForbidCollisionObject::staticConfigure () [inline], [static]
Definition at line 17 of file st_forbid_collision_object.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_picknplace/include/sm_mtc_picknplace/states/ms_pick_object_states/st_forbid_collision_object.h