sm_starcraft_ai::StState3 Struct Reference
#include <st_state_3.h>
Classes
struct ATTACK
struct BUILD
struct MOVE
struct PREVIOUS
Public Types
typedef mpl::list< Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StState2, PREVIOUS >, Transition< EvKeyPressA< CbDefaultKeyboardBehavior, OrKeyboard >, SS1::Ss1, MOVE >, Transition< EvKeyPressB< CbDefaultKeyboardBehavior, OrKeyboard >, SS2::Ss2, BUILD >, Transition< EvKeyPressC< CbDefaultKeyboardBehavior, OrKeyboard >, SS3::Ss3, ATTACK > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_state_3.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StState2, PREVIOUS>, Transition<EvKeyPressA<CbDefaultKeyboardBehavior, OrKeyboard>, SS1::Ss1, MOVE>, Transition<EvKeyPressB<CbDefaultKeyboardBehavior, OrKeyboard>, SS2::Ss2, BUILD>, Transition<EvKeyPressC<CbDefaultKeyboardBehavior, OrKeyboard>, SS3::Ss3, ATTACK> > sm_starcraft_ai::StState3::reactions
Definition at line 24 of file st_state_3.h.
Member Function Documentation
void sm_starcraft_ai::StState3::onEntry () [inline]
Definition at line 52 of file st_state_3.h.
    {
        ROS_INFO("On Entry!");
    }
void sm_starcraft_ai::StState3::onExit () [inline]
Definition at line 57 of file st_state_3.h.
    {
        ROS_INFO("On Exit!");
    }
void sm_starcraft_ai::StState3::onSingleBehaviorTickCallback () [inline]
Definition at line 67 of file st_state_3.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_starcraft_ai::StState3::onTimerClientTickCallback () [inline]
Definition at line 62 of file st_state_3.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_starcraft_ai::StState3::runtimeConfigure () [inline]
Definition at line 35 of file st_state_3.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StState3::onTimerClientTickCallback, this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StState3::onSingleBehaviorTickCallback
      , this);
    }
static void sm_starcraft_ai::StState3::staticConfigure () [inline], [static]
Definition at line 27 of file st_state_3.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_starcraft_ai/include/sm_starcraft_ai/states/st_state_3.h