sm_moveit_wine_serve::StNavigateToSourceTable Struct Reference
#include <st_navigate_to_source_table.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, SS1::SsPickObject, SUCCESS >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StNavigateToSourceTable, ABORT >, Transition< EvFinishDemo, StInitialPosture > > reactions
Public Member Functions
void runtimeConfigure ()
void OnEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 11 of file st_navigate_to_source_table.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, SS1::SsPickObject, SUCCESS>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StNavigateToSourceTable, ABORT>, Transition<EvFinishDemo, StInitialPosture> > sm_moveit_wine_serve::StNavigateToSourceTable::reactions
Definition at line 23 of file st_navigate_to_source_table.h.
Member Function Documentation
OnEntry()
void sm_moveit_wine_serve::StNavigateToSourceTable::OnEntry () [inline]
Definition at line 56 of file st_navigate_to_source_table.h.
        {
            ROS_INFO("state on entry");
        }
runtimeConfigure()
void sm_moveit_wine_serve::StNavigateToSourceTable::runtimeConfigure () [inline]
Definition at line 31 of file st_navigate_to_source_table.h.
References sm_moveit_wine_serve::cl_perception_system::ClPerceptionSystem::decidePickCubePose(), sm_moveit_wine_serve::cl_perception_system::ClPerceptionSystem::getMainTablePose(), and smacc::ISmaccClient::requiresClient().
        {
            auto* navigateGlobalPosition = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbNavigateGlobalPosition>();
            
            ClPerceptionSystem *perceptionSystem;
            navigateGlobalPosition->requiresClient(perceptionSystem);
            //perceptionSystem->nextObject();
            auto tablePose = perceptionSystem->getMainTablePose().pose;
            tablePose.position.x -= 0.85;
            geometry_msgs::PoseStamped nextCubePose;
            if (perceptionSystem->decidePickCubePose(nextCubePose))
            {
                // align with the cube in the y axis
                tablePose.position.y = nextCubePose.pose.position.y;
                navigateGlobalPosition->setGoal(tablePose);
            }
            else
            {
                this->postEvent<EvFinishDemo>();
            }
        }
staticConfigure()
static void sm_moveit_wine_serve::StNavigateToSourceTable::staticConfigure () [inline], [static]
Definition at line 26 of file st_navigate_to_source_table.h.
        {
            configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
        }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_wine_serve/include/sm_moveit_wine_serve/states/st_navigate_to_source_table.h