sm_starcraft_ai::attack_inner_states::StiAttack3 Struct Reference
#include <sti_attack_3.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StiAttack1, TIMEOUT >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StiAttack2, PREVIOUS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StiAttack1, NEXT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_attack_3.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StiAttack1, TIMEOUT>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StiAttack2, PREVIOUS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StiAttack1, NEXT> > sm_starcraft_ai::attack_inner_states::StiAttack3::reactions
Definition at line 22 of file sti_attack_3.h.
Member Function Documentation
onEntry()
void sm_starcraft_ai::attack_inner_states::StiAttack3::onEntry () [inline]
Definition at line 50 of file sti_attack_3.h.
  {
    ROS_INFO("On Entry!");
  }
onExit()
void sm_starcraft_ai::attack_inner_states::StiAttack3::onExit () [inline]
Definition at line 55 of file sti_attack_3.h.
  {
    ROS_INFO("On Exit!");
  }
onSingleBehaviorTickCallback()
void sm_starcraft_ai::attack_inner_states::StiAttack3::onSingleBehaviorTickCallback () [inline]
Definition at line 65 of file sti_attack_3.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("single behavior tick!");
  }
onTimerClientTickCallback()
void sm_starcraft_ai::attack_inner_states::StiAttack3::onTimerClientTickCallback () [inline]
Definition at line 60 of file sti_attack_3.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("timer client tick!");
  }
runtimeConfigure()
void sm_starcraft_ai::attack_inner_states::StiAttack3::runtimeConfigure () [inline]
Definition at line 33 of file sti_attack_3.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
  {
    // get reference to the client
    ClRosTimer *client;
    this->requiresClient(client);
    // subscribe to the timer client callback
    client->onTimerTick(&StiAttack3::onTimerClientTickCallback, this);
    // getting reference to the single countdown behavior
    auto *cbsingle = this->getOrthogonal<OrTimer>()
                          ->getClientBehavior<CbTimerCountdownOnce>();
    // subscribe to the single countdown behavior callback
    cbsingle->onTimerTick(&StiAttack3::onSingleBehaviorTickCallback
      , this);
  }
staticConfigure()
static void sm_starcraft_ai::attack_inner_states::StiAttack3::staticConfigure () [inline], [static]
Definition at line 25 of file sti_attack_3.h.
  {
    configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
    configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
    configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
    configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_starcraft_ai/include/sm_starcraft_ai/states/attack_inner_states/sti_attack_3.h