sm_dance_bot_strikes_back::StNavigateToWaypointsX Struct Reference
#include <st_navigate_to_waypoints_x.h>
Classes
struct TRANSITION_1
struct TRANSITION_2
struct TRANSITION_3
struct TRANSITION_4
struct TRANSITION_5
Public Types
typedef mpl::list< Transition< EvWaypoint0< ClMoveBaseZ, OrNavigation >, SS1::SsRadialPattern1, TRANSITION_1 >, Transition< EvWaypoint1< ClMoveBaseZ, OrNavigation >, SS2::SsRadialPattern2, TRANSITION_2 >, Transition< EvWaypoint2< ClMoveBaseZ, OrNavigation >, SS3::SsRadialPattern3, TRANSITION_3 >, Transition< EvWaypoint3< ClMoveBaseZ, OrNavigation >, SS4::SsFPattern1, TRANSITION_4 >, Transition< EvWaypoint4< ClMoveBaseZ, OrNavigation >, SS5::SsSPattern1, TRANSITION_5 >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StNavigateToWaypointsX > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_navigate_to_waypoints_x.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvWaypoint0<ClMoveBaseZ, OrNavigation>, SS1::SsRadialPattern1, TRANSITION_1>, Transition<EvWaypoint1<ClMoveBaseZ, OrNavigation>, SS2::SsRadialPattern2, TRANSITION_2>, Transition<EvWaypoint2<ClMoveBaseZ, OrNavigation>, SS3::SsRadialPattern3, TRANSITION_3>, Transition<EvWaypoint3<ClMoveBaseZ, OrNavigation>, SS4::SsFPattern1, TRANSITION_4>, Transition<EvWaypoint4<ClMoveBaseZ, OrNavigation>, SS5::SsSPattern1, TRANSITION_5>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StNavigateToWaypointsX> > sm_dance_bot_strikes_back::StNavigateToWaypointsX::reactions
Definition at line 26 of file st_navigate_to_waypoints_x.h.
Member Function Documentation
void sm_dance_bot_strikes_back::StNavigateToWaypointsX::runtimeConfigure () [inline]
Definition at line 35 of file st_navigate_to_waypoints_x.h.
References smacc::ISmaccClient::getComponent(), smacc::ISmaccState::requiresClient(), and move_base_z_client::WaypointNavigator::sendNextGoal().
  {
    ClMoveBaseZ *move_base;
    this->requiresClient(move_base);
    auto waypointsNavigator = move_base->getComponent<WaypointNavigator>();
    
    waypointsNavigator->sendNextGoal();
    ROS_INFO("current iteration waypoints x: %ld", waypointsNavigator->getCurrentWaypointIndex());
  }
static void sm_dance_bot_strikes_back::StNavigateToWaypointsX::staticConfigure () [inline], [static]
Definition at line 29 of file st_navigate_to_waypoints_x.h.
  {
    configure_orthogonal<OrLED, CbLEDOn>();
    configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_strikes_back/include/sm_dance_bot_strikes_back/states/st_navigate_to_waypoints_x.h