sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart Struct Reference
#include <ssr_radial_loop_start.h>
Public Types
typedef smacc::Transition< EvLoopContinue< SsrRadialLoopStart >, SsrRadialRotate, CONTINUELOOP > reactions
Public Member Functions
void onInitialize ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file ssr_radial_loop_start.h.
Member Typedef Documentation
typedef smacc::Transition<EvLoopContinue<SsrRadialLoopStart>, SsrRadialRotate, CONTINUELOOP> sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart::reactions
Definition at line 8 of file ssr_radial_loop_start.h.
Member Function Documentation
bool sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart::loopWhileCondition () [inline]
Definition at line 14 of file ssr_radial_loop_start.h.
Referenced by onEntry().
                            {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d",
             superstate.iteration_count, superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart::onDefinition () [inline], [static]
Definition at line 10 of file ssr_radial_loop_start.h.
{}
void sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart::onEntry () [inline]
Definition at line 22 of file ssr_radial_loop_start.h.
References smacc::SmaccState< SsrRadialLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
                 {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      SsrRadialLoopStart::loopWhileCondition);
  }
void sm_dance_bot_2::radial_motion_states::SsrRadialLoopStart::onInitialize () [inline]
Definition at line 12 of file ssr_radial_loop_start.h.
{}
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_2/include/sm_dance_bot_2/states/radial_motion_states/ssr_radial_loop_start.h