sm_mtc_pour::StPlacePoseKinematics Struct Reference
#include <st_place_pose_kinematics.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StReleaseObject, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StReleaseObject, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_place_pose_kinematics.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StReleaseObject, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StReleaseObject, SUCCESS> > sm_mtc_pour::StPlacePoseKinematics::reactions
Definition at line 14 of file st_place_pose_kinematics.h.
Member Function Documentation
void sm_mtc_pour::StPlacePoseKinematics::onSingleBehaviorTickCallback () [inline]
Definition at line 45 of file st_place_pose_kinematics.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_mtc_pour::StPlacePoseKinematics::onTimerClientTickCallback () [inline]
Definition at line 40 of file st_place_pose_kinematics.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_mtc_pour::StPlacePoseKinematics::runtimeConfigure () [inline]
Definition at line 23 of file st_place_pose_kinematics.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StPlacePoseKinematics::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StPlacePoseKinematics::onSingleBehaviorTickCallback,
      this);
    }
static void sm_mtc_pour::StPlacePoseKinematics::staticConfigure () [inline], [static]
Definition at line 17 of file st_place_pose_kinematics.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_mtc_pour/include/sm_mtc_pour/states/ms_place_bottle_states/st_place_pose_kinematics.h