sm_moveit_3::pick_states::StNavigationPosture Struct Reference
#include <st_navigation_posture.h>
Public Types
typedef mpl::list< Transition< MoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StNavigationPosture, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_navigation_posture.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<MoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StNavigationPosture, ABORT> > sm_moveit_3::pick_states::StNavigationPosture::reactions
Definition at line 16 of file st_navigation_posture.h.
Member Function Documentation
runtimeConfigure()
void sm_moveit_3::pick_states::StNavigationPosture::runtimeConfigure () [inline]
Definition at line 62 of file st_navigation_posture.h.
References move_group_interface_client::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StNavigationPosture, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StNavigationPosture::throwSequenceFinishedEvent, this);
        this->getOrthogonal<OrNavigation>()->getClientBehavior<CbMoveJoints>()->scalingFactor_ = 1;
        /*
        ros::WallDuration(3).sleep();
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        auto moveCartesianRelative = this->getOrthogonal<OrArm>()
                                         ->getClientBehavior<CbMoveCartesianRelative>();
        std::vector<std::string> namesposes = moveGroupClient->moveGroupClientInterface.getNamedTargets();
        ROS_INFO("--- named poses: ");
        for (auto &posename : namesposes)
        {
            ROS_INFO_STREAM(" - named pose: " << posename);
        }
        ROS_INFO("--- named poses");
        moveCartesianRelative->offset_.z = -0.35;
        auto currentTable = perceptionSystem->getCurrentTable();
        if (currentTable == RobotProcessStatus::TABLE0)
        {
            moveCartesianRelative->offset_.x = -0.25;
        }
        else if (currentTable == RobotProcessStatus::TABLE1)
        {
            moveCartesianRelative->offset_.x = 0.25;
        }
    */
    }
staticConfigure()
static void sm_moveit_3::pick_states::StNavigationPosture::staticConfigure () [inline], [static]
Definition at line 19 of file st_navigation_posture.h.
    {
    // std::map<std::string, double> jointValues{
    // {"l_wheel_joint", 0.2032989263112741},
    // {"r_wheel_joint", -0.25798452342087597},
    // {"torso_lift_joint", -1.2577603815717127e-05},
    // {"bellows_joint", 0.006785193726937263},
    // {"head_pan_joint", 0.0053190193943049024},
    // {"head_tilt_joint", 0.0037173708013753526},
    // //{"shoulder_pan_joint", 0.7199986235290062},
    // {"shoulder_pan_joint", 1.0},
    // //{"shoulder_lift_joint", 0.7000699976533715},
    // {"shoulder_lift_joint", 1.51},
    // {"upperarm_roll_joint", -7.398079828480064e-05},
    // //{"elbow_flex_joint", -1.99994794099468},
    // {"elbow_flex_joint", -2.49994794099468},
    // {"forearm_roll_joint", 0.00021030168417901507},
    // {"wrist_flex_joint", -0.89},
    // {"wrist_roll_joint", -0.00023467601597193521},
    // {"l_gripper_finger_joint", 0.05001998415439018},
    // {"r_gripper_finger_joint", 0.050039698895249535}};
    // std::map<std::string, double> jointValues
    // {{"torso_lift_joint", -1.5886941446227077e-11},
    // {"bellows_joint", 0.006636882979390101},
    // {"head_pan_joint", -1.7973139598836951e-07},
    // {"head_tilt_joint",0.0024005013786707607},
    // {"shoulder_pan_joint", 1.3199500661528623},
    // {"shoulder_lift_joint", 1.3999822887756963},
    // {"upperarm_roll_joint", -0.19998775461277418},
    // {"elbow_flex_joint",1.7199706352473747},
    // {"forearm_roll_joint", 1.3521167669949818e-06},
    // {"wrist_flex_joint", 1.6600028174761388},
    // {"wrist_roll_joint", -2.1971452301983163e-07},
    // // {"l_gripper_finger_joint",0.05003185444046081},
    // // {"r_gripper_finger_joint", 0.050057917261335}
    // };
        //configure_orthogonal<OrNavigation, CbMoveJoints>(jointValues);
        configure_orthogonal<OrNavigation, CbMoveKnownState>("sm_moveit_3", "
      config/manipulation/known_states/nav_posture.yaml");
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_3/include/sm_moveit_3/states/pick_states/st_navigation_posture.h