smacc::client_bases::SmaccServiceClient< ServiceType > Class Template Reference
#include <smacc_service_client.h>
Public Member Functions
SmaccServiceClient ()
virtual void initialize () override
bool call (ServiceType &srvreq)
Public Attributes
boost::optional< std::string > serviceName_
Protected Attributes
ros::NodeHandle nh_
ros::ServiceClient client_
bool initialized_
Additional Inherited Members
Detailed Description
template<typename ServiceType>
class smacc::client_bases::SmaccServiceClient< ServiceType >
Definition at line 17 of file smacc_service_client.h.
Constructor & Destructor Documentation
SmaccServiceClient()
template<typename ServiceType>
smacc::client_bases::SmaccServiceClient< ServiceType >::SmaccServiceClient () [inline]
Definition at line 22 of file smacc_service_client.h.
    {
        initialized_ = false;
    }
Member Function Documentation
call()
template<typename ServiceType>
bool smacc::client_bases::SmaccServiceClient< ServiceType >::call (ServiceType & srvreq) [inline]
Definition at line 45 of file smacc_service_client.h.
Referenced by sm_dance_bot::cl_service3::CbService3::onEntry(), sm_ridgeback_floor_coverage_static_1::cl_service3::CbService3::onEntry(), sm_ridgeback_floor_coverage_dynamic_1::cl_service3::CbService3::onEntry(), and sm_dance_bot_strikes_back::cl_service3::CbService3::onEntry().
    {
        return client_.call(srvreq);
    }
initialize()
template<typename ServiceType>
virtual void smacc::client_bases::SmaccServiceClient< ServiceType >::initialize () [inline], [override], [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 27 of file smacc_service_client.h.
    {
        if (!initialized_)
        {
            if (!serviceName_)
            {
                ROS_ERROR("service client with no service name set. Skipping.");
            }
            else
            {
                ROS_INFO_STREAM("[" << this->getName() << "] Client Service: " << *
      serviceName_);
                this->initialized_ = true;
                client_ = nh_.serviceClient<ServiceType>(*serviceName_);
            }
        }
    }
Member Data Documentation
client_
template<typename ServiceType>
ros::ServiceClient smacc::client_bases::SmaccServiceClient< ServiceType >::client_ [protected]
Definition at line 52 of file smacc_service_client.h.
Referenced by smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >::call(), and smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >::initialize().
initialized_
template<typename ServiceType>
bool smacc::client_bases::SmaccServiceClient< ServiceType >::initialized_ [protected]
Definition at line 53 of file smacc_service_client.h.
Referenced by smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >::initialize(), and smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >::SmaccServiceClient().
nh_
template<typename ServiceType>
ros::NodeHandle smacc::client_bases::SmaccServiceClient< ServiceType >::nh_ [protected]
Definition at line 51 of file smacc_service_client.h.
Referenced by smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >::initialize().
serviceName_
template<typename ServiceType>
boost::optional<std::string> smacc::client_bases::SmaccServiceClient< ServiceType >::serviceName_
Definition at line 20 of file smacc_service_client.h.
The documentation for this class was generated from the following file:
smacc/include/smacc/client_bases/smacc_service_client.h