cl_move_group_interface::CbCircularPouringMotion Class Reference
#include <cb_pouring_motion.h>
Public Member Functions
CbCircularPouringMotion (const geometry_msgs::PointStamped &pivotPoint, double deltaHeight, std::string tipLink=``)
virtual void generateTrajectory () override
virtual void createMarkers () override
void getCurrentEndEffectorPose (tf::StampedTransform &currentEndEffectorTransform)
Public Attributes
boost::optional< double > angularSpeed_rad_s_
boost::optional< double > linearSpeed_m_s_
Protected Attributes
geometry_msgs::PointStamped pivotPoint_
double deltaHeight_
Private Member Functions
void computeCurrentEndEffectorPoseRelativeToPivot ()
Additional Inherited Members
Detailed Description
Definition at line 14 of file cb_pouring_motion.h.
Constructor & Destructor Documentation
CbCircularPouringMotion()
cl_move_group_interface::CbCircularPouringMotion::CbCircularPouringMotion (const geometry_msgs::PointStamped & pivotPoint, double deltaHeight, std::string tipLink = ``)
Definition at line 13 of file cb_pouring_motion.cpp.
        : pivotPoint_(planePivotPoint)
        , deltaHeight_(deltaHeight)
        , CbMoveEndEffectorTrajectory(tipLink)
    {
    }
Member Function Documentation
computeCurrentEndEffectorPoseRelativeToPivot()
void cl_move_group_interface::CbCircularPouringMotion::computeCurrentEndEffectorPoseRelativeToPivot () [private]
createMarkers()
void cl_move_group_interface::CbCircularPouringMotion::createMarkers () [override], [virtual]
Reimplemented from cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 106 of file cb_pouring_motion.cpp.
References cl_move_group_interface::CbMoveEndEffectorTrajectory::beahiorMarkers_, cl_move_group_interface::CbMoveEndEffectorTrajectory::createMarkers(), and pivotPoint_.
    {
        CbMoveEndEffectorTrajectory::createMarkers();
        visualization_msgs::Marker marker;
        marker.ns = "trajectory";
        marker.id = beahiorMarkers_.markers.size();
        marker.type = visualization_msgs::Marker::SPHERE;
        marker.action = visualization_msgs::Marker::ADD;
        marker.scale.x = 0.05;
        marker.scale.y = 0.05;
        marker.scale.z = 0.05;
        marker.color.a = 1.0;
        marker.color.r = 0.0;
        marker.color.g = 0;
        marker.color.b = 1.0;
        marker.pose.position = this->pivotPoint_.point;
        marker.header.frame_id = this->pivotPoint_.header.frame_id;
        marker.header.stamp = ros::Time::now();
        beahiorMarkers_.markers.push_back(marker);
    }
generateTrajectory()
void cl_move_group_interface::CbCircularPouringMotion::generateTrajectory () [override], [virtual]
Reimplemented from cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 44 of file cb_pouring_motion.cpp.
References deltaHeight_, cl_move_group_interface::CbMoveEndEffectorTrajectory::endEffectorTrajectory_, getCurrentEndEffectorPose(), linearSpeed_m_s_, and pivotPoint_.
    {
        // at least 1 sample per centimeter (average)
        const double METERS_PER_SAMPLE = 0.01;
        float dist_meters =0;
        float totallineardist = fabs(this->deltaHeight_);
        int totalSamplesCount = totallineardist / METERS_PER_SAMPLE;
        int steps = totallineardist/ METERS_PER_SAMPLE;
        float interpolation_factor_step = 1.0/totalSamplesCount;
        double secondsPerSample;
        if (linearSpeed_m_s_)
        {
            secondsPerSample = METERS_PER_SAMPLE / (*linearSpeed_m_s_);
        }
        else
        {
            secondsPerSample = std::numeric_limits<double>::max();
        }
        tf::Vector3 v0, v1;
        tf::StampedTransform currentEndEffectorTransform;
        this->getCurrentEndEffectorPose(currentEndEffectorTransform);
        v0 = currentEndEffectorTransform.getOrigin();
        v1 = v0;
        v1.setZ(v1.z()- this->deltaHeight_);
        tf::Quaternion initialOrientation = currentEndEffectorTransform.getRotation();
        tf::Quaternion rotation = tf::shortestArcQuat(v0, v1);
        auto finalOrientation = initialOrientation * rotation;
        float interpolation_factor = 0;
        tf::Vector3 vi = v0;
        for (float i =0; i < steps; i++)
        {
            auto q = tf::slerp(initialOrientation, finalOrientation, interpolation_factor);
            interpolation_factor += interpolation_factor_step;
            dist_meters += METERS_PER_SAMPLE;
            vi = v0;
            vi.setZ(vi.getZ() + dist_meters);
            tf::Transform pose;
            pose.setOrigin(vi);
            pose.setRotation(q);
            geometry_msgs::PoseStamped globalPose;
            tf::poseTFToMsg(pose, globalPose.pose);
            globalPose.header.frame_id = pivotPoint_.header.frame_id;
            globalPose.header.stamp = pivotPoint_.header.stamp + ros::Duration(i *
      secondsPerSample);
            this->endEffectorTrajectory_.push_back(globalPose);
        }
    }
getCurrentEndEffectorPose()
void cl_move_group_interface::CbCircularPouringMotion::getCurrentEndEffectorPose (tf::StampedTransform & currentEndEffectorTransform)
Definition at line 20 of file cb_pouring_motion.cpp.
References cl_move_group_interface::CbMoveEndEffectorTrajectory::movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, pivotPoint_, and cl_move_group_interface::CbMoveEndEffectorTrajectory::tipLink_.
Referenced by generateTrajectory().
    {
        tf::TransformListener tfListener;
        try
        {
            if (!tipLink_ || *tipLink_ == "")
            {
                tipLink_ = this->movegroupClient_->
      moveGroupClientInterface.getEndEffectorLink();
            }
            tfListener.waitForTransform(this->pivotPoint_.header.frame_id, *
      tipLink_, ros::Time(0), ros::Duration(10));
            tfListener.lookupTransform(this->pivotPoint_.header.frame_id, *
      tipLink_, ros::Time(0), currentEndEffectorTransform);
            // we define here the global frame as the pivot frame id
            // tfListener.waitForTransform(currentRobotEndEffectorPose.header.frame_id,
       planePivotPose_.header.frame_id, ros::Time(0), ros::Duration(10));
            // tfListener.lookupTransform(currentRobotEndEffectorPose.header.frame_id,
       planePivotPose_.header.frame_id, ros::Time(0), globalBaseLink);
        }
        catch (const std::exception &e)
        {
            std::cerr << e.what() << '\n';
        }
    }
Member Data Documentation
angularSpeed_rad_s_
boost::optional<double> cl_move_group_interface::CbCircularPouringMotion::angularSpeed_rad_s_
Definition at line 17 of file cb_pouring_motion.h.
deltaHeight_
double cl_move_group_interface::CbCircularPouringMotion::deltaHeight_ [protected]
Definition at line 33 of file cb_pouring_motion.h.
Referenced by generateTrajectory().
linearSpeed_m_s_
boost::optional<double> cl_move_group_interface::CbCircularPouringMotion::linearSpeed_m_s_
Definition at line 19 of file cb_pouring_motion.h.
Referenced by generateTrajectory().
pivotPoint_
geometry_msgs::PointStamped cl_move_group_interface::CbCircularPouringMotion::pivotPoint_ [protected]
Definition at line 30 of file cb_pouring_motion.h.
Referenced by createMarkers(), generateTrajectory(), and getCurrentEndEffectorPose().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_pouring_motion.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_pouring_motion.cpp