smacc::ISmaccClientBehavior Class Reference
#include <smacc_client_behavior_base.h>
Public Member Functions
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Protected Member Functions
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Private Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Private Attributes
ISmaccStateMachine * stateMachine_
ISmaccState * currentState
smacc::ISmaccOrthogonal * currentOrthogonal
Friends
class ISmaccState
class ISmaccOrthogonal
Detailed Description
Definition at line 12 of file smacc_client_behavior_base.h.
Constructor & Destructor Documentation
ISmaccClientBehavior()
smacc::ISmaccClientBehavior::ISmaccClientBehavior ()
Definition at line 5 of file smacc_client_behavior_base.cpp.
References currentState, and stateMachine_.
    {
        stateMachine_ = nullptr;
        currentState = nullptr;
    }
 ISmaccClientBehavior()
smacc::ISmaccClientBehavior::~ISmaccClientBehavior () [virtual]
Definition at line 11 of file smacc_client_behavior_base.cpp.
    {
        ROS_WARN("Client behavior deallocated.");
    }
Member Function Documentation
dispose()
void smacc::ISmaccClientBehavior::dispose () [protected], [virtual]
Reimplemented in smacc::SmaccAsyncClientBehavior.
Definition at line 38 of file smacc_client_behavior_base.cpp.
Referenced by onExit().
    {
    }
executeOnEntry()
void smacc::ISmaccClientBehavior::executeOnEntry () [protected], [virtual]
Reimplemented in smacc::SmaccAsyncClientBehavior.
Definition at line 26 of file smacc_client_behavior_base.cpp.
References getName(), and onEntry().
Referenced by onExit().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior onEntry", this->
      getName().c_str());
        this->onEntry();
    }
executeOnExit()
void smacc::ISmaccClientBehavior::executeOnExit () [protected], [virtual]
Reimplemented in smacc::SmaccAsyncClientBehavior.
Definition at line 32 of file smacc_client_behavior_base.cpp.
References getName(), and onExit().
Referenced by smacc::SmaccAsyncClientBehavior::executeOnExit(), and onExit().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior onExit", this->getName().c_str());
        this->onExit();
    }
getCurrentState()
ISmaccState * smacc::ISmaccClientBehavior::getCurrentState () [inline], [protected]
Definition at line 48 of file smacc_client_behavior_impl.h.
References currentState.
Referenced by cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), onExit(), and cl_move_base_z::CbNavigateGlobalPosition::readStartPoseFromParameterServer().
{
    return this->currentState;
}
getName()
std::string smacc::ISmaccClientBehavior::getName () const
Definition at line 16 of file smacc_client_behavior_base.cpp.
References smacc::introspection::demangleSymbol().
Referenced by smacc::SmaccAsyncClientBehavior::dispose(), cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), executeOnEntry(), smacc::SmaccAsyncClientBehavior::executeOnEntry(), executeOnExit(), smacc::SmaccAsyncClientBehavior::executeOnExit(), cl_move_group_interface::CbMoveJoints::moveJoints(), smacc::SmaccClientBehavior::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), smacc::SmaccClientBehavior::onExit(), and runtimeConfigure().
    {
        return demangleSymbol(typeid(*this).name());
    }
getStateMachine()
ISmaccStateMachine * smacc::ISmaccClientBehavior::getStateMachine () [inline]
Definition at line 42 of file smacc_client_behavior_impl.h.
References stateMachine_.
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), smacc::SmaccAsyncClientBehavior::onFailure(), smacc::SmaccAsyncClientBehavior::onFinished(), smacc::SmaccAsyncClientBehavior::onSuccess(), cl_ros_timer::CbTimerCountdownOnce::onTimerTick(), and cl_ros_timer::CbTimerCountdownLoop::onTimerTick().
{
    return this->stateMachine_;
}
onEntry()
virtual void smacc::ISmaccClientBehavior::onEntry () [inline], [protected], [virtual]
Reimplemented in cl_move_group_interface::CbMoveEndEffectorTrajectory, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_ridgeback_floor_coverage_dynamic_1::cl_lidar::ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >, cl_move_base_z::CbNavigateBackwards, cl_move_base_z::CbNavigateForward, cl_move_base_z::CbNavigateGlobalPosition, cl_ros_publisher::CbDefaultPublishLoop, cl_move_base_z::CbAbsoluteRotate, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_move_base_z::CbRotate, cl_move_group_interface::CbMoveCartesianRelative, cl_move_group_interface::CbMoveNamedTarget, sm_dance_bot::cl_service3::CbService3, sm_dance_bot_strikes_back::cl_service3::CbService3, sm_ridgeback_floor_coverage_dynamic_1::cl_service3::CbService3, sm_ridgeback_floor_coverage_static_1::cl_service3::CbService3, cl_move_group_interface::CbMoveEndEffectorRelative, cl_move_group_interface::CbMoveJoints, cl_move_base_z::CbUndoPathBackwards, cl_move_group_interface::CbMoveEndEffector, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_ridgeback_floor_coverage_dynamic_1::cl_string_publisher::CbStringPublisher, sm_ridgeback_floor_coverage_static_1::cl_string_publisher::CbStringPublisher, cl_move_group_interface::CbAttachObject, cl_move_group_interface::CbExecuteLastTrajectory, cl_move_group_interface::CbMoveLastTrajectoryInitialState, cl_move_base_z::CbNavigateNextWaypoint, sm_dance_bot::cl_lidar::CbLidarSensor, sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor, sm_ridgeback_floor_coverage_dynamic_1::cl_lidar::CbLidarSensor, sm_ridgeback_floor_coverage_static_1::cl_lidar::CbLidarSensor, cl_move_group_interface::CbDetachObject, cl_keyboard::CbDefaultKeyboardBehavior, cl_move_group_interface::CbEndEffectorRotate, smacc::SmaccClientBehavior, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOff, sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOn, sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOff, sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOn, cl_ros_timer::CbTimerCountdownLoop, sm_calendar_week::cl_subscriber::CbDefaultSubscriberBehavior, sm_calendar_week::cl_subscriber::CbWatchdogSubscriberBehavior, sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbCloseGripper, sm_fetch_two_table_pick_n_place_1::cl_gripper::CbCloseGripper, sm_moveit_screw_loop::cl_gripper::CbCloseGripper, sm_packml::cl_subscriber::CbDefaultSubscriberBehavior, sm_packml::cl_subscriber::CbWatchdogSubscriberBehavior, sm_respira_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_respira_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_starcraft_ai::cl_subscriber::CbDefaultSubscriberBehavior, sm_starcraft_ai::cl_subscriber::CbWatchdogSubscriberBehavior, sm_three_some::cl_subscriber::CbDefaultSubscriberBehavior, sm_three_some::cl_subscriber::CbWatchdogSubscriberBehavior, cl_ros_timer::CbTimerCountdownOnce, sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbOpenGripper, sm_fetch_two_table_pick_n_place_1::cl_gripper::CbOpenGripper, sm_moveit_screw_loop::cl_gripper::CbOpenGripper, cl_ros_publisher::CbMutedBehavior< RosMsgType >, and cl_ros_timer::CbTimer.
Definition at line 32 of file smacc_client_behavior_base.h.
Referenced by executeOnEntry(), and smacc::SmaccAsyncClientBehavior::executeOnEntry().
{};
onExit()
virtual void smacc::ISmaccClientBehavior::onExit () [inline], [protected], [virtual]
Reimplemented in cl_move_group_interface::CbMoveEndEffectorTrajectory, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_ridgeback_floor_coverage_dynamic_1::cl_lidar::ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >, cl_ros_publisher::CbDefaultPublishLoop, cl_move_base_z::CbNavigateGlobalPosition, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_move_base_z::CbNavigateBackwards, cl_move_base_z::CbNavigateForward, cl_move_base_z::CbAbsoluteRotate, cl_move_group_interface::CbMoveCartesianRelative, cl_move_group_interface::CbMoveNamedTarget, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_ridgeback_floor_coverage_dynamic_1::cl_string_publisher::CbStringPublisher, sm_ridgeback_floor_coverage_static_1::cl_string_publisher::CbStringPublisher, cl_move_group_interface::CbMoveEndEffectorRelative, cl_move_base_z::CbUndoPathBackwards, cl_move_group_interface::CbMoveJoints, sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbCloseGripper, sm_fetch_two_table_pick_n_place_1::cl_gripper::CbCloseGripper, sm_moveit_screw_loop::cl_gripper::CbCloseGripper, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbOpenGripper, sm_fetch_two_table_pick_n_place_1::cl_gripper::CbOpenGripper, sm_moveit_screw_loop::cl_gripper::CbOpenGripper, sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOff, sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOn, sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOff, sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOn, cl_move_group_interface::CbAttachObject, cl_move_base_z::CbNavigateNextWaypoint, cl_move_group_interface::CbDetachObject, smacc::SmaccClientBehavior, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, and cl_ros_timer::CbTimer.
Definition at line 34 of file smacc_client_behavior_base.h.
References dispose(), executeOnEntry(), executeOnExit(), getCurrentState(), onOrthogonalAllocation(), and postEvent().
Referenced by executeOnExit(), and smacc::SmaccAsyncClientBehavior::executeOnExit().
{};
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject >
void smacc::ISmaccClientBehavior::onOrthogonalAllocation () [private]
Definition at line 73 of file smacc_client_behavior_impl.h.
Referenced by onExit().
{}
postEvent() [1/2]
template<typename EventType >
void smacc::ISmaccClientBehavior::postEvent (const EventType & ev) [protected]
Definition at line 15 of file smacc_client_behavior_impl.h.
References smacc::CURRENT_STATE, smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
        stateMachine_->postEvent(ev,
      EventLifeTime::CURRENT_STATE);
    }
}
postEvent() [2/2]
template<typename EventType >
void smacc::ISmaccClientBehavior::postEvent () [protected]
Definition at line 28 of file smacc_client_behavior_impl.h.
References smacc::CURRENT_STATE, and stateMachine_.
Referenced by onExit(), and cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent().
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
         
        stateMachine_->template postEvent<EventType>(
      EventLifeTime::CURRENT_STATE);
    }
}
requiresClient()
template<typename SmaccClientType >
void smacc::ISmaccClientBehavior::requiresClient (SmaccClientType *& storage)
Definition at line 54 of file smacc_client_behavior_impl.h.
References currentOrthogonal, and smacc::ISmaccOrthogonal::requiresClient().
Referenced by cl_ros_timer::CbTimer::onEntry(), sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbOpenGripper::onEntry(), sm_fetch_two_table_pick_n_place_1::cl_gripper::CbOpenGripper::onEntry(), sm_moveit_screw_loop::cl_gripper::CbOpenGripper::onEntry(), cl_ros_timer::CbTimerCountdownOnce::onEntry(), sm_fetch_two_table_pick_n_place_1::cl_gripper::CbCloseGripper::onEntry(), sm_moveit_screw_loop::cl_gripper::CbCloseGripper::onEntry(), sm_fetch_six_table_pick_n_sort_1::cl_gripper::CbCloseGripper::onEntry(), cl_ros_timer::CbTimerCountdownLoop::onEntry(), sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOn::onEntry(), sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOn::onEntry(), sm_dance_bot::cl_led::CbLEDOff::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOff::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOn::onEntry(), sm_ridgeback_floor_coverage_dynamic_1::cl_led::CbLEDOff::onEntry(), sm_ridgeback_floor_coverage_static_1::cl_led::CbLEDOff::onEntry(), sm_dance_bot::cl_led::CbLEDOn::onEntry(), cl_keyboard::CbDefaultKeyboardBehavior::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_base_z::CbNavigateNextWaypoint::onEntry(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot::cl_string_publisher::CbStringPublisher::onEntry(), sm_ridgeback_floor_coverage_static_1::cl_string_publisher::CbStringPublisher::onEntry(), sm_ridgeback_floor_coverage_dynamic_1::cl_string_publisher::CbStringPublisher::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveJoints::onEntry(), cl_move_group_interface::CbMoveNamedTarget::onEntry(), cl_move_group_interface::CbMoveCartesianRelative::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_ros_publisher::CbPublishOnce< RosMsgType >::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_ros_publisher::CbDefaultPublishLoop::onEntry(), cl_move_base_z::CbNavigateGlobalPosition::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< sm_dance_bot_strikes_back::cl_lidar::ClLidarSensor >::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), and cl_move_base_z::CbUndoPathBackwards::onExit().
{
    currentOrthogonal->requiresClient(storage);
}
requiresComponent()
template<typename SmaccComponentType >
void smacc::ISmaccClientBehavior::requiresComponent (SmaccComponentType *& storage)
Definition at line 60 of file smacc_client_behavior_impl.h.
References smacc::ISmaccStateMachine::requiresComponent(), and stateMachine_.
Referenced by cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), and cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry().
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("Cannot use the requiresComponent funcionality before asigning the client behavior to an
       orthogonal. Try using the OnEntry method to capture required components.");
    }
    else
    {
        stateMachine_->requiresComponent(storage);
    }
}
runtimeConfigure()
void smacc::ISmaccClientBehavior::runtimeConfigure () [protected], [virtual]
Definition at line 21 of file smacc_client_behavior_base.cpp.
References getName().
    {
        ROS_DEBUG("[%s] Default empty SmaccClientBehavior runtimeConfigure", this->
      getName().c_str());
    }
Friends And Related Function Documentation
ISmaccOrthogonal
friend class ISmaccOrthogonal [friend]
Definition at line 64 of file smacc_client_behavior_base.h.
ISmaccState
friend class ISmaccState [friend]
Definition at line 63 of file smacc_client_behavior_base.h.
Member Data Documentation
currentOrthogonal
smacc::ISmaccOrthogonal* smacc::ISmaccClientBehavior::currentOrthogonal [private]
Definition at line 61 of file smacc_client_behavior_base.h.
Referenced by requiresClient().
currentState
ISmaccState* smacc::ISmaccClientBehavior::currentState [private]
Definition at line 59 of file smacc_client_behavior_base.h.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), getCurrentState(), and ISmaccClientBehavior().
stateMachine_
ISmaccStateMachine* smacc::ISmaccClientBehavior::stateMachine_ [private]
Definition at line 56 of file smacc_client_behavior_base.h.
Referenced by getStateMachine(), ISmaccClientBehavior(), postEvent(), and requiresComponent().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_client_behavior_base.h
smacc/include/smacc/impl/smacc_client_behavior_impl.h
smacc/src/smacc/smacc_client_behavior_base.cpp