sm_fetch_two_table_pick_n_place_1::place_states::StPlaceRetreat Struct Reference
#include <st_place_retreat.h>
Public Types
typedef mpl::list< Transition< MoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StPlaceRetreat, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_place_retreat.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<MoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StPlaceRetreat, ABORT> > sm_fetch_two_table_pick_n_place_1::place_states::StPlaceRetreat::reactions
Definition at line 16 of file st_place_retreat.h.
Member Function Documentation
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::place_states::StPlaceRetreat::runtimeConfigure () [inline]
Definition at line 26 of file st_place_retreat.h.
References cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StPlaceRetreat, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StPlaceRetreat::throwSequenceFinishedEvent, this);
    }
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::place_states::StPlaceRetreat::staticConfigure () [inline], [static]
Definition at line 19 of file st_place_retreat.h.
    {
        geometry_msgs::Vector3 offset;
        offset.z = 0.15;
        configure_orthogonal<OrArm, CbMoveCartesianRelative>(offset);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/place_states/st_place_retreat.h