sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture Struct Reference
#include <st_navigation_posture.h>
Public Types
typedef mpl::list< Transition< EvCbFailure< CbMoveKnownState, OrArm >, StNavigationPosture, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onSuccessFullExit ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 7 of file st_navigation_posture.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbFailure<CbMoveKnownState, OrArm>, StNavigationPosture, ABORT> > sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::reactions
Definition at line 15 of file st_navigation_posture.h.
Member Function Documentation
onSuccessFullExit()
void sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::onSuccessFullExit () [inline]
Definition at line 31 of file st_navigation_posture.h.
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::nextCube(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StNavigationPosture, SS >::throwSequenceFinishedEvent().
Referenced by runtimeConfigure().
            {
                ClPerceptionSystem *perceptionSystem;
                this->requiresClient(perceptionSystem);
                perceptionSystem->nextCube();
                this->throwSequenceFinishedEvent();
            }
runtimeConfigure()
void sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::runtimeConfigure () [inline]
Definition at line 23 of file st_navigation_posture.h.
References onSuccessFullExit(), and smacc::ISmaccState::requiresClient().
            {
                ros::WallDuration(2).sleep();
                ClMoveGroup *moveGroupClient;
                this->requiresClient(moveGroupClient);
                moveGroupClient->onMotionExecutionSuccedded(&
      StNavigationPosture::onSuccessFullExit, this);
            }
staticConfigure()
static void sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::staticConfigure () [inline], [static]
Definition at line 18 of file st_navigation_posture.h.
            {
                configure_orthogonal<OrArm, CbMoveKnownState>("sm_fetch_six_table_pick_n_sort_1", "
      config/manipulation/known_states/nav_posture.yaml");
            }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/states/place_states/st_navigation_posture.h