sm_moveit_wine_serve::pick_states::StGraspRetreat Struct Reference
#include <st_grasp_retreat.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbMoveCartesianRelative2, OrArm >, StNavigationPosture, SUCCESS >, Transition< EvCbFailure< CbMoveCartesianRelative2, OrArm >, StGraspRetreat, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit (SUCCESS)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_grasp_retreat.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbMoveCartesianRelative2, OrArm>, StNavigationPosture, SUCCESS>, Transition<EvCbFailure<CbMoveCartesianRelative2, OrArm>, StGraspRetreat, ABORT> > sm_moveit_wine_serve::pick_states::StGraspRetreat::reactions
Definition at line 17 of file st_grasp_retreat.h.
Member Function Documentation
onEntry()
void sm_moveit_wine_serve::pick_states::StGraspRetreat::onEntry () [inline]
Definition at line 42 of file st_grasp_retreat.h.
    {
        
    }
onExit()
void sm_moveit_wine_serve::pick_states::StGraspRetreat::onExit (SUCCESS) [inline]
Definition at line 47 of file st_grasp_retreat.h.
References smacc::ISmaccState::requiresClient().
    {
        ClMoveGroup *moveGroup;
        this->requiresClient(moveGroup);
        
        moveGroup->getComponent<CpConstraintTableWorkspaces>()->setBigTableCollisionVolume();
    }
runtimeConfigure()
void sm_moveit_wine_serve::pick_states::StGraspRetreat::runtimeConfigure () [inline]
Definition at line 25 of file st_grasp_retreat.h.
References smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StGraspRetreat, SS >::throwSequenceFinishedEvent().
    {
        /*for the case of abor/retry cartesian retreat --*/
        ClMoveGroup *moveGroup;
        this->requiresClient(moveGroup);
        moveGroup->getComponent<CpConstraintTableWorkspaces>()->disableTableCollisionVolume();
        ros::Duration(1).sleep();
        auto moveCartesianRelative = this->getOrthogonal<OrArm>()
                                         ->getClientBehavior<CbMoveCartesianRelative2>();
        moveCartesianRelative->offset_.z = 0.15;
        moveGroup->onMotionExecutionSuccedded(&
      StGraspRetreat::throwSequenceFinishedEvent, this);
    }
staticConfigure()
static void sm_moveit_wine_serve::pick_states::StGraspRetreat::staticConfigure () [inline], [static]
Definition at line 20 of file st_grasp_retreat.h.
    {
        configure_orthogonal<OrArm, CbMoveCartesianRelative2>("map", "gripper_link");
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_wine_serve/include/sm_moveit_wine_serve/states/pick_states/st_grasp_retreat.h