sm_dance_bot::StNavigateForward1 Struct Reference
#include <st_navigate_forward_1.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, StRotateDegrees2 >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StNavigateToWaypointsX, ABORT >, Transition< EvActionPreempted< ClMoveBaseZ, OrNavigation >, StNavigateToWaypointsX, PREEMPT > > reactions
Public Member Functions
void runtimeConfigure ()
void onActionClientSucceeded (ClMoveBaseZ::ResultConstPtr &msg)
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_navigate_forward_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, StRotateDegrees2>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StNavigateToWaypointsX, ABORT>, Transition<EvActionPreempted<ClMoveBaseZ, OrNavigation>, StNavigateToWaypointsX, PREEMPT> > sm_dance_bot::StNavigateForward1::reactions
Definition at line 16 of file st_navigate_forward_1.h.
Member Function Documentation
onActionClientSucceeded()
void sm_dance_bot::StNavigateForward1::onActionClientSucceeded (ClMoveBaseZ::ResultConstPtr & msg) [inline]
Definition at line 35 of file st_navigate_forward_1.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO_STREAM(" [Callback SmaccSignal] Success Detected from StAquireSensors (connected to client
       signal), result data: " << *msg);
  }
runtimeConfigure()
void sm_dance_bot::StNavigateForward1::runtimeConfigure () [inline]
Definition at line 26 of file st_navigate_forward_1.h.
References onActionClientSucceeded(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and smacc::ISmaccState::requiresClient().
  {
    ClMoveBaseZ *move_base_action_client;
    this->requiresClient(move_base_action_client);
    // we careful with the lifetime of the callbac, us a scoped connection if is not forever
    move_base_action_client->onSucceeded(&
      StNavigateForward1::onActionClientSucceeded, this);
  }
staticConfigure()
static void sm_dance_bot::StNavigateForward1::staticConfigure () [inline], [static]
Definition at line 19 of file st_navigate_forward_1.h.
  {
    configure_orthogonal<OrNavigation, CbNavigateForward>(1);
    configure_orthogonal<OrLED, CbLEDOff>();
    configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/states/st_navigate_forward_1.h