moveit_z_client::ClMoveGroup Class Reference
#include <cl_movegroup.h>
Public Member Functions
ClMoveGroup (std::string groupName)
virtual ~ClMoveGroup ()
void postEventMotionExecutionSucceded ()
void postEventMotionExecutionFailed ()
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionSuccedded (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionFailed (TCallback callback, T *object)
Public Attributes
moveit::planning_interface::MoveGroupInterface moveGroupClientInterface
moveit::planning_interface::PlanningSceneInterface planningSceneInterface
Private Attributes
std::function< void()> postEventMotionExecutionSucceded_
std::function< void()> postEventMotionExecutionFailed_
smacc::SmaccSignal< void()> onSucceded_
smacc::SmaccSignal< void()> onFailed_
Additional Inherited Members
Detailed Description
Definition at line 61 of file cl_movegroup.h.
Constructor & Destructor Documentation
ClMoveGroup()
moveit_z_client::ClMoveGroup::ClMoveGroup (std::string groupName)
Definition at line 11 of file cl_movegroup.cpp.
    : moveGroupClientInterface(groupName)
{
    ros::WallDuration(10.0).sleep();
}
 ClMoveGroup()
moveit_z_client::ClMoveGroup::~ClMoveGroup () [virtual]
Definition at line 17 of file cl_movegroup.cpp.
{
}
Member Function Documentation
configureEventSourceTypes()
template<typename TObjectTag , typename TDerived >
void moveit_z_client::ClMoveGroup::configureEventSourceTypes () [inline]
Definition at line 86 of file cl_movegroup.h.
  {
    postEventMotionExecutionSucceded_ = [=]() {
      this->onSucceded_();
      this->postEvent<MoveGroupMotionExecutionSucceded<TDerived, TObjectTag>>();
    };
    postEventMotionExecutionFailed_ = [=]() {
      this->onFailed_();
      this->postEvent<MoveGroupMotionExecutionFailed<TDerived, TObjectTag>>();
    };
  }
onMotionExecutionFailed()
template<typename TCallback , typename T >
boost::signals2::connection moveit_z_client::ClMoveGroup::onMotionExecutionFailed (TCallback callback, T * object) [inline]
Definition at line 106 of file cl_movegroup.h.
Referenced by sm_moveit::SS1::SsPickObject::runtimeConfigure(), sm_moveit_3::SS1::SsPickObject::runtimeConfigure(), and sm_moveit_2::SS1::SsPickObject::runtimeConfigure().
  {
    return this->getStateMachine()->createSignalConnection(
      onFailed_, callback, object);
  }
onMotionExecutionSuccedded()
template<typename TCallback , typename T >
boost::signals2::connection moveit_z_client::ClMoveGroup::onMotionExecutionSuccedded (TCallback callback, T * object) [inline]
Definition at line 100 of file cl_movegroup.h.
Referenced by sm_moveit_4::place_states::StNavigationPosture::runtimeConfigure(), sm_moveit::pick_states::StNavigationPosture::runtimeConfigure(), sm_moveit_4::pick_states::StNavigationPosture::runtimeConfigure(), sm_moveit::place_states::StPlaceRetreat::runtimeConfigure(), sm_moveit_2::place_states::StPlaceRetreat::runtimeConfigure(), sm_moveit_2::place_states::StPlaceApproach::runtimeConfigure(), sm_moveit_3::place_states::StPlaceApproach::runtimeConfigure(), sm_moveit_3::place_states::StPlaceRetreat::runtimeConfigure(), sm_moveit::place_states::StPlaceApproach::runtimeConfigure(), sm_moveit_2::pick_states::StNavigationPosture::runtimeConfigure(), and sm_moveit_3::pick_states::StNavigationPosture::runtimeConfigure().
  {
    return this->getStateMachine()->createSignalConnection(
      onSucceded_, callback, object);
  }
postEventMotionExecutionFailed()
void moveit_z_client::ClMoveGroup::postEventMotionExecutionFailed ()
Definition at line 27 of file cl_movegroup.cpp.
References postEventMotionExecutionFailed_.
Referenced by moveit_z_client::CbMoveJoints::moveJoints(), moveit_z_client::CbMoveEndEffectorRelative::moveRelative(), moveit_z_client::CbMoveCartesianRelative::moveRelativeCartesian(), and moveit_z_client::CbMoveEndEffector::moveToAbsolutePose().
{
    ROS_INFO("[ClMoveGroup] Post Motion Failure Event");
    postEventMotionExecutionFailed_();
}
postEventMotionExecutionSucceded()
void moveit_z_client::ClMoveGroup::postEventMotionExecutionSucceded ()
Definition at line 21 of file cl_movegroup.cpp.
References postEventMotionExecutionSucceded_.
Referenced by moveit_z_client::CbMoveJoints::moveJoints(), moveit_z_client::CbMoveEndEffectorRelative::moveRelative(), moveit_z_client::CbMoveCartesianRelative::moveRelativeCartesian(), and moveit_z_client::CbMoveEndEffector::moveToAbsolutePose().
{
    ROS_INFO("[ClMoveGroup] Post Motion Success Event");
    postEventMotionExecutionSucceded_();
}
Member Data Documentation
moveGroupClientInterface
moveit::planning_interface::MoveGroupInterface moveit_z_client::ClMoveGroup::moveGroupClientInterface
Definition at line 74 of file cl_movegroup.h.
Referenced by moveit_z_client::CbMoveNamedTarget::getNamedTargetValues(), moveit_z_client::CbMoveEndEffector::onEntry(), moveit_z_client::CbMoveJoints::onEntry(), moveit_z_client::CbMoveEndEffectorRelative::onEntry(), moveit_z_client::CbMoveNamedTarget::onEntry(), and moveit_z_client::CbMoveCartesianRelative::onEntry().
onFailed_
smacc::SmaccSignal<void()> moveit_z_client::ClMoveGroup::onFailed_ [private]
Definition at line 68 of file cl_movegroup.h.
onSucceded_
smacc::SmaccSignal<void()> moveit_z_client::ClMoveGroup::onSucceded_ [private]
Definition at line 67 of file cl_movegroup.h.
planningSceneInterface
moveit::planning_interface::PlanningSceneInterface moveit_z_client::ClMoveGroup::planningSceneInterface
Definition at line 76 of file cl_movegroup.h.
Referenced by sm_moveit_3::cl_perception_system::ClPerceptionSystem::initialize(), moveit_z_client::CbMoveEndEffector::moveToAbsolutePose(), and sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::onInitialize().
postEventMotionExecutionFailed_
std::function<void()> moveit_z_client::ClMoveGroup::postEventMotionExecutionFailed_ [private]
Definition at line 65 of file cl_movegroup.h.
Referenced by postEventMotionExecutionFailed().
postEventMotionExecutionSucceded_
std::function<void()> moveit_z_client::ClMoveGroup::postEventMotionExecutionSucceded_ [private]
Definition at line 64 of file cl_movegroup.h.
Referenced by postEventMotionExecutionSucceded().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/cl_movegroup.h
smacc_client_library/moveit_z_client/src/moveit_z_client/cl_movegroup.cpp