sm_moveit_4::cl_perception_system::ClPerceptionSystem Class Reference
#include <cl_perception_system.h>
Public Member Functions
ClPerceptionSystem ()
virtual ~ClPerceptionSystem ()
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
virtual void initialize () override
void identifyCubeColorsByNames (const std::vector< std::string > &linknames)
void simulatedLinkStateCallback (const gazebo_msgs::LinkStates &linksmsg)
void propagateLinkStatesToTf (const gazebo_msgs::LinkStates &linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > &transforms)
void nextCube ()
void retryCubeAfterFail ()
virtual void update () override
RobotProcessStatus getCurrentTable ()
geometry_msgs::PoseStamped decidePickCubePose ()
geometry_msgs::PoseStamped decidePlacePose ()
Public Attributes
ros::Time startTime
ros::Duration readDelay
int decissionsCount
int currentCube = 0
tf::TransformListener tfListener_
tf::TransformBroadcaster tfBroadcaster_
ros::Subscriber gazeboStateSubscriber_
ros::Time lastUpdateStamp_
ros::Duration updatePeriod_
bool tableCollision_
bool cubeCollision_
moveit::planning_interface::PlanningSceneInterface * planningSceneInterface_
std::vector< CubeInfo > cubeInfos_
std::vector< TableInfo > tablesInfo_ = {{`yellow`}, {`white`}, {`purple`}, {`none`}, {`red`}, {`green`}}
std::vector< cl_move_base_z::Pose * > tablePoses_
Additional Inherited Members
Detailed Description
Definition at line 39 of file cl_perception_system.h.
Constructor & Destructor Documentation
ClPerceptionSystem()
sm_moveit_4::cl_perception_system::ClPerceptionSystem::ClPerceptionSystem () [inline]
Definition at line 63 of file cl_perception_system.h.
            {
                startTime = ros::Time::now();
                readDelay = ros::Duration(5);
                decissionsCount = 0;
            }
 ClPerceptionSystem()
virtual sm_moveit_4::cl_perception_system::ClPerceptionSystem::~ClPerceptionSystem () [inline], [virtual]
Definition at line 70 of file cl_perception_system.h.
            {
            }
Member Function Documentation
configureEventSourceTypes()
template<typename TObjectTag , typename TDerived >
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::configureEventSourceTypes () [inline]
Definition at line 75 of file cl_perception_system.h.
            {
                int TABLE_COUNT = 6;
                for (int i = 0; i < TABLE_COUNT; i++)
                {
                    auto tablepose = this->createComponent<cl_move_base_z::Pose, TDerived, TObjectTag>("
      table_" + std::to_string(i));
                    tablePoses_.push_back(tablepose);
                }
            }
decidePickCubePose()
geometry_msgs::PoseStamped sm_moveit_4::cl_perception_system::ClPerceptionSystem::decidePickCubePose () [inline]
Definition at line 264 of file cl_perception_system.h.
            {
                geometry_msgs::PoseStamped ret;
                return ret;
            }
decidePlacePose()
geometry_msgs::PoseStamped sm_moveit_4::cl_perception_system::ClPerceptionSystem::decidePlacePose () [inline]
Definition at line 270 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), and cl_move_base_z::Pose::toPoseMsg().
            {
                cl_move_base_z::ClMoveBaseZ *moveBaseclient;
                this->requiresClient(moveBaseclient);
                auto pose = moveBaseclient->getComponent<
      cl_move_base_z::Pose>();
                auto currentPose = pose->toPoseMsg();
                geometry_msgs::PoseStamped ret;
                return ret;
            }
getCurrentTable()
RobotProcessStatus sm_moveit_4::cl_perception_system::ClPerceptionSystem::getCurrentTable () [inline]
Definition at line 248 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), sm_moveit_4::cl_perception_system::ONTHEWAY, sm_moveit_4::cl_perception_system::TABLE0, sm_moveit_4::cl_perception_system::TABLE1, and cl_move_base_z::Pose::toPoseMsg().
            {
                cl_move_base_z::ClMoveBaseZ *moveBaseclient;
                this->requiresClient(moveBaseclient);
                auto pose = moveBaseclient->getComponent<
      cl_move_base_z::Pose>();
                auto currentPose = pose->toPoseMsg();
                int tableIndex = 0;
                if (currentPose.position.x > -0.2)
                    return RobotProcessStatus::TABLE0;
                else if (currentPose.position.x < -0.8)
                    return RobotProcessStatus::TABLE1;
                else
                    return RobotProcessStatus::ONTHEWAY;
            }
identifyCubeColorsByNames()
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::identifyCubeColorsByNames (const std::vector< std::string > & linknames) [inline]
Definition at line 98 of file cl_perception_system.h.
References sm_moveit_4::cl_perception_system::CubeInfo::color, and sm_moveit_4::cl_perception_system::CubeInfo::dstTableInfo_.
            {
                if (cubeInfos_.size() == 0)
                {
                    std::vector<std::string> strs;
                    for (auto &linkname : linknames)
                    {
                        if (linkname.find("cube") != std::string::npos)
                        {
                            strs.clear();
                            boost::split(strs, linkname, boost::is_any_of("_:")); // demo_cube_green::link
                            CubeInfo cubeinfo;
                            cubeinfo.color = strs[2];
                            cubeinfo.dstTableInfo_ = &(*(std::find_if(this->
      tablesInfo_.begin(), this->tablesInfo_.end(),
                                                                      [&](auto &ti) { return ti.
      targetColor_ == cubeinfo.color; })));
                            cubeInfos_.push_back(cubeinfo);
                        }
                    }
                }
            }
initialize()
virtual void sm_moveit_4::cl_perception_system::ClPerceptionSystem::initialize () [inline], [override], [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 85 of file cl_perception_system.h.
References moveit_z_client::ClMoveGroup::planningSceneInterface, and simulatedLinkStateCallback().
            {
                ros::NodeHandle nh;
                gazeboStateSubscriber_ =
                    nh.subscribe("/gazebo/link_states", 1, &
      ClPerceptionSystem::simulatedLinkStateCallback, this);
                moveit_z_client::ClMoveGroup *movegroupclient;
                requiresClient(movegroupclient);
                planningSceneInterface_ = &movegroupclient->
      planningSceneInterface;
                tableCollision_ = true;
                updatePeriod_ = ros::Duration(0.25);
            }
nextCube()
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::nextCube () [inline]
Definition at line 232 of file cl_perception_system.h.
            {
                currentCube = (currentCube + 1) % 3;
                ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
            }
propagateLinkStatesToTf()
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::propagateLinkStatesToTf (const gazebo_msgs::LinkStates & linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > & transforms) [inline]
Definition at line 197 of file cl_perception_system.h.
            {
                transforms.clear();
                int i = 0;
                std::vector<geometry_msgs::Pose> filteredLinkPoses;
                for (auto &b : linksmsg.pose)
                {
                    auto linkname = linksmsg.name[i];
                    if (linkname.find(linkNameFilter) != std::string::npos)
                        filteredLinkPoses.push_back(b);
                    i++;
                }
                i = 0;
                for (auto &cubepose : filteredLinkPoses)
                {
                    tf::Pose tfpose;
                    tf::poseMsgToTF(cubepose, tfpose);
                    tf::StampedTransform transform;
                    transform.setOrigin(tfpose.getOrigin());
                    transform.setRotation(tfpose.getRotation());
                    transform.frame_id_ = globalFrame;
                    transform.child_frame_id_ = objectPrefix + std::to_string(i);
                    transform.stamp_ = ros::Time::now();
                    tfBroadcaster_.sendTransform(transform);
                    i++;
                    transforms.push_back(transform);
                }
            }
retryCubeAfterFail()
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::retryCubeAfterFail () [inline]
Definition at line 238 of file cl_perception_system.h.
            {
                currentCube = (currentCube - 1) % 3;
                ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
            }
simulatedLinkStateCallback()
void sm_moveit_4::cl_perception_system::ClPerceptionSystem::simulatedLinkStateCallback (const gazebo_msgs::LinkStates & linksmsg) [inline]
Definition at line 121 of file cl_perception_system.h.
Referenced by initialize().
            {
                identifyCubeColorsByNames(linksmsg.name);
                std::vector<tf::StampedTransform> cubeTransforms;
                this->propagateLinkStatesToTf(linksmsg, "cube", "cube_", "map",
      cubeTransforms);
                std::vector<tf::StampedTransform> tableTransforms;
                this->propagateLinkStatesToTf(linksmsg, "table", "table_", "map",
      tableTransforms);
                auto ellapsed = ros::Time::now() - this->lastUpdateStamp_;
                if (ellapsed > updatePeriod_)
                {
                    ROS_DEBUG("Updating planning scene perception");
                    auto attachedObjects = planningSceneInterface_->
      getAttachedObjects();
                    bool hasCubeAttached = false;
                    for (auto &k : attachedObjects)
                    {
                        if (k.first.find("cube") != std::string::npos)
                        {
                            hasCubeAttached = true;
                            break;
                        }
                    }
                    if (tableCollision_ && !hasCubeAttached)
                    {
                        std::vector<moveit_msgs::CollisionObject> collisionObjects(tableTransforms.size());
                        std::vector<std::string> removeCollisionObjectNames(tableTransforms.size());
                        auto thickness = 0.12;
                        for (int i = 0; i < tableTransforms.size(); i++)
                        {
                            auto &tableTransf = tableTransforms[i];
                            auto &pos = tableTransf.getOrigin();
                            std::string tablename = "table_" + std::to_string(i);
                            removeCollisionObjectNames[i] = tablename;
                            moveit_msgs::CollisionObject &collision = collisionObjects[i];
                            collision.operation = moveit_msgs::CollisionObject::ADD;
                            collision.id = tablename;
                            collision.primitives.resize(1);
                            collision.primitives[0].type = collision.primitives[0].BOX;
                            collision.primitives[0].dimensions.resize(3);
                            collision.primitives[0].dimensions[0] = 1.2;
                            collision.primitives[0].dimensions[1] = 1.3;
                            collision.primitives[0].dimensions[2] = 0.001 + thickness;
                            /* Define the pose of the table. */
                            collision.primitive_poses.resize(1);
                            collision.primitive_poses[0].position.x = pos[0];
                            collision.primitive_poses[0].position.y = pos[1];
                            collision.primitive_poses[0].position.z = 0.7 - thickness * 0.5;
                            collision.primitive_poses[0].orientation.w = 1.0;
                            collision.header.frame_id = tableTransf.frame_id_;
                            collision.header.stamp = tableTransf.stamp_;
                        }
                        //
      this->planningSceneInterface_->removeCollisionObjects(removeCollisionObjectNames);
                        this->planningSceneInterface_->addCollisionObjects(
      collisionObjects);
                    }
                    if (cubeCollision_ && !hasCubeAttached)
                    {
                        // for i, cube_transf in enumerate(cube_transforms):
                        // #self.planning_scene.removeCollisionObject("cube_" + str(i))
                        // pos = cube_transf[0]
                        // self.planning_scene.addCube(
                        // "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                        // #self.cube_collision = False
                    }
                }
            }
update()
virtual void sm_moveit_4::cl_perception_system::ClPerceptionSystem::update () [inline], [override], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 244 of file cl_perception_system.h.
            {
            }
Member Data Documentation
cubeCollision_
bool sm_moveit_4::cl_perception_system::ClPerceptionSystem::cubeCollision_
Definition at line 54 of file cl_perception_system.h.
cubeInfos_
std::vector<CubeInfo> sm_moveit_4::cl_perception_system::ClPerceptionSystem::cubeInfos_
Definition at line 58 of file cl_perception_system.h.
Referenced by sm_moveit_4::StInitialForward::runtimeConfigure().
currentCube
int sm_moveit_4::cl_perception_system::ClPerceptionSystem::currentCube = 0
Definition at line 46 of file cl_perception_system.h.
decissionsCount
int sm_moveit_4::cl_perception_system::ClPerceptionSystem::decissionsCount
Definition at line 45 of file cl_perception_system.h.
gazeboStateSubscriber_
ros::Subscriber sm_moveit_4::cl_perception_system::ClPerceptionSystem::gazeboStateSubscriber_
Definition at line 50 of file cl_perception_system.h.
lastUpdateStamp_
ros::Time sm_moveit_4::cl_perception_system::ClPerceptionSystem::lastUpdateStamp_
Definition at line 51 of file cl_perception_system.h.
planningSceneInterface_
moveit::planning_interface::PlanningSceneInterface* sm_moveit_4::cl_perception_system::ClPerceptionSystem::planningSceneInterface_
Definition at line 55 of file cl_perception_system.h.
readDelay
ros::Duration sm_moveit_4::cl_perception_system::ClPerceptionSystem::readDelay
Definition at line 43 of file cl_perception_system.h.
startTime
ros::Time sm_moveit_4::cl_perception_system::ClPerceptionSystem::startTime
Definition at line 42 of file cl_perception_system.h.
tableCollision_
bool sm_moveit_4::cl_perception_system::ClPerceptionSystem::tableCollision_
Definition at line 53 of file cl_perception_system.h.
tablePoses_
std::vector<cl_move_base_z::Pose *> sm_moveit_4::cl_perception_system::ClPerceptionSystem::tablePoses_
Definition at line 61 of file cl_perception_system.h.
tablesInfo_
std::vector<TableInfo> sm_moveit_4::cl_perception_system::ClPerceptionSystem::tablesInfo_ = {{`yellow`}, {`white`}, {`purple`}, {`none`}, {`red`}, {`green`}}
Definition at line 59 of file cl_perception_system.h.
tfBroadcaster_
tf::TransformBroadcaster sm_moveit_4::cl_perception_system::ClPerceptionSystem::tfBroadcaster_
Definition at line 49 of file cl_perception_system.h.
tfListener_
tf::TransformListener sm_moveit_4::cl_perception_system::ClPerceptionSystem::tfListener_
Definition at line 48 of file cl_perception_system.h.
updatePeriod_
ros::Duration sm_moveit_4::cl_perception_system::ClPerceptionSystem::updatePeriod_
Definition at line 52 of file cl_perception_system.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_moveit_4/include/sm_moveit_4/clients/perception_system_client/cl_perception_system.h