sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception Class Reference
#include <cp_simulated_gazebo_perception.h>
Public Member Functions
void setSafeArmMotionToAvoidCubeCollisions ()
void unsetSafeArmMotionToAvoidCubeCollisions ()
virtual void onInitialize () override
void simulatedLinkStateCallback (const gazebo_msgs::LinkStates &linksmsg)
void additional (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject &collision, ros::Time time)
void lateralBox (std::vector< moveit_msgs::CollisionObject > &collisions, ros::Time time)
void createVirtualFloorCollisionBox (std::vector< moveit_msgs::CollisionObject > &collisions, ros::Time time)
void identifyCubeColorsByNames (const std::vector< std::string > &linknames)
void propagateLinkStatesToTf (const gazebo_msgs::LinkStates &linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > &transforms)
Public Attributes
double safeTableHeightOffsetForCubeCollisions = 0
Private Attributes
ros::Time startTime
ros::Duration readDelay
ros::Time lastUpdateStamp_
ros::Duration updatePeriod_
bool tableCollision_
bool cubeCollision_
moveit::planning_interface::PlanningSceneInterface * planningSceneInterface_
ClMoveGroup * movegroupclient_
tf::TransformListener tfListener_
tf::TransformBroadcaster tfBroadcaster_
ros::Subscriber gazeboStateSubscriber_
Additional Inherited Members
Detailed Description
Definition at line 25 of file cp_simulated_gazebo_perception.h.
Member Function Documentation
additional()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::additional (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject & collision, ros::Time time) [inline]
Definition at line 151 of file cp_simulated_gazebo_perception.h.
            {
                collision.operation = moveit_msgs::CollisionObject::ADD;
                collision.id = id;
                collision.primitives.resize(1);
                collision.primitives[0].type = collision.primitives[0].BOX;
                collision.primitives[0].dimensions.resize(3);
                collision.primitives[0].dimensions[0] = xl;
                collision.primitives[0].dimensions[1] = yl;
                collision.primitives[0].dimensions[2] = zl ;
                collision.primitive_poses.resize(1);
                collision.primitive_poses[0].position.x = x;
                collision.primitive_poses[0].position.y = y;
                collision.primitive_poses[0].position.z = z;
                collision.primitive_poses[0].orientation.w = 1.0;
                collision.header.frame_id = frameid;
                collision.header.stamp = time;
            }
createVirtualFloorCollisionBox()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::createVirtualFloorCollisionBox (std::vector< moveit_msgs::CollisionObject > & collisions, ros::Time time) [inline]
Definition at line 184 of file cp_simulated_gazebo_perception.h.
            {
                moveit_msgs::CollisionObject floor;
                //additional(0, 0, -0.1, 8, 8, 0.05, "floor", "map", floor, time);
                //collisions.push_back(floor);
            }
identifyCubeColorsByNames()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::identifyCubeColorsByNames (const std::vector< std::string > & linknames) [inline]
Definition at line 194 of file cp_simulated_gazebo_perception.h.
References sm_moveit_4::cl_perception_system::CubeInfo::color, sm_moveit_4::cl_perception_system::CpSceneState::cubeInfos_, sm_moveit_4::cl_perception_system::CubeInfo::dstTableInfo_, and sm_moveit_4::cl_perception_system::CpSceneState::tablesInfo_.
            {
                CpSceneState *scene;
                this->requiresComponent(scene);
                if (scene->cubeInfos_.front().color == "")
                {
                    std::vector<std::string> strs;
                    int i=0;
                    for (auto &linkname : linknames)
                    {
                        if (linkname.find("cube") != std::string::npos)
                        {
                            strs.clear();
                            boost::split(strs, linkname, boost::is_any_of("_:")); // demo_cube_green::link
                            CubeInfo& cubeinfo = scene->cubeInfos_[i++];
                            cubeinfo.color = strs[2];
                            cubeinfo.dstTableInfo_ = &(*(std::find_if(scene->tablesInfo_.begin(), scene->
      tablesInfo_.end(),
                                                                      [&](auto &ti) { return ti.
      associatedCubeColor_ == cubeinfo.color; })));
                        }
                    }
                }
            }
lateralBox()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::lateralBox (std::vector< moveit_msgs::CollisionObject > & collisions, ros::Time time) [inline]
Definition at line 174 of file cp_simulated_gazebo_perception.h.
            {
                moveit_msgs::CollisionObject box;
                additional(0, -0.28, 0.3, 1.0, 0.01, 0.6, "right", "base_link", box, time);
                collisions.push_back(box);
                additional(0, 0.28, 0.3, 1.0, 0.01, 0.6, "left", "base_link", box, time);
                collisions.push_back(box);
            }
onInitialize()
virtual void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::onInitialize () [inline], [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 57 of file cp_simulated_gazebo_perception.h.
References moveit_z_client::ClMoveGroup::planningSceneInterface, and simulatedLinkStateCallback().
            {
                this->requiresClient(movegroupclient_);
                planningSceneInterface_ = &
      movegroupclient_->planningSceneInterface;
                
                tableCollision_ = true;
                updatePeriod_ = ros::Duration(0.25);
                startTime = ros::Time::now();
                
                // order is important, to avoid "preemption" of the callback before it is initialized
                ros::NodeHandle nh;
                gazeboStateSubscriber_ =
                    nh.subscribe("/gazebo/link_states", 1, &
      CpSimulatedGazeboPerception::simulatedLinkStateCallback
      , this);
            }
propagateLinkStatesToTf()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::propagateLinkStatesToTf (const gazebo_msgs::LinkStates & linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > & transforms) [inline]
Definition at line 220 of file cp_simulated_gazebo_perception.h.
            {
                transforms.clear();
                int i = 0;
                std::vector<geometry_msgs::Pose> filteredLinkPoses;
                for (auto &b : linksmsg.pose)
                {
                    auto linkname = linksmsg.name[i];
                    if (linkname.find(linkNameFilter) != std::string::npos)
                        filteredLinkPoses.push_back(b);
                    i++;
                }
                i = 0;
                for (auto &linkpose : filteredLinkPoses)
                {
                    tf::Pose tfpose;
                    tf::poseMsgToTF(linkpose, tfpose);
                    tf::StampedTransform transform;
                    transform.setOrigin(tfpose.getOrigin());
                    transform.setRotation(tfpose.getRotation());
                    transform.frame_id_ = globalFrame;
                    transform.child_frame_id_ = objectPrefix + std::to_string(i + 1);
                    transform.stamp_ = ros::Time::now();
                    tfBroadcaster_.sendTransform(transform);
                    i++;
                    transforms.push_back(transform);
                }
            }
setSafeArmMotionToAvoidCubeCollisions()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::setSafeArmMotionToAvoidCubeCollisions () [inline]
Definition at line 47 of file cp_simulated_gazebo_perception.h.
Referenced by sm_moveit_4::cl_perception_system::ClPerceptionSystem::setSafeArmMotionToAvoidCubeCollisions().
            {
                 safeTableHeightOffsetForCubeCollisions = 0.17;
            }
simulatedLinkStateCallback()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::simulatedLinkStateCallback (const gazebo_msgs::LinkStates & linksmsg) [inline]
Definition at line 72 of file cp_simulated_gazebo_perception.h.
Referenced by onInitialize().
            {
                identifyCubeColorsByNames(linksmsg.name);
                std::vector<tf::StampedTransform> cubeTransforms;
                this->propagateLinkStatesToTf(linksmsg, "cube", "cube_", "map",
      cubeTransforms);
                std::vector<tf::StampedTransform> tableTransforms;
                this->propagateLinkStatesToTf(linksmsg, "table", "table_", "map",
      tableTransforms);
                auto ellapsed = ros::Time::now() - this->lastUpdateStamp_;
                if (ellapsed > updatePeriod_)
                {
                    ROS_DEBUG("Updating planning scene perception");
                    auto attachedObjects = planningSceneInterface_->
      getAttachedObjects();
                    bool hasCubeAttached = false;
                    for (auto &k : attachedObjects)
                    {
                        if (k.first.find("cube") != std::string::npos)
                        {
                            hasCubeAttached = true;
                            break;
                        }
                    }
                    if (tableCollision_ && !hasCubeAttached)
                    {
                        std::vector<moveit_msgs::CollisionObject> collisionObjects(tableTransforms.size());
                        //std::vector<std::string> removeCollisionObjectNames(tableTransforms.size());
                        ros::Time time = ros::Time::now();
                        auto thickness = 0.12;
                        for (int i = 0; i < tableTransforms.size(); i++)
                        {
                            auto &tableTransf = tableTransforms[i];
                            auto &pos = tableTransf.getOrigin();
                            std::string tablename = "table_" + std::to_string(i + 1);
                            //removeCollisionObjectNames[i] = tablename;
                            moveit_msgs::CollisionObject &collision = collisionObjects[i];
                            collision.operation = moveit_msgs::CollisionObject::ADD;
                            collision.id = tablename;
                            collision.primitives.resize(1);
                            collision.primitives[0].type = collision.primitives[0].BOX;
                            collision.primitives[0].dimensions.resize(3);
                            collision.primitives[0].dimensions[0] = 1.05;
                            collision.primitives[0].dimensions[1] = 1.4;
                            collision.primitives[0].dimensions[2] = 0.001 + thickness +
      safeTableHeightOffsetForCubeCollisions;
                            /* Define the pose of the table. */
                            collision.primitive_poses.resize(1);
                            collision.primitive_poses[0].position.x = pos[0];
                            collision.primitive_poses[0].position.y = pos[1];
                            collision.primitive_poses[0].position.z = 0.7 - thickness * 0.5;
                            collision.primitive_poses[0].orientation.w = 1.0;
                            collision.header.frame_id = tableTransf.frame_id_;
                            collision.header.stamp = tableTransf.stamp_;
                            time = tableTransf.stamp_;
                        }
                        createVirtualFloorCollisionBox(collisionObjects, time
      );
                        lateralBox(collisionObjects, time);
                        this->planningSceneInterface_->applyCollisionObjects(
      collisionObjects);
                    }
                    if (cubeCollision_ && !hasCubeAttached)
                    {
                        // for i, cube_transf in enumerate(cube_transforms):
                        // #self.planning_scene.removeCollisionObject("cube_" + str(i))
                        // pos = cube_transf[0]
                        // self.planning_scene.addCube(
                        // "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
                        // #self.cube_collision = False
                    }
                }
            }
unsetSafeArmMotionToAvoidCubeCollisions()
void sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::unsetSafeArmMotionToAvoidCubeCollisions () [inline]
Definition at line 52 of file cp_simulated_gazebo_perception.h.
Referenced by sm_moveit_4::cl_perception_system::ClPerceptionSystem::unsetSafeArmMotionToAvoidCubeCollisions().
            {
                 safeTableHeightOffsetForCubeCollisions = 0;
            }
Member Data Documentation
cubeCollision_
bool sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::cubeCollision_ [private]
Definition at line 33 of file cp_simulated_gazebo_perception.h.
gazeboStateSubscriber_
ros::Subscriber sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::gazeboStateSubscriber_ [private]
Definition at line 41 of file cp_simulated_gazebo_perception.h.
lastUpdateStamp_
ros::Time sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::lastUpdateStamp_ [private]
Definition at line 30 of file cp_simulated_gazebo_perception.h.
movegroupclient_
ClMoveGroup* sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::movegroupclient_ [private]
Definition at line 36 of file cp_simulated_gazebo_perception.h.
planningSceneInterface_
moveit::planning_interface::PlanningSceneInterface* sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::planningSceneInterface_ [private]
Definition at line 35 of file cp_simulated_gazebo_perception.h.
readDelay
ros::Duration sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::readDelay [private]
Definition at line 28 of file cp_simulated_gazebo_perception.h.
safeTableHeightOffsetForCubeCollisions
double sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::safeTableHeightOffsetForCubeCollisions = 0
Definition at line 44 of file cp_simulated_gazebo_perception.h.
startTime
ros::Time sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::startTime [private]
Definition at line 27 of file cp_simulated_gazebo_perception.h.
tableCollision_
bool sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::tableCollision_ [private]
Definition at line 32 of file cp_simulated_gazebo_perception.h.
tfBroadcaster_
tf::TransformBroadcaster sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::tfBroadcaster_ [private]
Definition at line 40 of file cp_simulated_gazebo_perception.h.
tfListener_
tf::TransformListener sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::tfListener_ [private]
Definition at line 39 of file cp_simulated_gazebo_perception.h.
updatePeriod_
ros::Duration sm_moveit_4::cl_perception_system::CpSimulatedGazeboPerception::updatePeriod_ [private]
Definition at line 31 of file cp_simulated_gazebo_perception.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_moveit_4/include/sm_moveit_4/clients/perception_system_client/components/cp_simulated_gazebo_perception.h