moveit_z_client::CbMoveEndEffectorRelative Class Reference
#include <cb_move_end_effector_relative.h>
Public Member Functions
CbMoveEndEffectorRelative ()
CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
virtual void onEntry () override
virtual void onExit () override
Public Attributes
geometry_msgs::Transform transform_
boost::optional< std::string > group_
Protected Member Functions
void moveRelative (moveit::planning_interface::MoveGroupInterface &moveGroupinterface, geometry_msgs::Transform &transformOffset)
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 14 of file cb_move_end_effector_relative.h.
Constructor & Destructor Documentation
CbMoveEndEffectorRelative() [1/2]
moveit_z_client::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative ()
Definition at line 14 of file cb_move_end_effector_relative.cpp.
References transform_.
{
    transform_.rotation.w = 1;
}
CbMoveEndEffectorRelative() [2/2]
moveit_z_client::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
Definition at line 19 of file cb_move_end_effector_relative.cpp.
{
}
Member Function Documentation
moveRelative()
void moveit_z_client::CbMoveEndEffectorRelative::moveRelative (moveit::planning_interface::MoveGroupInterface & moveGroupinterface, geometry_msgs::Transform & transformOffset) [protected]
Definition at line 50 of file cb_move_end_effector_relative.cpp.
References movegroupClient_, moveit_z_client::ClMoveGroup::postEventMotionExecutionFailed(), and moveit_z_client::ClMoveGroup::postEventMotionExecutionSucceded().
Referenced by onEntry().
{
    auto referenceStartPose = moveGroupInterface.getCurrentPose();
    tf::Quaternion currentOrientation;
    tf::quaternionMsgToTF(referenceStartPose.pose.orientation, currentOrientation);
    tf::Quaternion desiredRelativeRotation;
    tf::quaternionMsgToTF(transformOffset.rotation, desiredRelativeRotation);
    auto targetOrientation = desiredRelativeRotation * currentOrientation;
    geometry_msgs::PoseStamped targetObjectPose = referenceStartPose;
    tf::quaternionTFToMsg(targetOrientation, targetObjectPose.pose.orientation);
    targetObjectPose.pose.position.x += transformOffset.translation.x;
    targetObjectPose.pose.position.y += transformOffset.translation.y;
    targetObjectPose.pose.position.z += transformOffset.translation.z;
    moveGroupInterface.setPlanningTime(1.0);
    ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Target End efector Pose: " << targetObjectPose);
    moveGroupInterface.setPoseTarget(targetObjectPose);
    moveGroupInterface.setPoseReferenceFrame("map");
    moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
    bool success = (moveGroupInterface.plan(computedMotionPlan) ==
      moveit::planning_interface::MoveItErrorCode::SUCCESS);
    ROS_INFO_NAMED("CbMoveEndEffectorRelative", "Success Visualizing plan 1 (pose goal) %s", success ? "" :
       "FAILED");
    if (success)
    {
        auto executionResult = moveGroupInterface.execute(computedMotionPlan);
        if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
        {
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution succedded");
            movegroupClient_->postEventMotionExecutionSucceded
      ();
        }
        else
        {
            moveGroupInterface.setPoseTarget(referenceStartPose); // undo to avoid abort-repeat state
       issues with this relative motion
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed(
      );
        }
    }
    else
    {
        moveGroupInterface.setPoseTarget(referenceStartPose); //undo since we did not executed the motion
        ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
        movegroupClient_->postEventMotionExecutionFailed();
    }
}
onEntry()
void moveit_z_client::CbMoveEndEffectorRelative::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_move_end_effector_relative.cpp.
References group_, movegroupClient_, moveit_z_client::ClMoveGroup::moveGroupClientInterface, moveRelative(), smacc::SmaccClientBehavior::requiresClient(), and transform_.
{
    ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Transform end effector pose relative: " <<
      transform_);
    this->requiresClient(movegroupClient_);
    if (this->group_)
    {
        auto res = std::async(std::launch::async, [=]
        {
                moveit::planning_interface::MoveGroupInterface move_group(*(this->
      group_));
                this->moveRelative(move_group, this->transform_);
        });
    }
    else
    {
        auto res = std::async(std::launch::async, [=]
        {
            this->moveRelative(movegroupClient_->
      moveGroupClientInterface, this->transform_);
        });
    }
}
onExit()
void moveit_z_client::CbMoveEndEffectorRelative::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 46 of file cb_move_end_effector_relative.cpp.
{
}
Member Data Documentation
group_
boost::optional<std::string> moveit_z_client::CbMoveEndEffectorRelative::group_
Definition at line 19 of file cb_move_end_effector_relative.h.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* moveit_z_client::CbMoveEndEffectorRelative::movegroupClient_ [protected]
Definition at line 33 of file cb_move_end_effector_relative.h.
Referenced by moveRelative(), and onEntry().
transform_
geometry_msgs::Transform moveit_z_client::CbMoveEndEffectorRelative::transform_
Definition at line 17 of file cb_move_end_effector_relative.h.
Referenced by CbMoveEndEffectorRelative(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/moveit_z_client/include/moveit_z_client/client_behaviors/cb_move_end_effector_relative.h
smacc_client_library/moveit_z_client/src/moveit_z_client/client_behaviors/cb_move_end_effector_relative.cpp