sm_moveit_4::StRotate180 Struct Reference
#include <st_navigate_to_destiny_table.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, StForwardNextTable, SUCCESS >, Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StRotate180, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_navigate_to_destiny_table.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, StForwardNextTable, SUCCESS>, Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StRotate180, ABORT> > sm_moveit_4::StRotate180::reactions
Definition at line 15 of file st_navigate_to_destiny_table.h.
Member Function Documentation
runtimeConfigure()
void sm_moveit_4::StRotate180::runtimeConfigure () [inline]
Definition at line 23 of file st_navigate_to_destiny_table.h.
References smacc::ISmaccClient::getComponent(), smacc::ISmaccState::requiresClient(), and cl_move_base_z::Pose::toPoseMsg().
    {
        ClMoveBaseZ *moveBaseClient_;
        this->requiresClient(moveBaseClient_);
        auto pose = moveBaseClient_->getComponent<Pose>();
        auto currentPose = pose->toPoseMsg();
        double targetAbsoluteAngleDegrees;
        if (currentPose.position.x < -0.2) // robot is at negative x-axis side
        {
                targetAbsoluteAngleDegrees = 0;
        }
        else // the robot in at positive x-axis side
        {
                targetAbsoluteAngleDegrees = 180;
        }
        auto absoluteRotateBehavior = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbAbsoluteRotate>();
        absoluteRotateBehavior->absoluteGoalAngleDegree = targetAbsoluteAngleDegrees;
        absoluteRotateBehavior->spinningPlanner = CbAbsoluteRotate::SpiningPlanner::PureSpinning;
    }
staticConfigure()
static void sm_moveit_4::StRotate180::staticConfigure () [inline], [static]
Definition at line 18 of file st_navigate_to_destiny_table.h.
    {
        configure_orthogonal<OrNavigation, CbAbsoluteRotate>(180/*-M_PI*/);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit_4/include/sm_moveit_4/states/st_navigate_to_destiny_table.h