move_base_z_client::WaypointEventDispatcher Class Reference
#include <waypoints_event_dispatcher.h>
Public Member Functions
template<typename TDerived , typename TObjectTag >
void initialize (ClMoveBaseZ *client)
void postWaypointEvent (int index)
Private Attributes
std::function< void()> postWaypointFn [WAYPOINTS_EVENTCOUNT]
Detailed Description
Definition at line 1560 of file waypoints_event_dispatcher.h.
Member Function Documentation
template<typename TDerived , typename TObjectTag > void move_base_z_client::WaypointEventDispatcher::initialize (ClMoveBaseZ * client)
Definition at line 1580 of file waypoints_event_dispatcher.h.
Referenced by move_base_z_client::WaypointNavigator::configureEventSourceTypes().
{
    configurePostEvWaypoint<EvWaypoint0<TDerived, TObjectTag>>(postWaypointFn, client, 0);
    configurePostEvWaypoint<EvWaypoint1<TDerived, TObjectTag>>(postWaypointFn, client, 1);
    configurePostEvWaypoint<EvWaypoint2<TDerived, TObjectTag>>(postWaypointFn, client, 2);
    configurePostEvWaypoint<EvWaypoint3<TDerived, TObjectTag>>(postWaypointFn, client, 3);
    configurePostEvWaypoint<EvWaypoint4<TDerived, TObjectTag>>(postWaypointFn, client, 4);
    configurePostEvWaypoint<EvWaypoint5<TDerived, TObjectTag>>(postWaypointFn, client, 5);
    configurePostEvWaypoint<EvWaypoint6<TDerived, TObjectTag>>(postWaypointFn, client, 6);
    configurePostEvWaypoint<EvWaypoint7<TDerived, TObjectTag>>(postWaypointFn, client, 7);
    configurePostEvWaypoint<EvWaypoint8<TDerived, TObjectTag>>(postWaypointFn, client, 8);
    configurePostEvWaypoint<EvWaypoint9<TDerived, TObjectTag>>(postWaypointFn, client, 9);
    configurePostEvWaypoint<EvWaypoint10<TDerived, TObjectTag>>(postWaypointFn, client, 10);
    configurePostEvWaypoint<EvWaypoint11<TDerived, TObjectTag>>(postWaypointFn, client, 11);
    configurePostEvWaypoint<EvWaypoint12<TDerived, TObjectTag>>(postWaypointFn, client, 12);
    configurePostEvWaypoint<EvWaypoint13<TDerived, TObjectTag>>(postWaypointFn, client, 13);
    configurePostEvWaypoint<EvWaypoint14<TDerived, TObjectTag>>(postWaypointFn, client, 14);
    configurePostEvWaypoint<EvWaypoint15<TDerived, TObjectTag>>(postWaypointFn, client, 15);
    configurePostEvWaypoint<EvWaypoint16<TDerived, TObjectTag>>(postWaypointFn, client, 16);
    configurePostEvWaypoint<EvWaypoint17<TDerived, TObjectTag>>(postWaypointFn, client, 17);
    configurePostEvWaypoint<EvWaypoint18<TDerived, TObjectTag>>(postWaypointFn, client, 18);
    configurePostEvWaypoint<EvWaypoint19<TDerived, TObjectTag>>(postWaypointFn, client, 19);
    configurePostEvWaypoint<EvWaypoint20<TDerived, TObjectTag>>(postWaypointFn, client, 20);
    configurePostEvWaypoint<EvWaypoint21<TDerived, TObjectTag>>(postWaypointFn, client, 21);
    configurePostEvWaypoint<EvWaypoint22<TDerived, TObjectTag>>(postWaypointFn, client, 22);
    configurePostEvWaypoint<EvWaypoint23<TDerived, TObjectTag>>(postWaypointFn, client, 23);
    configurePostEvWaypoint<EvWaypoint24<TDerived, TObjectTag>>(postWaypointFn, client, 24);
    configurePostEvWaypoint<EvWaypoint25<TDerived, TObjectTag>>(postWaypointFn, client, 25);
    configurePostEvWaypoint<EvWaypoint26<TDerived, TObjectTag>>(postWaypointFn, client, 26);
    configurePostEvWaypoint<EvWaypoint27<TDerived, TObjectTag>>(postWaypointFn, client, 27);
    configurePostEvWaypoint<EvWaypoint28<TDerived, TObjectTag>>(postWaypointFn, client, 28);
    configurePostEvWaypoint<EvWaypoint29<TDerived, TObjectTag>>(postWaypointFn, client, 29);
    configurePostEvWaypoint<EvWaypoint30<TDerived, TObjectTag>>(postWaypointFn, client, 30);
    configurePostEvWaypoint<EvWaypoint31<TDerived, TObjectTag>>(postWaypointFn, client, 31);
    configurePostEvWaypoint<EvWaypoint32<TDerived, TObjectTag>>(postWaypointFn, client, 32);
    configurePostEvWaypoint<EvWaypoint33<TDerived, TObjectTag>>(postWaypointFn, client, 33);
    configurePostEvWaypoint<EvWaypoint34<TDerived, TObjectTag>>(postWaypointFn, client, 34);
    configurePostEvWaypoint<EvWaypoint35<TDerived, TObjectTag>>(postWaypointFn, client, 35);
    configurePostEvWaypoint<EvWaypoint36<TDerived, TObjectTag>>(postWaypointFn, client, 36);
    configurePostEvWaypoint<EvWaypoint37<TDerived, TObjectTag>>(postWaypointFn, client, 37);
    configurePostEvWaypoint<EvWaypoint38<TDerived, TObjectTag>>(postWaypointFn, client, 38);
    configurePostEvWaypoint<EvWaypoint39<TDerived, TObjectTag>>(postWaypointFn, client, 39);
    configurePostEvWaypoint<EvWaypoint40<TDerived, TObjectTag>>(postWaypointFn, client, 40);
    configurePostEvWaypoint<EvWaypoint41<TDerived, TObjectTag>>(postWaypointFn, client, 41);
    configurePostEvWaypoint<EvWaypoint42<TDerived, TObjectTag>>(postWaypointFn, client, 42);
    configurePostEvWaypoint<EvWaypoint43<TDerived, TObjectTag>>(postWaypointFn, client, 43);
    configurePostEvWaypoint<EvWaypoint44<TDerived, TObjectTag>>(postWaypointFn, client, 44);
    configurePostEvWaypoint<EvWaypoint45<TDerived, TObjectTag>>(postWaypointFn, client, 45);
    configurePostEvWaypoint<EvWaypoint46<TDerived, TObjectTag>>(postWaypointFn, client, 46);
    configurePostEvWaypoint<EvWaypoint47<TDerived, TObjectTag>>(postWaypointFn, client, 47);
    configurePostEvWaypoint<EvWaypoint48<TDerived, TObjectTag>>(postWaypointFn, client, 48);
    configurePostEvWaypoint<EvWaypoint49<TDerived, TObjectTag>>(postWaypointFn, client, 49);
    configurePostEvWaypoint<EvWaypoint50<TDerived, TObjectTag>>(postWaypointFn, client, 50);
    configurePostEvWaypoint<EvWaypoint51<TDerived, TObjectTag>>(postWaypointFn, client, 51);
    configurePostEvWaypoint<EvWaypoint52<TDerived, TObjectTag>>(postWaypointFn, client, 52);
    configurePostEvWaypoint<EvWaypoint53<TDerived, TObjectTag>>(postWaypointFn, client, 53);
    configurePostEvWaypoint<EvWaypoint54<TDerived, TObjectTag>>(postWaypointFn, client, 54);
    configurePostEvWaypoint<EvWaypoint55<TDerived, TObjectTag>>(postWaypointFn, client, 55);
    configurePostEvWaypoint<EvWaypoint56<TDerived, TObjectTag>>(postWaypointFn, client, 56);
    configurePostEvWaypoint<EvWaypoint57<TDerived, TObjectTag>>(postWaypointFn, client, 57);
    configurePostEvWaypoint<EvWaypoint58<TDerived, TObjectTag>>(postWaypointFn, client, 58);
    configurePostEvWaypoint<EvWaypoint59<TDerived, TObjectTag>>(postWaypointFn, client, 59);
    configurePostEvWaypoint<EvWaypoint60<TDerived, TObjectTag>>(postWaypointFn, client, 60);
    configurePostEvWaypoint<EvWaypoint61<TDerived, TObjectTag>>(postWaypointFn, client, 61);
    configurePostEvWaypoint<EvWaypoint62<TDerived, TObjectTag>>(postWaypointFn, client, 62);
    configurePostEvWaypoint<EvWaypoint63<TDerived, TObjectTag>>(postWaypointFn, client, 63);
    configurePostEvWaypoint<EvWaypoint64<TDerived, TObjectTag>>(postWaypointFn, client, 64);
    configurePostEvWaypoint<EvWaypoint65<TDerived, TObjectTag>>(postWaypointFn, client, 65);
    configurePostEvWaypoint<EvWaypoint66<TDerived, TObjectTag>>(postWaypointFn, client, 66);
    configurePostEvWaypoint<EvWaypoint67<TDerived, TObjectTag>>(postWaypointFn, client, 67);
    configurePostEvWaypoint<EvWaypoint68<TDerived, TObjectTag>>(postWaypointFn, client, 68);
    configurePostEvWaypoint<EvWaypoint69<TDerived, TObjectTag>>(postWaypointFn, client, 69);
    configurePostEvWaypoint<EvWaypoint70<TDerived, TObjectTag>>(postWaypointFn, client, 70);
    configurePostEvWaypoint<EvWaypoint71<TDerived, TObjectTag>>(postWaypointFn, client, 71);
    configurePostEvWaypoint<EvWaypoint72<TDerived, TObjectTag>>(postWaypointFn, client, 72);
    configurePostEvWaypoint<EvWaypoint73<TDerived, TObjectTag>>(postWaypointFn, client, 73);
    configurePostEvWaypoint<EvWaypoint74<TDerived, TObjectTag>>(postWaypointFn, client, 74);
    configurePostEvWaypoint<EvWaypoint75<TDerived, TObjectTag>>(postWaypointFn, client, 75);
    configurePostEvWaypoint<EvWaypoint76<TDerived, TObjectTag>>(postWaypointFn, client, 76);
    configurePostEvWaypoint<EvWaypoint77<TDerived, TObjectTag>>(postWaypointFn, client, 77);
    configurePostEvWaypoint<EvWaypoint78<TDerived, TObjectTag>>(postWaypointFn, client, 78);
    configurePostEvWaypoint<EvWaypoint79<TDerived, TObjectTag>>(postWaypointFn, client, 79);
    configurePostEvWaypoint<EvWaypoint80<TDerived, TObjectTag>>(postWaypointFn, client, 80);
    configurePostEvWaypoint<EvWaypoint81<TDerived, TObjectTag>>(postWaypointFn, client, 81);
    configurePostEvWaypoint<EvWaypoint82<TDerived, TObjectTag>>(postWaypointFn, client, 82);
    configurePostEvWaypoint<EvWaypoint83<TDerived, TObjectTag>>(postWaypointFn, client, 83);
    configurePostEvWaypoint<EvWaypoint84<TDerived, TObjectTag>>(postWaypointFn, client, 84);
    configurePostEvWaypoint<EvWaypoint85<TDerived, TObjectTag>>(postWaypointFn, client, 85);
    configurePostEvWaypoint<EvWaypoint86<TDerived, TObjectTag>>(postWaypointFn, client, 86);
    configurePostEvWaypoint<EvWaypoint87<TDerived, TObjectTag>>(postWaypointFn, client, 87);
    configurePostEvWaypoint<EvWaypoint88<TDerived, TObjectTag>>(postWaypointFn, client, 88);
    configurePostEvWaypoint<EvWaypoint89<TDerived, TObjectTag>>(postWaypointFn, client, 89);
    configurePostEvWaypoint<EvWaypoint90<TDerived, TObjectTag>>(postWaypointFn, client, 90);
    configurePostEvWaypoint<EvWaypoint91<TDerived, TObjectTag>>(postWaypointFn, client, 91);
    configurePostEvWaypoint<EvWaypoint92<TDerived, TObjectTag>>(postWaypointFn, client, 92);
    configurePostEvWaypoint<EvWaypoint93<TDerived, TObjectTag>>(postWaypointFn, client, 93);
    configurePostEvWaypoint<EvWaypoint94<TDerived, TObjectTag>>(postWaypointFn, client, 94);
    configurePostEvWaypoint<EvWaypoint95<TDerived, TObjectTag>>(postWaypointFn, client, 95);
    configurePostEvWaypoint<EvWaypoint96<TDerived, TObjectTag>>(postWaypointFn, client, 96);
    configurePostEvWaypoint<EvWaypoint97<TDerived, TObjectTag>>(postWaypointFn, client, 97);
    configurePostEvWaypoint<EvWaypoint98<TDerived, TObjectTag>>(postWaypointFn, client, 98);
    configurePostEvWaypoint<EvWaypoint99<TDerived, TObjectTag>>(postWaypointFn, client, 99);
    configurePostEvWaypoint<EvWaypoint100<TDerived, TObjectTag>>(postWaypointFn, client, 100)
      ;
    configurePostEvWaypoint<EvWaypoint101<TDerived, TObjectTag>>(postWaypointFn, client, 101)
      ;
    configurePostEvWaypoint<EvWaypoint102<TDerived, TObjectTag>>(postWaypointFn, client, 102)
      ;
    configurePostEvWaypoint<EvWaypoint103<TDerived, TObjectTag>>(postWaypointFn, client, 103)
      ;
    configurePostEvWaypoint<EvWaypoint104<TDerived, TObjectTag>>(postWaypointFn, client, 104)
      ;
    configurePostEvWaypoint<EvWaypoint105<TDerived, TObjectTag>>(postWaypointFn, client, 105)
      ;
    configurePostEvWaypoint<EvWaypoint106<TDerived, TObjectTag>>(postWaypointFn, client, 106)
      ;
    configurePostEvWaypoint<EvWaypoint107<TDerived, TObjectTag>>(postWaypointFn, client, 107)
      ;
    configurePostEvWaypoint<EvWaypoint108<TDerived, TObjectTag>>(postWaypointFn, client, 108)
      ;
    configurePostEvWaypoint<EvWaypoint109<TDerived, TObjectTag>>(postWaypointFn, client, 109)
      ;
    configurePostEvWaypoint<EvWaypoint110<TDerived, TObjectTag>>(postWaypointFn, client, 110)
      ;
    configurePostEvWaypoint<EvWaypoint111<TDerived, TObjectTag>>(postWaypointFn, client, 111)
      ;
    configurePostEvWaypoint<EvWaypoint112<TDerived, TObjectTag>>(postWaypointFn, client, 112)
      ;
    configurePostEvWaypoint<EvWaypoint113<TDerived, TObjectTag>>(postWaypointFn, client, 113)
      ;
    configurePostEvWaypoint<EvWaypoint114<TDerived, TObjectTag>>(postWaypointFn, client, 114)
      ;
    configurePostEvWaypoint<EvWaypoint115<TDerived, TObjectTag>>(postWaypointFn, client, 115)
      ;
    configurePostEvWaypoint<EvWaypoint116<TDerived, TObjectTag>>(postWaypointFn, client, 116)
      ;
    configurePostEvWaypoint<EvWaypoint117<TDerived, TObjectTag>>(postWaypointFn, client, 117)
      ;
    configurePostEvWaypoint<EvWaypoint118<TDerived, TObjectTag>>(postWaypointFn, client, 118)
      ;
    configurePostEvWaypoint<EvWaypoint119<TDerived, TObjectTag>>(postWaypointFn, client, 119)
      ;
    configurePostEvWaypoint<EvWaypoint120<TDerived, TObjectTag>>(postWaypointFn, client, 120)
      ;
    configurePostEvWaypoint<EvWaypoint121<TDerived, TObjectTag>>(postWaypointFn, client, 121)
      ;
    configurePostEvWaypoint<EvWaypoint122<TDerived, TObjectTag>>(postWaypointFn, client, 122)
      ;
    configurePostEvWaypoint<EvWaypoint123<TDerived, TObjectTag>>(postWaypointFn, client, 123)
      ;
    configurePostEvWaypoint<EvWaypoint124<TDerived, TObjectTag>>(postWaypointFn, client, 124)
      ;
    configurePostEvWaypoint<EvWaypoint125<TDerived, TObjectTag>>(postWaypointFn, client, 125)
      ;
    configurePostEvWaypoint<EvWaypoint126<TDerived, TObjectTag>>(postWaypointFn, client, 126)
      ;
    configurePostEvWaypoint<EvWaypoint127<TDerived, TObjectTag>>(postWaypointFn, client, 127)
      ;
    configurePostEvWaypoint<EvWaypoint128<TDerived, TObjectTag>>(postWaypointFn, client, 128)
      ;
    configurePostEvWaypoint<EvWaypoint129<TDerived, TObjectTag>>(postWaypointFn, client, 129)
      ;
    configurePostEvWaypoint<EvWaypoint130<TDerived, TObjectTag>>(postWaypointFn, client, 130)
      ;
    configurePostEvWaypoint<EvWaypoint131<TDerived, TObjectTag>>(postWaypointFn, client, 131)
      ;
    configurePostEvWaypoint<EvWaypoint132<TDerived, TObjectTag>>(postWaypointFn, client, 132)
      ;
    configurePostEvWaypoint<EvWaypoint133<TDerived, TObjectTag>>(postWaypointFn, client, 133)
      ;
    configurePostEvWaypoint<EvWaypoint134<TDerived, TObjectTag>>(postWaypointFn, client, 134)
      ;
    configurePostEvWaypoint<EvWaypoint135<TDerived, TObjectTag>>(postWaypointFn, client, 135)
      ;
    configurePostEvWaypoint<EvWaypoint136<TDerived, TObjectTag>>(postWaypointFn, client, 136)
      ;
    configurePostEvWaypoint<EvWaypoint137<TDerived, TObjectTag>>(postWaypointFn, client, 137)
      ;
    configurePostEvWaypoint<EvWaypoint138<TDerived, TObjectTag>>(postWaypointFn, client, 138)
      ;
    configurePostEvWaypoint<EvWaypoint139<TDerived, TObjectTag>>(postWaypointFn, client, 139)
      ;
    configurePostEvWaypoint<EvWaypoint140<TDerived, TObjectTag>>(postWaypointFn, client, 140)
      ;
    configurePostEvWaypoint<EvWaypoint141<TDerived, TObjectTag>>(postWaypointFn, client, 141)
      ;
    configurePostEvWaypoint<EvWaypoint142<TDerived, TObjectTag>>(postWaypointFn, client, 142)
      ;
    configurePostEvWaypoint<EvWaypoint143<TDerived, TObjectTag>>(postWaypointFn, client, 143)
      ;
    configurePostEvWaypoint<EvWaypoint144<TDerived, TObjectTag>>(postWaypointFn, client, 144)
      ;
    configurePostEvWaypoint<EvWaypoint145<TDerived, TObjectTag>>(postWaypointFn, client, 145)
      ;
    configurePostEvWaypoint<EvWaypoint146<TDerived, TObjectTag>>(postWaypointFn, client, 146)
      ;
    configurePostEvWaypoint<EvWaypoint147<TDerived, TObjectTag>>(postWaypointFn, client, 147)
      ;
    configurePostEvWaypoint<EvWaypoint148<TDerived, TObjectTag>>(postWaypointFn, client, 148)
      ;
    configurePostEvWaypoint<EvWaypoint149<TDerived, TObjectTag>>(postWaypointFn, client, 149)
      ;
    configurePostEvWaypoint<EvWaypoint150<TDerived, TObjectTag>>(postWaypointFn, client, 150)
      ;
    configurePostEvWaypoint<EvWaypoint151<TDerived, TObjectTag>>(postWaypointFn, client, 151)
      ;
    configurePostEvWaypoint<EvWaypoint152<TDerived, TObjectTag>>(postWaypointFn, client, 152)
      ;
    configurePostEvWaypoint<EvWaypoint153<TDerived, TObjectTag>>(postWaypointFn, client, 153)
      ;
    configurePostEvWaypoint<EvWaypoint154<TDerived, TObjectTag>>(postWaypointFn, client, 154)
      ;
    configurePostEvWaypoint<EvWaypoint155<TDerived, TObjectTag>>(postWaypointFn, client, 155)
      ;
    configurePostEvWaypoint<EvWaypoint156<TDerived, TObjectTag>>(postWaypointFn, client, 156)
      ;
    configurePostEvWaypoint<EvWaypoint157<TDerived, TObjectTag>>(postWaypointFn, client, 157)
      ;
    configurePostEvWaypoint<EvWaypoint158<TDerived, TObjectTag>>(postWaypointFn, client, 158)
      ;
    configurePostEvWaypoint<EvWaypoint159<TDerived, TObjectTag>>(postWaypointFn, client, 159)
      ;
    configurePostEvWaypoint<EvWaypoint160<TDerived, TObjectTag>>(postWaypointFn, client, 160)
      ;
    configurePostEvWaypoint<EvWaypoint161<TDerived, TObjectTag>>(postWaypointFn, client, 161)
      ;
    configurePostEvWaypoint<EvWaypoint162<TDerived, TObjectTag>>(postWaypointFn, client, 162)
      ;
    configurePostEvWaypoint<EvWaypoint163<TDerived, TObjectTag>>(postWaypointFn, client, 163)
      ;
    configurePostEvWaypoint<EvWaypoint164<TDerived, TObjectTag>>(postWaypointFn, client, 164)
      ;
    configurePostEvWaypoint<EvWaypoint165<TDerived, TObjectTag>>(postWaypointFn, client, 165)
      ;
    configurePostEvWaypoint<EvWaypoint166<TDerived, TObjectTag>>(postWaypointFn, client, 166)
      ;
    configurePostEvWaypoint<EvWaypoint167<TDerived, TObjectTag>>(postWaypointFn, client, 167)
      ;
    configurePostEvWaypoint<EvWaypoint168<TDerived, TObjectTag>>(postWaypointFn, client, 168)
      ;
    configurePostEvWaypoint<EvWaypoint169<TDerived, TObjectTag>>(postWaypointFn, client, 169)
      ;
    configurePostEvWaypoint<EvWaypoint170<TDerived, TObjectTag>>(postWaypointFn, client, 170)
      ;
    configurePostEvWaypoint<EvWaypoint171<TDerived, TObjectTag>>(postWaypointFn, client, 171)
      ;
    configurePostEvWaypoint<EvWaypoint172<TDerived, TObjectTag>>(postWaypointFn, client, 172)
      ;
    configurePostEvWaypoint<EvWaypoint173<TDerived, TObjectTag>>(postWaypointFn, client, 173)
      ;
    configurePostEvWaypoint<EvWaypoint174<TDerived, TObjectTag>>(postWaypointFn, client, 174)
      ;
    configurePostEvWaypoint<EvWaypoint175<TDerived, TObjectTag>>(postWaypointFn, client, 175)
      ;
    configurePostEvWaypoint<EvWaypoint176<TDerived, TObjectTag>>(postWaypointFn, client, 176)
      ;
    configurePostEvWaypoint<EvWaypoint177<TDerived, TObjectTag>>(postWaypointFn, client, 177)
      ;
    configurePostEvWaypoint<EvWaypoint178<TDerived, TObjectTag>>(postWaypointFn, client, 178)
      ;
    configurePostEvWaypoint<EvWaypoint179<TDerived, TObjectTag>>(postWaypointFn, client, 179)
      ;
    configurePostEvWaypoint<EvWaypoint180<TDerived, TObjectTag>>(postWaypointFn, client, 180)
      ;
    configurePostEvWaypoint<EvWaypoint181<TDerived, TObjectTag>>(postWaypointFn, client, 181)
      ;
    configurePostEvWaypoint<EvWaypoint182<TDerived, TObjectTag>>(postWaypointFn, client, 182)
      ;
    configurePostEvWaypoint<EvWaypoint183<TDerived, TObjectTag>>(postWaypointFn, client, 183)
      ;
    configurePostEvWaypoint<EvWaypoint184<TDerived, TObjectTag>>(postWaypointFn, client, 184)
      ;
    configurePostEvWaypoint<EvWaypoint185<TDerived, TObjectTag>>(postWaypointFn, client, 185)
      ;
    configurePostEvWaypoint<EvWaypoint186<TDerived, TObjectTag>>(postWaypointFn, client, 186)
      ;
    configurePostEvWaypoint<EvWaypoint187<TDerived, TObjectTag>>(postWaypointFn, client, 187)
      ;
    configurePostEvWaypoint<EvWaypoint188<TDerived, TObjectTag>>(postWaypointFn, client, 188)
      ;
    configurePostEvWaypoint<EvWaypoint189<TDerived, TObjectTag>>(postWaypointFn, client, 189)
      ;
    configurePostEvWaypoint<EvWaypoint190<TDerived, TObjectTag>>(postWaypointFn, client, 190)
      ;
    configurePostEvWaypoint<EvWaypoint191<TDerived, TObjectTag>>(postWaypointFn, client, 191)
      ;
    configurePostEvWaypoint<EvWaypoint192<TDerived, TObjectTag>>(postWaypointFn, client, 192)
      ;
    configurePostEvWaypoint<EvWaypoint193<TDerived, TObjectTag>>(postWaypointFn, client, 193)
      ;
    configurePostEvWaypoint<EvWaypoint194<TDerived, TObjectTag>>(postWaypointFn, client, 194)
      ;
    configurePostEvWaypoint<EvWaypoint195<TDerived, TObjectTag>>(postWaypointFn, client, 195)
      ;
    configurePostEvWaypoint<EvWaypoint196<TDerived, TObjectTag>>(postWaypointFn, client, 196)
      ;
    configurePostEvWaypoint<EvWaypoint197<TDerived, TObjectTag>>(postWaypointFn, client, 197)
      ;
    configurePostEvWaypoint<EvWaypoint198<TDerived, TObjectTag>>(postWaypointFn, client, 198)
      ;
    configurePostEvWaypoint<EvWaypoint199<TDerived, TObjectTag>>(postWaypointFn, client, 199)
      ;
    configurePostEvWaypoint<EvWaypoint200<TDerived, TObjectTag>>(postWaypointFn, client, 200)
      ;
    configurePostEvWaypoint<EvWaypoint201<TDerived, TObjectTag>>(postWaypointFn, client, 201)
      ;
    configurePostEvWaypoint<EvWaypoint202<TDerived, TObjectTag>>(postWaypointFn, client, 202)
      ;
    configurePostEvWaypoint<EvWaypoint203<TDerived, TObjectTag>>(postWaypointFn, client, 203)
      ;
    configurePostEvWaypoint<EvWaypoint204<TDerived, TObjectTag>>(postWaypointFn, client, 204)
      ;
    configurePostEvWaypoint<EvWaypoint205<TDerived, TObjectTag>>(postWaypointFn, client, 205)
      ;
    configurePostEvWaypoint<EvWaypoint206<TDerived, TObjectTag>>(postWaypointFn, client, 206)
      ;
    configurePostEvWaypoint<EvWaypoint207<TDerived, TObjectTag>>(postWaypointFn, client, 207)
      ;
    configurePostEvWaypoint<EvWaypoint208<TDerived, TObjectTag>>(postWaypointFn, client, 208)
      ;
    configurePostEvWaypoint<EvWaypoint209<TDerived, TObjectTag>>(postWaypointFn, client, 209)
      ;
    configurePostEvWaypoint<EvWaypoint210<TDerived, TObjectTag>>(postWaypointFn, client, 210)
      ;
    configurePostEvWaypoint<EvWaypoint211<TDerived, TObjectTag>>(postWaypointFn, client, 211)
      ;
    configurePostEvWaypoint<EvWaypoint212<TDerived, TObjectTag>>(postWaypointFn, client, 212)
      ;
    configurePostEvWaypoint<EvWaypoint213<TDerived, TObjectTag>>(postWaypointFn, client, 213)
      ;
    configurePostEvWaypoint<EvWaypoint214<TDerived, TObjectTag>>(postWaypointFn, client, 214)
      ;
    configurePostEvWaypoint<EvWaypoint215<TDerived, TObjectTag>>(postWaypointFn, client, 215)
      ;
    configurePostEvWaypoint<EvWaypoint216<TDerived, TObjectTag>>(postWaypointFn, client, 216)
      ;
    configurePostEvWaypoint<EvWaypoint217<TDerived, TObjectTag>>(postWaypointFn, client, 217)
      ;
    configurePostEvWaypoint<EvWaypoint218<TDerived, TObjectTag>>(postWaypointFn, client, 218)
      ;
    configurePostEvWaypoint<EvWaypoint219<TDerived, TObjectTag>>(postWaypointFn, client, 219)
      ;
    configurePostEvWaypoint<EvWaypoint220<TDerived, TObjectTag>>(postWaypointFn, client, 220)
      ;
    configurePostEvWaypoint<EvWaypoint221<TDerived, TObjectTag>>(postWaypointFn, client, 221)
      ;
    configurePostEvWaypoint<EvWaypoint222<TDerived, TObjectTag>>(postWaypointFn, client, 222)
      ;
    configurePostEvWaypoint<EvWaypoint223<TDerived, TObjectTag>>(postWaypointFn, client, 223)
      ;
    configurePostEvWaypoint<EvWaypoint224<TDerived, TObjectTag>>(postWaypointFn, client, 224)
      ;
    configurePostEvWaypoint<EvWaypoint225<TDerived, TObjectTag>>(postWaypointFn, client, 225)
      ;
    configurePostEvWaypoint<EvWaypoint226<TDerived, TObjectTag>>(postWaypointFn, client, 226)
      ;
    configurePostEvWaypoint<EvWaypoint227<TDerived, TObjectTag>>(postWaypointFn, client, 227)
      ;
    configurePostEvWaypoint<EvWaypoint228<TDerived, TObjectTag>>(postWaypointFn, client, 228)
      ;
    configurePostEvWaypoint<EvWaypoint229<TDerived, TObjectTag>>(postWaypointFn, client, 229)
      ;
    configurePostEvWaypoint<EvWaypoint230<TDerived, TObjectTag>>(postWaypointFn, client, 230)
      ;
    configurePostEvWaypoint<EvWaypoint231<TDerived, TObjectTag>>(postWaypointFn, client, 231)
      ;
    configurePostEvWaypoint<EvWaypoint232<TDerived, TObjectTag>>(postWaypointFn, client, 232)
      ;
    configurePostEvWaypoint<EvWaypoint233<TDerived, TObjectTag>>(postWaypointFn, client, 233)
      ;
    configurePostEvWaypoint<EvWaypoint234<TDerived, TObjectTag>>(postWaypointFn, client, 234)
      ;
    configurePostEvWaypoint<EvWaypoint235<TDerived, TObjectTag>>(postWaypointFn, client, 235)
      ;
    configurePostEvWaypoint<EvWaypoint236<TDerived, TObjectTag>>(postWaypointFn, client, 236)
      ;
    configurePostEvWaypoint<EvWaypoint237<TDerived, TObjectTag>>(postWaypointFn, client, 237)
      ;
    configurePostEvWaypoint<EvWaypoint238<TDerived, TObjectTag>>(postWaypointFn, client, 238)
      ;
    configurePostEvWaypoint<EvWaypoint239<TDerived, TObjectTag>>(postWaypointFn, client, 239)
      ;
    configurePostEvWaypoint<EvWaypoint240<TDerived, TObjectTag>>(postWaypointFn, client, 240)
      ;
    configurePostEvWaypoint<EvWaypoint241<TDerived, TObjectTag>>(postWaypointFn, client, 241)
      ;
    configurePostEvWaypoint<EvWaypoint242<TDerived, TObjectTag>>(postWaypointFn, client, 242)
      ;
    configurePostEvWaypoint<EvWaypoint243<TDerived, TObjectTag>>(postWaypointFn, client, 243)
      ;
    configurePostEvWaypoint<EvWaypoint244<TDerived, TObjectTag>>(postWaypointFn, client, 244)
      ;
    configurePostEvWaypoint<EvWaypoint245<TDerived, TObjectTag>>(postWaypointFn, client, 245)
      ;
    configurePostEvWaypoint<EvWaypoint246<TDerived, TObjectTag>>(postWaypointFn, client, 246)
      ;
    configurePostEvWaypoint<EvWaypoint247<TDerived, TObjectTag>>(postWaypointFn, client, 247)
      ;
    configurePostEvWaypoint<EvWaypoint248<TDerived, TObjectTag>>(postWaypointFn, client, 248)
      ;
    configurePostEvWaypoint<EvWaypoint249<TDerived, TObjectTag>>(postWaypointFn, client, 249)
      ;
    configurePostEvWaypoint<EvWaypoint250<TDerived, TObjectTag>>(postWaypointFn, client, 250)
      ;
    configurePostEvWaypoint<EvWaypoint251<TDerived, TObjectTag>>(postWaypointFn, client, 251)
      ;
    configurePostEvWaypoint<EvWaypoint252<TDerived, TObjectTag>>(postWaypointFn, client, 252)
      ;
    configurePostEvWaypoint<EvWaypoint253<TDerived, TObjectTag>>(postWaypointFn, client, 253)
      ;
    configurePostEvWaypoint<EvWaypoint254<TDerived, TObjectTag>>(postWaypointFn, client, 254)
      ;
    configurePostEvWaypoint<EvWaypoint255<TDerived, TObjectTag>>(postWaypointFn, client, 255)
      ;
    configurePostEvWaypoint<EvWaypoint256<TDerived, TObjectTag>>(postWaypointFn, client, 256)
      ;
}
void move_base_z_client::WaypointEventDispatcher::postWaypointEvent (int index)
Definition at line 5 of file waypoints_event_dispatcher.cpp.
References postWaypointFn, and WAYPOINTS_EVENTCOUNT.
Referenced by move_base_z_client::WaypointNavigator::onGoalReached().
{
    auto& fn = postWaypointFn[index % WAYPOINTS_EVENTCOUNT];
    if(fn!=nullptr)
        fn();
}
Member Data Documentation
std::function<void()> move_base_z_client::WaypointEventDispatcher::postWaypointFn[WAYPOINTS_EVENTCOUNT] [private]
Definition at line 1562 of file waypoints_event_dispatcher.h.
Referenced by postWaypointEvent().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/waypoints_navigator/waypoints_event_dispatcher.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/components/waypoints_navigator/waypoints_event_dispatcher.cpp