sm_pr2_plugs::StFailStillUnplugged Struct Reference
#include <st_fail_still_unplugged.h>
Classes
struct DONE
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StFetchPlug, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StFailLowerSpine, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file st_fail_still_unplugged.h.
Member Typedef Documentation
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StFetchPlug, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StFailLowerSpine, SUCCESS> > sm_pr2_plugs::StFailStillUnplugged::reactions
Definition at line 16 of file st_fail_still_unplugged.h.
Member Function Documentation
void sm_pr2_plugs::StFailStillUnplugged::onSingleBehaviorTickCallback () [inline]
Definition at line 47 of file st_fail_still_unplugged.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
void sm_pr2_plugs::StFailStillUnplugged::onTimerClientTickCallback () [inline]
Definition at line 42 of file st_fail_still_unplugged.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
void sm_pr2_plugs::StFailStillUnplugged::runtimeConfigure () [inline]
Definition at line 25 of file st_fail_still_unplugged.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StFailStillUnplugged::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StFailStillUnplugged::onSingleBehaviorTickCallback, this)
      ;
    }
static void sm_pr2_plugs::StFailStillUnplugged::staticConfigure () [inline], [static]
Definition at line 19 of file st_fail_still_unplugged.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_fail_still_unplugged.h