sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable Struct Reference
#include <st_navigate_to_source_table.h>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbNavigateGlobalPosition, OrNavigation >, SS1::SsPickObject, SUCCESS >, Transition< EvCbFailure< CbNavigateGlobalPosition, OrNavigation >, StNavigateToSourceTable, ABORT >, Transition< EvFinishDemo, StInitialPosture > > reactions
Public Member Functions
void runtimeConfigure ()
void OnEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 13 of file st_navigate_to_source_table.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbNavigateGlobalPosition, OrNavigation>, SS1::SsPickObject, SUCCESS>, Transition<EvCbFailure<CbNavigateGlobalPosition, OrNavigation>, StNavigateToSourceTable, ABORT>, Transition<EvFinishDemo, StInitialPosture> > sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable::reactions
Definition at line 24 of file st_navigate_to_source_table.h.
Member Function Documentation
OnEntry()
void sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable::OnEntry () [inline]
Definition at line 57 of file st_navigate_to_source_table.h.
        {
            ROS_INFO("state on entry");
        }
runtimeConfigure()
void sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable::runtimeConfigure () [inline]
Definition at line 32 of file st_navigate_to_source_table.h.
References sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::decidePickCubePose(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::getMainTablePose(), and smacc::ISmaccClient::requiresClient().
        {
            auto *navigateGlobalPosition = this->getOrthogonal<OrNavigation>()->
      getClientBehavior<CbNavigateGlobalPosition>();
            ClPerceptionSystem *perceptionSystem;
            navigateGlobalPosition->requiresClient(perceptionSystem);
            //perceptionSystem->nextObject();
            auto tablePose = perceptionSystem->getMainTablePose().pose;
            tablePose.position.x -= 0.85;
            geometry_msgs::PoseStamped nextCubePose;
            if (perceptionSystem->decidePickCubePose(nextCubePose))
            {
                // align with the cube in the y axis
                tablePose.position.y = nextCubePose.pose.position.y;
                navigateGlobalPosition->setGoal(tablePose);
            }
            else
            {
                this->postEvent<EvFinishDemo>();
            }
        }
staticConfigure()
static void sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable::staticConfigure () [inline], [static]
Definition at line 27 of file st_navigate_to_source_table.h.
        {
            configure_orthogonal<OrNavigation, CbNavigateGlobalPosition>();
        }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/states/st_navigate_to_source_table.h