sm_fetch_two_table_pick_n_place_1::pick_states::StNavigationPosture Struct Reference
#include <st_navigation_posture.h>
Public Types
typedef mpl::list< Transition< EvMoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StNavigationPosture, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_navigation_posture.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvMoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StNavigationPosture, ABORT> > sm_fetch_two_table_pick_n_place_1::pick_states::StNavigationPosture::reactions
Definition at line 16 of file st_navigation_posture.h.
Member Function Documentation
runtimeConfigure()
void sm_fetch_two_table_pick_n_place_1::pick_states::StNavigationPosture::runtimeConfigure () [inline]
Definition at line 24 of file st_navigation_posture.h.
References cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StNavigationPosture, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StNavigationPosture::throwSequenceFinishedEvent, this);
        this->getOrthogonal<OrNavigation>()->getClientBehavior<CbMoveJoints>()->scalingFactor_ = 1;
        /*
        ros::WallDuration(3).sleep();
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        auto moveCartesianRelative = this->getOrthogonal<OrArm>()
                                         ->getClientBehavior<CbMoveCartesianRelative>();
        std::vector<std::string> namesposes = moveGroupClient->moveGroupClientInterface.getNamedTargets();
        ROS_INFO("--- named poses: ");
        for (auto &posename : namesposes)
        {
            ROS_INFO_STREAM(" - named pose: " << posename);
        }
        ROS_INFO("--- named poses");
        moveCartesianRelative->offset_.z = -0.35;
        auto currentTable = perceptionSystem->getCurrentTable();
        if (currentTable == RobotProcessStatus::TABLE0)
        {
            moveCartesianRelative->offset_.x = -0.25;
        }
        else if (currentTable == RobotProcessStatus::TABLE1)
        {
            moveCartesianRelative->offset_.x = 0.25;
        }
    */
    }
staticConfigure()
static void sm_fetch_two_table_pick_n_place_1::pick_states::StNavigationPosture::staticConfigure () [inline], [static]
Definition at line 19 of file st_navigation_posture.h.
    {
        configure_orthogonal<OrNavigation, CbMoveKnownState>("sm_fetch_two_table_pick_n_place_1", "
      config/manipulation/known_states/nav_posture.yaml");
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_pick_n_place_1/include/sm_fetch_two_table_pick_n_place_1/states/pick_states/st_navigation_posture.h