sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart Struct Reference
#include <sti_spattern_loop_start.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiSPatternLoopStart >, StiSPatternRotate1, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_spattern_loop_start.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiSPatternLoopStart>, StiSPatternRotate1, CONTINUELOOP> > sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart::reactions
Definition at line 16 of file sti_spattern_loop_start.h.
Member Function Documentation
loopCondition()
bool sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart::loopCondition () [inline]
Definition at line 27 of file sti_spattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    return superstate.iteration_count++ < superstate.total_iterations();
  }
onEntry()
void sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart::onEntry () [inline]
Definition at line 33 of file sti_spattern_loop_start.h.
References smacc::SmaccState< StiSPatternLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopCondition().
  {
    checkWhileLoopConditionAndThrowEvent(&
      StiSPatternLoopStart::loopCondition);
  }
runtimeConfigure()
void sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart::runtimeConfigure () [inline]
Definition at line 23 of file sti_spattern_loop_start.h.
  {
  }
staticConfigure()
static void sm_dance_bot_2::s_pattern_states::StiSPatternLoopStart::staticConfigure () [inline], [static]
Definition at line 19 of file sti_spattern_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_2/include/sm_dance_bot_2/states/ms_dance_bot_run_mode/s_pattern_states/sti_spattern_loop_start.h