move_base_z_client::CbAbsoluteRotate Class Reference
#include <cb_absolute_rotate.h>
Public Member Functions
CbAbsoluteRotate ()
CbAbsoluteRotate (float absoluteGoalAngleDegree)
virtual void onEntry () override
Public Attributes
tf::TransformListener listener
ClMoveBaseZ * moveBaseClient_
boost::optional< float > absoluteGoalAngleDegree
Detailed Description
Definition at line 18 of file cb_absolute_rotate.h.
Constructor & Destructor Documentation
CbAbsoluteRotate() [1/2]
move_base_z_client::CbAbsoluteRotate::CbAbsoluteRotate ()
Definition at line 6 of file cb_absolute_rotate.cpp.
{
}
CbAbsoluteRotate() [2/2]
move_base_z_client::CbAbsoluteRotate::CbAbsoluteRotate (float absoluteGoalAngleDegree)
Definition at line 10 of file cb_absolute_rotate.cpp.
References absoluteGoalAngleDegree.
{
    this->absoluteGoalAngleDegree =
      absoluteGoalAngleDegree;
}
Member Function Documentation
onEntry()
void move_base_z_client::CbAbsoluteRotate::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 15 of file cb_absolute_rotate.cpp.
References absoluteGoalAngleDegree, smacc::ISmaccClient::getComponent(), smacc::SmaccClientBehavior::getCurrentState(), listener, moveBaseClient_, smacc::ISmaccState::param(), smacc::SmaccClientBehavior::requiresClient(), smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), and move_base_z_client::PlannerSwitcher::setDefaultPlanners().
{
    double goal_angle;
    if (!this->absoluteGoalAngleDegree)
    {
        this->getCurrentState()->param("goal_angle", goal_angle, 45.0);
    }
    else
    {
        goal_angle = *this->absoluteGoalAngleDegree;
    }
    this->requiresClient(moveBaseClient_);
    auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
    //this should work better with a coroutine and await
    //this->plannerSwitcher_->setForwardPlanner();
    plannerSwitcher->setDefaultPlanners();
    ros::Rate rate(10.0);
    geometry_msgs::Pose currentPoseMsg;
    while (ros::ok())
    {
        tf::StampedTransform currentPose;
        try
        {
            listener.lookupTransform("/odom", "/base_link",
                                     ros::Time(0), currentPose);
            tf::poseTFToMsg(currentPose, currentPoseMsg);
            break;
        }
        catch (tf::TransformException ex)
        {
            ROS_INFO("[CbAbsoluteRotate] Waiting transform: %s", ex.what());
            ros::Duration(1.0).sleep();
        }
    }
    ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    auto currentAngle = tf::getYaw(currentPoseMsg.orientation);
    auto targetAngle = goal_angle * M_PI / 180.0;
    goal.target_pose.pose.position = currentPoseMsg.position;
    goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(targetAngle);
    ROS_INFO_STREAM("current pose: " << currentPoseMsg);
    ROS_INFO_STREAM("goal pose: " << goal.target_pose.pose);
    moveBaseClient_->sendGoal(goal);
}
Member Data Documentation
absoluteGoalAngleDegree
boost::optional<float> move_base_z_client::CbAbsoluteRotate::absoluteGoalAngleDegree
Definition at line 25 of file cb_absolute_rotate.h.
Referenced by CbAbsoluteRotate(), and onEntry().
listener
tf::TransformListener move_base_z_client::CbAbsoluteRotate::listener
Definition at line 21 of file cb_absolute_rotate.h.
Referenced by onEntry().
moveBaseClient_
ClMoveBaseZ* move_base_z_client::CbAbsoluteRotate::moveBaseClient_
Definition at line 23 of file cb_absolute_rotate.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_absolute_rotate.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_absolute_rotate.cpp