move_base_z_client::CbUndoPathBackwards Class Reference
#include <cb_undo_path_backwards.h>
Private Member Functions
virtual void onEntry () override
Private Attributes
tf::TransformListener listener
ClMoveBaseZ * moveBaseClient_
Additional Inherited Members
Detailed Description
Definition at line 18 of file cb_undo_path_backwards.h.
Member Function Documentation
onEntry()
void move_base_z_client::CbUndoPathBackwards::onEntry () [override], [private], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 7 of file cb_undo_path_backwards.cpp.
References smacc::ISmaccClient::getComponent(), moveBaseClient_, smacc::SmaccClientBehavior::requiresClient(), smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), and move_base_z_client::PlannerSwitcher::setBackwardPlanner().
{
    this->requiresClient(moveBaseClient_);
    auto *odomTracker = moveBaseClient_->getComponent<OdomTracker>();
    auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
    nav_msgs::Path forwardpath = odomTracker->getPath();
    //ROS_INFO_STREAM("[UndoPathBackward] Current path backwards: " << forwardpath);
    odomTracker->setWorkingMode(WorkingMode::CLEAR_PATH_BACKWARD);
    ClMoveBaseZ::Goal goal;
    if (forwardpath.poses.size() > 0)
    {
        goal.target_pose = forwardpath.poses.front();
        plannerSwitcher->setBackwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
}
Member Data Documentation
listener
tf::TransformListener move_base_z_client::CbUndoPathBackwards::listener [private]
Definition at line 20 of file cb_undo_path_backwards.h.
moveBaseClient_
ClMoveBaseZ* move_base_z_client::CbUndoPathBackwards::moveBaseClient_ [private]
Definition at line 22 of file cb_undo_path_backwards.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_undo_path_backwards.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_undo_path_backwards.cpp