sm_starcraft_ai::StObserve Struct Reference
#include <st_observe.h>
Classes
struct ATTACK
struct BUILD
struct MOVE
Public Types
typedef mpl::list< Transition< EvKeyPressA< CbDefaultKeyboardBehavior, OrKeyboard >, SS1::SsMove, MOVE >, Transition< EvKeyPressB< CbDefaultKeyboardBehavior, OrKeyboard >, SS2::SsBuild, BUILD >, Transition< EvKeyPressC< CbDefaultKeyboardBehavior, OrKeyboard >, SS3::SsAttack, ATTACK > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_observe.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressA<CbDefaultKeyboardBehavior, OrKeyboard>, SS1::SsMove, MOVE>, Transition<EvKeyPressB<CbDefaultKeyboardBehavior, OrKeyboard>, SS2::SsBuild, BUILD>, Transition<EvKeyPressC<CbDefaultKeyboardBehavior, OrKeyboard>, SS3::SsAttack, ATTACK> > sm_starcraft_ai::StObserve::reactions
Definition at line 23 of file st_observe.h.
Member Function Documentation
onEntry()
void sm_starcraft_ai::StObserve::onEntry () [inline]
Definition at line 51 of file st_observe.h.
    {
        ROS_INFO("On Entry!");
    }
onExit()
void sm_starcraft_ai::StObserve::onExit () [inline]
Definition at line 56 of file st_observe.h.
    {
        ROS_INFO("On Exit!");
    }
onSingleBehaviorTickCallback()
void sm_starcraft_ai::StObserve::onSingleBehaviorTickCallback () [inline]
Definition at line 66 of file st_observe.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_starcraft_ai::StObserve::onTimerClientTickCallback () [inline]
Definition at line 61 of file st_observe.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_starcraft_ai::StObserve::runtimeConfigure () [inline]
Definition at line 34 of file st_observe.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StObserve::onTimerClientTickCallback, this
      );
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StObserve::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_starcraft_ai::StObserve::staticConfigure () [inline], [static]
Definition at line 26 of file st_observe.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_starcraft_ai/include/sm_starcraft_ai/states/st_observe.h