sm_calendar_week::StTuesday Struct Reference
#include <st_tuesday.h>
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StWednesday, PREEMPT >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StWednesday, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 5 of file st_tuesday.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StWednesday, PREEMPT>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StWednesday, SUCCESS> > sm_calendar_week::StTuesday::reactions
Definition at line 15 of file st_tuesday.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_calendar_week::StTuesday::onSingleBehaviorTickCallback () [inline]
Definition at line 46 of file st_tuesday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_calendar_week::StTuesday::onTimerClientTickCallback () [inline]
Definition at line 41 of file st_tuesday.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_calendar_week::StTuesday::runtimeConfigure () [inline]
Definition at line 24 of file st_tuesday.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StTuesday::onTimerClientTickCallback, this
      );
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StTuesday::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_calendar_week::StTuesday::staticConfigure () [inline], [static]
Definition at line 18 of file st_tuesday.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_calendar_week/include/sm_calendar_week/states/st_tuesday.h