sm_three_some::StState3 Struct Reference
#include <st_state_3.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, SS1::Ss1, TIMEOUT >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StState2, PREVIOUS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, SS1::Ss1, NEXT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_state_3.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, SS1::Ss1, TIMEOUT>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StState2, PREVIOUS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, SS1::Ss1, NEXT> > sm_three_some::StState3::reactions
Definition at line 22 of file st_state_3.h.
Member Function Documentation
onEntry()
void sm_three_some::StState3::onEntry () [inline]
Definition at line 50 of file st_state_3.h.
    {
        ROS_INFO("On Entry!");
    }
onExit()
void sm_three_some::StState3::onExit () [inline]
Definition at line 55 of file st_state_3.h.
    {
        ROS_INFO("On Exit!");
    }
onSingleBehaviorTickCallback()
void sm_three_some::StState3::onSingleBehaviorTickCallback () [inline]
Definition at line 65 of file st_state_3.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_three_some::StState3::onTimerClientTickCallback () [inline]
Definition at line 60 of file st_state_3.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_three_some::StState3::runtimeConfigure () [inline]
Definition at line 33 of file st_state_3.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StState3::onTimerClientTickCallback, this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StState3::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_three_some::StState3::staticConfigure () [inline], [static]
Definition at line 25 of file st_state_3.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/states/st_state_3.h