sm_respira_1::StLeakyLungStep1 Struct Reference
#include <st_leaky_lung_step_1.h>
Classes
struct ATTACK
struct BUILD
struct MOVE
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StLeakyLungStep2, SUCCESS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StLeakyLungStep2, SUCCESS > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_leaky_lung_step_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StLeakyLungStep2, SUCCESS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StLeakyLungStep2, SUCCESS> > sm_respira_1::StLeakyLungStep1::reactions
Definition at line 23 of file st_leaky_lung_step_1.h.
Member Function Documentation
onEntry()
void sm_respira_1::StLeakyLungStep1::onEntry () [inline]
Definition at line 51 of file st_leaky_lung_step_1.h.
    {
        ROS_INFO("On Entry!");
    }
onExit()
void sm_respira_1::StLeakyLungStep1::onExit () [inline]
Definition at line 56 of file st_leaky_lung_step_1.h.
    {
        ROS_INFO("On Exit!");
    }
onSingleBehaviorTickCallback()
void sm_respira_1::StLeakyLungStep1::onSingleBehaviorTickCallback () [inline]
Definition at line 66 of file st_leaky_lung_step_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_respira_1::StLeakyLungStep1::onTimerClientTickCallback () [inline]
Definition at line 61 of file st_leaky_lung_step_1.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_respira_1::StLeakyLungStep1::runtimeConfigure () [inline]
Definition at line 34 of file st_leaky_lung_step_1.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StLeakyLungStep1::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StLeakyLungStep1::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_respira_1::StLeakyLungStep1::staticConfigure () [inline], [static]
Definition at line 26 of file st_leaky_lung_step_1.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(50);
        configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
        configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/st_leaky_lung_step_1.h