sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart Struct Reference
#include <sti_radial_loop_start.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiRadialLoopStart >, StiRadialRotate, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_radial_loop_start.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiRadialLoopStart>, StiRadialRotate, CONTINUELOOP> > sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart::reactions
Definition at line 15 of file sti_radial_loop_start.h.
Member Function Documentation
loopWhileCondition()
bool sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart::loopWhileCondition () [inline]
Definition at line 26 of file sti_radial_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
onEntry()
void sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart::onEntry () [inline]
Definition at line 34 of file sti_radial_loop_start.h.
References smacc::SmaccState< StiRadialLoopStart, SS >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      StiRadialLoopStart::loopWhileCondition);
  }
runtimeConfigure()
void sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart::runtimeConfigure () [inline]
Definition at line 22 of file sti_radial_loop_start.h.
  {
  }
staticConfigure()
static void sm_ridgeback_floor_coverage_static_1::radial_motion_states::StiRadialLoopStart::staticConfigure () [inline], [static]
Definition at line 18 of file sti_radial_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_ridgeback_floor_coverage_static_1/include/sm_ridgeback_floor_coverage_static_1/states/ms_dance_bot_run_mode/radial_motion_states/sti_radial_loop_start.h