sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire Struct Reference
#include <sti_cmv_cycle_inspire.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StiPSCyclePlateau, TIMEOUT >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StiPSCyclePlateau, NEXT >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StiPSCycleLoop, PREVIOUS >, Transition< EvKeyPressY< CbDefaultKeyboardBehavior, OrKeyboard >, MsLeakyLung, ABORT >, Transition< EvKeyPressZ< CbDefaultKeyboardBehavior, OrKeyboard >, MsPatientObstruction, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_cmv_cycle_inspire.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StiPSCyclePlateau, TIMEOUT>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StiPSCyclePlateau, NEXT>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StiPSCycleLoop, PREVIOUS>, Transition<EvKeyPressY<CbDefaultKeyboardBehavior, OrKeyboard>, MsLeakyLung, ABORT>, Transition<EvKeyPressZ<CbDefaultKeyboardBehavior, OrKeyboard>, MsPatientObstruction, ABORT> > sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::reactions
Definition at line 25 of file sti_cmv_cycle_inspire.h.
Member Function Documentation
onEntry()
void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::onEntry () [inline]
Definition at line 53 of file sti_cmv_cycle_inspire.h.
  {
    ROS_INFO("On Entry!");
  }
onExit()
void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::onExit () [inline]
Definition at line 58 of file sti_cmv_cycle_inspire.h.
  {
    ROS_INFO("On Exit!");
  }
onSingleBehaviorTickCallback()
void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::onSingleBehaviorTickCallback () [inline]
Definition at line 68 of file sti_cmv_cycle_inspire.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("single behavior tick!");
  }
onTimerClientTickCallback()
void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::onTimerClientTickCallback () [inline]
Definition at line 63 of file sti_cmv_cycle_inspire.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("timer client tick!");
  }
runtimeConfigure()
void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::runtimeConfigure () [inline]
Definition at line 36 of file sti_cmv_cycle_inspire.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
  {
    // get reference to the client
    ClRosTimer *client;
    this->requiresClient(client);
    // subscribe to the timer client callback
    client->onTimerTick(&StiPSCycleInspire::onTimerClientTickCallback
      , this);
    // getting reference to the single countdown behavior
    auto *cbsingle = this->getOrthogonal<OrTimer>()
                         ->getClientBehavior<CbTimerCountdownOnce>();
    // subscribe to the single countdown behavior callback
    cbsingle->onTimerTick(&StiPSCycleInspire::onSingleBehaviorTickCallback
      , this);
  }
staticConfigure()
static void sm_respira_1::cmv_cycle_inner_states::StiPSCycleInspire::staticConfigure () [inline], [static]
Definition at line 28 of file sti_cmv_cycle_inspire.h.
  {
    configure_orthogonal<OrTimer, CbTimerCountdownOnce>(40);
    configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
    configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
    configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/cmv_cycle_inner_states/sti_cmv_cycle_inspire.h