sm_pr2_plugs::StGoalIsLocal Struct Reference
#include <st_goal_is_local.h>
Classes
struct FALSE
struct TRUE
Public Types
typedef mpl::list< Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StSafetyTuck, FALSE >, Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StUntuckAtOutlet, TRUE > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file st_goal_is_local.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StSafetyTuck, FALSE>, Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StUntuckAtOutlet, TRUE> > sm_pr2_plugs::StGoalIsLocal::reactions
Definition at line 17 of file st_goal_is_local.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_pr2_plugs::StGoalIsLocal::onSingleBehaviorTickCallback () [inline]
Definition at line 48 of file st_goal_is_local.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_pr2_plugs::StGoalIsLocal::onTimerClientTickCallback () [inline]
Definition at line 43 of file st_goal_is_local.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_pr2_plugs::StGoalIsLocal::runtimeConfigure () [inline]
Definition at line 26 of file st_goal_is_local.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StGoalIsLocal::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&StGoalIsLocal::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_pr2_plugs::StGoalIsLocal::staticConfigure () [inline], [static]
Definition at line 20 of file st_goal_is_local.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5);
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_goal_is_local.h