sm_moveit::pick_states::StNavigationPosture Struct Reference
#include <st_navigation_posture.h>
Public Types
typedef mpl::list< Transition< MoveGroupMotionExecutionFailed< ClMoveGroup, OrArm >, StNavigationPosture, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 8 of file st_navigation_posture.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<MoveGroupMotionExecutionFailed<ClMoveGroup, OrArm>, StNavigationPosture, ABORT> > sm_moveit::pick_states::StNavigationPosture::reactions
Definition at line 16 of file st_navigation_posture.h.
Member Function Documentation
runtimeConfigure()
void sm_moveit::pick_states::StNavigationPosture::runtimeConfigure () [inline]
Definition at line 41 of file st_navigation_posture.h.
References moveit_z_client::ClMoveGroup::onMotionExecutionSuccedded(), smacc::ISmaccState::requiresClient(), and smacc::SmaccState< StNavigationPosture, SS >::throwSequenceFinishedEvent().
    {
        ClMoveGroup *moveGroupClient;
        this->requiresClient(moveGroupClient);
        moveGroupClient->onMotionExecutionSuccedded(&
      StNavigationPosture::throwSequenceFinishedEvent, this);
        /*
        ros::WallDuration(3).sleep();
        ClPerceptionSystem *perceptionSystem;
        this->requiresClient(perceptionSystem);
        auto moveCartesianRelative = this->getOrthogonal<OrArm>()
                                         ->getClientBehavior<CbMoveCartesianRelative>();
        std::vector<std::string> namesposes = moveGroupClient->moveGroupClientInterface.getNamedTargets();
        ROS_INFO("--- named poses: ");
        for (auto &posename : namesposes)
        {
            ROS_INFO_STREAM(" - named pose: " << posename);
        }
        ROS_INFO("--- named poses");
        moveCartesianRelative->offset_.z = -0.35;
        auto currentTable = perceptionSystem->getCurrentTable();
        if (currentTable == RobotProcessStatus::TABLE0)
        {
            moveCartesianRelative->offset_.x = -0.25;
        }
        else if (currentTable == RobotProcessStatus::TABLE1)
        {
            moveCartesianRelative->offset_.x = 0.25;
        }
    */
    }
staticConfigure()
static void sm_moveit::pick_states::StNavigationPosture::staticConfigure () [inline], [static]
Definition at line 19 of file st_navigation_posture.h.
    {
        std::map<std::string, double> jointValues{
            {"l_wheel_joint", 0.2032989263112741},
            {"r_wheel_joint", -0.25798452342087597},
            {"torso_lift_joint", -1.2577603815717127e-05},
            {"bellows_joint", 0.006785193726937263},
            {"head_pan_joint", 0.0053190193943049024},
            {"head_tilt_joint", 0.0037173708013753526},
            {"shoulder_pan_joint", 1.3199986235290062},
            {"shoulder_lift_joint", 0.7000699976533715},
            {"upperarm_roll_joint", -7.398079828480064e-05},
            {"elbow_flex_joint", -1.99994794099468},
            {"forearm_roll_joint", 0.00021030168417901507},
            {"wrist_flex_joint", -0.5700976747076689},
            {"wrist_roll_joint", -0.00023467601597193521},
            {"l_gripper_finger_joint", 0.05001998415439018},
            {"r_gripper_finger_joint", 0.050039698895249535}};
        configure_orthogonal<OrNavigation, CbMoveJoints>(jointValues);
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_moveit/include/sm_moveit/states/pick_states/st_navigation_posture.h