sm_respira_1::ac_cycle_inner_states::StiACCycleDwell Struct Reference
#include <sti_ac_cycle_dwell.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StiACCycleLoop, TIMEOUT >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StiACCycleExpire, PREVIOUS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StiACCycleLoop, NEXT >, Transition< EvKeyPressY< CbDefaultKeyboardBehavior, OrKeyboard >, MsLeakyLung, ABORT >, Transition< EvKeyPressZ< CbDefaultKeyboardBehavior, OrKeyboard >, MsPatientObstruction, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_ac_cycle_dwell.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StiACCycleLoop, TIMEOUT>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StiACCycleExpire, PREVIOUS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StiACCycleLoop, NEXT>, Transition<EvKeyPressY<CbDefaultKeyboardBehavior, OrKeyboard>, MsLeakyLung, ABORT>, Transition<EvKeyPressZ<CbDefaultKeyboardBehavior, OrKeyboard>, MsPatientObstruction, ABORT> > sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::reactions
Definition at line 24 of file sti_ac_cycle_dwell.h.
Member Function Documentation
onEntry()
void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onEntry () [inline]
Definition at line 52 of file sti_ac_cycle_dwell.h.
  {
    ROS_INFO("On Entry!");
  }
onExit()
void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onExit () [inline]
Definition at line 57 of file sti_ac_cycle_dwell.h.
  {
    ROS_INFO("On Exit!");
  }
onSingleBehaviorTickCallback()
void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onSingleBehaviorTickCallback () [inline]
Definition at line 67 of file sti_ac_cycle_dwell.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("single behavior tick!");
  }
onTimerClientTickCallback()
void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onTimerClientTickCallback () [inline]
Definition at line 62 of file sti_ac_cycle_dwell.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("timer client tick!");
  }
runtimeConfigure()
void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::runtimeConfigure () [inline]
Definition at line 35 of file sti_ac_cycle_dwell.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
  {
    // get reference to the client
    ClRosTimer *client;
    this->requiresClient(client);
    // subscribe to the timer client callback
    client->onTimerTick(&StiACCycleDwell::onTimerClientTickCallback
      , this);
    // getting reference to the single countdown behavior
    auto *cbsingle = this->getOrthogonal<OrTimer>()
                          ->getClientBehavior<CbTimerCountdownOnce>();
    // subscribe to the single countdown behavior callback
    cbsingle->onTimerTick(&StiACCycleDwell::onSingleBehaviorTickCallback
      , this);
  }
staticConfigure()
static void sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::staticConfigure () [inline], [static]
Definition at line 27 of file sti_ac_cycle_dwell.h.
  {
    configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
    configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
    configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
    configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/ac_cycle_inner_states/sti_ac_cycle_dwell.h