sm_respira_1::ac_cycle_inner_states::StiACCycleInspire Struct Reference
#include <sti_ac_cycle_inspire.h>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StiACCyclePlateau, TIMEOUT >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StiACCyclePlateau, NEXT >, Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StiACCycleLoop, PREVIOUS >, Transition< EvKeyPressY< CbDefaultKeyboardBehavior, OrKeyboard >, MsLeakyLung, ABORT >, Transition< EvKeyPressZ< CbDefaultKeyboardBehavior, OrKeyboard >, MsPatientObstruction, ABORT > > reactions
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_ac_cycle_inspire.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StiACCyclePlateau, TIMEOUT>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StiACCyclePlateau, NEXT>, Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StiACCycleLoop, PREVIOUS>, Transition<EvKeyPressY<CbDefaultKeyboardBehavior, OrKeyboard>, MsLeakyLung, ABORT>, Transition<EvKeyPressZ<CbDefaultKeyboardBehavior, OrKeyboard>, MsPatientObstruction, ABORT> > sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::reactions
Definition at line 26 of file sti_ac_cycle_inspire.h.
Member Function Documentation
onEntry()
void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onEntry () [inline]
Definition at line 54 of file sti_ac_cycle_inspire.h.
  {
    ROS_INFO("On Entry!");
  }
onExit()
void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onExit () [inline]
Definition at line 59 of file sti_ac_cycle_inspire.h.
  {
    ROS_INFO("On Exit!");
  }
onSingleBehaviorTickCallback()
void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onSingleBehaviorTickCallback () [inline]
Definition at line 69 of file sti_ac_cycle_inspire.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("single behavior tick!");
  }
onTimerClientTickCallback()
void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onTimerClientTickCallback () [inline]
Definition at line 64 of file sti_ac_cycle_inspire.h.
Referenced by runtimeConfigure().
  {
    ROS_INFO("timer client tick!");
  }
runtimeConfigure()
void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::runtimeConfigure () [inline]
Definition at line 37 of file sti_ac_cycle_inspire.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
  {
    // get reference to the client
    ClRosTimer *client;
    this->requiresClient(client);
    // subscribe to the timer client callback
    client->onTimerTick(&StiACCycleInspire::onTimerClientTickCallback
      , this);
    // getting reference to the single countdown behavior
    auto *cbsingle = this->getOrthogonal<OrTimer>()
                         ->getClientBehavior<CbTimerCountdownOnce>();
    // subscribe to the single countdown behavior callback
    cbsingle->onTimerTick(&StiACCycleInspire::onSingleBehaviorTickCallback
      , this);
  }
staticConfigure()
static void sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::staticConfigure () [inline], [static]
Definition at line 29 of file sti_ac_cycle_inspire.h.
  {
    configure_orthogonal<OrTimer, CbTimerCountdownOnce>(40);
    configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
    configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
    configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/ac_cycle_inner_states/sti_ac_cycle_inspire.h