sm_pr2_plugs::StProcessRechargeCommand Struct Reference
#include <st_process_recharge_command.h>
Classes
struct FALSE
struct TRUE
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, StNavigateToOutlet, TRUE >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StUnplug, FALSE > > reactions
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onSingleBehaviorTickCallback ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file st_process_recharge_command.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, StNavigateToOutlet, TRUE>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StUnplug, FALSE> > sm_pr2_plugs::StProcessRechargeCommand::reactions
Definition at line 18 of file st_process_recharge_command.h.
Member Function Documentation
onSingleBehaviorTickCallback()
void sm_pr2_plugs::StProcessRechargeCommand::onSingleBehaviorTickCallback () [inline]
Definition at line 49 of file st_process_recharge_command.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("single behavior tick!");
    }
onTimerClientTickCallback()
void sm_pr2_plugs::StProcessRechargeCommand::onTimerClientTickCallback () [inline]
Definition at line 44 of file st_process_recharge_command.h.
Referenced by runtimeConfigure().
    {
        ROS_INFO("timer client tick!");
    }
runtimeConfigure()
void sm_pr2_plugs::StProcessRechargeCommand::runtimeConfigure () [inline]
Definition at line 27 of file st_process_recharge_command.h.
References onSingleBehaviorTickCallback(), onTimerClientTickCallback(), and smacc::ISmaccState::requiresClient().
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&StProcessRechargeCommand::onTimerClientTickCallback
      , this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&
      StProcessRechargeCommand::onSingleBehaviorTickCallback
      , this);
    }
staticConfigure()
static void sm_pr2_plugs::StProcessRechargeCommand::staticConfigure () [inline], [static]
Definition at line 21 of file st_process_recharge_command.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
        configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_pr2_plugs/include/sm_pr2_plugs/states/st_process_recharge_command.h