sm_moveit_3::cl_perception_system::ClPerceptionSystem Class Reference
#include <cl_perception_system.h>
Public Member Functions
ClPerceptionSystem ()
virtual ~ClPerceptionSystem ()
virtual void initialize () override
void simulatedLinkStateCallback (const gazebo_msgs::LinkStates &linksmsg)
void propagateLinkStatesToTf (const gazebo_msgs::LinkStates &linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > &transforms)
void nextCube ()
void retryCubeAfterFail ()
void tryCaptureInitialCubePoses ()
virtual void update () override
RobotProcessStatus getCurrentTable ()
geometry_msgs::PoseStamped decidePickCubePose ()
geometry_msgs::PoseStamped decidePlacePose ()
Public Attributes
cl_move_base_z::Pose * detectedCubePose0
cl_move_base_z::Pose * detectedCubePose1
cl_move_base_z::Pose * detectedCubePose2
boost::optional< geometry_msgs::PoseStamped > originalCube0Pose
boost::optional< geometry_msgs::PoseStamped > originalCube1Pose
boost::optional< geometry_msgs::PoseStamped > originalCube2Pose
boost::optional< geometry_msgs::PoseStamped > cube0DestinationInTable1
boost::optional< geometry_msgs::PoseStamped > cube1DestinationInTable0
boost::optional< geometry_msgs::PoseStamped > cube2DestinationInTable1
ros::Time startTime
ros::Duration readDelay
int decissionsCount
int currentCube = 0
tf::TransformListener tfListener_
tf::TransformBroadcaster tfBroadcaster_
ros::Subscriber gazeboStateSubscriber_
ros::Time lastUpdateStamp_
ros::Duration updatePeriod_
bool tableCollision_
bool cubeCollision_
moveit::planning_interface::PlanningSceneInterface * planningInterface_
Additional Inherited Members
Detailed Description
Definition at line 26 of file cl_perception_system.h.
Constructor & Destructor Documentation
ClPerceptionSystem()
sm_moveit_3::cl_perception_system::ClPerceptionSystem::ClPerceptionSystem () [inline]
Definition at line 56 of file cl_perception_system.h.
  {
    startTime = ros::Time::now();
    readDelay = ros::Duration(5);
    decissionsCount = 0;
    lastUpdateStamp_ = ros::Time::now();
    updatePeriod_ = ros::Duration(10);
    tableCollision_ = true;
    cubeCollision_ = false;
  }
 ClPerceptionSystem()
virtual sm_moveit_3::cl_perception_system::ClPerceptionSystem::~ClPerceptionSystem () [inline], [virtual]
Definition at line 68 of file cl_perception_system.h.
  {
  }
Member Function Documentation
decidePickCubePose()
geometry_msgs::PoseStamped sm_moveit_3::cl_perception_system::ClPerceptionSystem::decidePickCubePose () [inline]
Definition at line 243 of file cl_perception_system.h.
References cl_move_base_z::Pose::toPoseStampedMsg(), and cl_move_base_z::Pose::waitTransformUpdate().
  {
    cl_move_base_z::Pose *targetObjectPose;
    if (currentCube == 0)
    {
      targetObjectPose = detectedCubePose0;
    }
    else if (currentCube == 1)
    {
      targetObjectPose = detectedCubePose1;
    }
    else
    {
      targetObjectPose = detectedCubePose2;
    }
    targetObjectPose->waitTransformUpdate();
    return targetObjectPose->toPoseStampedMsg();
  }
decidePlacePose()
geometry_msgs::PoseStamped sm_moveit_3::cl_perception_system::ClPerceptionSystem::decidePlacePose () [inline]
Definition at line 264 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), and cl_move_base_z::Pose::toPoseMsg().
  {
    cl_move_base_z::ClMoveBaseZ *moveBaseclient;
    this->requiresClient(moveBaseclient);
    auto pose = moveBaseclient->getComponent<cl_move_base_z::Pose>();
    auto currentPose = pose->toPoseMsg();
    int tableIndex = 0;
    if (currentPose.position.x > -0.2) // negative side
    {
      ROS_INFO("[StOpenGripper] locate cube in table 0");
      tableIndex = 0;
    }
    else
    {
      ROS_INFO("[StOpenGripper] locate cube in table 1");
      tableIndex = 1;
    }
    decissionsCount++;
    if (tableIndex == 0)
    {
      ROS_INFO("[Perception System] deciding cube target in table 0");
      if (currentCube == 0)
      {
        ROS_INFO("[Perception System] deciding cube target 0 in table 0");
        return *originalCube0Pose;
      }
      else if (currentCube == 1)
      {
        ROS_INFO("[Perception System] deciding cube target 1 in table 0");
        return *cube1DestinationInTable0;
      }
      else
      {
        ROS_INFO("[Perception System] deciding cube target 2 in table 0");
        return *originalCube2Pose;
      }
    }
    else
    {
      if (currentCube == 0)
      {
        ROS_INFO("[Perception System] deciding cube target 0 in table 1");
        return *cube0DestinationInTable1;
      }
      else if (currentCube == 1)
      {
        ROS_INFO("[Perception System] deciding cube target 1 in table 1");
        return *originalCube1Pose;
      }
      else
      {
        ROS_INFO("[Perception System] deciding cube target 2 in table 1");
        return *cube2DestinationInTable1;
      }
    }
  }
getCurrentTable()
RobotProcessStatus sm_moveit_3::cl_perception_system::ClPerceptionSystem::getCurrentTable () [inline]
Definition at line 227 of file cl_perception_system.h.
References smacc::ISmaccClient::getComponent(), sm_moveit_3::cl_perception_system::ONTHEWAY, sm_moveit_3::cl_perception_system::TABLE0, sm_moveit_3::cl_perception_system::TABLE1, and cl_move_base_z::Pose::toPoseMsg().
  {
    cl_move_base_z::ClMoveBaseZ *moveBaseclient;
    this->requiresClient(moveBaseclient);
    auto pose = moveBaseclient->getComponent<cl_move_base_z::Pose>();
    auto currentPose = pose->toPoseMsg();
    int tableIndex = 0;
    if (currentPose.position.x > -0.2)
      return RobotProcessStatus::TABLE0;
    else if (currentPose.position.x < -0.8)
      return RobotProcessStatus::TABLE1;
    else
      return RobotProcessStatus::ONTHEWAY;
  }
initialize()
virtual void sm_moveit_3::cl_perception_system::ClPerceptionSystem::initialize () [inline], [override], [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 72 of file cl_perception_system.h.
References moveit_z_client::ClMoveGroup::planningSceneInterface, and simulatedLinkStateCallback().
  {
    ros::NodeHandle nh;
    gazeboStateSubscriber_ =
        nh.subscribe("/gazebo/link_states", 1, &
      ClPerceptionSystem::simulatedLinkStateCallback, this);
    
    moveit_z_client::ClMoveGroup* movegroupclient;
    requiresClient(movegroupclient);
    planningInterface_ = &movegroupclient->
      planningSceneInterface;
  }
nextCube()
void sm_moveit_3::cl_perception_system::ClPerceptionSystem::nextCube () [inline]
Definition at line 168 of file cl_perception_system.h.
  {
    currentCube = (currentCube + 1) % 3;
    ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
  }
propagateLinkStatesToTf()
void sm_moveit_3::cl_perception_system::ClPerceptionSystem::propagateLinkStatesToTf (const gazebo_msgs::LinkStates & linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > & transforms) [inline]
Definition at line 133 of file cl_perception_system.h.
  {
    transforms.clear();
    int i = 0;
    std::vector<geometry_msgs::Pose> filteredLinkPoses;
    for (auto &b : linksmsg.pose)
    {
      auto linkname = linksmsg.name[i];
      if (linkname.find(linkNameFilter) != std::string::npos)
        filteredLinkPoses.push_back(b);
      i++;
    }
    i = 0;
    for (auto &cubepose : filteredLinkPoses)
    {
      tf::Pose tfpose;
      tf::poseMsgToTF(cubepose, tfpose);
      tf::StampedTransform transform;
      transform.setOrigin(tfpose.getOrigin());
      transform.setRotation(tfpose.getRotation());
      transform.frame_id_ = globalFrame;
      transform.child_frame_id_ = objectPrefix + std::to_string(i);
      transform.stamp_ = ros::Time::now();
      tfBroadcaster_.sendTransform(transform);
      i++;
      transforms.push_back(transform);
    }
  }
retryCubeAfterFail()
void sm_moveit_3::cl_perception_system::ClPerceptionSystem::retryCubeAfterFail () [inline]
Definition at line 174 of file cl_perception_system.h.
  {
    currentCube = (currentCube - 1) % 3;
    ROS_INFO_STREAM("[Perception system] next cube: " << currentCube);
  }
simulatedLinkStateCallback()
void sm_moveit_3::cl_perception_system::ClPerceptionSystem::simulatedLinkStateCallback (const gazebo_msgs::LinkStates & linksmsg) [inline]
Definition at line 84 of file cl_perception_system.h.
Referenced by initialize().
  {
      std::vector<tf::StampedTransform> cubeTransforms;
      this->propagateLinkStatesToTf(linksmsg, "cube", "cube_", "map", cubeTransforms
      );
      std::vector<tf::StampedTransform> tableTransforms;
      this->propagateLinkStatesToTf(linksmsg, "table", "table_", "map",
      tableTransforms);
      auto ellapsed = ros::Time::now() - this->lastUpdateStamp_;
      if (ellapsed > updatePeriod_)
      {
          ROS_DEBUG("Updating planning scene perception");
          auto attachedObjects = planningInterface_->getAttachedObjects();
          bool hasCubeAttached = false;
          for(auto& k : attachedObjects)
          {
              if(k.first.find("cube")!= std::string::npos)
              {
                 hasCubeAttached = true;
                 break;
              }
          }
        if(tableCollision_ && ! hasCubeAttached)
        {
        // for i, table_transf in enumerate(table_transforms):
        // #self.planning_scene.removeCollisionObject("table_" + str(i))
        // thickness = 0.12
        // pos = table_transf[0]
        // self.planning_scene.addBox(
        // "table_" + str(i), 1.2, 1.3, 0.001 + thickness, pos[0], pos[1], 0.7 -
       thickness*0.5) # 0.68
        }
        if(cubeCollision_ && ! hasCubeAttached)
        {
        // for i, cube_transf in enumerate(cube_transforms):
        // #self.planning_scene.removeCollisionObject("cube_" + str(i))
        // pos = cube_transf[0]
        // self.planning_scene.addCube(
        // "cube_" + str(i), 0.06, pos[0], pos[1], pos[2])
        // #self.cube_collision = False
        }
      }
  }
tryCaptureInitialCubePoses()
void sm_moveit_3::cl_perception_system::ClPerceptionSystem::tryCaptureInitialCubePoses () [inline]
Definition at line 180 of file cl_perception_system.h.
References cl_move_base_z::Pose::isInitialized, and cl_move_base_z::Pose::toPoseStampedMsg().
  {
    auto ellapsed = ros::Time::now() - startTime;
    bool applyUpdate = ellapsed > readDelay;
    if (applyUpdate)
    {
      if (!originalCube0Pose && detectedCubePose0->
      isInitialized)
      {
        originalCube0Pose = detectedCubePose0->
      toPoseStampedMsg();
        cube0DestinationInTable1 = originalCube0Pose;
        (*cube0DestinationInTable1).pose.position.x = -originalCube0Pose->pose.position.x;
        ROS_INFO_STREAM("[Perception system] Original Cube 0 Pose captured" <<
      originalCube0Pose->pose);
        ROS_INFO_STREAM("[Perception system] Cube 0 Pose table 1 destination" << (*
      cube0DestinationInTable1));
      }
      if (!originalCube1Pose && detectedCubePose1->
      isInitialized)
      {
        originalCube1Pose = detectedCubePose1->
      toPoseStampedMsg();
        cube1DestinationInTable0 = originalCube1Pose;
        (*cube1DestinationInTable0).pose.position.x = -originalCube1Pose->pose.position.x;
        ROS_INFO_STREAM("[Perception system] Original Cube 1 Pose captured" <<
      originalCube1Pose->pose);
        ROS_INFO_STREAM("[Perception system] Cube 1 Pose table 0 destination" << (*
      cube1DestinationInTable0));
      }
      if (!originalCube2Pose && detectedCubePose2->
      isInitialized)
      {
        originalCube2Pose = detectedCubePose2->
      toPoseStampedMsg();
        cube2DestinationInTable1 = originalCube2Pose;
        (*cube2DestinationInTable1).pose.position.x = -originalCube2Pose->pose.position.x;
        ROS_INFO_STREAM("[Perception system] Original Cube 2 Pose captured" <<
      originalCube2Pose->pose);
        ROS_INFO_STREAM("[Perception system] Cube 2 Pose table 1 destination" << (*
      cube2DestinationInTable1));
      }
    }
  }
update()
virtual void sm_moveit_3::cl_perception_system::ClPerceptionSystem::update () [inline], [override], [virtual]
Implements smacc::ISmaccUpdatable.
Definition at line 222 of file cl_perception_system.h.
  {
    tryCaptureInitialCubePoses();
  }
Member Data Documentation
cube0DestinationInTable1
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::cube0DestinationInTable1
Definition at line 37 of file cl_perception_system.h.
cube1DestinationInTable0
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::cube1DestinationInTable0
Definition at line 38 of file cl_perception_system.h.
cube2DestinationInTable1
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::cube2DestinationInTable1
Definition at line 39 of file cl_perception_system.h.
cubeCollision_
bool sm_moveit_3::cl_perception_system::ClPerceptionSystem::cubeCollision_
Definition at line 53 of file cl_perception_system.h.
currentCube
int sm_moveit_3::cl_perception_system::ClPerceptionSystem::currentCube = 0
Definition at line 45 of file cl_perception_system.h.
decissionsCount
int sm_moveit_3::cl_perception_system::ClPerceptionSystem::decissionsCount
Definition at line 44 of file cl_perception_system.h.
detectedCubePose0
cl_move_base_z::Pose* sm_moveit_3::cl_perception_system::ClPerceptionSystem::detectedCubePose0
Definition at line 29 of file cl_perception_system.h.
detectedCubePose1
cl_move_base_z::Pose* sm_moveit_3::cl_perception_system::ClPerceptionSystem::detectedCubePose1
Definition at line 30 of file cl_perception_system.h.
detectedCubePose2
cl_move_base_z::Pose* sm_moveit_3::cl_perception_system::ClPerceptionSystem::detectedCubePose2
Definition at line 31 of file cl_perception_system.h.
gazeboStateSubscriber_
ros::Subscriber sm_moveit_3::cl_perception_system::ClPerceptionSystem::gazeboStateSubscriber_
Definition at line 49 of file cl_perception_system.h.
lastUpdateStamp_
ros::Time sm_moveit_3::cl_perception_system::ClPerceptionSystem::lastUpdateStamp_
Definition at line 50 of file cl_perception_system.h.
originalCube0Pose
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::originalCube0Pose
Definition at line 33 of file cl_perception_system.h.
originalCube1Pose
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::originalCube1Pose
Definition at line 34 of file cl_perception_system.h.
originalCube2Pose
boost::optional<geometry_msgs::PoseStamped> sm_moveit_3::cl_perception_system::ClPerceptionSystem::originalCube2Pose
Definition at line 35 of file cl_perception_system.h.
planningInterface_
moveit::planning_interface::PlanningSceneInterface* sm_moveit_3::cl_perception_system::ClPerceptionSystem::planningInterface_
Definition at line 54 of file cl_perception_system.h.
readDelay
ros::Duration sm_moveit_3::cl_perception_system::ClPerceptionSystem::readDelay
Definition at line 42 of file cl_perception_system.h.
startTime
ros::Time sm_moveit_3::cl_perception_system::ClPerceptionSystem::startTime
Definition at line 41 of file cl_perception_system.h.
tableCollision_
bool sm_moveit_3::cl_perception_system::ClPerceptionSystem::tableCollision_
Definition at line 52 of file cl_perception_system.h.
tfBroadcaster_
tf::TransformBroadcaster sm_moveit_3::cl_perception_system::ClPerceptionSystem::tfBroadcaster_
Definition at line 48 of file cl_perception_system.h.
tfListener_
tf::TransformListener sm_moveit_3::cl_perception_system::ClPerceptionSystem::tfListener_
Definition at line 47 of file cl_perception_system.h.
updatePeriod_
ros::Duration sm_moveit_3::cl_perception_system::ClPerceptionSystem::updatePeriod_
Definition at line 51 of file cl_perception_system.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_moveit_3/include/sm_moveit_3/clients/perception_system_client/cl_perception_system.h