sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop Struct Reference
#include <sti_cmv_cycle_loop.h>
Public Types
typedef mpl::list< Transition< EvLoopContinue< StiCMVCycleLoop >, StiCMVCycleInspire, CONTINUELOOP > > reactions
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void staticConfigure ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file sti_cmv_cycle_loop.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<StiCMVCycleLoop>, StiCMVCycleInspire, CONTINUELOOP> > sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::reactions
Definition at line 17 of file sti_cmv_cycle_loop.h.
Member Function Documentation
loopWhileCondition()
bool sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::loopWhileCondition () [inline]
Definition at line 28 of file sti_cmv_cycle_loop.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SsCMVCycle>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
             superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
onEntry()
void sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::onEntry () [inline]
Definition at line 37 of file sti_cmv_cycle_loop.h.
References smacc::SmaccState< StiCMVCycleLoop, SsCMVCycle >::checkWhileLoopConditionAndThrowEvent(), and loopWhileCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&
      StiCMVCycleLoop::loopWhileCondition);
  }
runtimeConfigure()
void sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::runtimeConfigure () [inline]
Definition at line 24 of file sti_cmv_cycle_loop.h.
  {
  }
staticConfigure()
static void sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::staticConfigure () [inline], [static]
Definition at line 20 of file sti_cmv_cycle_loop.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_respira_1/include/sm_respira_1/states/cmv_cycle_inner_states/sti_cmv_cycle_loop.h